### ISSUE TITLE
box2d-2.1.2: Fails to build on x86_64

### ISSUE THREAD

**Issue by vanishakesswani** [haikuports/haikuports#1012]
![box2d](https://cloud.githubusercontent.com/assets/24365311/21766575/55582b28-d695-11e6-86a2-119c712f5ff5.png)

**Comment by diversys** [comment]
Looks like it wasn't linked against **/system/lib/libglut.so**. Probably some patching is needed to take care of it. Check the patchset for clues.

**Comment by diversys** [comment]
In #1025 it seems to build just fine (apart from policy error).

**Comment by korli** [comment]
Superseded by version 2.3.1
