### ISSUE TITLE
befar-4.2_beta: Fails to build on x86_64

### ISSUE THREAD

**Issue by vanishakesswani** [haikuports/haikuports#1014]
![befar](https://cloud.githubusercontent.com/assets/24365311/21766638/ac74bf2a-d695-11e6-8b96-fa4b32ab8385.png)

**Comment by diversys** [comment]
Like in #1015 there is a missing or extra quote somewhere. It would be easier for you to spot this if you start using **Pe** instead of **StyledEdit** as the former has syntax highlighting. To do that you can just open **FileTypes -> Text** and change **Preferred application**.

**Comment by korli** [comment]
Fixed
