### ISSUE TITLE
fpc: bad script shebang during creation

### ISSUE THREAD

**Issue by halamix2** [haikuports/haikuports#10140]
`fpcbuild-3.2.2/fpcsrc/compiler/cscript.pas` in `dev-lang/fpc/work-3.2.2/sources` in line 400 contains
```pascal
{$ifdef BEOS}
   AddStart('#!/boot/beos/bin/sh');
{$else}
  AddStart('#!/bin/sh');
{$endif}
```

My guess is that the if should be changed to `{$ifdef BEOS and not defined(HAIKU)}`

**Comment by halamix2** [comment]
- I might want to link this to #437, as it blocks compilation of hedgewars

**Comment by Begasus** [comment]
Didn't fix building hedgewars. :/

**Comment by halamix2** [comment]
Yeah, another error is ` Can't find unit system used by testPascalCompiler`

**Comment by Begasus** [comment]
In Terminal it's working :/
```
/Opslag/wip/hedgewars-src-1.0.2/build/hedgewars/CMakeFiles/CMakeTmp> fpc testpascalcompiler.pas 
Free Pascal Compiler version 3.2.2 [2024/02/24] for x86_64
Copyright (c) 1993-2021 by Florian Klaempfl and others
Target OS: Haiku for x86_64
Compiling testpascalcompiler.pas
Linking testpascalcompiler
3 lines compiled, 0.1 sec
```

**Comment by Begasus** [comment]
Fix merged (pushed a small change there, removed the BeOS check al together as it's not needed), detection worked with testing in hedgewars.
