### ISSUE TITLE
file_data-5.4.3 broken in HaikuDepot

### ISSUE THREAD

**Issue by syneryder** [haikuports/haikuports#10243]
I’m having problems installing file_data-5.43-1-any via the HaikuDepot program. It downloads, but during install I just get the error message:

```
 Fatal error occurred while installing package
 file_data: Failed to download package file_data ()
```

This breaks install for other applications depending on it (eg vim, Bluefish, Toot, anything that has a dependency on "file"). I've checked that my network is working, and I'm able to download and install other things from HaikuDepot. I was running hrev57650 at the time, if that's relevant.

There is a workaround (thanks to SantiagoLema in [this Haiku forum thread](https://discuss.haiku-os.org/t/file-data-broken-in-haikudepot/14800)): if I download the file_data hpkg from the haikudepot website instead, I'm able to install it manually successfully. It does give a warning about requiring *itself* as a dependency during manual install, however - could that cause the error above?

**Comment by Begasus** [comment]
Saw the post in the forum the other day in the forum, I can't check atm on the installed systems as they already got file_data installed. Will run some checks in VM's.

**Comment by Begasus** [comment]
Looks like a checksum failure?

**Comment by Begasus** [comment]
Local checksum is fine with the expected one: 
```
sha256sum /boot/system/packages/file_data-5.43-1-any.hpkg
777d0c8238b783b96b541e6e5e2a910bdb7e4e1165f0f75c05909b2ef1403c1b  /boot/system/packages/file_data-5.43-1-any.hpkg
```
