### ISSUE TITLE
upgrade autoconf on the build machines to version 2.72

### ISSUE THREAD

**Issue by jmairboeck** [haikuports/haikuports#10265]
The new texlive 2024 (see #10261) requires autoconf 2.72, and it is used in the PATCH function of texlive_core.

Presumably because of haikuports/haikuporter#168, the version installed on the build host (which is currently 2.71) is used instead of the newer version available in the repository.

**Comment by korli** [comment]
IMO using autoconf in PATCH looks suspicious. An additional patch can be added in the patchset

**Comment by jmairboeck** [comment]
In the patchset, I am patching configure.ac files and then run autoconf in the PATCH function. Should I move that to BUILD instead?

I wrote it like this as BUILD shouldn't modify source files, that is what PATCH is for, IMHO.

**Comment by korli** [comment]
> In the patchset, I am patching configure.ac files and then run autoconf in the PATCH function. Should I move that to BUILD instead?

Yes.

> I wrote it like this as BUILD shouldn't modify source files, that is what PATCH is for, IMHO.

Generated scripts are not source files.

**Comment by jmairboeck** [comment]
I moved the autoconf invocation in texlive_core to BUILD in e2f4699.

I leave this open for now because the general issue is still relevant. Although I suppose this can now wait until beta 5 arrives, when an upgrade of the builders is due anyway.

The real fix would be the haikuporter improvement mentioned above, to allow anything to be used in PATCH.

**Comment by korli** [comment]
I don't understand why this issue is still open.
