### ISSUE TITLE
Qt5 package is missing Deskbar links on x86_64

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#1027]
Package version is qt5-5.5.1-4-x86_64.hpkg

**Comment by diversys** [comment]
Probably because these binaries are missing from the package:

	addAppDeskbarSymlink $binDir/assistant "Qt/Assistant"
	addAppDeskbarSymlink $binDir/designer "Qt/Designer"
	addAppDeskbarSymlink $binDir/linguist "Qt/Lingist"
	addAppDeskbarSymlink $binDir/qdbusviewer "Qt/Qt D-Bus Viewer"
	addAppDeskbarSymlink $binDir/qmlviewer "Qt/QML Viewer"
	addAppDeskbarSymlink $binDir/qhelpconverter "Qt/Qt Help Converter"

**Comment by korli** [comment]
I think these binaries are in the _devel package. Why specific to x86_64?

**Comment by diversys** [comment]
Oh, didn't notice it! Sorry for the noise.
