### ISSUE TITLE
bebook: checksum mismatch

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#10297]
revision: 2b9c6061e94559930fb99275a8a9e6b328f72d6d

```
Validating checksum of bebook_20081026.zip
Error: Expected SHA-256: 8bd4836744c2542567b95b3b1cacf60333562e178d5cbcf3aa0a69a02d2f7a28
Error: Found SHA-256:    7c28184dadf58c82ae41d8f5a6c33f6f573f3c3123206c7e09ffaec5edd1b497
```

**Comment by Begasus** [comment]
How is vim related to bebook? (also the removed recipes didn't supply any packages anymore on the depot).

**Comment by Begasus** [comment]
ah! no wonder I couldn't find it :) thanks for the clarification!

**Comment by Begasus** [comment]
The archive seems to be hacked? Opening it opens a page in WebPositive! Maybe we should disable this untill this is resolved?

**Comment by Begasus** [comment]
Nothing (beside eventualy disable those recipes - bad experience for users that would like to try them out) we can do here, guess this is up to HaikuInc?

**Comment by pulkomandy** [comment]
Yes, I think the domain and host for this are handled by Haiku inc. I hope they can restore access to that machine as it had quite a lot of "historical" content that should be archived before shutting it down :/
