### ISSUE TITLE
wine-bin 7.9-1 error:24 partial write 64

### ISSUE THREAD

**Issue by bbjimmy** [haikuports/haikuports#10301]
x86_64 hrev57689  attempt to launch notepad, WinMine, WineConsole, or Regedit from a Terminal:

~/Desktop> /boot/system/bin/notepad
wine client error:24: partial write 64

etc.

**Comment by waddlesplash** [comment]
CC @X547.

**Comment by X547** [comment]
Something regression caused by kernel sockets changes?

**Comment by korli** [comment]
it would be nice to know one last working hrev before hrev57689.

**Comment by waddlesplash** [comment]
Fixed in https://github.com/haiku/haiku/commit/20ac27def64f92a5003e04e2d40d4f9647fc183c.
