### ISSUE TITLE
Gittyup: error while attempting a connection with SSH

### ISSUE THREAD

**Issue by nexus6-haiku** [haikuports/haikuports#10336]
I get this error while opening a private repo that I have created to test Genio's Git capabilities:

Clone - git@github.com:nexus6-haiku/TestPrivateGit.git
Failed to clone into '/boot/home/TestPrivateGit' - failed to start SSH session: Failed getting banner

This is the very same error I get in Genio (SSH is currently disabled as we were not able to fix it).
Any thoughts? Is there a problem in libgit2 or in libssh2, maybe?

**Comment by augiedoggie** [comment]
I may be remembering when I was first testing gittyup before creating the recipe.  I was using the git submodules for the ssh/git libraries instead of the system ones.  I'll see if I can find some time to look at it.

**Comment by nexus6-haiku** [comment]
Libssh2 is quite old now, isn't it?
My gut feeling is that libssh2 might be the culprit but I had not enough time to investigate! Let me know!
