### ISSUE TITLE
Telegram: Missing symbol _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate

### ISSUE THREAD

**Issue by nexus6-haiku** [haikuports/haikuports#10334]
The error occurred after the last update to hrev57704 (x86_64).
Telegram version: telegram_desktop-4.16.2-1
Previous versions of Telegram don't work after the upgrade either (down to 4.14)

**Comment by threedeyes** [comment]
The process of upgrading Qt to version 6.7 is not yet complete. I will finish it today. Please wait until it is complete.

**Comment by threedeyes** [comment]
Fixed in https://github.com/haikuports/haikuports/commit/62663cc6a91b8a7b69003ad122b5dc03ab05819f
