### ISSUE TITLE
Audacity: stability issues

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#10355]
Audacity 3.4.2-2

See: https://discuss.haiku-os.org/t/any-stable-version-of-audacity-how-to-install/14939

Set build level for release build.

**Comment by Begasus** [comment]
Already replied to the topic on the forum, will cp it here too, but seems it's broken (at least I can't launch/get it to work here):
```
Even when setting this define on in the build process Audacity isn’t launching correct, nothing pops up in Terminal, syslog (running tail on it in another tab) only shows:
2024-04-19 14:50:35 KERN: xsi_semget: key 33814980 already exist
launches but sits there showing nothing … R1B4 64bit.
```

**Comment by kenmays** [comment]
@begasus - Seems fixed on nightlies (hrev57708+).
