### ISSUE TITLE
lazarus-ide : Could not resolve symbol '_ZNK7QString12isSimpleTextEv'

### ISSUE THREAD

**Issue by yann64** [haikuports/haikuports#10361]
When starting lazarus-ide on Haiku nightly x86_64 hrev57709, the folowing error message can be seen:

```
~>lazarus-ide
runtime_loader: /boot/system/lib/libQt6Pas.so.6.2.7: Could not resolve symbol '_ZNK7QString12isSimpleTextEv'
resolve symbol "_ZNK7QString12isSimpleTextEv" returned: -2147478780
runtime_loader: /boot/system/lib/libQt6Pas.so.6.2.7: Troubles relocating: Symbol not found
```

**Comment by Begasus** [comment]
Will have a look, probably related to the Qt update, maybe it's just enough to revbump libqt6pas for this. Thanks for reporting!

**Comment by Begasus** [comment]
Should be fixed in https://github.com/haikuports/haikuports/pull/10363
Seemed CudaText also suffered from this, libqt6pas revbump/patch from upstream (partial) fixed it here.
Once ready on the buildmasters could you re-check?

**Comment by yann64** [comment]
Confirmed as fixed.

**Comment by Begasus** [comment]
Thanks for the confirmation! :)
