### ISSUE TITLE
curl: bump to 8.7.1

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#10374]
See: https://discuss.haiku-os.org/t/anyone-seen-this-network-error/14955/5
dasouth - "I saw that the ticket that I created had been reviewed, and the issue was internal to curl. I can confirm this, as I did a build of the latest curl source (8.7.1). and I had no trouble using Webpositive on that web site.

The webkit2gtk browsers however, still have the issue even with a new curl build."

**Comment by korli** [comment]
https://github.com/haikuports/haikuports/commit/9b51e5308ffd9fb001113a6f07ddadf4be6d9189
