### ISSUE TITLE
QtCreator 13.0 fails to parse /bin/clang

### ISSUE THREAD

**Issue by smallstepforman** [haikuports/haikuports#10404]
QtCreator 13.0 fails to load cmake project with the following error:

[cmake] -- The C compiler identification is Clang 17.0.6
[cmake] -- The CXX compiler identification is GNU 13.2.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - failed
[cmake] -- Check for working C compiler: /bin/clang
[cmake] -- Check for working C compiler: /bin/clang - broken
[cmake] CMake Error at /boot/system/data/cmake/Modules/CMakeTestCCompiler.cmake:67 (message):
[cmake]   The C compiler
[cmake] 
[cmake]     "/bin/clang"
[cmake] 
[cmake]   is not able to compile a simple test program.
[cmake] 
[cmake]   It fails with the following output:
[cmake] 
[cmake]     Change Dir: '/boot/home/Development/Gallery/build/Desktop-Debug/CMakeFiles/CMakeScratch/TryCompile-ahiMXT'
[cmake]     
[cmake]     Run Build Command(s): /boot/system/bin/cmake -E env VERBOSE=1 /boot/system/bin/make -f Makefile cmTC_f205b/fast
[cmake]     /boot/system/bin/make  -f CMakeFiles/cmTC_f205b.dir/build.make CMakeFiles/cmTC_f205b.dir/build
[cmake]     make[1]: Entering directory '/boot/home/Development/Gallery/build/Desktop-Debug/CMakeFiles/CMakeScratch/TryCompile-ahiMXT'
[cmake]     Building C object CMakeFiles/cmTC_f205b.dir/testCCompiler.c.o
[cmake]     /bin/clang   -fcolor-diagnostics -MD -MT CMakeFiles/cmTC_f205b.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_f205b.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_f205b.dir/testCCompiler.c.o -c /boot/home/Development/Gallery/build/Desktop-Debug/CMakeFiles/CMakeScratch/TryCompile-ahiMXT/testCCompiler.c
[cmake]     Linking C executable cmTC_f205b
[cmake]     /boot/system/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f205b.dir/link.txt --verbose=1
[cmake]     /bin/clang CMakeFiles/cmTC_f205b.dir/testCCompiler.c.o -o cmTC_f205b 
[cmake]     clang: error: unable to execute command: Executable "ld.lld" doesn't exist!
[cmake]     clang: error: linker command failed with exit code 1 (use -v to see invocation)
[cmake]     CMakeFiles/cmTC_f205b.dir/build.make:99: recipe for target 'cmTC_f205b' failed
[cmake]     make[1]: *** [cmTC_f205b] Error 1
[cmake]     make[1]: Leaving directory '/boot/home/Development/Gallery/build/Desktop-Debug/CMakeFiles/CMakeScratch/TryCompile-ahiMXT'
[cmake]     Makefile:127: recipe for target 'cmTC_f205b/fast' failed
[cmake]     make: *** [cmTC_f205b/fast] Error 2

clang 17.0 is present (and the link /bin/clang).  Haiku hrev57719 (1.May.2024).  Previous version of QtCreator worked fine with same cmake based project files.

**Comment by korli** [comment]
have you installed cmd:ld.lld?

**Comment by smallstepforman** [comment]
That fixes the issue (llvm17_ldd).  This wasn't an issue in the past.  Thanks Korli.

**Comment by korli** [comment]
Well llvm_lld should probably be recommended when installing llvm_clang. @davidkaroly
