### ISSUE TITLE
Create recipe for libmpdec.

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#10432]
Low-priority, but leaving this here before we forget.

Python 3.x bundles a copy of [`libmpdec`](https://www.bytereef.org/mpdecimal/), but can use a system provided one via `--with-system-libmpdec`.

That flag's default value changed to `yes` for Python 3.13.0, and the bundled `libmpdec` will be [removed in 3.15.0](https://docs.python.org/3.13/whatsnew/3.13.html#build-changes).

So, considering we didn't needed it so far... we have at least a couple of years to get this one ready :-D

**Comment by Begasus** [comment]
Any magic needed here, builds pretty straightforward? :)

**Comment by Begasus** [comment]
np :) https://github.com/haikuports/haikuports/pull/10433 (need to run a 32bit build to check), tests all passed.
wget needed for pulling a zip file for the tests, maybe this could be added as SOURCE_URI_2?

**Comment by Begasus** [comment]
Build is OK on 32bit too :)
![mpdecimal-4 0 0](https://github.com/haikuports/haikuports/assets/16057090/1ddb20f6-5ecd-414c-87b8-86c279a5ac16)

**Comment by Begasus** [comment]
Done :)
