### ISSUE TITLE
qxlsx: library version mismatch

### ISSUE THREAD

**Issue by alex-w** [haikuports/haikuports#10437]
qxlsx port has version 1.4.7, but library version inside of recipe is 1.4.4: https://github.com/haikuports/haikuports/blob/4f71e3ea37886a7f4b7fa4aa3fd9e8abc3a103f7/dev-libs/qxlsx/qxlsx-1.4.7.recipe#L19

**Comment by Begasus** [comment]
libVersion isn't always the same as portVersion, in this case it's correct.
![qxlsx](https://github.com/haikuports/haikuports/assets/16057090/8ec10a9a-1394-482e-9c8e-d43d5480f3cb)

**Comment by Begasus** [comment]
Looking at the Arch content it looks correct also?

https://archlinux.org/packages/extra/x86_64/qxlsx-qt6/
```
usr/lib/libQXlsxQt6.so
usr/lib/libQXlsxQt6.so.0.1.4.4
usr/lib/libQXlsxQt6.so.1.4.4
```

**Comment by alex-w** [comment]
It's interesting - cmake script for qxlsx has definition 1.4.4 as version of qxlsx, but release page has 1.4.7 as version of package. At least, this issue in not related to Haiku and Haiku ports. :)

**Comment by Begasus** [comment]
No problem, better safe then sorry (we're all human) :) Thanks for reporting. +1
