### ISSUE TITLE
ld.lld: error: unknown emulation: elf_x86_64_haiku

### ISSUE THREAD

**Issue by Zardshard** [haikuports/haikuports#10445]
Compiling a program with gcc using the lld linker fails with the error

```
ld.lld: error: unknown emulation: elf_x86_64_haiku
collect2: error: ld returned 1 exit status
```

### Reproducing the error

Take a simple main.cpp, for example

```c++
int main() {
     return 0;
}
```

and compile it with `gcc main.cpp -o main -fuse-ld=lld`.

### Workaround

For those stumbling on my issue before it's resolved (which I suspect will take a while), just add `-Wl,-m,elf_x86_64` to the compiler command line. This was tested on a large project (HaikuWebKit) and it worked without issue.

### Version information

**gcc:** 13.2.0
**lld:** llvm17_lld. I observed similar behaviour with llvm16_lld and llvm12_lld. I didn't test llvm9_lld.
**haiku:** hrev57728 on the nightlies

**Comment by threedeyes** [comment]
From 03e922e75733ac16c3081bb0a48bbcb0f6f58dfa Mon Sep 17 00:00:00 2001
From: Gerasim Troeglazov <3dEyes@gmail.com>
Date: Tue, 9 Apr 2024 23:06:28 +1000
Subject: Add haiku gcc targets


diff --git a/lld/ELF/Driver.cpp b/lld/ELF/Driver.cpp
index 7e2a72a..73640c0 100644
--- a/lld/ELF/Driver.cpp
+++ b/lld/ELF/Driver.cpp
@@ -172,8 +172,8 @@ static std::tuple<ELFKind, uint16_t, uint8_t> parseEmulation(StringRef emul) {
           .Case("elf64lriscv", {ELF64LEKind, EM_RISCV})
           .Case("elf64ppc", {ELF64BEKind, EM_PPC64})
           .Case("elf64lppc", {ELF64LEKind, EM_PPC64})
-          .Cases("elf_amd64", "elf_x86_64", {ELF64LEKind, EM_X86_64})
-          .Case("elf_i386", {ELF32LEKind, EM_386})
+          .Cases("elf_amd64", "elf_x86_64", "elf_x86_64_haiku", {ELF64LEKind, EM_X86_64})
+          .Cases("elf_i386", "elf_i386_haiku", {ELF32LEKind, EM_386})
           .Case("elf_iamcu", {ELF32LEKind, EM_IAMCU})
           .Case("elf64_sparc", {ELF64BEKind, EM_SPARCV9})
           .Case("msp430elf", {ELF32LEKind, EM_MSP430})
-- 
2.43.2

**Comment by threedeyes** [comment]
`From 03e922e75733ac16c3081bb0a48bbcb0f6f58dfa Mon Sep 17 00:00:00 2001
From: Gerasim Troeglazov <3dEyes@gmail.com>
Date: Tue, 9 Apr 2024 23:06:28 +1000
Subject: Add haiku gcc targets


diff --git a/lld/ELF/Driver.cpp b/lld/ELF/Driver.cpp
index 7e2a72a..73640c0 100644
--- a/lld/ELF/Driver.cpp
+++ b/lld/ELF/Driver.cpp
@@ -172,8 +172,8 @@ static std::tuple<ELFKind, uint16_t, uint8_t> parseEmulation(StringRef emul) {
           .Case("elf64lriscv", {ELF64LEKind, EM_RISCV})
           .Case("elf64ppc", {ELF64BEKind, EM_PPC64})
           .Case("elf64lppc", {ELF64LEKind, EM_PPC64})
-          .Cases("elf_amd64", "elf_x86_64", {ELF64LEKind, EM_X86_64})
-          .Case("elf_i386", {ELF32LEKind, EM_386})
+          .Cases("elf_amd64", "elf_x86_64", "elf_x86_64_haiku", {ELF64LEKind, EM_X86_64})
+          .Cases("elf_i386", "elf_i386_haiku", {ELF32LEKind, EM_386})
           .Case("elf_iamcu", {ELF32LEKind, EM_IAMCU})
           .Case("elf64_sparc", {ELF64BEKind, EM_SPARCV9})
           .Case("msp430elf", {ELF32LEKind, EM_MSP430})
-- 
2.43.2
`

**Comment by threedeyes** [comment]
```
From 03e922e75733ac16c3081bb0a48bbcb0f6f58dfa Mon Sep 17 00:00:00 2001
From: Gerasim Troeglazov <3dEyes@gmail.com>
Date: Tue, 9 Apr 2024 23:06:28 +1000
Subject: Add haiku gcc targets


diff --git a/lld/ELF/Driver.cpp b/lld/ELF/Driver.cpp
index 7e2a72a..73640c0 100644
--- a/lld/ELF/Driver.cpp
+++ b/lld/ELF/Driver.cpp
@@ -172,8 +172,8 @@ static std::tuple<ELFKind, uint16_t, uint8_t> parseEmulation(StringRef emul) {
           .Case("elf64lriscv", {ELF64LEKind, EM_RISCV})
           .Case("elf64ppc", {ELF64BEKind, EM_PPC64})
           .Case("elf64lppc", {ELF64LEKind, EM_PPC64})
-          .Cases("elf_amd64", "elf_x86_64", {ELF64LEKind, EM_X86_64})
-          .Case("elf_i386", {ELF32LEKind, EM_386})
+          .Cases("elf_amd64", "elf_x86_64", "elf_x86_64_haiku", {ELF64LEKind, EM_X86_64})
+          .Cases("elf_i386", "elf_i386_haiku", {ELF32LEKind, EM_386})
           .Case("elf_iamcu", {ELF32LEKind, EM_IAMCU})
           .Case("elf64_sparc", {ELF64BEKind, EM_SPARCV9})
           .Case("msp430elf", {ELF32LEKind, EM_MSP430})
-- 
2.43.2
```

**Comment by pulkomandy** [comment]
This is fixed in llvm 17 but still broken in llvm 18 it seems?

**Comment by pulkomandy** [comment]
@davidkaroly it looks like you made the update to llvm 18, a lot of patches from llvm 17 are not present in the llvm 18 patchset, were they all upstreamed? I will at least re-add this one.
