### ISSUE TITLE
Zeal: command line arguments are ignored if Zeal is already opened or minimized to tray

### ISSUE THREAD

**Issue by nexus6-haiku** [haikuports/haikuports#10441]
Passing parameters to Zeal with an existing instance running is vital for implementing an integration with an IDE/Editor.
Unfortunately Zeal does not implement this behaviour correctly.

Steps to reproduce:

1. run Zeal and minimize it via "Minimize to Tray" menu item in the Deskbar
2. Open a Terminal
3. Input "`Zeal BView`"
4. Nothing happens

The problem occurs also if the window is shown on screen:

1. run Zeal 
2. Open a Terminal
3. Input "`Zeal BView`"
4. Nothing happens

If the window is on screen and no parameters are passed, Zeal becomes the frontmost window:

1. run Zeal 
2. Open a Terminal
3. Input "`Zeal`"
4. Zeal's window is brought to front

The expected behaviour is:

1. Zeal is invoked from Terminal
2. its window is shown if hidden
3. it is brough to front
4. any command line argument is forwarded to the running instance.

If Zeal is not running, it should be run first then proceed with step 2.

**Comment by augiedoggie** [comment]
It seems to work if I undo part of the patch by @threedeyes that controls the app singleton behavior and then change the executable type in the rdef file to `B_MULTIPLE_LAUNCH`.  I'm not familiar enough with the Qt stuff to know if this is the proper solution to the problem though.

**Comment by nexus6-haiku** [comment]
I’m not familiar at all with Qt but I ve noticed that the arguments should be forwarded to the running instance although it does not work as expected.
Which parts have you removed?
There should be only one instance running so `B_MULTIPLE_LAUNCH` does not seem right to me.
What about single launch?

**Comment by augiedoggie** [comment]
I removed both of the `#ifndef Q_OS_HAIKU` modifications to the main.cpp file.  It's the first changes in the [patchset](https://github.com/haikuports/haikuports/blob/master/app-doc/zeal/patches/zeal-0.7.0.patchset).  I haven't tried it with B_SINGLE_LAUNCH.  I assumed that B_MULTIPLE_LAUNCH would have a better chance of success since it lets the app handle the singleton code as it normally would.

**Comment by threedeyes** [comment]
> It seems to work if I undo part of the patch by @threedeyes that controls the app singleton behavior and then change the executable type in the rdef file to `B_MULTIPLE_LAUNCH`.  I'm not familiar enough with the Qt stuff to know if this is the proper solution to the problem though.

This patch was made a long time ago when QSingleApplication was not working correctly on the Haiku. Now it can be removed and made as it should be.
