### ISSUE TITLE
Trash can support for Tux Paint

### ISSUE THREAD

**Issue by billkendrick** [haikuports/haikuports#10568]
Tux Paint acts as a self-contained drawing environment for children, and to that end offers a unique and simplified file management interface via the "Open" dialog.  That dialog offers an "Erase" option to delete previously-saved drawings.

Nowadays, this causes drawings to land in the user's "Trash", so they can be recovered later on most desktop environments where Tux Paint runs: Freedesktop.org environments (like KDE on Linux), Windows, and macOS.  However, under Haiku the file is still simply deleted outright via an `unlink()` call (see the `#define UNLINK_ONLY` in `tuxpaint.c`).

Supporting Haiku's desktop environment's trash can would be great.  For history, see: https://sourceforge.net/p/tuxpaint/feature-requests/148/

**Comment by korli** [comment]
@billkendrick Please reuse this [trash](https://github.com/haiku/haiku/blob/3e910e720f3408a2ccf7dae9019621a390f3527b/src/bin/trash.cpp#L55) function. Should be straightforward.

**Comment by billkendrick** [comment]
> @billkendrick Please reuse this [trash](https://github.com/haiku/haiku/blob/3e910e720f3408a2ccf7dae9019621a390f3527b/src/bin/trash.cpp#L55) function. Should be straightforward.

Thank you!  @Begasus I have dropped something in, but I cannot build for, or test on, Haiku... so I'm hoping you can do any final tweaks to get it building and confirm it works. :)

https://sourceforge.net/p/tuxpaint/tuxpaint/ci/3c5303563a506a8a9066ae26c2bf072655ce4826/

Thanks!

**Comment by Begasus** [comment]
@billkendrick build failed with undefined reference to 'haiku_trash':
```
...Linking Tux Paint...
cc  -O2 -g -ffast-math -W -Wall -fno-common -ffloat-store -fvisibility=hidden -Wcast-align -Wredundant-decls -Wbad-function-cast -Wwrite-strings -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wstrict-aliasing=2 -I/packages/pango-1.50.14-2/.self/develop/headers/pango-1.0 -I/packages/glib2-2.78.0-1/.self/develop/headers -I/packages/fribidi-1.0.13-1/.self/develop/headers/fribidi -I/packages/cairo1.18-1.18.0-1/.self/develop/headers/cairo -I/packages/fontconfig-2.13.96-2/.self/develop/headers -I/packages/libxml2-2.12.5-1/.self/develop/headers/libxml2 -I/packages/pixman-0.42.2-1/.self/develop/headers/pixman-1 -I/packages/glib2-2.78.0-1/.self/develop/headers -I/packages/libffi-3.4.2-2/.self/develop/headers -I/packages/glib2-2.78.0-1/.self/develop/headers/glib-2.0 -I/packages/glib2-2.78.0-1/.self/develop/lib/glib-2.0/include -I/packages/libpcre2-10.43-2/.self/develop/headers -I/packages/harfbuzz-8.3.0-2/.self/develop/headers/harfbuzz -I/packages/freetype-2.13.2-1/.self/develop/headers/freetype2 -I/packages/libpng16-1.6.40-1/.self/develop/headers -I/packages/zlib-1.3-3/.self/develop/headers -I/packages/graphite2-1.3.14-2/.self/develop/headers -I/packages/sdl2_pango-0.1.2-2/.self/develop/headers -I/packages/pango-1.50.14-2/.self/develop/headers/pango-1.0 -I/packages/glib2-2.78.0-1/.self/develop/headers -I/packages/fribidi-1.0.13-1/.self/develop/headers/fribidi -I/packages/cairo1.18-1.18.0-1/.self/develop/headers/cairo -I/packages/fontconfig-2.13.96-2/.self/develop/headers -I/packages/libxml2-2.12.5-1/.self/develop/headers/libxml2 -I/packages/pixman-0.42.2-1/.self/develop/headers/pixman-1 -I/packages/glib2-2.78.0-1/.self/develop/headers -I/packages/libffi-3.4.2-2/.self/develop/headers -I/packages/glib2-2.78.0-1/.self/develop/headers/glib-2.0 -I/packages/glib2-2.78.0-1/.self/develop/lib/glib-2.0/include -I/packages/libpcre2-10.43-2/.self/develop/headers -I/packages/harfbuzz-8.3.0-2/.self/develop/headers/harfbuzz -I/packages/freetype-2.13.2-1/.self/develop/headers/freetype2 -I/packages/libpng16-1.6.40-1/.self/develop/headers -I/packages/zlib-1.3-3/.self/develop/headers -I/packages/graphite2-1.3.14-2/.self/develop/headers    -D_REENTRANT -I/packages/libsdl2-2.30.2-2/.self/develop/headers -I/packages/libsdl2-2.30.2-2/.self/develop/headers/SDL2 -I/packages/fribidi-1.0.13-1/.self/develop/headers/fribidi -DVER_DATE=\"2024-06-07\" -DVER_VERSION=\"0.9.33\" -DDATA_PREFIX=\"/boot/home/destdir//share/tuxpaint/\" -DDOC_PREFIX=\"/boot/home/destdir//share/doc/tuxpaint-0.9.33/\" -DLOCALEDIR=\"/boot/home/destdir//share/locale/\" -DIMDIR=\"/boot/home/destdir//share/tuxpaint/im/\" -DCONFDIR=\"/boot/home/config/settings/TuxPaint/\" -DMAGIC_PREFIX=\"/boot/home/destdir//lib/tuxpaint/plugins/\"      \
        -o tuxpaint obj/tuxpaint.o obj/i18n.o obj/im.o obj/cursor.o obj/pixels.o obj/rgblinear.o obj/playsound.o obj/fonts.o obj/parse.o obj/fill.o obj/progressbar.o obj/dirwalk.o obj/get_fname.o obj/onscreen_keyboard.o obj/gifenc.o obj/sounds.o obj/BeOS_print.o \
        -L/packages/libsdl2-2.30.2-2/.self/develop/lib -lSDL2 -L/packages/sdl2_image-2.0.5-3/.self/develop/lib -L/packages/libsdl2-2.30.2-2/.self/develop/lib -lSDL2_image -lSDL2 -L/packages/sdl2_ttf-2.20.2-2/.self/develop/lib -L/packages/libsdl2-2.30.2-2/.self/develop/lib -lSDL2_ttf -lSDL2 -L/packages/sdl2_gfx-1.0.4-4/.self/develop/lib -L/packages/libsdl2-2.30.2-2/.self/develop/lib -lSDL2_gfx -lSDL2 -L/packages/zlib-1.3-3/.self/lib -lz -L/packages/libpng16-1.6.40-1/.self/develop/lib -lpng16 -L/packages/sdl2_mixer-2.0.4-4/.self/develop/lib -L/packages/libsdl2-2.30.2-2/.self/develop/lib -lSDL2_mixer -lSDL2 -L/packages/sdl2_pango-0.1.2-2/.self/develop/lib -L/packages/pango-1.50.14-2/.self/develop/lib -L/packages/glib2-2.78.0-1/.self/develop/lib -L/packages/harfbuzz-8.3.0-2/.self/develop/lib -lSDL2_Pango -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lharfbuzz -L/packages/pango-1.50.14-2/.self/develop/lib -L/packages/glib2-2.78.0-1/.self/develop/lib -L/packages/harfbuzz-8.3.0-2/.self/develop/lib -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lharfbuzz -L/packages/pango-1.50.14-2/.self/develop/lib -L/packages/glib2-2.78.0-1/.self/develop/lib -L/packages/harfbuzz-8.3.0-2/.self/develop/lib -L/packages/fontconfig-2.13.96-2/.self/develop/lib -L/packages/freetype-2.13.2-1/.self/develop/lib -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lharfbuzz -lfontconfig -lfreetype -L/packages/librsvg-2.50.7-4/.self/develop/lib -L/packages/glib2-2.78.0-1/.self/develop/lib -L/packages/gdk_pixbuf-2.42.9-4/.self/develop/lib -L/packages/glib2-2.78.0-1/.self/develop/lib -L/packages/cairo1.18-1.18.0-1/.self/develop/lib -lrsvg-2 -lm -lgio-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lintl -lcairo -lintl -L/packages/libpng16-1.6.40-1/.self/develop/lib -lpng16 -lz -lbe -lnetwork -liconv -L/packages/fribidi-1.0.13-1/.self/develop/lib -lfribidi -lpaper -lstdc++ -limagequant -lm
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/../../../../x86_64-unknown-haiku/bin/ld: obj/tuxpaint.o: in function `trash':
/Opslag/patchUpstream/TuxPaint/tuxpaint-tuxpaint/src/tuxpaint.c:30969:(.text+0x3157b): undefined reference to `haiku_trash'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/../../../../x86_64-unknown-haiku/bin/ld: /Opslag/patchUpstream/TuxPaint/tuxpaint-tuxpaint/src/tuxpaint.c:30969:(.text+0x33413): undefined reference to `haiku_trash'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/../../../../x86_64-unknown-haiku/bin/ld: /Opslag/patchUpstream/TuxPaint/tuxpaint-tuxpaint/src/tuxpaint.c:30969:(.text+0x34999): undefined reference to `haiku_trash'
collect2: error: ld returned 1 exit status
Makefile:1215: recipe for target 'tuxpaint' failed
make: *** [tuxpaint] Error 1
```

**Comment by korli** [comment]
@Begasus please amend in Makefile: `beos_ARCH_LIBS:=obj/BeOS_print.o obj/haiku_trash.o `

**Comment by Begasus** [comment]
Seems that part "obj/haiku_trash.o" is missing in Makefile @billkendrick , looking into it  @korli thanks!

**Comment by billkendrick** [comment]
> @Begasus please amend in Makefile: `beos_ARCH_LIBS:=obj/BeOS_print.o obj/haiku_trash.o `

Hah yes, I got a little ahead of myself. I just committed changes to Makefile to (hopefully) get that built and linked. (Basically copy/paste of what was in there to build & link to `win32_trash.o` for Windows)  `git pull` and try again!

**Comment by Begasus** [comment]
Now it's failing :)
First error (sorry for being a n00b here)
```
...Compiling Haiku trash support...
In file included from src/haiku_trash.c:42:
/boot/system/develop/headers/os/app/Message.h:12:10: fatal error: new: No such file or directory
   12 | #include <new>
      |          ^~~~~
compilation terminated.
```

I'm guessing some headers are not needed in there, but running into other errors when proceeding then, like:
```
In file included from /boot/system/develop/headers/os/storage/Node.h:9,
                 from src/haiku_trash.c:49:
/boot/system/develop/headers/os/storage/Statable.h:17:1: error: unknown type name 'class'
   17 | class BVolume;
      | ^~~~~
/boot/system/develop/headers/os/storage/Statable.h:20:1: error: unknown type name 'class'
   20 | class BStatable {
      | ^~~~~
/boot/system/develop/headers/os/storage/Statable.h:20:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
   20 | class BStatable {
      |                 ^
```

**Comment by korli** [comment]
@billkendrick it should be haiku_trash.cpp

**Comment by korli** [comment]
it should be haiku_trash.cpp, and maybe `extern "C" status_t haiku_trash(const char *f)`.

**Comment by billkendrick** [comment]
:facepalm: Okay try now @Begasus

**Comment by Begasus** [comment]
```
src/tuxpaint.c:334:8: error: expected identifier or '(' before string constant
  334 | extern "C" status_t haiku_trash(const char *f)
      |        ^~~
```

**Comment by korli** [comment]
> ```
> src/tuxpaint.c:334:8: error: expected identifier or '(' before string constant
>   334 | extern "C" status_t haiku_trash(const char *f)

it's for haiku_trash.cpp actually. instead of `status_t haiku_trash(const char *f)`

**Comment by Begasus** [comment]
> > ```
> > src/tuxpaint.c:334:8: error: expected identifier or '(' before string constant
> >   334 | extern "C" status_t haiku_trash(const char *f)
> > ```
> 
> it's for haiku_trash.cpp actually. instead of `status_t haiku_trash(const char *f)`

Had that switched here, now:
```
src/haiku_trash.cpp:74:26: error: 'kAttrOriginalPath' was not declared in this scope
   74 |   err = node.GetAttrInfo(kAttrOriginalPath, &ai);
      |                          ^~~~~~~~~~~~~~~~~
Makefile:1370: recipe for target 'obj/haiku_trash.o' failed
make: *** [obj/haiku_trash.o] Error 1
```

**Comment by korli** [comment]
> kAttrOriginalPath

Please declare as in https://github.com/haiku/haiku/blob/3e910e720f3408a2ccf7dae9019621a390f3527b/src/bin/trash.cpp#L21

**Comment by Begasus** [comment]
Just found that in the Haiku source, build proceeding

**Comment by Begasus** [comment]
Current diff here now @billkendrick (not sure it's correct, but builds now):
```diff
/Opslag/patchUpstream/TuxPaint/tuxpaint-tuxpaint> git diff
diff --git a/src/haiku_trash.cpp b/src/haiku_trash.cpp
index f09c108e7..fe6d84bc6 100644
--- a/src/haiku_trash.cpp
+++ b/src/haiku_trash.cpp
@@ -52,7 +52,7 @@
 #include <storage/Path.h>
 #include <support/TypeConstants.h>
 
-status_t haiku_trash(const char *f)
+extern "C" status_t haiku_trash(const char *f)
 {
   status_t err;
   attr_info ai;
@@ -61,6 +61,7 @@ status_t haiku_trash(const char *f)
   const char *original_path;
   char trash_dir[B_PATH_NAME_LENGTH];
   char trashed_file[B_PATH_NAME_LENGTH];
+  static const char *kAttrOriginalPath = "_trk/original_path";
 
   dev = dev_for_path(f);
   err = find_directory(B_TRASH_DIRECTORY, dev, false, trash_dir, B_PATH_NAME_LENGTH);
diff --git a/src/tuxpaint.c b/src/tuxpaint.c
index ad78bb191..42fcf5e49 100644
--- a/src/tuxpaint.c
+++ b/src/tuxpaint.c
@@ -331,7 +331,7 @@ typedef struct safer_dirent
   char d_name[FILENAME_MAX];
 } safer_dirent;
 
-extern "C" status_t haiku_trash(const char *f);
+extern status_t haiku_trash(const char *f);
 
 #define dirent safer_dirent
 
```

**Comment by billkendrick** [comment]
On Fri, Jun 07, 2024 at 12:49:59AM -0700, Schrijvers Luc wrote:
> Just found that in the Haiku source, build proceeding

I've tried to follow along and committed to master Git branch.
Please check that it's working, and apply any further changes
if you can -- off to bed for me. :-)  Thanks, both!

**Comment by Begasus** [comment]
Works, thanks @korli and @billkendrick !

![TP_trash](https://github.com/haikuports/haikuports/assets/16057090/d028c104-8948-46f3-a4b7-2765f94c0e99)

**Comment by korli** [comment]
> Works, thanks @korli and @billkendrick !

Super! Please check that the file can be restored from the trash.

**Comment by billkendrick** [comment]
On Fri, Jun 07, 2024 at 12:53:33AM -0700, Schrijvers Luc wrote:
> Current diff here now @billkendrick (not sure it's correct, but builds now):

I think except for where I declared `kAttrOriginalPath`, it should
be the same in Git...? :-)

To test, you should be able to draw a picture in Tux Paint, save it,
then go to the "Open" dialog, select the drawing, and click "Erase".
Instead of being totally removed (via `unlink()` system call), the
intention here is for it to be moved to your desktop's Trash.

Can you confirm that works?  And I assume there's a "restore"
(put the file back where it came) option within the Trash in Haiku
(as there is in KDE, Windows, and macOS).  If so, can you confirm
that the file gets moved back into Tux Paint's saved-files folder
(and hence, if you go back into the "Open" dialog, you'll see the
drawing reaapear)...?

Thanks again, and goodnight!

-bill!

**Comment by Begasus** [comment]
Give me a minute ;) just pulled latest changes.

**Comment by Begasus** [comment]
Confirming, moving to trash functions fine, restoring it works also and the image shows up again when clicking on open in TP. Success!

**Comment by korli** [comment]
What's the plan with this issue? Keep open until next release?

**Comment by Begasus** [comment]
I guess it can be closed, next release is in the pipeline (shortly). There is still an open issue in regards op printing: https://github.com/haikuports/haikuports/issues/8059 (but that has been here for a while, so not a stopper for the release atm).

**Comment by billkendrick** [comment]
Thanks again you two!
