### ISSUE TITLE
Avahi: not available in HaikuDepot

### ISSUE THREAD

**Issue by robante15** [haikuports/haikuports#10570]
Avahi is not available on HaikuDepot although there is a recipe here on HaikuPorts. It is also not possible to find it using pkgman

I am using Haiku hrev57733 x86_64

**Comment by Begasus** [comment]
It was disabled from the start as there hasn't been any testing/needs dbus: https://github.com/haikuports/haikuports/commit/0d2dbc2ae38474ebbc99f1932b7030976cebb2a9

**Comment by robante15** [comment]
Thanks for the clarification
