### ISSUE TITLE
qbittorrent and qbittorrent_qt5 share work directory

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#1058]
The two recipes are in the same directory. As a result, they use the same "work" folder. This creates confusion if you build qbittorrent (configures for Qt4), then qbittorrent_qt5 (thinks the package is already built, tries to run "make install", fails because qmake doesn't find its required files).

Possible solutions:
- Always make sure we only have one recipe per directory
- Move the "work" directory according to the recipe name to make sure there aren't any conflicts

**Comment by korli** [comment]
Fixed in 2971318b14638de0455d22f68021f4c98d29d42b.
