### ISSUE TITLE
w6 faild to build in x86_64

### ISSUE THREAD

**Issue by punsith** [haikuports/haikuports#1059]

**Comment by punsith** [comment]
~/haikuporter> haiku-games::w6-1.7
bash: haiku-games::w6-1.7: command not found
~/haikuporter>         /boot/home/haikuports/haiku-games/w6/w6-1.7.recipe
bash: /boot/home/haikuports/haiku-games/w6/w6-1.7.recipe: Permission denied
~/haikuporter> ----------------------------------------------------------------------
bash: ----------------------------------------------------------------------: command not found
~/haikuporter> Skipping download of source for W6Haiku.zip
bash: Skipping: command not found
~/haikuporter> Skipping checksum validation of W6Haiku.zip
bash: Skipping: command not found
~/haikuporter> Skipping download of source for W6forR5-with-sources.zip
bash: Skipping: command not found
~/haikuporter> Skipping checksum validation of W6forR5-with-sources.zip
bash: Skipping: command not found
~/haikuporter> Skipping unpack of W6Haiku.zip
bash: Skipping: command not found
~/haikuporter> Cleaning source dir for W6forR5-with-sources.zip
bash: Cleaning: command not found
~/haikuporter> Unpacking source of W6forR5-with-sources.zip
bash: Unpacking: command not found
~/haikuporter> 'ascii' codec can't decode byte 0xc3 in position 32: ordinal not in range(128)

**Comment by mmuman** [comment]
did you just paste random text into Terminal?

**Comment by punsith** [comment]
no why should i :o

**Comment by korli** [comment]
Invalid
