### ISSUE TITLE
Updating osl to 1.11.17.0

### ISSUE THREAD

**Issue by brad0** [haikuports/haikuports#10604]
Updating to osl 1.11.17 should allow updating the port to use LLVM 12.

**Comment by Begasus** [comment]
Could porbably use an opdate on openexr version, and openimageio has dependencies for dropped boost version.

**Comment by brad0** [comment]
> Could porbably use an opdate on openexr version, and openimageio has dependencies for dropped boost version.

I was looking at my first try at recipes and quickly was stuck on the openimageio boost dependency and don't understand how this works as is.

**Comment by Begasus** [comment]
Running into issues there already, checksum changed, source dir changed ..

**Comment by Begasus** [comment]
Thanks Fedora for some pointers in the right direction :)

https://src.fedoraproject.org/rpms/openshadinglanguage/blob/rawhide/f/openshadinglanguage.spec

```
grabbing osl-1.11.17.0-1-x86_64.hpkg and moving it to /Opslag/haikuports/packages/osl-1.11.17.0-1-x86_64.hpkg
grabbing osl_debuginfo-1.11.17.0-1-x86_64.hpkg and moving it to /Opslag/haikuports/packages/osl_debuginfo-1.11.17.0-1-x86_64.hpkg
grabbing osl_devel-1.11.17.0-1-x86_64.hpkg and moving it to /Opslag/haikuports/packages/osl_devel-1.11.17.0-1-x86_64.hpkg
``

PS, I see the latest version for this is 1.13.10.0 at repology?

**Comment by brad0** [comment]
> PS, I see the latest version for this is 1.13.10.0 at repology?

Ya, there are newer versions. I mentioned the same branch to minimize potentially breaking other dependencies.

**Comment by Begasus** [comment]
Ok, makes sense, from my finds I only see Blender is using it (commente out in the recipe), so far it seems that nothing is using it. I got the Qt tool to compile too, but can't seem  to do anything descent with it. :)

**Comment by brad0** [comment]
Ok, I just noticed this and aflplus as dependencies utilizing LLVM 9 still.

**Comment by Begasus** [comment]
Installing Blender also pulled it in, but I guess that's because of this one? Needs some more checking, at least the 32bit Blender still mentions LLVM 9 too.
```
~> inrecipe lib:libLLVM_9
/Opslag/haikuports/app-forensics/aflplusplus/aflplusplus-3.12c.recipe:57:       lib:libLLVM_9$secondaryArchSuffix
/Opslag/haikuports/media-gfx/blender/blender-2.79b.recipe:62:   lib:libLLVM_9$secondaryArchSuffix
/Opslag/haikuports/media-libs/osl/osl-1.11.14.2.recipe:55:      lib:libLLVM_9$secondaryArchSuffix
```

**Comment by Begasus** [comment]
This is messy ... can't open Blender on 64bit, needs openimageio 2.2.16 and opensubdiv 3.4.3 it seems.

**Comment by Begasus** [comment]
Addes a "draft" roadmap on how to bump this, it's not formatted, so just flat text. It's not complete but if you want to get into it should give you a first idea on what's needed. wip! :)

https://github.com/Begasus/haikuports/wiki/Bump-Recipe

**Comment by Begasus** [comment]
@brad0 could you check https://github.com/haikuports/haikuports/pull/10621 ?
This contains an update for 1.11.17.0 and the latest one 1.13.10.0 (first one on LLVM 12, second one on LLVM 18).
