### ISSUE TITLE
bakefile building faild for x86_64

### ISSUE THREAD

**Issue by punsith** [haikuports/haikuports#1061]
clocal.m4:1037: _LT_SYS_MODULE_PATH_AIX is expanded from...
aclocal.m4:4186: _LT_LINKER_SHLIBS is expanded from...
aclocal.m4:5261: _LT_LANG_C_CONFIG is expanded from...
aclocal.m4:159: _LT_SETUP is expanded from...
aclocal.m4:88: LT_INIT is expanded from...
aclocal.m4:123: AC_PROG_LIBTOOL is expanded from...
configure.in:16: the top level
configure.in:16: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
aclocal.m4:4186: _LT_LINKER_SHLIBS is expanded from...
aclocal.m4:5261: _LT_LANG_C_CONFIG is expanded from...
aclocal.m4:159: _LT_SETUP is expanded from...
aclocal.m4:88: LT_INIT is expanded from...
aclocal.m4:123: AC_PROG_LIBTOOL is expanded from...
configure.in:16: the top level
configure.in:11: error: version mismatch.  This is Automake 1.15,
configure.in:11: but the definition used by this AM_INIT_AUTOMAKE
configure.in:11: comes from Automake 1.11.  You should recreate
configure.in:11: aclocal.m4 with aclocal and run automake again.
configure.in:11: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.in:11: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.in:11: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
Makefile.am: installing './INSTALL'
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
Makefile.am:129: warning: source file 'src/bottlenecks.c' is in a subdirectory,
Makefile.am:129: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
Makefile.am:129: warning: source file 'src/bkl_c_wrap.c' is in a subdirectory,
Makefile.am:129: but option 'subdir-objects' is disabled
[Errno -2147459069] No such file or directory: '/boot/home/haikuports/dev-util/bakefile/work-0.2.8'
Error: Build has failed - stopping.
~>

**Comment by diversys** [comment]
Try to clean up with `hp bakefile -c` and try again.

**Comment by punsith** [comment]
okay i will :)

**Comment by punsith** [comment]
![unkon](https://cloud.githubusercontent.com/assets/24215220/22183284/2a4c1f5a-e088-11e6-948e-13b4af5c5300.png)
