### ISSUE TITLE
OpenEXR crash with Genio (beta4)

### ISSUE THREAD

**Issue by jackburton79** [haikuports/haikuports#10610]
Latest Genio crashes on start in beta4 32 bit.
What's strange is that the crash is inside OpenEXR (exception not caught)

```
terminate called after throwing an instance of 'Iex_2_4::InputExc'
  what(): File is not an image file
```

Which is correct as Genio is loading pngs with BTranslationUtils::GetBitmap().
I suspect it's the same issue as #9792 and the openEXR package needs to be rebuilt.

**Comment by Begasus** [comment]
Why not switch to OpenEXR 3.2.2? (fwiw, working on a version bump there towards 3.2.4 at the moment). OpenEXR 2.4.1 is already pretty old :) (released: Feb 12, 2020)

**Comment by korli** [comment]
> Why not switch to OpenEXR 3.2.2? (fwiw, working on a version bump there towards 3.2.4 at the moment). OpenEXR 2.4.1 is already pretty old :) (released: Feb 12, 2020)

it must be used by a translator: https://cgit.haiku-os.org/haiku/tree/build/jam/repositories/HaikuPorts/x86?h=r1beta4#n910
see for Haiku Ticket https://dev.haiku-os.org/ticket/18537 for upgrades.

**Comment by Begasus** [comment]
Commented on the ticket, having the update on our current 3.2 version shouldn't interfere with this? https://github.com/haikuports/haikuports/pull/10612

**Comment by korli** [comment]
> Latest Genio crashes on start in beta4 32 bit. What's strange is that the crash is inside OpenEXR (exception not caught)
> 
> ```
> terminate called after throwing an instance of 'Iex_2_4::InputExc'
>   what(): File is not an image file
> ```
> 
> Which is correct as Genio is loading pngs with BTranslationUtils::GetBitmap(). I suspect it's the same issue as #9792 and the openEXR package needs to be rebuilt.

Done in bf79bdaf3f074ca5db9f69375383c8dfa6f7648e

**Comment by Begasus** [comment]
@jackburton79 could you check if @korli 's push has fixed it for you?

**Comment by jackburton79** [comment]
> @jackburton79 could you check if @korli 's push has fixed it for you?

Confirmed fixed. Thanks!
