### ISSUE TITLE
bencode_tools build fail on x86_64

### ISSUE THREAD

**Issue by punsith** [haikuports/haikuports#1062]
~> haikuporter -S  bencode --no-dependencies
Checking if any package-infos need to be updated ...
Looking for stale dependency-infos ...
Error: bencode not found in repository
~> haikuporter -S  bencode_tools --no-dependencies
Checking if any package-infos need to be updated ...
Looking for stale dependency-infos ...
Checking if package dependencies need to be updated ...
        updating dependency infos of bencode_tools-20110315
----------------------------------------------------------------------
dev-util::bencode_tools-20110315
        /boot/home/haikuports/dev-util/bencode/bencode_tools-20110315.recipe
----------------------------------------------------------------------

Downloading: http://zakalwe.fi/~shd/foss/bencode-tools/bencode-tools-2011-03-15.tar.bz2 ...
--2017-01-14 11:09:58--  http://zakalwe.fi/~shd/foss/bencode-tools/bencode-tools-2011-03-15.tar.bz2
Resolving zakalwe.fi... failed: Operation timed out.
wget: unable to resolve host address ‘zakalwe.fi’
Warning: Unable to fetch source from http://zakalwe.fi/~shd/foss/bencode-tools/bencode-tools-2011-03-15.tar.bz2 (error: Command '['wget', '-c', '--timeout=10', '--tries=3', '-O', u'/boot/home/haikuports/dev-util/bencode/download/bencode-tools-2011-03-15.tar.bz2', u'http://zakalwe.fi/~shd/foss/bencode-tools/bencode-tools-2011-03-15.tar.bz2']' returned non-zero exit status 4), trying next location.

Downloading: https://ports-mirror.haiku-os.org/bencode/bencode-tools-2011-03-15.tar.bz2 ...
--2017-01-14 11:10:08--  https://ports-mirror.haiku-os.org/bencode/bencode-tools-2011-03-15.tar.bz2
Resolving ports-mirror.haiku-os.org... failed: Operation timed out.
wget: unable to resolve host address ‘ports-mirror.haiku-os.org’
Warning: Unable to fetch source from https://ports-mirror.haiku-os.org/bencode/bencode-tools-2011-03-15.tar.bz2 (error: Command '['wget', '-c', '--timeout=10', '--tries=3', '-O', u'/boot/home/haikuports/dev-util/bencode/download/bencode-tools-2011-03-15.tar.bz2', u'https://ports-mirror.haiku-os.org/bencode/bencode-tools-2011-03-15.tar.bz2']' returned non-zero exit status 4)
Error: Failed to fetch source from all known locations.
~>

**Comment by diversys** [comment]
Resolving zakalwe.fi... failed: Operation timed out.

http://zakalwe.fi/~shd/foss/bencode-tools/bencode-tools-2011-03-15.tar.bz2 works fine here. Must be something with your DNS server.

**Comment by punsith** [comment]
yes It is i change my dns :D then worked
