### ISSUE TITLE
mandoc: Issue with parsing Haiku-modified man pages

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#10644]
Ref: https://discuss.haiku-os.org/t/manual-pages-for-programmers-clib/15153/11
```
[donn](https://discuss.haiku-os.org/u/donn)
[10h](https://discuss.haiku-os.org/t/manual-pages-for-programmers-clib/15153/11?u=cocobean)
OK, I tracked down the source - I think - and I think part of the problem is a bug in how the Haiku port system is patching the pages.

The popen.3p source is actually a legit man page, with a SYNOPSIS section and everything you need, if you don’t mind the PROLOG blurb at the top.

Here, that blurb says

… The Linux implementation of this interface may differ …

where our port has patched in

… This interface might not be implemented on Haiku.

But it clipped off 863 bytes of the text, losing the SYNOPSIS and starting in midstream with the business about execl.

Some pages seem to escape without harm, and when the top is chopped the amount of damage varies. Looks like we lose everything up to the first blank line in the nroff source. If any - if there’s no blank line, in the source, you get the original Linux version with no patch, e.g. strdup.

So I’d say there’s room for considerable improvement without a massive amount of work, just need to swap in something that works correctly, in place of the Perl code. Whatever it’s doing, I imagine it’s written with a formatted page in mind. Here’s something that would work using awk -

#!/bin/awk -f
{
    if (prolog) {
        if (/The Linux implementation/) {
            print "This interface might not be implemented on Haiku."
            skip = 1
        } else if (/^\./) {
            prolog = 0
            print
        } else if (!skip) {
            print
        }
    } else if (/\.SH PROLOG/) {
        prolog = 1
        print
    } else 
        print
}
```

**Comment by donncave** [comment]
From the perspective of this issue, it makes sense to me to go forward with the nroff source, rather than fixing the problem by applying this patch to formatted pages, if that's what happened.  This generation of the file will be easier to patch - I'm reasonably sure the Linux disclaimer was grafted in just this way, so it's on its own separate line;  there are easily recognized structure elements in the text, etc.

**Comment by lonemadmax** [comment]
I don't grok perl, but the regex seems to be looking for ".SH PROLOG" + newline + whatever until an empty line is found, and that indeed corresponds to your popen example, killing NAME, SYNOPSIS and part of DESCRIPTION sections **in the latest version** of our man_pages_posix. The previous one did have a newline after the PROLOG.

This is where upstream includes their notice: https://git.kernel.org/pub/scm/docs/man-pages/man-pages-posix.git/tree/posix.py#n318. And [when they changed that separator](https://git.kernel.org/pub/scm/docs/man-pages/man-pages-posix.git/commit/posix.py?id=1bac4def072144ce140b5bf11846a1925d1a8e9e). It seems our package update was rushed without testing. There's also a README in that directory that should tell what other things they do, if you understand any of it.

**Comment by Begasus** [comment]
Maybe revert the change here? I tried with the awk script but couldn't get that to work.

**Comment by lonemadmax** [comment]
The perl line should do, changing `^\s*$` to... some escaped incantation that looks for `.\"`. Maybe `^\.\\\"$`. I'll give it a try in few minutes if you don't beat me to it.

The awk script also looks right to me *without having tested it*.

**Comment by donncave** [comment]
It worked for me, but I have no idea about the context there, I was just `hfix < popen.3p > popen.fixed`
I will append a sed script for your amusement.  What I'm looking at is a directory hierarchy with man3p/popen.3p at the bottom.  These files start with
        '\" et
        .TH POPEN "3P" 2017 "IEEE/The Open Group" "POSIX Programmer's Manual"
        .\"
        .SH PROLOG
        This manual page is part of the POSIX Programmer's Manual.
        The Linux implementation of this interface may differ (consult
        the corresponding Linux manual page for details of Linux behavior),
        or the interface may not be implemented on Linux.
        .\"
        .SH NAME
... and the object is to modify the 2nd through last lines of the .SH PROLOG ... .\" section.

`sed '/\.SH PROLOG/,/^\./{ /Linux/,/^\./{ /^\./ { i\
This interface might not be implemented on Haiku.
; b }; d } }'`

**Comment by lonemadmax** [comment]
While the content change was easy to fix, there's also a license change in the 2017 version that seems wouldn't allow us to modify and redistribute it. The buggy package has been removed and we are back to the correctly formatted 2013 version.

I guess this can be closed.
