### ISSUE TITLE
Enable Lua for mpv recipe.

### ISSUE THREAD

**Issue by lidgnulinux** [haikuports/haikuports#10665]
Hello, I notice that MPV won't show osd bar and subtitle. I made a [post](https://discuss.haiku-os.org/t/cant-show-subtitle-on-any-video-player/15211) at haiku forum and get suggested to make an issue here.Thanks.

**Comment by Begasus** [comment]
Quick look show it only supports lua5.1 and lua5.2.

**Comment by Begasus** [comment]
From the test package it seemed this wasn't the issue, if it's OK with you @lidgnulinux this can be closed then.

**Comment by Begasus** [comment]
Thanks for checking! +1
