### ISSUE TITLE
tuxracer build failed on x86_64 

### ISSUE THREAD

**Issue by punsith** [haikuports/haikuports#1068]
![tuxracer](https://cloud.githubusercontent.com/assets/24215220/21956418/42521e0a-da4e-11e6-8c35-14e2aa1c2fc7.png)

**Comment by diversys** [comment]
It's the same error over and over. haikuporter/pkgman fails to get libsdl for some reason. You need to download it manually using `pkgman install libsdl_devel` and try again with those recipes.

**Comment by punsith** [comment]
i updated but error remain " 
![remain](https://cloud.githubusercontent.com/assets/24215220/21956485/f47d8fe6-da4f-11e6-9874-756c67eddb8b.png)

**Comment by diversys** [comment]
As can be seen it's a new error. Try to `pkgman install tcl_devel `

**Comment by punsith** [comment]
an error 
![g](https://cloud.githubusercontent.com/assets/24215220/21956696/093dff34-da54-11e6-89a2-ebc8bc40925f.png)

**Comment by diversys** [comment]
Odd, it should work. You can manually download them:

http://packages.haiku-os.org/haikuports/master/repo/x86_64/current/packages/tcl-8.5.18-4-x86_64.hpkg
http://packages.haiku-os.org/haikuports/master/repo/x86_64/current/packages/tcl_devel-8.5.18-4-x86_64.hpkg

**Comment by punsith** [comment]
still errors remain :( 
![s](https://cloud.githubusercontent.com/assets/24215220/21956919/d9969f34-da58-11e6-9f13-9e6d50bd369c.png)

**Comment by Begasus** [comment]
lib:libtcl8.5	#tcl version in the recipe has to be set to >=8.0 instead of >=8.5
 
This line was added (last year I think), a new build for tcl with 8.0 instead of 8.5 fixes this for tuxracer

**Comment by korli** [comment]
You need to install tcl_devel.

**Comment by punsith** [comment]
i install it using pkgman and also manually :\

**Comment by Begasus** [comment]
Weird enough I could get it to build with an extra patch on 64bit, but it seems on 32bit it's broken (launches but only a very small window pops up).
Patch: https://git.altlinux.org/gears/t/tuxracer.git?p=tuxracer.git;a=blob;f=tuxracer-0.61-gcc33.patch;h=623e5a41f9f4e785a8b83fc2965bba5654bb858d;hb=2886e8587e150b0ced6ca790ae23dd989516ea0b

Running on 64bit:

![Tux-Racer-64bit](https://user-images.githubusercontent.com/16057090/175952697-75513079-3c54-4189-bf1b-7a86516bee98.png)

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/8897
Crashes on exit though (both arch's).
