### ISSUE TITLE
beautifulsoup build faild on x86_64

### ISSUE THREAD

**Issue by punsith** [haikuports/haikuports#1069]
![beautifulsoup](https://cloud.githubusercontent.com/assets/24215220/21956572/18333826-da52-11e6-9f62-3c530248fbb2.png)

**Comment by diversys** [comment]
Another DNS error.

**Comment by punsith** [comment]
can you suggest me a good DNS server , i used opendns , and google dns but same thing happens

**Comment by scottmc** [comment]
This should probably be updated anyways, latest version if 4.5.3:
https://pypi.python.org/packages/9b/a5/c6fa2d08e6c671103f9508816588e0fb9cec40444e8e72993f3d4c325936/beautifulsoup4-4.5.3.tar.gz#md5=937e0df0d699a1237646f38fd567f0c6

**Comment by punsith** [comment]
will i udpade the source url on recipe

**Comment by punsith** [comment]
![ont yet](https://cloud.githubusercontent.com/assets/24215220/21957874/cb031086-da6e-11e6-91db-707cbfcd3f95.png)

**Comment by korli** [comment]
A bunch of python recipes don't install with the same problem, they should be fixed as well.

**Comment by punsith** [comment]
korli what is with wirk file , why it cant find it ?
