### ISSUE TITLE
QEMU crashes when running Haiku R1 Beta4

### ISSUE THREAD

**Issue by dalmemail** [haikuports/haikuports#10715]
![qemu_822_failure](https://github.com/user-attachments/assets/034687f7-3078-4578-9940-054fdf2e3ced)

Command issued was: ```$ qemu-system-x86_64 -m 1024 -cdrom path_to_haiku_iso```

The screenshot is from QEMU 8.2.2 but it does happen with QEMU 8.1.5 too.

Log on the terminal says:
```
OpenGL load add-on: /boot/system/add-ons/opengl/Software Pipe
OpenGL add-on registered: /boot/system/add-ons/opengl/Software Pipe
GalliumContext: CreateDisplay: Using llvmpipe (LLVM 12.0.1, 256 bits) driver.
UnlockGL is called from wrong thread, lockerThread: 18140, callerThread: 18144
Kill Thread
```

I tried a nightly iso of Sortix 1.1 and it does run perfectly.

**Comment by Begasus** [comment]
Maybe try this (got this from the forum also), it works for me here:
```
#!sh

args=(
	-display haiku
	-machine q35
	-accel tcg
	-cpu max
	-m 2G
	-serial stdio
	-parallel none
	-monitor none
#	-bios "OVMF.fd"
	-device cirrus-vga
	-smp 8

	-device nec-usb-xhci,id=xhci
	-device usb-tablet,bus=xhci.0
	-device usb-kbd,bus=xhci.0

	-hda /Opslag/media/vmiso/haiku-nightly-anyboot_64.iso
)

qemu-system-x86_64 "${args[@]}"
```
Saved as `haikuQemu` script in  /boot/home/config/non-packaged/bin (set executable)

**Comment by dalmemail** [comment]
You're right @OscarL : @Begasus solution works. Thank you both very much !

**Comment by waddlesplash** [comment]
Is there any advantage to the SDL2 backend? Should we just disable it?

**Comment by dalmemail** [comment]
Idk if there are any advantages of disabling it. But I would put the display "haiku" as default for sure.
