### ISSUE TITLE
WonderBrush crashes with multiple files

### ISSUE THREAD

**Issue by donncave** [haikuports/haikuports#10797]

**Comment by donncave** [comment]
[ Dang touchpad noise. ]  The crashes occur when I add several bitmap files to a project - drop the files on the screen, select the bitmap, copy, paste into <unnamed>.  At some point it crashes, apparently in a ListView, possible the very crowded file list at the top of the left side.  hrev57939.

**Comment by donncave** [comment]
Reproduces much more reliably if I select items in that list of files at the top.

**Comment by humdingerb** [comment]
Bugs for native apps shuold be reported at the apps issue tracker. This specific crash sounds like similar issues that are fixed with this patch https://github.com/stippi/WonderBrush-v2/pull/29
For some reason it won't get merged though.

@all: should we just pull the patch and apply it in the recipe? I've been using a patched up WonderBrush for a long time now, because otherwise it's too unstable for any but the most basic stuff.

**Comment by pulkomandy** [comment]
> 
> Bugs for native apps shuold be reported at the apps issue tracker. This specific crash sounds like similar issues that are fixed with this patch stippi/WonderBrush-v2#29 https://github.com/stippi/WonderBrush-v2/pull/29 
> For some reason it won't get merged though.
> 
> @ALL https://github.com/ALL : should we just pull the patch and apply it in the recipe? I've been using a patched up WonderBrush for a long time now, because otherwise it's too unstable for any but the most basic stuff.
> 
We should revert the change in Haiku that broke an application that works fine on BeOS. This is not acceptable from Haiku, and stippi is right to not want to merge a workaround for it in Wonderbrush.

**Comment by humdingerb** [comment]
Fair enough. Until then I'll keep using my locally patched version.

**Comment by waddlesplash** [comment]
Do we have a ticket at the Haiku bugtracker for this, then? I see a few closed tickets about BListView autoscroll but none about this crash.

**Comment by waddlesplash** [comment]
Fixed in [hrev57966](https://git.haiku-os.org/haiku/tag/?h=hrev57966).
