### ISSUE TITLE
wireshark  building faild on x86_64 

### ISSUE THREAD

**Issue by punsith** [haikuports/haikuports#1080]
library error again :/ 
![wireshark](https://cloud.githubusercontent.com/assets/24215220/21996842/2101a0c4-dbfa-11e6-9994-f7b568361429.png)

**Comment by diversys** [comment]
If you get build-requires ... could not be resolved it means that either required package is not yet in the repo or that the package has wrong provides. 

In either case the proper way to resolve it is to try to download this package first (e.g. `pkgman search crypt`) or build it yourself. 

Please don't open issues with "broken" x86_64 recipes with this problem. And don't mark them as broken.

**Comment by punsith** [comment]
okay i am installing the libraryes thank you :)

**Comment by punsith** [comment]
![wishark](https://cloud.githubusercontent.com/assets/24215220/22045041/050c68e4-dce6-11e6-8b7c-546d3b3bd29e.png)
1 i updated the libraries then i removed workfiles using hp wireshark -c now this apprises

**Comment by diversys** [comment]
The error message is pretty clear, isn't in? You simply ran out our memory. Give your VM some more memory (and maybe also adjust VirtualMemory) and try again.

**Comment by punsith** [comment]
![aa](https://cloud.githubusercontent.com/assets/24215220/22131673/e7c5ebae-de82-11e6-9e38-bc7ddfaae23c.png)

**Comment by korli** [comment]
Thanks punsith. this build failure is valid.

**Comment by punsith** [comment]
you are welcome

**Comment by korli** [comment]
Fixed
