### ISSUE TITLE
Broken Epiphany/Web

### ISSUE THREAD

**Issue by kim1963** [haikuports/haikuports#10817]
After update glib_networking-2.72.2-2-x86_64.hpkg to glib_networking-2.72.2-3-x86_64.hpkg
Debug information for team /boot/system/lib/webkit2gtk-4.1/WebKitNetworkProcess (225490):
CPU(s): 6x Intel Core™ i5-8400
Memory: 15,88 Гбайт total, 2,78 Гбайт used
Haiku revision: hrev57951 Aug 11 2024 06:25:31 (x86_64)

[WebKitNetworkProcess-225490-debug-12-08-2024-02-43-37.txt](https://github.com/user-attachments/files/16579916/WebKitNetworkProcess-225490-debug-12-08-2024-02-43-37.txt)

**Comment by waddlesplash** [comment]
Seems our glib_networking version may not be fully compatible with OpenSSL 3? CC @pulkomandy.

**Comment by kim1963** [comment]
After revert glib_networking-2.72.2-3-x86_64.hpkg to glib_networking-2.72.2-2-x86_64.hpkg
browser work fine/

**Comment by kim1963** [comment]
Fixed
After update webkit_gtk

**Comment by kim1963** [comment]
Fixed after update webkiy_gtk
