### ISSUE TITLE
Broken QuiteRSS

### ISSUE THREAD

**Issue by kim1963** [haikuports/haikuports#10818]
After update Qt5 .hpkg to version 5.15.14-2

**Comment by waddlesplash** [comment]
Please give more information about what is broken.

**Comment by kim1963** [comment]
RSS download not work.

**Comment by kim1963** [comment]
After revert Qt5 .hpkg
news reader work fine/

**Comment by lonemadmax** [comment]
Can be closed after Qt5 fix.
