### ISSUE TITLE
Update gtkwebkit to less outdated depedencies

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#10815]
Hello,

Just some notes on my attempts to clean up old versions of libraries on my system. This is all for x86 secondary architecture.

- gtkwebkit is currently built against ICU 66 instead of a newer 74 or even 75
- I tried to rebuild it, but it needs libevent, which depends on openssl 1.1.1
- I tried to rebuild libevent, but that failed due to trying to use kqueue but using parts of it that we don't implement yet (EVFILT_SIGNAL)

- gtkwebkit, qt5 and fluidsynth2 also depend on flac13 instead of the newer flac1.4.
- I tried to rebuild fluidsynth2, but it fails fo find header files from libnsdispatch.

Of course, help is welcome to fix some of these issues :)

**Comment by pulkomandy** [comment]
Yes, forcing libevent to not enable kqueue support until this is improved on Haiku side should be fine. I think disabling just parts of the kqueue implementation would be a bad idea, it would then only half-work

**Comment by Begasus** [comment]
> * gtkwebkit is currently built against ICU 66 instead of a newer 74 or even 75

It even uses LLVM12

**Comment by Begasus** [comment]
webkit-gtk needs cmd:xgettext atleast in BUILD_PREREQUIRES, but build errors atm (link will stay up for a week): https://bpa.st/LGMA

**Comment by waddlesplash** [comment]
> I think disabling just parts of the kqueue implementation would be a bad idea, it would then only half-work

It turns out the signal handling is basically separate from the event handling and can be safely disabled (and libevent can then use its standard signal handling routines.) I sent @OscarL a patch to test, seems to work here after a fix to kqueue in Haiku, and should be much more performant (and not prone to strange races.)

**Comment by pulkomandy** [comment]
Thanks, I was able to rebuild it, should be fine now!

**Comment by Begasus** [comment]
@pulkomandy so the fluidsynth PR can be closed?

**Comment by pulkomandy** [comment]
I'm not sure what the status is with flac13 on x86, didn't check that yet (and I will not be in front of my 32bit machine for a few days).

**Comment by Begasus** [comment]
Build wise flac13 is fine, I only started to look into it because it was mentioned here, if there are no problems anymore maybe it's pointless medling with the existing packages atm? (given that there are no newer versions involved)

**Comment by pulkomandy** [comment]
I would like to retire older versions of packages and keep only the latest one as much as possible. In the case of flac, the latest one is flac 1.4, and I was trying to move all recipes to that, so flac13 can be removed.

I find these old packages annoying (why have two versions of a thing when you can have just one), and also potentially a source of problems if the two versions of a library end up being loaded in the same application (for example we know this is a problem with openssl 3 vs openssl 1.1, but it can be also with other libraries).

Anyway, no problem about it, I will keep that in my TODO list as a background task to try to keep at least my computers with only one version of each library installed, and rebuild things as needed to achieve that goal.

**Comment by Begasus** [comment]
OK fair enough, trying to "uninstall" flac13 here seems to bring down multiple packages, will do some checks on it here also, as for fluidsynth2 it builds fine with current flack 1.4, just not for gcc2 (either flac version), but maybe that can be dropped?
