### ISSUE TITLE
libuv : needs platform specific implementations

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#1082]
I got this during builing cmake 3.7.2:

> ( .... )
> Install the project...
> runtime_loader: /boot/system/lib/libuv.so.1.0.0: Could not resolve symbol 'uv__io_check_fd'
> resolve symbol "uv__io_check_fd" returned: -2147478780
> runtime_loader: /boot/system/lib/libuv.so.1.0.0: Troubles relocating: Symbol not found
> Makefile:72: recipe for target 'install' failed
> make: *** [install] Error 4
> [Errno -2147459069] No such file or directory: '/Ports/haikuports/dev-util/cmake/work-3.7.2'
> Error: Build has failed - stopping.
> /P/haikuports ❯❯❯ objdump -x /boot/system/lib/libuv.so.1.0.0 |grep uv__io_check_fd
> 0000000000000000 UND 0000000000000000 uv__io_check_fd
> ~ ❯❯❯

See other logs here: https://github.com/libuv/libuv/pull/1188

**Comment by korli** [comment]
1/ libuv should be marked as broken.
2/ the TEST() section shouldn't ignore failures...

**Comment by extrowerk** [comment]
Current version with some problems:
https://github.com/haikuports/haikuports/pull/1849

**Comment by waddlesplash** [comment]
https://github.com/haikuports/haikuports/commit/1d4daf6fa17202895f5cc3277de4099c18b23e74
