### ISSUE TITLE
Broken BeAM 

### ISSUE THREAD

**Issue by kim1963** [haikuports/haikuports#10835]
Download mail broken
[Beam-244992-debug-15-08-2024-01-40-20.txt](https://github.com/user-attachments/files/16620486/Beam-244992-debug-15-08-2024-01-40-20.txt)

**Comment by kim1963** [comment]
[Uploading Beam-959068-debug-14-09-2024-01-18-49.txt…]()

**Comment by kim1963** [comment]
[Beam-959068-debug-14-09-2024-01-18-49.txt](https://github.com/user-attachments/files/17000636/Beam-959068-debug-14-09-2024-01-18-49.txt)

**Comment by korli** [comment]
Should be fixed in 1.2.2-2
