### ISSUE TITLE
yt_dlp wanting to install ffmpeg-4.2.9 etc.

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#10837]
I was just about to install yt-dlp on the beta5-test-image and wondered why it wants to install ffmpeg-4.2.9, ffmpeg_avdevice-4.2.9 and ffmpeg_tools-4.2.9.  Why doesn't it go for the ffmpeg6-6.1.1_* versions? ffmpeg6-6.1.1-3-x86_64.hpkg is already installed with the beta5-test-image...

**Comment by Begasus** [comment]
yt_dlp requires "ffmpeg_tools" which isn't installed by default, so it picks the first available one, if you want to have it pick ffmpeg6 you would have to put a version strain on the recipe (which can be tricky if some other package requires a different tools package for ffmpeg.

**Comment by humdingerb** [comment]
OK, so since ffmpeg6 comes with Haiku beta5, it'd make sense to have yt-dlp depend on ffmpeg_tools6?

**Comment by Begasus** [comment]
that would be "ffmpeg6_tools", I guess youtube-dl can have that too. (already did it local on beta4 here, with a rebuild for mpv and (newer) mpvqt, latest beta for PlasmaTube seem to like it) :)

**Comment by humdingerb** [comment]
OK. You think we should wait with the ffmpeg6_tools update until beta5 is out? That'd save beta4 users from updating their ffmpeg packages to v6.

**Comment by Begasus** [comment]
Current beta4 users can't install it with pkgman/HaikuDepot, so bumping this now doesn't have any change for those (me included on this install). So +1 to revbump for ffmpeg6 from me. :)

**Comment by humdingerb** [comment]
Thanks, I've updated the youtube-dl and yt-dl packages accordingly.

**Comment by Begasus** [comment]
+1 saw it :)
