### ISSUE TITLE
Broken Otter browser

### ISSUE THREAD

**Issue by kim1963** [haikuports/haikuports#10836]
![screenshot313](https://github.com/user-attachments/assets/d135a1ec-3f75-4847-bcca-9c1b2d9c9622)

hrev57937+36 64 bit

**Comment by kim1963** [comment]
After update Qt5 .hpkg to version 5.15.14-2

**Comment by lonemadmax** [comment]
The logs show libQt5Core wanting libcrypto.so and libssl.so.
Workaround: softlink the versioned files from somewhere in LIBRARY_PATH.
In my case (32-bit Haiku):
```
ln -s /boot/system/lib/x86/libcrypto.so.3 /boot/home/config/non-packaged/lib/x86/libcrypto.so
ln -s /boot/system/lib/x86/libssl.so.3 /boot/home/config/non-packaged/lib/x86/libssl.so
```

That will probably also work for similar issues with other apps.

**Comment by Begasus** [comment]
Confirmed fixes launch for Tokodon on 64bit too.
