### ISSUE TITLE
postgresql package conflict with each other

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#10855]
Trying a new build for qgis (with other changes in the background) I got this on launch:

```
~> /boot/system/apps/QGIS/QGIS
runtime_loader: /boot/system/lib/libpq.so: Could not resolve symbol 'scram_SaltedPassword'
resolve symbol "scram_SaltedPassword" returned: -2147478780
runtime_loader: /boot/system/lib/libpq.so: Troubles relocating: Symbol not found
```

Looking into the library I saw it was provided by postgresql12 (which doesn't provide the symbol), I then saw I had also postgresql11 installed which does provide the symbol, uninstalling postgresql solved the problem.

EDIT, both packages provide the same libraries (no SONAMEs involved to seperate them from each other).

**Comment by waddlesplash** [comment]
There should definitely be CONFLICTS entries here, yes.

**Comment by Begasus** [comment]
I don't think it's widely used, need some testing against them, maybe make postgresql12 the default one?
Or even mute the older ones? (given that a rebuild with v12 still works for qgis or others)

**Comment by Begasus** [comment]
Fixed in: https://github.com/haikuports/haikuports/pull/10990
