### ISSUE TITLE
games-emulation/melonds/melonds-0.9.5.recipe (cmake does not find libarchive)

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#10877]

**Comment by Begasus** [comment]
First guess is that libarchive is missing a requirement for _devel "devel:libiconv$secondaryArchSuffix"
Error for melonds is:
```
--   Package 'iconv', required by 'libarchive', not found
```
cmake doesn't know how to find it even when added  in melonds recipe, so probably needs to be added in the one for libarchive?

**Comment by waddlesplash** [comment]
We should really patch pkg-config to not export `Requires.private` by default. It's only useful when statically linking, in general. They used to not do this but then changed the behavior years ago, if memory serves, but I can't remember the full reasons for it.

**Comment by pulkomandy** [comment]
According to https://github.com/mesonbuild/meson/issues/3970 , pkg-config exposes cflags from Requires.private, but not libraries. And pkgconf behaves differently. Should we try to switch things to use pkgconf instead of pkg-config?

**Comment by pulkomandy** [comment]
I added devel:libiconv to the requirements of melonds, but it doesn't help. The libiconv_devel package does not include a pkg-config file.

**Comment by Begasus** [comment]
> First guess is that libarchive is missing a requirement for _devel `devel:libiconv$secondaryArchSuffix` Error for melonds is:
> 
> ```
> --   Package 'iconv', required by 'libarchive', not found
> ```
> 
> cmake doesn't know how to find it even when added in melonds recipe, so probably needs to be added in the one for libarchive?
> 
> EDIT: from the libarchive pkgconfig file: `Requires.private: iconv libcrypto`

Even adding it to libarchive in REQUIRES_devel didn''t work here, maybe just add a manual pkgconfig file, isn't the first time it's being done.

**Comment by Begasus** [comment]
Did a check with adding a pkgconfig file for iconv, seems to work finding libarchive:
```
	# Add pkgconfig file
	mkdir -p $developLibDir/pkgconfig
	cat > $developLibDir/pkgconfig/iconv.pc << EOF
bindir=$prefix/bin
exec_prefix=$prefix
libdir=$libDir
includedir=$includeDir

Name: libiconv
Description: $SUMMARY
Version: $portVersion
Libs: -L$developLibDir -liconv -lcharset
Cflags: -I$includeDir
EOF
```

**Comment by Begasus** [comment]
Fixed in: https://github.com/haikuports/haikuports/pull/11001
