### ISSUE TITLE
No profiling support in Clang / LLVM

### ISSUE THREAD

**Issue by johnsonjh** [haikuports/haikuports#10992]
Required libraries seem missing / not built:

`$ clang -fprofile-generate test.c`
`ld.lld: error: cannot open /boot/system/lib/clang/17/lib/haiku/libclang_rt.profile-x86_64.a: No such file or directory`

**Comment by johnsonjh** [comment]
Same win LLVM 18:

`
ld.lld: error: cannot open /boot/system/lib/clang/18/lib/haiku/libclang_rt.profile-x86_64.a: No such file or directory`

**Comment by korli** [comment]
Please check with 18.1.7-3 (https://github.com/haikuports/haikuports/commit/d8bb561bb8952f1e8da71b82bbcb69e94e887507)

**Comment by johnsonjh** [comment]
@korli Tested.  It works!  It would be cool to have old versions fixed too like Clang 17 but that isn't necessary for my purposes.

I'll close the issue.

**Comment by korli** [comment]
18.1.7-3 on x86 also available
