### ISSUE TITLE
libotr build is broken

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#1100]
It tries to use the stack protector, which still doesn't work in our version of gcc5.

**Comment by korli** [comment]
Please check with f9d8797279fa9c4796b43a6986a6cc26c478ad40.

**Comment by pulkomandy** [comment]
aes.o: In function `aes_gen_tables':
/sources/libotr-4.1.0/toolkit/aes.c:69: undefined reference to `__stack_chk_guard'
/sources/libotr-4.1.0/toolkit/aes.c:139: undefined reference to `__stack_chk_fail_local'
aes.o: In function `aes_set_key':
/sources/libotr-4.1.0/toolkit/aes.c:440: undefined reference to `__stack_chk_guard'
/sources/libotr-4.1.0/toolkit/aes.c:586: undefined reference to `__stack_chk_fail_local'
aes.o: In function `aes_encrypt':
/sources/libotr-4.1.0/toolkit/aes.c:591: undefined reference to `__stack_chk_guard'
/sources/libotr-4.1.0/toolkit/aes.c:676: undefined reference to `__stack_chk_fail_local'
aes.o: In function `aes_decrypt':
/sources/libotr-4.1.0/toolkit/aes.c:681: undefined reference to `__stack_chk_guard'
/sources/libotr-4.1.0/toolkit/aes.c:766: undefined reference to `__stack_chk_fail_local'
/boot/system/develop/tools/x86/bin/../lib/gcc/i586-pc-haiku/5.4.0/../../../../i586-pc-haiku/bin/ld: .libs/otr_readforge: hidden symbol `__stack_chk_fail_local' isn't defined
/boot/system/develop/tools/x86/bin/../lib/gcc/i586-pc-haiku/5.4.0/../../../../i586-pc-haiku/bin/ld: final link failed: Bad value

**Comment by fbrosson** [comment]
@pulkomandy, you might have forgotten to clean your work dir.

When I build libotr_x86-4.1.0 on x86_gcc2 everything is OK, and I get the hpkgs:
```Shell
$ ls -go libotr_x86*-4.1.0-2-x86_gcc2.hpkg
-rw-r--r-- 1 243113 Feb  5 19:26 libotr_x86_devel-4.1.0-2-x86_gcc2.hpkg
-rw-r--r-- 1 258159 Feb  5 19:26 libotr_x86-4.1.0-2-x86_gcc2.hpkg

$ package info libotr_x86-4.1.0-2-x86_gcc2.hpkg
name: libotr_x86  version: 4.1.0-2

$ package info libotr_x86_devel-4.1.0-2-x86_gcc2.hpkg
name: libotr_x86_devel  version: 4.1.0-2
```

**Comment by korli** [comment]
Is it still a problem?
