### ISSUE TITLE
gcc_fortran: missing dependency on gcc

### ISSUE THREAD

**Issue by jmairboeck** [haikuports/haikuports#11011]
When just having `cmd:gfortran$secondaryArchSuffix` in BUILD_PREREQUIRES (i.e. no gcc), gfortran doesn't work. It is missing libmpc.so.3 to start, and at the end of the compilation complains about missing liblto_plugin.so, which is in the main gcc package. So that should be added to the requirements of gcc_fortran, and maybe `lib:libmpc$secondaryArchSuffix` too to be explicit. (didn't haikuporter complain about that with a policy warning?)

**Comment by mtl1979** [comment]
This seems easy to verify using for example `dev-tex/pmx/pmx-3.0.0.recipe` by removing the explicit prerequire for `cmd:gcc$secondaryArchSuffix`. Other recipes on Haikuports that use gfortran seem to need either g++ or gcc in addition to gfortran.

**Comment by jmairboeck** [comment]
That was exactly the recipe where I noticed the problem with. I wrote that recipe ;)

**Comment by mtl1979** [comment]
Building gcc from sources takes quite long time, so testing why haikuporter doesn't detect the missing dependencies or what is the best fix has to wait until building gcc finishes... AFAIK, packagefs is a lot stricter with dependencies than haikuporter.
