### ISSUE TITLE
new tcpdump & libpcap for R1/beta5

### ISSUE THREAD

**Issue by infrastation** [haikuports/haikuports#11012]
tcpdump 4.99.5 and libpcap 1.10.5 are available. This stable release of libpcap includes a number of Haiku-specific bug fixes and new features that were made and tested in the development branch earlier this year. It would be useful to update both ports before R1/beta5 so that tcpdump in HaikuPorts works correctly on R1/beta5 when it is published.

Without using HaikuPorts getting a correctly working tcpdump binary is as simple as `./configure && make`, so along with the new versions let me suggest the following simplifications to the ports:
* libpcap
  * Use HTTPS in `SOURCE_URI`.
  * Do not define `_BSD_SOURCE` because libpcap build system does it automatically when necessary.
  * Do not pass `--enable-shared` to `configure` because that is the default behaviour.
  * Drop `libpcap-1.10.4.patchset` because the upstream code now implements this logic.
  * Drop `libpcap-1.10.4.gcc2.patchset` and instead of GCC 2 use a current version of GCC to compile libpcap on 32-bit Haiku because libpcap does not need binary compatibility with BeOS, but does require a C99 compiler ([previous discussion](https://github.com/the-tcpdump-group/libpcap/pull/1153#discussion_r1072102873)).
* tcpdump
  * Use HTTPS in `SOURCE_URI`.
  * Modify the build and run time dependencies on libpcap to require libpcap >= 1.10.0.
  * Drop `tcpdump-4.99.4.patchset` because the the upstream build system already includes necessary changes.

Also you may want to use `.tar.xz` for the tarballs, which are available at the same location as the `.tar.gz` tarballs.

Let me know in case you need any additional information.

**Comment by korli** [comment]
@infrastation thanks for the heads up! This should be OK on both arches:
* ATM I only switch to .tar.xz for tcpdump.
* updating tcpdump also update libpcap with libpcap >= 1.10.5
* autoconf is removed, not needed when no patching is taking place.

**Comment by waddlesplash** [comment]
> Do not define _BSD_SOURCE because libpcap build system does it automatically when necessary.

BTW this should not be necessary in general; if you are specifying `-std=c11` or something like that, the compiler defines `__STRICT_ANSI__` which turns off BSD and other extensions in headers if possible. If you use `-std=gnu11` then the compiler will not do this.

**Comment by korli** [comment]
libpcap now switched to HTTPS
