### ISSUE TITLE
falkon doesn't open

### ISSUE THREAD

**Issue by theotheroracle** [haikuports/haikuports#11037]
after installing falkon, which seemed to go fine, through the haikudepot, i'm unable to open it, getting the error message in the screenshot whenever i try
![falkon-crash](https://github.com/user-attachments/assets/981a23de-8649-4d9d-9398-9c617d9b9102)

**Comment by threedeyes** [comment]
Haiku revision, arch?

**Comment by threedeyes** [comment]
How much RAM? I see a red icon that means there is almost no free memory.

**Comment by threedeyes** [comment]
It's very strange. I tested the build on 32bit and everything works fine. Tell me the revision of Haiku it doesn't work on, I'll try to reproduce the problem.

**Comment by kenmays** [comment]
@threedeyes - I noted this when I updated to the new revision of qtwebengine_bin which immediately broke Dooble with this message on hrev58043 x86: ~> /system/apps/Dooble/Dooble
runtime_loader: /boot/system/lib/x86/libQt5WebEngineWidgets.so.5.15.17: Could not map image: Invalid Argument

**Comment by theotheroracle** [comment]
I was testing on 32bit Pentium duo, I had updated to haiku master from beta4

**Comment by theotheroracle** [comment]
my laptop also only has 512MB of ram

**Comment by korli** [comment]
You can try to increase the swap in the Virtual Memory preferences panel.

**Comment by theotheroracle** [comment]
adding swap doesn't improve things it seems

**Comment by kenmays** [comment]
@threedeyes - Possible fix is a rebuild of qt5webengine -> qt5webengine_bin. I found my qt5webengine_bin issue was with a harfbuzz library mismatch (possibly from R1B4-R1b5 repo changeover).

**Comment by Begasus** [comment]
Previous package still works if you have it around (on R1B5), so I don't think it's a harfbuzz mismatch.

**Comment by threedeyes** [comment]
The reason was quite strange. If you remove from the recipe the creation of a package containing debuginfo, the browsers start working.

**Comment by threedeyes** [comment]
> after installing falkon, which seemed to go fine, through the haikudepot, i'm unable to open it, getting the error message in the screenshot whenever i try

Install the updates and try it now please.

**Comment by Begasus** [comment]
From my side: nexcloud-client and falkon up and running again, thanks!

**Comment by kenmays** [comment]
- Falkon - working
- Dooble - working
- Epiphany - working
