### ISSUE TITLE
Update to universal ctags - ctags 5.8 is 15 years out of date

### ISSUE THREAD

**Issue by johnsonjh** [haikuports/haikuports#11054]
Hi there - the ctags 5.8 you are packaging is the 2009 release of exuberant ctags, and is no longer being updated at ctags.sf.net.

The current upstream for ctags is now universal ctags at ctags.io with the git repo moved to https://github.com/universal-ctags/ctags - this is the recognize official successor project.

ctags is currently at 6.1 (p6.1.20240901.0).  

They push release on an irregular schedule, but usually at least a new point release update every couple of weeks.

**Comment by Begasus** [comment]
Bumped to latest stable 6.1.0 in https://github.com/haikuports/haikuports/pull/11062
