### ISSUE TITLE
mailnews missing libraries

### ISSUE THREAD

**Issue by theotheroracle** [haikuports/haikuports#11050]
after installing from haikudepot, it says its missing libplds, libplc, libnspr, as shown in the screenshot . i tried reinstalling, no change . 
i'm running x86 haiku on a pentium M mobile processor, with 512MB of ram, automatic swap, and i've upgraded to the master channel from beta4 . 
![mailnews-crash](https://github.com/user-attachments/assets/919432fe-4dcc-46a6-8700-a23e00d5b2a2)

**Comment by lonemadmax** [comment]
From what I'm reading, that dependency is only defined for x86_64, while the 32bits one compiles its own version. But then it seems the [last change](https://github.com/haikuports/haikuports/commit/78d1cd4a4a8d20a8870572544310582c057a6d5a#diff-387c41b80378d5c24f6574892a587ff116f21e18ea24ee141ff1f8fb9971c87bL154-R156) removed those from the package.
I think you'd need the gcc2 libraries, which are also not available from the nspr package.

**Comment by korli** [comment]
@lonemadmax  thanks for the tip! had missed this by updating for x86_64. 
@theotheroracle  please update and test with 2.0.0.25-4

**Comment by theotheroracle** [comment]
it works !
