### ISSUE TITLE
Gutenprint 5.2.12 fails to build on x86_gcc2

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#1109]

**Comment by pulkomandy** [comment]
gutenprint-5.2.11-3-x86_gcc2.hpkg builds just fine here. Can you share a build log and the exact command line you used?

**Comment by Vidrep** [comment]
It is Gutenprint 5.2.12 that does not build on x86_gcc2

**Comment by Vidrep** [comment]
[Gutenprint_5.2.12_build_log.txt](https://github.com/haikuports/haikuports/files/753142/Gutenprint_5.2.12_build_log.txt)

**Comment by Begasus** [comment]
Probably missing some {} in the source files for gcc2? (seen these type of errors on some sources here also in the past)
