### ISSUE TITLE
libiconv hpkg file is missing

### ISSUE THREAD

**Issue by am11** [haikuports/haikuports#11134]
Repro:

1. Go to https://depot.haiku-os.org/#!/pkg/libiconv/haikuports/haikuports_x86_64/1/17/-/-/3/x86_64?bcguid=bc2-LVXG
2. Click on `Download package 'hpkg' file`

Expected behavior: file is available
Actual behavior:
<img width="996" alt="image" src="https://github.com/user-attachments/assets/b039d5b6-a810-4dec-858e-768710bef2ed">

More info: specifically this package is giving us 404 in downstream CI: https://dev.azure.com/dnceng-public/public/_build/results?buildId=805922&view=logs&jobId=c870e702-81d6-5105-d4cd-c3ac690245c9&j=c870e702-81d6-5105-d4cd-c3ac690245c9&t=af8261d5-9928-5ef5-a6dc-b15ed873ffe3, so it can download, e.g. krb5_dev successfully https://depot.haiku-os.org/#!/pkg/krb5/haikuports/haikuports_x86_64/1/20/-/-/3/x86_64?bcguid=bc2-SJDL
<img width="1706" alt="image" src="https://github.com/user-attachments/assets/ce5d69c9-c5ac-4d25-a56f-5f5a883ba2b0">

Related: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/1201

**Comment by trungnt2910** [comment]
This is confirmed to be a HaikuDepot issue, not a scripting bug.

I have tried fetching the `.hpkg` file directly from the Web UI, got the same 404 error.

![image](https://github.com/user-attachments/assets/474adeab-4967-4137-9dad-f389961151f9)

**Comment by am11** [comment]
Yup, script is working out just fine since you wrote it! 👌😎

**Comment by korli** [comment]
see https://dev.haiku-os.org/ticket/19101 
current revision: https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/libiconv-1.17-4-x86_64.hpkg
