### ISSUE TITLE
wireshark_gui-4.2.3-2-x86_64.hpkg fails to start

### ISSUE THREAD

**Issue by infrastation** [haikuports/haikuports#11135]
Reproduces on both hrev58136 (VM) and the latest R1/beta5 (PC). Neither host has a sound card, adding a virtual sound card to the VM makes no difference.
```
~> wireshark 
runtime_loader: /boot/system/bin/wireshark: Could not resolve symbol '_ZN10QAudioSink12stateChangedEN7QtAudio5StateE'
resolve symbol "_ZN10QAudioSink12stateChangedEN7QtAudio5StateE" returned: -2147478780
runtime_loader: /boot/system/bin/wireshark: Troubles relocating: Symbol not found
~>
```

**Comment by waddlesplash** [comment]
IIRC this happened previously, and a rebuild of Wireshark fixed the problem. But what changed in the Qt packages to break this symbol anyway? Shouldn't the ABI still be compatible?

**Comment by Begasus** [comment]
Thanks for reporting back :)
