### ISSUE TITLE
Nheko fails to start

### ISSUE THREAD

**Issue by theotheroracle** [haikuports/haikuports#11178]
![nheko-crash](https://github.com/user-attachments/assets/6bd884bb-b034-4e0d-a7fa-c8df5401dd7b)
when trying to launch nheko from the gui, i get the error `Failed to launch Nheko. Error: Symbol not found` ( see screenshot )
To get more info i launched from the terminal, and got 
```
runtime_loader: /boot/system/apps/Nheko: Could not resolve symbol '_ZN7QtAudio13convertVolumeEfNS_11VolumeScaleES0_'
resolve symbol "_ZN7QtAudio13convertVolumeEfNS_11VolumeScaleES0_" returned: -2147478780
runtime_loader: /boot/system/apps/Nheko: Troubles relocating: Symbol not found
```
My repos:
```
        BeSly Software Solutions
                base-url:  https://software.besly.de/repo
                identifier: tag:besly.de,2020:happy
                priority:  2
        FatElk
                base-url:  http://fatelk.com/repo
                identifier: http://fatelk.com/repo
                priority:  1
        Haiku
                base-url:  https://eu.hpkg.haiku-os.org/haiku/master/x86_gcc2/current
                identifier: tag:haiku-os.org,2001:repositories/haiku/master/x86_gcc2
                priority:  1
        HaikuPorts
                base-url:  https://eu.hpkg.haiku-os.org/haikuports/master/x86_gcc2/current
                identifier: tag:haikuports.org,2013:repositories/haikuports/master/x86_gcc2
                priority:  1
```

**Comment by Begasus** [comment]
Checking, maybe needs a rebuild.

**Comment by mtl1979** [comment]
This is known issue in Qt 6, rebuild will fix it...

**Comment by Begasus** [comment]
> This is known issue in Qt 6, rebuild will fix it...

Building up on fixing it, there was a cycling dependency for libfmt and spdlog. Fix coming up, doing a rebuild again with newly build packages from the depot to be sure.

**Comment by Begasus** [comment]
Should be fixed with: https://github.com/haikuports/haikuports/pull/11186

@theotheroracle could you check again?

**Comment by theotheroracle** [comment]
works great now !
