### ISSUE TITLE
Globe crashes at launch

### ISSUE THREAD

**Issue by tmtfx** [haikuports/haikuports#11171]
Globe crashes as soon as it is launched. (here on hrev 58179 x86_64)
I downloaded the source and compiling I found a problem on RHTMLbmenu
error:
RHTML_bmenu.cpp:423:22: error: narrowing conversion of '128' from 'int' to 'cha' [-Wnarrowing]

it seems that it's easily fixed changing `char cursordata[]` to `unsigned char cursordata[]`

then the program compiles without error and it runs without the above described crash.

[PATCH.txt](https://github.com/user-attachments/files/17175350/PATCH.txt)

**Comment by tmtfx** [comment]
Oops, sorry, you are right!
Just opened there with a link to this patch

**Comment by korli** [comment]
the package will be rebuilt with the patch when the builder are back ( see f4eafaeae36aa73fde376c88e247d4ad192d9652 ).
