### ISSUE TITLE
Python ctypes find_library runs ldconfig

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#1120]
ldconfig isn't available on Haiku, hence the need to implement an Haiku version of this function.

Tested on x86_64, with Python 3.5.2.
retext uses this function to find libxcb for instance.

**Comment by phoudoin** [comment]
does calling find_paths a good alternative? I'm not used yet to what find_paths can and can't do, but according the -r option, one can use it to find a named library in a set off known places, right?

**Comment by pulkomandy** [comment]
Yes, find_paths could achieve a similar effect in Haiku. There even is an API for it (BPathFinder), so we could use that instead of running an executable.

**Comment by phoudoin** [comment]
I was considering about implementing this in python's ctypes/util.py directly.
But in fact searching in each $LIBRARY_PATH env variable seems to be a better way. 

I guess the %A placeholder must be mapped to current working directory here, though.

I also don't know how to handle secondary architecture case...

**Comment by pulkomandy** [comment]
%A should be mapped to the directory of the exectuable currently running (you can get this using get_image_info). It is not the same as the current working directory.

The secodnary architecture simply adds the architecture as a sub-directory to all the paths. You can look at the BPathFinder implementation, if you really want to rewrite it in Python.

**Comment by phoudoin** [comment]
I means what should be the expected behavior in such case:

``wrapper.py
lib/
  libtowrap.so
``
with in wrapper.py:
``
from ctypes.util import find_library
path = find_library("towrap")

?

From python runtime pov, mapping %A to current script directory would make more sense I guess than the directory of python interpreter, no?

**Comment by phoudoin** [comment]
Proposition of python27 patch to add an Haiku specific implementation of find_library() in ctypes.util module.

It search in $LIBRARY_PATH order (same as does the runtime_loader) and handle %A/lib as either initial script directory or, if no script (interactive interpreter), the current working directory.

It does NOT:
-  handle secondary architecture 
- handle versioned SONAME (ideally it should return the full path of the most recent version of the library found).

Tell me if it make sense enough before I try to add those missing features...

**Comment by phoudoin** [comment]
```
--- python27-ctypes-util.py	2017-04-06 04:23:56.711720960 +0000
+++ new-python27-ctypes-util.py	2017-05-18 15:34:33.560201728 +0000
@@ -232,6 +232,30 @@
         def find_library(name, is64 = False):
             return _get_soname(_findLib_crle(name, is64) or _findLib_gcc(name))
 
+    elif sys.platform.startswith("haiku"):
+
+        def find_library(name):
+	        
+            for directory in os.environ['LIBRARY_PATH'].split(os.pathsep):
+                if directory.startswith("%A/"):
+                    if sys.argv[0]:
+                    	local_dir = os.path.dirname(os.path.abspath(sys.argv[0]))
+                    else:
+                        local_dir = os.getcwd()
+                    directory = directory.replace('%A', local_dir)
+                fname = os.path.join(directory, name)
+                if os.path.isfile(fname):
+                    return fname
+                fname = os.path.join(directory, "lib%s" % name)
+                if os.path.isfile(fname):
+                    return fname
+	
+                fname = os.path.join(directory, "lib%s.so" % name)
+                if os.path.isfile(fname):
+                    return fname
+
+            return None
+
     else:
 
         def _findSoname_ldconfig(name):
@@ -299,6 +323,11 @@
             print cdll.LoadLibrary("libcrypto.dylib")
             print cdll.LoadLibrary("libSystem.dylib")
             print cdll.LoadLibrary("System.framework/System")
+        elif sys.platform.startswith("haiku"):
+            print find_library("root")
+            print find_library("be")
+            print find_library("tracker")
+            print find_library("media")
         else:
             print cdll.LoadLibrary("libm.so")
             print cdll.LoadLibrary("libcrypt.so")
```

**Comment by phoudoin** [comment]
The builtin test produces this output with this patched version:

```
~> python util.py
None
None
None
/boot/system/lib/libroot.so
/boot/system/lib/libbe.so
/boot/system/lib/libtracker.so
/boot/system/lib/libmedia.so
```

**Comment by phoudoin** [comment]
Will rework it, as finding the latest version of the library is needed per specification.

**Comment by phoudoin** [comment]
Okay, I've a working implementation. Made for python 2.7. 
Which python 3.x should I patch too in priority?

If patched version works as expected, will see to push it upstream.

**Comment by phoudoin** [comment]
Will patch python. 3.5.2 too

**Comment by phoudoin** [comment]
Python 3.6.1, actually.

**Comment by phoudoin** [comment]
I also map "c" and "m" library to libroot.so on Haiku. If it can help some python modules expecting to be able to bind some libc or libm api, well...
