### ISSUE TITLE
libresprite: gui.xml not found

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#11226]
When trying to start libresprite, it says "gui.xml was not found"

**Comment by Begasus** [comment]
still with the updated one? that should be fixed :) will check

**Comment by Begasus** [comment]
Quick fix, create a "data" directory in /boot/home/config/settings/libresprite, move all other parts in that directory into the data one.
A quick test to show the error is to launch this one in Terminal with "libresprite --debug", it saves the debug info in a file on the Desktop that shows the correct path, guess I still had an error in the postinstall script.
Will fix (again) :) in the morning.
