### ISSUE TITLE
POLICY ERROR in cpctools-0.3.0-4 and lbreakout2-2.6.5 and links-2.8

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#1125]
POLICY ERROR: "bin/png2crtc" needs library "libpng16.so.16", but the package doesn't seem to declare that as a requirement

**Comment by scottmc** [comment]
POLICY ERROR: "/packaging/lbreakout2/bin/lbreakout2" needs library "libpng16.so.16"

**Comment by fbrosson** [comment]
cpctools-0.3.0 fixed in f236353c848aa2f92e86f6c8fbd52aec3564c8ec.

**Comment by scottmc** [comment]
POLICY ERROR: "/packaging/links/bin/links" needs library "libpng16.so.16"

**Comment by scottmc** [comment]
These might be fixed in master, but should then be submitted to release as Pull Request(s)

**Comment by scottmc** [comment]
Also libusb and libwebp need their latest versions submitted to Release as Pull Requests.  These should fix a few of the buildbot issues.

**Comment by fbrosson** [comment]
- [x] lbreakout2: #1127.
- [ ] links-2.8
