### ISSUE TITLE
minestest not running on latest master

### ISSUE THREAD

**Issue by theotheroracle** [haikuports/haikuports#11289]
whenever i try to launch minetest, it crashes instantly

[Minetest-456-debug-30-10-2024-20-14-54.report](https://github.com/user-attachments/files/17578638/Minetest-456-debug-30-10-2024-20-14-54.report.txt)

Intel Pentium M @ 1.50GHz
2048 MiB Memory

```
~> pkgman list-repos
        BeSly Software Solutions
                base-url:  https://software.besly.de/repo
                identifier: tag:besly.de,2020:happy
                priority:  2
        FatElk
                base-url:  http://fatelk.com/repo
                identifier: http://fatelk.com/repo
                priority:  1
        Haiku
                base-url:  https://eu.hpkg.haiku-os.org/haiku/master/x86_gcc2/current
                identifier: tag:haiku-os.org,2001:repositories/haiku/master/x86_gcc2
                priority:  1
        HaikuPorts
                base-url:  https://eu.hpkg.haiku-os.org/haikuports/master/x86_gcc2/current
                identifier: tag:haikuports.org,2013:repositories/haikuports/master/x86_gcc2
                priority:  1
```

**Comment by Begasus** [comment]
Still OK on R1B5 64bit:

![minetest](https://github.com/user-attachments/assets/e523f8be-6f03-4f8e-82f2-afa0aee6f202)

**Comment by mtl1979** [comment]
The debug log is missing symbols in critical place, but it clearly hits some assertion failure inside libstdc++ when reading settings. This suggests there is something corrupted in the settings. Possibly if it is started from Terminal, it will print the actual assertion that fails.

**Comment by jmairboeck** [comment]
I updated minetest to the latest version and also fixed the build type to generate the correct debug information in #11302. It starts and seems to work, but it would be good if someone could test this properly please.

**Comment by theotheroracle** [comment]
when running from terminal, it outputs:
```
~> /boot/system/apps/Minetest/Minetest 
terminate called after throwing an instance of 'SettingNotFoundException'
  what():  Setting [help] not found.
Abort
Kill Thread
```

**Comment by mtl1979** [comment]
> when running from terminal, it outputs:
> ```
> ~> /boot/system/apps/Minetest/Minetest 
> terminate called after throwing an instance of 'SettingNotFoundException'
>   what():  Setting [help] not found.
> Abort
> Kill Thread
> ```

That's unhandled exception... Might want to check that on the original repository.... Some times this kind of errors are already fixed if there is newer version available. If not, should be reported there.

**Comment by theotheroracle** [comment]
@jmairboeck i tested your code, and it doesn't crash on my machine ! i was also able to get into the game as well, albeit at an abysmal framerate, but that's probably just my poor hardware :)

**Comment by jmairboeck** [comment]
> @jmairboeck i tested your code, and it doesn't crash on my machine ! i was also able to get into the game as well, albeit at an abysmal framerate, but that's probably just my poor hardware :)

It looks like the new version uses OpenGL 3, while the old version is supposed to use OpenGL ES 2, if I understand it correctly. Maybe it performed better before.

Thanks for testing though, I'll merge my PR then.
