### ISSUE TITLE
cbindgen: bump == 0.26.0

### ISSUE THREAD

**Issue by kenz-gelsoft** [haikuports/haikuports#11285]
Can I request bumping cbindgen here?

If it bumps to exactly 0.26, helpful to me for packaging current firefox port.

https://discuss.haiku-os.org/t/progress-on-porting-firefox/13493/238?u=kenz

@kenmays I read your latest update to the recipe and understand how it works, so maybe I can update recipe myself. But if you have any tool to ease updating dependency crate URLs and checksums, can I ask you updating it?

**Comment by kenmays** [comment]
@kenz-gelsoft - Your nose is closer to the Firefox wheels than mine. Feel free to update cbindgen as needed.

**Comment by kenz-gelsoft** [comment]
OK I will give a try!

**Comment by korli** [comment]
> OK I will give a try!

Never tried myself but this tool is supposed to help: https://github.com/haikuports/haikuporter/blob/master/tools/cargo-to-recipe.sh

**Comment by Begasus** [comment]
Last time I tried it it failed on me @korli :) But doesn't hurt to try.

**Comment by Begasus** [comment]
PR created at: https://github.com/haikuports/haikuports/pull/11290 not checked on 32bit (yet).

**Comment by kenz-gelsoft** [comment]
@korli Thanks for the info!

@Begasus Oh, and thanks for the quick work before I start to work!

I expected many SOURCE_URI_NN like original, but could it be simplified like this?

**Comment by kenz-gelsoft** [comment]
Started building firefox cleanly with your test package.

Will post the test result tonight (15-16 hrs later).

I uninstalled cbindgen version
```
~/src/gecko-dev> which cbindgen
/bin/cbindgen
```
configure step find cbindgen correctly
```
 0:06.68 checking for cbindgen... /bin/cbindgen
```

**Comment by kenz-gelsoft** [comment]
Test package could be used successfully to build firefox. I'm OK with this!

**Comment by Begasus** [comment]
Build completed for both arch's on buildmasters, closing. :)
