### ISSUE TITLE
libssh2 1.11

### ISSUE THREAD

**Issue by jackburton79** [haikuports/haikuports#11292]
Any reason why libssh2 is stuck at version 1.9 which was released in 2021 ?

**Comment by Begasus** [comment]
Related: https://github.com/haikuports/haikuports/pull/10976

**Comment by jackburton79** [comment]
Tried libgit2 (with Genio) and works correctly.
Actually, works much better, since it resolves https://github.com/Genio-The-Haiku-IDE/Genio/issues/394

**Comment by Begasus** [comment]
Thanks, been running (installed) it for about a week, no downside here.

**Comment by jackburton79** [comment]
Works great!
