### ISSUE TITLE
fish: issues with the 32 bits package.

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#11300]
Currently, `fish_x86-3.7.1-1_x86_gcc2.hpkg` contains:

```
bin/
    x86/
        fish
        fish_indent
        fish_key_reader
    fish-x86                (links to x86/fish)
    fish_indent-x86         (links to x86/fish_indent)
    fish_key_reader-x86     (links to x86/fish_key_reader)
```

It would be better to just have the executables under /bin (recipe uses `!x86_gcc2`).

Also, it contains the following unnecessary files:
   - data/applications/fish.desktop
   - data/pixmaps/fish.png

I've tried adding `-DCMAKE_INSTALL_BINDIR=bin`, and while that moves the executable to the right place, it also breaks the rest of the install, as the `fish` folder that should be under `data`, ends up under `data/applications` instead, and the `pkgconfig/fish.pc` that should also be under `data`, ends up under `data/pixmaps` 8-|

I guess I could just `mv` files around and remove the symlinks (who creates those, anyway, haikuporter?), but there should be a better way, right?

**Comment by jmairboeck** [comment]
> I guess I could just `mv` files around and remove the symlinks (who creates those, anyway, haikuporter?),

The symlinks are created automatically by haikuporter here: https://github.com/haikuports/haikuporter/blob/a7cef38f2aaf7d54f0c230bb1c1866c197edf39d/HaikuPorter/Port.py#L1445-L1455

**Comment by mtl1979** [comment]
> Also, it contains the following unnecessary files:
> 
> * data/applications/fish.desktop
> * data/pixmaps/fish.png
> 

`cmake/Install.cmake` has test `NOT APPLE` which should exclude Haiku too...

**Comment by augiedoggie** [comment]
> `cmake/Install.cmake` has test `NOT APPLE` which should exclude Haiku too...

That means it includes Haiku.  It should be `NOT APPLE AND NOT HAIKU`

**Comment by mtl1979** [comment]
> Contributor

Yup... Other bad stuff in same file regarding target directory of pkgconfig file.
