### ISSUE TITLE
guile 3.0.10 x86 failed to build on buildmaster

### ISSUE THREAD

**Issue by jmairboeck** [haikuports/haikuports#11325]
It failed to build during the "GEN guile-procedures.texi" build step, without any concrete error message: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/7053/builds/84776.log

The build rule `cat`s together some files and pipes them into the `guile` interpreter: https://git.savannah.gnu.org/cgit/guile.git/tree/libguile/Makefile.am#n848

Locally (in a beta5 x86 VM), the build works fine. Could it be that `guile` just crashes?

**Comment by jsteinaker** [comment]
Build failing in the same place ("GEN guile-procedures.texi") on x86_64, latest Nightly. lt-guile crashes, Debugger points to libgc (boehm_gc), specifically a malloc. Coincidentally, this is the same library that is making GnuCash crash on startup. Also, I just checked and Guile 2.2 build is failing at the same step.

From what the forums say, this is the first step in the build process the guile executable just builded is used, so the crash is not necessarily related to guile-procedures.texi but the Guile executable itself.

**Comment by jmairboeck** [comment]
Thanks @jsteinaker. I could reproduce the crash on x86_64 nightly too now. It looks like there is some problem with malloc in boehm_gc indeed. I don't know how to fix it though.

It did work in the past, as there is a package for guile-3.0.10 on x86_64, and I also built it locally before. Maybe a downgrade of boehm_gc would work?

**Comment by jsteinaker** [comment]
I just tried downgrading to 8.2.6 and it didn't help (neither Guile compilation or GnuCash runtime). Since 8.2.6 is on Haikuports since February and the last Guile 3 package was built succesfully on August, I'm guessing boehm_gc is not the problem (otherwise 8.2.6 should work), but instead a change that was made on Haiku itself. Time to file a bug report maybe?

**Comment by jmairboeck** [comment]
If I understood it correctly, libatomic_ops is only used as a fallback. By default, it uses compiler intrinsics, and these are used on Haiku too.

**Comment by jsteinaker** [comment]
Worth retesting after @waddlesplash patches in Boehm-GC 8.2.8-2, as  they fix all crashes in GnuCash and they were very possibly Guile-related.
