### ISSUE TITLE
es-de issue for reading mp4 media

### ISSUE THREAD

**Issue by DigitalBox98** [haikuports/haikuports#11345]
When scrapping media for ZX Spectrum game "Chuckie Egg", the mp4 video downloaded is producing a crash in the application when trying to launch the game via ES DE

Workaround : remove the mp4 video from the /boot/home/ES-DE/downloaded_media/videos/Checkie Egg.mp4 and then ES DE is no more producing a crash

Note : the mp4 video is OK outside of ES DE

**Comment by Begasus** [comment]
Is the video part of the ES-DE package? If so that would be an easy fix (if it doesn't brake anything else).

**Comment by Begasus** [comment]
OK, nothing we can handle from our side then?

**Comment by DigitalBox98** [comment]
I will double check if the issue is relative to the video media first to confirm

**Comment by DigitalBox98** [comment]
Ok, I didn't notice this issue on another OS, and looking in the debugger I can see that VideoCodecContext->pix_fmt is returning -1 in VideoFFmpegComponent.cpp

To be investigated : is av_get_pix_fmt_name() (in libavutil ?) handling well this kind of value, because it seems to be this line which is returning a segmentation fault (see below).

So not relative to es-de, but a side effect from another lib I guess.

![debug](https://github.com/user-attachments/assets/fd838e24-68b9-4843-ba74-ebbd85875b8d)

**Comment by DigitalBox98** [comment]
After checking : 
- This is relative on how ES-DE handle unknown "pix_fmt" : the current code is not enough robust, and it's not relative to haikuports -> I will close this issue as it must be handled at ES-DE source repo level 
- On other platforms, the corresponding video isn't problematic, so I guess the "pix_fmt" is returning a recognized format while on Haiku the format is NONE (-1)
The mix of both is creating this error
