### ISSUE TITLE
Web (epiphany) crash when copy/paste text in searchbar

### ISSUE THREAD

**Issue by andianton** [haikuports/haikuports#11358]
When you try to copy/paste text from the serch bar, both epiphany and nightly browser apps crashes.

 Steps to repro the issue:

 - open web (epiphany)
 - write something în search bar (it doesnt matter what)
 - select text and copy
 - then try to paste it in the search bar
 - notice the crash

 Note: this happens both on web app and nightly

**Comment by waddlesplash** [comment]
If you're using Nightly, that means you have the experimental Wayland server package installed. I think this may be a known bug with that version? CC @X547.

**Comment by kenz-gelsoft** [comment]
Yes that is known bug of wayland-server custom build I and 3dEyes distributes.

I made a PR fixed this problem and GNOME Web regression. Waiting review.

https://github.com/X547/wayland-server/pull/7

**Comment by kenz-gelsoft** [comment]
This will be fixed by  #11368
