### ISSUE TITLE
librecad crashes on exit

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#1140]
[LibreCAD-56295-debug-04-02-2017-04-00-33.report.txt](https://github.com/haikuports/haikuports/files/752086/LibreCAD-56295-debug-04-02-2017-04-00-33.report.txt)

**Comment by korli** [comment]
Using muparser as a system lib instead of the included one might help (yet to be written dev-cpp/muparser). This is at least what Linux distributions do.

**Comment by korli** [comment]
A recipe now exists for muparser: https://github.com/haikuports/haikuports/blob/master/dev-cpp/muparser/muparser-2.2.5.recipe

**Comment by korli** [comment]
fixed in 3c85c62e29f7aef2397647597414561011f04df3
