### ISSUE TITLE
subversion: missing symbol error from libserf

### ISSUE THREAD

**Issue by augiedoggie** [haikuports/haikuports#11414]
Subversion is crashing for me on x86_64 nightly and x86 beta5.  I tried a quick rebuild of both subversion and serf but it didn't seem to fix the problem.

The missing symbol is from openssl 1.x, but serf and subversion seem to be using openssl 3.
```
runtime_loader: /boot/system/lib/libserf-1.so.1.3.0: Could not resolve symbol 'ERR_GET_FUNC'
resolve symbol "ERR_GET_FUNC" returned: -2147478780
runtime_loader: /boot/system/lib/libserf-1.so.1.3.0: Troubles relocating: Symbol not found
```

**Comment by korli** [comment]
@augiedoggie please test with serf-1.3.10.

**Comment by augiedoggie** [comment]
seems ok, thanks @OscarL
