### ISSUE TITLE
Iceweasel_bin: Missing library

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#11420]
I just installed Iceweasel_bin 128.5.0-1. Doesn't launch. From Terminal:

```
XPCOMGlueLoad error for file /boot/system/apps/Iceweasel/libxul.so:
Missing library
Couldn't load XPCOM.
```

**Comment by diversys** [comment]
cat /var/log/syslog should show which library is missing

**Comment by Begasus** [comment]
Launches OK here from Terminal (R1B5 64bit).

**Comment by humdingerb** [comment]
syslog says:

`KERN: runtime_loader: Cannot open file libdbus-1.so.3 (needed by /boot/system/apps/Iceweasel/lib/libxul.so): No such file or directory
`

But trying to start Iceweasel again doesn't add this line again...

**Comment by Begasus** [comment]
So you have libdbus installed? :) here is the list from readelf: https://bpa.st/OXAA

**Comment by kenz-gelsoft** [comment]
Indeed it start failing to launch after uninstalling dbus. I'll fix recipe.

**Comment by humdingerb** [comment]
Bloody dbus. :)
Some app needed it before and the stupid thing delayed (or crashed? can't remember...) every shutdown.

**Comment by kenz-gelsoft** [comment]
Sorry for catching this. Thank you for reporting @humdingerb !

**Comment by kenz-gelsoft** [comment]
I confirmed that 128.5.0-2 now requires dbus on installing.

![IceweaselNowRequiresDbus](https://github.com/user-attachments/assets/599e0193-5aed-4696-b525-f1bb9b34ef90)

**Comment by Begasus** [comment]
Libevent missing also.

**Comment by waddlesplash** [comment]
Hmm, how didn't HaikuPorter catch these and show policy warnings?

**Comment by kenz-gelsoft** [comment]
> libevent (needed for launch) missing also.
> 
> ```
> KERN: runtime_loader: Cannot open file libevent-2.1.so.7 (needed by /boot/system/apps/Iceweasel/lib/libxul.so): No such file or directory
> ```

Thank you for investigating this! As I am AFK now, I will update recipe tonight (10hr later or so).

> EDIT:
> 
> These don't stop from launching, but maybe worth to have a look at?
> 
> ```
> KERN: runtime_loader: Cannot open file /boot/system/apps/Iceweasel/libosclientcerts.so (needed by /boot/system/lib/libnspr4.so): No such file or directory
> KERN: runtime_loader: Cannot open file libcanberra.so.0 (needed by /boot/system/lib/libnspr4.so): No such file or directory
> ```

I feel this dependency should be specified in the nspr package, but should my recipe also add this?

**Comment by kenz-gelsoft** [comment]
> Hmm, how didn't HaikuPorter catch these and show policy warnings?

Probably I saw these warnings when I used non-_bin package, but I missed or took serionsly.

After I made a _bin recipe, I merery use non-_bin recipe as it took much longer time to build by requiring fresh source tree and initializing git repo for work tree for any small changes.

**Comment by waddlesplash** [comment]
HaikuPorter should generate these warnings even when building the `_bin` package, I think? It should generate them by scanning the libraries and binaries actually in the package.

**Comment by kenz-gelsoft** [comment]
> HaikuPorter should generate these warnings even when building the `_bin` package, I think? It should generate them by scanning the libraries and binaries actually in the package.

Thanks for the info. I will check this closely next time execute haikuporter.

**Comment by Begasus** [comment]
> Hmm, how didn't HaikuPorter catch these and show policy warnings?

My guess is that they are not caught in default paths, there are others that suffer from this (eg plugins).

**Comment by Begasus** [comment]
> > EDIT:
> > These don't stop from launching, but maybe worth to have a look at?
> > ```
> > KERN: runtime_loader: Cannot open file /boot/system/apps/Iceweasel/libosclientcerts.so (needed by /boot/system/lib/libnspr4.so): No such file or directory
> > KERN: runtime_loader: Cannot open file libcanberra.so.0 (needed by /boot/system/lib/libnspr4.so): No such file or directory
> > ```
> 
> I feel this dependency should be specified in the nspr package, but should my recipe also add this?

The first one is a included library from the package, the second one canberra is not even in haikuports or in any dependency, it's disabled for a few.
So not sure how they would be connected to nspr.
PS. shouldn't stop the release, but could be worth investigating.

**Comment by kenz-gelsoft** [comment]
> > libevent (needed for launch) missing also.
> > ```
> > KERN: runtime_loader: Cannot open file libevent-2.1.so.7 (needed by /boot/system/apps/Iceweasel/lib/libxul.so): No such file or directory
> > ```
> 
> Thank you for investigating this! As I am AFK now, I will update recipe tonight (10hr later or so).

done in #11424

no more warnings in haikuporter build, I hope I can close this.

**Comment by Begasus** [comment]
Thanks, time for some smoke testing ;)

**Comment by kenz-gelsoft** [comment]
A tester suggests installing pciutil, but I could launch iceweasel without pciutil.

https://discuss.haiku-os.org/t/iceweasel-does-not-open-after-installation/16049/2?u=kenz

**Comment by Begasus** [comment]
First run did crash :) (mind you I was  playing music through YT while installing uBlock), playing nice and uBlock working. 👍 
Not sure how pciutils comes in.
