### ISSUE TITLE
 Iceweasel: config is stored in wrong location.

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#11423]
Config files are currently stored in `~/.mozilla`, but should be shored in `~/config/settings/Mozilla`. It is a bad practice to pollute home directory with dot files in Haiku.

CC: @kenz-gelsoft

**Comment by kenz-gelsoft** [comment]
Notes for myself
- https://www.haiku-os.org/docs/api/FindDirectory_8h.html#aa10135f62098fc92d18c653a1fff9c0ea45391fd2c9fb9279f385ccf787d8a078

**Comment by kenz-gelsoft** [comment]
I changed config path as intended locally, but nsXREDirProvider has some other related paths lower-cased, dot-prepended. I am considering those.

**Comment by kenz-gelsoft** [comment]
There are more UNIX path depending code than I previously searched in https://github.com/haikuports/haikuports/issues/11423#issuecomment-2527880283
- [getenv("HOME")](https://searchfox.org/mozilla-esr128/search?q=getenv%28%22HOME%22%29&path=&case=false&regexp=false)

**Comment by waddlesplash** [comment]
The XDG directory handling should work, as Haiku does set XDG variables, I think.

**Comment by kenz-gelsoft** [comment]
I should finished code change in my branch, but I am testing and preparing migration steps from previous version.

Probably I'll commit and make a PR on this tonight.

**Comment by kenz-gelsoft** [comment]
Migration step
```
~> rm -rf config/settings/Mozilla/
~> cp -R .mozilla config/settings/Mozilla
~> mv config/settings/Mozilla/{f,F}irefox/
~> mv config/settings/Mozilla/{e,E}xtensions/
```
