### ISSUE TITLE
python3 missing _ctypes

### ISSUE THREAD

**Issue by tidux** [haikuports/haikuports#1143]
Setuptools, Pip, etc. are not packaged for python3 yet, and attempting to install them manually yields the following error:

`no such module named _ctypes`

This makes Python3 modules effectively unusable.

**Comment by korli** [comment]
python3 is mistakenly marked as buildable on x86_gcc2. Just use x86 or x86_64 for the time being.
See 3cc7606d17fa7741f379c38728b25ea2efa098fe and a7613f20d0d2068f8e01c6ea1c024e074ca4dad5
Reverted in 5f88e141d37b7bcc99284e856a9645188792bd9f
