### ISSUE TITLE
Support of 3440x1440 in VMWare Addons

### ISSUE THREAD

**Issue by chatoune** [haikuports/haikuports#1144]
In the source file VMwareAddons/vmware_video/accelerant/ProposeDisplayMode.c, add the following screen definition.
{ { 319750, 3440, 3488, 3520, 3600, 1440, 1443, 1453, 1481, 0 }, B_RGB32_LITTLE, 3440, 1440, 0, 0, MODE_FLAGS }, /* 3440x1440@60 Hz - Reduced Blanking */

Regards,

Eddy

**Comment by diversys** [comment]
Please create a PR at https://github.com/HaikuArchives/VMwareAddons

**Comment by chatoune** [comment]
Just did it.
Thanks for the information.

Regards,

Eddy
