### ISSUE TITLE
dev-lang/openjdk missing javaws command

### ISSUE THREAD

**Issue by tidux** [haikuports/haikuports#1145]
IIRC IcedTea's Java Web Start implementation got merged in OpenJDK 8 so fixing the build and changing some options should be enough.

**Comment by korli** [comment]
It seems to be deprecated: 
> Oracle will not include Java Web Start in Java SE 11 (18.9 LTS) and later

**Comment by tidux** [comment]
Deprecated or not it's still needed for a ton of things out there, like server IPMI consoles.

**Comment by korli** [comment]
Won't fix.
