### ISSUE TITLE
Minor recipe cleanup issue.

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#11461]
Minor "cosmetic" issue:

`inrecipe '${LIBRARY_PATH:+:$LIBRARY_PATH}' | wc -l`

returns 142 at the moment.

I think that something like the following is functionally equivalent, and easier to read (bash syntax is hard just as it is, no need to make it harder for newbies like myself... or am I missing something?):

```diff
-export LIBRARY_PATH="$sourceDir/build/bin${LIBRARY_PATH:+:$LIBRARY_PATH}"
+export LIBRARY_PATH="$sourceDir/build/bin:${LIBRARY_PATH}"
```

**Comment by augiedoggie** [comment]
If $LIBRARY_PATH is empty then you'll get an error because of the trailing colon.

**Comment by Begasus** [comment]
If I understand this correctly we should keep these as they are then?

**Comment by Begasus** [comment]
> @Begasus, yeah, I guess is better to revert the one I mentioned on your PR for KDE frameworks, even if just for consistency's sake with the rest of the .recipes. Sorry.

Only need to find out which one it was :P Thanks :)
