### ISSUE TITLE
Remove references to parameter --no-dependencies on documentation

### ISSUE THREAD

**Issue by dalmemail** [haikuports/haikuports#11478]
At least on page https://github.com/haikuports/haikuports/wiki/Patching-with-HaikuPorter of the wiki there are some references to --no-dependencies at the very end of the page, however this parameter is no longer available (see https://github.com/haikuports/haikuporter/commit/7aef5fe1ee3a95de8839d382876702134f0232a7).

**Comment by augiedoggie** [comment]
Fixed in [127870f1d39408eff7c1cdf9b70b225e49057609](https://github.com/haikuports/haikuports/wiki/Patching-with-HaikuPorter/127870f1d39408eff7c1cdf9b70b225e49057609)

A quick search of the wiki didn't reveal any other instances.
