### ISSUE TITLE
lapack build fail on haiku x86_64 hrev50953

### ISSUE THREAD

**Issue by armgong** [haikuports/haikuports#1150]
[ 99%] Building C object LAPACKE/CMakeFiles/lapacke.dir/utils/lapacke_ctr_nancheck.c.o

[ 99%] Building C object LAPACKE/CMakeFiles/lapacke.dir/utils/lapacke_make_complex_double.c.o

[ 99%] Building C object LAPACKE/CMakeFiles/lapacke.dir/utils/lapacke_z_nancheck.c.o

[ 99%] Building C object LAPACKE/CMakeFiles/lapacke.dir/utils/lapacke_ztr_trans.c.o

[100%] Linking C shared library ../lib/liblapacke.so

Error running link command: Argument too big

make[2]: *** [LAPACKE/CMakeFiles/lapacke.dir/build.make:62445: lib/liblapacke.so] Error 2

make[1]: *** [CMakeFiles/Makefile2:1732: LAPACKE/CMakeFiles/lapacke.dir/all] Error 2

make: *** [Makefile:161: all] Error 2

[Errno -2147459069] No such file or directory: '/boot/home/haikuports/sci-libs/lapack/work-3.7.0'

Error: Build has failed - stopping.

**Comment by armgong** [comment]
after these mod , build ok 
~~~diff
diff --git a/sci-libs/lapack/lapack-3.7.0.recipe b/sci-libs/lapack/lapack-3.7.0.recipe
index 5b06bc1..bdbab36 100644
--- a/sci-libs/lapack/lapack-3.7.0.recipe
+++ b/sci-libs/lapack/lapack-3.7.0.recipe
@@ -16,7 +16,6 @@ PROVIDES="
 	lapack$secondaryArchSuffix = $portVersion
 	lib:liblapack$secondaryArchSuffix = $portVersion compat >= 3.7.0
 	lib:liblapacke$secondaryArchSuffix = $portVersion
-	lib:libtmglib$secondaryArchSuffix = $portVersion
 	"
 REQUIRES="
 	haiku$secondaryArchSuffix
@@ -29,7 +28,6 @@ PROVIDES_devel="
 	lapack${secondaryArchSuffix}_devel = $portVersion
 	devel:liblapack$secondaryArchSuffix = $portVersion compat >= 3.7.0
 	devel:liblapacke$secondaryArchSuffix = $portVersion
-	devel:libtmglib$secondaryArchSuffix = $portVersion
 	"
 REQUIRES_devel="
 	lapack$secondaryArchSuffix == $portVersion base
@@ -55,12 +53,12 @@ BUILD()
 
 	cmake .. \
 		-DCMAKE_INSTALL_PREFIX=$prefix \
-		-DCMAKE_Fortran_USE_RESPONSE_FILE_FOR_OBJECTS=1 \
-		-DCMAKE_Fortran_USE_RESPONSE_FILE_FOR_INCLUDES=1 \
 		-DCMAKE_BUILD_TYPE=Release \
 		-DUSE_OPTIMIZED_BLAS=ON \
 		-DBUILD_SHARED_LIBS=ON \
-		-DLAPACKE=ON
+		-DLAPACKE=ON \
+		-DCBLAS=ON \
+		-DBUILD_TESTING=OFF
 
 	make $jobArgs
 }
@@ -77,7 +75,6 @@ INSTALL()
 
 	prepareInstalledDevelLibs liblapack \
 		liblapacke \
-		libtmglib
 
 	fixPkgconfig

**Comment by korli** [comment]
you need cmake 3.7

**Comment by armgong** [comment]
ok thanks
