### ISSUE TITLE
libid3tag has no pkg-config file

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#1151]
Not sure why. Audacity looks for it using pkg-config, which obviously doesn't find it because of this.

**Comment by diversys** [comment]
Perhaps applying this patch might help https://github.com/openembedded/openembedded/blob/master/recipes/libid3tag/files/libid3tag-pkg-config.patch

**Comment by Begasus** [comment]
seems to work @diversys :) 


~> pkg-config id3tag --libs
-L/packages/libid3tag-0.15.1b-3/.self/develop/lib -lid3tag -lz
~> pkg-config id3tag --cflags
-I/packages/libid3tag-0.15.1b-3/.self/develop/headers

**Comment by diversys** [comment]
Hopefully fixed in c20c4b.
