### ISSUE TITLE
FileType issues for ".squashfs" files after installing Beezer.

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#11542]
I've just noticed that on one of my newer installs (beta5), if I install Beezer, the FileType preflet shows the `application/x-squashfs-image` type without associated extensions, icon, or preferred app, and Tracker fails to properly "sniff"/identify such files.

If I uninstall Beezer, but leave `squashfs_tools` installed, then said file type appears in FileTypes as "SquashFS image", as intended, with proper icon, sniffer rules, etc, etc.

Is Beezer somehow overriding that mimedata from `squashfs_tools`. Why only for that filetype, and not for others like .hpkg for example?

Paging Dr. @augiedoggie :-)

**Comment by augiedoggie** [comment]
I'm not sure if there's anything I can do about the problem. When a package claims to handle a previously unknown filetype then haikuporter(via `mimeset`) will store the extra mime_db files.  If more than one package handles the filetype then there will be conflicting mime_db entries.

**Comment by augiedoggie** [comment]
Seems like these filetypes should already exist if `squashfs_tools` is active in the chroot. Perhaps those filetype associations don't get activated immediately in the chroot.  I'm not sure how that works but I don't see anything wrong with what either package is doing.

**Comment by augiedoggie** [comment]
> As far as I can see, only squashfs_tools adds a [file type for SquashFS image](https://github.com/haikuports/haikuports/blob/master/sys-fs/squashfs_tools/squashfs_tools-4.6.1.recipe#L86) (.rdef file [here](https://github.com/haikuports/haikuports/blob/master/sys-fs/squashfs_tools/additional-files/x-squashfs-image.rdef), for reference), while this is Beezer's [.rdef file](https://github.com/Teknomancer/beezer/blob/master/Source/SquashFSArchiver/SquashFSArchiver.rdef) (which I had interpreted to be one not adding a new file type, just declaring support for a particular one).


The rdef files for the addons have no effect here.  The short answer is that it's used to do file lookups on non-BFS volumes.  The only thing Beezer does is declare support via the `file_types` resource in the main Beezer.rdef file.

**Comment by augiedoggie** [comment]
> Then I'm even more puzzled as to what's going on with the "disappearing" SquashFS filetype data. :-D

`squashfs_tools` includes a full definition for that filetype.  `Beezer` just says that it can handle that filetype.

Again, you have to ignore the filetype information you put into the `Beezer` addon rdef since that is used differently.

When `mimeset` is run on `Beezer` then it generates a barebones mime_db entry from the `file_types` resource which seems to override the full `squashfs_tools` entry.

**Comment by waddlesplash** [comment]
Haiku picks the newest file when there are conflicting entries in packagefs. I don't know if there's much that we can do about that. Depending on squashfs_tools during the build may avoid the problem?

**Comment by augiedoggie** [comment]
I pushed a new PR #11543 which seems to work around the problem.  @OscarL maybe you could check it out before I close this issue?
