### ISSUE TITLE
PDFTranslator won't build on x86_gcc2

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#1155]
Error: unable to resolve required packages for build for pdftranslator-1.0.2
Error:  dependency-infos:
Error:          /boot/home/haikuports/repository/pdftranslator-1.0.2.DependencyInfo
Error:  repositories:
Error:          [u'/boot/home/haikuports/packages', '/boot/system/packages']
Error:

**Comment by pulkomandy** [comment]
Fixed in Haiku hrev51043.
