### ISSUE TITLE
Add WebWatch to HaikuArchives

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#1158]
http://cgit.haiku-os.org/haiku/tree/src/apps/webwatch

**Comment by humdingerb** [comment]
I'll have a try...

**Comment by humdingerb** [comment]
Perfect. I managed to migrate WebWatch out of the Haiku tree, added makefile and the catkeys, converted the readme to markdown, see [my repo](https://github.com/humdingerb/webwatch). And what did I see when I tried to transfer the repo to HaikuArchives? It's [already there](https://github.com/HaikuArchives/WebWatch)!!

@waddlesplash: Seeing that my WebWatch is more complete, with preserved commit history and all, can you remove the WebWatch currently at HaikuArchives so I can transfer mine?

**Comment by waddlesplash** [comment]
@humdingerb done.

**Comment by humdingerb** [comment]
@waddlesplash, I transferred the webwatch repo and got the note: "You don’t have the permission to create repositories on HaikuArchives". Did the request at least get thru?

**Comment by waddlesplash** [comment]
Apparently not. I think I fixed the permissions, you should now be able to move it in.

**Comment by humdingerb** [comment]
Thanks. Seems to have worked.

**Comment by diversys** [comment]
Could you recreate the repo as "WebWatch" (vs webwatch) to make it consistent with other repos?

**Comment by waddlesplash** [comment]
It can be renamed. No need for recreation.

**Comment by humdingerb** [comment]
I'm sorry. I only realized that I should have named it "WebWatch" after I transferred the repo. Hoped nobody notices... :)
The renaming is done by an "Owner", I suppose?

**Comment by waddlesplash** [comment]
Done.
