### ISSUE TITLE
Request for QtKeychain to be added

### ISSUE THREAD

**Issue by Perelandra0x309** [haikuports/haikuports#1162]
I made a rather longshot attempt to compile owncloud and it finds all the QT5 libraries except Qt5Keychain which appears to be missing from dev-qt/qt5.

**Comment by waddlesplash** [comment]
Qt5Keychain appears to be a third-party library: https://github.com/frankosterfeld/qtkeychain

**Comment by korli** [comment]
Should go in dev-libs/qtkeychain

**Comment by CodeforEvolution** [comment]
I we wanted to this, we would need to code a platform specific implementation. For example, some existing backends for it are the Gnome keyring and KWallet. We'd need to use BKey and BKeyStore as our implementation.

**Comment by CodeforEvolution** [comment]
Hello! I have successfully made QtKeychain functional on my system and starting to convert my porting to a recipe and patchset, expect a completed QtKeychain recipe soon!

**Comment by Perelandra0x309** [comment]
Nice!  I can cross this off my list of things to when/if find time.

**Comment by extrowerk** [comment]
Any news here?

**Comment by mmuman** [comment]
Oh, I just notice this now.
I actually ported qtkeychain myself: https://github.com/frankosterfeld/qtkeychain/pull/128 

Now, the only issue left is a workaround for QCoreApplication that doesn't seem to spawn a BApplication, but maybe that's intended? poke @threedeyes 

I also have owncloud running. At least it did last time I tried.

**Comment by mmuman** [comment]
I cleaned up the code to create a BApplication when required anyway, although I think QCoreApplication should do so, but well.

**Comment by Begasus** [comment]
Closing as we have a port at: https://github.com/haikuports/haikuports/blob/14c2cab5428145b93232cb69683a67bbe68a9f06/dev-libs/qtkeychain/qtkeychain-0.10.0.recipe
