### ISSUE TITLE
Error while running Weather downloaded from Haikudepot x86_gcc2

### ISSUE THREAD

**Issue by AkshayAgarwal007** [haikuports/haikuports#1224]
![error](https://cloud.githubusercontent.com/assets/8170214/24078737/e862b032-0c9b-11e7-824e-7166589a1089.PNG)

**Comment by humdingerb** [comment]
What version of Haiku and the Weather package?
Works here with hrev51022 and Weather 0.1.1_git-5

**Comment by AkshayAgarwal007** [comment]
hrev50988
Weather 0.1.1._git-3

**Comment by humdingerb** [comment]
Weather ws updated with hrev51009. You need to update (make sure your repos are set to "current", see [Update your system](https://www.haiku-os.org/guides/daily-tasks/updating-system).

**Comment by AkshayAgarwal007** [comment]
Okay. Thanks!
