### ISSUE TITLE
Old bep files around that should be save to be removed ... 

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#1244]
./app-crypt/gnupg/gnupg-1.4.10.recipe:STATUS_HAIKU="stable"

./app-shells/bash/bash-4.1.recipe:STATUS_HAIKU="stable"

./dev-games/flatzebra/flatzebra-0.1.3.recipe:STATUS_HAIKU="stable"

./dev-lang/dmd_bin/dmd_bin-1.064.recipe:STATUS_HAIKU="stable"
./dev-lang/fpc/fpc-2.4.0.recipe:STATUS_HAIKU="unstable"
./dev-lang/fpc/fpc-2.6.0.recipe:STATUS_HAIKU="untested"
./dev-lang/v8/v8-r13067.recipe:STATUS_HAIKU="unstable"

./dev-libs/boehm_gc/boehm_gc-7.2_alpha6.recipe:STATUS_HAIKU="stable"
./dev-libs/libdwarf/libdwarf-20120410.recipe:STATUS_HAIKU="stable"

./dev-scheme/chicken/chicken-4.5.0.recipe:STATUS_HAIKU="stable"
./dev-scheme/chicken/chicken-4.7.0.recipe:STATUS_HAIKU="stable"

./games-puzzle/gnurobbo/gnurobbo-0.65.recipe:STATUS_HAIKU="stable"

./media-gfx/graphviz/graphviz-2.24.recipe:STATUS_HAIKU="stable"
./media-gfx/tuxpaint/tuxpaint-0.9.21.recipe:STATUS_HAIKU="stable"

./media-libs/gd/gd-2.0.36rc1.recipe:STATUS_HAIKU="stable"
./media-libs/giflib/giflib-4.1.6.recipe:STATUS_HAIKU="stable"
./media-libs/liblo/liblo-0.26.recipe:STATUS_HAIKU="stable"

./media-sound/fluidsynth/fluidsynth-1.1_midi_buffer.recipe:STATUS_HAIKU="stable"
./media-sound/fluidsynth/fluidsynth-1.1.3.recipe:STATUS_HAIKU="stable"

./media-video/gnash/gnash-0.recipe:STATUS_HAIKU="stable"
	also obsolete files in the directory?

./net-libs/enet/enet-1.2.2.recipe:STATUS_HAIKU="stable"

./net-misc/tor/tor-0.2.2.35.recipe:STATUS_HAIKU="stable"
./net-misc/tor/tor-0.2.3.25.recipe:STATUS_HAIKU="stable"

./net-p2p/rtorrent/rtorrent-0.8.5.recipe:STATUS_HAIKU="stable"

./sys-apps/dmidecode/dmidecode-2.11.recipe:STATUS_HAIKU="stable"
./sys-apps/hgrep/hgrep-1.0.recipe:STATUS_HAIKU="stable"

./sys-devel/libtool/libtool-2.2.10.recipe:STATUS_HAIKU="stable"
./sys-devel/libtool/libtool-2.2.6.recipe:STATUS_HAIKU="stable"
./sys-devel/libtool/libtool-2.2.6b.recipe:STATUS_HAIKU="stable"
./sys-devel/libtool/libtool-2.2.7b.recipe:STATUS_HAIKU="stable"
./sys-devel/libtool/libtool-2.2.8.recipe:STATUS_HAIKU="stable"
./sys-devel/libtool/libtool-2.2.x.recipe:STATUS_HAIKU="unstable"

./x11-libs/pixman/pixman-0.17.2.recipe:STATUS_HAIKU="stable"
./x11-libs/pixman/pixman-0.18.2.recipe:STATUS_HAIKU="stable"
./x11-libs/pixman/pixman-0.18.4.recipe:STATUS_HAIKU="stable"
./x11-libs/pixman/pixman-0.19_master.recipe:STATUS_HAIKU="stable"
./x11-libs/pixman/pixman-0.19.4.recipe:STATUS_HAIKU="stable"

**Comment by scottmc** [comment]
Old recipes for these can probably be removed:
tor, libtool, pixman, rtorrent, gd, liblo, bash, tuxpaint, hgrep.

opensound looks to be partially converted to proper recipe format but left the STATS_HAIKU and DEPEND="" in it.

Maybe break this into 2 tickets, one for the ones that were marked "stable" and one for the ones marked unstable/untested or broken.  

Are these caught by running --lint?  If not then maybe a new rule should be added to the lint check for "STATUS_HAIKU" and "DEPEND"?

**Comment by Begasus** [comment]
Some of them could still be useful, it's a matter of going through the list of finding out which ones can actually be used to create an updated recipe for them (earlier I did the same for hgrep), ps, haven't used lint on any of these ...

**Comment by mmuman** [comment]
The git recipe for opensound seems more recent, someone should make a release one from it...

**Comment by Begasus** [comment]
Updated with the ones that safely be deleted imho (hgrep and lgrep also @scottmc ?)
