### ISSUE TITLE
Old bep files that needs updating/checking/removed ...

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#1246]

**Comment by korli** [comment]
app-text/enchant/enchant-1.6.0.recipe should be converted to a recipe
dev-libs/redland/redland-1.0.15.recipe should be converted to a recipe

**Comment by Begasus** [comment]
@korli https://github.com/haikuports/haikuports/pull/1250 wip ...

**Comment by Begasus** [comment]
redland also updated now :)

**Comment by Begasus** [comment]
se and gpp also updated with a new recipe ...

**Comment by Begasus** [comment]
./dev-cpp/glog/ ./dev-cpp/mm_common updated ...

**Comment by Begasus** [comment]
./dev-libs/oniguruma updated ...

**Comment by korli** [comment]
serd and libxdg_basedir were updated

**Comment by Begasus** [comment]
/dev-util/quilt and /media-fonts/farsi_fonts PR created ...

**Comment by return** [comment]
#1312 PR created for Eigen.

**Comment by Begasus** [comment]
Thanks @return ! The list is getting smaller :)

**Comment by Begasus** [comment]
A PR for opensound already exists ... https://github.com/haikuports/haikuports/pull/1282

**Comment by return** [comment]
#1316 PR for libsigsegv.

**Comment by Begasus** [comment]
/dev-libs/libsigsegv/libsigsegv PR looks ok, wput also updated :)

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/1324
looks like b43_fwcutter isn't needed as it's already in the firmwares 
https://www.haiku-os.org/files/download-data-for-wlan-firmwares.txt

**Comment by Begasus** [comment]
fatsort and spiff updated also ...

**Comment by Begasus** [comment]
www-servers/cherokee updated ...

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/1342
jed updated ...

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/1358
recipe for current version of convmv created ...

**Comment by Begasus** [comment]
ebook-tools updated also :)

**Comment by Begasus** [comment]
redis updated ...

**Comment by Begasus** [comment]
pjdfstest, beacon and hqx also updated ...

**Comment by Begasus** [comment]
old bep file for bsdbuild removed ...

**Comment by Begasus** [comment]
for glpng ... https://github.com/haikuports/haikuports/pull/1786

**Comment by Begasus** [comment]
sdl_rtf, waave fixed, xinetd in the PR's

**Comment by Begasus** [comment]
PR for jbigkit created .... https://github.com/haikuports/haikuports/pull/2376

**Comment by Begasus** [comment]
PR for ntp created .... https://github.com/haikuports/haikuports/pull/2378
still fails due to missing adjtim()

**Comment by Begasus** [comment]
PR created for libwebm: https://github.com/haikuports/haikuports/pull/2426

**Comment by Begasus** [comment]
List is getting smaller, mediatomb and minidlna PR have been launched :)

**Comment by Begasus** [comment]
PR for jack2: https://github.com/haikuports/haikuports/pull/3060

**Comment by Begasus** [comment]
pychart and pydispatcher PR available at: https://github.com/haikuports/haikuports/pull/3304

**Comment by Begasus** [comment]
PR (wip) for pyxml and rdflib are here (by @bach5000 ) https://github.com/haikuports/haikuports/pull/3406

**Comment by waddlesplash** [comment]
Anything left here?

**Comment by Begasus** [comment]
I'll try to see if I can find some time tomorrow to investigate, I think most is covered ...

**Comment by Begasus** [comment]
A few remaining ones:
- [ ] hgrep, a rcipe had been done in the past but didn't go in to replace the old one, maybe that could be removed? https://github.com/haikuports/haikuports/blob/c2a214e6473117adfdbf84d0f792341b30e1bbd7/sys-apps/hgrep/hgrep-1.0.1.recipe
- [ ] cdrdao, can't find any work done there, but seems there is a newer version available 1.2.4 https://github.com/haikuports/haikuports/blob/c2a214e6473117adfdbf84d0f792341b30e1bbd7/app-cdr/cdrdao/cdrdao-1.2.3.recipe
- [ ] mysql, did some checking there but wasn't able to produce any working recipe, https://github.com/haikuports/haikuports/blob/4de2811802ba801ea83fc30104c6d23629cc408c/dev-db/mysql/mysql-5.0.83.recipe
- [ ] pyopengl, nothing new so far, https://github.com/haikuports/haikuports/blob/c2a214e6473117adfdbf84d0f792341b30e1bbd7/dev-python/pyopengl/pyopengl-3.0.1.recipe
- [ ] ntp, a recipe was created (https://github.com/haikuports/haikuports/pull/2378) but not merged, maaybe reove the old one also? https://github.com/haikuports/haikuports/blob/c2a214e6473117adfdbf84d0f792341b30e1bbd7/net-misc/ntp/ntp-4.2.6p2.recipe
- [ ] lemon, a new recipe is in place, old bep file can be removed: https://github.com/haikuports/haikuports/blob/c2a214e6473117adfdbf84d0f792341b30e1bbd7/sys-devel/lemon/lemon-3.7.5.recipe
- [ ] pyserial, nothing new there: https://github.com/haikuports/haikuports/blob/c2a214e6473117adfdbf84d0f792341b30e1bbd7/dev-python/pyserial/pyserial-2.5.recipe
- [ ] pearpc, nothing new there: https://github.com/haikuports/haikuports/blob/c2a214e6473117adfdbf84d0f792341b30e1bbd7/app-emulation/pearpc/pearpc-0.5.0_cvs.recipe

**Comment by Begasus** [comment]
Afaik the list is finished on the old bep files, last one not merged (yet) is the one for mysql.
I would like this one to stay in (if only for historical reasons) with a "maybe" working recipe.
Think this one can be closed (if no one else finds some old bep file around) ;)

**Comment by Begasus** [comment]
Last of the remaining bep files has gone, closing this one :)
