### ISSUE TITLE
virtualbox-guest-additions: Cannot build recipe

### ISSUE THREAD

**Issue by raefaldhia** [haikuports/haikuports#1254]
![screenshot from 2017-03-26 18-20-01](https://cloud.githubusercontent.com/assets/10385303/24330823/1ad32eec-1251-11e7-9faa-24e78348377a.png)

**Comment by mmuman** [comment]
Those errors usually happen due to changes in haikuporter or the repository/ folder not being consistent...
Try updating haikuporter, renaming repository/ to move it away so it will rebuild it?

**Comment by korli** [comment]
Possi: touch the recipe, make sure your arch is enabled in the recipe.

**Comment by raefaldhia** [comment]
It works now thank you!
Do you know how to install it? i've tried to install it but virtualbox says it not instaled
i used x86_64 haiku.

**Comment by mmuman** [comment]
Oh, I only tested it with 32bit, so I don't know if it works at all there. There might be some things to fix.

**Comment by diversys** [comment]
The recipe should work, however 
```
TEMPLATE_VBOXR0DRV_LDFLAGS
TEMPLATE_VBOXR0DRV_CFLAGS 
```
need some changes to create proper kernel drivers

https://github.com/haikuports/haikuports/blob/master/app-emulation/virtualbox-guest-additions/patches/virtualbox_guest_additions-5.1.14.patchset#L28

**Comment by raefaldhia** [comment]
I still got some issue, build in GCC 5.4.0

![screenshot from 2017-04-02 14-03-50](https://cloud.githubusercontent.com/assets/10385303/24585146/6c64851a-17ad-11e7-91f5-5dd53e624ed9.png)
