### ISSUE TITLE
Missing Provide for lib:libgomp

### ISSUE THREAD

**Issue by CodeforEvolution** [haikuports/haikuports#1261]
There are recipes that depend on lib:libgomp, but nothing provides it. Seemingly, gcc should provide it as it seems gcc supposedly should provide libgomp.

**Comment by waddlesplash** [comment]
Yeah, HaikuPorter's handling of gcc syslibs is kinda bogus and hacky, which is my fault. I should look into fixing that one of these days.

**Comment by korli** [comment]
It's actually provided by the gcc_syslibs package:
https://github.com/haikuports/haikuports/blob/master/sys-devel/gcc/gcc-5.4.0_2016_06_04.recipe#L393

**Comment by CodeforEvolution** [comment]
Oops, didn't catch that. Though on the x86 version of Haiku, no package provides devel:libgomp.

**Comment by korli** [comment]
Right, the gcc packages weren't updated since then. Any recipe needs devel:libgomp? They usually need lib:libgomp only.

**Comment by Begasus** [comment]
Looks like there is no gcc_syslibs (and therefore no libgomp) for x86_gcc2

**Comment by Begasus** [comment]
> Right, the gcc packages weren't updated since then. Any recipe needs devel:libgomp? They usually need lib:libgomp only.

fluidsynth needs one for x86_gcc2 it seems? https://github.com/haikuports/haikuports/blob/0975f29d4efcb1130fd8873bb417c8b63a368413/media-sound/fluidsynth/fluidsynth2-2.0.7.recipe#L39
