### ISSUE TITLE
mplayer 1.1.1-3 seems broken on gcc2 hybrid

### ISSUE THREAD

**Issue by Giova84** [haikuports/haikuports#1263]
Today (on Haiku hrev51051 gcc2 hybrid) I attempted to install mplayer 1.1.1-3 from HaikuDepot, but i get an error message:

> "Nothing provides libpng_x86 16.17.0"

libpng_x86 is installed form HaikuDepot, but seems an older version.

Then I unpacked the hpkg file (which I downloaded from the HaikuDepot website), i edited the .packageinfo file, excluding this version of libpng, i rebuilt the package and then mplayer hpkg installed fine with all his dependencies, but when I attempt to run it from the Terminal, i get:

```
~> mplayer
runtime_loader: /boot/system/bin/mplayer: Could not resolve symbol 'mpg123_decode_frame_64'
resolve symbol "mpg123_decode_frame_64" returned: -2147478780
runtime_loader: /boot/system/bin/mplayer: Troubles relocating: Symbol not found
```

**Comment by michaelvoliveira** [comment]
Hum.. is not a libpng problem.. 
try to include in .packageinfo -lmpg123

**Comment by Giova84** [comment]
Hi Michael, libmpg123 (_x86) is still included in the .packageinfo file, in the "requires" section.

**Comment by diversys** [comment]
New mplayer package simply needs to be rebuilt and uploaded to HaikuPorts repo.
I've built it locally from the recipe and at least it starts just fine. Didn't try to play anything since I'm in VMware tho.

**Comment by Giova84** [comment]
@diversys 
I can test it. The last time, mplayer had some problems: was unable to stream youtube videos, so i'd like to test this new package: can you provide a download link? ATM I can't build it with HaikuPort.

Thank you!

**Comment by Giova84** [comment]
I attempted to build mplayer from HaikuPorts, but all that I get is another error.
Output here: http://sprunge.us/EWEB
It claims:
```
Applying: Haiku supporting code from Sergei Reznikov
Fetching package for devel:libcaca_x86 ...
*** Failed to find a match for "devel:libcaca_x86": Name not found
Error: unable to resolve required packages for build for mplayer_x86-1.3.0
Error:  dependency-infos:
Error:          /boot/home/haikuports/repository/mplayer_x86-1.3.0.DependencyInfo
Error:  repositories:
Error:          [u'/boot/home/haikuports/packages', '/boot/system/packages']
Error: 
```
Some hints?
I run hrev51090 gcc2_hybrid, the following is the content of haikuports.conf file: http://sprunge.us/VXQX

**Comment by pulkomandy** [comment]
This is a missing dependency, you need to build it yourself:

    haikuporter -S --get-dependencies libcaca_x86

It may complain about other missing ones, build them and see how far you can get.
Last time I tried, some of the dependencies also had a broken recipe so it will take some effort to fix all of them.

**Comment by Giova84** [comment]
Missing libcaca, libdvd, libfaac, libsmb. For now I give up.
@diver (in comment https://github.com/haikuports/haikuports/issues/1263#issuecomment-292477182 ): how did you rebuilt the mplayer package? Did you fix something, due all these errors about missing dependencies?

**Comment by diversys** [comment]
I think I built it on x86_64 where all the missing libs are there (in the Depot). libsmb is Depot too on x86_gcc2. It's in samba package.

**Comment by miqlas** [comment]
Just made a PR with some fixes, can you guys test it? It builds just fine on AMD64.

**Comment by Giova84** [comment]
Well, I've done `haikuporter -c mplayer_x86` to clean the working directories and I've also done `cd /haikuporter && git pull` to get the latest receipes.

But I still got the same errors:
http://sprunge.us/YHFR

It is ok, or is just a matter of broken dependencies?

**Comment by miqlas** [comment]
Giova, it isn't broken, you just using a Haiku variant what got no libcaca in the Depot yet, so you should compile it first like:

hp libcaca_x86

And install the created package(s). Source und debug packages doesn't required.

Maybe there will be other missing stuff, you need to compile all of them.

The buildbots will do that for us, but they aren't online yet.

**Comment by extrowerk** [comment]
can we close this?

**Comment by humdingerb** [comment]
yes. I just built the current mplayer recipe on 32bit.
