### ISSUE TITLE
wget 1.19.1 failed build on x86_gcc2

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#1264]
Building on a x86_gcc5 hybrid install:
~/haikuports> haikuporter -S -j4 --get-dependencies --no-source-packages wget_x86_gcc2

/sources/wget-1.19.1/src/init.c: In function `setval_internal':
/sources/wget-1.19.1/src/init.c:883: incompatible types in return
Makefile:1649: recipe for target 'init.o' failed
make[3]: *** [init.o] Error 1
make[3]: Leaving directory '/sources/wget-1.19.1/src'
Makefile:1464: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/sources/wget-1.19.1/src'
Makefile:1454: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/sources/wget-1.19.1'
Makefile:1410: recipe for target 'all' failed
make: *** [all] Error 2
[Errno -2147459069] No such file or directory: '/boot/home/haikuports/net-misc/wget/work-x86_gcc2-1.19.1'
Error: Build has failed - stopping

**Comment by Vidrep** [comment]
wget 1.19.1 is tested as building, installing and working on both x86 and x86_64.
Screenshots will be uploaded later showing successful download.

**Comment by korli** [comment]
You should be able to build version 1.18 until this problem is fixed.

**Comment by korli** [comment]
You should probably disable ALLOW_UNTESTED in your haikuports.conf, otherwise you'll get a lot of issues like this one.

**Comment by korli** [comment]
Fixed in 7eee9f321ff62a4079e9c4484d556cc967d607f0
