### ISSUE TITLE
Roadfighter should put configuration files under  ~/config/settings/roadfighter folder instead of ~/.roadfighter folder

### ISSUE THREAD

**Issue by Giova84** [haikuports/haikuports#1294]
As the subject states, currently the game roadfighter will create the folder .roadfigther under /home, but these config folder should be present as ~/config/settings/roadfighter

**Comment by korli** [comment]
The recipe: https://github.com/haikuports/haikuports/blob/master/games-arcade/roadfighter/roadfighter-1.0.1269.recipe
