### ISSUE TITLE
Handbrake dependency issue on x86_64

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#1331]
hrev51155 x86_64
I get this dependency issue when installing from HaikuDepot, even after installing the libass hpkg
"nothing provides lib:libass>=5.3.0 needed by handbrake-1.0.3-1"

**Comment by Vidrep** [comment]
Another dependency issue when building:
Fetching package for devel:libbluray >= 2 ...
*** Failed to find a match for "devel:libbluray >= 2": Name not found

**Comment by Vidrep** [comment]
This issue can be closed.

**Comment by korli** [comment]
The second problem is more in Haikuporter. It tries to install a package with the version spec in the name, which obviously doesn't exist.
