### ISSUE TITLE
Handbrake: HaikuDepot description and screenshot

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#1333]
Handbrake for 64 bit Haiku is showing a screenshot of the old 0.7.0-beta1 GUI.
There is nothing in the description to indicate to the user that Handbrake 1.0.3-2 is a only  a command line interface (CLI) application, at this time.
Until a native Haiku GUI is made available, there shouldn't be a screenshot showing one.

**Comment by korli** [comment]
Well I think this isn't an issue which Haikuports can fix.

**Comment by Vidrep** [comment]
Fixed. The issue can be closed.
