### ISSUE TITLE
libgphoto2 update

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#1334]
Update to current: libgphoto2-2.5.13
CHECKSUM_SHA256="ceaacbdf187d1cd1aed5336991f46b0100f6960b6c8383f9aeab98f1f64780ef"

**Comment by Vidrep** [comment]
Build and tested on Haiku hrev51159 x86_64

**Comment by korli** [comment]
Updated in fea3dfee5e59e99c1b352917176e5d4316b5889d
