### ISSUE TITLE
gphoto2 update

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#1335]
Current revision: gphoto2-2.5.11
CHECKSUM_SHA256="c2b85221a1d90a416b309283695ebaecaf5de2276371fc2292d655b745ccf6db"

**Comment by Vidrep** [comment]
Built and tested on Haiku hrev51159 x86_64

**Comment by korli** [comment]
Updated in f6f2560cfd235244f41aef3a3e24bb9574d8d1e6
