### ISSUE TITLE
clucene will not build on x86_gcc2

### ISSUE THREAD

**Issue by Paradoxianer** [haikuports/haikuports#1339]
Trying to build clucene
with  

> haikuporter  --get-dependencies clucene_x86

 i get
 Set runtime path of "/packages/clucene_x86-2.3.3.4-3/.self/lib/libclucene-contribs-lib.so.2.3.3.4" to ""
 mv: cannot stat '/packages/clucene_x86-2.3.3.4-3/.self/lib/x86/libclucene-core.*': No such file or directory
[Errno -2147459069] No such file or directory: '/boot/home/Develop/haikuports/dev-cpp/clucene/work-x86-2.3.3.4'
Error: Build has failed - stopping.

**Comment by korli** [comment]
disabled in f7ade90ff126ee90b22243b30617387be7f65282
