### ISSUE TITLE
Qt5 - QSettings default path

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#1343]
With the default QSettings path, the apps compiled with Qt5 are unable to save the settings.  I guess that the default path is in some "read-only" directory.

With Qt4, I don't have this issue.

**Comment by korli** [comment]
You'll have to be a bit more specific, please Haiku revision and architecture plus package version.

**Comment by Lan72** [comment]
I have the same situation. I have installed NB hrev51168 x86_gcc2 and Qt5.7.1. 

By the last recipe, I built a qBittorent 3.3.12. After running qBittorent, I change some options, which are not saved after the restart. The following message is permanently written to the log file: "An access error occurred while trying to write the configuration file."

The default path for the settings folder must be such /boot/home/.config/qBittorrent, but it is not created. Even if you manually create this folder, no settings files will be created in it (needs to be qBittorrent.conf and qBittorrent-data.conf).

**Comment by korli** [comment]
This is normally fixed in the recipe 5.8.

**Comment by unspacyar** [comment]
My apologies Korli, you are right:

Here is the missing info:
The Qt5 package is: 5.6.1-1 (x86_gcc2) (the latest at HaikuDepot)
Haiku version: hrev51165 x86_gcc2

In any case, based in your last comment, will be fixed when the package get upgraded against recipe 5.8, isn't?

**Comment by threedeyes** [comment]
Very strange. QSettings can not create full path for file creation. The default path is settings dir + organization app name. If you create the whole path manually, the settings file is successfully created. For example librecad is the path settings - /boot/home/config/settings/LibreCad/LibreCad.conf. If you create the folder /boot/home/config/settings/LibreCad, then the settings file will be created successfully.

**Comment by threedeyes** [comment]
I suspect that this section is not compiled. https://github.com/qt/qtbase/blob/dev/src/corelib/io/qsettings.cpp#L192

**Comment by korli** [comment]
@threedeyes please see https://github.com/haikuports/haikuports/blob/master/dev-qt/qt5/patches/qt5-5.8.0.patchset#L5297 for the patch fix in 5.8.0. The bug is in QFileSystemEngine::createDirectory().

The code in 5.9.0 isn't the same anymore, the patch isn't needed anymore.

**Comment by unspacyar** [comment]
Hello.  Just  to make an example:

Original code:
	QSettings().setValue("Locale/Language", m_current);

 (this code didn't save the preferences in Haiku - At least, with Qt 5.6.1-1 (x86_gcc2))


Modified code:
	QSettings("data").setValue("Locale/Language", m_current);

after the modification, the configuration is saved under home/config/settings/data.conf

As far as I know, the original code works well in Windows and Linux, without need to define the filename.  Please, tell me if I'm wrong. Thank you guys!

**Comment by Lan72** [comment]
> This is normally fixed in the recipe 5.8.

The only pity is that 5.8.0 can not be built under x86_gcc2. And 5.9.0 beta 3, by the way, too.
At the end of the building produces the known error:

[Errno -2147459069] No such file or directory: '/boot/home/haikuports/dev-qt/qt5/work-x86-5.8.0'
 Error: Build has failed - stopping.

**Comment by waddlesplash** [comment]
@korli @threedeyes: Perhaps the patchset (or at least part of it) should be upstreamed?

**Comment by korli** [comment]
@waddlesplash I've pushed a few patches, do they need another reviewer than you?

**Comment by waddlesplash** [comment]
@korli Yes, they need one of the QtCore maintainers as reviewers. Find out whoever reviewed the first rounds of upstreamed patches and see if they can do it, I suppose.

**Comment by korli** [comment]
I added Tobias Koenig. Let's wait a bit for some more.

**Comment by unspacyar** [comment]
Since this issue was fixed long time ago, I guess this ticket could be closed.
