### ISSUE TITLE
Godot recipes found in two locations

### ISSUE THREAD

**Issue by CodeforEvolution** [haikuports/haikuports#1351]
Hello! I'm just wondering if the godot recipes should be put in a central location, as a recipe for godot 2.0 is in [game-engines/godot](https://github.com/haikuports/haikuports/blob/75a3cf5384f650242f4b8a1094ab305d33ed99e7/games-engines/godot/godot-2.0.recipe) and another recipe for godot 2.1.3 is in [dev-games/godot](https://github.com/haikuports/haikuports/blob/2e9a42ccdf83911203a4d2fe34e7253b260a4c2e/dev-games/godot/godot-2.1.3.recipe). Should any action be taken or are the recipes in different locations for a certain reason? Edit: Another concern, though could this cause the automated package building system to build both godot 2.0 and 2.1.3, since they are listed under two different categories?

**Comment by richienyhus** [comment]
Gentoo Portage puts it in dev-games/godot, although game-engines/godot does seem more apt.

**Comment by pulkomandy** [comment]
We always follow Gentoo, even when their choices are not perfect. So let's delete or move the 2.0 recipe.
