### ISSUE TITLE
Texlive does not install on x86_gcc2 

### ISSUE THREAD

**Issue by clasqm** [haikuports/haikuports#1361]
texlive_x86 does not install on x86_gcc2 as of hrev51173

I downloaded it and tried to install manually, and the problem seems to be an outdated libpng dependency. Since I wanted to play with LyX, I created a workaround: ​https://yahbblog.wordpress.com/2017/05/21/a-solution-to-haikus-word-processor-woes/

**Comment by Begasus** [comment]
Did a full build for it a while back for both x86_64 and x86_gcc2, installs ok, so seems not to be an issue (if a local build is done).
