### ISSUE TITLE
zipconf.h isn't detected in Terminal

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#1368]
I was testing ebook-tools in Terminal and it gave me an error that it couldn't find zipconf.h (part of libzip), I created a PR for ebook-tools with a new recipe, that ones seems to work inside haikuporters enviroment ... 
I then created an update on the libzip recipe that puts the header in $includeDir instead of $libDir/libzip, that one gets detected in Terminal, I also saw that libsigc++ creates a header in a subfolder for $libDir ... any info on how it would be detected with the current recipe for libzip in Terminal?
Recipe update for libzip:
https://github.com/haikuports/haikuports/pull/1366

**Comment by Begasus** [comment]
Getting this one with the current version of libzip and ebook-tools_x86:

  Scanning dependencies of target epub
  [ 12%] Building C object src/libepub/CMakeFiles/epub.dir/epub.o
  In file included from /sources/ebook-tools-0.2.2/src/libepub/epublib.h:9:0,
                   from /sources/ebook-tools-0.2.2/src/libepub/epub.c:2:
  /boot/system/develop/headers/x86/zip.h:59:21: fatal error: zipconf.h: No such file or directory

**Comment by miqlas** [comment]
I dsuppose ebook Tools doesnt use pkg-config, just checks for zip.h. 
zipconf.h is in a subdir, but called as 
#include <zipconf.h>

2 options:
- Move zipconf.h one level higher, fix the pkg-config include directive.
- Change the zip.h with sed like:
#include <libzip/zipconf.h>

I would take the second route.

**Comment by Begasus** [comment]
zipconf.h is default installed in "libincludedir" which means it's installed in "$libDir/libzip/zipconf.h" (iirc), hence why it's not picked up by ebook-tools (there is a pr for libzip that puts zipconf in "$includeDir" next to zip.h) ....

**Comment by Begasus** [comment]
Updated the PR for libzip, if I take the second route it would probably mean that future things depending on libzip will also need to be changed to use #include <libzip/zipconf> @miqlas

**Comment by Begasus** [comment]
This can be closed, libzip is updated
