### ISSUE TITLE
Pe build breaks due to inconsistent type definitions in lex-based language addons

### ISSUE THREAD

**Issue by anevilyak** [haikuports/haikuports#1373]
Owing to changes in the locale kit, the x86 Pe package no longer launches. When attempting to rebuild it via HaikuPorter though, I see errors such as:

Languages/Sources/Lout_Popup.l:71:62: error: invalid initialization of non-const reference of type 'yy_size_t& {aka long unsigned int&}' from an rvalue of type 'yy_size_t {aka long unsigned int}'
 #define YY_INPUT(tok,result,max) GetNextChar(tok, result, max)
                                                              ^
generated/objects-nodebug/Languages/Sources/Lout_Popup.cpp:1303:3: note: in expansion of macro 'YY_INPUT'
   YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),

This appears to be due to the yy_n_chars variable being declared as a simple static int, while GetNextChar expects it to be a yy_size_t ; however, said variable is, as best I can tell, automatically generated by flex/bison themselves, at least I find no explicit declaration of it anywhere, so I'm uncertain as to how to fix it. This is on hrev51190, with Flex 2.6.1 and Bison 3.0.4.

**Comment by diversys** [comment]
Same here on x86_64

**Comment by diversys** [comment]
Removing this line fixes the build https://github.com/HaikuArchives/Pe/blob/master/Sources/CLanguageInterface.cpp#L176
`return collator.Greater(second->Name(), first->Name(), B_COLLATE_SECONDARY);`

**Comment by korli** [comment]
Should be fixed in ffc1cd9.
