### ISSUE TITLE
Pe does not build? 

### ISSUE THREAD

**Issue by khallebal** [haikuports/haikuports#1374]
Tried on x86 only for now.

C++ generated/objects-nodebug/Sources/CLanguageInterface.o 
Sources/CLanguageInterface.cpp: In function 'bool CompareInterfacesByName(const CLanguageInterface*, const CLanguageInterface*)':
Sources/CLanguageInterface.cpp:176:76: error: no matching function for call to BCollator::Greater(const char*, const char*, collator_strengths)'
  return collator.Greater(second->Name(), first->Name(), B_COLLATE_SECONDARY);
                                                                            ^

**Comment by khallebal** [comment]
It looks like a silly bug, but i'm not familliar with pe's code to fix it.

**Comment by waddlesplash** [comment]
Duplicate of #1373.

**Comment by diversys** [comment]
Actually, it's a different build breakage.
Removing the third parameter from https://github.com/HaikuArchives/Pe/blob/master/Sources/CLanguageInterface.cpp#L176
`return collator.Greater(second->Name(), first->Name());
`
fixes it.

**Comment by Begasus** [comment]
I can confirm for x86_gcc2, the build went fine, but packaging in strict mode with haikuporter failed:

Warning: POLICY ERROR: can't find used library "libhekkel.so"

**Comment by pulkomandy** [comment]
For preservation of the behavior of previous versions, at https://github.com/HaikuArchives/Pe/blob/master/Sources/CLanguageInterface.cpp#L229 we should also add a collator.SetStrength(B_COLLATE_SECONDARY). Doing this beaks the build on older versions of Haiku, however (because this API didn't exist yet).

**Comment by diversys** [comment]
Probably fixed in https://github.com/HaikuArchives/Pe/commit/7f4ca18b106c50cfdb3a4b699cb43ec60ea32499
