### ISSUE TITLE
dmidecode update to revision 3.1

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#1380]
I modified the current recipe for dmidecode for the latest revision (v3.1), and tested that it builds and runs OK on 64 bit Haiku. The only error is that it cannot be built in strict mode.My hacked recipe is pasted below:

SUMMARY="Decodes BIOS SMBIOS/DMI tables"
DESCRIPTION="
Reports information about your system's hardware as described in your system \
BIOS according to the SMBIOS/DMI standard"
HOMEPAGE="http://www.nongnu.org/dmidecode/"
COPYRIGHT="2000-2002 Alan Cox, 2002-2010 Jean Delvare"
LICENSE="GNU GPL v2"
REVISION="2"
SOURCE_URI="http://download.savannah.gnu.org/releases/dmidecode/dmidecode-3.1.tar.gz"
CHECKSUM_SHA256="b5ffe3e9d9b70addc0e84dc4a955ac1005d5ad07ec0dbf98b5ea208480711bc0"

ARCHITECTURES="x86_gcc2 x86 x86_64"

PROVIDES="
	dmidecode = $portVersion
	cmd:dmidecode = $portVersion
	"
REQUIRES="
	haiku
	"

BUILD_REQUIRES="
	haiku_devel
	"
BUILD_PREREQUIRES="
	cmd:make
	cmd:gcc
	"

BUILD()
{
	make
}

INSTALL()
{
	make install prefix=$prefix \
		sbindir=$prefix/bin \
		mandir=$prefix/documentation/man \
		docdir=$prefix/documentation/dmidecode
}

**Comment by miqlas** [comment]
Solved: https://github.com/haikuports/haikuports/pull/1382

**Comment by Vidrep** [comment]
Works fine now on 64 bit
