### ISSUE TITLE
unlzx uses an unsafe source

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#1408]
```
----------------------------------------------------------------------
app-arch::unlzx-1.1
    /boot/home/haikuports/app-arch/unlzx/unlzx-1.1.recipe
----------------------------------------------------------------------

Downloading: git+https://github.com/tweakdeveloper/unlzx.git#36a85e7 ...
Error: Downloading from unsafe sources is disabled in haikuports.conf!
```

**Comment by Begasus** [comment]
This one can be closed I think ;)

**Comment by korli** [comment]
Closed with 4ecca2b7bc5344f75c4e91770b47fa98297d334e

**Comment by probonopd** [comment]
I am still getting `Error: Downloading from unsafe sources is disabled in haikuports.conf!` even when using `git+https://github.com/...`.

**Comment by Begasus** [comment]
That was the point when fixing it in https://github.com/haikuports/haikuports/pull/1500

**Comment by probonopd** [comment]
I am not talking about `unlzx` but about another recipe I am currently writing that throws the same error.
What is "unsafe" about `git+https://github.com/...`?

**Comment by Begasus** [comment]
checksum changes with every commit to git+https...
