### ISSUE TITLE
fribidi fails to build

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#1425]
```
.deps/fribidi-char-sets-cp1255.Plo:1: *** missing separator.  Stop.
make[2]: Leaving directory '/sources/fribidi-0.19.7/charset'
```

**Comment by waddlesplash** [comment]
Hm. I can't reproduce this locally. Looks like it only happens on arfonzo's builder? (It might be a bit out of date...)

**Comment by pulkomandy** [comment]
What is your setup for the builders? Are they switched to kitchen now?
Also, which branch is being used? I had created the release branch to have a fixed target to work on, are you still using it or are we going to try building from master?

**Comment by waddlesplash** [comment]
> What is your setup for the builders? Are they switched to kitchen now?

They are indeed.

>  Also, which branch is being used? I had created the release branch to have a fixed target to work on, are you still using it or are we going to try building from master?

I'm going with master. The plan is to get all of master working and a complete set of packages from that; then we can create an "r1beta1" branch for security updates, etc. after the release is published.

**Comment by waddlesplash** [comment]
Was apparently caused by outdated packages on arfonzo's slave. Fixed now.
