### ISSUE TITLE
Jam crashes on 64 bit

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#1428]
hrev51206 x86_64
haikuporter -S -j4 --get-dependencies --no-source-packages pe

**Comment by Vidrep** [comment]
Debug information for team /boot/system/bin/jam (15931):
CPU(s): 4x Intel Core™ i5-3570
Memory: 7.95 GiB total, 575.09 MiB used
Haiku revision: hrev51206 Jun 14 2017 16:15:29 (x86_64)

Active Threads:
	thread 15932: team 15931 debug task 
	thread 15931: jam (main)
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x7fa3e72a46b0	0x1ca6636d402	hashitem + 0x53 
			Disassembly:
				hashitem:
				0x000001ca6636d3af:               55  push %rbp
				0x000001ca6636d3b0:           4889e5  mov %rsp, %rbp
				0x000001ca6636d3b3:             4154  push %r12
				0x000001ca6636d3b5:               53  push %rbx
				0x000001ca6636d3b6:         4883ec30  sub $0x30, %rsp
				0x000001ca6636d3ba:           4889fb  mov %rdi, %rbx
				0x000001ca6636d3bd:         488975c8  mov %rsi, -0x38(%rbp)
				0x000001ca6636d3c1:           8955c4  mov %edx, -0x3c(%rbp)
				0x000001ca6636d3c4:         488b45c8  mov -0x38(%rbp), %rax
				0x000001ca6636d3c8:           488b00  mov (%rax), %rax
				0x000001ca6636d3cb:           488b00  mov (%rax), %rax
				0x000001ca6636d3ce:         488945e8  mov %rax, -0x18(%rbp)
				0x000001ca6636d3d2:         837dc400  cmp $0x0, -0x3c(%rbp)
				0x000001ca6636d3d6:             740f  jz 0x6636d3e7
				0x000001ca6636d3d8:           8b4318  mov 0x18(%rbx), %eax
				0x000001ca6636d3db:             85c0  test %eax, %eax
				0x000001ca6636d3dd:             7508  jnz 0x6636d3e7
				0x000001ca6636d3df:           4889df  mov %rbx, %rdi
				0x000001ca6636d3e2:       e833010000  call 0x1ca6636d51a
				0x000001ca6636d3e7:         837dc400  cmp $0x0, -0x3c(%rbp)
				0x000001ca6636d3eb:             7511  jnz 0x6636d3fe
				0x000001ca6636d3ed:           8b4330  mov 0x30(%rbx), %eax
				0x000001ca6636d3f0:             85c0  test %eax, %eax
				0x000001ca6636d3f2:             750a  jnz 0x6636d3fe
				0x000001ca6636d3f4:       b800000000  mov $0x0, %eax
				0x000001ca6636d3f9:       e913010000  jmp 0x1ca6636d511
				0x000001ca6636d3fe:         488b45e8  mov -0x18(%rbp), %rax
				0x000001ca6636d402:           0fb600  movzx (%rax), %eax <--

			Frame memory:
				[0x7fa3e72a4660]  pF*......F*.....   70 46 2a e7 01 00 00 00 c0 46 2a e7 a3 7f 00 00
				[0x7fa3e72a4670]  X..cP.....7f....   58 d5 04 63 50 01 00 00 be 87 37 66 ca 01 00 00
				[0x7fa3e72a4680]  `..cP...........   60 0a 04 63 50 01 00 00 00 00 00 00 ca 01 00 00
				[0x7fa3e72a4690]  Hf*.............   48 66 2a e7 a3 7f 00 00 02 00 00 00 00 00 00 00
				[0x7fa3e72a46a0]  .F*.......6f....   e0 46 2a e7 a3 7f 00 00 1a f8 36 66 ca 01 00 00
		0x7fa3e72a46f0	0x1ca6636f815	newstr + 0x59 
		0x7fa3e72a4730	0x1ca6636d98f	list_new + 0x55 
		0x7fa3e72a5890	0x1ca6636a7fb	main + 0x68c 
		0x7fa3e72a58c0	0x1ca6636a0a3	_start + 0x4f 
		0x7fa3e72a58e0	0xc811777e46	runtime_loader + 0x129 
		00000000	0x7fdd35a17260	commpage_thread_exit + 0 

		Registers:
			  rip:	0x000001ca6636d402
			  rsp:	0x00007fa3e72a4660
			  rbp:	0x00007fa3e72a46a0
			  rax:	0x000001ca00000000
			  rbx:	0x0000015063099b00
			  rcx:	0x00007fa3e72a46c0
			  rdx:	0x0000000000000001
			  rsi:	0x00007fa3e72a46c0
			  rdi:	0x0000015063099b00
			   r8:	0x0000000000000000
			   r9:	0x0000000000000001
			  r10:	0x0000000000000000
			  r11:	0x0000000000000001
			  r12:	0x0000000000000002
			  r13:	0x00007fa3e72a6660
			  r14:	0x0000000000000000
			  r15:	0x0000000000000000
			   cs:	0x0023
			   ds:	0x0000
			   es:	0x0000
			   fs:	0x0000
			   gs:	0x0000
			   ss:	0x001b
			  st0:	0
			  st1:	0
			  st2:	0
			  st3:	0
			  st4:	0
			  st5:	0
			  st6:	0
			  st7:	0
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0, 0, 0, 0}
			  mm2:	{0, 0, 0, 0}
			  mm3:	{0, 0, 0, 0}
			  mm4:	{0, 0, 0, 0}
			  mm5:	{0, 0, 0, 0}
			  mm6:	{0, 0, 0, 0}
			  mm7:	{0, 0, 0, 0}
			 xmm0:	{0x6574, 0x2f6d, 0x7270, 0x6665, 0x7265, 0x6e65, 0x6563, 0x73}
			 xmm1:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm8:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm9:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm10:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm11:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm12:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm13:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm14:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm15:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	249139	0x5a0365e000	0x5a0368d000	0x5a0388d000	0x5a038c1000	lib    	/boot/system/lib/libicutu.so.57.1
	249140	0x8381464000	0x83815fc000	0x83817fb000	0x8381810000	lib    	/boot/system/lib/libicuuc.so.57.1
	249136	0x9972507000	0x9972513000	0x9972712000	0x9972714000	lib    	/boot/system/lib/libicuio.so.57.1
	249133	0xa646ed4000	0xa647036000	0xa647236000	0xa64724a000	lib    	/boot/system/lib/libstdc++.so.6.0.21
	249128	0xc811764000	0xc811782000	0xc811981000	0xc811983000	lib    	/boot/system/runtime_loader
	249135	0x1309dec1000	0x1309e13e000	0x1309e33d000	0x1309e352000	lib    	/boot/system/lib/libicui18n.so.57.1
	249138	0x1411fdcd000	0x1411fdd8000	0x1411ffd8000	0x1411ffd9000	lib    	/boot/system/lib/libiculx.so.57.1
	249134	0x160bdc42000	0x160bf4c0000	0x160bf6bf000	0x160bf6c0000	lib    	/boot/system/lib/libicudata.so.57.1
	249131	0x16202c9c000	0x16202cb1000	0x16202eb0000	0x16202eb1000	lib    	/boot/system/lib/libgcc_s.so.1
	249137	0x195150c9000	0x1951511e000	0x1951531e000	0x19515321000	lib    	/boot/system/lib/libicule.so.57.1
	249130	0x1a88636d000	0x1a8864c3000	0x1a8866c3000	0x1a886716000	lib    	/boot/system/lib/libroot.so
	249129	0x1ca6635e000	0x1ca66381000	0x1ca66581000	0x1ca66588000	app    	/boot/system/bin/jam
	249132	0x24abfe37000	0x24abfe48000	0x24ac0048000	0x24ac0049000	lib    	/boot/system/lib/libroot-addon-icu.so
	249127	0x7fdd35a17000	0x7fdd35a1f000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	973924	0x1cfeb7000	0x1cfec7000	        64	rw-        	full          	rld heap
	973923	0x4f7f8b000	0x4f7f9b000	        64	rw-        	full          	rld heap
	973893	0x5ca258000	0x5ca259000	         4	rw-S       	full          	_rld_debug_
	973892	0x121478b000	0x121479b000	        64	rw-        	full          	rld heap
	973918	0x5a0365e000	0x5a0368d000	       188	r-x        	full          	libicutu.so.57.1_seg0ro
	973919	0x5a0388d000	0x5a0388f000	         8	rw-        	full          	libicutu.so.57.1_seg1rw
	973920	0x5a0388f000	0x5a038c1000	       200	rw-        	full          	libicutu.so.57.1_seg2rw
	973921	0x8381464000	0x83815fc000	      1632	r-x        	full          	libicuuc.so.57.1_seg0ro
	973922	0x83817fb000	0x8381810000	        84	rw-        	full          	libicuuc.so.57.1_seg1rw
	973912	0x9972507000	0x9972513000	        48	r-x        	full          	libicuio.so.57.1_seg0ro
	973913	0x9972712000	0x9972714000	         8	rw-        	full          	libicuio.so.57.1_seg1rw
	973905	0xa646ed4000	0xa647036000	      1416	r-x        	full          	libstdc++.so.6.0.21_seg0ro
	973906	0xa647236000	0xa647242000	        48	rw-        	full          	libstdc++.so.6.0.21_seg1rw
	973907	0xa647242000	0xa64724a000	        32	rw-        	full          	libstdc++.so.6.0.21_seg2rw
	973890	0xc811764000	0xc811782000	       120	r-x        	full          	runtime_loader_seg0ro
	973891	0xc811981000	0xc811983000	         8	rw-        	full          	runtime_loader_seg1rw
	973910	0x1309dec1000	0x1309e13e000	      2548	r-x        	full          	libicui18n.so.57.1_seg0ro
	973911	0x1309e33d000	0x1309e352000	        84	rw-        	full          	libicui18n.so.57.1_seg1rw
	973916	0x1411fdcd000	0x1411fdd8000	        44	r-x        	full          	libiculx.so.57.1_seg0ro
	973917	0x1411ffd8000	0x1411ffd9000	         4	rw-        	full          	libiculx.so.57.1_seg1rw
	973902	0x1506302a000	0x150630ba000	       576	rw-        	full          	heap
	973908	0x160bdc42000	0x160bf4c0000	     25080	r-x        	full          	libicudata.so.57.1_seg0ro
	973909	0x160bf6bf000	0x160bf6c0000	         4	rw-        	full          	libicudata.so.57.1_seg1rw
	973900	0x16202c9c000	0x16202cb1000	        84	r-x        	full          	libgcc_s.so.1_seg0ro
	973901	0x16202eb0000	0x16202eb1000	         4	rw-        	full          	libgcc_s.so.1_seg1rw
	973914	0x195150c9000	0x1951511e000	       340	r-x        	full          	libicule.so.57.1_seg0ro
	973915	0x1951531e000	0x19515321000	        12	rw-        	full          	libicule.so.57.1_seg1rw
	973897	0x1a88636d000	0x1a8864c3000	      1368	r-x        	full          	libroot.so_seg0ro
	973898	0x1a8866c3000	0x1a8866d1000	        56	rw-        	full          	libroot.so_seg1rw
	973899	0x1a8866d1000	0x1a886716000	       276	rw-        	full          	libroot.so_seg2rw
	973894	0x1ca6635e000	0x1ca66381000	       140	r-x        	full          	jam_seg0ro
	973895	0x1ca66581000	0x1ca66585000	        16	rw-        	full          	jam_seg1rw
	973896	0x1ca66585000	0x1ca66588000	        12	rw-        	full          	jam_seg2rw
	973903	0x24abfe37000	0x24abfe48000	        68	r-x        	full          	libroot-addon-icu.so_seg0ro
	973904	0x24ac0048000	0x24ac0049000	         4	rw-        	full          	libroot-addon-icu.so_seg1rw
	973888	0x7fa3e62a2000	0x7fa3e72a7000	     16404	rw-s       	full          	jam_15931_stack
	973887	0x7fbbcfbaf000	0x7fbbcfbb3000	        16	rw-        	full          	user area
	973889	0x7fdd35a17000	0x7fdd35a1f000	        32	r-xSk      	full          	commpage

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------

**Comment by Vidrep** [comment]
KERN: package_daemon [69029216:  1166] The latest volume state is also the currently active one
KERN: package_daemon [69037142:  1166] KERN: Volume::InitialVerify((nil), (nil))
KERN: package_daemon [69044446:  1166] KERN: Volume::InitialVerify(): volume at "/boot/home/haikuports/haiku-apps/pe/work-2.4.5/boot/system" is consistent
KERN: package_daemon [69652440:  1166] Volume::_PackagesEntryCreated("pe-2.4.5-5-build.hpkg")
KERN: package_daemon [69681266:  1166] CommitTransactionHandler::_ChangePackageActivation(): activating 1, deactivating 0 packages
KERN: packagefs [69693785:  1166] Volume::_ChangeActivation(): 1 new packages, 0 old packages
KERN: packagefs [69701634:  1166] package "pe-2.4.5-5-build.hpkg" activated
KERN: vm_soft_fault: va 0xfc00000000 not covered by area in address space
KERN: vm_page_fault: vm_soft_fault returned error 'Bad address' on fault at 0xfc00000000, ip 0xfc7e98f402, write 0, user 1, thread 0x493
KERN: vm_page_fault: thread "jam" (1171) in team "jam" (1171) tried to read address 0xfc00000000, ip 0xfc7e98f402 ("jam_seg0ro" +0xf402)
KERN: debug_server: Thread 1171 entered the debugger: Segment violation
KERN: stack trace, current PC 0xfc7e98f402  hashitem + 0x53:
KERN:   (0x7f3b5610d360)  0xfc7e99181a  newstr + 0x5e
KERN:   (0x7f3b5610d3a0)  0xfc7e98f994  list_new + 0x5a
KERN:   (0x7f3b5610d3e0)  0xfc7e98c800  main + 0x691
KERN:   (0x7f3b5610e540)  0xfc7e98c0a8  _start + 0x54
KERN:   (0x7f3b5610e570)  0x2167b4a6e48  runtime_loader + 0x12b
KERN: package_daemon [74112682:   677] volume at "/boot/home/haikuports/haiku-apps/pe/work-2.4.5/boot/system" unregistered
KERN: package_daemon [74122802:   677] KERN: root at "/boot/home/haikuports/haiku-apps/pe/work-2.4.5/boot" unregistered

**Comment by diversys** [comment]
jam just needs to be rebuilt

**Comment by korli** [comment]
Should be fixed.
