### ISSUE TITLE
Jasper 2.0.13 package problems

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#1447]
hrev51209 x86_64
Built jasper 2.0.13 from haikuports recipe
When attempting to install there is a package problems notification:
"package libicns-0.8.1-5 requires lib:libjasper>=1.0.0, but none of the providers can be installed"

**Comment by korli** [comment]
I've some packages to rebuild to finish the ABI bump, this is one of them.

**Comment by korli** [comment]
This one should be OK.
