### ISSUE TITLE
mesa 17.0.6 dependency incorrectly named

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#1448]
When attempting to build mesa-17.0.6 it generates the following error:
"Fetching package for mako_python ...
*** Failed to find a match for "mako_python": Name not found"

The naming of the package found in HaikuDepot is reversed
"python_mako-1.0.3-1-x86_64.hpkg"

**Comment by Vidrep** [comment]
Making the following change in the mesa recipe "mako_python"-> "python_mako" now allows the source to compile properly:

BUILD_PREREQUIRES="
	llvm${secondaryArchSuffix}
	python_mako
	cmd:bison
	cmd:find
	cmd:flex
	cmd:gcc$secondaryArchSuffix
	cmd:ld$secondaryArchSuffix
	cmd:scons
	cmd:sed

**Comment by korli** [comment]
Hello Vidrep, it's correctly named. You meed to build "mako" first, which isn't in the depot yet.

**Comment by Vidrep** [comment]
Actually, there is a program in HaikuDepot named "python_mako". Installing it does not resolve the dependency issue because mesa is looking for "mako_python". Correcting the name in the recipe did allow the recipe to build.

**Comment by korli** [comment]
@Vidrep the recipe is named "mako", the packages named "mako_python" and "mako_python3". What is in HaikuDepot isn't up to date.
