### ISSUE TITLE
Please bump vulnerable Expat to 2.2.1

### ISSUE THREAD

**Issue by hartwork** [haikuports/haikuports#1453]
Please excuse my posting style.

Vulnerable copy found at:
https://github.com/haikuports/haikuports/tree/master/dev-libs/expat

Expat 2.2.1 change log:
https://github.com/libexpat/libexpat/blob/master/expat/Changes

Commits that you may need on top:
* https://github.com/libexpat/libexpat/commit/602e6c78ca750c082b72f8cdf4a38839b312959f
* https://github.com/libexpat/libexpat/commit/e5e25fac1698d9ea8dbb2e51c18d1072254b5f4b

Best, Sebastian

**Comment by waddlesplash** [comment]
Thanks for the notification!

**Comment by scottmc** [comment]
Added Milestone and Blocker to this.  Any takers?

**Comment by waddlesplash** [comment]
CC @Begasus - in case you have time to handle it.

Otherwise, if nobody else does, I can get to it by the weekend.

**Comment by korli** [comment]
This can't be a blocker.

**Comment by pulkomandy** [comment]
We already have a 2.2.0 recipe it seems? So is it just about deleting the old one?

**Comment by scottmc** [comment]
I think just need to update recipe to build 2.2.1 and remove old ones.

**Comment by waddlesplash** [comment]
There appear to be some pretty bad vulnerabilities fixed in it. It's a blocker.

**Comment by Begasus** [comment]
I'll try to have a look at it later, if time permits ...

**Comment by korli** [comment]
@waddlesplash IMO it might be a release blocker, not a beta blocker (a beta is feature complete and free of major bugs).

**Comment by waddlesplash** [comment]
@korli If this was a hard fix, I might agree with you, but it's a rather easy fix. I should have time to get to it later today if someone else doesn't.

**Comment by pulkomandy** [comment]
"Blocker" is not defined by wether the fix is easy. It is defined by the fact that we really, really can't release without the changes, which is clearly not the case here for a beta version.
Still, if we can get the changes in, it's all fine.

**Comment by korli** [comment]
Updated in 2ee42a5529a33e0b5e68047dca1eb11727bd5285
