### ISSUE TITLE
Something wrong with tinyxml recipe and package

### ISSUE THREAD

**Issue by miqlas** [haikuports/haikuports#1460]
I see the following if i try to start Blender:

> runtime_loader: Cannot open file libtinyxml.so.@MAJOR_V@: No such file or directory

It seems, opencolorio using it.

In the tinyxml recipe i see the following:

> mv libtinyxml.so.@MAJOR_V@.@MINOR_V@ $libDir/libtinyxml.so

Maybe something wrong with this...

**Comment by miqlas** [comment]
Yeah, it looks wrong:

> /P/haikuports ❯❯❯ objdump -x /boot/system/lib/libOpenColorIO.so.1.0.9
> 
> /boot/system/lib/libOpenColorIO.so.1.0.9:     file format elf64-x86-64
> /boot/system/lib/libOpenColorIO.so.1.0.9
> architecture: i386:x86-64, flags 0x00000150:
> HAS_SYMS, DYNAMIC, D_PAGED
> start address 0x0000000000000000
> 
> Program Header:
> (....)
> 
> Dynamic Section:
>   NEEDED               libtinyxml.so.@MAJOR_V@
>   NEEDED               libstdc++.so.6
>   NEEDED               libgcc_s.so.1
>   NEEDED               libroot.so
>   SONAME               libOpenColorIO.so.1

**Comment by korli** [comment]
Please replace the line https://github.com/haikuports/haikuports/blob/master/dev-libs/tinyxml/tinyxml-2.6.2.recipe#L47 with:
sed -e "s:@MAJOR_V@:2:" -e "s:@MINOR_V@:6.2:" $portDir/additional-files/Makefile > ./Makefile

BTW one could also add a pkgconfig file.

**Comment by Begasus** [comment]
Not sure if it fixes it, but if someone could take a look at it ... 
https://github.com/Begasus/haikuports/commit/d30249224c8aed1eb1bf4581c0a31dc49236f685

**Comment by korli** [comment]
Should be fixed by 176e4a25c63e6538aa750bef3f8d19481911ebb4
