### ISSUE TITLE
Qupzilla Icon in Haiku's style

### ISSUE THREAD

**Issue by Giova84** [haikuports/haikuports#1464]
Hi,
looking at the commits I've seen that, recently, the Qupzilla's icon has been changed to replicate the official one:
![QupZilla new icon ](http://funkyimg.com/i/2uCa6.png)

But previously there was this icon:
![QupZilla Haiku's icon](http://funkyimg.com/i/2uCa5.png)

Wouldn't be better to keep the icon in Haiku's style? Furthermore it better recalls a World Wide Web browser.
The latter was made years ago by Justin Stressman.

**Comment by Giova84** [comment]
However (I think it's fair), I'd like to point the original artwork from the author of this nice icon (Justin Stressman, as I've said: is another great artist as we can see from his blog!)
http://haikudou.blogspot.com/2012/07/a-journey-of-thousand-miles-begins-with.html

**Comment by threedeyes** [comment]
What do you think about it?
![qupzilla icon](http://funkyimg.com/i/2uDfH.png)

**Comment by Giova84** [comment]
Kudos, threedeyes! I forgot the fact that you're also an icon-maker :-)
This icon, IMHO, looks far better: is brighter and follows the nice style of Haiku!
I  vote for this icon, let's wait for Humdinger.

**Comment by diversys** [comment]
+1 Great work!

**Comment by threedeyes** [comment]
![qupzilla icons](http://funkyimg.com/i/2uDL8.png)

**Comment by Giova84** [comment]
Hi threedeyes, I vote for the first one, the one which is showed in Icon-O-Matic; otherwise I also like "qupzilla v1" icon.

**Comment by humdingerb** [comment]
I, too, like v1. Maybe try if including the tip of the light blue thingy in the black outline looks good.
The gradient of the sphere could use the blues of the original QupZilla icon. Maybe...

**Comment by pulkomandy** [comment]
My vote goes to v3, but I'd add a shadow below the white wing (or what is it?) over the globe and the blue one.

**Comment by threedeyes** [comment]
Fixed palette for v1 and v3.
![qupzilla icons](http://funkyimg.com/i/2uJrT.png)

**Comment by threedeyes** [comment]
Fixed in f3e5cacd6551fa6ed076710b4f299f932df9fea1
