### ISSUE TITLE
Python recipes are broken

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#1471]
@korli, it looks like in your unification of the Python2 and Python3 recipes, you (incorrectly) moved them from a traditional ARCHITECTURES setup to be 'any', which is invalid: setuptools builds bytecode (.pyc) files upon INSTALL, and this bytecode is architecture-dependent, and so the recipes can't be `any`.

If you ran a script to make these changes, running it in reverse (just for the ARCH part) would make sense. Otherwise I can do so.

**Comment by korli** [comment]
Last time I checked this was correct:
https://stackoverflow.com/questions/30443490/is-pyc-platform-independent

**Comment by waddlesplash** [comment]
Oh, it appears I was wrong -- pyc are arch-independent, but python-version dependent, which is why we didn't do it in the past: https://github.com/haikuports/haikuports/commit/22c10b29d25c986e03fc5647b7cab155bbbf1139

**Comment by waddlesplash** [comment]
So, should we keep them as any-arch, or move them to be arch-specific?

**Comment by korli** [comment]
The arch-specific recipes are already correctly specified (ie pycrypto). What is the issue actually?

**Comment by waddlesplash** [comment]
Hm, I guess there isn't one then.
