### ISSUE TITLE
Add recipe for TesseractTranslator

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#1487]
https://github.com/threedeyes/TesseractTranslator

**Comment by phoudoin** [comment]
I've one ^_^

Issue is libtesseract.so has a dependency on connect() which is unresolved. 
Our tesseract haikuports is broken?

**Comment by phoudoin** [comment]
This missing recipe issue is fixed. Could someone close it?

**Comment by korli** [comment]
There is some issue with the recipe, let's keep this issue open as a reminder.

**Comment by phoudoin** [comment]
The issue is (well, was, when my PR will be merged) in apps-text/tesseract port, not in the translator itself.
