### ISSUE TITLE
mesa update recipe to 17.1.3

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#1490]
Newest mesa is 17.1.3
CHECKSUM_SHA256="5f1ee9a8aea2880f887884df2dea0c16dd1b13eb42fd2e52265db0dc1b380e8c"

**Comment by diversys** [comment]
It would be much easier to merge a PR. If you're not familiar with git yet give https://try.github.io a try ;)

**Comment by korli** [comment]
17.1.4 with commit 317c7f94ea11020497218b1180ccd4837758736e
