### ISSUE TITLE
vim: split gvim into a separate sub-package

### ISSUE THREAD

**Issue by miqlas** [haikuports/haikuports#1509]
Wish from @[jessicah](https://github.com/haikuports/haikuports/issues/902#issuecomment-267750644) :

> _Can we split gvim into a separate sub-package? Otherwise it requires installing ruby just to install command line vim, which doesn't actually need ruby._

**Comment by pulkomandy** [comment]
Why does gvim need ruby, while the cli version doesn't?

if_ruby in vim (http://vimdoc.sourceforge.net/htmldoc/if_ruby.html) can be used both for CLI and GUI executable. It sounds annoying to have different setups for the CLI and GUI, as if you want to use a ruby plugin, you probably want it to work no matter if you use the GUI or CLI.

**Comment by miqlas** [comment]
@pulkomandy : no, there is no difference between vim and gvim, as they built with the same compile-time switches.

I already using `--enable-rubyinterp=dynamic` in the [vim recipe](https://github.com/haikuports/haikuports/blob/08615e025f3aa44e8ae5b0f973df76ed1f8dffa6/app-editors/vim/vim-8.0.0599.recipe), so ruby is dinamically checked at runtime and used if available. It isn't listed as REQ anymore.

So technically this ticket already solved, i just made it for me to remember to split gvim into a separate optional package. Not sure if it makes sense hovewer. Any ideas?

**Comment by pulkomandy** [comment]
Just remove the REQUIRES for ruby from the recipe then (if it is there)? I think we can even have a RECOMMENDS or some other way to specify such optional dependencies.

I don't mind splitting the package, but I'll likely always have gvim installed.

**Comment by miqlas** [comment]
then let's not do it.
