### ISSUE TITLE
Expat 2.2.2 has been released

### ISSUE THREAD

**Issue by hartwork** [haikuports/haikuports#1512]
Dear Expat maintainers,

Expat 2.2.2 has been released.  It fixes a few rough egdes that you reported with 2.2.1 and should help reduce the number of downstream patches.  The change log is up at https://github.com/libexpat/libexpat/blob/master/expat/Changes.  Please report bugs for anything new that you run into.

Best

&nbsp;
Sebastian

PS: I would love to send this via e-mail. If you have a mail contact to write to for this, please let me know.

**Comment by waddlesplash** [comment]
There is a mailing list: https://github.com/haikuports/haikuports/wiki/MailingList

**Comment by Begasus** [comment]
/sources/expat-2.2.2/lib/xmlparse.c:74: #error You do not have support for any sources of high quality entropy enabled.  For end user security, that is probably not what you want. Your options include: * Linux + glibc >=2.25 (getrandom): HAVE_GETRANDOM, * Linux + glibc <2.25 (syscall SYS_getrandom): HAVE_SYSCALL_GETRANDOM, * BSD / macOS (arc4random_buf): HAVE_ARC4RANDOM_BUF, * libbsd (arc4random_buf): HAVE_ARC4RANDOM_BUF + HAVE_LIBBSD, * Windows (RtlGenRandom): _WIN32. If insist on not using any of these, bypass this error by defining XML_POOR_ENTROPY; you have been warned. For CMake, one way to pass the define is: cmake -DCMAKE_C_FLAGS="-pipe -O2 -DHAVE_SYSCALL_GETRANDOM" . If you have reasons to patch this detection code away or need changes to the build system, please open a bug.  Thank you!

If I leave out the concerning check for:
#if !defined(HAVE_GETRANDOM) && !defined(HAVE_SYSCALL_GETRANDOM) \
    && !defined(HAVE_ARC4RANDOM_BUF) && !defined(_WIN32) \
    && !defined(XML_POOR_ENTROPY)
it works ...

**Comment by Begasus** [comment]
PS, that is for gcc2, for gcc5 it's ok ...

**Comment by hartwork** [comment]
Does libbsd exist on Haiku for rescue? Or is there native `arc4random` or something?

**Comment by Begasus** [comment]
libbsd exist on Haiku, arc4random seems not ... probably some missing feature (a ticket on the bug tracker has been created for this)

**Comment by hartwork** [comment]
libbsd alone would suffice, it provides both `arc4random`, `arc4random_buf`, only one is needed.

**Comment by Begasus** [comment]
I tried with LDFLAGS="-lbsd"  and other options (also --with-libbsd), but without luck ...

**Comment by hartwork** [comment]
If you have libbsd headers and .a installed and run `./configure --with-libbsd`, config.log should explain why `arc4random_buf` detection failed. My guess: some error mentioning `u_char`?

**Comment by pulkomandy** [comment]
You probably need to #define _BSD_SOURCE too?

**Comment by hartwork** [comment]
Can you share command lines and error logs / error output with me?

**Comment by Begasus** [comment]
Getting there, it builds now with another patch ... need to check on x86_64 first :)

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/1525
this one seems to be working ok, could probably use some checks (pkg-man gives the correct information so far) ...

**Comment by hartwork** [comment]
The way I read #1525 there is native (i.e. without libbsd) `arc4random_bug` on Haiku. I'd be happy to fix the related auto-detection in `configure.ac` for Haiku upstream if you can share the related bits from config.log or so.

**Comment by Begasus** [comment]
would be nice if there was a IRC channel on freenode where we could discuss this a bit sooner, I can be found in #haiku channel after my work is done (and if I find the time to check on things, trying to grab the config.log issue ...

**Comment by Begasus** [comment]
configure:15297: checking for arc4random_buf (BSD or libbsd)
configure:15312: gcc -o conftest -g -O2 -Wall -Wmissing-prototypes -Wstrict-prototypes -fexceptions -fno-strict-aliasing   -fno-strict-aliasing conftest.c  >&5
/sources/expat-2.2.2/conftest.c:30: warning: function declaration isn't a prototype
/sources/expat-2.2.2/conftest.c: In function `main':
/sources/expat-2.2.2/conftest.c:31: warning: implicit declaration of function `arc4random_buf'
/tmp/ccxVLceI.o: In function `main':
/sources/expat-2.2.2/conftest.c:31: undefined reference to `arc4random_buf'
collect2: ld returned 1 exit status
configure:15312: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "expat"
| #define PACKAGE_TARNAME "expat"
| #define PACKAGE_VERSION "2.2.2"
| #define PACKAGE_STRING "expat 2.2.2"
| #define PACKAGE_BUGREPORT "expat-bugs@libexpat.org"
| #define PACKAGE_URL ""
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define STDC_HEADERS 1
| #define BYTEORDER 1234
| #define HAVE_MEMMOVE 1
| #define HAVE_BCOPY 1
| /* end confdefs.h.  */
| 
|   #include <stdlib.h>  /* for arc4random_buf on BSD, for NULL */
|   #if defined(HAVE_LIBBSD)
|   # include <bsd/stdlib.h>
|   #endif
|   int main() {
|     arc4random_buf(NULL, 0U);
|     return 0;
|   }
| 
configure:15322: result: no
configure:15330: checking for getrandom (Linux 3.17+, glibc 2.25+)
configure:15342: gcc -o conftest -g -O2 -Wall -Wmissing-prototypes -Wstrict-prototypes -fexceptions -fno-strict-aliasing   -fno-strict-aliasing conftest.c  >&5
/sources/expat-2.2.2/conftest.c:27: sys/random.h: No such file or directory
configure:15342: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "expat"
| #define PACKAGE_TARNAME "expat"
| #define PACKAGE_VERSION "2.2.2"
| #define PACKAGE_STRING "expat 2.2.2"
| #define PACKAGE_BUGREPORT "expat-bugs@libexpat.org"
| #define PACKAGE_URL ""
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define STDC_HEADERS 1
| #define BYTEORDER 1234
| #define HAVE_MEMMOVE 1
| #define HAVE_BCOPY 1
| /* end confdefs.h.  */
| 
|   #include <stdlib.h>  /* for NULL */
|   #include <sys/random.h>
|   int main() {
|     return getrandom(NULL, 0U, 0U);
|   }
| 
configure:15352: result: no
configure:15355: checking for syscall SYS_getrandom (Linux 3.17+)
configure:15369: gcc -o conftest -g -O2 -Wall -Wmissing-prototypes -Wstrict-prototypes -fexceptions -fno-strict-aliasing   -fno-strict-aliasing conftest.c  >&5
/sources/expat-2.2.2/conftest.c:28: sys/syscall.h: No such file or directory
configure:15369: $? = 1
configure: failed program was:
| /* confdefs.h */

**Comment by korli** [comment]
Superseded by 2.2.3 in 68b032af7a1e85c7b43c29cfe7e32ac39fcedf5f.
