### ISSUE TITLE
QtWebKit 5.212.0~alpha2 fails to build on x86_gcc2

### ISSUE THREAD

**Issue by Lan72** [haikuports/haikuports#1515]
QtWebKit 5.212.0~alpha2 fails to build on x86_gcc2 with a standard error:

> Makefile:162: recipe for target 'all' failed
> make: *** [all] Error 2
> [Errno -2147459069] No such file or directory: '/boot/home/haikuports/dev-qt/qtwebkit/work-x86-5.212.0~alpha2'
> Error: Build has failed - stopping.
[Error.txt](https://github.com/haikuports/haikuports/files/1153950/Error.txt)

**Comment by threedeyes** [comment]
You need qt 5.9 for qtwebkit 5.212 building.

**Comment by Lan72** [comment]
I know, but Qt 5.9 also isn't build on x86_gcc2 the approximately same error: 
https://github.com/haikuports/haikuports/issues/1343#issuecomment-302966288

**Comment by diversys** [comment]
The actual error should be above that error message though.

**Comment by threedeyes** [comment]
Fixed in e7d8e2392a7c5a6cf73ad254f92843411a0de4be

**Comment by Lan72** [comment]
After numerous attempts to build QtWebKit 5.212.0~alpha2 on x86_gcc2 I didn't manage to make it. The error is the same, described above.

At first gcc 5.4 falls by 6% of the process (see a screenshot), 
![screenshot](https://user-images.githubusercontent.com/26386474/32982098-a1d6340c-cc87-11e7-914c-1ccbc5d7b740.jpg)
and then building stops at 24% with a standard error: 
[Error_Qt5WebKit.txt](https://github.com/haikuports/haikuports/files/1484723/Error_Qt5WebKit.txt)
