### ISSUE TITLE
Some any-arch font recipes failing to build

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#1516]
see: http://vmpkg.haiku-os.org/kitchen/#/build/23

symbola & lato fail checksum, nanumfont throws an "ascii codec can't decode ordinal", open_sans gives 404.

**Comment by diversys** [comment]
* symbola & lato are done. 

* nanumfont downloads font with Korean filename which hp fails to read. https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte
`sys.getdefaultencoding() `in python returns ascii instead of utf8. 

* open_sans is 404 and I didn't manage to find a mirror.

**Comment by waddlesplash** [comment]
Google Fonts has Open Sans: https://fonts.google.com/specimen/Open+Sans?selection.family=Open+Sans

I don't know if the download is scriptable though?

**Comment by korli** [comment]
https://github.com/google/fonts/tree/master/apache/opensans/
for instance: https://github.com/google/fonts/raw/beaec0837bd21524b57ecb435158f9011fc03999/apache/opensans/OpenSans-Bold.ttf

**Comment by Begasus** [comment]
For open-sans ... 
https://github.com/haikuports/haikuports/pull/1549

**Comment by Begasus** [comment]
If nothing is left behind this could be closed?

**Comment by korli** [comment]
I think symbola fails, the archive URL needs a stable version mirror.

**Comment by Begasus** [comment]
http://users.teilar.gr/%7Eg1951d/Symbola.zip ?

**Comment by Begasus** [comment]
checksum fails, not sure if it's related to the prior update on that recipe?

**Comment by Begasus** [comment]
This fixes the checksum for Symbola ...
https://github.com/haikuports/haikuports/pull/1785

**Comment by Begasus** [comment]
This can be closed now?

**Comment by korli** [comment]
Thanks!
