### ISSUE TITLE
All autotools-based recipes failing to build following mass package updates

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#1517]
see http://vmpkg.haiku-os.org/kitchen/#/build/22. For instance: 
```
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /bin/automake line 3936.
autoreconf: automake failed with exit status: 255
```
All the other failed autotools-based recipes have the same error.

This started happening after I `pkgman full-sync`'d @kallisti5's builder to the latest HaikuPorts, which contains @korli's mass-rebuilded packages. @korli -- do you have any idea what's going on here?

**Comment by pulkomandy** [comment]
This messages comes from Perl (from version 5.22), they changed something about how they handle regex.
Either revert to an older perl or update the autotools to a newer version.

**Comment by waddlesplash** [comment]
Indeed. Fixed with an automake update.
