### ISSUE TITLE
nasm fails to build following perl upgrade

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#1521]
```
perl -I./perllib ./macros.pl ./standard.mac version.mac \
    ./macros/*.mac ./output/*.mac
Can't locate pptok.ph in @INC (did you run h2ph?) (@INC contains: ./perllib /packages/perl-5.26.0-1/.self/non-packaged/lib/perl5/site_perl/5.26.0/x86_64-haiku /packages/perl-5.26.0-1/.self/non-packaged/lib/perl5/site_perl/5.26.0 /packages/perl-5.26.0-1/.self/lib/perl5/vendor_perl/5.26.0/x86_64-haiku /packages/perl-5.26.0-1/.self/lib/perl5/vendor_perl/5.26.0 /packages/perl-5.26.0-1/.self/lib/perl5/5.26.0/x86_64-haiku /packages/perl-5.26.0-1/.self/lib/perl5/5.26.0) at ./macros.pl line 40.
Makefile:151: recipe for target 'macros.c' failed
make: *** [macros.c] Error 3
```
http://vmpkg.haiku-os.org/kitchen/#/build/37
cc @korli

**Comment by korli** [comment]
I would suggest to remove perl from the BUILD_PREREQUIRES. The timestamps seem to lure make to rebuild the output files, but it's not needed.
The list of perl generated files to touch from the Makefile:
x86/insnsb.c x86/insnsa.c x86/insnsd.c x86/insnsi.h x86/insnsn.c \
x86/regs.c x86/regs.h x86/regflags.c x86/regdis.c x86/regdis.h \
x86/regvals.c asm/tokhash.c asm/tokens.h asm/pptok.h asm/pptok.c \
x86/iflag.c x86/iflaggen.h \
macros/macros.c \
asm/pptok.ph asm/directbl.c asm/directiv.h \
version.h version.mac version.mak nsis/version.nsh
