### ISSUE TITLE
various python packages fail to build with "No module named '_ctypes'"

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#1532]
See: https://kitchen.haiku-os.org/#/build/9

Specifically (python3): feedparser, fonttools, html2text, mako.

Cc @korli.

**Comment by waddlesplash** [comment]
(this is rather important because non-GCC2 mesa depends on mako to build, and so Qt, etc. can't be built without it either)

**Comment by jessicah** [comment]
Seems to be missing libffi and devel declarations (python2 recipes include libffi).

See: https://stackoverflow.com/questions/27022373/python3-importerror-no-module-named-ctypes-when-using-value-from-module-mul#comment42577506_27022373
