### ISSUE TITLE
mosh: "EINTR" is not exported by the Errno module

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#1534]
Most of the tests run by `make check` fail with `"EINTR" is not exported by the Errno module` error.
[test-suite.txt](https://github.com/haikuports/haikuports/files/1177726/test-suite.txt)

**Comment by diversys** [comment]
I compared `Errno.pm` from macOS version of perl 5.24.1 and it looks like
`/system/lib/perl5/5.18.2/x86_64-haiku/Errno.pm` is incomplete. I.e. BEGIN block misses all error defines.

**Comment by diversys** [comment]
This seems to be https://rt.perl.org/Public/Bug/Display.html?id=123784 which was fixed in v5.22.
So Perl 5.18.2 in HaikuPorts repo is broken and needs to be updated (with it deps).

**Comment by korli** [comment]
could you check that perl 5.26 is OK?

**Comment by waddlesplash** [comment]
CC @diversys?

**Comment by diversys** [comment]
Most of the tests still fail but I don't see this error anymore. Closing.
