### ISSUE TITLE
QTHaikuPlugin: build fails

### ISSUE THREAD

**Issue by miqlas** [haikuports/haikuports#1540]
The current QtHaikuPlugins recipe ( https://github.com/haikuports/haikuports/commit/504b68d72ab3e1c101b0f0e149d3b0e780e38694 ) doesn't builds on x86_64:

> waiting for build package qthaikuplugins-1.0~git-3 to be activated
> Building ...
> cd haiku/ && ( test -e Makefile || /bin/qmake -o Makefile /sources/qthaikuplugins-72a1763761fb47b12470f6bccdaec2d9f2a96d66/platforms/qhaikuplatform/haiku/haiku.pro ) && make -f Makefile 
> make[1]: Entering directory '/sources/qthaikuplugins-72a1763761fb47b12470f6bccdaec2d9f2a96d66/platforms/qhaikuplatform/haiku'
> make[1]: *** No rule to make target '/packages/qt5-5.9.1-2/.self/lib/libQt5EventDispatcherSupport.a', needed by '../plugins/platforms/libqhaiku.so'.  Stop.
> make[1]: Leaving directory '/sources/qthaikuplugins-72a1763761fb47b12470f6bccdaec2d9f2a96d66/platforms/qhaikuplatform/haiku'
> Makefile:44: recipe for target 'sub-haiku-make_first' failed
> make: *** [sub-haiku-make_first] Error 2
> Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 2
> Error: Build has failed - stopping.

The makefile contains this:

> ####### Build rules
> 
> ../plugins/platforms/$(TARGET): /packages/qt5-5.9.1-2/.self/lib/libQt5EventDispatcherSupport.a /packages/qt5-5.9.1-2/.self/lib/libQt5FontDatabaseSupport.a /packages/qt5-5.9.1-2/.self/lib/libQt5ThemeSupport.a $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
> 	@test -d ../plugins/platforms/ || mkdir -p ../plugins/platforms/
> 	-$(DEL_FILE) $(TARGET)
> 	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
> 	-$(MOVE) $(TARGET) ../plugins/platforms/ 

But it shouldn't list that static libs, as it works if i remove them, but this makefile is a generated one, so we should patch the file, what generates them, but i can't find why are they there.

**Comment by threedeyes** [comment]
You need qt5-5.9.1-3. This bug fixed in https://github.com/haikuports/haikuports/commit/d0291562eacac18398925fc4329df6b893628550#diff-fbf61c0bb92e06ab684fc7987324f8e2R443

**Comment by miqlas** [comment]
@threedeyes : thanks for the info. That rev is not available in depot. I wait then.

**Comment by miqlas** [comment]
Closing as solved.
