### ISSUE TITLE
Qupzilla: the GreaseMonkey addon cause spam in the syslog

### ISSUE THREAD

**Issue by Giova84** [haikuports/haikuports#1550]
Haiku hrev51336 gcc2h but I also noticed this in old revision.

While I had opened the /var/log folder I noticed that the Syslog file was growing second after second with the same messagges: http://sprunge.us/SRZR

I noticed that when I quit Qupzilla this no longer occurs... After some investigation i further noticed that this trouble occurs when in QupZilla I have enabled the GreaseMonkey addon: if I disable such addon, the Syslog file is no longer spammed.

My disk is sane and in a good health (checkfs -c /boot give no errors).

**Comment by diversys** [comment]
Unable to reproduce it here...

**Comment by waddlesplash** [comment]
QupZilla removed in https://github.com/haikuports/haikuports/commit/6187dcea9436f01b87034f2af894608065b18caa.
