### ISSUE TITLE
Psi+: enable QTWebkit

### ISSUE THREAD

**Issue by Giova84** [haikuports/haikuports#1554]
Is possible to build Psi Plus by also using the QTWebkit: in this way is possible to use themes and a better management of web contents. In the recipe should be added `--enable-webkit`; some months ago, in facts I built Psi+ with the webkit support and look nicer and more useful.

**Comment by korli** [comment]
Could you make a PR for it?

**Comment by Giova84** [comment]
As I've said in the other ticket #1555 I don't know how to make a PR...

However for Psi+ there is the need to add the ```--enable-webkit``` line in the recipe, and for compile it on gcc2h, there is the need to point to ```qmake-x86``` instead of ```qmake``` in the configure file.

**Comment by Giova84** [comment]
In the PR #1558 I enabled the ability to build PSI+ with QtWebkit.
The next PR will be to check if we are on gcc2h and set `qmake` to `qmake-x86`. I was thinking to implement something like this in the recipe, in the `PATCH()` section, which check if is Haiku gcc2h or Haiku X86:

```
currentarch=$(getarch)
if [ $currentarch == x86_gcc2 ]; then
echo "you are on gcc2h"
configfile=/boot/home/haikuports/net-im/psi_plus/work-x86-0.16.475/sources/psi-plus-snapshots-0.16.475/configure
sed "/qmake/c\qmake-x86" -i $configfile
else
echo "you are on x86"
fi
```

I have tried and works OK, but I'm not sure if it can be done in a better way: however I also think that would be needed to enable x86_gcc2 in the recipe file, from `ARCHITECTURES="!x86_gcc2 x86"` to `ARCHITECTURES="x86_gcc2 x86"`

@diversys can you  give me some hints?

**Comment by pulkomandy** [comment]
This should not be needed. I think haikuporter already handles it (it does something similar to "setarch").
And, why is qmake installed to bin/x86 anyway? There will never be a Qt for gcc2, so the binaries for the secondary arch could go in the main bin directory?

**Comment by Giova84** [comment]
Last time I've built psi plus on Haiku gcc2h, and I had the need to set qmake-x86 in the configure file, because, as you noticed, on Haiku the qmake-x86 (at least on QT 4.8.7) is under /system/bin; qmake, instead, in under /system/bin/x86.

However diver told me to change the previous PR, but I don't understand where I have to bump the revision: in the recipe name?

**Comment by pulkomandy** [comment]
Inside the recipe, there is a REVISION="1" line. You need to increase this each time you change the recipe. This way we can see the difference between packages made before and after the change.

**Comment by scottmc** [comment]
@Giova84 here's our wiki page for how to fork and then make pull requests.

https://github.com/haikuports/haikuports/wiki/DevelopmentModel

One you learn this process, doing pull requests will be much easier.  Then
we can comment on this in line, and merge them when they are ready.
