### ISSUE TITLE
Enable privoxy on gcc2h

### ISSUE THREAD

**Issue by Giova84** [haikuports/haikuports#1555]
Currently, the `privoxy-3.0.26.recipe`, reports `ARCHITECTURES="?x86_gcc2 ?x86 x86_64 ?ppc"`

But changing to `ARCHITECTURES="x86_gcc2 ?x86 x86_64 ?ppc"` will make it able to build Privoxy also on gcc2h: I have been able, in facts, to build it on gcc2h.

**Comment by korli** [comment]
Could you make a PR?

**Comment by Giova84** [comment]
If I would been able to make a pull request, I'd avoid to open a ticket :-)
So I'm very sorry, because I'm not confidential at all with Git...
Is the same for #1554

Anyway for Privoxy is just a matter to edit the ```ARCHITECTURES=``` line in the recipe

**Comment by diversys** [comment]
Hope this helps:
https://try.github.io/levels/1/challenges/1
https://help.github.com/articles/creating-a-pull-request/

**Comment by Giova84** [comment]
Thanks, @diversys
I will take a look, also if I still can't figure out: I have to fork something, then make the changes on the fork and then send a PR?

However I read:
>In the "Branch" menu, choose the branch that contains your commits.
>To the right of the Branch menu, click New pull request.

Well, I am on Qupzilla and when I click on any menu here on this website, nothing happens.
Also with WebPositive, this website doesn't works very good..
Is a shame, considerind the fact that GitHub is useful and necessary for Haiku, but on Haiku's browsers this website is partially working. I'm very sorry for the offtopic/rant.

However, since send a PR could require some time (for me), can someone take care of apply the changes which I reported?

**Comment by pulkomandy** [comment]
You can use "hub" from Haiku command line to create pull requests. It may be easier than using a web browser, especially a broken one :)

**Comment by Giova84** [comment]
Thanks, Pulkomandy: I will do an attempt this evening.
Last question: to do my changes I have to clone the whole HaikuPorts repository or I can just grab the sources which I need?

**Comment by diversys** [comment]
@Giova84 Yes, you fork haikuports using Fork button on this page.

There is a simpler route for you, you can just open the recipe https://github.com/haikuports/haikuports/blob/master/net-proxy/privoxy/privoxy-3.0.26.recipe
click Edit button and edit it right in the browser. This will automatically fork haikuports and create a PR.

**Comment by Giova84** [comment]
@diversys  I'm back on Google Chrome on Windows and I wil try do this now :-)

**Comment by Giova84** [comment]
Done PR in #1557

**Comment by korli** [comment]
Thanks!
