### ISSUE TITLE
Lynx: fails to connect to some sites

### ISSUE THREAD

**Issue by PeteCA** [haikuports/haikuports#1568]
I decided I wanted a text-access browser that wasn't bedevilled by all the javascript crud and so on, so I picked up Lynx 2.8.9 from the repository.  Unfortunately it just fails to connect to a few sites that it should have no trouble with (e.g. bbc.co.uk).

I went back to the stable 2.8.8 source and compiled it (with the needed Haiku patch or two), but it suffered from the same problem.  After investigation it seems that the Haiku return codes from connect are sufficiently different from, say, Linux that the were not recognized by the program.

In particular, Haiku returns EINPROGRESS where Linux returns EALREADY.  The following trivial patch to WWW/Library/Implementation/HTTCP.c fixes things:

```
`--- "HTTCP.c ORIG"	2013-12-17 17:56:13.000000000 -0800
+++ HTTCP.c	2017-08-04 21:52:36.109314048 -0700
@@ -2104,6 +2104,7 @@
 #endif /* INET6 */
 		    if ((status < 0) &&
 			(SOCKET_ERRNO != EALREADY
+			 && SOCKET_ERRNO != EINPROGRESS
 #ifdef EAGAIN
 			 && SOCKET_ERRNO != EAGAIN
 #endif`

[OK -- I totally failed to enter the above with WebPositive.  I'm now in Linux and it seems to have worked... (:-/)]

**Comment by PeteCA** [comment]
OK... I'm sorry about that, but W+ is just leaving me helpless!!  I get no tooltips -- just blank balloons -- so I can't find how to insert the patch verbatim.  Nor can I see any way to edit what looked reasonable before I submitted it...  If you can't understand what I posted, email me.

**Comment by korli** [comment]
the code in question:

```
		{
		    /*
		     * The select says we aren't ready yet.  Try to connect
		     * again to make sure.  If we don't get EALREADY or
		     * EISCONN, something has gone wrong.  Break out and report
		     * it.
		     *
		     * For some reason, SVR4 returns EAGAIN here instead of
		     * EALREADY, even though the man page says it should be
		     * EALREADY.
		     *
		     * For some reason, UCX pre 3 apparently returns errno =
		     * 18242 instead of EALREADY or EISCONN.
		     */
#ifdef INET6
		    status = connect(*s, res->ai_addr, res->ai_addrlen);
#else
		    status = connect(*s, (struct sockaddr *) &soc_address,
				     sizeof(soc_address));
#endif /* INET6 */
		    if ((status < 0) &&
			(SOCKET_ERRNO != EALREADY
#ifdef EAGAIN
			 && SOCKET_ERRNO != EAGAIN
#endif
			) &&
#ifdef UCX
			(SOCKET_ERRNO != 18242) &&
#endif /* UCX */
			(SOCKET_ERRNO != EISCONN)) {
#ifdef SOCKET_DEBUG_TRACE
			HTInetStatus("confirm-not-ready connect");
#endif /* SOCKET_DEBUG_TRACE */
			break;
		    }

```

It seems like a bug in Haiku: a first connect() has already returned EINPROGRESS, the second connect() should only return EALREADY or EISCONN.

http://pubs.opengroup.org/onlinepubs/9699919799/functions/connect.html
"Subsequent calls to connect() for the same socket, before the connection is established, shall fail and set errno to [EALREADY]."

**Comment by PeteCA** [comment]
Ah -- that sounds definitive.  I thought it was probably a different interpretation of the protocol, but I guess Haiku has it wrong.  The patch might be useful until it's corrected though.  I tried my patched code in Linux, too, and it doesn't clobber anything there.

**Comment by korli** [comment]
I opened a bug report https://dev.haiku-os.org/ticket/13662

**Comment by PeteCA** [comment]
Thanks!  More informative than I would have been able to do....

**Comment by korli** [comment]
Applied a fix in hrev51358. Could you eventually check?
BTW it seems lynx in x86_64 depot seems to not have ssl build in.

**Comment by PeteCA** [comment]
May be a while before I get a chance to update, but I'll try to get there.

I guess it doesn't get ssl because the package is actually 'openssl_devel....' and the recipe just specifies 'devel:libssl'.

**Comment by pulkomandy** [comment]
No, that sounds correct.

Each package comes with a list of 'PROVIDES' entries which allows us to have fine grained dependencies. The library is indeed called libssl, and the OpenSSL development package declares that (otherwise haikuporter would complain that it can't resolve the dependency).

This allows us to rework how packages are organized and named without having to change dependencies in other packages. As long as there is something providing devel:libssl (which reads "development files for libssl"), it will be usable. No matter if the package is named openssl_devel, openssl_dev, or whatever convention we decide to use in the future.

**Comment by korli** [comment]
No feedback from original reporter. Closing as fixed.
