### ISSUE TITLE
Write recipe for Calibre

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#1571]
I worked on the source some months ago ( https://github.com/kovidgoyal/calibre/pull/620 ), the GUI worked okay, not tested with external devices like ebookreader, but it got libmtp and libusb support, so it could work.

Maybe the supporting code aged a bit, but one could polish it to get more e-book-fetish-coverage on Haiku platform, because throw out your damn tv boy!

Ah, btw, it requires some python stuff, but it couldn't be a tought task, as i got them compiled locally and i'm not Neumann, btw.

**Comment by unspacyar** [comment]
Hi. If you need some test with a reader, I could do it. I have a Kindle and a Sony reader.

**Comment by miqlas** [comment]
@unspacyar : Great! Thanks! Just build Calibre and report back!

**Comment by diversys** [comment]
This is what I'm getting when trying to build on x86_64 with sip (which doesn't contain any files) and sip_python installed.
![image](https://user-images.githubusercontent.com/1316513/33960653-74d996b8-e05c-11e7-9fd3-cc95c77f168f.png)

**Comment by extrowerk** [comment]
It requires PyQt5, but i suppose it is clear to you.

**Comment by extrowerk** [comment]
And btw what the heck is with your terminal?
I know you got a mac, but the mouse cursor is the haiku one, so hmmm...

**Comment by diversys** [comment]
This is with installed PyQt5. It's Haiku Terminal.

**Comment by extrowerk** [comment]
Will look into it during my vacation.

-- Z.

2017.12.14. dátummal, 7:51 időpontban diversys <notifications@github.com> írta:

**Comment by extrowerk** [comment]
So the current dependencies:

- [ ] zlib
- [ ] bzip2
- [ ] unrar
- [ ] unrardll
- [ ] expat
- [ ] sqlite
- [ ] libffi
- [ ] openssl
- [ ] ncurses
- [ ] readline
- [ ] python
- [ ] pywin32
- [ ] setuptools
- [ ] six
- [ ] cssutils
- [ ] dateutil
- [ ] dnspython
- [ ] mechanize
- [ ] regex
- [ ] dukpy
- [ ] chardet
- [ ] msgpack
- [ ] pygments
- [ ] pycrypto
- [ ] apsw
- [ ] icu
- [ ] nasm
- [ ] cmake
- [ ] libjpeg
- [ ] libpng
- [ ] libwebp
- [ ] jxrlib
- [ ] freetype
- [ ] fontconfig
- [ ] iconv
- [ ] libxml2
- [ ] libxslt
- [ ] lxml
- [ ] html5-parser
- [ ] webencodings
- [ ] html5lib
- [ ] pillow
- [ ] netifaces
- [ ] psutil
- [ ] chmlib
- [ ] poppler
- [ ] podofo
- [ ] libgpg-error
- [ ] libgcrypt
- [ ] glib
- [ ] dbusglib
- [ ] dbuspython
- [ ] dbus
- [ ] qt
- [ ] webkit
- [ ] sip
- [ ] pyqt
- [ ] optipng
- [ ] mozjpeg
- [ ] libusb
- [ ] libmtp
- [ ] macfsevents
- [ ] easylzma

**Comment by Begasus** [comment]
For easylzma: https://github.com/haikuports/haikuports/pull/3228

**Comment by luka177** [comment]
For dukpy: https://github.com/haikuports/haikuports/pull/4473/
(not tested on x86)

**Comment by korli** [comment]
see #4657
