### ISSUE TITLE
Suggestion for PHP port

### ISSUE THREAD

**Issue by HutchSails** [haikuports/haikuports#1588]
I like the php port.  I have a number of apps that use the php-fpm option of php.  Would be great it that could be added!

**Comment by miqlas** [comment]
@HutchSails : just take my recipe and patchset, change it according your requiments, build and test it, report back and i will implement the neccessary changes (what you reported) in my recipe.
Deal?

**Comment by kenmays** [comment]
Added in php 8.1.

**Comment by extrowerk** [comment]
> Present in php 7.4.30 and php 8.1.9.

Neither the modified recipes nor the updated patchsets mentions ```php-fpm```. Do they really enabled?
