### ISSUE TITLE
[qt5] build is broken on x86_gcc2 hybrid

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#1684]
http://vmpkg.haiku-os.org/master/x86_gcc2/buildruns/130/builds/983.log

```
/Media/Source/builder/x86_gcc2/packages/openssl-1.0.2l-1-x86_gcc2.hpkg
/Media/Source/builder/x86_gcc2/packages/openssl_x86-1.0.2g-1-x86_gcc2.hpkg
/Media/Source/builder/x86_gcc2/packages/openssl_x86-1.1.0f-1-x86_gcc2.hpkg
/Media/Source/builder/x86_gcc2/packages/openssl_x86_devel-1.1.0f-1-x86_gcc2.hpkg
```

Looks like one of these patches is needed:
https://github.com/OpenMandrivaAssociation/qt5-qtbase/blob/master/0001-Port-QSslCertificate-to-openssl-1.1.patch
https://github.com/patch-exchange/openssl-1.1-transition/blob/master/qt5-qtbase/qtbase-5.7.0-openssl-1.1.patch

**Comment by diversys** [comment]
Need to check if was merged to Qt 5.9.2

http://code.qt.io/cgit/qt/qtbase.git/commit/?id=cfbe03a6e035ab3cce5f04962cddd06bd414dcea

**Comment by diversys** [comment]
Looks like "OpenSSL 1.1 backend" commit didn't make it to to Qt 5.9.2 and is planned for 5.9.10 https://wiki.qt.io/Qt_5.10_Release

https://github.com/qt/qtbase/commits/5.10/src/network/ssl

**Comment by korli** [comment]
Build seems complete: http://vmpkg.haiku-os.org/master/x86_gcc2/?buildrunDir=263&viewMode=compact

**Comment by waddlesplash** [comment]
And it has appeared in https://eu.hpkg.haiku-os.org/haikuports/master/repository/x86_gcc2/current/packages/
