### ISSUE TITLE
Einsteinium: policy error on x86_64

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#1694]
Can't find used library: libstdc++.r4.so

**Comment by Begasus** [comment]
working ok here on x86_64 (first time build) ...
grabbing einsteinium-1.4.1-1-x86_64.hpkg and moving it to /boot/home/haikuports/packages/einsteinium-1.4.1-1-x86_64.hpkg

**Comment by Begasus** [comment]
I haven't updated my install here, maybe with the recent changes they showed up?

uname -a
Haiku shredder 1 hrev51441 Sep 25 2017 17:18:57 x86_64 x86_64 Haiku

**Comment by korli** [comment]
Fixed in 2e1c509337f9a8eab8720d0f823ec5e80cddabcd
