### ISSUE TITLE
Luarocks: policy error

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#1695]
For instance : Missing provides for cmd:luarocks_5.3

**Comment by Begasus** [comment]
I'm not getting the policy error?
cmd:luarocks_$LUAVERSION$secondaryArchSuffix = $portVersion (this provides luarocks_5.3 for me)
luarocks version in Terminal also shows version 2.4.2 ...

**Comment by korli** [comment]
Move your system lua hpkg in your Haikuports packages directory. Touch the luarocks recipe and try a rebuild. Using the installed lua version in LUAVERSION is indeed incorrect.

**Comment by Begasus** [comment]
Ah, maybe because I only have lua5.3 installed?

**Comment by Begasus** [comment]
moved it over to ~/config/packages, "touch" luarocks, but still no policy error here ...

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/1699
Hope this fixes it for your?

**Comment by Begasus** [comment]
checked on all arch's here ...

**Comment by korli** [comment]
It should, thanks.
