### ISSUE TITLE
adding x86_gcc2 to SECONDARY_ARCHITECTURES ...

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#1711]
Is it still needed to have SECONDARY_ARCHITECTURES="(!/?x86_gcc2)" for x86, there are no x86 images (anyboot/iso's) around any more, so sounds like we don't have to build x86_gcc2 packages for a x86 system?

**Comment by korli** [comment]
I would avoid adding x86_gcc2 at all in secondary architectures.

**Comment by Begasus** [comment]
Hence my question :) we 'had' a x86 image available where it would be plausible to use it, but since we don't have it around it sounds useless ...

**Comment by korli** [comment]
Well you could also remove ppc arm m68k, what benefits?

**Comment by Begasus** [comment]
do you build "x86_gcc2" as secondary arch on ppc arm m68k? if so, it would be ok to have it in :)
(ps, no experience in those arches) ...

**Comment by korli** [comment]
x86_gcc2 could be a secondary arch for x86_64 if that's your question.

**Comment by Begasus** [comment]
If it's possible to use x86_gcc2 in a x86_64 system I stand corrected and it could stay in

**Comment by waddlesplash** [comment]
Well it's not right now, and it's unclear that it ever will be.

**Comment by Begasus** [comment]
I think this can be closed? I don't see x86_gcc2 in the newer/updated recipes (secondary arch's) ...
