### ISSUE TITLE
quassel uses a git binary patch

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#1717]
When building without git, the build fails.

**Comment by digitalcircuit** [comment]
Based on [a build log](https://launchpadlibrarian.net/335855400/buildlog_ubuntu-artful-amd64.quassel_1%3A0.13~201709050202~20170904.0260fbe~ubuntu17.10.1_BUILDING.txt.gz ) from @mamarley's [unofficial Ubuntu PPA](https://launchpad.net/~mamarley/+archive/ubuntu/quassel-git ), Quassel shouldn't need `git` to build...

```
[...]
-- The following OPTIONAL packages have not been found:

 * LibsnoreQt5 (required version >= 0.7.0), a cross-platform notification framework,
<https://projects.kde.org/projects/playground/libs/snorenotify>
   Enable support for the snorenotify framework
 * Ldap
 * Git
[...]
```

I'm not sure how Quassel's CMake build system works, though, and **someone else might need to chime in.**

**Comment by korli** [comment]
You misunderstand the issue. The provided patchset https://github.com/haikuports/haikuports/blob/master/net-irc/quassel/patches/quassel-0.9.2.patchset needs 'git' to handle the git binary patch format, this is normally not needed. Using 'patch' should suffice.

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/8905
