### ISSUE TITLE
games-arcade/xrick uses a binary patch

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#1719]

**Comment by pulkomandy** [comment]
can you clarify what you mean by "binary patch"? I don't understand the problem

**Comment by korli** [comment]
see https://github.com/haikuports/haikuports/blob/master/games-arcade/xrick/patches/xrick-021212.patchset#L381
Such patches can't be applied with "patch", only with git.

**Comment by pulkomandy** [comment]
Oh, I see. These are only PNG files used in the README, I think we can remove them?

**Comment by korli** [comment]
I don't know: what is this README meant for?

**Comment by pulkomandy** [comment]
I think @humdingerb added it because otherwise there's no way to know the keys to use to play the game. But maybe it doesn't need the pictures, or we can simply move them to additional-files instead of in the patch.

**Comment by Begasus** [comment]
Some keys were changed in the patch I think, there is a file with keycodes included in the source, don't know how much it deviates from the ones mentioned in the readme from @humdinger

**Comment by Begasus** [comment]
Fixed in: https://github.com/haikuports/haikuports/pull/8906
