### ISSUE TITLE
app-arch/unarr: obsolete version, please use upstream as source

### ISSUE THREAD

**Issue by selmf** [haikuports/haikuports#1723]
The port currently uses a 2 year old version of unarr that has known bugs. This isn't unarr 1.0, it's a pre-1.0 snapshot (1.0~[number of git commit].[git shorthash], the tilde after the 1.0 indicates the version is lower than 1.0 in Debian version syntax).  This version has at least one major bug (no largefile support). For me this wasn't an issue as I simply patched that bug in the Debian package. For you it probably is as that patch isn't included in the source you're using.

So, please update your port ;) And don't use my openSuse buildservice repo as source, use the proper unarr 1.0.0 upstream release. It's available [here.](https://github.com/selmf/unarr/releases)

**Comment by phoudoin** [comment]
I will update the port recipe. Thanks for notice.

**Comment by phoudoin** [comment]
BTW, there is a typo in pkg-config.pc.cmake:

@CMAKE_INSTALL_INCLUDEDIR_LIBDIR@ should be @CMAKE_INSTALL_LIBDIR@

**Comment by selmf** [comment]
You're right. I'll fix it. Let me know if you find anything else so I can bundle it into a bugfix release.
