### ISSUE TITLE
[libsoup] configure: error: XML::Parser perl module is required for intltool 

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#1734]
http://vmpkg.haiku-os.org/master/x86_64/buildruns/374/builds/2020.log

It looks like `xml_parser-2.44-3-x86_64.hpkg` is built against perl 5.18 and needs to be rebuilt.

When looking into it however I found something odd regarding our port of perl.
I have manually built xml_parser and trying to execute `perl -e "require XML::Parser"` results in an error outside of chroot. For some reason vendor directories differ. `perl -V` inside chroot:
```
/packages/perl-5.26.1-1/.self/non-packaged/lib/perl5/site_perl/5.26/x86_64-haiku
/packages/perl-5.26.1-1/.self/non-packaged/lib/perl5/site_perl/5.26
/packages/perl-5.26.1-1/.self/lib/perl5/vendor_perl/5.26/x86_64-haiku
/packages/perl-5.26.1-1/.self/lib/perl5/vendor_perl/5.26
/packages/perl-5.26.1-1/.self/lib/perl5/5.26.1/x86_64-haiku
/packages/perl-5.26.1-1/.self/lib/perl5/5.26.1
```
Outside fo chroot:

```
/boot/home/config/lib/perl5/5.26.1/x86_64-haiku
/boot/home/config/lib/perl5/5.26.1
/boot/home/config/non-packaged/lib/perl5/site_perl/5.26.1/x86_64-haiku
/boot/home/config/non-packaged/lib/perl5/site_perl/5.26.1
/boot/home/config/lib/perl5/vendor_perl/5.26.1/x86_64-haiku
/boot/home/config/lib/perl5/vendor_perl/5.26.1
/boot/home/config/lib/perl5/vendor_perl
/boot/system/lib/perl5/5.26.1/x86_64-haiku
/boot/system/lib/perl5/5.26.1
/boot/system/non-packaged/lib/perl5/site_perl/5.26.1/x86_64-haiku
/boot/system/non-packaged/lib/perl5/site_perl/5.26.1
/boot/system/lib/perl5/vendor_perl/5.26.1/x86_64-haiku
/boot/system/lib/perl5/vendor_perl/5.26.1
/boot/system/lib/perl5/vendor_perl
```

See patch: https://github.com/haikuports/haikuports/blob/master/dev-lang/perl/patches/perl-5.26.1.patchset#L364

**Comment by korli** [comment]
xml_parser needs to be rebuilt with perl 5.26 installed on the system (as a user package is not enough).

about your question related to the vendor directories, haikuporter defines a system variable so that perl/python/etc modules are installed in the vendor directories:
https://github.com/haikuports/haikuporter/blob/master/HaikuPorter/Port.py#L1520

**Comment by diversys** [comment]
I winder why in the first case minor version is not present:
`/packages/perl-5.26.1-1/.self/lib/perl5/vendor_perl/5.26`
while it does in the second one:
`/boot/system/lib/perl5/vendor_perl/5.26.1`

**Comment by diversys** [comment]
I've bumped xml_parser but it still was built against an older perl, even though I don't see it in the list of packages available in chroot...

**Comment by korli** [comment]
I know I changed the portVersion to perl short version in https://github.com/haikuports/haikuports/commit/39e5c6736760a81a930daefc01688caf75c8fddf
This is weird indeed.

**Comment by diversys** [comment]
```
hp libsoup --why xml_parser
Checking if any package-infos need to be updated ...
Looking for stale dependency-infos ...
Warning: port xml_parser-2.44 doesn't seem to be required by libsoup-2.60.1
```

**Comment by Begasus** [comment]
Is still valid?

**Comment by diversys** [comment]
Nope :)
