### ISSUE TITLE
[binutils] 2.28.1 assertion fail

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#1750]
Some ports like Qt4, gcc, llvm and quite a few others fail with:
`/boot/system/develop/tools/x86/bin/../lib/gcc/i586-pc-haiku/5.4.0/../../../../i586-pc-haiku/bin/ld: BFD (GNU Binutils) 2.28.1 assertion fail /sources/binutils-2.28.1/bfd/elf32-i386.c:5636`

**Comment by waddlesplash** [comment]
Here's an example, thanks to @bbjimmy: http://coquillemartialarts.com/jim/libqt4-4.8.7.recipe.log

**Comment by waddlesplash** [comment]
Same assert happens with binutils 2.29.

**Comment by Lan72** [comment]
There is a solution https://github.com/haikuports/haikuports/issues/1794
Thanks to **diversys** personally!

**Comment by waddlesplash** [comment]
well, I'm the one that did the fix 😛

**Comment by Lan72** [comment]
**waddlesplash**
Then many thanks to you, as well as all those who helped solve this problem!
This is the foundation for the stable operation of web browsers based on Qt5, and many other applications on x86_gcc2.

**Comment by waddlesplash** [comment]
I guess this isn't an issue anymore.
