### ISSUE TITLE
Write recipe for CuteMarkEd

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#1761]
Link: https://cloose.github.io/CuteMarkEd/

![63641b6db71c44358d6cfce0a5804b57](https://user-images.githubusercontent.com/5569059/32172489-17e41094-bd7c-11e7-93a2-1b914b52dad5.png)

**Comment by korli** [comment]
category: app-text/cutemarked

**Comment by fbrosson** [comment]
Done in #2057
