### ISSUE TITLE
virtualbox-guest-additions: x86_64 build don't work

### ISSUE THREAD

**Issue by phoudoin** [haikuports/haikuports#1768]
virtualbox_guest_additions-5.1.26-1-x86_64.hpkg freshly build from HaikuPorts on a hrev51497 x86_64 haiku, running under VirtualBox 5.1.30.
Tested on same machine.

The drivers/dev/misc/vboxdev (and file_systems/vboxfs module too) failed to load with a `Bad Data` error. Due to the common kernel module *vboxguest* failure to load. 
No log error on why.

The PCI vboxguest fake-device is present.

**Comment by diversys** [comment]
@scgtrp any idea what might be wrong? Maybe something is wrong with compile flags? See https://github.com/haikuports/haikuports/commit/befb49f5683a3c1c5dc31eebe2b75f6ae47225df#diff-ebc27920c07cdec9acf0f26f637eb7d45

**Comment by Begasus** [comment]
Should be fixed? in https://github.com/haikuports/haikuports/pull/6152 
Please re-open when not.
