### ISSUE TITLE
jpeg: wrong name for debuginfo package

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#1769]
The buildbot repo currently has a jpeg_x86_x86_debuginfo-9b-5 package. This does not look correct and does not match the "provides" entry in the packet (which is correct with a single _x86). I don't know if this is a problem in haikuporter or in the recipe.

**Comment by KapiX** [comment]
Fixed in 2cf106cd1dd9980852e6ee48e4eca3ced813a962.
