### ISSUE TITLE
xpdfreader fails at packaging stage

### ISSUE THREAD

**Issue by khallebal** [haikuports/haikuports#1774]
First the build failed stating that the build is broken on x86, so i changed the archs section 
from 
ARCHITECTURES="x86_gcc2 x86 x86_64"
to
ARCHITECTURES="x86 !x86_gcc2"
SECONDARY_ARCHITECTURES="x86"
That fixed it, but it failed with following error

-- Installing: /packages/xpdfreader_x86-4.00-1/.self/bin/xpdf
-- Set runtime path of "/packages/xpdfreader_x86-4.00-1/.self/bin/xpdf" to ""
-- Installing: /packages/xpdfreader_x86-4.00-1/.self/man/man1/xpdf.1
mv: cannot stat '/packages/xpdfreader_x86-4.00-1/.self/binDir/xpdf': No such file or directory
[Errno -2147459069] No such file or directory: '/boot/home/haikuports/app-text/xpdfreader/work-x86-4.00'
Error: Build has failed - stopping.

**Comment by Begasus** [comment]
This should fix it ... https://github.com/haikuports/haikuports/pull/1778
