### ISSUE TITLE
Rust can't compile a hello world in x86_64 and debug mode

### ISSUE THREAD

**Issue by aarroyoc** [haikuports/haikuports#1791]
Just installed Rust with: `pkgman install rust` on a x86_64 nightly.

Then I created a new Cargo project:
```
cargo new hola_mundo --bin
cd hola_mundo
cargo run
```
The project doesn't compile (sorry for the image, can't copy/paste):
![rusthaiku](https://user-images.githubusercontent.com/3681517/32754388-c0a5bf70-c8d0-11e7-8d12-b05981c0c8b7.PNG)

However, compiling in release mode works:
![haikurust](https://user-images.githubusercontent.com/3681517/32754414-e038e07e-c8d0-11e7-8627-cb551b9d7005.PNG)

**Comment by korli** [comment]
@jessicah any idea

**Comment by zzzzzzzzz** [comment]
Is it still valid with most recent rust 1.35 ?   Are both 'rust_bin' and 'rust' affected? 

I've tried beta2 hybrid with locally built rust_bin 1.35 and there is no such behaviour, however, cargo/rustc works when 'setarch x86' is done - otherwise it cannot find a linker.

**Comment by korli** [comment]
@nielx could you please check this issue ?

**Comment by nielx** [comment]
Unless there is anything specific in the Hello Mundo test, this should definitely work. I always try out the latest build on building cargo (in debugging mode)

**Comment by waddlesplash** [comment]
Well, the issue is from 2017, so let's presume it's fixed if it works for you then.
