### ISSUE TITLE
QtWebKit 5.212.0~alpha2 on x86_gcc2

### ISSUE THREAD

**Issue by Lan72** [haikuports/haikuports#1794]
After numerous attempts to build QtWebKit 5.212.0~alpha2 on x86_gcc2 I didn't manage to make it. The error is the same, described earlier.

At first gcc 5.4 falls by 6% of the process, [see a screenshot](https://user-images.githubusercontent.com/26386474/32982098-a1d6340c-cc87-11e7-914c-1ccbc5d7b740.jpg), and then building stops at 24% with a standard error: 
[Error_Qt5WebKit.txt](https://github.com/haikuports/haikuports/files/1484723/Error_Qt5WebKit.txt)

In vain you have closed [the previous topic](https://github.com/haikuports/haikuports/issues/1515), because the problem on x86_gcc2 is not solved.

**Comment by diversys** [comment]
Click Save report button in that crash dialog and attach debug report here.

**Comment by Lan72** [comment]
Here is the debug report: 
[ld-2432-debug-18-11-2017-16-58-58.report.txt](https://github.com/haikuports/haikuports/files/1484827/ld-2432-debug-18-11-2017-16-58-58.report.txt)

P.S.: If don't press Stop button in crash dialog window at 6% of the process, the building reaches 40% and stops at step "Scanning dependencies of target WebCore".

**Comment by khallebal** [comment]
For the build tools crash, this could be triggered by what i believe to be a bfs issue, it happens when you have alot of  extracted archives on the filesystem (when you build alot of packages in haikuports or manually and don't clean up), one workaround i find to fix it for me is clean up all the extracted archives you have, and then run "checkfs /boot" and try to rebuild your pkg, this works for me everytime it's worth a shot.

**Comment by diversys** [comment]
It looks like you're running haikuporter with -j2 argument making it use 2 build jobs. That's why the build only stops after the second error. Qt build uses quite a lot of memory which doubles with -j2. So I would try to build with -j1 again.

**Comment by Lan72** [comment]
**khallebal**
I always clean the system from the unpacked files and extracted archives after working with haikuports.

**diversys**
Interesting idea. Now I'll try this -j1 argument. I still have always used the -j4 argument, and there were no such problems.

**Comment by Lan72** [comment]
Unfortunately, nothing happened.
With -j1 argument, the process reached 82%, then the gcc 5.4 again fell:
[ld-41042-debug-20-11-2017-01-16-37.report.txt](https://github.com/haikuports/haikuports/files/1488106/ld-41042-debug-20-11-2017-01-16-37.report.txt)
[Error_Qt5WebKit2.txt](https://github.com/haikuports/haikuports/files/1488131/Error_Qt5WebKit2.txt)

After restarting the process and a new fall, I did not press the Stop button in crash dialog window. Now the process has reached 98% and stopped at the stage of linking of libQt5WebKit.so library:
[Error_Qt5WebKit3.txt](https://github.com/haikuports/haikuports/files/1488130/Error_Qt5WebKit3.txt)

**Comment by diversys** [comment]
Likely due to a bug in binutils package. See #1750.

**Comment by diversys** [comment]
Try with this version http://eu.hpkg.haiku-os.org/haikuports/master/build-packages/binutils_x86-2.26.1_2016_07_22-5-x86_gcc2.hpkg

**Comment by Lan72** [comment]
**diversys**
Thank you very much!!
Finally it was possible to create QtWebKit 5.212.0~alpha2 on x86_gcc2!

I shared the finished builds on Google Drive for public access:

**qtwebkit_x86-5.212.0~alpha2-7-x86_gcc2.hpkg**
https://drive.google.com/open?id=1RfdYi8xNNi8BKOWMQTjqCyuwCrW5Sw0i

**qtwebkit_x86_devel-5.212.0~alpha2-7-x86_gcc2.hpkg**
https://drive.google.com/open?id=18GkKVxpOfdbXgzJnoOfdj-IAU9Fe97v7

And here are a few new programs that I recently built.
Perhaps they will help someone:

**otter_browser_x86-0.9.92v2-1-x86_gcc2.hpkg**
https://drive.google.com/open?id=1DZQ1R3TAxkl7e_zMhjAeeU9BIAv-C0iG

**qmplay2_x86-17.10.24-1-x86_gcc2.hpkg**
https://drive.google.com/open?id=1rR0i3NYTKFdfsYtCuMJ1ln5nYvBbSWgh

**qmmp_x86-1.1.12-1-x86_gcc2.hpkg**
https://drive.google.com/open?id=1gepuzGchkb1NHSbNHCMWjuK3VyJmy-tL

All dependencies are available on 
http://eu.hpkg.haiku-os.org/haikuports/master/repository/x86_gcc2/current/packages/
If possible, you can put these builds there.

Once again, many thanks for your helpful help!
