### ISSUE TITLE
enable USE_ICONV_MAPPING in unzip

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#1802]
Apparently it allows unzipping files with non-UTF8-compatible encodings: https://twitter.com/marcan42/status/933961046657720321

**Comment by waddlesplash** [comment]
PR to Gentoo Portage, for reference: https://github.com/gentoo/gentoo/pull/6276

**Comment by pulkomandy** [comment]
It should be enabled already. Or did my work get dropped in a "revision bump" again?

**Comment by waddlesplash** [comment]
Ah, indeed.
