### ISSUE TITLE
qBittorrent and libtorrent-rasterbar fails to build on x86_gcc2

### ISSUE THREAD

**Issue by Lan72** [haikuports/haikuports#1807]
qBittorrent 4.0.0 and libtorrent-rasterbar 1.1.5, when building on the x86_gcc2, give out similar errors associated with the boost headers in _/boot/system/develop/headers/x86/boost/_.
[qBittorrent_error.txt](https://github.com/haikuports/haikuports/files/1504360/qBittorrent_error.txt)
[libtorrent-rasterbar_error.txt](https://github.com/haikuports/haikuports/files/1504361/libtorrent-rasterbar_error.txt)

The same errors occur when trying to build earlier versions of qBittorrent and libtorrent-rasterbar with old recipes, for example, 3.3.12 and 1.0.9 respectively, which I built in the summer. Then there were no such errors.

**Comment by diversys** [comment]
According to https://github.com/qbittorrent/qBittorrent/issues/4112
We have to either add `DEFINES += BOOST_NO_CXX11_REF_QUALIFIERS` to src/src.pro or bump out boost recipe to 1.58.

**Comment by Lan72** [comment]
At a certain stage, it helped, but when linking qbittorrent, a new error occurred:

> linking qbittorrent
filterparserthread.o: In function `(anonymous namespace)::parseIPAddress(char const*, boost::asio::ip::address&) [clone .constprop.103]':
/sources/qBittorrent-release-4.0.0/src/base/bittorrent/private/filterparserthread.cpp:97: undefined reference to `boost::asio::ip::address_v4::address_v4(std::array<unsigned char, 4ul> const&)'
collect2: error: ld returned 1 exit status
Makefile:1002: recipe for target 'qbittorrent' failed
make[1]: *** [qbittorrent] Error 1
make[1]: Leaving directory '/sources/qBittorrent-release-4.0.0/src'
Makefile:44: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2
[Errno -2147459069] No such file or directory: '/boot/home/haikuports/net-p2p/qbittorrent/work-x86-4.0.0'
Error: Build has failed - stopping.
[qBittorrent_error2.txt](https://github.com/haikuports/haikuports/files/1507011/qBittorrent_error2.txt)

**Comment by diversys** [comment]
https://github.com/qbittorrent/qBittorrent/issues/6721 looks related.

**Comment by diversys** [comment]
What's odd is why it build fine on x86_64...

**Comment by Lan72** [comment]
**diversys**
Many thanks, but I did quite differently. I built the boost 1.65.1 on x86_gcc2, and under his libraries I successfully built the latest version of qBittorrent and libtorrent-rasterbar. By the way, qBittorrent already has a new version 4.0.1, it was I who built it.

**Comment by diversys** [comment]
Fixed in bd1d16c.
