### ISSUE TITLE
Repos are not in consistent state

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#1809]
At least on x86_gcc2 with new eu.hpkg repo pkgman is unable to install QupZilla_x86 as it was built against an older Qt. Since we aim for users to never see errors like that we have to make sure there are no packages with missing reqs. Can haikuporter find such broken packages and drop them?

**Comment by waddlesplash** [comment]
Qt is binary compatible within major versions. Does the recipe not declare this correctly?
