### ISSUE TITLE
ninja fails with "fatal: posix_spawn_file_actions_adddup2: Bad file descriptor"

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#1810]
https://kitchen.haiku-os.org/master/x86_64/logviewer.html?buildruns/616/builds/9027.log

Unclear if this is a Ninja bug, a CMake bug, or a Haiku bug. Cc @korli

**Comment by waddlesplash** [comment]
Oh, here's another one: https://kitchen.haiku-os.org/master/x86_64/logviewer.html?buildruns/615/builds/9009.log

**Comment by korli** [comment]
please update to hrev51516 or newer.

**Comment by waddlesplash** [comment]
Ah. CC @mmlr. I guess we can't upgrade just yet due to TCP?

**Comment by mmlr** [comment]
Yes, that is the hold off reason. Usually we could just lift the chroot haiku, but due to the wait4 syscall interface change, this does not work without the host getting upgraded as well, which pulls in the TCP changes.

**Comment by waddlesplash** [comment]
The VMs have been upgraded now.
