### ISSUE TITLE
Replace man with man-db

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#1817]
The current "man" command used is an old version, the upstream website is dead and it lives only on our mirrors. We should consider switching to a replacement.

https://savannah.nongnu.org/projects/man-db looks good.

However it needs a berkeley db instead of plain files, so maybe that wouldn't work for us (the db needs to be built somehow).

**Comment by waddlesplash** [comment]
Is there some alternative man command that does not use berkdb that we could use? (Do we even need to upgrade?)

**Comment by alaviss** [comment]
How about FreeBSD's [man](https://github.com/freebsd/freebsd/tree/master/usr.bin/man)?

**Comment by waddlesplash** [comment]
FreeBSD's man appears to be ... a shell script. 😆 

OpenBSD mandoc looks nice.

**Comment by alaviss** [comment]
mandoc partly relies on an database as well (see #1990)

I guess I will try to port FreeBSD's man

**Comment by korli** [comment]
we switched to mandoc 15fa2d6aa72ab2299bd17c4745bc0a4586837520

**Comment by bugcrazy** [comment]
man has been replaced by man-doc, is it still necessary to have this issue open?

**Comment by Begasus** [comment]
Probably can be closed as there isn't any need for it anymore? (looks @pulkomandy ) :)

**Comment by pulkomandy** [comment]
You don't really need me just to click the close button, right? As korli said in 2019, we have switched to mandoc. This is exactly what this ticket was about. No need for 4 persons to check that?

**Comment by Begasus** [comment]
Could have been closed in 2019 then, if not maybe there was a reason (that I don't know) it wasn't done back then?

**Comment by bugcrazy** [comment]
> Could have been closed in 2019 then, if not maybe there was a reason (that I don't know) it wasn't done back then?

Maybe they expected man-db port!?

It would be a good idea to check old tickets and also create labels to classify recurring tickets as LLVM, so it's easy to find tickets with the same or similar problem!

**Comment by Begasus** [comment]
I've done a run over on all the tickets not that long ago, closing some that were invalid/fixed, and from time to time I still check up on my own created issues. There are still some left that are candidates to closure as they are not required changed over the years.
