### ISSUE TITLE
Write a recipe for wordgrinder.

### ISSUE THREAD

**Issue by return** [haikuports/haikuports#1844]
A terminal-based word processor which gets the hell out of your way and lets you get some work done.
Should compile on Haiku without any changes.

site: http://cowlark.com/wordgrinder/
source: https://github.com/davidgiven/wordgrinder

**Comment by fbrosson** [comment]
An initial (broken) recipe was just added with #1909. It needs to be investigated.

**Comment by fbrosson** [comment]
Recipe fixed with #1925.
