### ISSUE TITLE
[aqemu] add platform specific code to get memory size

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#1850]
@CodeforEvolution, maybe you're interested as you just did the same in https://github.com/haikuports/haikuports/pull/1849.

Memory detection is disabled for now in aqemu and throws an error on app launch.
See https://github.com/haikuports/haikuports/commit/4f83f6d60037f7ea285927002da76768b2a2d87f#diff-43557af219ef21da986f8199f53ca022R48

**Comment by CodeforEvolution** [comment]
Well, I'll take a look at it when I have the chance. ;)
