### ISSUE TITLE
QupZilla menu bar items use wrong colour

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#1853]
Version: qupzilla_x86-1.8.9-6-x86_gcc2.hpkg

The main menu items (_File, Edit, View_...) seem to not use `B_MENU_SELECTED_ITEM_TEXT_COLOR`. I have that one set to white, but the menu text stays black.
The menu items under these 'main' menu items (_File | New Tab, File | New Window_...) show the correct colour.

**Comment by diversys** [comment]
Is this only with QupZilla or other Qt5 based apps as well?

**Comment by humdingerb** [comment]
I think I only have Otter-Browser as another Qt5 app. It shows the same behaviour.

**Comment by diversys** [comment]
Then it is probably an issue with qthaikustyle: https://github.com/threedeyes/qthaikuplugins/blob/master/styles/qthaikustyle/haiku/qhaikustyle.cpp#L1898.

**Comment by khallebal** [comment]
The progress bar also uses the wrong color for both qupzilla & otter_browser

**Comment by diversys** [comment]
Yes, progress bar as well as some more widgets are not styled yet. See https://github.com/threedeyes/qthaikuplugins/issues/1

**Comment by diversys** [comment]
Closing. See "Menu colour shouldn't use panel colour" from threedeyes/qthaikuplugins#1.
