### ISSUE TITLE
Notepadqq executable is not recognized as executable

### ISSUE THREAD

**Issue by Giova84** [haikuports/haikuports#1861]
Today I attempted to build Notepadqq on Haiku gcc2_h and was successful, except for the fact that when I launch (double click) the executable, i always get the following error:

![notepadqq_error](https://user-images.githubusercontent.com/3594780/33718982-975bc2bc-db5f-11e7-8ddb-4e592ece4603.png)

Obviously is set as executable, but no luck: I am totally unable to launch it. Why? I followed the recipe from Haikuports and I also applied the patch from here https://github.com/haikuports/haikuports/tree/master/app-editors/notepadqq

Can someone else try to build it on Haiku gcc2_h? It requires QT5 dev and mesa dev packages.

**Comment by diversys** [comment]
I just did that on gcc2h and Notepadqq is working just fine here.

**Comment by diversys** [comment]
![image](https://user-images.githubusercontent.com/1316513/33766172-61eb191a-dc2d-11e7-9161-4f6317899a6b.png)

**Comment by Giova84** [comment]
Sure, I trust you :-)
Maybe there is some trouble on my system, who knows.
I see that you commited `Notepadqq: enable secondary arch`: so can I expect to see soon Notepadqq on the repo? Or, in the meantime can you share the package? I'd like to test it, to see if works for me (maybe I miss something during the builiding of the package.

**Comment by diversys** [comment]
Buildmaster is having difficulties with building Qt recipes. See here http://vmpkg.haiku-os.org/master/x86_gcc2/logviewer.html?buildruns/525/builds/26647.log

Could you check you clean notepadqq work-dir, check your volume with checkfs and build it again?

**Comment by Giova84** [comment]
Well, the fact is that I also built Notepadqq on Haiku X86_64, and there works fine (I mean that I am able to run and use it); on Haiku X86_GCC2H, despite the fact that I didn't encounter FS issues - `checkfs -c /boot` doesn't find any issue - Notepadqq is unable to work. I was looking since time for a notepad like this, since I am a Notepad++ addict for work :-)

Since you were able to build Notepadqq on GCC2_h, in the meantime can you set the recipe as valid for GCC2_H? (I mean: turn `!x86_gcc2 ` to `x86_gcc2`).
We'll hope for Buildmaster's fix, and if for you is ok, try to upload the package somewhere, so I can be sure that my system is ok, and in the case I can improve or set as invalid this ticket :-)

**Comment by Giova84** [comment]
Well, I built it again, and now properly works (TBH I have no idea why previously I got the error about "not executable"):
![haiku_desktop_dec2017](https://user-images.githubusercontent.com/3594780/33807587-5ec30330-ddd9-11e7-9666-45762fd0cad3.png)

Now we'll wait to see this package in the repo :-)

**Comment by diversys** [comment]
Package is now in the repo too. Closing.
