### ISSUE TITLE
Sanity: 2 bugs found by Clang Static Analysis

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#1873]
Clang HTML report in attached zip archive.
[scan-build-Sanity.zip](https://github.com/haikuports/haikuports/files/1545156/scan-build-Sanity.zip)

**Comment by alaviss** [comment]
Shouldn't this be reported to [upstream](https://github.com/diversys/sanity)?

**Comment by Vidrep** [comment]
Why? Sanity is a native Haiku (originally BeOS) front end for SANE.

**Comment by alaviss** [comment]
Fixing bugs is the job of the Sanity developers. Here at haikuports we only package and make sure the program works, not fixing application bugs, which is the job of the upstream developers

On December 10, 2017 12:25:08 PM GMT+07:00, Vidrep <notifications@github.com> wrote:
>Why? Sanity is a native Haiku (originally BeOS) front end for SANE.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/haikuports/haikuports/issues/1873#issuecomment-350526166

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by diversys** [comment]
Reported upstream.
