### ISSUE TITLE
#include_next is broken for x86_64

### ISSUE THREAD

**Issue by alaviss** [haikuports/haikuports#1882]
Test case:

    echo '#include <bsd/string.h>' | gcc -D_BSD_SOURCE -x c -

Results:

    /boot/system/develop/headers/bsd/string.h:9:25: error: no include path in which to search for string.h

Expected:

    /boot/system/develop/lib/start_dyn.o: In function `_start':
    start_dyn.c:(.text+0x4d): undefined reference to `main'
    collect2: error: ld returned 1 exit status

Walkaround:

    echo '#include <bsd/string.h>' | gcc -D_BSD_SOURCE -include string.h -x c -

This issue is a blocker for any ports that use `libbsd`

**UPDATE**: this issue is also present in `clang`

**Comment by korli** [comment]
Just use #include <string.h>.

**Comment by pulkomandy** [comment]
You are not supposed to #include libbsd headers this way. You just include the header the normal way (#include <string.h>) and let include_next do its work. You need to define _BSD_SOURCE to make the contents of the file visible and add the "bsd" dir to the include search path (but it is already there by default).

**Comment by alaviss** [comment]
Thanks
