### ISSUE TITLE
advancemame does not provide location to put user supplied roms

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#1884]
Currently advancemame can play roms in the `/system/data/advance/rom` directory.  But since this is read-only the user is not able to add their own.
The advancemame recipe does not provide a location to allow users to add their own roms to play.  The recipe should be updated to add this support.  Also it is putting it's data files in `~/.advance`, it would be nice to get this moved to `~/config/settings/advancemame`

**Comment by Giova84** [comment]
I totally agree with you, about the fact of move it's data files to `~/config/settings/advancemame`; however, currently, is possible to place roms in `~/.advance/rom`  (which is R/W): then, obviously is possible to start roms by` ->advmame romName` in a Terminal window or by using a bash script.

**Comment by tuankiet65** [comment]
> The advancemame recipe does not provide a location to allow users to add their own roms to play. The recipe should be updated to add this support

You mean that the recipe should have a variable for changing the ROM path to that variable?

**Comment by scottmc** [comment]
It currently provides a directory, but that directory is write-protected since it's part of the read-only file system.  It needs to provide a directory in a wrtie-able location, perhaps this should be home/advancemame/rom

**Comment by tuankiet65** [comment]
I'll look into this then

**Comment by tuankiet65** [comment]
The code for determining home directory (aka data files) is here https://github.com/amadvance/advancemame/blob/59ec93126804e6baeb4aa5087dbce7dd5ec1d5b8/advance/linux/file.c#L87. However the file is meant for Linux platform, so should we just directly patch in this file or not?

**Comment by scottmc** [comment]
Yes, that looks like you have located where you will need to patch.  See some of the other patches listed on the task to get an idea of how to do this one.  You'll need to insert ifdef __HAIKU__ around your changes so that it won't break the code on non Haiku systems.

**Comment by tuankiet65** [comment]
You mean __HAIKU__?

**Comment by tuankiet65** [comment]
Oof looks like when you ``__HAIKU__`` it shows up as __HAIKU__ thanks to Markdown formatting.

**Comment by fbrosson** [comment]
The trick is to use a backslash in front of each underscores and each hash signs too: \#ifdef \_\_HAIKU\_\_

(Of course this is only required if you don't want to use a code bloc. Because when you use code blocs you disable MD inside it.)
