### ISSUE TITLE
RTMPDump build fails on x86_gcc2

### ISSUE THREAD

**Issue by Lan72** [haikuports/haikuports#1891]
Attempts to build RTMPDump fail.  
I tried to install-remove some versions of OpenSSL-x86_gcc2, but this didn't solve the problem. In all cases, the errors are the same:
[Errors_in_building_RTMPDump.txt](https://github.com/haikuports/haikuports/files/1556484/Errors_in_building_RTMPDump.txt)

**Comment by mmlr** [comment]
The log shows that you have openssl11_x86 and its devel package active and picked up in your haikuports packages directory. I don't think it has been ported to 1.1. Have you tried removing it and building against openssl-1.0.2 instead? It should be compatible with the 1.0 series.

There is however apparently a problem with the secondary arch build/packaging which is the reason for it being absent from the buildmaster repos, see:
https://kitchen.haiku-os.org/master/x86_gcc2/logviewer.html?builds/25917.log

**Comment by Lan72** [comment]
I removed openssl11_x86 and rebuilt and reinstalled openssl_x86-1.0.2-x86_gcc2 and openssl_1.0.2-x86_gcc2. Nothing helped. Tried to build RTMPDump in both variants. The result is zero. Unfortunately.

True, errors are of a somewhat different kind than before:
[Error_rtmpdump_x86-2.4_git.txt](https://github.com/haikuports/haikuports/files/1557365/Error_rtmpdump_x86-2.4_git.txt)
[Error_rtmpdump-2.4_git.txt](https://github.com/haikuports/haikuports/files/1557366/Error_rtmpdump-2.4_git.txt)

**Comment by diversys** [comment]
Collecting files to be packaged ...
...
```
cp librtmp.1.so /packages/rtmpdump_x86-2.4_git-2/.self/lib/x86
cp: cannot create regular file '/packages/rtmpdump_x86-2.4_git-2/.self/lib/x86': No such file or directory
```

This means that it is already in INSTALL() stage.

**Comment by Lan72** [comment]
Yes, all the necessary components are created, but do not assemble into packages.
I collected these libraries, commands and links to them, and manually built the packages, including develop.

I'm going to build ICQ desktop client by recipe, and the RTMPDump is an essential component for this.

P.S.: The same situation was when I was building [SQLiteBrowser 3.10](https://github.com/haikuports/haikuports/tree/master/dev-db/sqlitebrowser). Then, too, all the components were created and even collected, but not built into the package.

**Comment by Begasus** [comment]
Closing as it's fixed in the meantime.
