### ISSUE TITLE
[VirtualBox guest additions] build is broken on gcc2

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#1897]
Since we want users to be able to try Haiku in VirtualBox with working clipboard it would be nice to fix it.

```
kBuild: Compiling RuntimeGuestR3 - /sources/VirtualBox-4.3.40/src/VBox/Runtime/r3/posix/rtmemlocked-posix.cpp
/sources/VirtualBox-4.3.40/src/VBox/Runtime/r3/posix/rtmemlocked-posix.cpp: In function `int RTMemLockedAllocExTag(long unsigned int, const char *, void **)':
/sources/VirtualBox-4.3.40/src/VBox/Runtime/r3/posix/rtmemlocked-posix.cpp:87: implicit declaration of function `int mlock(...)'
/sources/VirtualBox-4.3.40/src/VBox/Runtime/r3/posix/rtmemlocked-posix.cpp: In function `void RTMemLockedFree(void *)':
/sources/VirtualBox-4.3.40/src/VBox/Runtime/r3/posix/rtmemlocked-posix.cpp:154: implicit declaration of function `int munlock(...)'
kmk: *** [/sources/VirtualBox-4.3.40/out/haiku.x86/strict/obj/RuntimeGuestR3/r3/posix/rtmemlocked-posix.o] Error 1
The failing command:
```

http://vmpkg.haiku-os.org/master/x86_gcc2/logviewer.html?buildruns/558/builds/26695.log

**Comment by CodeforEvolution** [comment]
It seems we are missing the posix functions, "mlock()" and "munlock", someone will have to implement these in libroot for the build to be fixed. I will open a ticket, as this is out of the context of haikuports.

**Comment by diversys** [comment]
Interesting, it used to build before. Perhaps earlier version of vbox additions didn't use it?

**Comment by diversys** [comment]
Downgraded vbox additions to 4.3.12 in https://github.com/haikuports/haikuports/commit/de577173ce69c5e1e3105ff16c11ebf76f90045f

While it compiles just fine now it doesn't work (VBoxTray crashes).
