### ISSUE TITLE
Qbittorrent no longer works after libtorrent-rasterbar update

### ISSUE THREAD

**Issue by Giova84** [haikuports/haikuports#1918]
After upgrading Haiku to hrev51692_gcc2h (which also updated libtorrent-rasterbar to libtorrent_rasterbar_x86-1.1.5-4-x86_gcc2.hpkg), QBittorrent (qbittorrent_x86-3.2.3-3-x86_gcc2.hpkg) no longer works:

![qbittorrent-error](https://user-images.githubusercontent.com/3594780/34155744-d6fa4d94-e4ba-11e7-96dd-1a8fa3901ded.png)

I guess that must be rebuilt?

**Comment by diversys** [comment]
`libtorrent_rasterbar_x86-1.1.5-4-x86_gcc2.hpkg` contains `libtorrent-rasterbar.so.9`. So you either need to downgrade libtorrent_rasterbar package or build newer qBittorrent, which currently fails http://vmpkg.haiku-os.org/master/x86_gcc2/logviewer.html?buildruns/584/builds/26763.log

**Comment by diversys** [comment]
Fixed in https://github.com/haikuports/haikuports/commit/bd1d16c6ade79370b351bf0603e20e707a3b933d.

**Comment by Lan72** [comment]
> or build newer qBittorrent, which currently fails

Everything is perfectly built, I today built a new version of qBittorrent.

The log shows that boost_x86_devel-1.57.0 and all its components are still installed in the system. Remove boost_x86_devel-1.57.0 and all its components from the system, and install boost_x86_devel-1.65.1. It is already available in the new repository.

I wrote about [this problem](https://github.com/haikuports/haikuports/issues/1807#issuecomment-347310225).
