### ISSUE TITLE
 Haiku hrev51692_gcc2h: cannot install qpdfview_x86

### ISSUE THREAD

**Issue by Giova84** [haikuports/haikuports#1919]
As shown in the screenshot:
(I attempt to install it from HaikuDepot)
![qpdf_install_error](https://user-images.githubusercontent.com/3594780/34156282-ce172538-e4bc-11e7-92ec-3e1eb17c2cb0.png)

**Comment by diversys** [comment]
Should be fixed in https://github.com/haikuports/haikuports/commit/3a9c9606283a474ef5c45282ed7a0b9a1c6362c.
