### ISSUE TITLE
man is broken? doesn't show man pages ... 

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#1963]
If I try to load a manpage for a package I get:
> man tidy.1
> No manual entry for tidy. (same for other entries)

After editing /system/settings/man.conf and remove some of the instances it works again
`TROFF /packages/man-1.6g-/cmd~groff/bin/groff -Tps -mandoc`
Remove the 
`/packages/man-1.6g-/cmd~xxxxxx     part`

After that this is what is left:
`TROFF /bin/groff -Tps -mandoc`

Doing this for the remaining lines makes "man" work again ...

**Comment by extrowerk** [comment]
This file gets generated the first time the user runs man, but never gets update. The problem is, it contains hardcoded PM paths to the binaries, and after a man update they doesn't exist anymore. 
Options:
- No PM paths at all (works ok)
- A postinstall script like in openssl

**Comment by fbrosson** [comment]
There are 2 possible fixes:
* `rm /system/settings/man.conf` (and repeat that after every upgrade of the `man` package, if the file got recreated.)
* or `rm /system/settings/man.conf` only once, and install the `mandoc` package which got merged in #1990.

**Comment by Begasus** [comment]
Closing as this is covered with mandoc
