### ISSUE TITLE
php fails to build on x86_64

### ISSUE THREAD

**Issue by eddrda** [haikuports/haikuports#1975]
```
/boot/home/haikuports/dev-lang/php/work-5.6.4/port.recipe: line 78: dos2unix: command not found
HEAD is now at fc4c03e import
Command '['bash', '-c', u'. /boot/home/haikuports/dev-lang/php/work-5.6.4/wrapper-script']' returned non-zero exit status 127
```

**Comment by Begasus** [comment]
dos2unix is available for x86_64, --get-dependencies should be able to fetch it?

**Comment by mmlr** [comment]
It should be investigated why the command isn't available, as it is declared as required in BUILD_PREREQUIRES.

**Comment by Begasus** [comment]
Probably missed adding --get-dependencies in the call?

**Comment by waddlesplash** [comment]
@mmlr: PATCH() is run outside chroot, and so even if something is declared in BUILD_PREREQUIRES, it likely won't be available in PATCH.
