### ISSUE TITLE
barrage fails to build on x86_64

### ISSUE THREAD

**Issue by eddrda** [haikuports/haikuports#1976]
```
build-requires "devel:libsdl" of package "barrage-1.0.4" could not be resolved
Error: unable to resolve required packages for build for barrage-1.0.4
Error:  dependency-infos:
Error:          /boot/home/haikuports/repository/barrage-1.0.4.DependencyInfo
Error:          /boot/home/haikuports/repository/barrage_source-1.0.4.DependencyInfo
Error:  repositories:
Error:          [u'/boot/home/haikuports/packages', '/boot/system/packages']
Error:
```

**Comment by Begasus** [comment]
add aclocal and autoconf in the prerequires and use "autoreconf -vfi" instead of "libtoolize -fi", that should do it

**Comment by Begasus** [comment]
although it's not clear why it's missing devel:libsdl, it's common available ...

**Comment by scottmc** [comment]
like just missing --get-dependencies ?

**Comment by nysnatuss** [comment]
It's just missing devel:libsdl in the local machine. I think installing the [libsdl_devel](https://depot.haiku-os.org/#!/pkg/libsdl_devel/haikuports/1/2/15/-/13/x86_64?bcguid=bc284-QJQT) will simply fix it.

**Comment by Begasus** [comment]
run "haikuporter --get-dependencies barrage"
