### ISSUE TITLE
Illegal opcode exception when running Qt-based browsers (Qupzilla, Otter) on a Via C3

### ISSUE THREAD

**Issue by ketsuban** [haikuports/haikuports#1991]
The offending instruction is a MOVSD in QGetCPUFeatures, which I understand is an SSE2 instruction (the existence of an earlier zero-operand MOVSD confused me when trying to look it up) which this processor doesn't support. I can't get a crash report from Debugger right now because it's not my machine and the owner is asleep, but I did post [a nigh-identical report when running WebPositive on the Haiku bug tracker](https://dev.haiku-os.org/ticket/13910) - same instruction, different place.

**Comment by kenmays** [comment]
@ketsuban - You'll need a SSE2-compatible processor to **properly** run those web browsers (and WebPositive).
