### ISSUE TITLE
Missing x11 libraries

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#1994]
At the moment working on some recipes to include some missing x11 libraries:
- [x] libice
- [x] libsm
- [x] ibxt
- [x] libxmu
- [x] libxrender
- [x] libxrandr
- [x] libxfont
- [x] glproto
- [x] libpciaccess
- [ ] xserver-sdl ...

**Comment by alaviss** [comment]
List please, with checkbox for easy tracking

**Comment by Begasus** [comment]
Not sure how to create the checkbox, but the striked ones are finished ...

**Comment by fbrosson** [comment]
https://guides.github.com/features/mastering-markdown/#examples > Extras

**Comment by Begasus** [comment]
Thanks :)

**Comment by Begasus** [comment]
Done so far :)

**Comment by extrowerk** [comment]
I wote to close this issue. For X server one can use http://www.jcraft.com/weirdx/ I see no point introducing X11 with all of the consequences of using an old unsupported version.

**Comment by waddlesplash** [comment]
Closing, supplanted by #2906.
