### ISSUE TITLE
htop - not show any activity about memory or process running

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#2014]
When running the htop system monitor, the app not show any activity.
I'm testing the app in x86_gcc2:

`
  Mem[                                                        0K/100K]   Tasks: 0, 0 thr; 0 running
  Swp[                                                        0K/100K]   Load average: 0.00 0.00 0.00 
                                                                         Uptime: 00:00:00

    PID USER      PRI  NI  VIRT   RES S CPU% MEM%   TIME+  Command

F1Help  F2Setup F3SearchF4FilterF5Tree  F6SortByF7Nice -F8Nice +F9Kill  F10Quit`

**Comment by diversys** [comment]
A dupe of #1655.
