### ISSUE TITLE
Qt applications doesn't respect the Deskbar when the windows are maximized

### ISSUE THREAD

**Issue by Giova84** [haikuports/haikuports#2031]
Since [this commit](http://cgit.haiku-os.org/haiku/commit/?id=b1b84675f0e854bea0a181d31b9472be4813f62d) on Haiku, at least Haiku's apps (those which I tried), when Maximized by using the zoom button on the right of the bar, doesn't covers the deskbar (eg when is placed on the top or on the bottom of Desktop).

The same doesn't occurs by using Qt applications; these apps still cover the Deskbar, when are maximized.

**Comment by diversys** [comment]
The issue should be moved here https://github.com/threedeyes/qthaikuplugins/issues

**Comment by Giova84** [comment]
Done: thank you to have point it out.
