### ISSUE TITLE
Helios CD burning apps fails with multiple warnings

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#2064]
Error: Downloading from unsafe sources is disabled in haikuports.conf!

Warning: UNSAFE SOURCES ARE BAD AND SHOULD NOT BE USED IN PRODUCTION
Warning: PLEASE MOVE TO A STATIC ARCHIVE DOWNLOAD WITH CHECKSUM ASAP!

/sources/helios-1.7.2/src/Application1.cpp: In method `void Application1::ShowRecentProjects()':
/sources/helios-1.7.2/src/Application1.cpp:4468: call of overloaded `RemoveItem(int)' is ambiguous
/boot/system/develop/headers/os/interface/Menu.h:96: candidates are: bool BMenu::RemoveItem(BMenuItem *)
/boot/system/develop/headers/os/interface/Menu.h:97:                 class BMenuItem * BMenu::RemoveItem(long int)
/boot/system/develop/headers/os/interface/Menu.h:100:                 bool BMenu::RemoveItem(BMenu *)
Makefile:108: recipe for target 'build/ColumnListView.o' failed
make: *** [build/ColumnListView.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:108: recipe for target 'build/Application1.o' failed
make: *** [build/Application1.o] Error 1
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 2
Error: Build has failed - stopping.

**Comment by pulkomandy** [comment]
Fixes in https://github.com/haikuports/haikuports/commit/38da34906020a89456d2c63236217c2d616174e9 .
