### ISSUE TITLE
Melt CD burning app crashes

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#2065]
Debug report:  
Debug information for team /boot/system/apps/Melt (46429):
CPU(s): 4x Intel Core™ i5-3570
Memory: 7.95 GiB total, 508.69 MiB used
Haiku revision: hrev51727 Jan  3 2018 12:26:17 (BePC)

Active Threads:
	thread 46437: w>Melt: Open 
	thread 46439: w>Melt: New CD-R 
	thread 46441: team 46429 debug task 
	thread 46429: Melt (main)
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x71f08e18	0x1a01daf	fread + 0x27 
			Disassembly:
				fread:
				0x01a01d88:               55  push %ebp
				0x01a01d89:             89e5  mov %esp, %ebp
				0x01a01d8b:           83ec0c  sub $0xc, %esp
				0x01a01d8e:               57  push %edi
				0x01a01d8f:               56  push %esi
				0x01a01d90:               53  push %ebx
				0x01a01d91:       e800000000  call 0x1a01d96
				0x01a01d96:               5b  pop %ebx
				0x01a01d97:     81c332f50700  add $0x7f532, %ebx
				0x01a01d9d:           8b7d0c  mov 0xc(%ebp), %edi
				0x01a01da0:         0faf7d10  imul 0x10(%ebp), %edi
				0x01a01da4:             85ff  test %edi, %edi
				0x01a01da6:             7504  jnz 0x1a01dac
				0x01a01da8:             31c0  xor %eax, %eax
				0x01a01daa:             eb4f  jmp 0x1a01dfb
				0x01a01dac:           8b4514  mov 0x14(%ebp), %eax
				0x01a01daf:         66833800  cmp $0x0, (%eax) <--

			Frame memory:
				[0x71f08e00]  xw..............   78 77 b5 01 00 00 00 00 00 00 00 00 f0 19 a0 01
				[0x71f08e10]  xw......           78 77 b5 01 00 00 00 00
		0x71f09e90	0x1b50d92	MeltApp::InitWindow(void) + 0xa6e (/sources/melt-a32d2888d6bb601e8158b1e0a373e9f52171681b/Melt.cpp:-1)
			Variables:
			this: 0x184dd408 {
				NewProjWin: 0x184ce008
				CDWin: 0x43535452
			}
			red {
				red: 200
				green: 0
				blue: 0
				alpha: 0
			}
			black {
				red: 0
				green: 0
				blue: 0
				alpha: 0
			}
			f: 0x1857eb18 {
				_flags: -72538984
				_IO_read_ptr: Cdrecord-ProDVD-ProBD-Clone 3.02a09 (i586-pc-haiku) Copyright (C) 1995-2016 Joerg Schilling
Using libscg version 'schily-0.9'.
scsibus10:
	10,0,0	1000) *
	10,1,0	1001) 'ATAPI   ' 'iHAS124   W     ' 'HL0G' Removable CD-ROM
	10,2,0	1002) *
	10,3,0	1003) *
	
				_IO_read_end: Cdrecord-ProDVD-ProBD-Clone 3.02a09 (i586-pc-haiku) Copyright (C) 1995-2016 Joerg Schilling
Using libscg version 'schily-0.9'.
scsibus10:
	10,0,0	1000) *
	10,1,0	1001) 'ATAPI   ' 'iHAS124   W     ' 'HL0G' Removable CD-ROM
	10,2,0	1002) *
	10,3,0	1003) *
	
				_IO_read_base: Cdrecord-ProDVD-ProBD-Clone 3.02a09 (i586-pc-haiku) Copyright (C) 1995-2016 Joerg Schilling
Using libscg version 'schily-0.9'.
scsibus10:
	10,0,0	1000) *
	10,1,0	1001) 'ATAPI   ' 'iHAS124   W     ' 'HL0G' Removable CD-ROM
	10,2,0	1002) *
	10,3,0	1003) *
	
				_IO_write_base: Cdrecord-ProDVD-ProBD-Clone 3.02a09 (i586-pc-haiku) Copyright (C) 1995-2016 Joerg Schilling
Using libscg version 'schily-0.9'.
scsibus10:
	10,0,0	1000) *
	10,1,0	1001) 'ATAPI   ' 'iHAS124   W     ' 'HL0G' Removable CD-ROM
	10,2,0	1002) *
	10,3,0	1003) *
	
				_IO_write_ptr: Cdrecord-ProDVD-ProBD-Clone 3.02a09 (i586-pc-haiku) Copyright (C) 1995-2016 Joerg Schilling
Using libscg version 'schily-0.9'.
scsibus10:
	10,0,0	1000) *
	10,1,0	1001) 'ATAPI   ' 'iHAS124   W     ' 'HL0G' Removable CD-ROM
	10,2,0	1002) *
	10,3,0	1003) *
	
				_IO_write_end: Cdrecord-ProDVD-ProBD-Clone 3.02a09 (i586-pc-haiku) Copyright (C) 1995-2016 Joerg Schilling
Using libscg version 'schily-0.9'.
scsibus10:
	10,0,0	1000) *
	10,1,0	1001) 'ATAPI   ' 'iHAS124   W     ' 'HL0G' Removable CD-ROM
	10,2,0	1002) *
	10,3,0	1003) *
	
				_IO_buf_base: Cdrecord-ProDVD-ProBD-Clone 3.02a09 (i586-pc-haiku) Copyright (C) 1995-2016 Joerg Schilling
Using libscg version 'schily-0.9'.
scsibus10:
	10,0,0	1000) *
	10,1,0	1001) 'ATAPI   ' 'iHAS124   W     ' 'HL0G' Removable CD-ROM
	10,2,0	1002) *
	10,3,0	1003) *
	
				_IO_buf_end: str
				_IO_save_base: Invalid Argument
				_IO_backup_base: Invalid Argument
				_IO_save_end: Invalid Argument
				_markers: 0
				_chain: 0x1a88360
				_fileno: 8
				_flags2: 0
				_old_offset: 7236281185698409839
				_cur_column: 0
				_vtable_offset: 44
				_shortbuf:  
				_lock: 0x1857ebbc
				_offset: -1
				_codecvt: 0x20746f6e
				_wide_data: 0x1857ebd0
				_mode: -1
				_unused2: roperly!

Are you sure you want to do this?

To alte
			}
			buf: 
Melt found 1 device on scsibus.
			bufzer: *
			scsid: 10,7,0
			i: 0
			RecorderCount: 1
			found_token: true
			config: No such file or directory
			savedrec: 0

		0x71f0a260	0x1b5118d	MeltApp::ReadyToRun(void) + 0x279 (/sources/melt-a32d2888d6bb601e8158b1e0a373e9f52171681b/Melt.cpp:-1)
			Variables:
			this: No such file or directory
			info {
				thread: 46429
				team: 46429
				port: 12108
				flags: 1
				signature: application/x-vnd.atomatrix-melt
			}
			ref {
				device: 4
				directory: 39
				name: Melt
			}
			entry {
				fDirFd: 3
				fName: Melt
				fCStatus: 0
				_reserved: Unavailable
			}
			path {
				_reserved: Unavailable
				fName: /boot/system/apps/Temp
				fCStatus: 0
			}
			mypath: mkdir /boot/system/apps/Temp
			len: No such file or directory
			j: No such file or directory
			testent {
				fDirFd: 4
				fName: Temp
				fCStatus: 0
				_reserved: Unavailable
			}

		0x71f0a460	0x167f373	BApplication::DispatchMessage(BMessage*, BHandler*) + 0x2eb 
		0x71f0a4a0	0x168b87f	BLooper::task_looper() + 0x20f 
		0x71f0a4e0	0x167deab	BApplication::Run() + 0x73 
		0x71f0a520	0x1b52864	main(int, char**) + 0x13c (/sources/melt-a32d2888d6bb601e8158b1e0a373e9f52171681b/Melt.cpp:-1)
			Variables:
			argc: No such file or directory
			argv: No such file or directory {
				*argv: Unavailable
			}

		0x71f0a548	0x1b46fea	_start + 0x56 
		0x71f0a578	0x7def0c	runtime_loader + 0x130 
		00000000	0x61169250	commpage_thread_exit + 0 

		Registers:
			  eip:	0x01a01daf
			  esp:	0x71f08e00
			  ebp:	0x71f08e18
			  eax:	0x00000000
			  ebx:	0x01a812c8
			  ecx:	0x00000000
			  edx:	0x00000000
			  esi:	0x00000000
			  edi:	0x00000001
			   cs:	0x001b
			   ds:	0x0023
			   es:	0x0023
			   fs:	0x0063
			   gs:	0x0023
			   ss:	0x0023
			  st0:	0.25
			  st1:	5.62
			  st2:	63.4
			  st3:	177
			  st4:	122
			  st5:	363
			  st6:	385
			  st7:	385
			  mm0:	{0, 0, 0, 0x8000}
			  mm1:	{0, 0, 0xc400, 0xb3c3}
			  mm2:	{0x3180, 0xa4a5, 0xd19b, 0xfd67}
			  mm3:	{0, 0, 0, 0xb100}
			  mm4:	{0, 0, 0, 0xf400}
			  mm5:	{0, 0, 0, 0xb580}
			  mm6:	{0, 0, 0, 0xc080}
			  mm7:	{0, 0, 0, 0xc080}
			 xmm0:	{0x2a77, 0x9c8f, 0x37e7, 0x4bb7, 0x41bc, 0xffcf, 0x2347, 0x9771}
			 xmm1:	{0x510a, 0xe289, 0xc3d8, 0x44c3, 0x8c98, 0x54d6, 0x650f, 0x96bb}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0x6a00, 0x97ce, 0x66e4, 0x11e2, 0xd699, 0x3b6c, 0xee5, 0xd985}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	643982	0x0051b000	0x00612000	0x00612000	0x00615000	lib    	/boot/system/lib/libtextencoding.so
	643967	0x007cd000	0x007ec000	0x007ec000	0x007ef000	lib    	/boot/system/runtime_loader
	643975	0x00900000	0x00909000	0x00909000	0x0090b000	lib    	/boot/system/lib/libicuio.so.57.1
	643979	0x00d82000	0x00ef4000	0x00ef4000	0x00f28000	lib    	/boot/system/lib/libicuuc.so.57.1
	643978	0x00f40000	0x00f79000	0x00f79000	0x00fb0000	lib    	/boot/system/lib/libicutu.so.57.1
	643977	0x01236000	0x01241000	0x01241000	0x01244000	lib    	/boot/system/lib/libiculx.so.57.1
	643976	0x01277000	0x012ca000	0x012ca000	0x012d5000	lib    	/boot/system/lib/libicule.so.57.1
	643969	0x01577000	0x01848000	0x01848000	0x018e1000	lib    	/boot/system/lib/libbe.so
	643980	0x01970000	0x0198a000	0x0198a000	0x0198b000	lib    	/boot/system/lib/libz.so.1.2.11
	643972	0x019a1000	0x01a77000	0x01a77000	0x01ac2000	lib    	/boot/system/lib/libroot.so
	643968	0x01b3e000	0x01b55000	0x01b55000	0x01b5a000	app    	/boot/system/apps/Melt
	643974	0x01cb0000	0x01f41000	0x01f41000	0x01faa000	lib    	/boot/system/lib/libicui18n.so.57.1
	643981	0x02015000	0x0202c000	0x0202c000	0x02031000	lib    	/boot/system/lib/libtranslation.so
	643971	0x020ec000	0x0211d000	0x0211d000	0x0212b000	lib    	/boot/system/lib/libstdc++.r4.so
	643970	0x022f4000	0x024a2000	0x024a2000	0x02502000	lib    	/boot/system/lib/libtracker.so
	643973	0x0280f000	0x0408d000	0x0408d000	0x0408e000	lib    	/boot/system/lib/libicudata.so.57.1
	643966	0x61169000	0x61171000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	3248006	0x00102000	0x00112000	        64	rw-        	full          	rld heap
	3248005	0x0011d000	0x0012d000	        64	rw-        	full          	rld heap
	3248004	0x00139000	0x00141000	        32	rw-        	full          	rld heap
	3247964	0x001aa000	0x001ab000	         4	rw-S       	full          	_rld_debug_
	3248001	0x0051b000	0x00612000	       988	r-x        	full          	libtextencoding.so_seg0ro
	3248002	0x00612000	0x00614000	         8	rw-        	full          	libtextencoding.so_seg1rw
	3248003	0x00614000	0x00615000	         4	rw-        	full          	libtextencoding.so_seg2rw
	3247963	0x00747000	0x00757000	        64	rw-        	full          	rld heap
	3247960	0x007cd000	0x007ec000	       124	r-x        	full          	runtime_loader_seg0ro
	3247961	0x007ec000	0x007ee000	         8	rw-        	full          	runtime_loader_seg1rw
	3247962	0x007ee000	0x007ef000	         4	rw-        	full          	runtime_loader_bss1
	3247985	0x00900000	0x00909000	        36	r-x        	full          	libicuio.so.57.1_seg0ro
	3247986	0x00909000	0x0090b000	         8	rw-        	full          	libicuio.so.57.1_seg1rw
	3247994	0x00d82000	0x00ef4000	      1480	r-x        	full          	libicuuc.so.57.1_seg0ro
	3247995	0x00ef4000	0x00f27000	       204	rw-        	full          	libicuuc.so.57.1_seg1rw
	3247996	0x00f27000	0x00f28000	         4	rw-        	full          	libicuuc.so.57.1_seg2rw
	3247991	0x00f40000	0x00f79000	       228	r-x        	full          	libicutu.so.57.1_seg0ro
	3247992	0x00f79000	0x00f7e000	        20	rw-        	full          	libicutu.so.57.1_seg1rw
	3247993	0x00f7e000	0x00fb0000	       200	rw-        	full          	libicutu.so.57.1_seg2rw
	3247989	0x01236000	0x01241000	        44	r-x        	full          	libiculx.so.57.1_seg0ro
	3247990	0x01241000	0x01244000	        12	rw-        	full          	libiculx.so.57.1_seg1rw
	3247987	0x01277000	0x012ca000	       332	r-x        	full          	libicule.so.57.1_seg0ro
	3247988	0x012ca000	0x012d5000	        44	rw-        	full          	libicule.so.57.1_seg1rw
	3247968	0x01577000	0x01848000	      2884	r-x        	full          	libbe.so_seg0ro
	3247969	0x01848000	0x018e0000	       608	rw-        	full          	libbe.so_seg1rw
	3247970	0x018e0000	0x018e1000	         4	rw-        	full          	libbe.so_seg2rw
	3247997	0x01970000	0x0198a000	       104	r-x        	full          	libz.so.1.2.11_seg0ro
	3247998	0x0198a000	0x0198b000	         4	rw-        	full          	libz.so.1.2.11_seg1rw
	3247977	0x019a1000	0x01a77000	       856	r-x        	full          	libroot.so_seg0ro
	3247978	0x01a77000	0x01a8a000	        76	rw-        	full          	libroot.so_seg1rw
	3247979	0x01a8a000	0x01ac2000	       224	rw-        	full          	libroot.so_seg2rw
	3247965	0x01b3e000	0x01b55000	        92	r-x        	full          	Melt_seg0ro
	3247966	0x01b55000	0x01b59000	        16	rw-        	full          	Melt_seg1rw
	3247967	0x01b59000	0x01b5a000	         4	rw-        	full          	Melt_seg2rw
	3247982	0x01cb0000	0x01f41000	      2628	r-x        	full          	libicui18n.so.57.1_seg0ro
	3247983	0x01f41000	0x01fa9000	       416	rw-        	full          	libicui18n.so.57.1_seg1rw
	3247984	0x01fa9000	0x01faa000	         4	rw-        	full          	libicui18n.so.57.1_seg2rw
	3247999	0x02015000	0x0202c000	        92	r-x        	full          	libtranslation.so_seg0ro
	3248000	0x0202c000	0x02031000	        20	rw-        	full          	libtranslation.so_seg1rw
	3247974	0x020ec000	0x0211d000	       196	r-x        	full          	libstdc++.r4.so_seg0ro
	3247975	0x0211d000	0x02128000	        44	rw-        	full          	libstdc++.r4.so_seg1rw
	3247976	0x02128000	0x0212b000	        12	rw-        	full          	libstdc++.r4.so_seg2rw
	3247971	0x022f4000	0x024a2000	      1720	r-x        	full          	libtracker.so_seg0ro
	3247972	0x024a2000	0x02500000	       376	rw-        	full          	libtracker.so_seg1rw
	3247973	0x02500000	0x02502000	         8	rw-        	full          	libtracker.so_seg2rw
	3247980	0x0280f000	0x0408d000	     25080	r-x        	full          	libicudata.so.57.1_seg0ro
	3247981	0x0408d000	0x0408e000	         4	rw-        	full          	libicudata.so.57.1_seg1rw
	3248007	0x184a6000	0x185e6000	      1280	rw-        	full          	heap
	3247956	0x60a2a000	0x60a2e000	        16	rw-        	full          	user area
	3247959	0x61169000	0x61171000	        32	r-xSk      	full          	commpage
	3248014	0x61171000	0x61172000	         4	rw-S       	full          	server_memory
	3247958	0x70f0b000	0x71f0c000	     16388	rw-s       	full          	Melt_46429_stack
	3248016	0x71f0c000	0x71f2c000	       128	rw-S       	full          	server_memory
	3248117	0x79fd2000	0x7a017000	       276	rw-s       	full          	w>Melt: New CD-R_46439_stack
	3248113	0x7a0d4000	0x7a119000	       276	rw-s       	full          	w>TrackerWindow_46437_stack

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	494543	    0	          0	Catalog
	494642	    0	      46439	AppServerLink_sLock
	495517	    0	          0	BMessageQueue Lock
	495532	    0	          0	Catalog
	495809	    0	       1484	Tracker shared icon cache
	495901	    0	      40615	some BLocker
	495929	    0	       1484	PeriodicUpdatePoses
	495951	    0	      46429	token space
	495954	   -1	      46429	Melt: New CD-R
	495960	    0	      40614	Light Lock
	495996	    0	      40635	Tracker node icon cache
	495997	    0	      40632	some BLocker
	496030	    0	      40624	clipboard
	496038	    0	       1484	some BLocker
	496050	    0	       1484	some BLocker
	496062	    0	       1484	LocaleRosterData
	496072	    0	       1484	width buffer
	496096	    0	      46437	TrackerWindow
	496110	    0	      46438	BLooperList lock
	496123	    0	          0	undo
	496141	    0	       1484	Light Lock
	496159	    0	       1484	some BBlockCache lock
	496165	    0	      40622	BMessageQueue Lock
	496171	    0	       1484	virtual directory manager
	496185	    0	      40616	some BLocker
	496187	    0	      40619	AppLooperPort
	496193	    0	      40618	some BLocker
	496197	    0	       1484	Catalog
	496202	    0	       1484	tool tip manager
	496206	    0	       1484	screen list
	496216	    0	       1484	BMessageQueue Lock
	496236	    0	       1484	some BLocker

**Comment by humdingerb** [comment]
Not a packaging issue. Please report at the project's tracker at https://github.com/matthiasr/melt/issues

**Comment by Vidrep** [comment]
Issue created: https://github.com/matthiasr/melt/issues/2
