### ISSUE TITLE
Qupzilla can't open a new private window due "Single launch" flag set in the application type window.

### ISSUE THREAD

**Issue by Giova84** [haikuports/haikuports#2069]
... As shown in the following screenshot:

![qupzilla_application_type](https://user-images.githubusercontent.com/3594780/34616981-33ec2162-f23a-11e7-9298-24a10ee93162.png)

If is changed to "Multiple launch", instead, is able to open a new private window.

**Comment by waddlesplash** [comment]
QupZilla removed in https://github.com/haikuports/haikuports/commit/6187dcea9436f01b87034f2af894608065b18caa.
