### ISSUE TITLE
Create an icon for CuteMarkEd

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#2072]
The app is missing the rdef/iom file, would be nice to see it set to the binary https://github.com/haikuports/haikuports/pull/2057

**Comment by humdingerb** [comment]
I created a nice little icon:

![cutemarked](https://user-images.githubusercontent.com/6107158/34684750-65ee3a2e-f4a6-11e7-95d9-7c4a6ef009dc.png)

I have an rdef and the edited recipe ready. Unfortunatley, the recently added defineDebugInfoPackage removed the resources from the binary...
May I comment out the debugpackage, or is there a trick?

Also, the "About" of CuteMarkEd will still show the original, rather ugly, icon.
Not sure how its buildsystem works its magic... Should it be patched for the new icon?
Help needed, if yes.

**Comment by Begasus** [comment]
Not sure how defineDebugInfoPackage removes the recourses for the icon, maybe some others can comment on this? Icon looks nice btm! :+1:

**Comment by diversys** [comment]
defineDebugInfoPackage uses `strip` which also removes the icon. Hopefully `strip` could be fixed to not do it.

**Comment by fbrosson** [comment]
Maybe we can create a GCI task to investigate how haikuporter can be taught to keep the ressources or to re-add them after creating the debuginfo package?

**Comment by pulkomandy** [comment]
On Mon, Jan 08, 2018 at 10:55:59AM -0800, Sergei Reznikov wrote:
> defineDebugInfoPackage uses `strip` which also removes the icon. Hopefully `strip` could be fixed to not do it.

Not easily.

Resources (such as icons) are just appended to the end of the file
without any change in the ELF header. So any tool that deals with elf
files will just ignore it.

However, there is a way around that:
1) save resources with xres
2) strip
3) re-add resources

I thought defineDebugInfoPackage would do it already, but maybe not. We
could fix that.

**Comment by fbrosson** [comment]
Yes it did... but the resources were being dropped again, after step 3, by objcopy.

https://github.com/haikuports/haikuporter/commit/c4c7fe9307a7f35ac05a02aa34bcb9b527c03e45 fixes this issue :)

**Comment by humdingerb** [comment]
Thanks. Updated the recipe to add the icon+rdef.

**Comment by fbrosson** [comment]
Cool!

Oops, `cutemarked-0.11.3.recipe` -> `$portVersion = 0.11.3`
https://github.com/haikuports/haikuports/commit/ad137139ce7ebbb5b16b6a32898cece0ad2cf2b8#diff-0faa6d5b6b0971436818fd4335cf5b5eR78
```diff
-	local INTERNAL="`echo "$portVersion" | cut -d. -f4`"
+	local INTERNAL="0"
```

**Comment by fbrosson** [comment]
Oops, I thought this would be a problem, but there is no problem, since there is no @INTERNAL@ in CuteMarkEd.rdef.in ;)

So sorry @humdingerb and everyone else for the noise.

(I'll delete this message and the one I wrote above. No need to keep them.)
