### ISSUE TITLE
bladeenc fails with error

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#2077]
Unpacking source of bladeenc-0.94.2-src-stable.tar.gz
'utf8' codec can't decode byte 0xb6 in position 41: invalid start byte
~/haikuports>

**Comment by scottmc** [comment]
Perhaps try this one?
http://gentoo.osuosl.org/distfiles/bladeenc-0.94.2-src-stable.tar.gz

**Comment by Vidrep** [comment]
I tried the one you linked. It also fails with errors.

**Comment by Begasus** [comment]
Tried several locations for the download, all end up in the same error, maybe a python problem?
Extracting with Expander works ok ...

**Comment by waddlesplash** [comment]
bladeenc was removed as the project seems dead.
