### ISSUE TITLE
Helios does not work on Haiku

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#2104]
New recipes created to allow Helios to build on Haiku. However, there is much work to be done to make this application actually function. User interface also has many issues.

**Comment by scottmc** [comment]
please report the issues you find over on the helios page: https://github.com/HaikuArchives/Helios/issues
perhaps this should be marked as broken in the recipe until the app works?

**Comment by Vidrep** [comment]
I would suggest we do that. Broken apps should be removed from HaikuDepot.

**Comment by mckaygerhard** [comment]
would be helpfull split this issue and paste each error log/output for each ... its too generic!

**Comment by waddlesplash** [comment]
Recipe was deactivated, and reported upstream at https://github.com/HaikuArchives/Helios/issues/8.
