### ISSUE TITLE
gpart - merge two pending pull requests into a single solution

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#2132]
There's two pending pull requests for gpart.  These should be reviewed and a best overall solution determined and then merged.  Any takers?

**Comment by fbrosson** [comment]
PR | Contributor | Version | Comments
---- | --------------- | ---------- | ----------------
#2021 | @sfanxiang | 0.3 ([stable](https://github.com/baruch/gpart/releases/tag/0.3])) | Has a patch which is split in two parts: the first is from upstream and the second is the port to Haiku. LGTM.
#2059 | @localanu | 0.3~git ([23b651d](https://github.com/baruch/gpart/commit/23b651d1e9c6ae1454e5d3fe315d7d4e145661c0)) | Has one small patch, but @alaviss noticed [the recipe does not currently build](https://github.com/haikuports/haikuports/pull/2059#issuecomment-355813270).

The only downside I can think of for @sfanxiang's recipe is that the patch from upstream is quite big. Maybe it could be worth doing some cherry-picking. But the easiest solution might be to rebase @sfanxiang's working patch against the project's git HEAD, thus allowing to drop the upstream patch.

**Comment by alaviss** [comment]
It's worth noting that @sfanxiang won't upstream the patch until [Ticket#13918](https://dev.haiku-os.org/ticket/13918) is fixed

**Comment by scottmc** [comment]
As @alaviss notes, this is dependent on Haiku tract ticket 13918 being fixed first.

**Comment by bugcrazy** [comment]
The best solution would be to create a new PR, joining the 2 PRs, updating the codes. If PR authors are not interested in updating their codes.

gpart repository has had few [commits]( https://github.com/baruch/gpart/commits/master)  over the years, more interest is unmerged [PRs]( https://github.com/baruch/gpart/pulls) .

**Comment by Begasus** [comment]
This commit at least breaks the build: https://github.com/baruch/gpart/commit/f16e53246396446ac50edcc9a0d7ae17449a0403
Can be bypassed with some ifdef/ifndef to finish a current checkout with the 2 open PR's included and the patch as done from @sfanxiang .
