### ISSUE TITLE
Update libsolv to current 0.6.30 from 0.3.0

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#2159]

**Comment by korli** [comment]
Our version diverged a bit from upstream. As this is a system package, change with care.

**Comment by Begasus** [comment]
@waddlesplash with recent changes to libsolv in the Haiku source, is this still valid?

**Comment by waddlesplash** [comment]
There is a ticket at Haiku itself about updating libsolv, so we don't need this one now.
