### ISSUE TITLE
Qupzilla: crashes when surfing to www.foxnews.com

### ISSUE THREAD

**Issue by dcatt-haiku** [haikuports/haikuports#2212]
Qupzilla crashes consistently when surfing to www.foxnews.com (and waiting for it to completely load)

This issue seems to affect all Webkit browsers for Haiku as WebPositive and Dooble are also affected by this issue, which may point to a more underlying issue.

http://www.foxnews.com/

**Comment by diversys** [comment]
Please attach debug report.

**Comment by dcatt-haiku** [comment]
I can't seem to get QupZilla to crash when it's attached to the Debugger.  I'll keep playing with it until I can.

**Comment by dcatt-haiku** [comment]
Otter crashes with www.foxnews.com as well...

QNetworkDiskCache::prepare() The cache directory is not set
Otter::Application::exec: Must be called from the main thread
QObject::~QObject: Timers cannot be stopped from another thread

**Comment by diversys** [comment]
IIRC many Qt apps print this maybe this is even normal. Anyway, debug report should tell something.

**Comment by dcatt-haiku** [comment]
Does the Debugger keep the app from crashing fully?  QupZilla eventually locks up, but doesn't necessarily crash in the way I was thinking it would when attached to the Debugger.

**Comment by extrowerk** [comment]
Then do not attach Debugger to the browser. Just let it crash and save the report in the popup window.

**Comment by kenmays** [comment]
@dcatt-haiku - I noticed similar issues with the QupZilla browser. Suggestion was to bump up to the newer Falkon 3.x web browser. WebKit is now deprecated so it could solve a lot of our current web browser rendering issues.

**Comment by kenmays** [comment]
@dcatt-haiku - Tested. Issue resolved with qtwebkit -9.
-   I rendered the entire page within 283MB usage using Otter 1.0.01 with 1GB RAM.
-   CPU usage minimal (<30% usage after page load initially completes).
-   Mem leak still present.

**Comment by waddlesplash** [comment]
QupZilla removed in https://github.com/haikuports/haikuports/commit/6187dcea9436f01b87034f2af894608065b18caa.
