### ISSUE TITLE
media-gfx/yacreader 9.0.0 is out

### ISSUE THREAD

**Issue by selmf** [haikuports/haikuports#2228]
We've just released YACReader 9.0.0

https://bitbucket.org/luisangelsm/yacreader/downloads/yacreader-9.0.0-src.tar.xz

Thanks to @miqlas patches this release *should* be Haiku-ready buildsystem and code wise, but we haven't tested it. If you still need any patches or modifications please let us know.

**Comment by extrowerk** [comment]
It seems it cannot find unarr in Haikuorter's chroot.
Out of chroot it finds everything.
No idea, where does it comes from. Will look again.

**Comment by selmf** [comment]
We use pkg-config and a fallback mechanism to detect the presence of unarr, see here:

https://bitbucket.org/luisangelsm/yacreader/src/3bb6c83a4543a3ebdd24a0ab47d5f3a3941ad08a/compressed_archive/unarr/unarr-wrapper.pri?at=default&fileviewer=file-view-default

The relevant part looks like this:

`unix:!macx {
    !contains(QT_CONFIG, no-pkg-config):packagesExist(libunarr) {
      message(Using system provided unarr installation found by pkg-config.)
      CONFIG += link_pkgconfig
      PKGCONFIG += libunarr
      DEFINES += use_unarr
      }
    else:exists(/usr/include/unarr.h):exists(/usr/lib/libunarr.so) {
      message(Using system provided unarr installation.)
      LIBS += -lunarr
      DEFINES += use_unarr
    }
  }`

It's possible that the pkg-config detection fails and the fallback mechanism isn't compatible with your changeroot. In that case you can use the patch in this commit:

https://bitbucket.org/selmf/yacreader/commits/3693e6273ca3ef472ae5e0f11ac61e978e9ca882?at=default

**Comment by extrowerk** [comment]
https://github.com/haikuports/haikuports/pull/2289

**Comment by extrowerk** [comment]
The Library still cant find YacReader, but no idea, why.

**Comment by selmf** [comment]
There is no search mechanism. On Linux YACReader is installed in /usr/bin and that means it's in the standard search paths, so just launching "YACReader" works fine. So … if a PATH environment variable or something similiar exists on Haiku, just add YACReader to it and it should work fine. If that is not an option, you will need to patch library_window.cpp.
Search for **QProcess::startDetached**. Since you seem to install the YACReader and YACReaderLibrary binaries to the same directory the Windows version of the launch command might work for you. 
Another option would be adding the $$BINDIR prefix to the Linux launch command.

If possible, try to avoid unnecessary Haiku specific #ifdefs. The goal should be making the build system flexible enough for Haiku's needs, not to add extra compatibility layers.

**Comment by extrowerk** [comment]
Fixed here: https://github.com/haikuports/haikuports/pull/2289
