### ISSUE TITLE
Calligra - app closes suddenly when trying to open a .xlsx file

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#2241]
When trying to open a .xlsx file, the Sheet app closes suddently, with the following output:

```
/boot/system/apps/Calligra> Sheets 
calligra.lib.pigment: Legacy integer arithmetics implementation
calligra.lib.migration: kde home not found
QFont::setPointSizeF: Point size <= 0 (-0.900000), must be greater than 0
KServiceTypeTrader: serviceType "ThumbCreator" not found
KServiceTypeTrader: serviceType "ThumbCreator" not found
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abort
Abort
/boot/system/apps/Calligra> 
```

**Comment by diversys** [comment]
Does it still happen after running ```kbuildsycoca5 --global```?

**Comment by unspacyar** [comment]
Yes, it still happen after running kbuildsycoca5 --global

/boot/system/apps/Calligra> setarch x86

Switching to architecture x86

[x86] /boot/system/apps/Calligra> kbuildsycoca5 --global
kbuildsycoca5 running...
"applications.menu"  not found in  () 

kf5.kservice.sycoca: Service type not found: "image/svg+xml"
kf5.kservice.sycoca: Service type not found: "video/x-mng"
kf5.kservice.sycoca: Service type not found: "text/plain"
kf5.kservice.sycoca: Service type not found: "image/png"
kf5.kservice.sycoca: Service type not found: "application/x-khtml-adaptor"
kf5.kservice.sycoca: Service type not found: "application/vnd.oasis.opendocument.presentation"
kf5.kservice.sycoca: Service type not found: "application/x-wpg"
kf5.kservice.sycoca: Service type not found: "multipart/x-mixed-replace"
kf5.kservice.sycoca: Service type not found: "application/vnd.oasis.opendocument.chart"
kf5.kservice.sycoca: Service type not found: "application/vnd.oasis.opendocument.text"
kf5.kservice.sycoca: Service type not found: "text/html"
kf5.kservice.sycoca: Service type not found: "application/vnd.oasis.opendocument.formula-template"
kf5.kservice.sycoca: Service type not found: "application/rtf"
kf5.kservice.sycoca: Service type not found: "image/wmf"
kf5.kservice.sycoca: Service type not found: "application/vnd.oasis.opendocument.text-template"
kf5.kservice.sycoca: Service type not found: "image/bmp"
kf5.kservice.sycoca: Service type not found: "application/x-quattropro"
kf5.kservice.sycoca: Service type not found: "application/vnd.oasis.opendocument.chart-template"
kf5.kservice.sycoca: Service type not found: "application/x-java"
kf5.kservice.sycoca: Service type not found: "image/x-portable-graymap"
kf5.kservice.sycoca: Service type not found: "application/vnd.openxmlformats-officedocument.spreadsheetml.template"
kf5.kservice.sycoca: Service type not found: "image/x-xbitmap"
kf5.kservice.sycoca: Service type not found: "text/csv"
kf5.kservice.sycoca: Service type not found: "application/x-kchart"
kf5.kservice.sycoca: Service type not found: "image/svg+xml-compressed"
kf5.kservice.sycoca: Service type not found: "image/x-jng"
kf5.kservice.sycoca: Service type not found: "application/vnd.oasis.opendocument.graphics"
kf5.kservice.sycoca: Service type not found: "application/x-kpresenter"
kf5.kservice.sycoca: Service type not found: "application/msword"
kf5.kservice.sycoca: Service type not found: "image/x-portable-pixmap"
kf5.kservice.sycoca: Service type not found: "application/x-vnd.kde.plan"
kf5.kservice.sycoca: Service type not found: "application/x-iwork-keynote-sffkey"
kf5.kservice.sycoca: Service type not found: "application/x-karbon"
kf5.kservice.sycoca: Service type not found: "application/vnd.oasis.opendocument.spreadsheet"
kf5.kservice.sycoca: Service type not found: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
kf5.kservice.sycoca: Service type not found: "image/vnd.microsoft.icon"
kf5.kservice.sycoca: Service type not found: "application/vnd.oasis.opendocument.text-master"
kf5.kservice.sycoca: Service type not found: "multipart/mixed"
kf5.kservice.sycoca: Service type not found: "application/vnd.oasis.opendocument.graphics-template"
kf5.kservice.sycoca: Service type not found: "application/xml"
kf5.kservice.sycoca: Service type not found: "application/x-mswrite"
kf5.kservice.sycoca: Service type not found: "application/vnd.ms-works"
kf5.kservice.sycoca: Service type not found: "image/x-xfig"
kf5.kservice.sycoca: Service type not found: "application/vnd.oasis.opendocument.spreadsheet-template"
kf5.kservice.sycoca: Service type not found: "image/openraster"
kf5.kservice.sycoca: Service type not found: "application/vnd.openxmlformats-officedocument.presentationml.presentation"
kf5.kservice.sycoca: Service type not found: "application/x-kspread"
kf5.kservice.sycoca: Service type not found: "application/pdf"
kf5.kservice.sycoca: Service type not found: "application/vnd.wordperfect"
kf5.kservice.sycoca: Service type not found: "application/vnd.ms-excel"
kf5.kservice.sycoca: Service type not found: "application/vnd.openxmlformats-officedocument.presentationml.template"
kf5.kservice.sycoca: Service type not found: "image/tiff"
kf5.kservice.sycoca: Service type not found: "image/jpeg"
kf5.kservice.sycoca: Service type not found: "image/x-portable-bitmap"
kf5.kservice.sycoca: Service type not found: "image/gif"
kf5.kservice.sycoca: Service type not found: "image/x-xpixmap"
kf5.kservice.sycoca: Service type not found: "application/x-java-applet"
kf5.kservice.sycoca: Service type not found: "application/vnd.oasis.opendocument.presentation-template"
kf5.kservice.sycoca: Service type not found: "application/illustrator"
kf5.kservice.sycoca: Service type not found: "application/vnd.openxmlformats-officedocument.wordprocessingml.template"
kf5.kservice.sycoca: Service type not found: "application/vnd.ms-powerpoint"
kf5.kservice.sycoca: Service type not found: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
kf5.kservice.sycoca: Service type not found: "application/vnd.oasis.opendocument.formula"
kf5.kservice.sycoca: Service type not found: "application/postscript"
kf5.kservice.sycoca: Service type not found: "image/x-tga"
[x86] /boot/system/apps/Calligra> Sheets 
calligra.lib.pigment: Legacy integer arithmetics implementation
calligra.lib.migration: kde home not found
QFont::setPointSizeF: Point size <= 0 (-0.900000), must be greater than 0
KServiceTypeTrader: serviceType "ThumbCreator" not found
KServiceTypeTrader: serviceType "ThumbCreator" not found
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abort
Abort
[x86] /boot/system/apps/Calligra>

**Comment by diversys** [comment]
Is it a VM? How much RAM do you have?

**Comment by unspacyar** [comment]
No, I'm running Haiku on real hardware.  It's a dual-core with 2 GB of RAM.

In any case, the RAM usage go from 30% to 60% during the seconds where the Sheet app try to open the file.  Then, goes back to 30%.  Apparently, the app closes before runing out of RAM.

**Comment by waddlesplash** [comment]
Still an issue?

**Comment by unspacyar** [comment]
Hi. Unfortunatelly, I didn't saved the xlsx files that used to test  this originally, but today I opened  about a dozen of .xlsx files (all of them created with Office suite on Windows), and didn't had any issue.

I guess this ticket can be closed.
