### ISSUE TITLE
ffmpeg_tools package from HaikuDepot fails to install on 64 bit

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#2254]
HaikuDepot: fatal error occurred while installing package ffmpeg_tools: Failed to find a match for "ffmpeg_tools"()

**Comment by mmlr** [comment]
The PROVIDES_tools does not actually provide ffmpeg_tools, it incorrectly provides ffmpeg_ffplay at its first line instead.

**Comment by Vidrep** [comment]
Welcome to the Haiku shell.

~/Desktop> diff ffmpeg-3.4.2-1.recipe ffmpeg-3.4.2-2.recipe
10c10
< REVISION="1"
---
> REVISION="2"
87c87
<       ffmpeg${secondaryArchSuffix}_ffplay = $portVersion
---
>       ffmpeg${secondaryArchSuffix}_tools = $portVersion
~/Desktop>

**Comment by Vidrep** [comment]
Issue is fixed.
