### ISSUE TITLE
Qt apps using unsuitable for font some things

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#2266]
This is with qt5_x86-5.9.3-2-x86_gcc2.hpkg

I see some Qt apps using an unsuitable font for some things that I can't seem a to find a way to change it. For example, the HTML view of the email client Troijita. Or here, viewing the page source with QupZilla:

![image](https://user-images.githubusercontent.com/1316513/36940561-57aeddd0-1f56-11e8-9b43-0b41b93aee51.png)

For some reason it uses the alphabetically second of my installed fonts. Not the first "Abusive Pencil", but the 2nd "Adobe Caslon" which is a font with decorative characters.

**Comment by diversys** [comment]
Probably a bug in QPA:
https://github.com/threedeyes/qthaikuplugins/blob/master/platforms/qhaikuplatform/haiku/qhaikuplatformfontdatabase.cpp#L92

**Comment by threedeyes** [comment]
Fixed in 2aed2e445015bae5e7867a594ec7d2a42e990c10
