### ISSUE TITLE
Blender not installing, complaining about libyaml_cpp

### ISSUE THREAD

**Issue by Knezzen** [haikuports/haikuports#2290]
Hi!

Trying to install Blender through HaikuDepot fails with an error message that nothing provides libyaml_cpp newer than 0.5.3, even though libyaml_cpp 0.6.1-1 is avaliable at HaikuDepot.

**Comment by extrowerk** [comment]
@Knezzen : Try again now.

**Comment by extrowerk** [comment]
Works ok after the bump. Please open this again if it still broken for you.
