### ISSUE TITLE
Krita installs fine, but complains about libgsl.so.0 when starting (x86_64)

### ISSUE THREAD

**Issue by Knezzen** [haikuports/haikuports#2292]
Installing Krita from HaikuDepot works just fine, but when trying to start Krita after successfully installing it, a dialog window pops up saying "Could not open Krita (Missing library: libgsl.so.0).

Sure enough "libgsl.so.0" is nowhere to be found on my system, but "libgsl.so.23" exists in /boot/system/lib and gsl is installed when searching for it in HaikuDepot.

**Comment by diversys** [comment]
I think Krita just needs to be rebuilt.

**Comment by diversys** [comment]
Should be fixed in d1ea233d753cea090cfb5672f79751b288f5d7c1. Please reopen if not.
