### ISSUE TITLE
Otter Browser start up error

### ISSUE THREAD

**Issue by elgast** [haikuports/haikuports#2335]
I installed Otter and when it starts I get a dialog box that says "Your profile directory (/boot/home/config/settings/Otter/otter) is running low on free disk space (4.0 KB remaining). This may lead to malfunction or even data loss. Do you want to continue? 
![img_20180315_190002560_hdr](https://user-images.githubusercontent.com/16988361/37517890-4f0e51dc-28e9-11e8-8da2-a32f2ff4806e.jpg)

**Comment by diversys** [comment]
https://discuss.haiku-os.org/t/directory-profiles/6287/5

**Comment by elgast** [comment]
Okay, so has a bug report been filed?

**Comment by diversys** [comment]
Nope.

**Comment by extrowerk** [comment]
Test it again.

**Comment by extrowerk** [comment]
I assume it is fixed.
