### ISSUE TITLE
After last upgrade qt-apps don't runs

### ISSUE THREAD

**Issue by petr-akhlamov** [haikuports/haikuports#2402]
When i try to open any QT-app, then get next error:
![qt1](https://user-images.githubusercontent.com/16255202/38094263-00503aa0-3376-11e8-850e-43ed4ce25b01.png)
![qt2](https://user-images.githubusercontent.com/16255202/38094264-007933f6-3376-11e8-88a2-3c010ab94627.png)
![qt3](https://user-images.githubusercontent.com/16255202/38094265-00a107aa-3376-11e8-8347-4c349251f84f.png)
Before upgrade all worked fine.

**Comment by diversys** [comment]
It looks like this commit broke it https://git.haiku-os.org/haiku/commit/?id=a25f7264b6a3e66687df4cd9850dd7d3bb1243a7

**Comment by petr-akhlamov** [comment]
In last builds already all works. Close as "Cannot Reproduce"
