### ISSUE TITLE
JRE missing in HaikuDepot 

### ISSUE THREAD

**Issue by petr-akhlamov** [haikuports/haikuports#2428]
JRE missing in HaikuDepot. Maybe, due broken URL at openjdk-1.7 recipe?
https://github.com/haikuports/haikuports/blob/8a75ac661f8d97af1ec9161a00d050620942021c/dev-lang/openjdk/openjdk-1.7.u80_b32.recipe
>
https://dl.dropboxusercontent.com/u/61946213/j2sdk-image-140528.tar.xz
>
404

**Comment by extrowerk** [comment]
@petr-akhlamov : please do not attach any precompiled binaries here, as there is no manual way to upload a package into the Depot.

If you can, please try to fix the recipe, create a PR, and if it gets merged the builder bots will build a new version and upload the resulting packages to the Depot server.

**Comment by pulkomandy** [comment]
There is a working recipe for openjdk 1.8, but it depends on a previous version of openjdk being available (because it needs to run some Java tools to build itself). So in this case, someone has to uplaod a package to the builders so they can use it to build new versions.

It should be possible to drop this on the builders to get things going: http://pulkomandy.tk/drop/openjdk_x86-1.8.u40_b27-2-x86_gcc2.hpkg (and you can also install it if you want)

**Comment by humdingerb** [comment]
FWIW, installing pulkomandy's openjdk 1.8 and changing the recipe's requirement from openjdk 1.7 to 1.8 errors out when trying to build the 1.8 recipe.

Are we sure the openjdk_x86-1.8.u40_b27-2-x86_gcc2.hpkg works correctly. I haven't been able to launch a Java app yet. E.g.:
´´´
/HiQ-Data/apps/JDownloader> java /HiQ-Data/apps/JDownloader/JDownloader.jar
Error: Could not find or load main class .HiQ-Data.apps.JDownloader.JDownloader.jar
´´´
It's entirely possible I'm doing it wrong. Not much of a Java user... With the old 1.7 openjdk this worked, but now says "permission denied":
´´´
/HiQ-Data/apps/JDownloader> /boot/system/lib/x86/openjdk/lib/jexec JDownloader.jar
bash: /boot/system/lib/x86/openjdk/lib/jexec: Permission denied
´´´

**Comment by diversys** [comment]
The basic command is: `java -jar jar-file`. The -jar flag tells the launcher that the application is packaged in the JAR file format. You can only specify one JAR file, which must contain all of the application-specific code.

**Comment by humdingerb** [comment]
Thanks, diver. That works better, but no cigar yet. :)
Says:
```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 50331656 bytes for Chunk::new
```
Can't upload the log: http://ix.io/17xF

**Comment by pulkomandy** [comment]
On Wed, Apr 11, 2018 at 08:50:35AM -0700, humdinger wrote:
> Are we sure the openjdk_x86-1.8.u40_b27-2-x86_gcc2.hpkg works correctly. I haven't been able to launch a Java app yet. E.g.:
> ´´´
> /HiQ-Data/apps/JDownloader> java /HiQ-Data/apps/JDownloader/JDownloader.jar
> Error: Could not find or load main class .HiQ-Data.apps.JDownloader.JDownloader.jar
> ´´´

The command to start a jar is:

    java -jar /HiQ-Data/apps/JDownloader/JDownloader.jar

> It's entirely possible I'm doing it wrong. Not much of a Java user... With the old 1.7 openjdk this worked, but now says "permission denied":
> ´´´
> /HiQ-Data/apps/JDownloader> /boot/system/lib/x86/openjdk/lib/jexec JDownloader.jar
> bash: /boot/system/lib/x86/openjdk/lib/jexec: Permission denied
> ´´´

Why would one run jexec directly? It's in the "lib" dir for a good
reason, probably?

**Comment by humdingerb** [comment]
I'm still failing to build openjdk v1.8.
I downloaded and installed
* http://packages.haiku-os.org/haikuports/master/hpkg/openjdk_x86_devel-1.7.u80_b32-3-x86_gcc2.hpkg
* http://packages.haiku-os.org/haikuports/master/hpkg/openjdk_x86-1.7.u80_b32-3-x86_gcc2.hpkg

Building then failed with a "File name too long", so I uncommented these lines in the v1.8 recipe:

 	#OpenJDK has an internal limitation of 256 characters in a path. And with the default src dir we go past it.
	cd ..
	mv $sourceDir src
	cd src
	ln -s src $sourceDir

It goes farther now, but still fails - I assume in INSTALLL() when it gets to the certificates:

> # There is insufficient memory for the Java Runtime Environment to continue.
> # Native memory allocation (malloc) failed to allocate 201326600 bytes for Chunk::new
> # An error report file with more information is saved as:
> # /sources/src/hs_err_pid13884.log
> Certificate was added to keystore

The hs_err_pid13884.log: http://ix.io/19pF

**Comment by humdingerb** [comment]
Wrong URL for the log... correction http://ix.io/19pH

BTW, can the v1.7 packages be uploaded manually and installed on the buildbot machines?

**Comment by humdingerb** [comment]
paging @mmlr ...
Could/should the v1.7 OpenJDK be added to the repo and buildbots manually?
Running Java apps would be nice and maybe someone can solve the build of v1.8 if v1.7 was available.

**Comment by korli** [comment]
Please check.

**Comment by threedeyes** [comment]
Now we need to somehow do this for x64. Maybe we can use experimental hybrid build (gcc2_x86 x86 x86_64) for it?

**Comment by return** [comment]
@korli It seems that installing the OpenJDK 1.8 package breaks other applications on hrev52295+100 x86_gcc2.

![screenshot1](https://user-images.githubusercontent.com/7050293/47828172-c6269a00-dd79-11e8-83a4-eac63867bfa6.png)

**Comment by korli** [comment]
@return this should be fixed in https://github.com/haikuports/haikuports/commit/8adae0ef41bdd1575ba487cd6eb24a7181173c00 but the builder has obsoleted openjdk 1.7 and can't rebuild the package.
I tested the package locally and it behaves incorrectly, saying it can't allocate memory. it seems the switch to gcc7 has produced a new problem.

**Comment by diversys** [comment]
Can we build openjdk 1.7? I seem to remember that 1.8 was slower on Haiku and was spamming syslog with allocating memory messages over and over again while 1.7 worked much faster.

**Comment by waddlesplash** [comment]
>  I tested the package locally and it behaves incorrectly, saying it can't allocate memory. it seems the switch to gcc7 has produced a new problem.

The out of memory errors should have been fixed by https://github.com/haikuports/haikuports/commit/b17ac441cea92dcc0d85a5e0efe667b230689333. So, I'm not sure what's going on here?

**Comment by waddlesplash** [comment]
> 

Now we need to somehow do this for x64. Maybe we can use experimental hybrid build (gcc2_x86 x86 x86_64) for it?

Yes, I've started working on this on my local machine.

**Comment by waddlesplash** [comment]
Actually, it seems we currently use the `server` VM by default, which explicitly allocates a much larger heap. We should probably use the `client` VM instead, which has memory behavior much more in line with what we expect, from reading Oracle's documentation.

**Comment by diversys** [comment]
See also http://mail.openjdk.java.net/pipermail/haiku-port-dev/2018-April/000144.html

**Comment by diversys** [comment]
...and http://mail.openjdk.java.net/pipermail/haiku-port-dev/2018-April/000138.html

**Comment by waddlesplash** [comment]
So, I did more investigation yesterday. It's not that it fails to allocate small heaps, it's that it allocates another 256MB every 150ms or so constantly from startup until it reaches 2GB at which point it of course runs out of address space and exits. Applications actually work ... for the 3-5 seconds before it hits that point.

It only actually uses 300-400MB of that 2GB from what I could tell. I didn't manage to find any resources online to explain what could be causing this, and adding Xmx or the like did nothing.

**Comment by waddlesplash** [comment]
It's fully patched and packages are now available.
