### ISSUE TITLE
mesa:  bump to 17.1.10

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#2435]
See https://dev.haiku-os.org/ticket/14076

**Comment by kenmays** [comment]
Korli - I tested up to Mesa 18.0.0 on Haiku hrev51875. For Mesa 18, it will not need the current patch for:
gallium/auxiliary/gallivm/lp_bld_misc.cpp

**Comment by korli** [comment]
https://dev.haiku-os.org/attachment/ticket/14076/mesa-17.1.10.recipe

**Comment by korli** [comment]
@kenmays hmm, I was under the impression that from 17.2.x mesa wouldn't build because of mesa internal changes. @kallisti5 what's the current status?

**Comment by kenmays** [comment]
Mesa 17.1.10 is good enough.

**Comment by kallisti5** [comment]
I haven't had the bandwidth lately to work on Mesa much in the last 2 months or so.

We/I need to finish our Meson build system additions.  SCons is going away and is the primary way we build Mesa.

https://github.com/kallisti5/mesa/tree/haiku-meson

**Comment by kallisti5** [comment]
The current status is the meson build in that branch *works* but the generated artifacts have missing symbols when used.   We need to fix the meson build before moving forward with more fixes.

**Comment by kallisti5** [comment]
*actually* i already got the original meson changes merged... sorry for the mis-info.
https://cgit.freedesktop.org/mesa/mesa/commit/?id=834d221512fae8dd290d347fec071c4adbe140ed

The artifacts generated are broken though :-)

**Comment by kenmays** [comment]
Just a note: Here are the current HaikuPort patches which integrate with Mesa 18.0 for Haiku hrev 51877+. I put them here so I can always test remotely against the build system.

I don't see anything major in the patchset only this:
"+GL_API void GL_APIENTRY glBlendBarrier (void);
+GL_API void GL_APIENTRY glPrimitiveBoundingBox (GLfloat minX, GLfloat minY, GLfloat minZ, GLfloat minW, GLfloat maxX, GLfloat maxY, GLfloat maxZ, GLfloat maxW);
+"

Note: From Mesa 13.0.4 patchset to Mesa 17.0-17.1 patchset there are hardly any internal changes being done. I mentioned that porting Mesa to other platforms - Gallium 0.4 renders OK for Flurry. Will work on it as time permits.

**Comment by kenmays** [comment]
[mesa-18.0-haiku.zip](https://github.com/haikuports/haikuports/files/1917707/mesa-18.0-haiku.zip)

**Comment by kenmays** [comment]
We can close this ticket. We can add --enable-texture-float and --enable-gallium-osmesa to
the recipe. Saw a small bug during shader cache test. We can move this to #2462.

**Comment by kenmays** [comment]
@kallisti5, @korli - We can update to Mesa 17.1.10. I'll suggest here that we can reimplement mesa_swrast
until mesa_swpipe can be refined.
![ken-haiku51904-mesa-17 1](https://user-images.githubusercontent.com/5168719/39441966-7e93f36e-4c64-11e8-9809-db1219b432c2.png)

**Comment by kenmays** [comment]
Fixed. I built x86_64 packages for Mesa 18.0.2 so this ticket is no longer needed.
You can close this ticket.

**Comment by korli** [comment]
closing as requested.
