### ISSUE TITLE
QMPlay2 is not able to open files from Tracker anymore

### ISSUE THREAD

**Issue by Daniel-Fortesque** [haikuports/haikuports#2439]
With version 17.04.21 it was possible to play files directly from Tracker via double-click.
With any later version it's not working anymore - QMPlay2 starts, but doesn't open the file.

**Comment by Daniel-Fortesque** [comment]
Ok, guess I will have to stick with the old version =)
Thanks for investigation guys! Should I close the issue?

**Comment by threedeyes** [comment]
Fixed in 267e872caf46fff4bb51ad3d9622f26bb4363b60

**Comment by Daniel-Fortesque** [comment]
Awesome! Keep up the great work! 
П.С.: Спасибо за апдейты и поддержку портов, вашим трудом гайка с каждым днём становится всё лучше!
