### ISSUE TITLE
SuperTuxKart 0.9.3 review

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2441]
Porting SuperTuxKart 0.9.3 to Haiku.

Website: https://supertuxkart.net
Src: https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.3/supertuxkart-0.9.3-src.tar.xz/download

Basic Req for Haiku port testing: GCC5, Mesa, Xrandr

**Comment by kenmays** [comment]
Dependency:
1. Xrandr

**Comment by kenmays** [comment]
This requires Xrandr library extension which is not included yet. Will reopen once Xrandr is included in repo.

**Comment by extrowerk** [comment]
If xrandr an hard requirement, you will have to patch it out. There is no X11 for Haiku.

**Comment by kenmays** [comment]
Ok, and since R1 beta is near - closing this request.

**Comment by extrowerk** [comment]
This is just strange. It have nothing to do with Haiku releases.

-- Z.

2018.08.10. dátummal, 15:49 időpontban kenmays <notifications@github.com> írta:

**Comment by kenmays** [comment]
I'm just retracting this one for now. I'll resubmit once I get it built on my end.

**Comment by AlwaysLivid** [comment]
Just briefly necroposting over here this to say that I completed the port of SuperTuxKart to the Haiku operating system as demonstrated on [Reddit](https://www.reddit.com/r/haikuOS/comments/h99w98/supertuxkart_now_runs_on_haiku/), as well as [on the SuperTuxKart blog](https://blog.supertuxkart.net/2020/07/supertuxkart-12-release-candidate-1.html), thanks to a recent addition of SDL support to the game's engine.

CC: @kenmays @extrowerk

**Comment by kenmays** [comment]
@ AlwaysLivid - Most excellent!

**Comment by AlwaysLivid** [comment]
> @AlwaysLivid - Most excellent!

I just haven't had the time to make a Haikuports port for it.
