### ISSUE TITLE
Qt5 crash with development version of RetroArch

### ISSUE THREAD

**Issue by kwyxz** [haikuports/haikuports#2484]
Hello folks,

The upcoming version of RetroArch will feature a fancy brand-new WIMP interface based on QT5. Here's a picture of it running on Debian GNU/Linux.

![debian-wimp](https://user-images.githubusercontent.com/1202508/39285842-70309ba8-48cf-11e8-9121-03867bb05a97.png)

It's available in branch `qt_wimp` of https://github.com/bparker06/RetroArch

I thought I'd give a try to building it on Haiku, and it built fine! Unfortunately, it crashes on startup. Here's a link to the debugging output : https://pastebin.com/raw/XR0gWQ5R

I had a long chat with the developer of the WIMP interface and we tried to tackle this down. According to him there's a chance the issue is within the Haiku implementation of Qt5. Has anyone seen anything similar?

Thanks!

**Comment by threedeyes** [comment]
I think the problem is a combination of Qt5 and SDL. They create their own copies of BeApplication.

**Comment by kwyxz** [comment]
Thank you for your answer! Looking at the current configuration, the video driver used for RetroArch is GL. Could it however be creating its own copy of `BeApplication` too?

**Comment by kwyxz** [comment]
I tried rebuilding RetroArch entirely without SDL and am getting the same crash... here is the report. 

[retroarch-nosdl.txt](https://github.com/haikuports/haikuports/files/1953279/retroarch-nosdl.txt)

**Comment by waddlesplash** [comment]
Is this still a problem?

**Comment by kwyxz** [comment]
It is not! That is amazing! Kudos to whoever figured it out and fixed it!
![Screenshot from 2020-04-10 12-17-41](https://user-images.githubusercontent.com/1202508/79017119-6a8f3d00-7b25-11ea-8cf4-0cb27387a575.png)
