### ISSUE TITLE
alex4: stops soon  after start of game

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2487]
![alex4_x64](https://user-images.githubusercontent.com/5168719/62917904-ec3e8900-bd52-11e9-9ad0-47d0195a429b.jpeg)

Note: Haiku hrev51890 x86_64 (gcc5)

alex4 game shows an intro and works for other menu options - but after you select to start the game it will only show background scene, but not the game character(s)) or details.

Game works fine on Haiku hrev51894 x86 (gcc2).

[Alex4-809-debug-08-08-2018-16-33-30.report.txt](https://github.com/haikuports/haikuports/files/2271080/Alex4-809-debug-08-08-2018-16-33-30.report.txt)

**Retested on hrev53368 x86_64.**

**Comment by kenmays** [comment]
Game works fine for x86 version on hrev51894.

**Comment by kenmays** [comment]
Added debug report. Reverified on hrev52187 x86_64 w/alex4 1.0-2 package.

**Comment by kenmays** [comment]
Retested on **hrev53368 x86_64** with **alex4-1.0-3-x86_64.hpkg** and **allegro-4.4.3.1-1-x86_64.hpkg**. Same issue.

**Comment by kenmays** [comment]
There seems a syscall be-gfx_direct-window drawing issue. Will move this to allegro review as the alex4 x86 build seems fine.

**Comment by pulkomandy** [comment]
Please do not close issues until problems are solved.

**Comment by kenmays** [comment]
I mentioned the issue is possibly coming from allegro as mentioned here as well:
https://www.allegro.cc/forums/thread/617917

In review:
1. dumb package seems fine.
2. allegro compiles fine, but lots of warnings. beos-code and some gfx.

**Comment by pulkomandy** [comment]
And? The game is still not working. We will close this issue when problems in Allegro have been fixed, on their side or ours.

**Comment by kenmays** [comment]
Seems several legacy games don;t work on Haiku x86_64 (i.e. at the moment). I'm closing ticket to consolidate to a general review all all games not working.
