### ISSUE TITLE
Calligra 3.1.0-1 x86_64 package not installing

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2501]
Calligra Suite 3.1.0-1 seems to download fully and install from Haiku Depot app - but doesn't install the Calligra Suite packages or show it in main menu (although it shows as active in Haiku Depot menu). After manually checking, Calligra Suite was not installed. 

NOTE: Installed a few other packages, no issues.

**Comment by alaviss** [comment]
`/var/log/syslog` would contains valuable informations regarding this issue. Could you please provide the log at the moment which those packages were installed? Thanks.

**Comment by kenmays** [comment]
[calligra-3.1_syslog-haiku-x86.txt](https://github.com/haikuports/haikuports/files/1969306/calligra-3.1_syslog-haiku-x86.txt)

**Comment by fbrosson** [comment]
@kenmays, can you try a `pkgman update` ? (You can also update with HaikuDepot, of course.)
After I saw eb7110d2ff70a0fe56c7ebe2330c3a37150bac55 I updated to `kio-5.45.0-2` and was then able to install calligra on my x86_64 system. It gets activated, it is shown in the Applications menu, and it runs fine.

On x86_gcc2, however, after a `pkgman update` and a `pkgman install calligra_x86` I see that calligra_x86 is activated but I don't get the _Applications_ → _Calligra_ menu.
(In other words, I have on x86_gcc2 the same issue you had on your x86_64 system.)

**Comment by kenmays** [comment]
Confirmed. Calligra 3.1.0 installs and works properly on Haiku hrev51921 x86_64.

**Comment by fbrosson** [comment]
Good news: I just noticed that my x86_gcc2 system now also has the _Applications_ → _Calligra_ menu.
(I don't remember having done anything special, so I guess that what fixed my issue (after the update) was a simple reboot.)
Closing this issue, as it seems to be fixed everywhere, thanks to @threedeyes!
