### ISSUE TITLE
Add recipe for QtWebEngine

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2512]
The Qt WebEngine add-on module provides classes and functions for embedding web content in applications and providing Chromium's fast moving web capabilities into Qt.

URL: https://wiki.qt.io/QtWebEngine
Docs: http://doc.qt.io/qt-5/qtwebengine-index.html

Closes: https://github.com/haikuports/haikuports/issues/3638

**Comment by pulkomandy** [comment]
Also required if we want to get OnlyOffice Desktop running.

**Comment by kenmays** [comment]
Falkon 3.0.1 baseline
![falkon-3 0 1-haiku-cocobean](https://user-images.githubusercontent.com/5168719/40159140-adea1b16-595c-11e8-816f-4d977c7208d8.png)
[falkon_rdef.txt](https://github.com/haikuports/haikuports/files/2011787/falkon_rdef.txt)
[falkon-3.0.1_spec_Haiku.txt](https://github.com/haikuports/haikuports/files/2011788/falkon-3.0.1_spec_Haiku.txt)

**Comment by fbrosson** [comment]
Cool, it looks like you did the most difficult part: port qtwebengine to Haiku! This is great news!

Would you like to try and write a recipe for it?
I'm a bit busy at the moment, otherwise I would have started writing a recipe and opened a PR with a commit ending with [`Co-authored-by:`](https://help.github.com/articles/creating-a-commit-with-multiple-authors/) followed by your `users.noreply.github.com` GitHub e-mail address :)

**Comment by kenmays** [comment]
@fbrosson - I've added the Falkon 3.10.1 and Qt WebEngine 5.10.1 recipe to get things started. Everything here should get the ball rolling rather quickly.

**Comment by extrowerk** [comment]
@kenmays : could you please create a pull request with the recipes (one / recipe).
Btw, the qtwebengine patchset looks strange to me, i expected that it requires extensive patching, and you don't even have any Haiku related patch in the patchset. Does it actually builds and works on Haiku?

**Comment by kenmays** [comment]
Yes, I'm building everything on Haiku. Getting very close but still need a lot of free time. Backing everything up for now. Will work on it more as my time permits.

**Comment by extrowerk** [comment]
Does xcursor and xrandr a hard dependency?

**Comment by kenmays** [comment]
No. I removed them.

**Comment by extrowerk** [comment]
@kenmays : Please, create a recipe, or post your actual patchset, or post at least one screenshot about QtWebEngine on Haiku because it is just a good clickbait trolling currently.

**Comment by kenmays** [comment]
@extrowerk - I'll post it soon and fix the patchset (it was just to provide others with some patches for their own use). Mentioned earlier I'm doing a complete walkthrough to first fix dependency packages before anyone else goes down this rabbit hole.

**Comment by kenmays** [comment]
@extrowerk - I'll post it soon and fix the patchset (it was just to provide others with some patches for their own use). Mentioned earlier I'm doing a complete walkthrough to first fix dependency packages before anyone else goes down this rabbit hole. (The main goal task was to just create the Qt WebEngine recipe.)
![qt_webengine-5 10_cocobean](https://user-images.githubusercontent.com/5168719/40273750-60890118-5b7b-11e8-880f-92c9acdb1311.png)

**Comment by kenmays** [comment]
Almost perfected my optional dependencies on Haiku...
![ken_qt-webengine_haiku](https://user-images.githubusercontent.com/5168719/40388793-4f69bbb0-5dc5-11e8-857d-bbdc29ef3776.jpeg)

**Comment by extrowerk** [comment]
Mate... Show a make output ;)

**Comment by kenmays** [comment]
Yes. Tested again with qt-webwngine v5.11.0 yesterday. Had to fix my setup after the update to GCC 7. Built and tested ICU 61.1. Time to dive back in and spin the wheel...

**Comment by kenmays** [comment]
See #2632
Provided initial recipes for Falkon and Qt WebEngine for future work. Closing ticket for now.
Working on WebPositive and Webkit for R1 beta.

**Comment by extrowerk** [comment]
Post your patches.

**Comment by kenmays** [comment]
Tests: 
http://webglsamples.org/toon-shading/toon-shading.html
https://www.onlyoffice.com/

**Comment by extrowerk** [comment]
@kenmays : how is this relevant? The whole web is a testcase.

**Comment by kenmays** [comment]
@extrowerk - I was making a note of Pulkomandy's 'request' about OnlyOffice. I'll remove it.

**Comment by extrowerk** [comment]
@kenmays : can you please remove the screenshots too? Thanks.

**Comment by KapiX** [comment]
Reposting from the PR so it won't be lost: https://gist.github.com/KapiX/8502596ef66813195cf8d2bec7393cd7 - with this patch QtWebEngine can be built, but will crash immediately.

**Comment by kenmays** [comment]
Bumped recipe and patchset to QtWebEngine 5.12.3. Still a W-I-P.

**Comment by KapiX** [comment]
I have updated the gist: https://gist.github.com/KapiX/8502596ef66813195cf8d2bec7393cd7

I managed to make Falkon run, but it won't draw anything.

This probably has something to do with the fact that on Linux QtWebEngine is built using Chromium's Ozone layer, but I had to disable it on Haiku because it depends on Linux's libevdev (so much for platform independence...).

I've also tried dumping stuff to files in Chromium code using Skia, but that doesn't work either.

I believe this patchset will also be useful for people wanting to work on Haiku Ozone platform - in theory it's a few classes to implement; in practice, as mentioned above, Ozone depends on Linux libraries, so additional work is needed there.

I'm done with this codebase for the time being. It's a treadmill of patching - 5.13.0 is already out and it updated Chromium from 69 to 73.

**Comment by kenmays** [comment]
After a year of effort, this fixed a lot of smaller issues - but has a lot of 'knobs' to maintain. **I'm closing this ticket.** libDRM, 3D acceleration, etc are needed/wanted by the Ozone project. **This adds a lot of workload to support, maintain, and test.**  Best to take smaller bites on this one.

**Comment by KapiX** [comment]
Please stop closing issues randomly. I also don't know where did you get that Ozone requires libDRM?

**Comment by kenmays** [comment]
I opened this ticket. Feel free to move under yourself if you are handling things further.

**Comment by KapiX** [comment]
You are not assigned to it as far as I can see so what is the problem?

**Comment by korli** [comment]
Just a note, this would be required by [Calibre5](https://github.com/haikuports/haikuports/blob/master/app-text/calibre/), and [PyQtWebengine](https://www.riverbankcomputing.com/software/pyqtwebengine/intro).

**Comment by waddlesplash** [comment]
I think @threedeyes got pretty far with this, but I don't think he ever posted a patch: https://www.youtube.com/watch?v=xsJE9HiJZl4

It would be really nice to have a truly solid browser for Haiku...

**Comment by kenmays** [comment]
Resolved: 
1. https://github.com/haikuports/haikuports/blob/master/dev-qt/qtwebengine/qtwebengine-5.15.2.recipe
2. https://github.com/haikuports/haikuports/blob/master/www-client/falkon/falkon-3.1.0.recipe

Ref: https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/6391/builds/76360.log

**Comment by kenmays** [comment]
QtWebEngine 5.12.2-1 build passed 95% build completion without errors using GCC 11.2.0.
