### ISSUE TITLE
GitHub Services depreciation warning

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#2539]
**NOTE:** This service been marked for deprecation: https://developer.github.com/changes/2018-04-25-github-services-deprecation/

      Functionality will be removed from GitHub.com on January 31st, 2019

**Comment by phoudoin** [comment]
what's the impact on us?
On which part we rely on GitHub Services? Automated detection of changes to trigger buildmaster ? Gerrit authentification ?

**Comment by pulkomandy** [comment]
On Sun, May 06, 2018 at 01:40:17PM +0000, phoudoin wrote:
> what's the impact on us?
> On which part we rely on GitHub Services? Automated detection of changes to trigger buildmaster ? Gerrit authentification ?

This warning is included in all e-mail notifications from haikuports to
the haikuports mailing list. I guess we need to rewire the mailing list
hooks to the new API?

**Comment by waddlesplash** [comment]
The mailing list is currently updated via GitHub itself through their send-email feature. AFAICT they do not have any official replacement for the email feature, only webhooks, so we might need to host a new webhook-to-email handler ourselves.

**Comment by korli** [comment]
can we close this?
