### ISSUE TITLE
Several packages not installing from Haiku Depot

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2544]
There are several packages in the Haiku Depot app that are not installing when selected from within the Haiku Depot app - but exist in the package repository and downloadable for manual installation.

x86_64:
1. nightandday
2. timecop
3. ghostscript
4. apache
5. cmark
6. qpdfview 
7.  libsigc++3_devel

**Comment by extrowerk** [comment]
nightanddy and timecop fixed, ghostscript is strange, idk why it doesn't working with Depot as it isntalls perfectly in terminal.

**Comment by extrowerk** [comment]
ghostscript listed as "ghostscript" but provides "ghostscript_gpl"
apache listed as "apache" but provides "apache2"
cmakerk listed as "cmark" but provides "libcmark"

Should we fix it in the recipes or do we want more flexible matching algo in Depot or in depot backend?

**Comment by extrowerk** [comment]
qpdfviewer fixed

**Comment by kenmays** [comment]
NOTE: ghostscript_gpl won't attach to Scribus 1.5.2 (disabled dependency or not compiled with it enabled?)
Needs review.

**Comment by fbrosson** [comment]
@extrowerk, I forgot to mention you in this [comment](https://github.com/haikuports/haikuports/commit/da53df6338482b5af548db26861506250f641ac6#commitcomment-28939822), so I'm adding a pointer to it here.
BTW, I suspect that bumping `REVISION` would have been enough to fix it.

@kenmays, I guess that when you tried to install the latest release of `libsigc++_devel` (before  da53df6338482b5af548db26861506250f641ac6), what (probably) happened was that you had another package which needed an older release of `libsigc++`.
So you could only install the latest release of `libsigc++_devel` if you accepted to uninstall the older release as well as `libsigc++` and the packages that depended on it.

If we want to be able to co-install more than one version of `libsigc++` then this requires that:
1) we have different `PROVIDES` and `PROVIDES_devel` for each recipe of `libsigc++` we want to co-install,
2) we add `CONFLICTS_devel`,
3) we rename the recipes themselves.

@extrowerk, you only took care of step 1. Shall I take care of steps 2 and 3?

**Comment by extrowerk** [comment]
@fbrosson : i have no time to do that in the following days. Would be nice if you can give a helping hand.

-- Z.

2018.05.12. dátummal, 1:33 időpontban fbrosson <notifications@github.com> írta:

**Comment by fbrosson** [comment]
Here it is: #2552.
Notice: I still need to check that everything builds.

**Comment by extrowerk** [comment]
@kenmays : Scribus built without Ghostscript, see here: https://github.com/haikuports/haikuports/blob/f57ded24f532692558246b15e1df39ac963806be/app-office/scribus/scribus-1.5.2.recipe
Enable it if you need, build it, test it, if works send a PR.

**Comment by kenmays** [comment]
Ghostscript optional. Reviewed with Scribus 1.5.4.
[scribus-1.5.4.recipe.txt](https://github.com/haikuports/haikuports/files/2002982/scribus-1.5.4.recipe.txt)

**Comment by threedeyes** [comment]
I tried to build version 1.5.4 (and 1.5.3), but had problems with the binloader. The startup process stops on loading dependencies. At the moment 1.5.2 is the latest version, which successfully runs under my Haiku.

**Comment by kenmays** [comment]
IMHO, Scribus 1.5.2 is good enough on Haiku for now.

**Comment by kenmays** [comment]
We can close this one for now. I installed the few remaining packages manually which is good enough.
Can fix remaining issues with Haiku Depot as needed. Thanks.

**Comment by fbrosson** [comment]
> Remaining install issues when using Haiku Depot:
> * ghostscript
> * ~cmark~
> * apache

* `cmark-0.26.1` fixed in 47e252d54a285f0b7bb97eb26fd81583efb6b7cd.
* `cmark-0.26.1` fixed in 1495c0fe5e2cf55d2faa8641d5936835cf90020a.
* `cmark` moved from category `dev-util` to `app-text` in #2681.

**Comment by kenmays** [comment]
Tested on hrev52187 x86_64.  Reverified package installs: cmark, ghostscript, apache
Passed. Ticket resolved.
