### ISSUE TITLE
libvpx: remove package libvpx3 dependency

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2580]
Enhancement: Please remove any package dependencies on earlier libvpx < 1.7.0 packages.

**Comment by kenmays** [comment]
Not a priority. Can review before R1 beta.

**Comment by fbrosson** [comment]
With #2584 `gd` will depend on `libvpx.so.5` (instead of `libvpx.so.3`).

**Comment by fbrosson** [comment]
With #2587 and #2586 gnuplot `5.0.7` and `5.2.3` now depend on `libvpx.so.5` (instead of `libvpx.so.3`).
