### ISSUE TITLE
open pull requests not (yet) migrated to GitHub

### ISSUE THREAD

**Issue by taosxx** [haikuports/haikuports#259]
It seems that open pull requests - in contrast to issues - have not been migrated from Bitbucket to GitHub yet.

**Comment by waddlesplash** [comment]
No, they haven't, because due to the nature of a pull request, the original authors have to manually migrate their own. :cry: So @bbjimmy and all the others who had open PRs need to fork this repo -> push your local branches to GitHub -> create a pull request.

**Comment by pulkomandy** [comment]
30 juin 2015 14:47 "gus knight" <notifications@github.com> a écrit:
> No, they haven't, because due to the nature of a pull request, the original authors have to
> manually migrate their own.  So @bbjimmy and all the others who had open PRs need to fork this repo
> -> push your local branches to GitHub -> create a pull request.

We can manually merge them using git as well (probably bitbucket allows getting the changes from a PR using git? I know github does).

Some of these were opened by GCI students and I doubt they will update, but we should still keep track of the work done.

-- 
Adrien.

**Comment by waddlesplash** [comment]
> We can manually merge them using git as well (probably bitbucket allows getting the changes from a PR using git? I know github does).

It does, but it's very annoying.

> Some of these were opened by GCI students and I doubt they will update, but we should still keep track of the work done.

Well, most of the ones left open are very stale. I merged all the open PRs to HaikuPorter before moving (as they all looked OK, and had been open for a while), and merged two of the HaikuPorts PRs. The only PR that had been touched in the last 6mo was @bbjimmy's, and he had some open review comments that weren't addressed, so I figured he'd be able to move the PR over here.

**Comment by waddlesplash** [comment]
Oh, and re GCI work: Most of those recipes were sub-par in quality which is why they weren't moved. I can try to clean some of them up, but IIRC most of them didn't even pass lint, let alone compile...

**Comment by taosxx** [comment]
I opened my PR on June, 22nd - and it has not been merged.

**Comment by waddlesplash** [comment]
Ah, whoops, I mistook your PR for one of the other ones. My apologies. It looks like it can be merged, hang on...

**Comment by pulkomandy** [comment]
@waddlesplash yes, the reason they were not merged is that they weren't ready. This doesn't mean the work done in writing and reviewing them should be ignored, it is still a good base to start from. We can't ignore this data. We probably don't need to convert them to PR or merge them immediately, I think a sensible solution would be to have tickets with the patches and comments (unless it is faster to actually finish the work and merge).

**Comment by waddlesplash** [comment]
Makes sense to me. Will do.

**Comment by waddlesplash** [comment]
@taosxx I merged your PR in 8caae31a88fe59a10345f4170c90e97f2c38d2aa.

**Comment by taosxx** [comment]
@waddlesplash thanks for merging!

**Comment by waddlesplash** [comment]
This is now being tracked in #260.

**Comment by bbjimmy** [comment]
all the issues were addressed in my pr, I was just going to make a
comment to that effect when the repo disappeared.


-- 
bbjimmy
http://www.coquillemartialarts.com
http://www.fatelk.com

**Comment by waddlesplash** [comment]
Oh, okay. I'll have a look at yours as well.

**Comment by waddlesplash** [comment]
@bbjimmy Merged in ae14e65ffb30f7a8384aa4bd9e40e8ca6f91a7d7.
