### ISSUE TITLE
ICU: Bump to ICU v61.1

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2598]
ICU 61 provides full support for the recent Unicode 10.0 release with many new characters and many property improvements. Unicode 10.0 adds 8,518 characters, for a total of 136,690 characters. These additions include 4 new scripts, for a total of 139 scripts, as well as 56 new emoji characters. Locale data is updated to CLDR 33 locale data and adds Google double-conversion library for formatting doubles.  This is the library used in V8 and a number of other projects for converting doubles to decimals. 

Homepage: http://site.icu-project.org/
Src: http://download.icu-project.org/files/icu4c/61.1/icu4c-61_1-src.tgz

Successfully Tested: ICU 61.1 on Haiku x86_64 hrev51971
[icu-61.1-testing_cocobean.txt](https://github.com/haikuports/haikuports/files/2029848/icu-61.1-testing_cocobean.txt)

Recipe/Patches:
[icu-61.1-haiku.zip](https://github.com/haikuports/haikuports/files/2030156/icu-61.1-haiku.zip)

**Comment by korli** [comment]
What about gcc2?

**Comment by kenmays** [comment]
@korli - Give it a test and let me know. I'll set up for that soon.

**Comment by kenmays** [comment]
1. Can enhance ICU 57.1 recipe with tzdata2018e.

**Comment by extrowerk** [comment]
@kenmays : please use pull requests for your work, and do not manually edit the patch files.
Are your recipes tested with haikuporter?

My PR superseeds your patches and recipe, but it would be nice if you would use the infrastructure, as it allows us to give comments, ideas and check your work easily.

**Comment by extrowerk** [comment]
Your gcc2 patchset summary references files, wich aren't patched in your patchset, that's inconsistent and not acceptable.

**Comment by kenmays** [comment]
@extrowerk - Amazing work on bumping ICU. Closing this one!

**Comment by kenmays** [comment]
https://github.com/haikuports/haikuports/pull/5097
