### ISSUE TITLE
Packages affected by GCC 7.3

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2619]
Tested on Haiku x86_64 hrev51983.
These packages were affected by GCC 7.3 change. May need recompilation or use of older GCC 5.x lib:

- [x] blender
- [x] hdf5
- [x] openblas
- [x] libgeotiff

Note:
- [ ] alex4 - crashes when you select 'start game' from games menu. gcc2 build OK.

Issues are in packages finding:

    libgfortran >=3.0
    libgcc_s >=5.4.0
    libproj >= 12.0.0

**Comment by kenmays** [comment]
Issues are:

- libgfortran >=3.0
- libgcc_s >=5.4.0

**Comment by kenmays** [comment]
These were minor issues being addressed by smaller tickets or future recompile.
Blender #2626.

**Comment by extrowerk** [comment]
What is the reason behind opening and closing issues randomly?
This and #2544 not even (completely) solved yet.

**Comment by fbrosson** [comment]
@extrowerk, with all my respect, that's not the right question to ask.
What you could ask is: _"Shall we reopen this issue?"_

**Comment by kenmays** [comment]
Ref #2651

**Comment by extrowerk** [comment]
I think libgeotiff is also fixed in the meantime. Can somebody check it?

**Comment by kenmays** [comment]
Tested on hrev52187 x86_64. Verified blender and libgeotiff 1.4.2-2 package install now without issue.
Ticket resolved.
