### ISSUE TITLE
audiofile build issue

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#2624]
https://kitchen.haiku-os.org/master/x86_64/logviewer.html?buildruns/1426/builds/10719.log

**Comment by diversys** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/audiofile/files/audiofile-0.3.6-gcc6-build-fixes.patch

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/2725
