### ISSUE TITLE
blender build issue

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#2626]
runtime_loader: /boot/system/lib/libstdc++.so.6.0.21: version "CXXABI_1.3.11" not found (required by libOpenImageIO.so.1.8)

https://kitchen.haiku-os.org/master/x86_64/logviewer.html?buildruns/1447/builds/10804.log

**Comment by extrowerk** [comment]
I assume OpenImageIO needs to be rebuilt

**Comment by scottmc** [comment]
perhaps related to #2880?

**Comment by korli** [comment]
Build success:
https://kitchen.haiku-os.org/master/x86_64/buildruns/1790/builds/11344.log
