### ISSUE TITLE
tor-x86 does not install from HaikuDepot

### ISSUE THREAD

**Issue by irtusb** [haikuports/haikuports#2627]
this is hrev 51983 x86_gcc2

* Trying to install tor_x86 from HaikuDepot results in following error
![imagen](https://user-images.githubusercontent.com/300455/40739067-3d1431c6-6413-11e8-82fe-27418116b75a.png)
succesfully installed via `pkgman install tor`

* Trying to uninstall it via HaikuDepot results in
![imagen](https://user-images.githubusercontent.com/300455/40738882-aca14174-6412-11e8-9069-5c09f1507c66.png)
 successfully uninstalled via `pkgman uninstall tor`

**Comment by diversys** [comment]
Should be fixed in https://github.com/haikuports/haikuports/commit/74ef3abf43048b4b8710f8913e010ae799c8f50a.
