### ISSUE TITLE
Mesa: enable OpenGL ES 2.0 feature

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2629]
Enable the OpenGL ES 2.0 feature in Mesa recipe to enhance cross-platform portability of OpenGL-based graphic apps to Haiku.

1. Run configure with --enable-gles2
2. Include the glx* headers

Test with web browsers:
Test example: http://arodic.github.io/p/jellyfish/
Test example: http://alteredqualia.com/three/examples/webgl_pasta.html

**Comment by extrowerk** [comment]
>Include the glx* headers

What is GLX?
What are the dependencies?
Why do we need this?
Any practical use case?
Any screenshot to prove it could work? (Would say: build mesa with gles2 and build something wich requires gles2 and create a screenshot)

**Comment by pulkomandy** [comment]
from Wikipedia: GLX (initialism for "OpenGL Extension to the X Window System")

We don't have - and don't plan to run - X11 on Haiku. Therefore GLX is useless.

For portability one could use EGL (https://en.wikipedia.org/wiki/EGL_(API)), which our Mesa already provides. EGL is designed to be less tied to a specific backend than GLX.

Enabling gles2 is possibly useful, however.

**Comment by extrowerk** [comment]
@pulkomandy : i asked the questions to point the spotlights to glx and its dependencies.

@kenmays : it seems you are working hard to get Haiku useful, nice job.
Just my 2 cents: please do not use any X11 libs in your recipe-changes/ports, as they are broken/incomplete/stubs/unusable. Even if X11 matures on Haiku we shouldn't base anything on it, as it would bring a whole mess dependencies, so from my viewpoint any changes in any recipe which introduces X11 dependencies should be automatically rejected.

**Comment by extrowerk** [comment]
@pulkomandy : true. +1

**Comment by kenmays** [comment]
Ok. I'll close this for now.
