### ISSUE TITLE
GCC / Gfortran broken

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#2651]
Since the GCC bump it is impossible to build some packages, because ```__cpu_model``` symbol is missing:

> runtime_loader: /boot/system/lib/libgfortran.so.4.0.0: Could not resolve symbol '__cpu_model'

Affected packages:
- alembic
- hdf5
- openblas
- ...

We cannot use the old, gcc5 built packages from Depot as they requires older GCC, so install is impossible.  There is more and more recipe depends on fortran, mostly libs, required by end-user programs, so it is a pain right now.

While this is already fixed upstream, this testcase shows the problem on current Haiku with current GCC: https://github.com/nothings/stb/issues/280#issue-146985437

**Comment by korli** [comment]
From http://kitchen.haiku-os.org/master/x86_64/buildruns/1389/builds/10671.log
```
libtool: link: /sources/gcc-7.3.0_2018_05_01-obj/./gcc/xgcc -B/sources/gcc-7.3.0_2018_05_01-obj/./gcc/ -B/packages/gcc-7.3.0_2018_05_01-1/.self/develop/tools/x86_64-unknown-haiku/bin/ -B/packages/gcc-7.3.0_2018_05_01-1/.self/develop/tools/x86_64-unknown-haiku/lib/ -isystem /packages/gcc-7.3.0_2018_05_01-1/.self/develop/tools/x86_64-unknown-haiku/include -isystem /packages/gcc-7.3.0_2018_05_01-1/.self/develop/tools/x86_64-unknown-haiku/sys-include    -shared .libs/libgfortran.la.lnkscript -Wl,--whole-archive ../libbacktrace/.libs/libbacktrace.a -Wl,--no-whole-archive  -Wl,-rpath -Wl,/sources/gcc-7.3.0_2018_05_01-obj/x86_64-unknown-haiku/libquadmath/.libs -Wl,-rpath -Wl,/packages/gcc-7.3.0_2018_05_01-1/.self/develop/tools/lib/gcc/x86_64-unknown-haiku/7.3.0 ../libquadmath/.libs/libquadmath.so  -Wl,--version-script=/sources/gcc-7.3.0/libgfortran/gfortran.map -shared-libgcc   -Wl,-soname -Wl,libgfortran.so.4 -o .libs/libgfortran.so.4.0.0
```

Somehow the linker didn't find the symbol in libgcc.so and assigned it a NOTYPE definition.
```
readelf -s build_packages/gcc_syslibs-7.3.0_2018_05_01-1-x86_64/lib/libgfortran.so.4.0.0 | grep cpu_model
   252: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __cpu_model
  1173: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __cpu_model
```

Did you try to rebuild gcc locally with gcc7 installed? The buildbot built gcc with gcc5 libs installed which don't have the required symbols. 

summary: I would try to rebuild binutils, then gcc.

**Comment by korli** [comment]
The gcc and binutils packages were rebuilt.

**Comment by diversys** [comment]
Same problem after updating gcc and binutils packages:
`runtime_loader: /boot/system/lib/libgfortran.so.4.0.0: Could not resolve symbol '__cpu_model'`

**Comment by extrowerk** [comment]
Got some comments/questions about this on #gcc:

_<redi> miqlas: does haiku  use ELF symbol versioning?
<redi> on gnu/linux that is a versioned symbol
<redi> 0000000000217190 B __cpu_model@GCC_4.8.0
<redi> is it present in libgcc_s.so.1 ?
<redi> is the symbol present? does it have global visibility? is it versioned_?

**Comment by pulkomandy** [comment]
You check this with readelf:

readelf -aW libgcc_s.so.1 | grep cpu_model

**Comment by korli** [comment]
I don't know if it's related, I had "Could not resolve symbol" errors on the bootstrap build at runtime, because a gcc patch was missing in the buildtools repository. 
https://git.haiku-os.org/buildtools/commit/?id=13dd3f531fc30b6e144034ddce1ea1c9b224dbfd

**Comment by extrowerk** [comment]
Mini-testcase:

hello.f:
```
Program Hello
Print *, "Hello World!"
End Program Hello
```

compile it like:
$ gfortran hello.f -o hello
run it:
$ ./hello

**Comment by jessicah** [comment]
Hmm, the symbol is in libgcc_s.so, but it's visibility is local, not global.

**Comment by jessicah** [comment]
Fixed in b941ba5c2d1cad6721c30306de56ee541af2a0a8

**Comment by extrowerk** [comment]
Great, thanks!
But you have forgot to bump the recipe revision.

**Comment by jessicah** [comment]
No, a new package hasn't been built yet (we lost our package builders on maui in the outage), so the previous bump from commit prior (fixing LTO) is sufficient.
