### ISSUE TITLE
libreoffice: x86_64 package missing app binaries

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2654]
Current libreoffice x86_64 package missing app binaries (i.e. Writer, Impress, Calc,...)
pkg: libreoffice-6.2.0.0~git-2-x86_64.hpkg

**Comment by diversys** [comment]
LibreOffice doesn't provide app binaries for its components, instead you're supposed to start them either from shortcuts (on Windows) or from .desktop files (on Linux).
These files simply run soffice binary (which we rename to LibreOffice) with parameters. See https://help.libreoffice.org/Common/Starting_the_Software_With_Parameters

**Comment by kenmays** [comment]
Confirmed. Works fine on my end.

**Comment by diversys** [comment]
What we can do, tho, is to make launchers like 3dEyes did for Calligra I think?

**Comment by kenmays** [comment]
Yes. Add a subfolder with the proper app links to the menu within the LibreOffice folder.
Whatever gives the 'best user experience' to launch the LibreOffice apps.
