### ISSUE TITLE
libreoffice: x86_64 package missing dependencies

### ISSUE THREAD

**Issue by Briseur** [haikuports/haikuports#2657]
It won't start without installing libboost 165 and there's an error message complaining about it but syslog also report missing OpenCL, It complains about some vclplugin too but I guess that it isn't ported yet..
libboost 165 package name is quite obvious and so with a little effort average user can fix that but it isn't the case for OpenCL and there's no error message about it only a line in syslog.

**Comment by kallisti5** [comment]
confirmed here.  boost163 comes pre-installed. It appears the pre-installed boost163 is enough to fill the dependency for libboost, however it should be locked to boost165

**Comment by diversys** [comment]
Should be fixed in 19971303a0fc8c4f47793cb0c9e335105996b3c1.
