### ISSUE TITLE
Update Mudlet

### ISSUE THREAD

**Issue by vadi2** [haikuports/haikuports#2660]
Would it be possible to update https://github.com/haikuports/haikuports/tree/master/game-mud/mudlet to latest?

**Comment by extrowerk** [comment]
Yes, bump the recipe version, do a test build and if it is OK, then send a PR.

**Comment by vadi2** [comment]
I'm not a Haiku OS user, so I can't.

**Comment by pulkomandy** [comment]
(It's just Haiku, not Haiku OS.)

Thanks for the notice, someone will take care of it eventually.
