### ISSUE TITLE
Various problems in Qt / Qt Creator

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#2672]
@threedeyes, I know you just pushed a new version of Qt and I haven't looked at it yet, so if these Qt Creator bugs are already fixed then you can check them off and close this ticket.

 - [x] Modal dialogs are not really modal (you can click on other app windows behind them and bring those to focus / the front)
 - [x] Autocomplete popup always disappears after about 1/3 of a second after it appears, rendering it unusable (related to item 1?)
 - [x] `Alt+Tab` away from Qt Creator adds a tabstop to focused input (probably in all input dialogs, didn't test)
 - [x] Zoom does not respect Deskbar (I guess this means Qt's `BWindow` subclass has its own implementation of `Zoom`?)
 - [ ] `Open Terminal Here` does not work

**Comment by waddlesplash** [comment]
Also cc @diversys.

**Comment by diversys** [comment]
The first 3 issues are probably bugs in QPA: https://github.com/threedeyes/qthaikuplugins/tree/master/platforms/qhaikuplatform

The last one sounds like it shoulrt be fixed in Qt Creator itself to open `/system/Terminal` instead of whatever it is trying to open.

**Comment by waddlesplash** [comment]
I guessed as much. Should I open a ticket there, or is this fine?

**Comment by diversys** [comment]
Autocomplete is fixed now. Other problems have been moved to https://github.com/threedeyes/qthaikuplugins/issues/1
Open Terminal Here still remains tho.

**Comment by diversys** [comment]
Haiku Terminal should probably be added to the list of known terminals here 
https://github.com/qt-creator/qt-creator/blob/master/src/libs/utils/consoleprocess_unix.cpp#L346-L357

**Comment by waddlesplash** [comment]
Oh, and Open in file browser is also broken.

**Comment by threedeyes** [comment]
> Oh, and Open in file browser is also broken.

What do you mean? "Open with" from Tracker?

**Comment by waddlesplash** [comment]
No, in right clicking in Qt Creator's file tree. It tries to run xdg-open.

**Comment by diversys** [comment]
Hopefully fixed in c4a7e0ae81352635df7fe916fa2361d5d675fb4b.
