### ISSUE TITLE
Album: Only first image gets displayed

### ISSUE THREAD

**Issue by danboid** [haikuports/haikuports#2682]
The Album app isn't much use currently because it only displays the first image file dragged into its window. If you drag multiple files in at once then it only shows a thumbnail preview of one image.

Also, what is 'Write thumbnails' from the Atributes menu supposed to do? It doesn't seem to do anything.

**Comment by danboid** [comment]
This is under Haiku 52001 x86_64

**Comment by scottmc** [comment]
Please open a new issue for this here:
https://github.com/HaikuArchives/album/issues


-Scott

**Comment by danboid** [comment]
Done

https://github.com/HaikuArchives/Album/issues/11
