### ISSUE TITLE
Xz_utils does not uncompress .xz files in Haiku Expander application

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#269]
Ticket #12204 from Haiku Bug Tracker
Bonefish responded as follows:
This is a problem with plain ".xz" files only. ".tar.xz" and ".txz" work. Easy to reproduce with an empty file (touch ~/Desktop/foo.xz), BTW. The expander rule looks good:
"application/x-xz"      .xz     "echo %s | sed 's/.xz$//g'"     "xz -df %s"
At least for listing it is analogous to the rule for ".gz":
"application/x-gzip"    .gz     "echo %s | sed 's/.gz$//g'"     "gunzip -c %s > `echo %s | sed 's/.gz$//g'`"
A difference compared to the gzip rules is that those for ".tar.gz" and ".tgz" don't list a MIME type. Copying the /system/data/expander/rules/xz_utils to /system/non-packaged/data/expander/rules/xz_utils and clearing those MIME type entries does indeed solve the problem.
So the xz_utils package needs to be fixed. Please file a HaikuPorts ticket.

**Comment by korli** [comment]
Should be fixed in hrev49499.
