### ISSUE TITLE
Add recipes for vasm and vlink

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#270]
I use these in some of my 8-bit coding activities, and having a recipe would be nice.
Should mostly compile out of the box (maybe need to remove -lm from the makefiles)

**Comment by waddlesplash** [comment]
@pulkomandy, please remember to add the appropriate tags to your issue next time...

**Comment by waddlesplash** [comment]
`vasm` was added in 605cb5f83c1e11b8daa78a5c7a7c410756065f06.

**Comment by pulkomandy** [comment]
vlink added in 146f2cc6654031.
