### ISSUE TITLE
SDL2: 3D mouse handling is completly broken

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#2719]
SDL Mouse input interpreted somehow wrong so no game is enjoyable:
- mouse sensitivity is way too high
- the directions also somehow broken if one moves the mouse vertically the viewport moving in every possible directions

This is AFAIK not a regression, it was always broken. Happens in every SDL2 based 3d game.

Affected ports (tested by me):
- eduke
- aleph one

It could be a GSoC task...

**Comment by pulkomandy** [comment]
It's probably much too simple for a GSoC task on its own. The whole SDL2 port was a GSoC task.

**Comment by scottmc** [comment]
Perhaps look into adding a TEST to the libsdl2 recipe?  IIRC it includes a boatload of tests.  Run them and then report back on this ticket what is broken.  These issues could then potentially be turned into GCI tasks.

**Comment by kenmays** [comment]
Failed 4 out of 10 mouse tests on SDL 2.0.8:
> INFO:  08/27/18 23:37:57: ----- Test Case 6.3: 'mouse_createFreeCursor' started
> ERROR: 08/27/18 23:37:57: >>> Test 'mouse_createFreeCursor': Failed (Aborted)
> ERROR: 08/27/18 23:37:57: >>> Test 'mouse_createFreeCursor': Failed
> INFO:  08/27/18 23:37:57: ----- Test Case 6.5: 'mouse_setCursor' started
> ERROR: 08/27/18 23:37:57: >>> Test 'mouse_setCursor': Failed (Aborted)
> ERROR: 08/27/18 23:37:57: >>> Test 'mouse_setCursor': Failed
> INFO:  08/27/18 23:37:57: ----- Test Case 6.6: 'mouse_getCursor' started
> ERROR: 08/27/18 23:37:57: >>> Test 'mouse_getCursor': Failed
> INFO:  08/27/18 23:37:57: ----- Test Case 6.9: 'mouse_createFreeColorCursor' started
> ERROR: 08/27/18 23:37:57: >>> Test 'mouse_createFreeColorCursor': Failed (Aborted)
> ERROR: 08/27/18 23:37:57: >>> Test 'mouse_createFreeColorCursor': Failed
>

**Comment by diversys** [comment]
Can you check is this is still an issue after b40072d3d29f8872f57215995c0b62612eddc04f?

**Comment by kenmays** [comment]
@diversys - Same mouse test errors.

**Comment by extrowerk** [comment]
@kenmays, failing tests are one thing, but the question is: does it function better with 3d games? I had no time to test yet.

**Comment by kenmays** [comment]
@extrowerk - Tested w/ Neverball 1.6.0. I now get excellent mouse precision control using default settings. **Issue resolved** (i.e. on my end).

The other mouse tests deal with changing the color of the cursor or setting the cursor. Nice to fix when time permits.

**Comment by extrowerk** [comment]
It seems to be solved, thanks!
