### ISSUE TITLE
mtr quits with _res is not supported for multi-threaded programs.

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#272]
Upon execution mtr quits with "_res is not supported for multi-threaded programs." message.
See more here https://dev.haiku-os.org/ticket/12195

**Comment by pulkomandy** [comment]
Looking at the source code, it seems there is support for res_ninit already. However I'm not sure the way to detect its availability is correct (dns.c line 323, #ifdef res_ninit).
Probably their configure script should check for it instead.

**Comment by diversys** [comment]
Fixed in hrev49619.
