### ISSUE TITLE
haiku-apps/xaos crashes on window resize

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#2721]
When resizing the window too much, it crashes.
Can't ssem to upload the debug.report, pasted at: http://ix.io/1enw

**Comment by korli** [comment]
[1enw.txt](https://github.com/haikuports/haikuports/files/3884128/1enw.txt)

**Comment by diversys** [comment]
AFAIR, previous version didn't crash on resize. We can either go back to that version or somebody need to fix it properly.

**Comment by korli** [comment]
Is this still current after d09196dc421b0ca1ab1aa41e7aa6027baca3a74b?

**Comment by humdingerb** [comment]
Still crashing on resize: 
[XaoS-4359-debug-16-02-2023-19-00-06.report.txt](https://github.com/haikuports/haikuports/files/10759587/XaoS-4359-debug-16-02-2023-19-00-06.report.txt)

**Comment by humdingerb** [comment]
Sorry, the above was with the old v3.4 that's available from HaikuDepot.
Just built 4.2.1 on 64bit: no crash! :)
