### ISSUE TITLE
"git help" should open HTML help in web browser

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#274]
git hqs qn help commqnd which should select the most appropriate way of showing the help. On some other platforms it will open a web browser with html pages, but on Haiku it always opens the man pages.
The HTML pages would be better as they have nicer formatting, hyperlinks, and other things expected from a modern help system.

**Comment by waddlesplash** [comment]
The HTML help is included and there is some way to configure Git to show it by default.

At any rate, I started on Git 2.4, but they changed the configuration system so our patchset to put configuration files in ~/config/settings/Git/ will take a bit of work...

**Comment by pulkomandy** [comment]
Fixed in 2aae89f05f52ce48c80764944ae15c424072188.
