### ISSUE TITLE
BeZilla 2.0.0.22-7: Not supported on many popular websites (EoL/Decommision?)

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2746]
Please review decommissioning BeZilla 2.0.0.22 as most popular websites do not support this version and it renders many business and media-related websites incorrectly (versus WebPositive 1.1).

NOTE: Mainly, does not work at all with certain websites (i.e. unsupported) or will misrender them worse than when viewed with WebPositive 1.1..

Although the source release is 10 years old, the application's main rendering functionality needed for browsing/supporting today's web servers is the main issue.

**Comment by scottmc** [comment]
We should at least update the HaikuDepot description to note the age of this if it hasn't already been noted there.

**Comment by extrowerk** [comment]
In the same time we should mark it and the Mail companion as untested for every arch, so if somebody really needs them, could still build it. I would remove them from depot too.

**Comment by diversys** [comment]
I just want to note that when last year(?) when it so happened that both Web+ and Qt browsers were broken Firefox was the only browser that still worked which I used it to find and download previous version of Qt to get QupZilla working again :)

**Comment by pulkomandy** [comment]
> I just want to note that when last year(?) when it so happened that both Web+ and Qt browsers were broken Firefox was the only browser that still worked which I used it to find and download previous version of Qt to get QupZilla working again :)

I would recommend NetSurf in that case!

Anyways, rather than removing old software from the depot, I would
rather rely on user ratings and comments so people can make an informed
decision on it. And it's not called Firefox so it's unlikely that people
would find it by accident anyways.

**Comment by kenmays** [comment]
Thanks everyone. I'll close this ticket as I now agree with keeping around this old browser - since I've experienced a few legacy commercial apps that  misrender on newer Firefox browsers.

As mentioned, since it is not labeled as Firefox, most people will consider it a BeOS legacy app
due to remaining info on the Web like: https://www-archive.mozilla.org/ports/beos/
