### ISSUE TITLE
command_not_found package broken?

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#2760]
On x86_64 i got this output:

https://dev.haiku-os.org/ticket/14222#comment:3

See the attachment.

**Comment by alaviss** [comment]
`GLOBAL_WRITABLE_FILES` is supposed to be the metadata for such purposes, but no one implemented any cleaning up functions for `pkgman` using it AFAIK.

**Comment by alaviss** [comment]
Closed via 728340e427aed9ef190ab6a39115076131b0d275
