### ISSUE TITLE
TexLive build fails

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#2772]
Building texlive-2014.recipe, revision 2, fails:
```
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Remember to add 'LT_INIT' to configure.ac.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:20: error: required file '../../build-aux/compile' not found
configure.ac:20:   'automake --add-missing' can install 'compile'
configure.ac:20: error: required file '../../build-aux/missing' not found
configure.ac:20:   'automake --add-missing' can install 'missing'
Makefile.am: error: required file '../../build-aux/depcomp' not found
Makefile.am:   'automake --add-missing' can install 'depcomp'
autoreconf: automake failed with exit status: 1
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 1
Error: Build has failed - stopping.
```
(Achtung! Big download 1.62 GiB...)

**Comment by alaviss** [comment]
Running

    autoreconf -vfi

Will fix the issue. But I think we should consider updating the recipe first.

**Comment by diversys** [comment]
I didn't know about this ticket so fixed it with this:
https://github.com/haikuports/haikuports/blob/673d62ada7c0d1e9fe24ce1360039300ff86000e/app-text/texlive/texlive-2014.recipe#L627-L630

Now I'm not sure if it was the best way but it gets the build to go much further.

It now fails with this:
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/2747/builds/12822.log
```
Master/install-tl:949 -> mtxrun --generate ...env: 'texlua': No such file or directory
Can't open perl script "/boot/system/data/texlive/tlpkg/tlpostcode/dvipdfmx.pl": No such file or directory
```

```mtxrun --generate``` calls ```texlua``` which is nowhere to be found.
And it looks like ```/boot/system/data/texlive``` is hardcoded? I found one place in the patch:
https://github.com/haikuports/haikuports/blob/e26d2729b881c398ea44a6e3a0058abc1851b68a/app-text/texlive/patches/texlive-2014.patchset#L152

Any ideas @jessicah ?

**Comment by Begasus** [comment]
Superseded by now.
