### ISSUE TITLE
libfm_extra-1.3.0.2 fails to build on x86 second arch

### ISSUE THREAD

**Issue by fbrosson** [haikuports/haikuports#2774]
[x11-libs/libfm-extra/libfm_extra-1.3.0.2.recipe](https://github.com/haikuports/haikuports/blob/d702b32ee598437d0639a1baadf351ceff69aed1/x11-libs/libfm-extra/libfm_extra-1.3.0.2.recipe) is failling to build on x86 secondary arch, as we can see in the logs after a revump for libfm_qt (0b2ff1fbe604324ab4d08def795011bb0d5493f3):
http://kitchen.haiku-os.org/master/x86_gcc2/?buildrunDir=1493

**Comment by Begasus** [comment]
Builds ok here, only need to create a few PR's for this I think ...

**Comment by Begasus** [comment]
pcmanfm_qt fails however with:
 /packages/qt5_x86-5.10.1-1/.self/settings/autostart.  Maybe need
    administrative privileges.

**Comment by Begasus** [comment]
Fixed in the meantime.
