### ISSUE TITLE
pcmanfm_qt-0.13.0 fails to build on x86_64 and x86 second arch

### ISSUE THREAD

**Issue by fbrosson** [haikuports/haikuports#2775]
[x11-misc/pcmanfm-qt/pcmanfm_qt-0.13.0.recipe](https://github.com/haikuports/haikuports/blob/2a621b9c9284db42673404baea9ea0e05f716664/x11-misc/pcmanfm-qt/pcmanfm_qt-0.13.0.recipe) is failling to build on x86_64 (and x86 secondary arch too), as we can see in the logs after a revump for that same recipe (2a621b9c9284db42673404baea9ea0e05f716664):
http://kitchen.haiku-os.org/master/x86_64/?buildrunDir=1654

**Comment by Begasus** [comment]
Fixed in: https://github.com/haikuports/haikuports/pull/8916
