### ISSUE TITLE
cantata: libavcodec_x86>=57.64.101 dependency broken

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2786]
Since the update to FFmpeg 4.x, some packages are not installing properly by pkgman due to
a ' libavcodec_x86>=57.64.101' provider not found error. FFmpeg 4.x provides libavcodec 58.x.

- cantata_x86

**Comment by alaviss** [comment]
@kenmays 

Thanks for taking the time to report these!

Note to contributors, before you merge any library updates, please check for ports that depend on the library you are updating, especially when the new version supersede the old one, and make sure to update such ports `REVISION` and test them.

With that said, fixing the bug should be as simple as bumping `REVISION` for the `cantata` recipe. I currently don't have access to my dev machine, so I will leave this to some other contributor.
