### ISSUE TITLE
Warning: dev-python/python_setuptools-5.3 is overruled by duplicate in dev-python - please remove one of them

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#282]
This is because `python_setuptools` is incompatible with `python3_setuptools`. Is this fixable?

**Comment by korli** [comment]
I don't understand the issue. How is it a problem in the recipes?

**Comment by waddlesplash** [comment]
Hmm, my bad, I guess the packages are compatible. I don't know why HaikuPorter gives this error though, but it invariably does on x86_64...

**Comment by korli** [comment]
there is now only one recipe for one version of setuptools.
