### ISSUE TITLE
Evaluate non-library packages for secondary arch

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#283]
Currently, some non-library packages (e.g. `sshfs`) declare they can be built for the secondary architecture. I don't see much point to this, and it should probably be disabled.

**Comment by weinhold** [comment]
Maybe I miss something, but if they can't be built with gcc 2, they have to be built for the secondary architecture on x86_gcc2/x86 hybrids, no?

**Comment by pulkomandy** [comment]
Yes, and the opposite case also exists (old code only building properly with gcc2, or 32-bit only, when we get 64/32 hybrids).

**Comment by waddlesplash** [comment]
> Maybe I miss something, but if they can't be built with gcc 2, they have to be built for the secondary architecture on x86_gcc2/x86 hybrids, no?

No, what I'm saying here is that some of these recipes (e.g. sshfs) say they can be built for both e.g. 'x86_gcc2' and the secondary arch 'x86', which doesn't make a lot of sense in the context that it's a filesystem addon, not a library.

**Comment by pulkomandy** [comment]
add-ons are not very different from libraries, in this case it can be loaded by userlandfs and there is no reason for userlandfs to run only on the pripary architecture (even if only for testing purposes).

**Comment by waddlesplash** [comment]
Right, but having 2 packages in the repository that are the same thing (one for primary, one for secondary) makes no sense to the end-user. We should pick one arch per primary arch to make packages for.

**Comment by waddlesplash** [comment]
OK, I ran a check. Here are the packages which do not have a `lib:`, `devel:`, or `addon:` provide, which have a `SECONDARY_ARCHITECTURES` section but not `!x86_gcc2` in `ARCHITECTURES`, and should be investigated as to why they have a `SECONDARY_ARCHITECTURES` section:

 - [ ] `sharutils`
 - [ ] `qemacs*`
 - [ ] `xemacs`
 - [ ] `bochs`
 - [ ] `vmware_addons`
 - [ ] `mc`
 - [ ] `screen`
 - [ ] `srm*`
 - [ ] `lyx`
 - [ ] `zsh*`
 - [ ] `tree`
 - [ ] `clucene`
 - [ ] `hugen`
 - [ ] `avr_libc`
 - [ ] `gnu_classpath`
 - [ ] `swi_prolog*`
 - [ ] `swig`
 - [ ] `gnulib`
 - [ ] `iniparse`
 - [ ] `pygame`
 - [ ] `pygments`
 - [ ] `indent`
 - [ ] `intltool`
 - [ ] `netsurf_buildsystem*`
 - [ ] `pkgconfig*`
 - [ ] `posixtestsuite`
 - [ ] `ragel`
 - [ ] `bzr`
 - [ ] `maelstrom`
 - [ ] `quake3`
 - [ ] `edgar`
 - [ ] `supertux`
 - [ ] `gemrb`
 - [ ] `ponscripter`
 - [ ] `solarus`
 - [ ] `xmoto`
 - [ ] `homeworld_sdl`
 - [ ] `armyknife`
 - [ ] `beae`
 - [ ] `beget`
 - [ ] `butterfly`
 - [ ] `cdplayer`
 - [ ] `clockwerk`
 - [ ] `cmake_haiku`
 - [ ] `colors`
 - [ ] `dockbert`
 - [ ] `hare`
 - [ ] `keymapswitcher`
 - [ ] `launchpad`
 - [ ] `masterpiece`
 - [ ] `netpulse`
 - [ ] `paladin`
 - [ ] `pecorename`
 - [ ] `wonderbrush`
 - [ ] `yab_ide`
 - [ ] `puri`
 - [ ] `superfreecell`
 - [ ] `iff_ilbm_translator`
 - [ ] `mailnews`
 - [ ] `cantarell`
 - [ ] `gphoto2`
 - [ ] `glm`
 - [ ] `bs2b`
 - [ ] `mda_vst`
 - [ ] `gogo_no_coda`
 - [ ] `vorbis_tools`
 - [ ] `handbrake*`
 - [ ] `mplayer`
 - [ ] `smtube`
 - [ ] `mtr`
 - [ ] `minicom`
 - [ ] `wget`
 - [ ] `verilator`
 - [ ] `fxload`
 - [ ] `help2man*`
 - [ ] `bin86`
 - [ ] `binutils`
 - [ ] `gcc`
 - [ ] `gphotofs`
 - [ ] `sshfs_fuse`
 - [ ] `bezilla`
 - [ ] `links`
 - [ ] `links`
 - [ ] `lynx`
 - [ ] `robinhood`
 - [ ] `shared_mime_info`
 - [ ] `zsh`
 - [ ] `smplayer`
 - [ ] `autoconf213`

**Comment by waddlesplash** [comment]
cc @diversys @korli since you guys wrote a lot of the recipes on this list AFAICT.

**Comment by mmuman** [comment]
I usually just add it regardless when writing a recipe for completeness… and also just in case the gcc2 port becomes too complicated that it should be abandoned. But yeah I suppose it's not that much needed.

**Comment by waddlesplash** [comment]
@mmuman If the GCC2 port is not needed, then architectures will be reversed and x86 will be the primary arch anyway. So yeah, don't add it.

**Comment by korli** [comment]
Care to share which 'check' you actually run?
I find this list not very helpful, there is more than "it's not a lib". I agree a comment would help to clarify anyway.
For instance an app which builds correctly with gcc2, but more extensively (ie against more libraries on gcc4). Pkgconfig needs both architectures, gnulib is a lib, or? I wouldn't say I wrote "a lot of" these recipes on this list, they come more from GCI IMO.
It would be interesting to automate the check, ie all recipes with dependencies on QT should be marked broken on gcc2, for instance smplayer. 
Though I'm a bit worried that such information is taken as primary source for what to include in a repository. There are poor quality applications or ports we probably don't want included.

**Comment by Begasus** [comment]
Wanted to have a look at glm (header only package) but looking at their website it reports that support for gcc is >= 4.7, looking at some work from fedora they have a patch to fix cmake (need to check that out here) install, so I was thinking about making the package "any", but after seeing the remark on the gcc version I think x86_gcc2 should be marked broken?
