### ISSUE TITLE
Add Mesa 18.x recipe

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2839]
Add recipe and patches for Mesa 18.x stable build. 
Tested: Built Mesa 18.1.5 with GCC 7.3 on Haiku x86_64 and x86_gcc2.

**Comment by kenmays** [comment]
Cancel for now.. Request satisfied by Mesa 17.1.10 deployment (hrev52138+).
Can reopen after R1 beta release.

**Comment by extrowerk** [comment]
Please, watch a github introduction video and/or study the user guides and create a pull request with your changes.

**Comment by kenmays** [comment]
Recipe built and will PR soon.

**Comment by kenmays** [comment]
Closed

**Comment by kenmays** [comment]
Going to hold this off until Mesa 18.2.1 release.

**Comment by kenmays** [comment]
Setting up Mesa 18.1 buildout.
Ref: https://github.com/kenmays/haikuports/tree/Mesa-18.1.5

**Comment by kenmays** [comment]
NOTE: I closed this ticket since the Mesa 17.1.10 update satisfied Y2018 3D FOSS porting projects to Haiku.
