### ISSUE TITLE
test fails for libXdmcp

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#2841]

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/2840

**Comment by Begasus** [comment]
From gcc2:
FAIL: Array
===========

FAIL Array (exit status: 224)

From x86
FAIL: Array
===========

runtime_loader: /sources/libXdmcp-1.1.2/.libs/libXdmcp.so.6.0.0: Troubles relocating: Symbol not found
FAIL Array (exit status: 4)

**Comment by alaviss** [comment]
Is there any `test-suite.log` file around that you can provide?

**Comment by Begasus** [comment]
Content of the test-suite.log is posted above

**Comment by Begasus** [comment]
Was missing libnetwork for the test.
