### ISSUE TITLE
Audacious crashes on exit

### ISSUE THREAD

**Issue by thaflo** [haikuports/haikuports#2843]
EDIT: Added debug report
[Debugger-1007-debug-03-03-2018-09-27-15.txt](https://github.com/haikuports/haikuports/files/2217211/Debugger-1007-debug-03-03-2018-09-27-15.txt)

Every time I close Audacious (which is a app I'm happy with) it crashes.
The Core Debug is 63 MB big, so I can't upload it here.
For any further help I'm here to assist.

**Comment by extrowerk** [comment]
Summon @diversys

**Comment by diversys** [comment]
Yes, it' a known issue with some Qt5 apps.

The debug report is a Debugger crash which should be reported to Haiku's Trac.

**Comment by diversys** [comment]
I mean that the Debugger crash report should be moved there, not Audacious.

**Comment by extrowerk** [comment]
I got it, but doesn't this happens because something in Qt or in QtHaikuPlugin?

**Comment by diversys** [comment]
Sure, but as I said it is a known issue that hasn't been fixed yet.

**Comment by threedeyes** [comment]
Fixed in 5a347036863fb062734594b651d81121c179ef6c
