### ISSUE TITLE
QuiteRSS: tiny fonts for contents view

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#2854]
The contents view shows with a very small font size:

![image](https://user-images.githubusercontent.com/1316513/43151592-f9c26040-8f74-11e8-9eeb-68987321e92e.png)

You can zoom in a bit with CTRL+mouse wheel, but not enough.

**Comment by humdingerb** [comment]
Turns out, in the Options the default font size is 1...
Would be nice if the defaults were bigger, but if that's too much of a hassle, feel free to close this issue.

**Comment by diversys** [comment]
This should be fixed in https://github.com/threedeyes/qthaikuplugins/commit/8f52eaae0b6a01da1017dae45a7293f54f0b3e34.
Could you try to build qthaikuplugins recipe from master to check?

**Comment by humdingerb** [comment]
That does indeed fix it! \o/

BTW, the path of `QuiteRss.ini` is needlessly deep:
`/boot/home/config/settings/QuiteRss/QuiteRss/QuiteRss/QuiteRss.ini`

**Comment by alaviss** [comment]
@humdingerb 
> BTW, the path of `QuiteRss.ini` is needlessly deep:
> `/boot/home/config/settings/QuiteRss/QuiteRss/QuiteRss/QuiteRss.ini`

I think this should be moved to it's own issue :)

**Comment by diversys** [comment]
BTW, could you please upload a new screenshot to https://depot.haiku-os.org/quiterss ? :)

**Comment by humdingerb** [comment]
>BTW, could you please upload a new screenshot to https://depot.haiku-os.org/quiterss ? :)

Done.
I'd like to push an improved description for QuiteRSS. Shall I bump the revision, or do you plan a new version soon anyway (maybe for #2859)?

**Comment by diversys** [comment]
It seems that you need to upload an icon and a screenshot to x86_64 repo to automatically sync it with x86_gcc2 repo. Otherwise you need to do it for both repos.

**Comment by humdingerb** [comment]
Added icon, screenshots and German localization to 64bit repo as well.
