### ISSUE TITLE
Using sonames as provides in recipes ...

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#2857]
Wanted to get a discussion started to get some mutual agreement on using sonames in recipes ...
Been looking into updating some of the X11 libs/protocols, for the protocols it isn't a problem (although I see configure sometimes telling me it finds (for instance) XINEMARAMA while the provides never mention the capitalized name for it, for the libraries it's another story, sometimes you see a deppendency for "libx11" sometimes for "libX11", the provides for libX11 mention the capitalized "X"
Getting on par with the provides for other libraries for instance would mean using (example) in provides: 
```
lib:libXau instead of lib:libxau
```
comments welcome :)

**Comment by alaviss** [comment]
My personal opinion is everything lowercase since they require less effort to type :smile:

I think in the end it's up to contributors' own taste, as long as it's not `libSoMeThInG`. I remember reading somewhere that `SONAME` is preferred, but I can't seem to find it.

**Comment by Begasus** [comment]
It shouldn't be to the contributor's taste, having one rule here would look better in all the recipes ... (imho), otherwise you keep having different provides/requires defined ...

**Comment by alaviss** [comment]
I don't think we need a hard requirement for this. The amount of libs required are usually small enough for it not to matter. It's the overall layout that we should care about.

If we really want a policy, then it should match the `SONAME` of the provided library. We already got `compat` version from it, so there's no reason not to do so with the name.

**Comment by fbrosson** [comment]
I'm also not very fond of making it a hard requirement.

How about making it a _hard requirement_ **_only_** for _new_ recipes, and a _strong recommendation_ for _existing_ recipes?

Otherwise we can make it a simple recommendation, in all cases.

**Comment by scottmc** [comment]
I recall running into this issue when trying to get the SDL libraries to work.  Looks like it's still libSDL

**Comment by pulkomandy** [comment]
On Tue, Jul 24, 2018 at 06:43:33PM +0000, Scott McCreary wrote:
> I recall running into this issue when trying to get the SDL libraries to work.  Looks like it's still libSDL

But since then haikuporter has been patched and is case insensitive. So
there is no technical reason to prefer one style or another now.

However, it is technically possible on the soname side to have two
independant libraries that differ only in case (libGL and libgl for
example). So, just in case this ever happens, we should use the correct
case everywhere. But, let's just migrate slowly as we change recipes,
there is no hurry to fix everything.

**Comment by Begasus** [comment]
It doesn't have to happen overnight, just wanted to light a balloon here :) On that note, a hard requirement isn't what I'm looking for also, just something we could look into for the future (and could get a slow start already now) :)

**Comment by alaviss** [comment]
I guess we can now close this?

**Comment by Begasus** [comment]
yep :)
