### ISSUE TITLE
super_transball hangs during intro splash screen

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2858]
Super Transball 2 (ref: http://www.braingames.getput.com)
1. Issue during x86_gcc2 package installation from HaikuDepot app (requires fix in recipe (see: #2784))
2. hangs at the intro splash screen or immediately exits without a crash output.

**Comment by alaviss** [comment]
Do you have a Debug Report that you can share? Thanks!

**Comment by kenmays** [comment]
Actually, it either hangs at the intro screen or exits without a crash output.

**Comment by extrowerk** [comment]
Does running it in Terminal gives any hint whats wrong?

**Comment by kenmays** [comment]
extrowerk - No terminal output. Can you confirm a working condition on your end?

**Comment by kenmays** [comment]
Debug report: [stransball2-548-debug-08-08-2018-17-08-32.report.txt](https://github.com/haikuports/haikuports/files/2271219/stransball2-548-debug-08-08-2018-17-08-32.report.txt)

**Comment by extrowerk** [comment]
Please create a haiku ticket.
A program could crash but should not trigger a KDL.

**Comment by kenmays** [comment]
KDL issue resolved in hrev52195.

**Comment by korli** [comment]
KDL issue submitted https://dev.haiku-os.org/ticket/14339

**Comment by kenmays** [comment]
On my x86 system, the KDL issue no longer appears after hrev52195-52201. Although, I got a KDL when I tested hrev52187 x86_64 for both the intel_extreme and radeon_hd drivers. NOTE: This is different from my gcc2 testing as that KDL happened during desktop initialization after the Haiku splash screen - not during an application launch triggering it.

**Comment by kenmays** [comment]
This one is due to a SDL conflict issue. The app is fine. Will push bug to SDL.

**Comment by kenmays** [comment]
super_transball-2.1.5-5 on hrev53340+2 x86. Boot screen still hangs. No KDL.

**Comment by Begasus** [comment]
super_transball_x86? there is no secondary Architecture enabled?

**Comment by Begasus** [comment]
Looks ok here ... 
![Super-Transball2](https://user-images.githubusercontent.com/16057090/62740549-77104280-ba38-11e9-808a-defa627b15f1.png)

**Comment by kenmays** [comment]
Tested on both **x86_gcc2** and **x86_64**. **Starting from GUI menu** - same results on both systems. Trying in OpenTerminal with x86 2nd arch on x86_gcc2 (x86) - same results. (update: **hrev53242 x86_64, hrev52353 x86_64,  hrev52353 x86_gcc2** tested,). Recompiled on GCC 8.3.0. Compiles OK. Same issue.

**Comment by Begasus** [comment]
Checked on x86_gcc2 and x86_64 (Beta1) before and after running "pkgman full-sync", still seems to run ok here, did you press the space bar after the initial screen?

**Comment by kenmays** [comment]
Thanks. **Pressing the space bar in the game's active window did resolved it.** Didn't seem to resolve pressing any other keys.
![stransball2-test](https://user-images.githubusercontent.com/5168719/62824366-8636e380-bb51-11e9-858d-6c4e8250f4d3.png)
