### ISSUE TITLE
python vendor-packages directory needs reviewed

### ISSUE THREAD

**Issue by kallisti5** [haikuports/haikuports#286]
I'm not sure if storing the sitepackage paths as references to /packages including python version is a good idea... it could make python modules tightly tied to python version / revision. Not sure though as i'm not a python guy :-)

```
python -c "import site; print(site.getsitepackages())"
['/packages/python-2.7.10-1/.self/non-packaged/lib/python2.7/site-packages', '/packages/python-2.7.10-1/.self/lib/python2.7/vendor-packages']
```

**Comment by korli** [comment]
I must miss something on this issue: I can't find a single reference to /packages in python modules packages (I tested requests and setuptools).

**Comment by Sylvain78** [comment]
I observe that python-config and python3-config differ for '--prefix' :
python-config --prefix --> /packages/python-2.7.18-2/.self
python3-config --prefix -->/boot/system

But i found this workaround :
python3 -c "import site; print(site.getsitepackages()[0])" | cut -d'/' -f-4  --> /packages/python3-3.7.12-1/.self

I hope it can help you , let me know.
