### ISSUE TITLE
Missing symbol Qbitorrent

### ISSUE THREAD

**Issue by SeanCollins** [haikuports/haikuports#287]
gethostbyname_r symbol missing in latest nightly

**Comment by pulkomandy** [comment]
It was an extension from libbind, and non-standard, and our update to netresolv removed it. Most software should be able to detect this, so al that should be needed is recompiling it.

**Comment by humdingerb** [comment]
There's no qbittorrent recipe, correct me if I'm wrong. So not really a haikuports issue.

**Comment by waddlesplash** [comment]
@humdingerb Ah, you're right, I forgot there is no qBittorrent recipe yet. We should create one then.

**Comment by diversys** [comment]
Fixed in b89b8e and hrev49551.
