### ISSUE TITLE
SSH reverse-tunneling broken

### ISSUE THREAD

**Issue by tunetracker** [haikuports/haikuports#288]
Was previously using SSH for reverse tunneling from recent hrevs (including 49137, 49172..) into my support laptop (which runs an older 48169, but shouldn't matter ?).

With newer hrevs (I tried 49523) I get an error: "No address associated with hostname"
Running ssh in verbose (-vvv) mode I see one of the last executed functions is client_request_forwarded_tcpip() in client_loop.c

(I'd say the code ends up in channel_rfwd_bind_host() in channels.c, but I'm not familiar with the ssh code so take with a grain of salt)

Digging a little I see the OpenSSH port moved from 6.7 to 6.9 and some vulnerabilities were closed or something. So I tried tweaking ssh_config, especially with the options related to hostname resolution, DNS lookup ..etc, but for some of them I get the "_res" error, which I thought was fixed by pulkomandy in a recent hrev. Anyway, I'm not sure if this is a haikuport error or a haiku error with the need to file a ticket there instead.

Using SSH normally/directly (not reverse-tunneling) seems to still work as before.

**Comment by tunetracker** [comment]
Meant to say,
I get the "_res: unsupported in multi-threaded applications" gethostbyname error.

**Comment by diversys** [comment]
Related to #272

**Comment by pulkomandy** [comment]
We should probably remove that __res API from Haiku completely, so these apps fail to build/run, instead of crashing in-flight when trying to use it.

**Comment by tunetracker** [comment]
Sounds good to me 8-)   A lot of pain with the buildbots (?) for a few days, and after that any __res usage would be gone for good.. Might also help when new ports are introduced in the future I guess.
+1

**Comment by tunetracker** [comment]
Something potentially relevant to __res:

CommandCenter tends to crash when I'm surfing in W+ at the same time as it's doing network time sync (loading the Time preflet as an add-on).. Maybe that will go away when Time no longer uses __res in the future ? Or maybe the problem is not related to Time being thread unsafe and I should file a ticket over at Haiku ? Please advise.


KERN: vm_soft_fault: va 0x719a0000 not covered by area in address space
KERN: vm_page_fault: vm_soft_fault returned error 'Bad address' on fault at 0x719a0844, ip 0x143481c, write 0, user 1, thread 0x4562
KERN: vm_page_fault: thread "(add-on)ntp_update_time" (17762) in team "CommandCenter" (602) tried to read address 0x719a0844, ip 0x143481c ("libnetwork.so_seg0ro" +0x1781c)
KERN: debug_server: Thread 17762 entered the debugger: Segment violation
KERN: stack trace, current PC 0x143481c  nsdispatch + 0xe4:
KERN:   (0x71945ff8)  0x142f811  gethostbyname_internal + 0x305
KERN:   (0x71946048)  0x142f4a9  gethostbyname + 0x79
KERN:   (0x71946078)  0x5cf11c  ntp_update_time__FPCcPPCcPl + 0x24
KERN:   (0x71946188)  0x1903f04  thread_func__25NetworktimeprefletAsAddonPv + 0x290
KERN:   (0x719462b8)  0x20d3c7f  thread_entry + 0x23

**Comment by pulkomandy** [comment]
The __res crash is very easy to spot in stack traces (it is an assert with a clear message). So this is not related to it. Please open an issue at Haiku with steps to reproduce.

**Comment by tunetracker** [comment]
Change of situation... I've reverted to the openssh package that was present in the previous hrev, and things are still broken:


pkgman install openssh-6.6p1-1-x86_gcc2.hpkg 
(..)
The following changes will be made:
  in system:
    upgrade package openssh to 6.6p1-1 from local file
Continue? [y/n] (y) : y
(..)
[system] Done.

ssh -V
OpenSSH_6.6p1, OpenSSL 1.0.0s 11 Jun 2015

ssh (..) N -R 2210:localhost:22 (..)
connect_to localhost: unknown host (No address associated with hostname)

So what else has change between 49172 and 49523.. There were many changes in haiku's networking code right ? Maybe the OpenSSH port needs a new recipe/patch to adapt to a new way to call gethostbyname() ? (just a random example) Or maybe it's an actual regression in Haiku, and I should file a ticket there, with the same details I posted here ? What's your take pulkomandy :-)

**Comment by diversys** [comment]
This was probably fixed in hrev49619.

**Comment by tunetracker** [comment]
No change in hrev49623 : "connect_to localhost: unknown host (No address associated with hostname)"

I'll file a ticket against Haiku though, given the change in assessment outlined in my previous comment.

Guess this haikuport ticket should be closed as invalid since it's not the openssh port that's at fault but Haiku
