### ISSUE TITLE
rssavers fails build on x86_64

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2881]
rssavers-0.2
========
Passes on Haiku hrev52146 x86_gcc2 w/GCC 2.95.3.
Tested on: Haiku hrev52146 x86_64 w/GCC 7.3.0
Debug file:
[rssaver_debug_x86_64.txt](https://github.com/haikuports/haikuports/files/2250415/rssaver_debug_x86_64.txt)

**Comment by extrowerk** [comment]
That's a build log.

**Comment by kenmays** [comment]
Fixed C++ code deprecation issues. Doesn;t affect gcc3 packaging so this is more of an enhancement - not bug. Resolved.

**Comment by extrowerk** [comment]
Now can you explain this?
I see no pull request and no commits, so if the package had problem on x86_64, then it is still exists.

**Comment by kenmays** [comment]
Not a bug (since there is no x86_64 package existing at the moment or with the rssaver-0.2 code itself).
Need to work on this as an enhancement ticket.
