### ISSUE TITLE
Handbrake: update FFmpeg dependency

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#2903]
Tested on hrev52201 x86_64, handbrake won't install due to older FFmpeg dependency.

**Comment by alaviss** [comment]
Could you try to bump `REVISION` of Handbrake and build it? If everything works, please open a PR. Thanks!

**Comment by kenmays** [comment]
Tested in hrev52204 x86_64, this is what is generated now:
/bin/gcc -std=gnu99 -pipe -fmessage-length=0 -Wall -g0 -O3 -lnetwork -liconv -DUSE_LIBAV_AAC -D__LIBHB__ -DUSE_PTHREAD -DSYS_HAIKU -DHAS_STRERROR_R -DARCH_X86_64 -I./libhb/ -I./contrib/include -I/system/develop/headers/libxml2 -c ../libhb/encavcodec.c -o libhb/encavcodec.o
../libhb/encavcodec.c: In function 'encavcodecInit':
../libhb/encavcodec.c:238:27: error: 'CODEC_FLAG_QSCALE' undeclared (first use in this function); did you mean 'AV_CODEC_FLAG_QSCALE'?
         context->flags |= CODEC_FLAG_QSCALE;
                           ^~~~~~~~~~~~~~~~~
                           AV_CODEC_FLAG_QSCALE
../libhb/encavcodec.c:238:27: note: each undeclared identifier is reported only once for each function it appears in
../libhb/encavcodec.c:281:27: error: 'CODEC_FLAG_GLOBAL_HEADER' undeclared (first use in this function); did you mean 'AV_CODEC_FLAG_GLOBAL_HEADER'?
         context->flags |= CODEC_FLAG_GLOBAL_HEADER;
                           ^~~~~~~~~~~~~~~~~~~~~~~~
                           AV_CODEC_FLAG_GLOBAL_HEADER
../libhb/encavcodec.c:285:27: error: 'CODEC_FLAG_GRAY' undeclared (first use in this function); did you mean 'AV_CODEC_FLAG_GRAY'?
         context->flags |= CODEC_FLAG_GRAY;
                           ^~~~~~~~~~~~~~~
                           AV_CODEC_FLAG_GRAY
../libhb/encavcodec.c:305:31: error: 'CODEC_FLAG_PASS1' undeclared (first use in this function); did you mean 'AV_CODEC_FLAG_PASS1'?
             context->flags |= CODEC_FLAG_PASS1;
                               ^~~~~~~~~~~~~~~~
                               AV_CODEC_FLAG_PASS1
../libhb/encavcodec.c:344:34: error: 'CODEC_FLAG_PASS2' undeclared (first use in this function); did you mean 'CODEC_FLAG_PASS1'?
             context->flags    |= CODEC_FLAG_PASS2;
                                  ^~~~~~~~~~~~~~~~
                                  CODEC_FLAG_PASS1
../libhb/module.rules:12: recipe for target 'libhb/encavcodec.o' failed
make: *** [libhb/encavcodec.o] Error 1

**Comment by pulkomandy** [comment]
This looks not too hard to fix by adding the missing AV_ prefix to the constants.

**Comment by alaviss** [comment]
Maybe we should update our Handbrake, there's version 1.1.1 around now

**Comment by alaviss** [comment]
@kenmays Then I suggest bumping our handbrake than trying to patch it.

**Comment by scottmc** [comment]
Keep in mind when making patches, you should try to make them such that you can upstream them.  That is, your patches won't break the app on other platforms.  By upstreaming it make it so that it will usually just work on the next version from upstream.  And then follow thru by sending your patch upstream.  Sometimes they get accepted right away, other times it might take years. ;)

**Comment by kenmays** [comment]
Fixed in: https://github.com/haikuports/haikuports/pull/2927
