### ISSUE TITLE
Request: X11

### ISSUE THREAD

**Issue by Symbian9** [haikuports/haikuports#2906]
There are many useful software that could be ported to Haiku if firstly add working X11 libs.

### Related

- Request: AzPainter - https://github.com/haikuports/haikuports/issues/2499

**Comment by waddlesplash** [comment]
The project is Haiku, not Haiku OS.

**Comment by Begasus** [comment]
I had been trying to build XSDL a while back, didn't got any further at that time

**Comment by extrowerk** [comment]
I wote to close this issue. For X server one can use http://www.jcraft.com/weirdx/ I see no point introducing X11 with all of the consequences of using an old unsupported version.

**Comment by Symbian9** [comment]
> For X server one can use http://www.jcraft.com/weirdx/

Is there any showcase of X11 app running under Haiku OS via WeirdX?

**Comment by extrowerk** [comment]
> > For X server one can use http://www.jcraft.com/weirdx/
> 
> Is there any showcase of X11 app running under Haiku OS via WeirdX?

I was able to get firefox forwarded trough ssh to Haiku, but i don't have the screenshot anymore. Why is it important?

**Comment by Symbian9** [comment]
> but i don't have the screenshot anymore. Why is it important?

Because I just want to know is there any workaround solution to launch X11 apps on Haiku OS.

**Comment by threedeyes** [comment]
> Because I just want to know is there any workaround solution to launch X11 apps on Haiku OS.

I built a fully working XSDL, but does it make sense to make a recipe for haikuports?

![screenshot40](https://user-images.githubusercontent.com/2559260/112318108-6b9a8980-8cf8-11eb-946b-5cbc1f2c369e.png)

**Comment by pulkomandy** [comment]
I think it could be useful until we get native GTK? Or for remote connection (if I can connect to my Linux server to run some Linux apps this way, for me it's a better solution than a VM)

I think the X11 server itself is nice to have, but apps in Haikuports should not depend on it.

**Comment by X547** [comment]
> I think the X11 server itself is nice to have, but apps in Haikuports should not depend on it.

I think it may depend if there are no better solution. When native port will be done, X11 dependency can be dropped.

**Comment by Symbian9** [comment]
> I think the X11 server itself is nice to have, but apps in Haikuports should not depend on it.

@pulkomandy, Is there a way to package X11 app for Haiku with bundled X11 server?

Something like AppImage for Linux or DMG for macOS.

**Comment by pulkomandy** [comment]
That way of packaging things is stupid and we won't do it. It makes apps larger and it makes it impossible to manage updates and bugfixes to the various components in an app.

**Comment by Symbian9** [comment]
> I think it could be useful until we get native GTK?

@pulkomandy, But what about such apps that are depends only on X11R6, without any dependencies to GTK?

- https://github.com/Symbian9/azpainter

**Comment by X547** [comment]
> But what about such apps that depends only on X11R6, without any dependencies to GTK?

I feel I heard about xlib implementation without X server and X11 protocol. It is better solution that waste less resources and provide more native experience.

**Comment by waddlesplash** [comment]
> But what about such apps that depends only on X11R6, without any dependencies to GTK?

X11 is being deprecated even on Linux, it would be better to migrate such applications to SDL2 anyway.

**Comment by waddlesplash** [comment]
@threedeyes, how advanced is your GTK port? Would it not make more sense just to get a WIP of that in-tree instead?

**Comment by threedeyes** [comment]
> how advanced is your GTK port? Would it not make more sense just to get a WIP of that in-tree instead?
It's hard to call it a port - just a little experiment. I just insert native window creation and surface rendering calls right into the Broadway backend code. The mouse works, but the keyboard doesn't. 
I wanted to write a GDK backend from scratch, but that's a lot of code and so hard. The smallest available GDK bakend has about 1 megabyte of source code. The depricated bakend for MIR is only about 500 kilobytes, but it's still a lot.

**Comment by waddlesplash** [comment]
Maybe it would make sense to write a SDL2 backend for GDK. It would probably be appreciated by the community at large, and we might get help from other people, and it has a much better chance of being upstreamed. It would also be able to be developed on Linux et al. before we try to bring it up on Haiku. The removed Mir backend looks like a good basis to start with indeed.

**Comment by threedeyes** [comment]
> Maybe it would make sense to write a SDL2 backend for GDK.

I can make a native backend for x11 - it's very easy.

**Comment by waddlesplash** [comment]
Yes, but using GDK apps inside an X11 window is janky; and even on Linux, X11 is pretty bad these days with all the extensions. Having an SDL2 backend would mean native clipboard integration, IME integration, etc. etc.

**Comment by waddlesplash** [comment]
I would actually be willing to donate money towards having a developer who is an expert in SDL2 and/or GDK to work on that, and I bet members of broader communities would too.

**Comment by X547** [comment]
> Having an SDL2 backend

SDL2 backend for X.Org or GTK? I think that native backend for GTK is preferred.

**Comment by X547** [comment]
> It's hard to call it a port - just a little experiment. I just insert native window creation and surface rendering calls right into the Broadway backend code. The mouse works, but the keyboard doesn't.

Why not publish this work? It is better than running GTK 3+ applications in browser or X11 emulated desktop window. It provides window integration.

**Comment by waddlesplash** [comment]
> SDL2 backend for X.Org or GTK? I think that native backend for GTK is preferred.

For GTK.

A native backend is preferred but it will be a ridiculous amount of work to write, and will not be fun to maintain in the slightest. GTK applications always, perpetually, feel like second or third class citizens on every platform except for GNOME itself. I don't think we can avoid that; so how much worse will an SDL2 port make things instead of a "native" port? Probably not very much, and they may make the workload sustainable.

**Comment by threedeyes** [comment]
Exactly. For me, writing code in pure C is a mockery. Especially the GTK itself is horrible on the inside, which makes the task even more difficult and brings no fun to coding.

**Comment by Symbian9** [comment]
> > SDL2 backend for X.Org or GTK?
>
> For GTK. 

For X.Org too! As it will allows to use X11 software written in *pure Xlib (libX11)*

- See: https://github.com/haikuports/haikuports/issues/2499

**Comment by threedeyes** [comment]
> For X.Org too! As it will allows to use X11 software written in pure Xlib (libX11)

Special for you: )))
![screenshot45](https://user-images.githubusercontent.com/2559260/112460486-ae1c9e80-8daa-11eb-928f-e63a18c631e7.png)

**Comment by Symbian9** [comment]
> Special for you: )))

WOW! Thanks!

So, its could be packaged for Haiku with your patches, right?

**Comment by waddlesplash** [comment]
I've been experimenting with a different approach: reimplementing Xlib on top of the Haiku APIs (https://github.com/waddlesplash/BeXlib). Enough things work that AzPainter starts up, and basic mouse and keyboard input works:

![image](https://user-images.githubusercontent.com/2175324/145481086-78778668-02d1-48d1-bd27-9f123c085fb1.png)

Quite a lot of things are still missing though, and this is a ways off from being usable.

**Comment by Symbian9** [comment]
> Enough things work that AzPainter starts up, and basic mouse and keyboard input works:

@waddlesplash, WOW! Great work! Keep it going, please!

**Comment by extrowerk** [comment]
Simply crazy. @waddlesplash just shake the grund even further!

**Comment by X547** [comment]
How about libxcb?

**Comment by waddlesplash** [comment]
XCB is much less pleasant to work with, and not a lot of things use it.

**Comment by X547** [comment]
> Enough things work that AzPainter starts up, and basic mouse and keyboard input works:

Bitmaps are not working yet?

**Comment by Symbian9** [comment]
> Bitmaps are not working yet?

Probably, it was issue not in bitmaps, but in AzPainter's hardcoded data paths instead:

- https://twitter.com/app4soft/status/1469070002317836292

**Comment by waddlesplash** [comment]
Yes, bitmaps are already working; the main views are all drawn with them in AzPainter. Bitmap cursors are also partially working (they have no transparency yet however.)

**Comment by X547** [comment]
```
runtime_loader: /boot/system/lib/libXext.so.6.4.0: Could not resolve symbol '_XUnlockMutex_fn'
```

**Comment by X547** [comment]
> Enough things work that AzPainter starts up, and basic mouse and keyboard input works:

How did you run it? I have undefined symbol `XAddExtension`.

**Comment by waddlesplash** [comment]
Xlibe and AzPainter are now in the repos.

**Comment by Symbian9** [comment]
WOW! @waddlesplash, Thank You so much!
