### ISSUE TITLE
Qt browsers (QupZilla, Otter) hangs loading pages after recent Qt library update

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#2917]
After last update from the Qt 5.11 package (x86_gcc2 version), I found very frecuents hangs in browsers that rely on that component (like QupZilla, Otter, etc.).   Usually, the loading process of the page get interrupted, and never load completely, unless push several times the "refresh" button.

Starting the browser from Terminal, I see several errors like this:
/boot/system/apps/Otter-Browser> Otter-Browser 
Empty filename passed to function
QSocketNotifier: Invalid socket 0 and type 'Read', disabling...
QSocketNotifier: Invalid socket 0 and type 'Read', disabling...
QSocketNotifier: Invalid socket 0 and type 'Read', disabling...
QSocketNotifier: Invalid socket 0 and type 'Read', disabling...
QSocketNotifier: Invalid socket 0 and type 'Write', disabling...
QSocketNotifier: Invalid socket 0 and type 'Read', disabling...
QSocketNotifier: Invalid socket 0 and type 'Read', disabling...
QSocketNotifier: Invalid socket 0 and type 'Write', disabling...
QSocketNotifier: Invalid socket 0 and type 'Read', disabling...
QSocketNotifier: Invalid socket 0 and type 'Read', disabling...
QSocketNotifier: Invalid socket 0 and type 'Read', disabling...
QSocketNotifier: Invalid socket 0 and type 'Read', disabling...
QSocketNotifier: Invalid socket 0 and type 'Read', disabling...
QSocketNotifier: Invalid socket 0 and type 'Read', disabling...

**Comment by threedeyes** [comment]
Fixed in 4a5a235ae8d49c88321c3b61f6bcee06539d255c
