### ISSUE TITLE
Fix Qt5WebKit

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#294]
Qt5WebKit build is totally busted.

**Comment by waddlesplash** [comment]
@threedeyes -- Can you have a look at this, or at least get me your Qt5WebKit patches?

**Comment by threedeyes** [comment]
2015-10-11 9:31 GMT+10:00 waddlesplash <notifications@github.com>:

> @threedeyes <https://github.com/threedeyes> -- Can you have a look at
> this, or at least get me your Qt5WebKit patches?
>

I will try to add my patches for Qt5 soon.

**Comment by threedeyes** [comment]
Fixed at #9a1a62ba8488986ec5434a51028b65aad7424122
