### ISSUE TITLE
Please update to uriparser 0.8.6

### ISSUE THREAD

**Issue by hartwork** [haikuports/haikuports#2941]
Hi!

Just a quick heads up that [uriparser 0.8.6](https://github.com/uriparser/uriparser/releases/tag/uriparser-0.8.6) with bugfixes has been released.

Thanks for updating!

**Comment by hartwork** [comment]
Overlooked 86af4ad56233fc9b7abbc5f9f48afb8eab5ad19d. Sorry for the noise and kudos for the quick update.

**Comment by scottmc** [comment]
@hartwork thanks for letting us know about update.
