### ISSUE TITLE
Failed to build OpenCV342_x86

### ISSUE THREAD

**Issue by Lan72** [haikuports/haikuports#2946]
```
~> hp opencv342_x86
Checking if any package-infos need to be updated ...
        updating dependency infos of opencv342_x86-3.4.2
        updating dependency infos of opencv_x86-3.4.1
Looking for stale dependency-infos ...
----------------------------------------------------------------------
media-libs::opencv342_x86-3.4.2
        /boot/home/haikuports/media-libs/opencv/opencv342-3.4.2.recipe
----------------------------------------------------------------------
Skipping download of source for opencv-3.4.2.tar.gz
Validating checksum of opencv-3.4.2.tar.gz
Unpacking source of opencv-3.4.2.tar.gz
Initialized empty Git repository in /boot/home/haikuports/media-libs/opencv/work-x86-3.4.2/sources/opencv-3.4.2/.git/
Fetching package for lib:libgfortran_x86 >= 3.0.0 ...
*** Failed to find a match for "lib:libgfortran_x86 >= 3.0.0": Name not found
Fetching package for opencv342_x86 == 3.4.2 base ...
*** Failed to find a match for "opencv342_x86 == 3.4.2 base": Name not found
Error: unable to resolve required packages for build for opencv342_x86-3.4.2
Error: dependency-infos:
Error: /boot/home/haikuports/repository/opencv342_x86-3.4.2.DependencyInfo
Error: /boot/home/haikuports/repository/opencv342_x86_debuginfo-3.4.2.DependencyInfo
Error: boot/home/haikuports/repository/opencv342_x86_devel-3.4.2.DependencyInfo
Error: repositories:
Error: [u'/boot/home/haikuports/packages', '/boot/system/packages']
Error:
```
I have libgfortran_x86 (libgfortran.so.4.0.0), since I have installed gcc_x86_fortran-7.3.0_2018_05_01-3-x86_gcc2.hpkg. 
As for the second requirement, it is completely incomprehensible to me.

Tell me, please, what could be the problem?

**Comment by extrowerk** [comment]
Recipe author here, hi!
Something strange, but i have to say, i never tested it on x86, thus marked as untested.

* I can't say what's up with fortran, as opencv doesn't defines it as direct requiment. I assume you have a leftover package before the GCC change, that's why it tries to pull the 3.0.0. You can analyze the dependency graph somehow.
* OpenCV needing itself is also strange, it built just fine on 64 bit.

Please feel free to hunt the bugs down and report back if you stucked.

**Comment by Lan72** [comment]
Yes, strange demands were made because of obsolete packages of lapack_x86 and lapack_x86_devel, which were in /boot/home/haikuports/packages.
I removed them, and the requirements regarding "lib:libgfortran_x86 >= 3.0.0" and "opencv342_x86 == 3.4.2 base" ceased.

But now there is a new requirement for "cmd:f2py2":
~> hp opencv342_x86
Checking if any package-infos need to be updated ...
Looking for stale dependency-infos ...
----------------------------------------------------------------------
media-libs::opencv342_x86-3.4.2
        /boot/home/haikuports/media-libs/opencv/opencv342-3.4.2.recipe
----------------------------------------------------------------------
Skipping download of source for opencv-3.4.2.tar.gz
Skipping checksum validation of opencv-3.4.2.tar.gz
Skipping unpack of opencv-3.4.2.tar.gz
Cleaning up temporary directories ...
Fetching package for cmd:f2py2 ...
*** Failed to find a match for "cmd:f2py2": Name not found
Error: unable to resolve prerequired packages for build for opencv342_x86-3.4.2
Error:  dependency-infos:
Error:          /boot/home/haikuports/repository/opencv342_x86-3.4.2.DependencyInfo
Error:          /boot/home/haikuports/repository/opencv342_x86_debuginfo-3.4.2.DependencyInfo
Error:          /boot/home/haikuports/repository/opencv342_x86_devel-3.4.2.DependencyInfo
Error:  repositories:
Error:          [u'/boot/home/haikuports/packages', '/boot/system/packages']
Error:

**Comment by extrowerk** [comment]
Thats numpy, i think.

**Comment by extrowerk** [comment]
any news here?

**Comment by Lan72** [comment]
Yes, there is a problem in the absence of python_numpy and/or python3_numpy under x86 architecture.
They contain and provide "cmd:f2py2".

Trying to build python_numpy_x86  does not lead to anything:
`~> hp python_numpy_x86
Checking if any package-infos need to be updated ...
        python_numpy-1.14.5 is still marked as broken on target architecture
        python_numpy_x86-1.14.5 is still marked as unsupported on target architecture
Looking for stale dependency-infos ...
        removing python_numpy_x86-1.14.5.DependencyInfo
Warning: skipping python_numpy_x86-1.14.5, as it is unsupported on the target architecture.
Error: No version of python_numpy_x86 can be built
~>`

If I add a secondary architecture to the recipe, , building goes, but then ends with an error:
`~> hp python3_numpy_x86
Checking if any package-infos need to be updated ...
        python3_numpy-1.14.5 is still marked as broken on target architecture
        updating dependency infos of python3_numpy_x86-1.14.5
Looking for stale dependency-infos ...
----------------------------------------------------------------------
dev-python::python3_numpy_x86-1.14.5
        /boot/home/haikuports/dev-python/numpy/python3_numpy-1.14.5.recipe
----------------------------------------------------------------------
Skipping download of source for numpy-1.14.5.zip
Validating checksum of numpy-1.14.5.zip
Unpacking source of numpy-1.14.5.zip
Initialized empty Git repository in /boot/home/haikuports/dev-python/numpy/work-x86-1.14.5/sources/numpy-1.14.5/.git/
chroot has these packages active:
        /boot/home/haikuports/packages/bzip2_x86-1.0.6-7-x86_gcc2.hpkg
        /boot/home/haikuports/packages/libpng16-1.6.35-1-x86_gcc2.hpkg
        /boot/home/haikuports/packages/libpng16_x86-1.6.35-1-x86_gcc2.hpkg
        /boot/home/haikuports/packages/openjpeg_x86-2.2.0-1-x86_gcc2.hpkg
        /boot/home/haikuports/packages/setuptools_python3-28.8.0-1-any.hpkg
        /boot/home/haikuports/packages/tar-1.29-3-x86_gcc2.hpkg
        /boot/home/haikuports/packages/zlib-1.2.11-2-x86_gcc2.hpkg
        /boot/home/haikuports/packages/zlib_x86-1.2.11-2-x86_gcc2.hpkg
        /boot/system/packages/bash-4.4.023-1-x86_gcc2.hpkg
        /boot/system/packages/binutils-2.17_2016_07_24-4-x86_gcc2.hpkg
        /boot/system/packages/bzip2-1.0.6-7-x86_gcc2.hpkg
        /boot/system/packages/ca_root_certificates-2018_06_20-1-any.hpkg
        /boot/system/packages/coreutils-8.24-1-x86_gcc2.hpkg
        /boot/system/packages/curl-7.61.1-2-x86_gcc2.hpkg
        /boot/system/packages/diffutils-3.5-2-x86_gcc2.hpkg
        /boot/system/packages/expat-2.2.6-1-x86_gcc2.hpkg
        /boot/system/packages/expat_x86-2.2.6-1-x86_gcc2.hpkg
        /boot/system/packages/file-5.34-1-x86_gcc2.hpkg
        /boot/system/packages/file_data-5.34-1-any.hpkg
        /boot/system/packages/fontconfig-2.12.6-2-x86_gcc2.hpkg
        /boot/system/packages/freetype-2.9-1-x86_gcc2.hpkg
        /boot/system/packages/freetype_x86-2.9-1-x86_gcc2.hpkg
        /boot/system/packages/gawk-4.1.4-2-x86_gcc2.hpkg
        /boot/system/packages/gcc-2.95.3_2017_07_20-2-x86_gcc2.hpkg
        /boot/system/packages/gcc_x86_fortran-7.3.0_2018_05_01-3-x86_gcc2.hpkg
        /boot/system/packages/gcc_x86_syslibs-7.3.0_2018_05_01-3-x86_gcc2.hpkg
        /boot/system/packages/gettext_libintl-0.19.8.1-5-x86_gcc2.hpkg
        /boot/system/packages/giflib6-5.0.5-5-x86_gcc2.hpkg
        /boot/system/packages/giflib6_x86-5.0.5-5-x86_gcc2.hpkg
        /boot/system/packages/git-2.16.4-1-x86_gcc2.hpkg
        /boot/system/packages/grep-2.24-1-x86_gcc2.hpkg
        /boot/system/packages/groff-1.20.1-4-x86_gcc2.hpkg
        /boot/system/packages/gutenprint-5.2.14-1-x86_gcc2.hpkg
        /boot/system/packages/gzip-1.8-2-x86_gcc2.hpkg
        /boot/system/packages/haiku-r1~beta1_hrev52316-1-x86_gcc2.hpkg
        /boot/system/packages/haiku_devel-r1~beta1_hrev52316-1-x86_gcc2.hpkg
        /boot/system/packages/haiku_x86-r1~beta1_hrev52316-1-x86_gcc2.hpkg
        /boot/system/packages/haiku_x86_devel-r1~beta1_hrev52316-1-x86_gcc2.hpkg
        /boot/system/packages/icu-57.1-3-x86_gcc2.hpkg
        /boot/system/packages/icu_x86-57.1-3-x86_gcc2.hpkg
        /boot/system/packages/ilmbase-2.2.1-1-x86_gcc2.hpkg
        /boot/system/packages/ilmbase_x86-2.2.1-1-x86_gcc2.hpkg
        /boot/system/packages/jasper-2.0.14-1-x86_gcc2.hpkg
        /boot/system/packages/jasper_x86-2.0.14-1-x86_gcc2.hpkg
        /boot/system/packages/jpeg-9c-2-x86_gcc2.hpkg
        /boot/system/packages/jpeg_x86-9c-2-x86_gcc2.hpkg
        /boot/system/packages/lcms_x86-2.9-2-x86_gcc2.hpkg
        /boot/system/packages/less-534-1-x86_gcc2.hpkg
        /boot/system/packages/libedit-20180525_3.1-1-x86_gcc2.hpkg
        /boot/system/packages/libffi-3.0.13-2-x86_gcc2.hpkg
        /boot/system/packages/libffi_x86-3.2.1-4-x86_gcc2.hpkg
        /boot/system/packages/libicns-0.8.1-7-x86_gcc2.hpkg
        /boot/system/packages/libicns_x86-0.8.1-7-x86_gcc2.hpkg
        /boot/system/packages/libiconv-1.15-4-x86_gcc2.hpkg
        /boot/system/packages/libpcre2-10.30-1-x86_gcc2.hpkg
        /boot/system/packages/libsolv-0.3.0_haiku_2014_12_22-2-x86_gcc2.hpkg
        /boot/system/packages/libsolv_x86-0.3.0_haiku_2014_12_22-2-x86_gcc2.hpkg
        /boot/system/packages/libwebp-1.0.0-1-x86_gcc2.hpkg
        /boot/system/packages/libwebp_x86-1.0.0-1-x86_gcc2.hpkg
        /boot/system/packages/libxml2-2.9.3-5-x86_gcc2.hpkg
        /boot/system/packages/man-1.6g-6-x86_gcc2.hpkg
        /boot/system/packages/nano-2.9.8-2-x86_gcc2.hpkg
        /boot/system/packages/ncurses6-6.1-1-x86_gcc2.hpkg
        /boot/system/packages/ncurses6_x86-6.1-1-x86_gcc2.hpkg
        /boot/system/packages/nghttp2-1.33.0-1-x86_gcc2.hpkg
        /boot/system/packages/noto-20170920-3-any.hpkg
        /boot/system/packages/noto_sans_cjk_jp-1.004-2-any.hpkg
        /boot/system/packages/openblas_x86-0.3.2-1-x86_gcc2.hpkg
        /boot/system/packages/openblas_x86_devel-0.3.2-1-x86_gcc2.hpkg
        /boot/system/packages/openexr-2.2.1-2-x86_gcc2.hpkg
        /boot/system/packages/openexr_x86-2.2.1-2-x86_gcc2.hpkg
        /boot/system/packages/openjpeg-2.1.2-3-x86_gcc2.hpkg
        /boot/system/packages/openssl-1.0.2p-1-x86_gcc2.hpkg
        /boot/system/packages/openssl_x86-1.0.2p-1-x86_gcc2.hpkg
        /boot/system/packages/perl-5.26.1-2-x86_gcc2.hpkg
        /boot/system/packages/python-2.7.12-1-x86_gcc2.hpkg
        /boot/system/packages/python3_x86-3.6.3-6-x86_gcc2.hpkg
        /boot/system/packages/readline-7.0.3-2-x86_gcc2.hpkg
        /boot/system/packages/readline6-6.3.8-2-x86_gcc2.hpkg
        /boot/system/packages/readline6_x86-6.3.8-2-x86_gcc2.hpkg
        /boot/system/packages/sed-4.2.1-6-x86_gcc2.hpkg
        /boot/system/packages/sqlite-3.24.0.0-1-x86_gcc2.hpkg
        /boot/system/packages/sqlite_x86-3.24.0.0-1-x86_gcc2.hpkg
        /boot/system/packages/tiff4-4.0.9-2-x86_gcc2.hpkg
        /boot/system/packages/tiff4_x86-4.0.9-2-x86_gcc2.hpkg
        /boot/system/packages/unzip-6.10c23-2-x86_gcc2.hpkg
----- Package Info ----------------
header size:                     80
heap size:                      929
TOC size:                        41
package attributes size:       1112
total size:                    1009
-----------------------------------
waiting for build package python3_numpy_x86-1.14.5-1 to be activated
Building ...
Running from numpy source directory.
blas_opt_info:
blas_mkl_info:
customize UnixCCompiler
  libraries mkl_rt not found in ['/packages/python3_numpy_x86-1.14.5-1/cmd~python3.6/lib']
  NOT AVAILABLE

blis_info:
customize UnixCCompiler
  libraries blis not found in ['/packages/python3_numpy_x86-1.14.5-1/cmd~python3.6/lib']
  NOT AVAILABLE

openblas_info:
customize UnixCCompiler
customize UnixCCompiler
customize UnixCCompiler
customize UnixCCompiler
  libraries openblas not found in ['/system/lib/x86']
Runtime library openblas was not found. Ignoring
  FOUND:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/system/develop/lib/x86']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

  FOUND:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/system/develop/lib/x86']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

/bin/sh: svnversion: command not found
/bin/sh: svnversion: command not found
F2PY Version 2
lapack_opt_info:
lapack_mkl_info:
customize UnixCCompiler
  libraries mkl_rt not found in ['/packages/python3_numpy_x86-1.14.5-1/cmd~python3.6/lib']
  NOT AVAILABLE

openblas_lapack_info:
customize UnixCCompiler
customize UnixCCompiler
customize UnixCCompiler
C compiler: gcc -Wno-unused-result -Wsign-compare -DNDEBUG -D_BSD_SOURCE -D_BSD_SOURCE -fPIC

creating /tmp/tmpspqlrx3t/tmp
creating /tmp/tmpspqlrx3t/tmp/tmpspqlrx3t
compile options: '-c'
gcc: /tmp/tmpspqlrx3t/source.c
gcc: cannot specify -o with -c or -S and multiple compilations
gcc: cannot specify -o with -c or -S and multiple compilations
Traceback (most recent call last):
  File "/sources/numpy-1.14.5/numpy/distutils/unixccompiler.py", line 58, in UnixCCompiler__compile
    extra_postargs, display = display)
  File "/sources/numpy-1.14.5/numpy/distutils/ccompiler.py", line 89, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "/sources/numpy-1.14.5/numpy/distutils/ccompiler.py", line 152, in CCompiler_spawn
    raise DistutilsExecError('Command "%s" failed with exit status %d%s' % (cmd, s, msg))
distutils.errors.DistutilsExecError: Command "gcc -Wno-unused-result -Wsign-compare -DNDEBUG -D_BSD_SOURCE -D_BSD_SOURCE -fPIC -c /tmp/tmpspqlrx3t/source.c -o /tmp/tmpspqlrx3t/tmp/tmpspqlrx3t/source.o -MMD -MF /tmp/tmpspqlrx3t/tmp/tmpspqlrx3t/source.o.d" failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 394, in <module>
    setup_package()
  File "setup.py", line 386, in setup_package
    setup(**metadata)
  File "/sources/numpy-1.14.5/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 166, in configuration
    config.add_subpackage('numpy')
  File "/sources/numpy-1.14.5/numpy/distutils/misc_util.py", line 1024, in add_subpackage
    caller_level = 2)
  File "/sources/numpy-1.14.5/numpy/distutils/misc_util.py", line 993, in get_subpackage
    caller_level = caller_level + 1)
  File "/sources/numpy-1.14.5/numpy/distutils/misc_util.py", line 930, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy/setup.py", line 16, in configuration
    config.add_subpackage('linalg')
  File "/sources/numpy-1.14.5/numpy/distutils/misc_util.py", line 1024, in add_subpackage
    caller_level = 2)
  File "/sources/numpy-1.14.5/numpy/distutils/misc_util.py", line 993, in get_subpackage
    caller_level = caller_level + 1)
  File "/sources/numpy-1.14.5/numpy/distutils/misc_util.py", line 930, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy/linalg/setup.py", line 29, in configuration
    lapack_info = get_info('lapack_opt', 0)  # and {}
  File "/sources/numpy-1.14.5/numpy/distutils/system_info.py", line 432, in get_info
    return cl().get_info(notfound_action)
  File "/sources/numpy-1.14.5/numpy/distutils/system_info.py", line 624, in get_info
    self.calc_info()
  File "/sources/numpy-1.14.5/numpy/distutils/system_info.py", line 1534, in calc_info
    openblas_info = get_info('openblas_lapack')
  File "/sources/numpy-1.14.5/numpy/distutils/system_info.py", line 432, in get_info
    return cl().get_info(notfound_action)
  File "/sources/numpy-1.14.5/numpy/distutils/system_info.py", line 624, in get_info
    self.calc_info()
  File "/sources/numpy-1.14.5/numpy/distutils/system_info.py", line 1831, in calc_info
    if not (assume_lapack or self.check_embedded_lapack(info)):
  File "/sources/numpy-1.14.5/numpy/distutils/system_info.py", line 1897, in check_embedded_lapack
    obj = c.compile([src], output_dir=tmpdir)
  File "/sources/numpy-1.14.5/numpy/distutils/ccompiler.py", line 89, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "/sources/numpy-1.14.5/numpy/distutils/ccompiler.py", line 343, in CCompiler_compile
    single_compile(o)
  File "/sources/numpy-1.14.5/numpy/distutils/ccompiler.py", line 303, in single_compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/sources/numpy-1.14.5/numpy/distutils/ccompiler.py", line 89, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "/sources/numpy-1.14.5/numpy/distutils/unixccompiler.py", line 61, in UnixCCompiler__compile
    raise CompileError(msg)
distutils.errors.CompileError: Command "gcc -Wno-unused-result -Wsign-compare -DNDEBUG -D_BSD_SOURCE -D_BSD_SOURCE -fPIC -c /tmp/tmpspqlrx3t/source.c -o /tmp/tmpspqlrx3t/tmp/tmpspqlrx3t/source.o -MMD -MF /tmp/tmpspqlrx3t/tmp/tmpspqlrx3t/source.o.d" failed with exit status 1
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 1
Error: Build has failed - stopping.
~>l`
However, it is obvious that this is already a topic for another discussion.

**Comment by extrowerk** [comment]
I think lapack is still broken on x86

**Comment by Lan72** [comment]
I do not remember exactly, but when I building lapack_x86, there were some problems, yes. I managed to build it from the second or third attempt. So lapack_x86 is in my system.

**Comment by extrowerk** [comment]
Maybe you could help to fix the recipe, afaik there were problems only at the packaging stage.
That would be nice!

-- Z.

2018.09.08. dátummal, 13:41 időpontban Alexey Lugin <notifications@github.com> írta:

**Comment by extrowerk** [comment]
It seems it cannot compile things, but i'm not sure.
Can you open an issue for lapack and numpy, please?

-- Z.

2018.09.08. dátummal, 12:35 időpontban Alexey Lugin <notifications@github.com> írta:

**Comment by Lan72** [comment]
Ok

**Comment by extrowerk** [comment]
I think this is solved in the meantime, if still happens, please reopen this.

**Comment by Begasus** [comment]
At this moment "cmd:f2py2" is only provided by:
 https://github.com/haikuports/haikuports/blob/790173af48fc983b859a2649d760fcb223935e1f/dev-python/numpy/numpy_python-1.16.5.recipe
As there is a newer version it doesn't support python 2.7 anymore: 
https://github.com/haikuports/haikuports/blob/d7a53b1edd75f1a2dbb88a32334c0999bd5cb51e/dev-python/numpy/numpy-1.17.4.recipe
Looks like previous version isn't installable atm?

**Comment by Begasus** [comment]
Numpy 1.16.5 is disabled for secondary architecture on 32 bit, it can be build from source though

**Comment by Begasus** [comment]
Should be fixed, closing
