### ISSUE TITLE
Apache Port 

### ISSUE THREAD

**Issue by lorglas** [haikuports/haikuports#2949]
Haiku x86_64 Hrev: 52272
Server version: Apache/2.4.34 (Unix)
Server built:   Jul 19 2018 22:10:58

> AH00526: Syntax error on line 164 of /packages/apache-2.4.34-1/.settings/httpd.conf: Error:\tApache has not been designed to serve pages while\n\trunning as root.  There are known race conditions that\n\twill allow any local user to read any file on the system.\n\tIf you still desire to serve pages as root then\n\tadd -DBIG_SECURITY_HOLE to the CFLAGS env variable\n\tand then rebuild the server.\n\tIt is strongly suggested that you instead modify the User\n\tdirective in your httpd.conf file to list a non-root\n\tuser.\n

Solution: 
```
useradd www-data
groupadd www-data
```

useradd / groupadd not automaticly for non-root user

> [core:emerg] [pid 2541:tid 1514973643904] (70023)This function has not been implemented on this platform: AH00023: Couldn't create the mpm-accept mutex 
> (70023)This function has not been implemented on this platform: could not create accept mutex
> AH00015: Unable to open logs

**Comment by extrowerk** [comment]
Maybe @fbrosson have some idea.

**Comment by fbrosson** [comment]
Yep, the recipe needs some fixes.
This is what I wrote as commit message for fcbd68f5939fd2004c152c1dbd2897b6818a6af2:
> Apache: bump to 2.4.34, switch SOURCE_URI to tar.bz2.
> Remark: the default configuration does not work out-of-the-box, but
> this was already the case before this version bump..

**Comment by Begasus** [comment]
Guessing we can leave this open, issue is still around

**Comment by diversys** [comment]
> [core:emerg] [pid 2541:tid 1514973643904] (70023)This function has not been implemented on this platform: AH00023: Couldn't create the mpm-accept mutex
> (70023)This function has not been implemented on this platform: could not create accept mutex
> AH00015: Unable to open logs

"This function has not been implemented on this platform" is `APR_ENOTIMPL`.
This message comes not from apache itself but from apr (`libapr-1.so.0`).
I checked apr patches and there is one very small one. However, in the past there was a big one (https://github.com/haikuports/haikuports/blob/3eec7a1b90808ab0b833ad18ec9d4f3de404a7a2/dev-libs/apr/patches/apr-1.0.1.diff) by @weinhold. It mentions several `APR_ENOTIMPL` in beos code. I wonder if it was mistakenly deleted?

**Comment by pulkomandy** [comment]
This is an extremely old patch (it seems to even pre-date the haikuports repository!).

I think what happened is either some of these changes were included in upstream apr at the time, or some of them are not needed for Haiku (since we are much more similar to standard UNIX systems than BeOS was).

But clearly something is not working as expected. I don't know how much of the BeOS code we still rely on, and how much things have been moved to portable UNIX alternatives already in current APR versions for Haiku.

Do we have any hint about which function in APR specifically is not working?

**Comment by diversys** [comment]
The error is gone. I enabled `apache` in 5bad07b93934aa9a6d5390217e4f065c914e5daf. Thanks!

**Comment by diversys** [comment]
apache produces the following error but seems to still run:
```
apachectl 
AH00557: httpd: apr_sockaddr_info_get() failed for shredder
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. 
Set the 'ServerName' directive globally to suppress this message
```

**Comment by waddlesplash** [comment]
Seems mostly harmless. Indeed we can consider this fixed.
