### ISSUE TITLE
LLVM/Clang does not compile x64 binaries with -fPIC by default

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#298]
CMake tries to run its ABI tests and fails to link them with `ld`, which gives a message saying "please recompile with -fPIC".

**Comment by korli** [comment]
is this about cmake or llvm? Please provide a command line to test and a log.

**Comment by waddlesplash** [comment]
I don't know which it's about, as I'm not sure if PIC support is part of LLVM or Clang.
And building any CMake project on x86_64 with CC=clang & CXX=clang++ will result in "Detecting CXX ABI info -- Failed", with the failing command/file/steps in CMakeFiles/CMakeError.log.

**Comment by kallisti5** [comment]
Could be related to https://llvm.org/bugs/show_bug.cgi?id=14200   Sometimes flags don't properly get set in llvm when cmake is used. In that case rtti wasn't getting set.

**Comment by korli** [comment]
Seems to be fixed: I tested with clang-git a build of zlib which is CMake based.
