### ISSUE TITLE
HaikuWebKit requires SSE2 which Pentium III doesn't have

### ISSUE THREAD

**Issue by R0bur** [haikuports/haikuports#3006]
Haiku web browsers based on HaikuWebKit crashes with exception "invalid opcode exception" on Pentium_III-based hardware.

https://dev.haiku-os.org/ticket/14060 - the ticket marked as "Closed" but the issue still exists

**Comment by kenmays** [comment]
@R0bur - Actually, SSE2 is implemented in Intel's Pentium 4/Pentium M and newer processors. You also can use AMD's Opteron/Phenom/Athlon64 K8  processors and newer AMD64 processors.

Note: Don't use legacy processors older than a Intel Pentium 4. Most media and web browser apps will not work properly.

**Comment by R0bur** [comment]
Okay, thanks.

**Comment by pulkomandy** [comment]
On Wed, Sep 05, 2018 at 11:03:05AM -0700, kenmays wrote:
> @R0bur - Actually, SSE2 is implemented in Intel's Pentium 4/Pentium M and newer processors. You also can use AMD's Opteron/Phenom/Athlon64 K8  processors and newer AMD64 processors.
> 
> Note: Don't use legacy processors older than a Intel Pentium 4. Most media and web browser apps will not work properly.

Media should work, as ffmpeg detects availability of the instruction
sets at runtime (it may still be that the CPU is not fast enough for
what you're trying to decode).

WebPositive will not support anything without SSE support, and does not
get much testing on machines without SSE2 (I have one, but I don't use
it often).

I recommend installing and using NetSurf instead, at least it will be
reasonably fast.

**Comment by R0bur** [comment]
@pulkomandy - Haiku works on the P-III hardware very well, teapot rolls fast enough, it give modern software development platform. Media encoding/decoding is not matter for my. But I need web browser for reading specs, docs and manuals and testing some web-pages.
Thank you for the recommendation to use NetSurf.
