### ISSUE TITLE
Mesa: Mesa 18.x mesa_swpipe driver inop after build

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3007]
Mesa 18.x **_mesa_swpipe_** driver (libswpipe.so) inop with GLinfo or in outputting 3D rendering. No major issues with Mesa library or working with legacy **_mesa_swrast_** driver.

Ref: https://dev.haiku-os.org/ticket/14452

Tested with Mesa 18.3-current_20180905, Mesa 18.2.0-rc5, and Mesa 18.1.7 (stable) w/hrev52300.

Mark as: Bug, Work in progress/help wanted
  
 Testing process:
    git clone ​https://gitlab.freedesktop.org/kallisti5/mesa.git
    git branch -u origin/hgl-modernize-drawable
    git checkout hgl-modernize-drawable
    scons
    find libGL.so in the build directory and put in ~/config/non-packaged/lib/
    mkdir ~/config/non-packaged/add-ons/opengl
    find libswpipe.so in the build directory and put in ~/config/non-packaged/add-ons/opengl/
    run GLInfo
    debug

**Comment by extrowerk** [comment]
Please, do not include pre-releases or for know-to-be-WIP ports in your issue.
