### ISSUE TITLE
Falkon: create Falkon recipe

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3012]
Falkon is a web browser,  previously QupZilla, using the Qt WebEngine rendering engine. 

Falkon has all standard functions you expect from a web browser. It includes bookmarks, history (both also in sidebar) and tabs. Above that, it has by default enabled blocking ads with a built-in AdBlock plugin.

Requires:
QtWebEngine (with Haiku modifications)

Current Haiku port project: https://github.com/kenmays/haikuports/tree/falkon-1/www-client/falkon

**Comment by kenmays** [comment]
@extrowerk - I've tested and created the recipe and patchset. Need help on creating new icon for RDEF and any other wanted enhancements for patchset.

**Comment by scottmc** [comment]
For the icon request, open a new ticket and we can have it as a GCI task.

**Comment by extrowerk** [comment]
There is no QtWebEngine in HaikuPorts yet. Please, start with that.
And i still would like to see a screenshot about Falkon running on Haiku.

**Comment by kenmays** [comment]
@scottmc - Thanks, I created it.

**Comment by kenmays** [comment]
Recipe work complete.
