### ISSUE TITLE
documentviewer broken build

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#3022]
see https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/1996/builds/11858.log

**Comment by diversys** [comment]
I think it should be already fixed upstream? https://github.com/HaikuArchives/DocumentViewer/commit/1c4968df6b72ffc61621f4545d3bd01dcda9800b

**Comment by waddlesplash** [comment]
Yes, and a lot of crashes fixed at once. We just need to update it.

**Comment by korli** [comment]
updated in edb69e9619f701a2103d2113a15c03467dd833f6
