### ISSUE TITLE
libebook broken build

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#3023]
see https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/1996/builds/11866.log

**Comment by diversys** [comment]
We should probably make this error a warning.
https://gitweb.gentoo.org/repo/gentoo.git/tree/app-text/libebook/libebook-0.1.3.ebuild#n43

**Comment by korli** [comment]
Done in b307e56f60e2f2f038c48834b7907a0970b006e4
