### ISSUE TITLE
librevenge broken build gcc7

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#3029]
see https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/1996/builds/11872.log

**Comment by Begasus** [comment]
https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/
Using -Wimplicit-fallthrough=0 in the Makefile works, but I'm not sure it's the right path to go ...

**Comment by Begasus** [comment]
Adding ``[[fallthrough]];`` on line 481 from that file also works ..

**Comment by korli** [comment]
as it's only gcc, patching with [[fallthrough]]; would also be OK.

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/3053

**Comment by korli** [comment]
thanks! fb5660d4a292cf8dad95b5d65431ef9b0bf1eb34
