### ISSUE TITLE
Create a recipe for games-board/gnuchess

### ISSUE THREAD

**Issue by michaelvoliveira** [haikuports/haikuports#303]
http://ftp.gnu.org/gnu/chess/gnuchess-6.2.1.tar.gz

lib=gettext

commands
libtoolize -fci
aclocal
autoconf
./configure --datarootdir='please insert a valid dir for install'
make

**Comment by michaelvoliveira** [comment]
Patch to build
https://drive.google.com/file/d/0B4OzNTNV4PS0Q3kwdXY5SWlub3M/view?usp=sharing

**Comment by michaelvoliveira** [comment]
How can I attach the patch here?

**Comment by diversys** [comment]
Github doesn't allow attaching text files. You can create pull request.

**Comment by michaelvoliveira** [comment]
BIG THANKS diversys! Now I'm able to read and made some decent patches and recipes based on this.

**Comment by diversys** [comment]
BTW, Github does support attaching text files now.
