### ISSUE TITLE
podofo broken build

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#3030]
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/1996/builds/11880.log

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/3049
But correct me if I'm wrong :)

**Comment by korli** [comment]
Thanks! 02ed1bfce6082016a22adc05abbbc4570d5c1dce
