### ISSUE TITLE
hexvexed doesn't install background.png

### ISSUE THREAD

**Issue by owenca** [haikuports/haikuports#3033]

**Comment by scottmc** [comment]
I just tagged a new beta2 release for Hexvexed
https://github.com/HaikuArchives/HexVexed/archive/1.0.0-Beta2.tar.gz
There recipe may need to have a line added to copy the background.png file into the backagrounds directory for it to work right.  Recipe should be updated to release=4
I will likely do a 1.0.0 release after GCI 2018 concludes, as there might be a few more issues fixed soon.

**Comment by Begasus** [comment]
@owenca I did that in the recipe, and the background.png is in the correct folder, but in the menu for HexVexed it doesn't show up (only a blank entry)

**Comment by Begasus** [comment]
Ok, moved everything in $appsDir/HexVexed/ (with subfolder backgrounds/background.png)
the item now shows up in the menu, but the background doesn't change when selecting ;)

**Comment by Begasus** [comment]
created a draft PR for this one ... https://github.com/haikuports/haikuports/pull/3089

**Comment by scottmc** [comment]
Maybe try creating a second background to put in same directory and then see if you can switch between the two?  I think it may not be switching because there isn't another to switch too?

**Comment by Begasus** [comment]
could check, ps, wouldn't it be better to put the *.png into a subfolder "backgrounds" in the source?
in that way if there were more backgrounds to come you could just cp the backgrounds/*.png to the correct folder

**Comment by Begasus** [comment]
same thing, both backgrounds in the folder and show up in the menu entry, nothing happens when selecting, but restarting flickers the new background and reverts to the default (none)

**Comment by scottmc** [comment]
looks like pending recipe got merged, but it still doesn't fix this issue.  It points to the beta3...  If/when the latest commit of hexvexed works, let me know and I'll do a beta4 tag.

**Comment by Begasus** [comment]
Latest commit works (I thought that was clear by now) :)

**Comment by scottmc** [comment]
ok, just tagged a beta-4, verify that works and then submit a new haikuports recipe and we should be good to go now?

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/3115
