### ISSUE TITLE
libdsk tarball missing

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#3037]
see https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/1834/builds/30604.log
the tarball for 1.5.4 isn't online anymore.
It's not on https://ports-mirror.haiku-os.org/ too.

A version update would solve this issue.

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/3039

**Comment by korli** [comment]
Thanks 39bd420a630826ccda0ef8fe504d20463e0a327e
