### ISSUE TITLE
Plee-the-bear won't launch (libclaw_net error)

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#3048]
Launching Plee from Terminal, I get:
```
runtime_loader: /boot/system/lib/x86/libclaw_net.so.1.7.4: Could not resolve symbol 'bind'
resolve symbol "bind" returned: -2147478780
runtime_loader: /boot/system/lib/x86/libclaw_net.so.1.7.4: Troubles relocating: Symbol not found
```
That's on 32bit Haiku.
(BTW, wouldn't a game be normally put in $appsDir instead of $binDir?)

**Comment by extrowerk** [comment]
AFAIK bind should be in libnetwork, so adding -DCMAKE_SHARED_LINKER_FLAGS="-lnetwork" should help.

**Comment by humdingerb** [comment]
Sadly, the current SOURCE_URI is dead.
There's a version 0.7.1: https://github.com/j-jorge/plee-the-bear/archive/0.7.1.tar.gz
But of course the patch won't apply anymore, and I have no idea where's what...

**Comment by korli** [comment]
@humdingerb have you pulled updates? I updated the source uri already:
https://github.com/haikuports/haikuports/commit/713c71f1088605acacb1746fccc1f5acff9148d5#diff-a0107c42be6f94347f377f0d2d6e2c8d

**Comment by humdingerb** [comment]
@korli
Indeed, I had an outdated SOURCE_URL...
And your patch did solve that symbol error described in the ticket. Thanks, I'll push your patch later!

While Plee now actually almost launches, it crashes right at the start. I'll open another ticket for that...
