### ISSUE TITLE
zziplib provides broken links in the _devel package

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#3050]
At least on x86_64 i got broken symlinks in devel/libs.

**Comment by Begasus** [comment]
This doesn't look correct .... https://github.com/haikuports/haikuports/blob/0d782eba6738395cc7a73e300ef29f1cc27cbb0f/dev-libs/zziplib/zziplib-0.13.67.recipe#L46

**Comment by Begasus** [comment]
Seen this one also a few times (not related to this issue), why is the last line in the PROVIDES not marked with $libVersionCompat?
https://github.com/haikuports/haikuports/blob/0d782eba6738395cc7a73e300ef29f1cc27cbb0f/dev-libs/zziplib/zziplib-0.13.69.recipe#L34

**Comment by korli** [comment]
fixed in 22f1fd98ba1a7c01d643a0c81d429b019f34d014
