### ISSUE TITLE
Add Shisen-Sho to HaikuArchives 

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#3057]
[shisen_x86_09.zip](https://github.com/haikuports/haikuports/files/2381925/shisen_x86_09.zip)

**Comment by korli** [comment]
No license

**Comment by korli** [comment]
Now I see a source file with GPLv2 board.cpp. It means the project is also GPLv2.
Mario Weilguni <mweilguni@sime.com>

**Comment by korli** [comment]
Added at https://github.com/HaikuArchives/ShisenSho
