### ISSUE TITLE
alembic broken build

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#3061]
see https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/1881/builds/30714.log

**Comment by Begasus** [comment]
Checked out version 1.7.9, added a define for __HAIKU__ in the IStreams.cpp at line 41, but the produced binaries fail with missing symbol:
```runtime_loader: /boot/system/lib/x86/libstdc++.so.6.0.24: Could not resolve symbol '___tls_get_addr'´´´

Adding the next for the installation of the lib should fix current one too I think:
```
   mkdir -p $prefix/lib2
   mv $prefix/lib/l* $prefix/lib2
   mkdir -p $libDir
   mv $prefix/lib2/* $libDir/
   rmdir $prefix/lib2```

**Comment by alaviss** [comment]
>     runtime_loader: /boot/system/lib/x86/libstdc++.so.6.0.24: Could not resolve symbol ___tls_get_addr

Now that's a problem. That symbol is provided by `libroot`...

**Comment by korli** [comment]
You should ask Cmake to disable the runtime path.

**Comment by korli** [comment]
Maybe -DCMAKE_SKIP_RPATH=ON

**Comment by korli** [comment]
1.7.9 recipe still broken: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/1969/builds/30827.log

**Comment by Begasus** [comment]
fix comming in a bit :)

**Comment by Begasus** [comment]
Should be ok with this one https://github.com/haikuports/haikuports/pull/3105
