### ISSUE TITLE
eepp broken build

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#3064]
see https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/1887/builds/30722.log

**Comment by Begasus** [comment]
fix comming up :)

**Comment by Begasus** [comment]
should be ok :) https://github.com/haikuports/haikuports/pull/3103

**Comment by scottmc** [comment]
is this working now?

**Comment by Begasus** [comment]
PR got merged, so I think this can be closed
