### ISSUE TITLE
monkeystudio broken build

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#3065]
```
src/QtDesignerManager.cpp:50:10: fatal error: pluginmanager_p.h: No such file or directory
#include "pluginmanager_p.h"
```

see https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/2052/builds/11997.log
and see https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/1889/builds/30725.log

**Comment by Begasus** [comment]
Build for x86_gcc still fails with the same error, re-opening
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/1128/builds/1987.log

**Comment by korli** [comment]
Build disabled for all archs in 31b08a35c29dd32b28cebd6194e4f6adc8a53f78
