### ISSUE TITLE
Helios - request, pull from HaikuDepot

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#3069]
Helios is not yet in a working state on Haiku and should be pulled from available downloads on HaikuDepot until the remaining issues are resolved.

**Comment by alaviss** [comment]
Can you tag those issues here? Thanks!

**Comment by Vidrep** [comment]
https://github.com/HaikuArchives/Helios/issues

**Comment by waddlesplash** [comment]
https://github.com/HaikuArchives/Helios/issues/8

**Comment by waddlesplash** [comment]
https://git.io/fADpR
