### ISSUE TITLE
schismtracker broken recipe 

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#3073]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/1941/builds/30790.log

I updated the recipe to use the Github archive, but the tarball doesn't contain the configure script anymore.
Maybe 'autoreconf' should be enough.

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/3078

**Comment by korli** [comment]
Thanks! da15bf76f11f9ebbf5186d596278d6166dbe673c
