### ISSUE TITLE
vim: Hardcoded user directory

### ISSUE THREAD

**Issue by alaviss** [haikuports/haikuports#3088]
https://github.com/haikuports/haikuports/blob/07db71a454374092cbbeb21ed6a447914aba2141/app-editors/vim/vim-8.0.1176.recipe#L141

This should be adjusted to use vim's `system()` to acquire this path on-the-fly.

**Comment by kenmays** [comment]
@alaviss - What do you consider the best method? I put the path in there for consistency, but we can review the best solution.

**Comment by alaviss** [comment]
It should be like this

```vim
execute "set runtimepath+=" . substitute(system("finddir B_USER_SETTINGS_DIRECTORY"), '\n\+$', '', '') . "/vim"
```

Instead of hardcoding the path to `vimrc`

**Comment by kenmays** [comment]
Updated recipe.

**Comment by kenmays** [comment]
All changes made. Reran recipe. Package rebuilt. Everything passes.
