### ISSUE TITLE
librecad broken build

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#3090]
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/2116/builds/12066.log

**Comment by Begasus** [comment]
Checking with the fixes from upstream, only colorwizard.cpp is not in the source (local) ...

**Comment by Begasus** [comment]
Should be fixed in https://github.com/haikuports/haikuports/pull/3100

**Comment by korli** [comment]
Thanks! 92a634bff98b8cf11ce06e34dbf175a965757519
