### ISSUE TITLE
bash_completion: should be of `any` architectures

### ISSUE THREAD

**Issue by alaviss** [haikuports/haikuports#3096]
Currently is restricted to `x86_64` for reasons unknown. This package doesn't contain any architecture specific bits.

https://github.com/haikuports/haikuports/blob/547d8d3f7bfef2e72519b1f07e9dbd9a470be2a6/app-shells/bash_completion/bash_completion-2.7.recipe#L22

**Comment by korli** [comment]
BTW it would be nice to add some tests for pkgman and finddir, so one can upstream the patchset.

**Comment by korli** [comment]
done in b4b6e692fb82091b2a733fb518717045eb0756de
