### ISSUE TITLE
vim: flawed logic in recipe

### ISSUE THREAD

**Issue by alaviss** [haikuports/haikuports#3097]
https://github.com/haikuports/haikuports/blob/07db71a454374092cbbeb21ed6a447914aba2141/app-editors/vim/vim-8.0.1176.recipe#L137-L141

`>` was used twice, which means the resulting `vimrc` only contains

    set runtimepath+=/boot/home/config/settings/vim

**Comment by kenmays** [comment]
Update recipe

**Comment by kenmays** [comment]
@alaviss - All changes made. Reran recipe. Package built. Everything passes.

**Comment by alaviss** [comment]
Closed by #3092
