### ISSUE TITLE
Command line soft-wrap broken

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#3117]
Inserting, editing, navigating in long commands are broken for me. It should automatically wrap long commands into more than one line, but it glitches.
I assume, the culprit could be:
- local settings
- font in terminal
- editline settings
- readline/ncurses
- bash settings
- PS1
and plenty more other things.

My PS1 is currently just "#" but the problem still there, just "less broken". If you have more ideas, please help to extend the list, and i will test all of them, to see where does it comes from.

**Comment by waddlesplash** [comment]
This is probably a bug in Haiku's Terminal?

**Comment by augiedoggie** [comment]
No response
