### ISSUE TITLE
Kernel crashes trying to build perl5

### ISSUE THREAD

**Issue by adamfowleruk** [haikuports/haikuports#3118]
Not sure if this is a porter or Haiku issue, so reporting in both places.

Cloned the latest haikuporter. ran ./haikuporter -S --all-dependencies ne to build the ne editor

After a while, it eventually tries to build perl5. At this point Haiku crashes. It is fully reproduceable as per the 2 attached images.

hrev52346

![haiku-kernel-porting-ne](https://user-images.githubusercontent.com/2700521/45926228-37bc2e80-bf18-11e8-9227-de88e92e0b91.png)
![haiku-kernel-porting-ne-2](https://user-images.githubusercontent.com/2700521/45926229-37bc2e80-bf18-11e8-9e2e-e3c843c28e07.png)

**Comment by diversys** [comment]
This is a bug in Haiku. Please move this ticket there. Thanks!

**Comment by adamfowleruk** [comment]
Done, thanks! https://dev.haiku-os.org/ticket/14512
