### ISSUE TITLE
diffutils's cmp: no output, even for different files

### ISSUE THREAD

**Issue by ttcoder** [haikuports/haikuports#312]
Whatever the result of the comparison, cmp remains silent, leading to think that all files are "equal"

Silent output is the behavior associated with "no difference" (by opposed to found differences, which generate some output), so it's a quite more serious bug than if it failed to work completely, because then we'd know not to rely on that command but as it is you're misled into thinking files compare to 'equal' even if they differ..

More details at https://dev.haiku-os.org/ticket/12390

**Comment by korli** [comment]
This isn't exactly a bug in cmp, more in Haiku: to find out if the output is redirected to /dev/null, cmp probes whether the stat structure are somehow identical. The two file descriptors are character devices and have st_rdev set to -1.
If cmp finds out stdout is /dev/null, then it spares the job of computing diffs, and outputs nothing.
