### ISSUE TITLE
liblo gcc2 build broken

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#3123]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/1989/builds/30880.log

**Comment by Begasus** [comment]
Got past the parse errors "Internal compiler error, output_operand_lossage `invalid expression as operand'" still remains for gcc2

**Comment by Begasus** [comment]
Maybe we should set gcc2 as broken and use commandSuffix for the recipe? I could push the changes for gcc2 into the patchset, but it wouldn't help anything (for now) ...

**Comment by korli** [comment]
gcc2 disabled in 36184523cdab98e97cedef173a66868ce86d575c
