### ISSUE TITLE
gdal1 broken build

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#3124]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/1989/builds/30870.log
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/2132/builds/12088.log

**Comment by Begasus** [comment]
updated the recipe for proj_x86 to not include the *.la, still getting the same error, somehow it's hardcoded? just can't seem to find where (already tried with linking statically instead of dynamically) ... same issue remains ...

**Comment by Begasus** [comment]
Working on it, things to be done:
[ ] bump proj not to include the *.la file
[ ] bump libgeotiff to not include the *.la file (and rebuild against proj)
[ ] bump recipe for gdal1 to use the correct settings/install etc ...
Managed so far, but need to check first 2 on x86_64 to be sure they are ok ... :)

**Comment by Begasus** [comment]
Working on it, things to be done:
[x] bump proj not to include the *.la file https://github.com/haikuports/haikuports/pull/3136
[x] bump libgeotiff to not include the *.la file (and rebuild against proj) https://github.com/haikuports/haikuports/pull/3137
[x] bump recipe for gdal1 to use the correct settings/install etc ... https://github.com/haikuports/haikuports/pull/3138
Builds ok for _x86 and x86_64, test fail for proj, will open a new issue for that ...
