### ISSUE TITLE
fatal error - Java Runtime Environment:

### ISSUE THREAD

**Issue by HutchSails** [haikuports/haikuports#313]
_A fatal error has been detected by the Java Runtime Environment:_

 SIGSEGV (0xb) at pc=0x0164df71, pid=621, tid=39102560

 JRE version: OpenJDK Runtime Environment (7.0) (build 1.7.0-internal-user_2015_05_27_14_28-b00)
 Java VM: OpenJDK Client VM (24.80-b11 mixed mode haiku-x86 )
 Problematic frame:
 C  [libnet.so+0xef71]  _fini+0x08

_This error occurred when using nightly hrev49652, after a Haiku Depot Arduino installation (which requires java)._

**Comment by HutchSails** [comment]
Was'nt at all sure where to post the crash log (other than to openjdk itself) as detailed here: 

https://www.haiku-os.org/community/forum/openjdk

**Comment by waddlesplash** [comment]
Save it as a '.txt. and upload it here.

**Comment by HutchSails** [comment]
Here is the full log of the JDE crash (wouldn't attach, unrecognized format):

  GNU nano 2.2.6                            File: javacrash.txt                                                              

_A fatal error has been detected by the Java Runtime Environment:_

SIGSEGV (0xb) at pc=0x00c73f71, pid=536, tid=32680032
 JRE version: OpenJDK Runtime Environment (7.0) (build 1.7.0-internal-user_2015_05_27_14_28-b00)
 Java VM: OpenJDK Client VM (24.80-b11 mixed mode haiku-x86 )
 Problematic frame:
 C  [libnet.so+0xef71]  _fini+0x0


 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp


---------------  T H R E A D  ---------------

Current thread is native thread

siginfo:si_signo=SIGSEGV: si_errno=Bad address, si_code=31 (), si_addr=0x00c73f71

Registers:
EAX=0x00c73f71, EBX=0x0250f11c, ECX=0x00000000, EDX=0x0000001c
ESP=0x72d6bfcc, EBP=0x72d6bff8, ESI=0x0036d044, EDI=0x0000001c
EIP=0x00c73f71, EFLAGS=0x00013207

Top of Stack: (sp=0x72d6bfcc)
0x72d6bfcc:   024fc1eb 00000a26 00000003 00000200
0x72d6bfdc:   024fc182 01f19a44 72d6d53c 72d6d548
0x72d6bfec:   01f19a44 72d6d53c 0036c5d0 72d6c008
0x72d6bffc:   01ed4ccf 0250f11c 005f99b4 72d6c038
0x72d6c00c:   005f8703 00000001 72d6d53c 72d6d548
0x72d6c01c:   00765a60 02509bff 00000002 06dcac56
0x72d6c02c:   0250f11c 0250f49c a46bd53c 72d6c068
0x72d6c03c:   02501b72 00000002 72d6d53c 72d6d548

Instructions: (pc=0x00c73f71)
0x00c73f51:   83 00 ff ff ff 8d b3 00 ff ff ff 83 f8 ff 74 0c
0x00c73f61:   83 ee 04 ff d0 8b 06 83 f8 ff 75 f4 5b 5e 5d c3
0x00c73f71:   55 89 e5 ff 75 08 e8 f1 53 ff ff e8 8f 52 ff ff
0x00c73f81:   e8 28 54 ff ff 89 ec 5d c3 00 00 00 00 00 00 00

Register to memory mapping:

EAX=
[error occurred during error reporting (printing register info), id 0xb]

Stack: [0x71d6d000,0x72d6d000],  sp=0x72d6bfcc,  free space=16379k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libnet.so+0xef71]  _fini+0x0
C  [libroot.so+0x92ccf]  exit+0x34
C  [java+0x703]  _start+0x58
C  0x02501b72


---------------  P R O C E S S  ---------------

VM state:at safepoint (shutting down)

VM Mutex/Monitor currently owned by a thread:  ([mutex/lock_event])
[0x18b49c68] Threads_lock - owner thread: 0x18b59c00

Heap
 def new generation   total 3520K, used 2318K [0x07400000, 0x077d0000, 0x0b200000)
  eden space 3136K,  61% used [0x07400000, 0x075e3958, 0x07710000)
  from space 384K, 100% used [0x07770000, 0x077d0000, 0x077d0000)
  to   space 384K,   0% used [0x07710000, 0x07710000, 0x07770000)
 tenured generation   total 7936K, used 851K [0x0b200000, 0x0b9c0000, 0x12e00000)
   the space 7936K,  10% used [0x0b200000, 0x0b2d4f70, 0x0b2d5000, 0x0b9c0000)
 compacting perm gen  total 12288K, used 4003K [0x12e00000, 0x13a00000, 0x16e00000)
   the space 12288K,  32% used [0x12e00000, 0x131e8ec0, 0x131e9000, 0x13a00000)
No shared spaces configured.

Card table byte_map: [0x002b0000,0x0032e000] byte_map_base: 0x00276000

Polling page: 0x001a8000

Code Cache  [0x050b2000, 0x0516a000, 0x070b2000)
 total_blobs=238 nmethods=84 adapters=91 free_code_cache=32034Kb largest_free_block=32803328

Compilation events (10 events):
Event: 1.218 Thread 0x18c87c00   80             java.util.LinkedHashMap$KeyIterator::next (8 bytes)
Event: 1.218 Thread 0x18c87c00 nmethod 80 0x05165a48 code [0x05165b50, 0x05165bec]
Event: 1.218 Thread 0x18c87c00   81             java.lang.String::compareTo (78 bytes)
Event: 1.218 Thread 0x18c87c00 nmethod 81 0x05165c88 code [0x05165d90, 0x05165eb0]
Event: 1.220 Thread 0x18c87c00   82             sun.nio.cs.UTF_8$Encoder::encodeArrayLoop (489 bytes)
Event: 1.222 Thread 0x18c87c00 nmethod 82 0x05166108 code [0x05166500, 0x05167258]
Event: 1.222 Thread 0x18c87c00   83             java.lang.String::startsWith (7 bytes)
Event: 1.223 Thread 0x18c87c00 nmethod 83 0x05168bc8 code [0x05168cc0, 0x05168d5c]
Event: 1.223 Thread 0x18c87c00   84             java.lang.AbstractStringBuilder::expandCapacity (50 bytes)
Event: 1.224 Thread 0x18c87c00 nmethod 84 0x05168dc8 code [0x05168ef0, 0x05169124]

GC Heap History (2 events):
Event: 1.141 GC heap before
{Heap before GC invocations=0 (full 0):
 def new generation   total 3520K, used 3136K [0x07400000, 0x077d0000, 0x0b200000)
  eden space 3136K, 100% used [0x07400000, 0x07710000, 0x07710000)
  from space 384K,   0% used [0x07710000, 0x07710000, 0x07770000)
  to   space 384K,   0% used [0x07770000, 0x07770000, 0x077d0000)
 tenured generation   total 7936K, used 0K [0x0b200000, 0x0b9c0000, 0x12e00000)
   the space 7936K,   0% used [0x0b200000, 0x0b200000, 0x0b200200, 0x0b9c0000)
 compacting perm gen  total 12288K, used 3795K [0x12e00000, 0x13a00000, 0x16e00000)
   the space 12288K,  30% used [0x12e00000, 0x131b4fa0, 0x131b5000, 0x13a00000)
No shared spaces configured.
Event: 1.150 GC heap after
Heap after GC invocations=1 (full 0):
 def new generation   total 3520K, used 384K [0x07400000, 0x077d0000, 0x0b200000)
  eden space 3136K,   0% used [0x07400000, 0x07400000, 0x07710000)
  from space 384K, 100% used [0x07770000, 0x077d0000, 0x077d0000)
  to   space 384K,   0% used [0x07710000, 0x07710000, 0x07770000)
 tenured generation   total 7936K, used 851K [0x0b200000, 0x0b9c0000, 0x12e00000)
   the space 7936K,  10% used [0x0b200000, 0x0b2d4f70, 0x0b2d5000, 0x0b9c0000)
 compacting perm gen  total 12288K, used 3795K [0x12e00000, 0x13a00000, 0x16e00000)
   the space 12288K,  30% used [0x12e00000, 0x131b4fa0, 0x131b5000, 0x13a00000)
No shared spaces configured.
}

Deoptimization events (0 events):
No events

Internal exceptions (10 events):
Event: 1.242 Thread 0x18b4fc00 Threw 0x075b6370 at /sources-3/hotspot/src/share/vm/prims/jni.cpp:721
Event: 1.242 Thread 0x18b4fc00 Threw 0x075b6370 at /sources-3/hotspot/src/share/vm/prims/jvm.cpp:1326
Event: 1.242 Thread 0x18b4fc00 Threw 0x075b6370 at /sources-3/hotspot/src/share/vm/oops/instanceKlass.cpp:551
Event: 1.242 Thread 0x18b4fc00 Threw 0x075b65e0 at /sources-3/hotspot/src/share/vm/runtime/reflection.cpp:1030
Event: 1.242 Thread 0x18b4fc00 Threw 0x075b6370 at /sources-3/hotspot/src/share/vm/prims/jni.cpp:721
Event: 1.243 Thread 0x18b4fc00 Threw 0x075b6370 at /sources-3/hotspot/src/share/vm/prims/jvm.cpp:1326
Event: 1.243 Thread 0x18b4fc00 Threw 0x075b6370 at /sources-3/hotspot/src/share/vm/prims/jvm.cpp:1326
Event: 1.243 Thread 0x18b4fc00 Threw 0x075b6370 at /sources-3/hotspot/src/share/vm/oops/instanceKlass.cpp:551
Event: 1.243 Thread 0x18b4fc00 Threw 0x075b6370 at /sources-3/hotspot/src/share/vm/prims/jvm.cpp:1326
Event: 1.243 Thread 0x18b4fc00 Threw 0x075b6370 at /sources-3/hotspot/src/share/vm/oops/instanceKlass.cpp:551

Events (10 events):
Event: 1.250 loading class 0x18cbdfa0
Event: 1.251 loading class 0x18cbdfd0
Event: 1.251 loading class 0x18cbdfd0 done
Event: 1.251 loading class 0x18cbdfa0 done
Event: 1.251 Thread 0x18c8dc00 Thread added: 0x18c8dc00
Event: 1.252 Thread 0x18e82400 Thread added: 0x18e82400
Event: 1.252 Thread 0x18c8dc00 Thread exited: 0x18c8dc00
Event: 1.252 Thread 0x18e82400 Thread exited: 0x18e82400
Event: 1.253 Thread 0x18b4fc00 Thread exited: 0x18b4fc00
Event: 1.253 Thread 0x18c88400 Thread exited: 0x18c88400


Dynamic libraries:
0x24f2000       /boot/system/runtime_loader
0x437000        /boot/system/lib/x86/openjdk/jre/lib/i386/jli/libjli.so
0x1e42000       /boot/system/lib/x86/libroot.so
0x1d55000       /boot/system/lib/x86/libz.so.1.2.8
0x1cfe000       /boot/system/lib/x86/libgcc_s.so.1
0x258b000       /boot/system/lib/x86/openjdk/jre/lib/i386/client/libjvm.so
0x179b000       /boot/system/lib/x86/libnetwork.so
0x12e4000       /boot/system/lib/x86/libbsd.so
0x22f6000       /boot/system/lib/x86/libsupc++.so
0x105c000       /boot/system/lib/x86/openjdk/jre/lib/i386/libverify.so
0xe3f000        /boot/system/lib/x86/openjdk/jre/lib/i386/libjava.so
0x14b9000       /boot/system/lib/x86/libbe.so
0xd16000        /boot/system/lib/x86/libstdc++.so.6.0.19
0x3371000       /boot/system/lib/x86/libicudata.so.55.1
0x19cd000       /boot/system/lib/x86/libicui18n.so.55.1
0xff0000        /boot/system/lib/x86/libicuio.so.55.1
0x145d000       /boot/system/lib/x86/libicule.so.55.1
0xa13000        /boot/system/lib/x86/libiculx.so.55.1
0x1956000       /boot/system/lib/x86/libicutu.so.55.1
0x7e0000        /boot/system/lib/x86/libicuuc.so.55.1
0x1236000       /boot/system/lib/x86/openjdk/jre/lib/i386/libzip.so
0x12d1000       /boot/system/lib/x86/libroot-addon-icu.so
0x697000        /boot/system/lib/x86/openjdk/jre/lib/i386/libawt.so
0xa57000        /boot/system/lib/x86/openjdk/jre/lib/i386/libhaikuapp.so
0x2366000       /boot/system/lib/x86/libtracker.so
0x351000        /boot/system/lib/x86/libtranslation.so
0x1836000       /boot/system/lib/x86/libtextencoding.so
0x9f2000        /boot/system/lib/x86/libgnu.so
0xc65000        /boot/system/lib/x86/openjdk/jre/lib/i386/libnet.so

VM Arguments:
java_command: processing.app.Base
Launcher Type: SUN_STANDARD

Environment Variables:
CLASSPATH=:java/lib/rt.jar:java/lib/tools.jar:lib/arduino-core.jar:lib/commons-codec-1.7.jar:lib/commons-exec-1.1.jar:lib/commons-httpclient-3.1.jar:lib/commons-l$
PATH=/boot/system/apps/Arduino/java/bin:.:/boot/home/config/non-packaged/bin:/boot/home/config/bin:/boot/system/non-packaged/bin:/bin:/boot/system/apps:/boot/syst$
LD_LIBRARY_PATH=/boot/system/apps/Arduino/lib

Signal Handlers:
SIGSEGV: [libjvm.so+0x486e10], sa_mask[0]=0xffeffcff, sa_flags=0x00000050
SIGBUS: [libjvm.so+0x486e10], sa_mask[0]=0xffeffcff, sa_flags=0x00000050
SIGFPE: [libjvm.so+0x3879d0], sa_mask[0]=0xffeffcff, sa_flags=0x00000050
SIGPIPE: [libjvm.so+0x3879d0], sa_mask[0]=0xffeffcff, sa_flags=0x00000050
SIGXFSZ: [libjvm.so+0x3879d0], sa_mask[0]=0xffeffcff, sa_flags=0x00000050
SIGILL: [libjvm.so+0x3879d0], sa_mask[0]=0xffeffcff, sa_flags=0x00000050
SIGUSR1: SIG_DFL, sa_mask[0]=0x00000000, sa_flags=0x00000000
SIGUSR2: [libjvm.so+0x387890], sa_mask[0]=0x00000000, sa_flags=0x00000050
SIGHUP: [libjvm.so+0x387a80], sa_mask[0]=0xffeffcff, sa_flags=0x00000050
SIGINT: [libjvm.so+0x387a80], sa_mask[0]=0xffeffcff, sa_flags=0x00000050
SIGTERM: [libjvm.so+0x387a80], sa_mask[0]=0xffeffcff, sa_flags=0x00000050
SIGQUIT: [libjvm.so+0x387a80], sa_mask[0]=0xffeffcff, sa_flags=0x00000050


---------------  S Y S T E M  ---------------

OS: Haiku
uname:Haiku 1 hrev49652 Sep 19 2015 01:20:52 BePC
rlimit: STACK 16384k, CORE 0k, NOFILE 8192, AS 8k
load average:0.00 0.00 0.00
Memory: 4k page, physical 754624k(542664k free)

CPU:total 1 (1 cores per cpu, 1 threads per core) family 16 model 2 stepping 3, cmov, cx8, fxsr, mmx, sse, sse2, sse3, 3dnowpref, tsc

Memory: 4k page, physical 754624k(542664k free)

vm_info: OpenJDK Client VM (24.80-b11) for haiku-x86 JRE (1.7.0-internal-user_2015_05_16_18_15-b00), built on May 16 2015 22:24:45 by "user" with gcc 4.8.4

time: Sun Sep 27 13:56:11 2015
elapsed time: 1 seconds



...

**Comment by HutchSails** [comment]
Long paste - yeah - that's ridiculous.  Probably my browser is the issue.  Maybe someone can cut and paste it, and I'll delete the original.

This one was a VirtualBox instance, but has same result on actual x86.

**Comment by diversys** [comment]
Should be fixed in a3a757a.
