### ISSUE TITLE
haikuporter: Unable to find haikuports.conf

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#314]
On a clean installation invoking ```haikuporter``` (installed with ```pkgman ins haikuporter```) is not very intuitive:
```
Error: Unable to find haikuports.conf in known search paths.
Error: See haikuports-sample.conf for more information
```

```haikuports.conf``` is located in ```/system/settings``` but apparently ```haikuporter``` doesn't look there.
```haikuports-sample.conf``` is not installed at all.

**Comment by DarkmatterVale** [comment]
What hrev are you running @diversys ?

**Comment by diversys** [comment]
Haiku revision doesn't matter (I'm running the latest anyway).

**Comment by waddlesplash** [comment]
Fixed (see above).
