### ISSUE TITLE
Create a servo recipe

### ISSUE THREAD

**Issue by cb88** [haikuports/haikuports#3144]
So, I checked out servo and attempted to build it. However, the mach build tool it uses is broken on Haiku. 

Haikuports provides pip which can be used to install setuptools and virtualenv which seems to work (but pip does hang after installing? perhaps a separate ticket should be created for that). It fails when attempting to import a module inside virtualenv.

This would be a first step toward building modern Firefox which now depends on rust and lot of stuff from servo. That said it may actually be easier to port Firefox once we have accelerated 3d drivers it can just render to Vulkan directly and we'll have a first class accelerated and multithreaded browser. I imagine web+ would benefit from acceleration also.

**Comment by waddlesplash** [comment]
Servo is a separate project from Firefox and requires its own window abstraction, etc. which would need to be ported first. So this isn't a "first step" for Firefox, and I don't see a reason to track it here...
