### ISSUE TITLE
VLC 2.2.8: needs audio output module rewritten for Haiku.

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3146]
![vlc-test2](https://user-images.githubusercontent.com/5168719/61297956-33584f00-a792-11e9-8e35-a5a8fb8c51d7.png)
VLC 2.2.8 on hrev53242.

VLC 2.2.8 needs audio output module rewritten for Haiku.

**Comment by diversys** [comment]
What's the point for this issue? It doesn't mention anything specific that needs to be worked on or fixed. 
VLC 2.2.8 builds and runs on both x86 anx x86_64 for quite some time now. What do you want to review? Your PR from https://github.com/haikuports/haikuports/pull/3140 doesn't have a patch. Someone actually need to sit down and write audio/video output modules for Haiku. I know @threedeyes wanted to take a look at doing that but he had problems with compiling VLC 3.x.

So let's close this one?

**Comment by fbrosson** [comment]
@diversys, this issue was opened after a comment (https://github.com/haikuports/haikuports/pull/3140#issuecomment-424555630) from @scottmc.

(BTW, I don't know if this issue should be closed or not. I'll leave this question to you all :)

**Comment by scottmc** [comment]
Trying to understand the state here, VLC 2.2.8 build and works using SDL?  But 3.x doesn't since VLC dropped SDL2 support?  And Qt support doesn't work yet either?  I just want an issue to report the current status and what needs to be done to get current version of VLC functional on Haiku someday and to capture what needs to happen to get there.

**Comment by diversys** [comment]
* VLC dropped SDL audio output in 2.0 and then SDL video output in 3.0, see https://www.videolan.org/developers/vlc-branch/NEWS. 
So the last (possibly) functional version was 2.0.
* Qt5 GUI works but clicking play deadlocks VLC. It looks like an unrelated problem to Qt though.

**Comment by kenmays** [comment]
You mentioned  "VLC 2.2.8 builds and runs on both x86 and x86_64 for quite some time now. "

@diversys - I started on VLC 3.0.4 after I noticed you marked VLC 2.2.8 recdipe marked as non-functional at one time as well as someone mentioning crash issues with VLC 0.8.6i (yet they mentioned it was resolved). There are also a bunch of dev bug tickets on VLC as not working with DVDs or other issues. Neither VLC 0.8.6i nor 2.2.8 packages exist in Haiku Depot, so saying it builds and runs and the marking of those recipes "as non-functional on this architecture" when being built is how this originally started. VLC 3.0.4 uses SDL_image (it clearly says so, maybe devs forgot to take it out) so I don't know why it is said otherwise.

So, 
- VLC: disable as it's currently non-functional 
- https://github.com/haikuports/haikuports/commit/a5483281a4bfe40acdfa69814d86a21ef26954ba
- 
- VLC crashes at launch
- https://github.com/haikuports/haikuports/issues/225

**Comment by luzpaz** [comment]
VLC 3.0.6 is latest stable

**Comment by kenmays** [comment]
Tested hrev53091 x86_gcc2 w/external DVD/Blu-ray USB player. I played several audio CDs and DVDs through MediaPlayer with no major issue. 

I'd think normal users can use the other existing media players (SMPlayer. MPV, Mplayer, MediaPlayer, (Kplayer?), etc). MediaPlayer is now suitable for nearly all audio CD and most DVD playback tasks.  

I'm closing this ticket for now - as we now have modern DVD playback solutions currently working well with Haiku

**Comment by waddlesplash** [comment]
But VLC still does not work.

**Comment by kenmays** [comment]
Currently, for review on x86_gcc2:
- vlc 0.8.6i-2 x86_gcc2: [Link](http://haiku.uwolke.ru/repo/binaries-x86_gcc2/packages/vlc-0.8.6i-2-x86_gcc2.hpkg)

Legacy:
- vlc 0.8.6d x86_gcc2: [Link](http://haiku-files.org/files/optional-packages/vlc-0.8.6d-gcc2-2009-04-18.zip)

NOTE (Haikuports): 
VLC 0.8.6i x86_gcc2: Fixed and tested recipe enough to build - but failed eventually. W-I-P
VLC 0.8.6i x86_64: Fixed and tested recipe enough to build.  W-I-P
VLC 3.0.6 x86_64 recipe: W-I-P

**Comment by kenmays** [comment]
![vlc-2 2 8_cocobean](https://user-images.githubusercontent.com/5168719/56777444-82d84180-6786-11e9-859a-7662bc5d14b6.jpeg)

@Diver and @waddlesplash - Actually, I got it working with H.264/HEVC videos. Played a few videos to completion - but complains about a few things if not preset (audio, qt4 interface, etc). Diver, excellent!

**Comment by kenmays** [comment]
We can close this. Reviewed VLC 3.0.7.1, but will leave for maintainer's discretion on further porting work.

**Comment by waddlesplash** [comment]
Once again, there is no audio output, yes? So this should stay open.

**Comment by CodeforEvolution** [comment]
I have written an audio module for VLC over at: https://github.com/CodeforEvolution/vlc in the “haiku” branch.
I am unaware if this functions properly or builds completely as the vlc buildsystem was giving me issues.
Hope this helps either way!

**Comment by waddlesplash** [comment]
What issues are you hitting?

**Comment by CodeforEvolution** [comment]
Essentially, the build system kept finding a function called “tdelete” despite it not existing on Haiku. Thus, the built-in replacement vlc provides for “tdelete” was not being used, causing the build to eventually run into a linker error. I tried to fix this, however, autotools was giving me a great amount of trouble.

**Comment by diversys** [comment]
@CodeforEvolution Please see this patch: https://github.com/haikuports/haikuports/blob/05ea6c617822c3ab2137079adf17944b44e93d0b/media-video/vlc/patches/vlc-2.2.8.patchset#L110-L117.

**Comment by CodeforEvolution** [comment]
Ah, I forgot there may have been a patch set here already. Unfortunately, I’m traveling now and won’t be able to check the functionality of those previous patches until next week.

**Comment by kenmays** [comment]
@CodeforEvolution - most excellent. My audio subsystem works so I'll test once you are done.

**Comment by kenmays** [comment]
@CodeforEvolution - Merged your audio patch and built on x86. Built successfully. No errors.
- Videos work well.
- Audio showing 'no suitable audio'

**Comment by CodeforEvolution** [comment]
Oh, thank you! See, I was trying to get that code to work and compile using the latest code from vlc (4.0.0-dev). I forgot that I could test with an older version. I’ll take a look at this and try to debug what is going wrong with the audio plugin.

**Comment by kenmays** [comment]
I bumped to hrev53253+3 x86. Everything is still working well. **No GUI crashes.** Ok, I'm going to also do some audio debugging as time permits. Might fix it by this weekend.

**Comment by kenmays** [comment]
I bumped to hrev53259+3 x86. Everything is still working well. No GUI crashes. Ok, I'm going to also do some audio debugging as time permits. Might fix it by this weekend.

**Comment by kenmays** [comment]
![vlc_3 0 8-carroteater](https://user-images.githubusercontent.com/5168719/66521680-7d568580-eaa0-11e9-9da2-69f98c97d720.png)
UPDATE: VLC-2.2.8, no crash issues on exit. No major issues other than the native audio plugin.
Will research that further in the year.

**Comment by diversys** [comment]
What's the point of posting screenshot from windows version? I think it's not the first time you do it.

**Comment by kenmays** [comment]
UPDATE: Audio and SDL output module provided by 3dEyes for VLC 3.0.11: https://discuss.haiku-os.org/t/improving-vlc-2-2-8-for-haiku/8754/21
