### ISSUE TITLE
dooble: x86 build broken

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3152]
Building Dooble 1.56f on Haiku x86 (gcc7) doesn't fetch the Qt5 dependencies.

NOTE: 
1. Recipe works of Haiku x86_64 without change
2. Recipe doesn't work on Haiku x86 (gcc7) without change.
- Issue: Won't fetch 'devel:libQt5*' packages for the x86 build. **Last worked on hrev51988 x86.**
- See Buildrun: 1363

Tag: Bug

**Comment by extrowerk** [comment]
Doesnt makes any sense.

**Comment by kenmays** [comment]
Recent updates to QT/Webkit etc. - just requesting a respin of the package although I already verified the package rebuilds properly and works as expected without crashing during daily web browsing use (recently, it used to crash before I rebuilt them). Relate this to what Pulkomandy requested during the NetSurf 3.8 update.

**Comment by extrowerk** [comment]
Doesnt makes any sense.

**Comment by kenmays** [comment]
Ok. As I said, just a request.

**Comment by extrowerk** [comment]
Then you should write that in the issue, as clear as possible, with error messages.
Your issue gave us absolutely no info.
Please, do your best!

**Comment by korli** [comment]
Please post a build log.

**Comment by kenmays** [comment]
@korli - the recipe's build issue was in the 'pkgman install devel:libQt5Core' for the x86_gcc2 build. See if it works on your end (or the buildbot). Works fine on x86_64 build. Tested on hrev52369.

**Comment by korli** [comment]
works fine here on x86_gcc2.

**Comment by extrowerk** [comment]
@korli: thanks.
