### ISSUE TITLE
BePodder need a new release

### ISSUE THREAD

**Issue by janus2** [haikuports/haikuports#3153]
I think the recipe need some changes

- The librunview is gone.
- Documentation is now in packages/bepodder
- BePodder support localization

The new recipe should be something like this "Trust me, I don't know what I'm doing!":

BUILD()
{
	make $jobArgs -C library/libfish
	make $jobArgs -C library/libfunky
	make $jobArgs OBJ_DIR=objects -C sources
	make OBJ_DIR=objects bindcatalogs
}

INSTALL()
{
	docFolder=$documentationDir/packages/bepodder

	mkdir -p $appsDir/BePodder
	cp sources/objects/BePodder $appsDir/BePodder
	cp -a docs/ReadMe.html $docFolder
	cp -r docs/images $docFolder

	addAppDeskbarSymlink $appsDir/BePodder/BePodder
}

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/3154 (at your service) :)

**Comment by janus2** [comment]
Thanks!
