### ISSUE TITLE
Update glib2

### ISSUE THREAD

**Issue by TwoFX** [haikuports/haikuports#316]
The most recent version of glib2 available on Haikuports is 2.38.1, which was authored on [October 15, 2013](https://git.gnome.org/browse/glib/tag/?id=2.38.1). Several GNOME applications (such as GNOME Chess) require newer versions of glib2 in order to compile (e.g. GNOME Chess requires glib2 >= 2.40 from March 2014 to build) and thus cannot be ported to Haiku.

**Comment by waddlesplash** [comment]
Did you try to update it? Doesn't sound too hard. Unless they made drastic changes...

**Comment by DarkmatterVale** [comment]
Could I take a crack at this if no one else is already updating the recipe?

**Comment by diversys** [comment]
Go ahead
