### ISSUE TITLE
QT5 compiled apps not show .png picture

### ISSUE THREAD

**Issue by mazbrili** [haikuports/haikuports#3173]
when compile luckybackup https://sourceforge.net/projects/luckybackup/files/0.4.9/source/luckybackup-0.4.9.tar.gz/download
it is compiled successfully.. but on about box.. it is missing png graphics 
![captureluckybackup](https://user-images.githubusercontent.com/25004583/46279281-dee13b80-c592-11e8-8ae1-1f22c5e0253c.PNG)

**Comment by fbrosson** [comment]
This is cool! Did the program build without any patch?

If you built it with haikuporter using a recipe, did you include `devel:libpng16$secondaryArchSuffix` in `BUILD_REQUIRES` ?
If you built it without haikuporter, were `libpng16_x86_devel` (for x86_gcc2 hybrid) or `libpng16_devel` (for x86_64) installed?

**Comment by diversys** [comment]
All other images in this app are in PNG format as well. So this seems to be a bug in the app itself.

**Comment by korli** [comment]
you can use strace to check which file paths are probed by the application.

**Comment by mazbrili** [comment]
@diversys  how to do that..  (sorry for silly question).. i will do that before opening issue

**Comment by mazbrili** [comment]
> `kern_read_stat(0xffffffff, ":/luckyPrefix/luckybackup_96.png", true, 0x7f237db35e60, 0x80) = 0x80006003 No such file or directory (8 us)`

ok got it..  new knowledge for me to use strace..

**Comment by mazbrili** [comment]
after i add qlabel on top background that i mention.. image show.. i dont know about this is normal or not..
right now i will close this ticket and make recipe for luckybackup..
thanks for all
