### ISSUE TITLE
Arduino needs update of recipe following OpenJDK update

### ISSUE THREAD

**Issue by HutchSails** [haikuports/haikuports#318]
The new version of Openjdk is Openjdk_x86-1.7.u80_b32-3, but current Arduino recipe calls for Openjdk_x86-1.7.u80_b32-2.  The Arduino recipe needs update of deps to new OpenJDK.
  - Thanks

**Comment by threedeyes** [comment]
Arduino package broken now and need to rebuild.

**Comment by threedeyes** [comment]
Fixed in 6c8716f
