### ISSUE TITLE
games-engines/instead: Should use find_directory() to look for user data.

### ISSUE THREAD

**Issue by alaviss** [haikuports/haikuports#3185]
https://github.com/haikuports/haikuports/blob/951f08c95e76ebed8bd4c8af5ce9cc93039d2d18/games-engines/instead/instead-3.2.2.recipe#L5

Currently `instead` looks for games in a dot directory in `HOME`. This is discouraged and the app should instead (no pun intended) look for games in `B_FIND_PATH_DATA_DIRECTORY`. This could be done with [`BPathFinder`](https://www.haiku-os.org/docs/api/classBPathFinder.html) or [`find_paths`](https://www.haiku-os.org/docs/api/FindDirectory_8h.html#ad96d494ae8950a8828043fd21db79231)

**Comment by diversys** [comment]
Looping @gl00my.

**Comment by gl00my** [comment]
In ~/.instead/ there are settings, games, user themes and other custom files. So, may be it is a good idea to use B_FIND_PATH_SETTINGS_DIRECTORY? Or  both?

Anyway, this code gives me an empty string. Can you give me more information?

	status_t status = find_path((void*)appdir, B_FIND_PATH_DATA_DIRECTORY,
		"Instead", dir, sizeof(dir));
	printf("%s\n", dir);

**Comment by gl00my** [comment]
From manual:
B_FIND_PATH_DATA_DIRECTORY | The base directory used for read-only data. SinceHaiku R1

Instead needs R/W directory. So B_FIND_PATH_DATA_DIRECTORY  can't be used.

B_FIND_PATH_DATA_DIRECTORY | The base directory used for read-only data. SinceHaiku R1
-- | --

**Comment by gl00my** [comment]
Ok, after installing package i got working find_path.
So, should i use B_FIND_PATH_SETTINGS_DIRECTORY?

**Comment by alaviss** [comment]
I pointed you to [`find_paths`](https://www.haiku-os.org/docs/api/FindDirectory_8h.html#ad96d494ae8950a8828043fd21db79231) because it returns a set of possible paths for you to check (one of which is `B_USER_NONPACKAGED_DATA_DIRECTORY`, which is RW). This only works if `~/.instead` only contains games. But since that folder contains more than just games, I would recommend [`find_directory`](https://www.haiku-os.org/docs/api/FindDirectory_8h.html#af95c55d472448ab7af9f32c33aeea71e) instead, with constant `B_USER_VAR_DIRECTORY` or `B_USER_SETTINGS_DIRECTORY`.

**Comment by gl00my** [comment]
Currently i use find_path and  B_FIND_PATH_SETTINGS_DIRECTORY - is it not ok? 
find_path is more clean to me as my project is C project.

**Comment by alaviss** [comment]
For your use case, it's absolutely not OK. You want to retrieve the user's settings directory, which `find_path` won't be able to give you. `find_path` can only find the global settings directory, which I believe is not what you want. I don't see why `find_directory` wouldn't be as clear. It's also a C api.

**Comment by gl00my** [comment]
Ok, got it.

**Comment by gl00my** [comment]
Btw, curently r/o data (lang files, lua files, tutorial game and so on)  is located inside applications dir (apps/Instead/data) is it ok? Or i should install data in separated data? (data/Instead)?

**Comment by pulkomandy** [comment]
find_path can of course find user directories as well. We really should document the API, however.

**Comment by alaviss** [comment]
I forgot to mention, once you've moved `instead` settings directory to a formal path, you should add [`USER_SETTINGS_FILES`](https://github.com/haikuports/haikuports/wiki/HaikuPorter-BuildRecipes#user_settings_files) to the recipe, describing the location. It's currently pure metadata and not exposed via the GUI AFAIK, but might become useful in the future.
