### ISSUE TITLE
Gutenprint 5.3.1 questions

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#3186]
I have a few questions about this package since building it on both Beta and current nightly for 64 bit.

- why is the new release named gutenprint8? Shouldn't it just be gutenprint-5.3.1?
- there is no way to select the new driver package once installed. Haiku defaults gutenprint 5.2.14
- I would think that the new package should replace the old one, and not live side-by-side
- the wrapper-script that is generated when building the package still refers to haikuVersion='r1~alpha1' on line 11. Shouldn't that be Beta now?
- when I tweak the recipe and patchset to read gutenprint, instead of gutenprint8, it still builds OK. However, when attempting to install the package I get this error: "requires haiku>=r1-beta1_hrev52295_100-1, but none of the providers can be installed". Why?

**Comment by fbrosson** [comment]
@korli added gutenprint `5.3.1` in 9c68aecfb29b3f0b4260259af5634602b58d8d0c using a different name to allow it to co-exist with gutenprint `5.2.x`.
(The `8` comes from the lib's soname.)

Maybe we should rename each `gutenprint-5.2.x.recipe` to `gutenprint2-5.2.x.recipe`, adapting the `PROVIDES*`, and rename `gutenprint8-5.3.1.recipe` to `gutenprint-5.3.1.recipe`, also adapting the `PROVIDES*`.
But this can only be done once every recipe which uses gutenprint `5.2.x` has been tested to work correctly with gutenprint `5.3.1`.

Regarding your other questions about `r1~alpha1` vs `r1-beta1`, I guess we need to update the build bots to include a newer haiku and haiku_devel in their default set of available packages. @mmlr please correct me if I'm wrong. Thanks!

**Comment by korli** [comment]
When Haiku builds OK with gutenprint 5.3.1, gutenprint 5.2 could be dropped, I believe that no recipe depends on it.

**Comment by korli** [comment]
I fixed gutenprint gcc2 build in c57faf08e611e65c201e3b9b7dd6b4d2daf8d276 and pushed a change to take the new version in Haiku: https://review.haiku-os.org/c/haiku/+/1407
