### ISSUE TITLE
[mplayer] implement cpu detection for Haiku

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#319]
It looks like for -enable-runtime-cpudetection https://github.com/haikuports/haikuports/blob/888605d829a0601a4e74f672f48e7c3677882891/media-video/mplayer/mplayer-1.1.1.recipe#L131 to actually work we need to add some OS support in
https://github.com/gbeauchesne/mplayer-vaapi/blob/master/cpudetect.c#L33

**Comment by waddlesplash** [comment]
Fixed in #960.

**Comment by diversys** [comment]
Looking at cpudetect.c I don't think it was implemented yet in #960

**Comment by waddlesplash** [comment]
See the output in the PR description - it looks like it's working?

**Comment by diversys** [comment]
I'm not sure, I thought it required platform specific code in cpudetect.c

My old mplayer running in VMware:

```
mplayer -v
MPlayer 1.1-4.8.4 (C) 2000-2012 MPlayer Team
CPU vendor name: GenuineIntel  max cpuid level: 13
CPU: Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz (Family: 6, Model: 58, Stepping: 9)
extended cpuid-level: 8
extended cache-info: 16801856
Detected cache-line size is 64 bytes
Cannot test OS support for SSE, leaving disabled.
CPUflags:  MMX: 1 MMX2: 1 3DNow: 0 3DNowExt: 0 SSE: 0 SSE2: 0 SSSE3: 1
Compiled with runtime CPU detection.

```

**Comment by diversys** [comment]
That might be because it was under VMware. @threedeyes what would you say?
