### ISSUE TITLE
recipe for liblqr

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#3202]
http://liblqr.wikidot.com/
depends on glib2

http://liblqr.wdfiles.com/local--files/en:download-page/liblqr-1-0.4.2.tar.bz2
LGPL
 2007-2009 Carlo Baldassi

**Comment by korli** [comment]
This could be used by photivo.

**Comment by Begasus** [comment]
Committed in https://github.com/haikuports/haikuports/blob/fe593927823285954c7c49d0845e916b091f79d0/media-libs/liblqr/liblqr-0.4.2.recipe
