### ISSUE TITLE
Qt5 - error running some qt apps

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#321]
After installing Qt5 packages (Qt5 and qt5_x86_devel), I get an error when running any items of the 'Qt' menu folder (Assistant, Designer, QML Viewer, Qt Assistant, etc.).

Previously (with the Qt4.8 package) that apps worked well.  Also, after the update, the 4.8 apps (like Qupzilla, for example, continues to work well).

I'm using hrev49730 x86_gcc2, on real hardware.

I attach two of the crash reports.  If you need more details, you could find me in the #haiku channel (_Dario_ nickname).

Thank you!

**Comment by unspacyar** [comment]
Sorry, I can't attach txt files here.  I post the crash reports here:

http://pastebin.com/aK0R8LL3
http://pastebin.com/SF7qs6hz

**Comment by diversys** [comment]
You need to rename .report to .txt to attach them.

**Comment by unspacyar** [comment]
Hello.  I tried to rename it to txt, but the site says that I need to be a "Collaborator" to attach it (aparently, I only can attach images: jpg, png, etc.).

**Comment by pulkomandy** [comment]
Which version of Qt5 was it? Have you tried the latest Qt5.6 recipe?

**Comment by unspacyar** [comment]
pulkomandy:  apparently, the crashes was caused because my CPU doesn't support SSE2 instructions (an Athlon XP).  When upgrade to a more modern computer, the issue dissapeared.

**Comment by mmuman** [comment]
I also had this issue when building my own Qt packages, I had to force the cpu target with -mtune or something in the recipe.

**Comment by korli** [comment]
Well seeing: https://bugs.archlinux.org/task/38796 https://bugreports.qt.io/browse/QTBUG-35430 and https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/qt5-base#n67
we should probably add the option -no-sse2 on x86 builds.
Optionally (the SSE2 libs are QtCore, QtGui and QtDeclarative): 

> If the distribution really requires support for those older CPUs, we highly 
recommend you compile Qt 5 libraries twice and install the SSE2-requiring 
version in $prefix/lib/sse2. The Linux dynamic linker searches for libraries 
there on its own already and has done that for a really long time. All 
binaries should come only from the -no-sse2 build.

**Comment by mmuman** [comment]
Given how much time is required to compile them once already... :-)))

**Comment by mmuman** [comment]
Btw this is still a problem here, and webkit also crashes in the same way.

**Comment by mmuman** [comment]
I just built webkit with -mstackrealign and it works fine.

**Comment by pulkomandy** [comment]
We should fix these stack alignment problems for good in Haiku. -mstackrealign should not be needed when using a modern gcc.
