### ISSUE TITLE
Musescore should be in appsdir, not boot/system/bin

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#3217]

**Comment by diversys** [comment]
Can't find Musicscore in haikuports.

**Comment by scottmc** [comment]
Typo.  It's Musescore.

**Comment by Begasus** [comment]
Having mscore in $appsDir isn't the only issue here I think, data is installed in $prefix/share and moved around to $dataDir, having the binary makes it startup but fails to find some workspaces conf file and crashes after that ...

**Comment by waddlesplash** [comment]
You need to tell the build script to install things to $appsDir directly.

**Comment by Begasus** [comment]
Then best bet would be to use PREFIX=$appsDir/MuseScore 
Other option would be to see where it sets the paths to ./self/share and change them to ./self/data (had checked that option but so far the installation still went into ./self/share)
