### ISSUE TITLE
musescore could use a nice Haiku icon

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#3218]

**Comment by ojasva** [comment]
Why not just use the logo from musescore.org as icon?

**Comment by korli** [comment]
I tried to import one of the svg assets from https://github.com/musescore/MuseScore/tree/master/assets in Icon-O-Matic. I couldn't get any to work.

**Comment by diversys** [comment]
Fixed in 920cfdc687678c64daa113864b6c0a1efa4c5d25.
