### ISSUE TITLE
Add abseil-cpp

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#3224]
https://github.com/abseil/abseil-cpp

**Comment by korli** [comment]
dev-cpp/abseil-cpp

**Comment by korli** [comment]
I'm not sure it's a such good idea to port some random lib which no project depends on. It won't probably be tested. Or do you have a use case for it?

**Comment by fbrosson** [comment]
I guess @scottmc would like to use if for https://www.tensorflow.org/.

**Comment by korli** [comment]
It doesn't look it's a hard dependency anyway, almost no port has it: https://repology.org/metapackages/?search=abseil

**Comment by fbrosson** [comment]
IDK, but both ArchLinux and Gentoo use if for TensorFlow, although Gentoo uses a Git snapshot inside TensorFlow's ebuild because it does not have a separate ebuild for abseil.

**Comment by fbrosson** [comment]
You are right. TensorFlow does not require abseil-cpp.
I made a confusion with python-tensorflow, which requires "Abseil Python Common Libraries" (i.e. absl-py on ArchLinux),
Links for convenience:
* https://github.com/abseil/abseil-cpp
* https://github.com/abseil/abseil-py
* https://www.archlinux.org/packages/community/any/absl-py/
* https://www.archlinux.org/packages/community/x86_64/python-tensorflow/
* https://www.archlinux.org/packages/community/any/python-tensorflow-serving-api/
* https://www.archlinux.org/packages/community/x86_64/tensorboard/
