### ISSUE TITLE
Album - Album hangs the entire S.O. when loading > 1400 thumbnails

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#324]
When browse a folder with more of 1400 pics, the Album app hangs after loading about 1300 thumbnails.  The app hangs the entire operative system.

The syslog doesn't show any error.  The last message is:
KERN: slab memory manager: created area 0xdf801000 (10610).

**Comment by waddlesplash** [comment]
This should be reported to Haiku's bugtracker (and possibly Album's), not here.

**Comment by unspacyar** [comment]
Sorry Waddlesplash!  I thinked that Album was part of Haikuports.
My apologies.
