### ISSUE TITLE
Write recipe for dbuspython

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#3247]
http://dbus.freedesktop.org/releases/dbus-python

**Comment by Begasus** [comment]
wip https://github.com/haikuports/haikuports/pull/4442#

**Comment by Begasus** [comment]
IMHO it should be dev-python/dbus-python for https://github.com/haikuports/haikuports/pull/4442
Repology yields zero maches for dbuspython: https://repology.org/projects/?search=dbuspython
For dbus-python it yields 180 pachages: https://repology.org/project/python:dbus-python/versions

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/4442
