### ISSUE TITLE
Sync Qemu with upstream version

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#325]
Currently it's Qemu 2.4.1 while https://github.com/mmlr/qemu-haiku/ is stuck on 2.1.2

**Comment by pulkomandy** [comment]
The upstream version builds with the SDL interface, but last time I tried, it crashed after a few seconds. mmlr's native UI avoids the problem, so we need to keep his changes.

**Comment by diversys** [comment]
Closed in favour of #3575.
