### ISSUE TITLE
Create an icon for Drawpile 

### ISSUE THREAD

**Issue by return** [haikuports/haikuports#3261]
The homepage logo could be used as a starting point for a Haiku icon for the Drawpile recipe.
https://drawpile.net/
https://github.com/haikuports/haikuports/blob/master/media-gfx/drawpile/drawpile-2.0.10.recipe#L65

Please mark this as a GCI 'task'.

**Comment by fbrosson** [comment]
Does someone know if the icon needs to be a vector image created with Icon-O-Matic? Or would it be OK to create a bitmap icon, also with Icon-O-Matic ?

@humdingerb, we have GCI student who has asked the question but I don't really know the answer. The task instance is [5729519617966080](https://codein.withgoogle.com/dashboard/task-instances/5729519617966080).
