### ISSUE TITLE
LibreOffice: copy&paste between documents doesn't work

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#3262]
Title says it all.

**Comment by diversys** [comment]
Clipboard support was added to KDE5 vcl very recently: https://cgit.freedesktop.org/libreoffice/core/log/?qt=grep&q=clipboard.

So all that is needed is updating LO to the current version, however there is still a problem with configure.ac - it detects stack protector again.

**Comment by diversys** [comment]
Copy&paste works now as of 524e2b6c309783de582742fb63faf8b1c4643dce. There are some clipboard bugs in Qt5 QPA plugin which is being worked on by @threedeyes.
