### ISSUE TITLE
clang-6.0.1-4 is broken.

### ISSUE THREAD

**Issue by khallebal** [haikuports/haikuports#3291]
Calling any of the binaries results in crash.

Active Threads:
	thread 70356: team 70355 debug task 
	thread 70355: clang-cpp (main)
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x72549e28	0x31edb08	llvm::StringMapImpl::LookupBucketFor(llvm::StringRef) + 0x48 
			Disassembly:
				llvm::StringMapImpl::LookupBucketFor(llvm::StringRef):
				0x031edac0:               55  push %ebp
				0x031edac1:       e84948faff  call 0x319230f
				0x031edac6:       059e270c03  add $0x30c279e, %eax
				0x031edacb:             89e5  mov %esp, %ebp
				0x031edacd:               57  push %edi
				0x031edace:               56  push %esi
				0x031edacf:               53  push %ebx
				0x031edad0:           83ec2c  sub $0x2c, %esp
				0x031edad3:           8945d8  mov %eax, -0x28(%ebp)
				0x031edad6:           8b450c  mov 0xc(%ebp), %eax
				0x031edad9:           8b4d10  mov 0x10(%ebp), %ecx
				0x031edadc:           8945dc  mov %eax, -0x24(%ebp)
				0x031edadf:           8b4508  mov 0x8(%ebp), %eax
				0x031edae2:           8b5804  mov 0x4(%eax), %ebx
				0x031edae5:             85db  test %ebx, %ebx
				0x031edae7:             745e  jz 0x31edb47
				0x031edae9:           8d43ff  lea -0x1(%ebx), %eax
				0x031edaec:             85c9  test %ecx, %ecx
				0x031edaee:           8945e0  mov %eax, -0x20(%ebp)
				0x031edaf1:             747a  jz 0x31edb6d
				0x031edaf3:           8b55dc  mov -0x24(%ebp), %edx
				0x031edaf6:             31f6  xor %esi, %esi
				0x031edaf8:             89d0  mov %edx, %eax
				0x031edafa:             01ca  add %ecx, %edx
				0x031edafc:         8d742600  lea (%esi), %esi
				0x031edb00:             89f7  mov %esi, %edi
				0x031edb02:               40  inc %eax
				0x031edb03:           c1e705  shl $0x5, %edi
				0x031edb06:             01fe  add %edi, %esi
				0x031edb08:         0fb678ff  movzx -0x1(%eax), %edi <--

			Frame memory:
				[0x72549df0]  . ^.`.Tr(.Tr}...   08 20 5e 00 60 9e 54 72 28 9e 54 72 7d 9c ed 00
				[0x72549e00]  d.+.0.......i...   64 02 2b 06 30 b3 96 02 ff 07 00 00 69 9c ed 00
				[0x72549e10]  .G...`......d.+.   1c 47 ee 00 03 60 00 80 f2 b8 90 02 64 02 2b 06
				[0x72549e20]  ........           80 1c b0 02 1d 00 00 00
		0x72549e98	0x31b96b5	_GLOBAL__N_1::CommandLineParser::addOption(llvm::cl::Option*, llvm::cl::SubCommand*) + 0x95 
		0x72549ec8	0x31b9a43	llvm::cl::Option::addArgument() + 0xc3 
		0x72549ee8	0x11876e1	_GLOBAL(int16, , bool, , , , double, , , , , double, , int32, , , int8, , ) + 0x151 
		0x72549f28	0xece3df	init_dependencies(image_t*, bool) + 0xef 
		0x72549f98	0xece834	load_program + 0xc8 
		0x72549fd8	0xed6f0d	runtime_loader + 0x105 
		00000000	0x67cf7250	commpage_thread_exit + 0 

		Registers:
			  eip:	0x031edb08
			  esp:	0x72549df0
			  ebp:	0x72549e28
			  eax:	0x0296b331
			  ebx:	0x00000800
			  ecx:	0x0000001d
			  edx:	0x0296b34d
			  esi:	0x00000000
			  edi:	0x00000000
			   cs:	0x001b
			   ds:	0x0023
			   es:	0x0023
			   fs:	0x0063
			   gs:	0x0023
			   ss:	0x0023
			  st0:	nan
			  st1:	nan
			  st2:	nan
			  st3:	nan
			  st4:	nan
			  st5:	0
			  st6:	1.04e+05
			  st7:	0.1
			  mm0:	{0xc87, 0x6000, 0, 0}
			  mm1:	{0x18, 0, 0, 0}
			  mm2:	{0x87f, 0, 0, 0}
			  mm3:	{0xf41, 0, 0, 0}
			  mm4:	{0xfbff, 0xbfeb, 0, 0}
			  mm5:	{0, 0, 0, 0}
			  mm6:	{0, 0, 0x8000, 0xcb41}
			  mm7:	{0xd000, 0xcccc, 0xcccc, 0xcccc}
			 xmm0:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm1:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	44882	0x00ab6000	0x00c09000	0x00c09000	0x00c17000	lib    	/boot/system/lib/x86/libstdc++.so.6.0.24
	44883	0x00ea7000	0x00ebf000	0x00ebf000	0x00ec0000	lib    	/boot/system/lib/x86/libgcc_s.so.1
	44879	0x00ec5000	0x00ee4000	0x00ee4000	0x00ee7000	lib    	/boot/system/runtime_loader
	44880	0x00ef0000	0x02a78000	0x02a78000	0x02b04000	app    	/boot/system/bin/clang-6.0
	44884	0x02b14000	0x02bf7000	0x02bf7000	0x02c38000	lib    	/boot/system/lib/x86/libroot.so
	44885	0x02c40000	0x02c58000	0x02c58000	0x02c59000	lib    	/boot/system/lib/x86/libz.so.1.2.11
	44881	0x02c5d000	0x06046000	0x06046000	0x0630a000	lib    	/boot/system/lib/x86/libLLVM-6.0.so
	44878	0x67cf7000	0x67cff000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	270465	0x00386000	0x003ae000	       160	rw-        	full          	rld heap
	270464	0x00415000	0x0043d000	       160	rw-        	full          	rld heap
	270447	0x004b8000	0x004b9000	         4	rw-S       	full          	_rld_debug_
	270446	0x005e2000	0x005f2000	        64	rw-        	full          	rld heap
	270454	0x00ab6000	0x00c09000	      1356	r-x        	full          	libstdc++.so.6.0.24_seg0ro
	270455	0x00c09000	0x00c10000	        28	rw-        	full          	libstdc++.so.6.0.24_seg1rw
	270456	0x00c10000	0x00c17000	        28	rw-        	full          	libstdc++.so.6.0.24_seg2rw
	270457	0x00ea7000	0x00ebf000	        96	r-x        	full          	libgcc_s.so.1_seg0ro
	270458	0x00ebf000	0x00ec0000	         4	rw-        	full          	libgcc_s.so.1_seg1rw
	270443	0x00ec5000	0x00ee4000	       124	r-x        	full          	runtime_loader_seg0ro
	270444	0x00ee4000	0x00ee6000	         8	rw-        	full          	runtime_loader_seg1rw
	270445	0x00ee6000	0x00ee7000	         4	rw-        	full          	runtime_loader_bss1
	270448	0x00ef0000	0x02a78000	     28192	r-x        	full          	clang-6.0_seg0ro
	270449	0x02a78000	0x02b02000	       552	rw-        	full          	clang-6.0_seg1rw
	270450	0x02b02000	0x02b04000	         8	rw-        	full          	clang-6.0_seg2rw
	270459	0x02b14000	0x02bf7000	       908	r-x        	full          	libroot.so_seg0ro
	270460	0x02bf7000	0x02c01000	        40	rw-        	full          	libroot.so_seg1rw
	270461	0x02c01000	0x02c38000	       220	rw-        	full          	libroot.so_seg2rw
	270462	0x02c40000	0x02c58000	        96	r-x        	full          	libz.so.1.2.11_seg0ro
	270463	0x02c58000	0x02c59000	         4	rw-        	full          	libz.so.1.2.11_seg1rw
	270451	0x02c5d000	0x06046000	     53156	r-x        	full          	libLLVM-6.0.so_seg0ro
	270452	0x06046000	0x062d0000	      2600	rw-        	full          	libLLVM-6.0.so_seg1rw
	270453	0x062d0000	0x0630a000	       232	rw-        	full          	libLLVM-6.0.so_seg2rw
	270466	0x180e0000	0x18140000	       384	rw-        	full          	heap
	270440	0x60736000	0x6073a000	        16	rw-        	full          	user area
	270442	0x67cf7000	0x67cff000	        32	r-xSk      	full          	commpage
	270441	0x71546000	0x7254c000	     16408	rw-s       	full          	clang-cpp_70355_stack

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------

**Comment by waddlesplash** [comment]
@return

**Comment by return** [comment]
@khallebal Which version / architecture of Haiku are you running and are you able to reproduce this crash?

**Comment by khallebal** [comment]
I use the beta hrev52295+100.
Oh it's broken alright, no doubt.
If it's not broken on regular nightlies that may be a hint it's time to branch a beta haikuports.

**Comment by korli** [comment]
Can't reproduce on beta. x86_gcc2

**Comment by khallebal** [comment]
In the meantime i switched to regular nightlies, and the situation has improved slightly in a way that some of the binaries don't crash others still do with the an identical trace i already submitted,
Am i the only one experiencing this crashes?

**Comment by khallebal** [comment]
With an update to hrev52579 and llvm6-6.0.1-5 the crashes now have gone away.
