### ISSUE TITLE
binutils: Fix for liberty testsuite

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3294]
Fix on all archs: **hp --test binutils**
This patch fixes a small test issue with binutils >= 2.26.1 test-pexecute.
[binutils-2.31.1_test-pexecute_patch.txt](https://github.com/haikuports/haikuports/files/2523102/binutils-2.31.1_test-pexecute_patch.txt)

Tag: Enhancement

**Comment by fbrosson** [comment]
Thanks @kenmays!
(I'll give it a try.)
