### ISSUE TITLE
[FPC] [PATCH] Recipe to construct a fpc 3.0.0 package for Haiku, based on  the official package.

### ISSUE THREAD

**Issue by oco27** [haikuports/haikuports#331]
Recipe to construct a fpc 3.0.0 package for Haiku, based on the official package. It will help bootstrapping a more classical recipe that will construct the package from sources. Based on work on 2.6.2 at BeGeistert 029 with Korli.

The corresponding package is available at http://nan.tf/download/fpc_bin-3.0.0-1-x86_gcc2.hpkg

[0001-recipe-to-construct-a-fpc-3.0.0-package-for-Haiku-ba.patch.txt](https://github.com/haikuports/haikuports/files/46787/0001-recipe-to-construct-a-fpc-3.0.0-package-for-Haiku-ba.patch.txt)

**Comment by waddlesplash** [comment]
Can you submit this as a pull request please?

**Comment by humdingerb** [comment]
How's the PR coming, oco? :)   
I had a quick look. Is the cmd:fpc in BUILD_PREREQUIRES really correct? I thought the fpc_bin package is exactly created to provide this to bootstrap the actual fpc package. (BTW, should the fpc_bin recipe be in its own folder, i.e. dev-lang/fpc_bin/ ? That's how it is for openttd etc.)

Trying to build I get:
```
POLICY ERROR: Invalid top-level package entry "doc"
POLICY ERROR: Invalid top-level package entry "share"
POLICY ERROR: no matching provides "cmd:cvsco.tdf" for "bin/cvsco.tdf"
POLICY ERROR: no matching provides "cmd:cvsdiff.tdf" for "bin/cvsdiff.tdf"
POLICY ERROR: no matching provides "cmd:cvsup.tdf" for "bin/cvsup.tdf"
POLICY ERROR: no matching provides "cmd:fp.ans" for "bin/fp.ans"
POLICY ERROR: no matching provides "cmd:gplprog.pt" for "bin/gplprog.pt"
POLICY ERROR: no matching provides "cmd:gplunit.pt" for "bin/gplunit.pt"
POLICY ERROR: no matching provides "cmd:grep.tdf" for "bin/grep.tdf"
POLICY ERROR: no matching provides "cmd:makeskel.rsj" for "bin/makeskel.rsj"
POLICY ERROR: no matching provides "cmd:program.pt" for "bin/program.pt"
POLICY ERROR: no matching provides "cmd:ptop.rsj" for "bin/ptop.rsj"
POLICY ERROR: no matching provides "cmd:tpgrep.tdf" for "bin/tpgrep.tdf"
POLICY ERROR: no matching provides "cmd:unit.pt" for "bin/unit.pt"
```
Have a look what's in dev-lang/fpc/work-3.0.0/packaging/fpc_bin/ to see what ended up in "doc" and "share".

**Comment by oco27** [comment]
Hi,
I am new to the github work flow... If i understand things correctly, what i need to do is fork the haikuport repository on github first and make the pull request from there, right ? Then, do you know if it is possible to switch my current repository to the forked one without loosing my changes ? It would save me a full download.

I will have a lot more time next week.

About errors, i thought it was only warnings on my computer. My first goal was to have something to convert the classical freepascal package for Haiku (http://www.freepascal.org/download.var) to  a working Haiku's package with the less effort as possible. It is what the proposed recipe is about. The second planned step was to integrate the process used to generate the classical package in the recipe itself (http://wiki.freepascal.org/Haiku_specific_Release_Engineering). The prerequisite on fpc is an anticipation of this : the a binary version of the compiler is required to compile freepascal. Maybe it it not the right way to do this.

About doc and share, it is somme documentation and samples files. It seems this is where there are installed on others unix like platform. Maybe those files should be copied in another location under Haiku ?

About other "commands", i don't know how to handle this : they are not real command but files (mostly templates) used by some commands and searched in the same directory as the commands it seems. Should i declare them as commands to avoid the message ?

**Comment by waddlesplash** [comment]
> Then, do you know if it is possible to switch my current repository to the forked one without loosing my changes ?

`git push <remote url> --set-upstream master:master` should do that.

**Comment by mmuman** [comment]
I usually keep the official repo as 'origin' for checkouts, and register my own fork as 'github':
```
git remote add github <remote url>
```
Then I do:
```
git push github mybranch
```
(I usually work in a branch, but master can do as well)
If you want to update master from origin before pushing:
```
git stash
git checkout master # if not already on
git pull --rebase origin
git checkout mybranch # if different
git stash pop
```

**Comment by pulkomandy** [comment]
I would recommend using the "hub" tool to work with github (available in the haiku repos).
In particular, "hub fork" and "hub pull-request" commands would do most of what you need.

**Comment by waddlesplash** [comment]
Merged.
