### ISSUE TITLE
gcompris 0.70 -compiled but activities icon not shown

### ISSUE THREAD

**Issue by mazbrili** [haikuports/haikuports#3340]
try gcompris on x86_64.. after edit recipe to enable compile.. gcompris  compiled but activities icon not show... 
![image](https://user-images.githubusercontent.com/25004583/47988468-ddb4a880-e114-11e8-8ae0-b3a22138ec03.png)

it supposed to be (if not problem)
![image](https://user-images.githubusercontent.com/25004583/47988510-f7ee8680-e114-11e8-84b4-2ab8b56d5fbb.png)

**Comment by extrowerk** [comment]
It doesnt looks like a HP bug, have you tried to contact the authors?

**Comment by Begasus** [comment]
Checkout out the latest version seems to be fine. :)

![GCompris-3 3](https://github.com/haikuports/haikuports/assets/16057090/a918316b-98d3-4a83-b69f-689e49a57a01)

**Comment by Begasus** [comment]
Fixed in: https://github.com/haikuports/haikuports/pull/9787
