### ISSUE TITLE
qaceedit: Error! Unable to find ace on startup(Added screenshot)

### ISSUE THREAD

**Issue by ojasva** [haikuports/haikuports#3341]
![ace](https://user-images.githubusercontent.com/44553464/47999151-a7345900-e127-11e8-8682-bef6e29683dd.png)

**Comment by extrowerk** [comment]
Where did you got it? There is no qaceedit in HaikuPorts. Report this problem at the provider (repository owner).

**Comment by extrowerk** [comment]
It seems it comes from the repo of Clasqm.
Report this for him.

**Comment by extrowerk** [comment]
For reference: https://depot.haiku-os.org/#!/?bcguid=bc1-WHFP&repos=besly,clasqm,haikuports,fatelk&arch=x86_gcc2&viewcrttyp=FEATURED&srchexpr=Qaceedit
