### ISSUE TITLE
KDevelop can't find clang header files in the libdir

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#3379]
At least it is the case with 6.0.1 on 64 bit.
Headers located at ```/boot/system/lib/clang/6.0.1/include```

But ```llvm-config --includedir``` says:
/boot/system/develop/headers

**Comment by extrowerk** [comment]
@return

**Comment by extrowerk** [comment]
LLVM5 also bugous.

**Comment by waddlesplash** [comment]
I think this is intentional...

**Comment by alaviss** [comment]
> Headers located at `/boot/system/lib/clang/6.0.1/include`

Headers there are used by the clang compiler. This is normal, although it should be in the `_clang` subpackage.

**Comment by korli** [comment]
Gcc does the same if one wonders.

**Comment by extrowerk** [comment]
@korli: KDevelop searching for the clang header files in the normal include paths, but not in the libdir.

**Comment by Begasus** [comment]
Any project to check this with? Latest KDevelop I have here is already on LLVM18. This was checked while testing LLVM18 builds for QtCreator/Clazy and KDevelop which use llvm-config or the cmake config files, so far I haven't seen any problem.

**Comment by Begasus** [comment]
Closing as fixed.
