### ISSUE TITLE
recipe for libshout and icecast-server

### ISSUE THREAD

**Issue by Barrett17** [haikuports/haikuports#3405]
Libshout: http://downloads.xiph.org/releases/libshout/libshout-2.4.1.tar.gz
Icecast download page (for icecast server): http://www.icecast.org/download/

**Comment by Begasus** [comment]
For libshout: https://github.com/haikuports/haikuports/commit/5bdf56eab7da3d10df3f38717b34fa32d18c5023
(needs support for libtheora and libspeex - working on that)

**Comment by Begasus** [comment]
PR for libshout: https://github.com/haikuports/haikuports/pull/3478
PR for icecast: https://github.com/haikuports/haikuports/pull/3479
Both building and installing fine under all arch's

**Comment by Begasus** [comment]
Icecast and libshout got merged, closing this one :)
