### ISSUE TITLE
armagetronad crashes

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3407]
On hrev53158:
x86_gcc2: Builds OK. Hangs before intro screen during launch.
x86_64: Builds OK. Hangs before intro screen during launch.

**Comment by kenmays** [comment]
Closing ticket. Package not in x86_64 repo.

**Comment by Begasus** [comment]
afaik this has been a problem before also? If not I'll revert the changes

**Comment by Begasus** [comment]
Last changes in the recipe shouldn't make any difference in how this works, needs more investigations to get this running on Haiku

**Comment by kenmays** [comment]
The recipe change is fine. The program hangs now with the newer kernel changes (versus hrev53144).
No program startup menu display yet (only open/closes GL window) ten hangs in terminal. Ctrl-C kills it.

Debugging:

$ armagetronad
Trying to start sound. Just restart Armagetron Advanced in case of crash.
GalliumContext: CreateScreen: Using llvmpipe (LLVM 7.0, 128 bits) driver.
Unlocking BLocker with sem 3939 from wrong thread 599, current holder -1 (see issue #6400).
Unlocking BLocker with sem 3940 from wrong thread 594, current holder -1 (see issue #6400).
Kill Thread

$ uname -a
Haiku shredder 1 hrev53158 May 22 2019 14:26:42 BePC x86 Haiku


===

Debug information for team /boot/home/atron/bin/armagetronad (11038):
CPU(s): 2x Intel Core
Memory: 1021.50 MiB total, 367.98 MiB used
Haiku revision: hrev53144 May 18 2019 11:21:28 (BePC)

Active Threads:
	thread 11039: SDL 
	thread 11043: direct daemon 
	thread 11044: _BMediaRoster_ 
	thread 11048: pthread func 
	thread 11049: pthread func 
	thread 11050: w>Untitled 
	thread 11051: team 11038 debug task 
	thread 11038: armagetronad (main)
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		**0x7293deb8	0x1efb7a7	__strtod_internal + 0x97**

**Comment by Begasus** [comment]
Seen it also here, alongside with some other recipes (which are disabled probably for a reason), maybe someone could fix these in the future :)

**Comment by kenmays** [comment]
Revisit issue after approved by maintainer(s). W-I-P.
