### ISSUE TITLE
GCC: towlower crashes on emoji

### ISSUE THREAD

**Issue by KapiX** [haikuports/haikuports#3410]
Description here: https://github.com/KapiX/Koder/issues/74

To reproduce:
```c++
#include <cwctype>

int main() {
    wint_t glassEmoji = 128269;
    wint_t lower = towlower(glassEmoji); // crash
    return 0;
}
```

Does not happen on Linux (openSuSE TW); GCCs used:
- `gcc-7 (SUSE Linux) 7.3.1 20180817 [gcc-7-branch revision 263612]`
- `gcc (SUSE Linux) 8.2.1 20181108 [gcc-8-branch revision 265914]`

**Comment by korli** [comment]
Why would this be a GCC problem?

**Comment by korli** [comment]
No, the crash in http://ix.io/1udW happens at line 127, which isn't ICU.

towlower() and towupper() should do like iswctype() and check the character range when gLocaleBackend is NULL.

**Comment by waddlesplash** [comment]
We really should drop the ICU addin and use `musl`'s C locale backend instead...

**Comment by korli** [comment]
@waddlesplash What does this have to do with this problem?

**Comment by waddlesplash** [comment]
Well, it would solve bugs like these by completely replacing the underlying code...?

**Comment by pulkomandy** [comment]
musl libc implementation:
https://git.musl-libc.org/cgit/musl/tree/src/ctype/tolower.c

This will fail on any accented character. I want tolower('Ê') to do the right thing. Not to mention turkish dotted vs non-dotted i and other crazyness.

Locales are hard. Leave it to the ICU professionals.

**Comment by waddlesplash** [comment]
Huh? This is about "towlower". Passing Unicode to that is against the specification. Musl implements towlower correctly, yes?

**Comment by korli** [comment]
This is a Haiku issue, closing.

**Comment by pulkomandy** [comment]
Not if you set your locale to one using ISO-8859-15, for example. Subtle bug, it will work for everything except ÿ. Encodings are fun!

towlower implementation in musl:
https://github.com/runtimejs/musl-libc/blob/master/src/ctype/towctrans.c

**Comment by jessicah** [comment]
I agree, keeping ICU makes sense. And yes, Haiku has had bugs in the past
that I've fixed for multi byte handling.

**Comment by korli** [comment]
Follow-up : https://dev.haiku-os.org/ticket/14730
