### ISSUE TITLE
Retroarch - binary doesn't have the 'application' signature (FileTypes properties)

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#3419]
The 'Retroarch' binary doesn't have the 'application' signature in the FileTypes properties.

This can cause some issues when searching by filetype.  For example, the "QuickLaunch" app doesn't recognize it as an application.

Tested in x86_gcc2 environment.

**Comment by kwyxz** [comment]
Hi, I'm the maintainer for Retroarch on Haiku. I'm not familiar with this 'application' signature nor with the FileTypes properties, but I'll look this up asap.

**Comment by humdingerb** [comment]
Basically, you provide an .rdef file that has the (vector) icon, app signature, supported filetypes (if applicable), version info etc. in it. This resource can then be added to the built application.
As an example, look at the otter_browser recipe. While not strictly necessary, it uses variables that are set in the recipe, which makes future updates simpler.
