### ISSUE TITLE
Update Python to 3.7

### ISSUE THREAD

**Issue by victordomingos** [haikuports/haikuports#3421]
Python 3.7 was releases almost half an year ago (we are already at Python 3.7.1 right now). Among other useful features, it has gone through a considerable optimisation work, which allows to get much better performance on most platforms.

Somebody should update the Python recipe(s) to the latest version and, if possible, make sure they're available on both 32 and 64 bits.

**Comment by korli** [comment]
You should probably volunteer :)

**Comment by victordomingos** [comment]
I would do it if I was knowledgeable about it, of course. Sorry.
