### ISSUE TITLE
StreamRadio not launching or building

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#3438]
After updating to hrev52620+2, "StreamRadio" (installed from HaikuDepot) will not launch anymore. "Could not open "StreamRadio" (Missing symbol: _ZTI10BAdapterIO)."

Attempting to build the StreamRadio package from source also fails with multiple errors now.

**Comment by Vidrep** [comment]
```In file included from StreamPlayer.h:15:0,
                 from StationListView.h:17,
                 from MainWindow.h:31,
                 from MainWindow.cpp:21:
StreamIO.h:28:10: n file included from StreamPlayer.h:15:0,
                 from StationListView.h:17,
                 from MainWindow.h:31,
                 from RadioApp.h:13,
                 from About.c[01;31mfatal error: MediaIO.h: No such file or directory
 #include <MediaIO.h>
          ^~~~~~~~~~~
pp:33:
StreamIO.h:28:10: fatal error: MediaIO.h: No such file or directory
 #include <MediaIO.h>
          ^~~~~~~~~~~
compilation terminated.
```

**Comment by diversys** [comment]
https://github.com/haiku/haiku/commit/df2639bf609ad25078e83bea707328eca8b61b25 moved ```MediaIO.h``` into another folder.

**Comment by Vidrep** [comment]
After setting the new path in the makefile, I now get this error:

``` 
In file included from StreamPlayer.h:15:0,
                 from StationListView.h:17,
                 from StationFinder.h:24,
                 from RadioApp.cpp:2:
StreamIO.h:82:35: error: expected class-name before ',' token
 class StreamIO : public BAdapterIO, protected BUrlProtocolListener {
                                   ^
StreamIO.h:127:2: error: 'BInputAdapter' does not name a type
  BInputAdapter*      fInputAdapter;
```

**Comment by scottmc** [comment]
New pull requests to fix this, this should be sent here:
https://github.com/HaikuArchives/Haiku-Radio

**Comment by Barrett17** [comment]
I guess before or after support for this should be added. However AFAIK the subsequent beta releases are going to be forked directly from master, so I'm not sure how the maintainers will behave.

**Comment by Vidrep** [comment]
Issue has been moved here: https://github.com/HaikuArchives/Haiku-Radio

On the haikuports side only the makefile has to be updated to point to new location of MediaIO.h
