### ISSUE TITLE
Recipe format version too old? Upgrade ports tree? On fresh clone.

### ISSUE THREAD

**Issue by lazybullfrog** [haikuports/haikuports#3462]
I just git cloned haikuports and haikuporter. I get this when trying to run haikuporter on the ports tree:

Error: The version of the recipe file format used in the ports tree is older than the one supported by haikuporter.
Error: Please upgrade the ports tree.

**Comment by humdingerb** [comment]
Make sure the TREE_PATH in your haikuports.conf points to the cloned haikuports tree.

**Comment by lazybullfrog** [comment]
Thanks. I had mistyped my path.

**Comment by diversys** [comment]
A more helpfull error message would be nice. how about moving it to haikuporter tracker?

**Comment by lazybullfrog** [comment]
Would this be better?

Error: The version of the recipe file format used in the ports tree is older than the one supported by haikuporter. Double check your TREE_PATH in haikuports.conf.

I'll open a ticket this evening.

**Comment by lazybullfrog** [comment]
Added ticket to haikuporter.
