### ISSUE TITLE
Update flameshot to v6.0

### ISSUE THREAD

**Issue by luzpaz** [haikuports/haikuports#3468]
https://github.com/lupoDharkael/flameshot/releases/tag/v0.6.0

https://github.com/haikuports/haikuports/tree/master/media-gfx/flameshot

CC @diversys

**Comment by alwayslivid** [comment]
This was fixed [here](https://github.com/haikuports/haikuports/pull/4111).

**Comment by Begasus** [comment]
Already updated to v12.* https://github.com/haikuports/haikuports/commit/dda732e5c3c4b0693a561e3eb8955e8af2baece3
