### ISSUE TITLE
LibreOffice: no backspace in Calc cell editing

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#3489]
When editing the contents of a cell, backspace doesn't work. I can move the cursor with the cursor keys and use DEL instead, but it is quite awkward... :)

**Comment by diversys** [comment]
This is probably the same as https://bugs.documentfoundation.org/show_bug.cgi?id=122238
See the full list of KDE5 vcl bugs 
https://bugs.documentfoundation.org/showdependencytree.cgi?id=102495&hide_resolved=0

**Comment by humdingerb** [comment]
Yes, looks like that is it.
There's a workaround posted in that ticket that does work: use SHIFT+BACKSPACE.

**Comment by diversys** [comment]
Aleksei Nikiforov committed a patch related to this issue.
It has been pushed to "master":

https://git.libreoffice.org/core/+/5843e14a4ddc6d2b1e375ca26eec33033bfad455%5E%21

tdf#122238 KDE5: disable mechanism of Qt for shortcut activation

It will be available in 6.3.0.
