### ISSUE TITLE
Update nasm to v2.14

### ISSUE THREAD

**Issue by Lan72** [haikuports/haikuports#3508]
Please update [nasm](https://github.com/haikuports/haikuports/tree/master/dev-lang/nasm) to [version 2.14](https://www.nasm.us/pub/nasm/releasebuilds/2.14/).

Because we have outdated version, it is impossible to build some libraries, for example, [the latest](https://download.videolan.org/pub/videolan/x264/snapshots/) [x264](https://github.com/haikuports/haikuports/tree/master/media-libs/x264) builds.

**Comment by kenmays** [comment]
When building newer releases of NASM >=2.14 on Haiku, a few erratic GCC/POSIX system headers messages appear in error. Tested with GCC2 and GCC7. No similar build issues with earlier stable versions of NASM on Haiku (i.e. NASM <=2.12.02). Will review further as time permits.

**Comment by kenmays** [comment]
Resolved. NASM 2.14.02-1 ported.
See: https://depot.haiku-os.org/#!/pkg/nasm/haikuports/2/14/02/-/1/x86_64?bcguid=bc143-LVJR
