### ISSUE TITLE
Write a recipe for Gitahead

### ISSUE THREAD

**Issue by return** [haikuports/haikuports#3510]
A very nice GUI Git client which has recently been open-sourced by SciTools [1]. Should be possible to easily port this to Haiku. https://github.com/gitahead/gitahead

[1] https://scitools.com/gitahead/

![dark](https://user-images.githubusercontent.com/7050293/50493642-ca3c0480-0a16-11e9-9522-d789ca244c77.png)

**Comment by Begasus** [comment]
Gave it a quick look, so far deppendencies not met: gir (gobject_introspection) and libsecret (those are not so easy to port over) :)

**Comment by return** [comment]
@Begasus Yeah I didn't notice the libsecret requirement. Even that needs platform-specific key store implementations. I think we should just use the BKeyStore API for storing Git credentials [0] instead rather than porting libsecret.

[0]https://github.com/gitahead/gitahead/blob/53d6ddc65cf5acee7d254ea991363dc4d1851f68/src/cred/CredentialHelper.cpp#L27

**Comment by Begasus** [comment]
@return that's out of my league :)

**Comment by augiedoggie** [comment]
I had this partially ported and working a while ago but I recently looked at their github page and it says the project has been abandoned.  We can probably close this issue.
