### ISSUE TITLE
Write a recipe for libgee

### ISSUE THREAD

**Issue by fsb4000** [haikuports/haikuports#3519]
Libgee - GObject collection library
HOMEPAGE="https://wiki.gnome.org/Projects/Libgee"

Latest version is https://download.gnome.org/sources/libgee/0.20/libgee-0.20.1.tar.xz

I managed to build it (it needs vala and libglib-2.0)
```
CC=gcc-x86 ./configure
make
```
But I failed to create recipe to test it

The lib is needed for many vala apps,..

**Comment by Begasus** [comment]
Running configure I don't see a check for vala?

**Comment by Begasus** [comment]
Test fail on a lot of places ..

**Comment by fsb4000** [comment]
Begasus, thank you for your interest Yes, vala don't need it for the build.  The library already provides file gee-0.8.vapi.

About the tests, sure, you are right, they fail. But I think maybe it's not scary. I mean the Windows version (MSYS2) also didn't pass the tests but vala programs  works fine.

Windows tests results:
```
 ./tests/tests.exe
/ArrayList/[Collection] type correctness: OK
/ArrayList/[Collection] iterator returns all elements once: OK
/ArrayList/[Collection] mutable iterator: OK
/ArrayList/[Collection] contains, size and is_empty: OK
/ArrayList/[Collection] add and remove: OK
/ArrayList/[Collection] clear: OK
/ArrayList/[Collection] add_all: OK
/ArrayList/[Collection] contains_all: OK
/ArrayList/[Collection] remove_all: OK
/ArrayList/[Collection] retain_all: OK
/ArrayList/[Collection] to_array: OK
/ArrayList/[Collection] GObject properties: OK
/ArrayList/[Collection] foreach: OK
/ArrayList/[Collection] fold: OK
/ArrayList/[Collection] map: OK
/ArrayList/[Collection] scan: OK
/ArrayList/[Collection] filter: OK
/ArrayList/[Collection] chop: OK
/ArrayList/[Collection] first_match: OK
/ArrayList/[Collection] any_match: OK
/ArrayList/[Collection] all_match: OK
/ArrayList/[Collection] max_min: OK
/ArrayList/[Collection] order_by: OK
/ArrayList/[List] iterator is ordered: OK
/ArrayList/[List] list iterator: OK
/ArrayList/[List] duplicates are retained: OK
/ArrayList/[List] get: GLib-Message: 23:37:20.059: Not implemented: g_test_trap_fork

(tests.exe:30540): GLib-ERROR **: 23:37:20.060: g_test_trap_ assertion with no trapped test
```

Here some real simple examples with the lib:
https://wiki.gnome.org/Projects/Vala/GeeSamples

**Comment by fsb4000** [comment]
Begasus, thank you, I installed, simple example works.
![sample code](https://i.imgur.com/7I8MlCo.png)

**Comment by Begasus** [comment]
Glad to see it's working ok :+1: (in my configure check for vale I enable it with "configure --enable-vala" otherwise it's not checking (or doesn't show the check) for it :)

**Comment by fsb4000** [comment]
Thank you Begasus.
I'll close the issue.
