### ISSUE TITLE
wrong "lib:libpng" provide in libpng16 package

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#3525]
The package does not include a "libpng", only a "libpng16". Yet lib:libpng is mentionned in the provides. It should be removed. However, we have to be careful because a lot of packages wrongly depend on it now :(

**Comment by Begasus** [comment]
Best to update the "newer" version for recipes using libpng would need to use "lib:libpng16", this would eventually lead up to leaving out the provide for libpng in it's recipe

**Comment by scottmc** [comment]
Might help to lay out a plan of attack for this one, perhaps a list of recipes that need to be updated?

**Comment by Begasus** [comment]
I think a complete list of recipes will be quite large :)

**Comment by korli** [comment]
it could be a good idea to clean up old recipes which are referencing lib:libpng.

**Comment by waddlesplash** [comment]
@Begasus, anything left to do here?

**Comment by waddlesplash** [comment]
Ah, I see most of these are tracked in #3779, and there are some left to go.

**Comment by Begasus** [comment]
Yeah, now I have some "stable" build environments I should check on the remaining ones (or someone else for that matter) :)

**Comment by Begasus** [comment]
Closing in favor of: https://github.com/haikuports/haikuports/issues/3779

**Comment by waddlesplash** [comment]
No, I think this should stay open as once #3779 is completed, we should change libpng itself.

**Comment by Begasus** [comment]
> No, I think this should stay open as once #3779 is completed, we should change libpng itself.

My bad, working on the last 2 ones atm

**Comment by korli** [comment]
What's the status?

**Comment by Begasus** [comment]
Last time I checked it was fine, but that has been a while, someone(?) should have another look at this. :)

**Comment by Begasus** [comment]
Done in: https://github.com/haikuports/haikuports/pull/8937

**Comment by Begasus** [comment]
Maybe it's time to nuke the old ones? libpng12 and libpng15, I don't think they are used anywhere anymore?
Looking into bumping libpng16 to it's latest release (all three are reported as vulnerable atm at repology).

**Comment by pulkomandy** [comment]
libpng12 is the one used to run old BeOS apps, I don't think we shoudl remove it.

**Comment by Begasus** [comment]
Created a PR to update libpng16, checked a build for libpng12 on 32bit (gcc2) and that's still fine, so it could stay then.
How about libpng15, there have been talks about removing it but those were put on hold in regards of the lib:libpng issue not being provided in the base package (which is solved)?
