### ISSUE TITLE
OpenAL switching to cpp, re-port will be required

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#3531]
The last c version was 0.19.1, for which i already made a PR ( https://github.com/haikuports/haikuports/pull/3530 ).
I tried to upstream the Haiku patches but i had to notice they completly reworked the sources and switched to cpp. The files aren't similar, at least for me, so i can't update our patchest for the master branch.
The Haiku support also removed from the master branch.
The rework started in oct 18', so if somebody up to the task it would be nice to reintroduce Haiku support for the upcoming version.

**Comment by korli** [comment]
bumped in de3c36296f83eb9cabcad95789797b5e7ab7316f
