### ISSUE TITLE
jansson doesn't install properly

### ISSUE THREAD

**Issue by x-t** [haikuports/haikuports#3536]
No pkgconfig files or headers are created.
```
~> ls /packages/jansson-2.11-2/.self/develop/lib/pkgconfig/
egl.pc  libcrypto.pc  libpng.pc    openssl.pc     python.pc
gl.pc   libcurl.pc    libpng16.pc  osmesa.pc      python2.pc
glu.pc  libjpeg.pc    libssl.pc    python-2.7.pc  zlib.pc
~> pkg-config --exists jansson
~> echo $?
1
~> 
```

**Comment by x-t** [comment]
At the time when I made the issue, it wasn't.

I tried installing it now and the same problem still persists.

**Comment by korli** [comment]
it definitely works here on x86_64. please try a reboot.

**Comment by x-t** [comment]
Yeah, I rebooted probably a billion times, I tried reinstalling the package as well, it just doesn't fix anything.
Running on r1beta1 btw.

**Comment by korli** [comment]
can we close this?

**Comment by x-t** [comment]
Yeah sure, I don't care enough to re-test it.
