### ISSUE TITLE
[vim] gvim does not display special characters in menus

### ISSUE THREAD

**Issue by KapiX** [haikuports/haikuports#354]
![screenshot4](https://cloud.githubusercontent.com/assets/686372/11907852/9c76c806-a5d7-11e5-95cc-a2edba4e0bba.png)

**Comment by pulkomandy** [comment]
It works fine here bot h in French and Polish.
Are you sure your font is working fine? (I'm using the default DejaVu Sans)

**Comment by KapiX** [comment]
With DejaVu Sans I get question marks and the font I'm using works fine for the rest of the system.
I am using custom built package though (7.4-2 while HaikuDepot has 7.4-1). Also, this is on gcc4h.

**Comment by KapiX** [comment]
I have just installed vim package from HaikuDepot on gcc2h, 7.4-3. Default font, no Polish characters. @pulkomandy which version of the package were you using?

**Comment by pulkomandy** [comment]
I also use 7.4-3 from HaikuDepot on gcc2h. I tried removing my vimrc and vimfiles but that doesn't change anything.
Could it be an encoding problem? My env settings possibly related are:

```
LC_MONETARY=fr.UTF-8
LC_NUMERIC=fr.UTF-8
LC_TYPE=en_US.UTF-8
TTYPE=UTF-8
LC_MESSAGES=fr.UTF-8
LC_COLLATE=fr.UTF-8
LC_CTYPE=fr.UTF-8
LC_TIME=fr.UTF-8
```

**Comment by KapiX** [comment]
@pulkomandy Which code for Polish did you try? `pl_PL.UTF-8` or `pl.UTF-8` (default)? For me `pl_PL` works, and `pl` does not. Can you confirm?

**Comment by pulkomandy** [comment]
Confirmed. Interestingly, "fr" does work and so does "fr_FR".
