### ISSUE TITLE
Please update uriparser to 0.9.1, includes security fixes

### ISSUE THREAD

**Issue by hartwork** [haikuports/haikuports#3545]
Hi!

Just a quick heads up that [uriparser 0.9.1](https://github.com/uriparser/uriparser/releases/tag/uriparser-0.9.1) with security fixes has been released.

Thanks for updating!

**Comment by Begasus** [comment]
diff --git a/configure.ac b/configure.ac
index 3144a69..ce90ee2 100644
--- a/configure.ac
+++ b/configure.ac
@@ -26,6 +26,8 @@ AM_CONDITIONAL([WIN32], test "$WIN32" = "yes")
 AC_CHECK_FUNCS([wprintf])
 AC_CHECK_FUNCS([reallocarray])  # needs AC_USE_SYSTEM_EXTENSIONS (#define _GNU_SOURCE)
 
+## Haiku check for -lsocket -lnetwork inet_ntop
+AC_SEARCH_LIBS([socket],[socket inet network])
 
 ## Option --disable-test
 AC_ARG_ENABLE(test, [

**Comment by Begasus** [comment]
PR created, thanks for the notice @hartwork ! https://github.com/haikuports/haikuports/pull/3547

**Comment by Begasus** [comment]
Merged, closing this one :)

**Comment by Begasus** [comment]
@hartwork thanks, the patch was merely to link libnetwork/libsocket (-lsocket being used during build), without that (or the previous patch) we end up with a undefined reference to inet_ntop

**Comment by Begasus** [comment]
Let me see if I can create a PR for this at github for you :)
