### ISSUE TITLE
[openjdk] Could not allocate metaspace

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#3549]
openjdk8_default-1.8.u192_b26-2-x86_64.hpkg

java -version
Error occurred during initialization of VM
Could not allocate metaspace: 1073741824 bytes

**Comment by diversys** [comment]
CompressedClassSpaceSize option makes it work.

java -XX:CompressedClassSpaceSize=32m -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-b26)
OpenJDK 64-Bit Server VM (build 25.192-b26, mixed mode)

**Comment by korli** [comment]
Well this means the mmap syscall fails with a size of 1GB. This obviously can't work if the OS hasn't the memory available.

**Comment by korli** [comment]
On Linux: 
```
$ ulimit -S -v 819400
$ java -version
Error occurred during initialization of VM
Could not allocate metaspace: 1073741824 bytes

$ulimit -S -v unlimited
$java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**Comment by waddlesplash** [comment]
It seems Java expects that it can overcommit memory, which isn't the case on Haiku.

**Comment by korli** [comment]
Make sure the OS has a minimum of swap space configured (for instance 256MB are enough on a 2GB VM).
