### ISSUE TITLE
Update hdf5 to 1.10.5

### ISSUE THREAD

**Issue by luzpaz** [haikuports/haikuports#3557]
Current stable is at https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.5/src/

Changelog is at: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.5/src/hdf5-1.10.5-RELEASE.txt

https://github.com/haikuports/haikuports/blob/master/sci-libs/hdf5/hdf5-1.10.1.recipe

Edit: updated links to point to 1.10.5

**Comment by luzpaz** [comment]
Previous efforts to bump hdf5 at https://github.com/haikuports/haikuports/pull/2898

**Comment by extrowerk** [comment]
If you have time, feel free to adjust my recipe in the linked PR and test all the depending packages with the updated hdf5 (actually this is the reason why that PR not merged yet).
hdf5 is really simple stuff,  it doesn't even needs a patching, so you can get it built easily.

**Comment by Begasus** [comment]
At the moment latest version is 1.10.5

**Comment by korli** [comment]
See 3e1dd9559a5c7de744941f79c4433938f53b1378
