### ISSUE TITLE
Request: Qt printing support

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3558]
Ref: https://wiki.qt.io/Qt-Printing
Goal: Enable printing features in Qt-based apps like Scribus 

Qt provides extensive cross-platform support for printing. Using the printing systems on each platform, Qt applications can print to attached printers and across networks to remote printers. Qt's printing system also supports PDF file generation, providing the foundation for basic report generation facilities.

**Comment by kenmays** [comment]
Closing this one. Best to just fix backend print infrastructure issues for x86_64 (and x86).

**Comment by danboid** [comment]
I'm also keen to see this get implemented.

The main apps I'd want to print from under Haiku are Libreoffice (mainly Writer) and the Otter browser. Libreoffice isn't much use until users can print directly from it.

**Comment by kenmays** [comment]
1. Tested:
- Otter Browser - works.
- Dooble - works. 

Thanks!

**Comment by danboid** [comment]
@kenmays 

You've fixed Haiku Qt printing? Have you tested Libreoffice yet?
