### ISSUE TITLE
Create an icon for RetroArch

### ISSUE THREAD

**Issue by alaviss** [haikuports/haikuports#3563]
Tag #3539.

RetroArch currently doesn't have an icon on Haiku.

**Comment by gouchi** [comment]
It is not possible to use the [current one](https://github.com/libretro/RetroArch/tree/master/media) ?

**Comment by gouchi** [comment]
This issue should be closed as there is an icon in the Application menu ?

![ra](https://github.com/user-attachments/assets/c4e748b0-c487-45f2-89ff-029c6dfdd04c)

**Comment by Begasus** [comment]
Thanks! Slipped through the net I guess. 👍
