### ISSUE TITLE
Otter Browser WebGL 1.0 context display issue

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3568]
Otter Browser 1.0.01-2 passes HTML5test WebGL 1.0 test but doesn't render WebGL 1.0 context display.
Possible issue is missing plugins/xcbglintegrations/

Test site: 
https://get.webgl.org/
https://get.webgl.org/webgl2/

**Comment by threedeyes** [comment]
QtWebKit is currently compiled with webgl support, but I did not implement support for initializing the OpenGL context in the QPA plugin - https://github.com/threedeyes/qthaikuplugins/tree/master/platforms/qhaikuplatform.

**Comment by kenmays** [comment]
Ok. Not a major issue. Closing ticket.
