### ISSUE TITLE
Port QEMU Haiku display driver to new API

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#3575]
Currently, QEMU uses SDL1.2 which was deprecated in the 2.12.0.
According to @threedeyes SDL2 uses OpenGL under Haiku for video output and has certain bugs like missing redraw if a window is inactive.

A better approach would be to port Haiku display driver to new API https://github.com/mmlr/qemu-haiku/blob/master/ui/haiku.cpp written by @mmlr .

**Comment by CodeforEvolution** [comment]
Actually, looking at the qemu code, there is an option to configure the SDL2 backend with just normal "2d" rendering, though I agree that it still would be nice to have a native backend.

**Comment by X547** [comment]
> According to @threedeyes SDL2 uses OpenGL under Haiku for video output and has certain bugs like missing redraw if a window is inactive.
Tested QEMU with SDL2 with my SDL2 and Mesa and confirmed deadlock in libGL when 3 or more windows (serial output etc.) are opened or window is minimized and restored. Likely problem in SDL2 OpenGL integration or Mesa HGL.

**Comment by davidkaroly** [comment]
qemu-2.1.2 won't build any more on Haiku.
On the other hand it might be not very difficult to port the Haiku UI driver to newer qemu versions. So far I tried it on qemu-2.12.1 and it seems functional and not much change needs to be done to the codebase.

**Comment by davidkaroly** [comment]
QEMU Haiku display and audio driver rebased on qemu-7.2.0 - see #7789

**Comment by davidkaroly** [comment]
Haiku UI has been merged in qemu-7.2.0 in #7789 and available from HaikuDepot so probably this ticket can be closed.

**Comment by diversys** [comment]
Thanks!
