### ISSUE TITLE
gcc-7.3 broken on 32 bits haiku.

### ISSUE THREAD

**Issue by khallebal** [haikuports/haikuports#3576]
I tried to compile a project, and during the dependency checks i got an error that the compiler is broken(unable to build the C test file ), looking in the log reveals that ld couldn't find "crti.o", "start_dyn.o" and "init_term_dyn.o". so i typed:

`setarch x86`

`gcc -Xlinker -v`

I got the confirmation:

```
GNU ld (GNU Binutils) 2.26.1
/boot/system/develop/tools/x86/bin/../lib/gcc/i586-pc-haiku/7.3.0/../../../../i586-pc-haiku/bin/ld: cannot find crti.o: No such file or directory
/boot/system/develop/tools/x86/bin/../lib/gcc/i586-pc-haiku/7.3.0/../../../../i586-pc-haiku/bin/ld: cannot find start_dyn.o: No such file or directory
/boot/system/develop/tools/x86/bin/../lib/gcc/i586-pc-haiku/7.3.0/../../../../i586-pc-haiku/bin/ld: cannot find init_term_dyn.o: No such file or directory
collect2: error: ld returned 1 exit status
```

**Comment by khallebal** [comment]
I wonder how i ended up missing the haiku_devel_x86 package in my system!... weired.
Sorry for the disturbance.

**Comment by Cyan4973** [comment]
I have the same problem recently. I can't complete compilation of `lz4` on Haiku 32-bit.
This happens with both default `gcc` (v2.95) and `gcc-x86` (v7.30).
Errors messages are similar to OP. `gcc` misses `crti.o` only, while `gcc-x86` misses all 3.

To be noted, `haiku_devel` and `haiku_x86_devel` packages are both installed on my system.
(I could not find `haiku_devel_x86`, so I assume it's just a typo).

**Comment by pulkomandy** [comment]
You need the gcc_syslibs and gcc_x86_syslibs as well. Are these not dependencies of anything?

**Comment by Cyan4973** [comment]
Strange. I was trying to reproduce yesterday's problem, but today, compilation works flawlessly, for both `gcc` (v2.95) and `gcc-x86`(v7.30).

I suspect a reboot was necessary for the system to correctly "register" that the dependencies were actually present. Not sure why. Maybe some caching side effect ?

**Comment by Begasus** [comment]
Getting a different output in the Terminal with "gcc -Xlinker -v" (on _x86), but the same message as explained in the reported issue by @khallebal:
```
GNU ld (GNU Binutils) 2.26.1
/boot/system/develop/lib/x86/start_dyn.o: In function `_start':
start_dyn.c:(.text+0x3a): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

**Comment by Begasus** [comment]
This is with trying to build Conky https://github.com/haikuports/haikuports/pull/4433 for secondaryArchSuffix

**Comment by Begasus** [comment]
0_° Strike that :) missed a $secondaryArchSuffix ;)
