### ISSUE TITLE
Update some fonts to newer versions

### ISSUE THREAD

**Issue by twse** [haikuports/haikuports#3584]
Please update the following fonts to newer versions:
- Fira 4.202
- Fira Code 1.206
- Lato 3.001 dev
- Roboto 2.138
- Source Sans Pro 2.040 upright and 1.090 italic
- Source Serif Pro 2.010 upright and 1.010 italic

**Comment by hanya** [comment]
Lato 3.001 dev has not released as font file.
Current Roboto 2.136 uses roboto-hinted.zip which contains hinting. But Roboto 2.138 does not have hinted one.

**Comment by waddlesplash** [comment]
Is the main Roboto now hinted, they just removed the unhinted version?

**Comment by twse** [comment]
Roboto 2.138 does have unhinted version.

**Comment by waddlesplash** [comment]
I see. Yeah, there's not much we can do then; we certainly need the hinted versions.

**Comment by twse** [comment]
Overpass should be bumped to 3.0.3 – the font also have LGPL 2.1 license as well.

**Comment by twse** [comment]
The Nanum font should be updated to v2.5.

**Comment by twse** [comment]
IBM Plex is now in version 1.3.0 – this release adds the Arabic font so please do that.

**Comment by twse** [comment]
The Liberation fonts just got an update: it is now version 2.00.5 and is released under the SIL Open Font License v1.1. Please do that.
