### ISSUE TITLE
binutils: disable-initfini-array flag code review

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3593]
I was told by waddlesplash about a previous --disable-initfini-array flag dependency. This flag feature **was not used** in the binutils recipes for Haiku prior to the binutils 2.27 port.

**NOTE:** https://gcc.gnu.org/ml/gcc-help/2014-04/msg00155.html

"> The C++ language does not define the order in which global variables
> in different files are initialized.  Any such dependency in your
> program is a potential bug.
>
> That said, yes, GCC 4.7 did change the order.  See
> http://gcc.gnu.org/PR46770 .  You may be able to change back by
> configuring with --disable-initfini-array.  **_That said, this solution
> is likely to be only temporary.  The only permanent fix will be to
> remove the unsupported dependency in your C++ program._**

Another option is the init_priority attribute documented at
http://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Attributes.html"

NOTE: Please review all supported C++ applications and drivers possibly affected.

**Comment by waddlesplash** [comment]
Those things are irrelevant, the problem was runtime_loader not obeying initialization order internally. I've since merged the patch I linked to on that change which fixes the bug, so this is no longer a problem.
