### ISSUE TITLE
x86_gcc2 build failures

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#3594]
I started an "everything" build on x86_gcc2 and there are quite a lot of build failures: https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=2597&viewMode=expanded

So far (list incomplete):
 - [x] advancemame_x86
 - [x] aobook_x86
 - [x] aplayer
 - [x] atftp
 - [x] autoconf264
 - [x] backup
 - [x] berdp
 - [x] besol_x86
 - [x] bladeenc
 - [x] bmake
 - [ ] bs2b (unsafe source)
 - [ ] bs2b_x86 (unsafe source)
 - [x] bsnow
 - [x] flatzebra_x86
 - [x] cal3d
 - [x] cantata_x86
 - [x] im_x86
 - [x] cdplayer
 - [x] cdplayer_x86
 - [x] cloog_x86 PR created, probably obsolete, so removing cloog if no one steps up
 - [x] corsix_th_x86
 - [ ] coveredcalc (unsafe source)
 - [x] cppunit
 - [x] cronie
 - [x] csound_x86
 - [x] cyberdogs_sdl
 - [x] cython_python3_x86
 - [x] distcc
 - [x] dragonmemory
 - [x] drive_encryption (patch send upstream)
 - [x] e2fsprogs_x86
 - [x] eduke32_x86
 - [x] visualboyadvance (unsafe source)

**Comment by hanya** [comment]
bladeenc: tar archive contains file named 'bladeenc-0.94.2/other_makefiles/BladeEnc.\xb6'
It gives 'utf8' codec can't decode byte 0xb6 in position 41: invalid start byte, error while unpacking.
Not possible to build with current haikuporter.

**Comment by Begasus** [comment]
bladeenc was removed/rejected a few days back of being obsolete ... old sources (but put them on my github account without the offending file (in a commit), also with the latest patches available with credits to the people behind it, it's there for historical reason, no need to hunt if further as it is now gone from haikuports

**Comment by Begasus** [comment]
cantata_x86 probably fixed with the latest release (checked the build and it went further then the log viewer indicates, system froze during build (current laptop isn't up for the build)

**Comment by kenmays** [comment]
Receipts that **didn't build successfully on x86_64 R1B1** buildbot platform yet:
- bmake-20180919
- cloog-0.19.0
- coveredcalc-1.10.0
- drive_encryption-1.0
Fix: **Disable** these receipts on both buildbot platforms until resolved by maintainer(s).

**Comment by Begasus** [comment]
Previous version for bmake worked, so used that one to overcome the "invalid user root" problem ...

**Comment by Begasus** [comment]
@kenmays could you provide a link to the failed results for the buildbot?

**Comment by kenmays** [comment]
@Begasus - add links in above message.

**Comment by Begasus** [comment]
For bs2b I've been looking into it, but not sure how to fix it (or what's really needed), I've found some plugin download and a library download (sources) at https://sourceforge.net/projects/bs2b/files/
Maybe someone could take over from there?

**Comment by Begasus** [comment]
For ClooG, looking at the log it's using /boot/home/haikuports/packages/isl13_x86-0.14-4-x86_gcc2.hpkg which is old and should be deleted (the recipe), builds ok with the most recent we have now for libisl (0.20)
ClooG still builds ok with the last one (both could use an update though)

**Comment by kenmays** [comment]
@Begasus, @waddlesplash  - **haikuwebkit-1.6.9** looks good to build on x86 build system. I did a local download and basic build test with the receipt/patch and it seems ok now.

**Comment by kenmays** [comment]
@Begasus - Confirmed **cloog-0.19.0** built successful with **isl-0.20.0** on x86.

**Comment by Begasus** [comment]
If someone could update ClooG and isl we should be on par :)

**Comment by kenmays** [comment]
@waddlesplash - please rerun an "everything" build to isolate any remaining issues.

**Comment by kenmays** [comment]
bmake-20181221-1-x86_gcc2 seems good.

**Comment by kenmays** [comment]
Fixed libpcap 1.8.1 for x86_gcc2. Built and packaged successfully on hrev53144.
