### ISSUE TITLE
Update opentoonz to 1.6.0

### ISSUE THREAD

**Issue by luzpaz** [haikuports/haikuports#3615]
https://github.com/opentoonz/opentoonz/releases/tag/v1.6.0  

https://github.com/haikuports/haikuports/tree/master/media-gfx/opentoonz

CC @korli

**Comment by extrowerk** [comment]
AFAIK it needs GL support in Qt, what the Haiku Qt port missing, so OpenToonz is unable to draw on the screen right now.

**Comment by threedeyes** [comment]
OpenGL support in QPA is not finished (disabled for now - https://github.com/threedeyes/qthaikuplugins/blob/master/platforms/qhaikuplatform/haiku/qhaikuintegration.cpp#L168). But partly already worked (code is outdated and need reworked).
For example: http://haikuware.ru/files/video/Qt5_GL_Cube.avi

**Comment by mmuman** [comment]
Nice to see work to bring OpenToonz to Haiku, I spent a lot of time on the Linux port when it was opened in the hope it'd help for Haiku as well ;-)

**Comment by korli** [comment]
upstream PR abandoned: https://github.com/opentoonz/opentoonz/pull/1144

**Comment by korli** [comment]
updated patch 93aeecb15fa301d00f8d4241cf329338613adee3

**Comment by luzpaz** [comment]
Updated ticket title
