### ISSUE TITLE
Update Links to 2.18

### ISSUE THREAD

**Issue by twse** [haikuports/haikuports#3629]
The Links web browser is in version 2.15 so please update it to latest version (2.18).

**Comment by Begasus** [comment]
Without great changes it would be easy to update the recipe (didn't check), patches welcome :)

**Comment by twse** [comment]
The old recipes for version 2.3 pre2 and 2.8 should be removed.

**Comment by Begasus** [comment]
links 2.8 still works for x86_gcc2, so I guess that should stay

**Comment by Begasus** [comment]
Guess this can be closed, we're at 2.19 atm :) https://github.com/haikuports/haikuports/pull/3743
