### ISSUE TITLE
Replace QupZilla with Falkon

### ISSUE THREAD

**Issue by twse** [haikuports/haikuports#3638]
QupZilla was renamed to [Falkon](https://falkon.org/) and moved to KDE Infrastructure.

**Comment by threedeyes** [comment]
QubZilla based on QtWebKit. Falkon based on QtWebEngine (chromium). We don't have ported QtWebEngine for now.

**Comment by Konrad77** [comment]
Any attempts to port it? Some sites are warning me that QtWebkit is outdated. (Github, slack etc)

**Comment by kenmays** [comment]
We have it compiling, but not fully functional yet.
https://github.com/haikuports/haikuports/issues/2512

**Comment by probonopd** [comment]
What issues are remaining? QupZilla is no more. Kong live Falkon.

**Comment by diversys** [comment]
QtWebEngine is now while compiling doesn't work as of yet.

**Comment by kenmays** [comment]
Resolved. Falkon 3.1.0-1 x64 package now provided. Ticket can be closed.

**Comment by probonopd** [comment]
Cool!

**Comment by waddlesplash** [comment]
It's not yet available due to the builders.

**Comment by waddlesplash** [comment]
complete.
