### ISSUE TITLE
openssh-7.6p1 build failure

### ISSUE THREAD

**Issue by zdykstra** [haikuports/haikuports#3649]
Hello! I'm attempting to build OpenSSH 7.6p1 via haikuporter on the following system:

`Haiku x200s 1 hrev52891 Feb 18 2019 15:18:07 x86_64 x86_64 Haiku`

The full build log, as requested, is available below. 

https://gist.github.com/zdykstra/684f4b1f79f611eac9d868a016eaef9b

Let me know if there are any additiona details I can provide for this issue.

**Comment by korli** [comment]
The required Haiku fix was refused (see https://review.haiku-os.org/c/haiku/+/1334).
A patch was nonetheless added in 86e5fd02789708c698ee2ffa8aafc066864cafb6, but this can't be upstreamed obviously.
