### ISSUE TITLE
Clang is unable to find gcc headers

### ISSUE THREAD

**Issue by khallebal** [haikuports/haikuports#3654]
After several hours of struggling trying to build qmplay2 with clang, it just couldn't  find the gcc headers (type_traits, c++config.h....),then i found in the net that, in order for clang to find them, it needs to be built with "--with-gcc-toolchain" flag.
See [relevant thread](https://stackoverflow.com/questions/10308167/when-enabling-c11-with-stdlibc-4-7-clang-error-out-while-gcc-compiles-fine), finaly this #2880 might be related.

**Comment by korli** [comment]
Did you try to install gcc_syslibs_devel (which provides the c++ headers) ?

**Comment by khallebal** [comment]
Yes i have them installed, that's the first thing that came to my mind but after i installed them that didn't help either. furthermore when i try to compile my own app it is unable to find the <new> header which is included by <Message.h>

**Comment by korli** [comment]
fixed for llvm9 in 137aa5aadedbe7430941a1e70d8f9cf59d29d531

**Comment by korli** [comment]
qmplay2 builds with clang9.
