### ISSUE TITLE
Qt browsers complain about missing libs in syslog

### ISSUE THREAD

**Issue by Briseur** [haikuports/haikuports#3663]
No crash but each time I launch QupZilla, I have few lines in syslog about  missing libresolv Otter Browser does the same thing.
KERN: runtime_loader: Cannot open file libresolv.so: No such file or directory
KERN: runtime_loader: Cannot open file libresolv: No such file or directory
KERN: runtime_loader: Cannot open file resolv.so: No such file or directory
KERN: runtime_loader: Cannot open file resolv: No such file or directory
Also some pages are triggering a search for libthai in QupZilla. I didn't check Otter Browser.
KERN: runtime_loader: Cannot open file libthai.so.0: No such file or directory
KERN: runtime_loader: Cannot open file libthai: No such file or directory

**Comment by threedeyes** [comment]
I have already solved this problem earlier in 294271542257e195573ceb57ef2aee510c9d89e2. But there were other problems and this fix has been reverted in 4a5a235ae8d49c88321c3b61f6bcee06539d255c

**Comment by threedeyes** [comment]
Fixed in 0ce8f68598681a11dd587508b9a38d686badcd67

**Comment by jmairboeck** [comment]
libthai is now available (in 30c59f4).
