### ISSUE TITLE
qt5-5.12.1 recipe requires lib:libpng16 but devel:libpng

### ISSUE THREAD

**Issue by mmuman** [haikuports/haikuports#3670]
the qt5-5.12.1 recipe requires the libpng16 lib: but libpng for devel: 
Not sure it's really a problem yet but we probably want this to be fixed.
Maybe related to #3525 ?

**Comment by threedeyes** [comment]
Fixed in 4c7bd64884bf0ccfcbb01093ae0de23180d07de6
