### ISSUE TITLE
create recipe for FLIF image encoder

### ISSUE THREAD

**Issue by ttcoder** [haikuports/haikuports#3680]
See https://flif.info/

Until now I've been using WebP for storing my app's background picture, as I thought it was the "last word" on image compression... Turns out FLIF kicks @ss and takes names, so I'm going to switch over to that instead.

**Comment by Begasus** [comment]
Was checking the latest release in Terminal, build fails with:
```
io.hpp: In function 'bool ioget_int_8bit(IO&, int*)':
io.hpp:32:16: error: expected unqualified-id before '(' token
     int c = io.getc();
                ^
io.hpp:32:16: error: too few arguments to function 'int getc_unlocked(FILE*)'
     int c = io.getc();
                ^
```

**Comment by ttcoder** [comment]
Might be a bug in official (numbered?) release vs. trunk, since I've just tried successfully with master:

# uname -a
Haiku shredder 1 hrev52295+96 Sep 27 2018 18:48: x86_64 x86_64 Haiku

# git clone https://github.com/FLIF-hub/FLIF.git

# make libflif_dec.so
# make libflif.so
# make  # was exceedingly careful, should have done just this (make) from the get go

# ./flif
Usage:
   flif [-e] [encode options] <input image(s)> <output.flif>
   flif [-d] [decode options] <input.flif> <output.pnm | output.pam | output.png>
(...)

# ./flif  /boot/system/cache/tmp/hub/FLIF/tools/2_webp_ll.png /boot/system/cache/tmp/hub/FLIF/tools/2_webp_ll.flif

# ./flif  /boot/system/cache/tmp/hub/FLIF/too
ls/2_webp_ll.flif /boot/system/cache/tmp/hub/FLIF/tools/2_webp_ll__REDO.png

**Comment by Begasus** [comment]
Ok, need to check that then with a recent git checkout, will get back to it later :)

**Comment by Begasus** [comment]
That worked :)

**Comment by Begasus** [comment]
I think this should do it :) https://github.com/haikuports/haikuports/pull/3684 (ps, not checked on x86_64 yet) :)

**Comment by ttcoder** [comment]
Well that was quick, thanks Begasus

**Comment by Begasus** [comment]
That was an easy one :) Closing the issue
