### ISSUE TITLE
libpcap 1.8.1-4 build fails for x86_gcc2

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3691]
Ref: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2690/builds/31960.log
Related to #3594

gcc -fvisibility=hidden -fpic -D_BSD_SOURCE -I.  -DBUILDING_PCAP -DHAVE_CONFIG_H  -D_U_="__attribute__((unused))" -D_BSD_SOURCE    -c bpf_filter.c
**bpf_filter.c:84:15: error: conflicting types for 'bpf_int32'**
**#define int32 bpf_int32**
              ^
In file included from bpf_filter.c:78:0:
./pcap/bpf.h:88:13: note: previous declaration of 'bpf_int32' was here
**typedef int bpf_int32;**
            ^~~~~~~~~
Makefile:508: recipe for target 'bpf_filter.o' failed
make: *** [bpf_filter.o] Error 1

**Comment by Begasus** [comment]
Same error with gcc7 on gcc2hybrid

**Comment by kenmays** [comment]
Issue with new patch: **libpcap: fix 32bit x86 build**
Conflicts with type defines within x86 system headers: **/os/support/SupportDefs.h**
Build works fine on x86_64 platform.

**Comment by kenmays** [comment]
Fixed the build issue on x86.  Needs a core dev review for further Haiku specific patching.

**Comment by kenmays** [comment]
Fixed.
