### ISSUE TITLE
 gadgeteer 0.8.1 build fails on x86_gcc2

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3693]
Ref:  https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=2704&viewMode=expanded

resolving build dependencies failed: requires "lib:libyaml" of package "gadgeteer-0.8.1" could not be resolved

**Comment by korli** [comment]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=2705&viewMode=expanded
