### ISSUE TITLE
streamradio 0.0.3_14-3 build fails on x86_gcc2

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3696]
Ref: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2717/builds/32010.log

from /sources/Haiku-Radio-26f3bbda29da165c849d246038af98e17270249c/About.cpp:33:
sources/Haiku-Radio-26f3bbda29da165c849d246038af98e17270249c/**StreamIO.h:41: parse error before `::'****

**Comment by Begasus** [comment]
Builds ok here without changes (if the buildbot is still using Beta1 it could be that there is still a problem with the libcodec changes) https://github.com/haikuports/haikuports/commit/c53247d4b986de32d17b6e9ad58c39c301da53bc

**Comment by kenmays** [comment]
Thanks for testing. Buildbot is on R1B1. Will check with @waddlesplash and @threedeyes on R1B1 libcodec issue.
