### ISSUE TITLE
Otter 1.0.01 hangs when trying to render arstechnica.com

### ISSUE THREAD

**Issue by fkap69** [haikuports/haikuports#3705]
Haiku x86-64 hrev53001.
No plugins enabled.
In (much) older nightlies it used to have memory leaks but managed to render the site.
I see one of my 4-cores always at 100% when it hangs.

**Comment by extrowerk** [comment]
Have you tested with other QtWebKit based browsers? QupZilla, etc...

**Comment by fkap69** [comment]
Just installed and tested with Qupzilla: exact same behavior.

**Comment by extrowerk** [comment]
Then it COULD be a problem in QtWebKit. Could you please test it with linux/etc?
Do not forget, most of the Qt based browser doesnt using QtWebKit anymore, but QtWebEngine.
One cannot compare the two.

**Comment by fkap69** [comment]
Just downloaded and tested on Ubuntu Gnome 16.04 as appimage: otter-browser-0.9.99.3-rc12-x86_64.AppImage

It has the same problem.

**Comment by extrowerk** [comment]
Then we can't do much, QtWebKit is deprecated, but afaik there is a community project to backport changes/keep up to date. We should look into it.

**Comment by pulkomandy** [comment]
QtWebKit is still maintained by Qt at https://github.com/qt/qtwebkit
They keep it running even if they don't recommend new apps using it.

**Comment by kenmays** [comment]
@fkap69 - Tested. Issue resolved with qtwebkit -9. 
- I rendered the entire page within 427MB usage using Otter 1.0.01. 
- CPU usage minimal (<30% usage after page load initially completes).
- Mem leak. Not as aggressive but still there..

**Comment by fkap69** [comment]
I should have closed this. It works fine for long time as suggested above.
