### ISSUE TITLE
telegram_desktop_x86 1.6.1 build failed for x86_gcc2

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3708]
Ref: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2751/builds/32079.log

**c++: internal compiler error: Kill Thread (program cc1plus)**
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
**CMakeFiles/Telegram.dir/build.make:1855: recipe for target 'CMakeFiles/Telegram.dir/sources/tdesktop-1.6.1/Telegram/SourceFiles/calls/calls_top_bar.o' failed
make[2]: *** [CMakeFiles/Telegram.dir/sources/tdesktop-1.6.1/Telegram/SourceFiles/calls/calls_top_bar.o] Error 4**

**Comment by threedeyes** [comment]
It's bug in our gcc7 related with compiling lambda functions.
If you try to build telegram with gcc8 then will be OK.
I will try to write a patch that will simplify the code (without using lambda functions).

**Comment by threedeyes** [comment]
Very strange.
I tried to [rebuild Telegram](https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2766/builds/32101.log). And buildmaster successfully compiled that file that didn't compile the last time (calls_top_bar.cpp), but he made a mistake on a completely different file (info_profile_icon.cpp).
On my home computer, the build is successful.
I think we need update gcc7 to actial 7.4 version for solve this problem.

**Comment by kenmays** [comment]
Ref: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2770/builds/32106.log

**build completed successfully for Haiku x86_gcc2 w/gcc_x86-7.3.0_2018_05_01**
**telegram_desktop_x86-1.6.2-1-x86_gcc2.hpkg** package posted in HaikuDepot.
