### ISSUE TITLE
Add a recipe for BGhostView

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#3709]
https://github.com/haikuarchives/bghostview

There is currently no GhostScript viewer for Haiku, this is one. We should add it to the package list.
Needs gcc > 2, XPM translator (for toolbar icons, these could be replaced with vector ones), libprefs and ghostscript_gpl.

**Comment by waddlesplash** [comment]
Would be nice to integrate its functionality into DocumentViewer instead of having yet another app...

**Comment by pulkomandy** [comment]
Yes, that's an option too.

**Comment by arnavbhatt288** [comment]
Maybe I can do it? :P

**Comment by Begasus** [comment]
BGhostview.h:12: Preferences.h: No such file or directory (probably BeOS legacy?)

**Comment by Begasus** [comment]
xpmtranslator isn't picked up (after building and installing it in ~/config/non-packaged/add-ons/translators), and BGhostView crashes on exit (c

**Comment by pulkomandy** [comment]
You have to install the gcc7 version of the translator in add-ons/x86/translators

**Comment by Begasus** [comment]
Ok, icons shown now, but we can't really provide a recipe until the issue with the XPMTranslator is solved? (should have that in haikuports before creating one for this)

**Comment by Begasus** [comment]
Aside from the translator ... https://github.com/haikuports/haikuports/pull/3735

**Comment by Begasus** [comment]
Closing this one, for XPMTranslator there should be another issue(?) when this gets resolved about the license
