### ISSUE TITLE
kolourpaint x86_gcc2 post-install script fails

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3719]
Post install  script fails during Kolourpaint package installation.

**Comment by diversys** [comment]
What version of kolourpaint it was and how exactly does it fail?

**Comment by kenmays** [comment]
Current package: kolourpaint_x86-19.03.80-2 x86_gcc2. 
fails to execute **run_kbuildsycoca.sh**

**Comment by diversys** [comment]
Where do you see this message? Can you provide a screenshot?

**Comment by kenmays** [comment]
In terminal:
$> **pkgman install kolourpaint_x86**
post_install script fails: **run_kbuildsycoca.sh**

**Comment by diversys** [comment]
Hopefully fixed in bfd2c6cb15ff65b593516bfa82f3b29f4fc6cafb.

**Comment by kenmays** [comment]
@diversys - Same issue. Reason is that the **run_kbuildsycoca5.sh** script is looking to execute **kbuildsycoca5** (x86-64) versus **kbuildsycoca5-x86** (x86_gcc2) at line 3.
