### ISSUE TITLE
kontacts x86_gcc2 build failed

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3721]
"extra_cmake_modules >= 5.55" build dependency failed
NOTE: Recipe disabled for x86_gcc2 build.

**Comment by Begasus** [comment]
Checking extra_cmake_modules recipe shows it doesn't support x86_gcc2, best would be to try the secondary architecture _x86 then?

**Comment by threedeyes** [comment]
already fixed in 719c493f4cb8332a7a2e895723a83070b6edec68

https://build.haiku-os.org/buildmaster/master/x86_gcc2/buildruns/2763/builds/32093.log

**Comment by kenmays** [comment]
NOTE: Ok. Build successful, but kontacts x86_gcc2 package missing.

**Comment by threedeyes** [comment]
hmm...
https://depot.haiku-os.org/#!/?bcguid=bc1-UKOS&repos=haikuports&arch=x86_gcc2&viewcrttyp=FEATURED&srchexpr=kcontacts
