### ISSUE TITLE
Emacs should be tested/enanled on econdary arch

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#3723]
https://github.com/haikuports/haikuports/blob/master/app-editors/emacs/emacs-26.1.recipe

Refer: https://www.phoronix.com/forums/forum/software/bsd-mac-os-x-hurd-others/1085589-haiku-s-usb-3-0-support-is-finally-in-great-shape?p=1085670#post1085670

**Comment by Begasus** [comment]
Smalll error in the recipe at the add to add the resources to the binary .... should be $commandBinDir instead of $binDir ...
![emacs-x86](https://user-images.githubusercontent.com/16057090/55264510-ef8a1a00-5274-11e9-9146-a034d6d45f56.png)

**Comment by extrowerk** [comment]
Solved.
