### ISSUE TITLE
eduke32 x86 build failed

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3728]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2597/builds/31752.log
version: eduke32_x86-20181118_7241
Related to #3594

Linker issue.

**Comment by Begasus** [comment]
Tried to build it with the same results, libxmp imported the definitions for minixmp (can't remember the right name for it, but it's mentioned in the build process, had no luck changing it to link against libxmp here

**Comment by kenmays** [comment]
Works fine on x86_64 without any receipt changes. Yes, contains libxmp-lite.
The recipe is marked as untested, but we can moved to broken for x86 - until further inspection.
