### ISSUE TITLE
isl13: decommision for x86_gcc2

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3738]
Decommission isl13 packages for x86_gcc2 platform.
- Fix **pkgman install devel:libisl** issue for isl 0.20
- Check for API breakage with dependent packages
- Related to #3594

**Comment by Begasus** [comment]
PR created to bump isl and remove the obsolete package isl13 (comments welcome) https://github.com/haikuports/haikuports/pull/3741

**Comment by kenmays** [comment]
Ref #3741
