### ISSUE TITLE
libwebp: decommission libwebp5 and libwebp6

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3739]
Decommission libwebp5 and libwebp6.
- Related to #3594

**Comment by Begasus** [comment]
Not familiar with the term decommission, what do you mean by it?

**Comment by kenmays** [comment]
@Begasus - Basically, it means withdraw something from use. We do this when we have a package that supercedes or replaces something else. In this case, libwebp replaces libwebp5 and libwebp6 (if no API breakage).

**Comment by pulkomandy** [comment]
The reason there are separate packages in the first place is ABI breakage. And tqere may be packages outside haikuports that depends on these libraries. So they are not going away anytime soon. Maybe in R2.

**Comment by kenmays** [comment]
@pulkomandy - Thanks for confirmation.
