### ISSUE TITLE
euae 0.8.29~WIP4-1 build failed for x86_gcc2

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3740]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2597/builds/31754.log
- waiting for build package euae-0.8.29~WIP4-1 to be activated
- Related to #3594

**Comment by mmlr** [comment]
This is actually a case issue and a bug in HaikuPorter. HaikuPorter waits for the build package to be activated as ```euae-0.8.29~WIP4-1``` with an upper case ```WIP``` as in the recipe name. The packagefs does mount it as ```euae-0.8.29~wip4-1``` however, with a lower case ```wip```. On a cursory look I couldn't find where it would be guaranteed that packagefs makes packages lower case. If such a guarantee exists, HaikuPorter should be updated to lower case its expectation.

**Comment by kenmays** [comment]
@mmlr - Thanks. I manually compiled euae 0.8.29~WIP4 successfully on hrev53043 x86_gcc2 without issues.

**Comment by kenmays** [comment]
See: haikuporter issue per mmlr comment - [102](https://github.com/haikuports/haikuporter/issues/102)

**Comment by mmlr** [comment]
Why did you close this issue? Nothing has been resolved, neither the problem in HaikuPorter was fixed nor was the recipe renamed. IMO the recipe should be renamed to lower case as that is consistent with all the other recipes. As a side effect it would work around the issue.

**Comment by kenmays** [comment]
@mmlr - Was adding the PR this morning.
Ref #3746
