### ISSUE TITLE
E-UAE crash

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#3762]
When trying to run the E-UAE 0.8.29-wip4-1, it crashed under Beta1 x86_gcc2 Haiku. 

Crash report here:
<details>
Debug information for team /boot/system/bin/uae (5075):
CPU(s): 2x Intel Pentium
Memory: 1.93 GiB total, 668.64 MiB used
Haiku revision: hrev52295+129 Mar  4 2019 10:03 (BePC)

Active Threads:
	thread 5076: SDL 
	thread 5080: direct daemon 
	thread 5083: _BMediaRoster_ 
	thread 5085: team 5075 debug task 
	thread 5075: uae (main)
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x19ab0618	0x19ab0618	? 
			Unable to retrieve disassembly for IP 0x19ab0618: address not contained in any valid image.
		0x53525150	0x42c0058b	? 

		Registers:
			  eip:	0x19ab0618
			  esp:	0x729d93dc
			  ebp:	0x19ab0618
			  eax:	0x00000000
			  ebx:	0x01795c08
			  ecx:	0x00000000
			  edx:	0x19ab063c
			  esi:	0x018b42c0
			  edi:	0x00000000
			   cs:	0x001b
			   ds:	0x0023
			   es:	0x0023
			   fs:	0x0063
			   gs:	0x0023
			   ss:	0x0023
			  st0:	nan
			  st1:	0
			  st2:	0
			  st3:	0
			  st4:	0
			  st5:	0
			  st6:	0
			  st7:	1.31e+04
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0, 0, 0, 0}
			  mm2:	{0, 0, 0, 0}
			  mm3:	{0, 0, 0, 0}
			  mm4:	{0, 0, 0, 0}
			  mm5:	{0, 0, 0, 0}
			  mm6:	{0, 0, 0, 0}
			  mm7:	{0, 0x3c00, 0xd4a5, 0xcc5a}
			 xmm0:	{0x4e98, 0x79fe, 0, 0, 0x8086, 0x2919, 0x103c, 0x360b}
			 xmm1:	{0x4e98, 0x79fe, 0, 0, 0x8086, 0x2919, 0x103c, 0x360b}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0x6aea, 0x1bf0, 0x5bec, 0x4a8d, 0x7695, 0x9b74, 0x5609, 0x302d}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	6927	0x0061d000	0x00656000	0x00656000	0x0068d000	lib    	/boot/system/lib/libicutu.so.57.1
	6919	0x0071b000	0x00735000	0x00735000	0x0073c000	lib    	/boot/system/lib/libgame.so
	6923	0x00ada000	0x00d6b000	0x00d6b000	0x00dd4000	lib    	/boot/system/lib/libicui18n.so.57.1
	6920	0x00e02000	0x00ef9000	0x00ef9000	0x00efc000	lib    	/boot/system/lib/libtextencoding.so
	6911	0x00f2d000	0x00f6f000	0x00f6f000	0x00f79000	lib    	/boot/system/lib/libSDL-1.2.so.0.11.4
	6908	0x00fa4000	0x00fc3000	0x00fc3000	0x00fc6000	lib    	/boot/system/runtime_loader
	6925	0x01134000	0x01187000	0x01187000	0x01192000	lib    	/boot/system/lib/libicule.so.57.1
	6909	0x012ee000	0x0166b000	0x0166b000	0x03c31000	app    	/boot/system/bin/uae
	6924	0x03c31000	0x03c3a000	0x03c3a000	0x03c3c000	lib    	/boot/system/lib/libicuio.so.57.1
	6916	0x03c3c000	0x03c48000	0x03c48000	0x03c4b000	lib    	/boot/system/lib/libdevice.so
	6926	0x03c4c000	0x03c57000	0x03c57000	0x03c5a000	lib    	/boot/system/lib/libiculx.so.57.1
	6914	0x03c5c000	0x03cfb000	0x03cfb000	0x03d0a000	lib    	/boot/system/lib/libGL.so
	6921	0x03d16000	0x03d48000	0x03d48000	0x03d55000	lib    	/boot/system/lib/libstdc++.r4.so
	6912	0x03d63000	0x04035000	0x04035000	0x040ce000	lib    	/boot/system/lib/libbe.so
	6929	0x0410b000	0x04122000	0x04122000	0x04127000	lib    	/boot/system/lib/libtranslation.so
	6910	0x04150000	0x0416a000	0x0416a000	0x0416b000	lib    	/boot/system/lib/libz.so.1.2.11
	6917	0x0422f000	0x04307000	0x04307000	0x04352000	lib    	/boot/system/lib/libroot.so
	6915	0x043aa000	0x0442d000	0x0442d000	0x0443b000	lib    	/boot/system/lib/libGLU.so.1.3.1
	6918	0x04501000	0x045b1000	0x045b1000	0x045d6000	lib    	/boot/system/lib/libmedia.so
	6913	0x045f6000	0x047a6000	0x047a6000	0x04805000	lib    	/boot/system/lib/libtracker.so
	6922	0x04954000	0x061d2000	0x061d2000	0x061d3000	lib    	/boot/system/lib/libicudata.so.57.1
	6928	0x062d4000	0x06446000	0x06446000	0x0647a000	lib    	/boot/system/lib/libicuuc.so.57.1
	6907	0x62933000	0x6293b000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	30311	0x00100000	0x00101000	         4	r--S       	full          	cloned direct area
	30295	0x00102000	0x00112000	        64	rw-        	full          	rld heap
	30294	0x00117000	0x00127000	        64	rw-        	full          	rld heap
	30293	0x0012d000	0x00135000	        32	rw-        	full          	rld heap
	30238	0x00250000	0x00251000	         4	rw-S       	full          	_rld_debug_
	30285	0x0061d000	0x00656000	       228	r-x        	full          	libicutu.so.57.1_seg0ro
	30286	0x00656000	0x0065b000	        20	rw-        	full          	libicutu.so.57.1_seg1rw
	30287	0x0065b000	0x0068d000	       200	rw-        	full          	libicutu.so.57.1_seg2rw
	30266	0x0071b000	0x00735000	       104	r-x        	full          	libgame.so_seg0ro
	30267	0x00735000	0x0073c000	        28	rw-        	full          	libgame.so_seg1rw
	30237	0x0075f000	0x0076f000	        64	rw-        	full          	rld heap
	30276	0x00ada000	0x00d6b000	      2628	r-x        	full          	libicui18n.so.57.1_seg0ro
	30277	0x00d6b000	0x00dd3000	       416	rw-        	full          	libicui18n.so.57.1_seg1rw
	30278	0x00dd3000	0x00dd4000	         4	rw-        	full          	libicui18n.so.57.1_seg2rw
	30268	0x00e02000	0x00ef9000	       988	r-x        	full          	libtextencoding.so_seg0ro
	30269	0x00ef9000	0x00efb000	         8	rw-        	full          	libtextencoding.so_seg1rw
	30270	0x00efb000	0x00efc000	         4	rw-        	full          	libtextencoding.so_seg2rw
	30244	0x00f2d000	0x00f6f000	       264	r-x        	full          	libSDL-1.2.so.0.11.4_seg0ro
	30245	0x00f6f000	0x00f77000	        32	rw-        	full          	libSDL-1.2.so.0.11.4_seg1rw
	30246	0x00f77000	0x00f79000	         8	rw-        	full          	libSDL-1.2.so.0.11.4_seg2rw
	30234	0x00fa4000	0x00fc3000	       124	r-x        	full          	runtime_loader_seg0ro
	30235	0x00fc3000	0x00fc5000	         8	rw-        	full          	runtime_loader_seg1rw
	30236	0x00fc5000	0x00fc6000	         4	rw-        	full          	runtime_loader_bss1
	30281	0x01134000	0x01187000	       332	r-x        	full          	libicule.so.57.1_seg0ro
	30282	0x01187000	0x01192000	        44	rw-        	full          	libicule.so.57.1_seg1rw
	30239	0x012ee000	0x0166b000	      3572	r-x        	full          	uae_seg0ro
	30240	0x0166b000	0x017c1000	      1368	rw-        	full          	uae_seg1rw
	30241	0x017c1000	0x03c31000	     37312	rw-        	full          	uae_seg2rw
	30279	0x03c31000	0x03c3a000	        36	r-x        	full          	libicuio.so.57.1_seg0ro
	30280	0x03c3a000	0x03c3c000	         8	rw-        	full          	libicuio.so.57.1_seg1rw
	30258	0x03c3c000	0x03c48000	        48	r-x        	full          	libdevice.so_seg0ro
	30259	0x03c48000	0x03c4b000	        12	rw-        	full          	libdevice.so_seg1rw
	30283	0x03c4c000	0x03c57000	        44	r-x        	full          	libiculx.so.57.1_seg0ro
	30284	0x03c57000	0x03c5a000	        12	rw-        	full          	libiculx.so.57.1_seg1rw
	30253	0x03c5c000	0x03cfb000	       636	r-x        	full          	libGL.so_seg0ro
	30254	0x03cfb000	0x03d09000	        56	rw-        	full          	libGL.so_seg1rw
	30255	0x03d09000	0x03d0a000	         4	rw-        	full          	libGL.so_seg2rw
	30271	0x03d16000	0x03d48000	       200	r-x        	full          	libstdc++.r4.so_seg0ro
	30272	0x03d48000	0x03d53000	        44	rw-        	full          	libstdc++.r4.so_seg1rw
	30273	0x03d53000	0x03d55000	         8	rw-        	full          	libstdc++.r4.so_seg2rw
	30247	0x03d63000	0x04035000	      2888	r-x        	full          	libbe.so_seg0ro
	30248	0x04035000	0x040cd000	       608	rw-        	full          	libbe.so_seg1rw
	30249	0x040cd000	0x040ce000	         4	rw-        	full          	libbe.so_seg2rw
	30291	0x0410b000	0x04122000	        92	r-x        	full          	libtranslation.so_seg0ro
	30292	0x04122000	0x04127000	        20	rw-        	full          	libtranslation.so_seg1rw
	30242	0x04150000	0x0416a000	       104	r-x        	full          	libz.so.1.2.11_seg0ro
	30243	0x0416a000	0x0416b000	         4	rw-        	full          	libz.so.1.2.11_seg1rw
	30260	0x0422f000	0x04307000	       864	r-x        	full          	libroot.so_seg0ro
	30261	0x04307000	0x0431a000	        76	rw-        	full          	libroot.so_seg1rw
	30262	0x0431a000	0x04352000	       224	rw-        	full          	libroot.so_seg2rw
	30256	0x043aa000	0x0442d000	       524	r-x        	full          	libGLU.so.1.3.1_seg0ro
	30257	0x0442d000	0x0443b000	        56	rw-        	full          	libGLU.so.1.3.1_seg1rw
	30263	0x04501000	0x045b1000	       704	r-x        	full          	libmedia.so_seg0ro
	30264	0x045b1000	0x045d5000	       144	rw-        	full          	libmedia.so_seg1rw
	30265	0x045d5000	0x045d6000	         4	rw-        	full          	libmedia.so_seg2rw
	30250	0x045f6000	0x047a6000	      1728	r-x        	full          	libtracker.so_seg0ro
	30251	0x047a6000	0x04804000	       376	rw-        	full          	libtracker.so_seg1rw
	30252	0x04804000	0x04805000	         4	rw-        	full          	libtracker.so_seg2rw
	30274	0x04954000	0x061d2000	     25080	r-x        	full          	libicudata.so.57.1_seg0ro
	30275	0x061d2000	0x061d3000	         4	rw-        	full          	libicudata.so.57.1_seg1rw
	30288	0x062d4000	0x06446000	      1480	r-x        	full          	libicuuc.so.57.1_seg0ro
	30289	0x06446000	0x06479000	       204	rw-        	full          	libicuuc.so.57.1_seg1rw
	30290	0x06479000	0x0647a000	         4	rw-        	full          	libicuuc.so.57.1_seg2rw
	30296	0x19a0c000	0x19ebc000	      4800	rw-        	full          	heap
	30231	0x61b78000	0x61b7c000	        16	rw-        	full          	user area
	30233	0x62933000	0x6293b000	        32	r-xSk      	full          	commpage
	30305	0x6293b000	0x6293c000	         4	rw-S       	full          	server_memory
	30300	0x707d4000	0x70819000	       276	rw-s       	full          	SDL_5076_stack
	30313	0x71832000	0x71877000	       276	rw-s       	full          	direct daemon_5080_stack
	30232	0x719d6000	0x729dc000	     16408	rw-s       	full          	uae_5075_stack
	30307	0x729dc000	0x729fc000	       128	rw-S       	full          	server_memory
	30317	0x7ab5a000	0x7ab9f000	       276	rw-s       	full          	_BMediaRoster__5083_stack

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	34346534	    0	       2963	screen list
	34346654	    0	       2963	BMessageQueue Lock
	34346655	    0	       2963	Untitled
	34346740	    1	       2963	SDL semaphore
	34346746	    0	       2963	some BBlockCache lock
	34346747	    0	       2963	Catalog
	34346748	    0	       2963	some BLocker
	34346749	    0	       2963	some BLocker
	34346750	    0	       2963	token space
	34346751	    0	       2963	BLooperList lock
	34346752	    0	       2963	AppServerLink_sLock
	34346753	    0	       2963	LocaleRosterData
	34346754	    0	       2963	some BLocker
	34346755	    0	       2963	BMessageQueue Lock
	34346758	    0	       2963	media plugin manager
	34346759	    0	       2963	shared buffer list
	34346760	    0	       2963	port pool
	34346761	    0	       2963	add-on manager
	34346762	    0	       2963	media theme lock
	34346763	    0	       2963	BMediaRoster::Roster locker
	34346764	    0	       2963	some BLocker
	34346765	    0	       2963	GameSound device lock
	34346766	    0	       2963	Catalog
	34346767	    0	       2963	PeriodicUpdatePoses
	34346768	    0	       2963	Light Lock
	34346769	    0	       2963	Light Lock
	34346770	    0	       2963	undo
	34346771	    0	       2963	some BLocker
	34346772	    0	       2963	some BLocker
	34346774	    1	      -5075	SDL semaphore
	34346784	    0	       2963	BMessageQueue Lock
	34346785	    0	       2963	AppLooperPort
	34346791	    0	       2963	clipboard
	34346793	    1	       2963	SDL semaphore
	34346795	    0	       2963	width buffer
	34346811	    0	       2963	time source object manager
	34346813	    0	       2963	dormant node manager locker
	34346816	    1	       2963	SDL semaphore
	34346821	    0	       2963	SDL semaphore
	34346823	    1	       2963	SDL semaphore
	34346828	    0	       2963	_BMediaRoster_
	34346848	    0	       2963	SDL semaphore
	34346849	    1	       2963	SDL semaphore

</details>

I'm using a valid. uaerc file stored in /home folder.  

contents of the .uaerc file:
<details>
kickstart_rom_file=/boot/home/Amiga/roms/Kickstart1.3.rom
use_gui=true
floppy0=/boot/home/Amiga/workbench/Workbench13.adf
</details>

Using an old version of e-uae binary (e-uae_0.8.28_beosr5-i586), with the same .uaerc config file, the emulator works well.

**Comment by kenmays** [comment]
Relax the -sdl-gl requirement.

**Comment by extrowerk** [comment]
https://github.com/haikuports/haikuports/pull/3746

**Comment by unspacyar** [comment]
@waddlesplash @kenmays:  I retested again after update to E-UAE 0.8.29-wip4-2, but the same error persists.

**Comment by kenmays** [comment]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2858/builds/32319.log

**Comment by korli** [comment]
> https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2858/builds/32319.log

@kenmays what's your analysis?

**Comment by extrowerk** [comment]
@kenmays: please, tell us what you meant with that link.

**Comment by kenmays** [comment]
@korli @extrowerk - Fixed. Enabling e-uae BeOS GUI within Haiku caused the erroneous crash issue.

**Comment by kenmays** [comment]
The BeOS GUI implementation for e-uae 0.8.29 triggered a crash on Haiku. Disabled for now.

**Comment by kenmays** [comment]
unspacyar - Thanks to @Begasus and @extrowerk, we've resolved this issue and added some improvements as well. Please test it well and inform us of any further bugs. Enjoy...

**Comment by Begasus** [comment]
Thanks for your contribution @kenmays ! I didn't do much ;)

**Comment by Begasus** [comment]
@unspacyar could you confirm or not if the latest PR solves your problem? https://github.com/haikuports/haikuports/pull/3831

**Comment by unspacyar** [comment]
@Begasus I didn't found an updated package in HaikuDepot yet.  Let me try to build it using haikuporter.

**Comment by unspacyar** [comment]
Hello. I tried building up with haikuporter, but not luck. Probably I'm doing something wrongm but It keep stuck at:
waiting for build package euae-0.8.29~WIP4-1 to be activated

Following is the complete output:

<details>
/boot/hp/haikuporter> haikuporter euae
Checking if any package-infos need to be updated ...
Looking for stale dependency-infos ...
Checking if package dependencies need to be updated ...
        updating dependency infos of euae-0.8.29~WIP4
----------------------------------------------------------------------
app-emulation::euae-0.8.29~WIP4
        /boot/hp/haikuports/app-emulation/euae/euae-0.8.29~WIP4.recipe
----------------------------------------------------------------------
Skipping download of source for e-uae-0.8.29-WIP4.tar.bz2
Skipping checksum validation of e-uae-0.8.29-WIP4.tar.bz2
Skipping unpack of e-uae-0.8.29-WIP4.tar.bz2
Cleaning up temporary directories ...
chroot has these packages active:
        /boot/hp/haikuports/packages/diffutils-3.5-2-x86_gcc2.hpkg
        /boot/hp/haikuports/packages/m4-1.4.18-2-x86_gcc2.hpkg
        /boot/hp/haikuports/packages/make-4.1-3-x86_gcc2.hpkg
        /boot/hp/haikuports/packages/ncurses6-6.0-3-x86_gcc2.hpkg
        /boot/hp/haikuports/packages/perl-5.18.2-3-x86_gcc2.hpkg
        /boot/hp/haikuports/packages/sed-4.2.1-6-x86_gcc2.hpkg
        /boot/system/packages/automake-1.16.1-1-x86_gcc2.hpkg
        /boot/system/packages/bash-4.4.023-1-x86_gcc2.hpkg
        /boot/system/packages/binutils-2.17_2016_07_24-4-x86_gcc2.hpkg
        /boot/system/packages/bison-3.0.5-1-x86_gcc2.hpkg
        /boot/system/packages/bzip2-1.0.6-8-x86_gcc2.hpkg
        /boot/system/packages/bzip2_devel-1.0.6-8-x86_gcc2.hpkg
        /boot/system/packages/ca_root_certificates-2018_10_17-1-any.hpkg
        /boot/system/packages/coreutils-8.24-2-x86_gcc2.hpkg
        /boot/system/packages/curl-7.64.1-1-x86_gcc2.hpkg
        /boot/system/packages/expat-2.2.6-1-x86_gcc2.hpkg
        /boot/system/packages/ffmpeg-4.1.1-1-x86_gcc2.hpkg
        /boot/system/packages/findutils-4.6.0-1-x86_gcc2.hpkg
        /boot/system/packages/flac-1.3.2-3-x86_gcc2.hpkg
        /boot/system/packages/flex-2.6.4-1-x86_gcc2.hpkg
        /boot/system/packages/fontconfig-2.12.6-2-x86_gcc2.hpkg
        /boot/system/packages/freetype-2.9.1-1-x86_gcc2.hpkg
        /boot/system/packages/gawk-4.1.4-2-x86_gcc2.hpkg
        /boot/system/packages/gcc-2.95.3_2017_07_20-2-x86_gcc2.hpkg
        /boot/system/packages/gettext_libintl-0.19.8.1-5-x86_gcc2.hpkg
        /boot/system/packages/giflib6-5.0.5-5-x86_gcc2.hpkg
        /boot/system/packages/glu-9.0.0-7-x86_gcc2.hpkg
        /boot/system/packages/grep-2.24-1-x86_gcc2.hpkg
        /boot/system/packages/gutenprint-5.2.14-1-x86_gcc2.hpkg
        /boot/system/packages/gzip-1.10-1-x86_gcc2.hpkg
        /boot/system/packages/haiku-r1~beta1_hrev52295_129-1-x86_gcc2.hpkg
        /boot/system/packages/haiku_devel-r1~beta1_hrev52295_129-1-x86_gcc2.hpkg
        /boot/system/packages/icu-57.1-3-x86_gcc2.hpkg
        /boot/system/packages/icu_devel-57.1-3-x86_gcc2.hpkg
        /boot/system/packages/ilmbase-2.2.1-2-x86_gcc2.hpkg
        /boot/system/packages/jasper-2.0.16-1-x86_gcc2.hpkg
        /boot/system/packages/jpeg-9c-2-x86_gcc2.hpkg
        /boot/system/packages/libicns-0.8.1-8-x86_gcc2.hpkg
        /boot/system/packages/libiconv-1.15-4-x86_gcc2.hpkg
        /boot/system/packages/libmikmod-3.3.11.1-1-x86_gcc2.hpkg
        /boot/system/packages/libmodplug-0.8.9.0-1-x86_gcc2.hpkg
        /boot/system/packages/libogg-1.3.3-2-x86_gcc2.hpkg
        /boot/system/packages/libpng16-1.6.37-1-x86_gcc2.hpkg
        /boot/system/packages/libpng16_devel-1.6.37-1-x86_gcc2.hpkg
        /boot/system/packages/libsdl-1.2.15-15-x86_gcc2.hpkg
        /boot/system/packages/libsdl_devel-1.2.15-15-x86_gcc2.hpkg
        /boot/system/packages/libsolv-0.3.0_haiku_2014_12_22-3-x86_gcc2.hpkg
        /boot/system/packages/libtheora-1.1.1-7-x86_gcc2.hpkg
        /boot/system/packages/libtool-2.4.6-1-x86_gcc2.hpkg
        /boot/system/packages/libtool_libltdl-2.4.6-1-x86_gcc2.hpkg
        /boot/system/packages/libvorbis-1.3.6-1-x86_gcc2.hpkg
        /boot/system/packages/libwebp-1.0.2-1-x86_gcc2.hpkg
        /boot/system/packages/libxml2-2.9.9-3-x86_gcc2.hpkg
        /boot/system/packages/libxml2_devel-2.9.9-3-x86_gcc2.hpkg
        /boot/system/packages/mesa-7.9.2-11-x86_gcc2.hpkg
        /boot/system/packages/mesa_devel-7.9.2-11-x86_gcc2.hpkg
        /boot/system/packages/ncurses6-6.1-1-x86_gcc2.hpkg
        /boot/system/packages/nghttp2-1.34.0-1-x86_gcc2.hpkg
        /boot/system/packages/noto-20170920-3-any.hpkg
        /boot/system/packages/noto_sans_cjk_jp-1.004-2-any.hpkg
        /boot/system/packages/openexr-2.2.1-2-x86_gcc2.hpkg
        /boot/system/packages/openjpeg-2.1.2-3-x86_gcc2.hpkg
        /boot/system/packages/openssl-1.0.2q-1-x86_gcc2.hpkg
        /boot/system/packages/pkgconfig-0.29.2-3-x86_gcc2.hpkg
        /boot/system/packages/readline-7.0.3-3-x86_gcc2.hpkg
        /boot/system/packages/readline6-6.3.8-2-x86_gcc2.hpkg
        /boot/system/packages/sdl_sound-1.0.3-8-x86_gcc2.hpkg
        /boot/system/packages/sdl_sound_devel-1.0.3-8-x86_gcc2.hpkg
        /boot/system/packages/smpeg-0.4.5-7-x86_gcc2.hpkg
        /boot/system/packages/speex-1.2.0-4-x86_gcc2.hpkg
        /boot/system/packages/tar-1.32-1-x86_gcc2.hpkg
        /boot/system/packages/tiff4-4.0.10-1-x86_gcc2.hpkg
        /boot/system/packages/unzip-6.10c23-2-x86_gcc2.hpkg
        /boot/system/packages/zlib-1.2.11-3-x86_gcc2.hpkg
        /boot/system/packages/zlib_devel-1.2.11-3-x86_gcc2.hpkg
----- Package Info ----------------
header size:                     80
heap size:                     1595
TOC size:                        41
package attributes size:       2381
total size:                    1675
-----------------------------------
waiting for build package euae-0.8.29~WIP4-1 to be activated
waiting for build package euae-0.8.29~WIP4-1 to be activated
waiting for build package euae-0.8.29~WIP4-1 to be activated
waiting for build package euae-0.8.29~WIP4-1 to be activated
waiting for build package euae-0.8.29~WIP4-1 to be activated
waiting for build package euae-0.8.29~WIP4-1 to be activated
waiting for build package euae-0.8.29~WIP4-1 to be activated
waiting for build package euae-0.8.29~WIP4-1 to be activated
waiting for build package euae-0.8.29~WIP4-1 to be activated
waiting for build package euae-0.8.29~WIP4-1 to be activated
waiting for build package euae-0.8.29~WIP4-1 to be activated
waiting for build package euae-0.8.29~WIP4-1 to be activated

</details>

**Comment by kenmays** [comment]
E-UAE 0.8.29-WIP4 Rev.3 package review
- **pkgman install euae_x86**
Built 05/14/2019 17:51:40. Tested on hrev52112 x86_gcc2 - no crashes yet.

**Comment by unspacyar** [comment]
Hello @kenmays , @waddlesplash : I installed the new version (euae_x86) and confirm that it works correctly now.

Thank you!
