### ISSUE TITLE
git is removed after doing "pkgman full-sync" (hrev 53071)

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#3764]
Can't install git again, fails with the next message:
```
problem 1: nothing provides vendor_perl>=5.26 needed by git-2.21.0-1
```

**Comment by waddlesplash** [comment]
Uh, can we maybe not break critical applications on the production HaikuPorts? The perl upgrade probably should have been tested a bit more.

**Comment by waddlesplash** [comment]
We also really need to implement haikuports/haikuporter#164...

**Comment by korli** [comment]
You must be kidding right?
