### ISSUE TITLE
Bump revision/versions for recipes using lib:libpng instead of lib:libpng16

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#3779]
Related to https://github.com/haikuports/haikuports/issues/3525

Created a list for the recipes in need of changes (also added links to the recipes and links to PR's already created)

- [x] grafx2 https://github.com/haikuports/haikuports/pull/3778 revision (merged)

- [x] lcdproc https://github.com/haikuports/haikuports/pull/3777 revision (merged)

- [x] apng2gif https://github.com/haikuports/haikuports/pull/3771 revision (merged)

- [x] wizznic https://github.com/haikuports/haikuports/pull/3772 version  (merged)

- [x] w6 https://github.com/haikuports/haikuports/pull/3773 revision (merged)

- [x] bgp https://github.com/haikuports/haikuports/pull/3776 version (merged)

- [x] links https://github.com/haikuports/haikuports/pull/3743 version  (merged)

- [x] visualboyadvance https://github.com/haikuports/haikuports/pull/3782 (removed in favor of new mGBA)

- [x] joyce https://github.com/haikuports/haikuports/pull/3780 version (merged)

- [x] abiword https://github.com/haikuports/haikuports/pull/3889 revision (merged)

- [x] tuxpaint https://github.com/haikuports/haikuports/pull/3036 (merged)

- [x] makeobj https://github.com/haikuports/haikuports/pull/3885 remove obselete file (merged)

- [x] freegish https://github.com/haikuports/haikuports/pull/3865 version (merged)

- [x] fife https://github.com/haikuports/haikuports/pull/3880 revision (merged)

- [x] speed_dreams https://github.com/haikuports/haikuports/pull/3869  revision/version (merged)

- [x] atari++ https://github.com/haikuports/haikuports/pull/3783 revision (merged)

- [x] simutrans Removed obsolete file(s)

- [x] libzmf https://github.com/haikuports/haikuports/pull/3792 revision (merged)

- [x] xmlroff https://github.com/haikuports/haikuports/pull/3795 version (merged)

- [x] libharu https://github.com/haikuports/haikuports/pull/3797 revision (merged)

- [x] love https://github.com/haikuports/haikuports/pull/3798 version (merged)

- [x] xemacs https://github.com/haikuports/haikuports/blob/c2a214e6473117adfdbf84d0f792341b30e1bbd7/app-editors/xemacs/xemacs-21.5_hg.recipe (unsafe source/broken)

- [x] irrlicht https://github.com/haikuports/haikuports/pull/3888 revision (merged)

- [x] libclaw https://github.com/haikuports/haikuports/pull/3813 revision (merged)

- [x] lugaru https://github.com/haikuports/haikuports/pull/3815 revision (merged)

- [x] xmoto https://github.com/haikuports/haikuports/pull/3894 revision PR (build is broken)

- [x] freeciv Version has been bumped

- [x] fontforge https://github.com/haikuports/haikuports/pull/3818 version (merged)

- [x] graphicsmagick https://github.com/haikuports/haikuports/pull/3830 version (merged)

- [x] allegro https://github.com/haikuports/haikuports/pull/3832 version (merged)

- [x] tesseract https://github.com/haikuports/haikuports/pull/3899 revision (merged)

- [x] agg https://github.com/haikuports/haikuports/pull/3860 revision (merged)

- [x] armagetronad https://github.com/haikuports/haikuports/pull/3863 revision (merged)

- [x] supertux https://github.com/haikuports/haikuports/pull/3866 revision (merged)

- [x] euae https://github.com/haikuports/haikuports/pull/3831 revision PR thanks to kenmays

- [x] freedroidrpg https://github.com/haikuports/haikuports/pull/3883 revision PR

- [x] fontconfig https://github.com/haikuports/haikuports/pull/3884 version PR

- [x] gnash https://github.com/haikuports/haikuports/pull/3225 version (closed without merging)

- [x] emacs https://github.com/haikuports/haikuports/pull/3904 obsolete by next version (merged)

- [x] virtualbox_guest_additions https://github.com/haikuports/haikuports/pull/3912 revision PR

- [x] plee_the_bear https://github.com/haikuports/haikuports/pull/6955 (merged)

- [x] openclonk https://github.com/haikuports/haikuports/pull/3881 git version (merged)

- [x] neverball https://github.com/haikuports/haikuports/pull/3919 git version (merged)

- [x] uqm https://github.com/haikuports/haikuports/blob/8cc423a678f9aad4da3d8e429008b2b99230a12e/games-strategy/uqm/uqm-0.7.0.recipe

- [x] colobot https://github.com/haikuports/haikuports/blob/e11566560d8d1e2bac6f20556557bcbfcc44f0fc/games-strategy/colobot/colobot-0.1.12.recipe

- [x] sequitur fixed https://github.com/haikuports/haikuports/commit/ec9946d0cbb991658d11e98d065528e3231def10

- [x] graphviz fixed https://github.com/haikuports/haikuports/blob/c9fc5502dbc7ee8d501ae3f6e9c917213ccc7975/media-gfx/graphviz/graphviz-2.40.1.recipe

- [x] gwenview fixed https://github.com/haikuports/haikuports/blob/c009173b104ae882d626f94ef2ec958982f299ae/kde-base/gwenview/gwenview-19.08.0.recipe

- [x] kwave https://github.com/haikuports/haikuports/pull/4339 (merged)

- [x] kdelibs4 https://github.com/haikuports/haikuports/blob/0d782eba6738395cc7a73e300ef29f1cc27cbb0f/dev-qt/kdelibs4/kdelibs4-4.13.2.recipe (not present anymore?)

- [x] openmw fixed in https://github.com/haikuports/haikuports/pull/6957

- [x] netpbm Fixed in https://github.com/haikuports/haikuports/pull/6944

- [x] leptonica fixed https://github.com/haikuports/haikuports/blob/8591236b047a69011f571f0bc4e8b3c8034efe69/media-libs/leptonica/leptonica-1.74.4.recipe

- [x] texlive https://github.com/haikuports/haikuports/pull/4340 PR

**Comment by Begasus** [comment]
WIP so if anyone could help out it would be nice (for instance, couldn't get joyce to build)

**Comment by alaviss** [comment]
you should write that entire wiki page here :P

Also, this is the syntax for list w checkboxes:

`- [ ] item`

**Comment by Begasus** [comment]
> you should write that entire wiki page here :P
> 
> Also, this is the syntax for list w checkboxes:
> 
> `- [ ] item`, which looks like this:
> 
>     * [ ]  item

Thought about that after I listed them there ;) PS joyce is ok (just need enabling secondary architecture, doesn't work for x86_gcc2)

**Comment by kenmays** [comment]
euae - updated.

**Comment by waddlesplash** [comment]
What's the status here?

**Comment by Begasus** [comment]
Oops, didn't see your reply here @waddlesplash ... need to recheck the remaining ones

**Comment by Begasus** [comment]
Still a few left

**Comment by Begasus** [comment]
OK, this list should be done now, I don't know if any are still in use (so far I haven't found one), feel free to open if there are still left overs.
