### ISSUE TITLE
Perl broken outside of haikuporter (for gcc2hybrid)?

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#3789]
I've come across the next problem when trying to build something from Terminal

![panic-locale](https://user-images.githubusercontent.com/16057090/56577273-e584de00-65ca-11e9-95fa-b68f3d37149c.png)

Checked this with gnucobol, which builds ok with haikuporter, when trying to build it from Terminal I'm getting the same error as the one in the screenshot (for visualboyadvance)

With gcc2hybrid (checked with gcc2/gcc7 (setarch))

**Comment by Begasus** [comment]
Checked on x86_64, it's ok there ...
![locale-panic2](https://user-images.githubusercontent.com/16057090/56579188-cfc5e780-65cf-11e9-9a88-74fd9c781240.png)

**Comment by Begasus** [comment]
After creating a working recipe (with download) for visualboyadvance and running it with haikuporter things are ok:
![panic-locale3](https://user-images.githubusercontent.com/16057090/56580176-45cb4e00-65d2-11e9-8db0-efb180e7fa11.png)

**Comment by korli** [comment]
Please list packages used by haikuporter in the log.

**Comment by Begasus** [comment]
will grab the list in a bit, ps none packages were activated from the haikuports/packages directory :)

**Comment by Begasus** [comment]
Here is the list:
[Terminal_log.txt](https://github.com/haikuports/haikuports/files/3111039/Terminal_log.txt)

**Comment by korli** [comment]
Please list system packages which are not found in this list.

**Comment by Begasus** [comment]
Like in all the installed system packages not used here in the log?

**Comment by Begasus** [comment]
[system_packages.txt](https://github.com/haikuports/haikuports/files/3111580/system_packages.txt)

These are the packages installed atm in /system/packages

**Comment by korli** [comment]
could you try to remove automake113?

**Comment by Begasus** [comment]
Removed/rebooted and still the same, issue remains

**Comment by Begasus** [comment]
Tried with a fresh clone, "pkgman full-sync" (hrev52212 to 53092), reboot and then it is the same thing, after reboot back into hrev52212 it works ok, so it must have happened somewhere in between ;)

**Comment by Begasus** [comment]
Tried several hrev's, all still have 5.26 default installed, after pkgman (full-sync) 5.28 is installed and giving the errors in the screenshots provided, re-installing 5.26 (removes the packages for git - depending on 5.28) helped out to get autotools to work correctly in Terminal again.

**Comment by korli** [comment]
It's not the same on x86_64?

**Comment by Begasus** [comment]
Checked a clone for x86_64 (Beta1), works ok with 5.26 and 5.26 (after updating with pkgman), need to investigate if this happens also on gcc2h Beta1, wip :)

**Comment by korli** [comment]
seems to be locale related, I tried with LC_ALL=POSIX to workaround.

**Comment by korli** [comment]
fixed in 085469acf2c2fe0d62e936553720612923d6c3f8

**Comment by korli** [comment]
Patch under review by upstream: https://rt.perl.org/Public/Bug/Display.html?id=134080

**Comment by korli** [comment]
Will be upstreamed in 5.31.1

**Comment by Begasus** [comment]
@korli Thanks! :)
