### ISSUE TITLE
Miniruby crashing in pthread_attr_get_np

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#3791]
During the compilation, miniruby crashes. For more information: https://bugs.ruby-lang.org/issues/15788

**Comment by korli** [comment]
Looks like a bug in Haiku pthread_getattr_np. 

>  For pthread_attr_get_np() attr should be initialized prior to the call by
     using pthread_attr_init(3).  pthread_getattr_np() does this
     automatically.

**Comment by extrowerk** [comment]
Ticket: https://dev.haiku-os.org/ticket/15025

**Comment by waddlesplash** [comment]
Ticket was fixed.
