### ISSUE TITLE
PyCharm encoding problems

### ISSUE THREAD

**Issue by konrad1977** [haikuports/haikuports#3816]
<img width="1680" alt="Skärmavbild 2019-04-30 kl  06 40 41" src="https://user-images.githubusercontent.com/4384932/56941167-fe354c80-6b12-11e9-8a24-8f475b0fa052.png">

Encoding looks strange in "Event Log"

Version:  2018.3.2 (18 December) 64 bit
JRE: 11.0.3+7 amd 64

**Comment by korli** [comment]
This uses openjdk8.

**Comment by Konrad77** [comment]
The JRE version comes from the about window. The .sh is not changed so its 8, as you say.

**Comment by korli** [comment]
Can't reproduce with version 2021.1.1. Please check and reopen if needed. Thanks.
