### ISSUE TITLE
PyCharm Update failure

### ISSUE THREAD

**Issue by konrad1977** [haikuports/haikuports#3817]
<img width="1680" alt="Skärmavbild 2019-04-30 kl  06 38 29" src="https://user-images.githubusercontent.com/4384932/56941211-5d935c80-6b13-11e9-9a40-c40d6e3767ff.png">

Updates doesnt work. 

Version:  2018.3.2 (18 December) 64 bit
JRE: 11.0.3+7 amd 64

**Comment by KapiX** [comment]
autoupdate should be disabled for packaged software. Is there a way to do this for PyCharm?

**Comment by korli** [comment]
Should be doable with PYCHARM_VM_OPTIONS="-Dide.no.platform.update=true"

**Comment by korli** [comment]
fixed in 49c83a9cbb91f64d1fb7e7bf463d57d4b364ce0a
