### ISSUE TITLE
Migration to Python 3.8

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#3822]
Hi,
I would like some clarification on how migration to python3.7 is supposed to happen.
Currently all python libs explicitly depend on version 3.6, but are suffixed with _python3 and depend on setuptools_python3.

This means we have to be careful updating them. I guess it should be something like:

PYTHON_PACKAGES=(python python3 python37)
PYTHON_VERSIONS=(2.7 3.6 3.7)

Does that sound right? And later we drop support for the "python3" suffix completely as we move on to later versions to avoid confusion?

I already hit a problem with youcompleteme. It runs "python3" as the python interpreter and depends on _python3 packages, so with the current setup, it does not work, and complains that the dependencies are not found (indeed, it is running a python 3.7 interpreter and the dependencies are in the directory for version 3.6).

**Comment by waddlesplash** [comment]
I think Python 3.x breaks internal ABI across minor versions, so we can't link against it and not do rebuilds, yes?

**Comment by pulkomandy** [comment]
Probably, in any case the files get installed to different directories anyway so they can't be used.
This is why "python3" does not seem to make much sense as a package suffix, and we should switch to "python37"?

**Comment by korli** [comment]
waddlesplash merged the 3.7 python with no care. Please don't assign this to me.

**Comment by extrowerk** [comment]
I personally doesn't like the idea to have 3 different python installed parallel, so I would decomission 3.6 alltogether, so 3.7 would become the python3.
Pro: Less changes required in the existing recipes, but they have to be revbumped to get all rebuilt against 3.7
Contra: Possible incompatibility with some existing python-module recipes, in that case if there is already a newer, 3.7 compatible version they should be version bumped.

This is a should teach us a good lesson what we can reuse if 3.8 gets released.

**Comment by extrowerk** [comment]
Beause Calibre i worked much with python modules lately, so i could try to do it as i wrote in my earlier comment. Let me know if you guys are ok with that.

**Comment by pulkomandy** [comment]
Sorry, I tried to find people involved but I may have misread the git log.

**Comment by pulkomandy** [comment]
@extrowerk well, Python 3.6 and 3.7 are incompatible, so this is an ABI break. Just like libpng16 vs libpng15, for example. I agree we should eventually remove Python 3.6, but it seems unreasonable to do this atomically (one super-mega-huge commit changing all recipes involving Python all at once, including cooperation with non-haikuports repos).

So, we need a migration path. What I suggest is a possible one. It allows us to have both versions side by side for a while and figure out the migration. Then we can drop the old 3.6 packages when we're ready and sure nothing uses them anymore.

**Comment by Begasus** [comment]
Changing the line in setuptools to your suggestion would bring it back to work as it was @pulkomandy ?
PYTHON_PACKAGES=(python python3 python37)
If so I could bump setuptools to use that (and set meson to use setuptools_python37 then).
I already checked it with "PYTHON_PACKAGES=(python python3 python7)" which then created the 7 suffix package that worked out ok for meson. For the future there should be some plan outlined on how to do the migration so it doesn't brake other packages.

**Comment by alaviss** [comment]
Every minor version of python there seems to be a rather long mantainance period (python 3.6 will be maintained [until 2021](https://www.python.org/dev/peps/pep-0494/#lifespan)).

So a suggestion of mine is that we stick to a minor version of python for a given release of Haiku (R1, R2, etc.). Other than being a much simpler process, I don't have any strong argument for following this :P

For now, I think @pulkomandy proposal is a good way to migrate into python 3.7. We should also make a blog post to notify our users of the migration to python 3.7 for those who uses `pip` (so they could re-install their deps).

---

Also we should plan for the deprecation of python2 modules in HaikuPorts, given that python 2.7 will reach EoL (Jan 1 2020) soon.

**Comment by korli** [comment]
I'm adding 3.8 and/or 3.9, and removing 3.6 in the next days.

**Comment by waddlesplash** [comment]
So, what is the status here then? We are now on 3.8, so is this now closeable?

**Comment by pulkomandy** [comment]
Beta 3 shipped with python 3.7 preinstalled, should we update to 3.8 (or 3.9?) by default in nightlies and beta4?

**Comment by Begasus** [comment]
If so, haikuporter should be fixed to use the correct version also then (not as in the last change where on Haiku install 2.7 was the default installed and users had to install 3.7 to be able to run haikuporter

**Comment by pulkomandy** [comment]
Python 3.7 will be end of life in june 2023. Should we plan for haiku beta4 to ship with 3.8 or 3.10?

**Comment by waddlesplash** [comment]
I made 3.9 the default recently, so likely beta4 will ship with 3.9 barring any changes.

**Comment by korli** [comment]
migration done
