### ISSUE TITLE
otter and qupzilla crash on playing youtube video

### ISSUE THREAD

**Issue by AlienSoldier2** [haikuports/haikuports#3836]
was working fine not that long ago.
https://gist.github.com/AlienSoldier2/388d7ea350a6ff01858b86fb0f282ac4#file-gistfile1-txt

**Comment by extrowerk** [comment]
Could you test the same browsers with the same backend (qtwebkit) on Linux? That would be great.

**Comment by threedeyes** [comment]
Can you tell me what is your CPUID?
I think it happened after I turned on the assempler optimization in gst_libav package.

**Comment by AlienSoldier2** [comment]
Sorry i have no linux installatio at the moment.
"Can you tell me what is your CPUID?"
Sure, how do i do this within Haiku?  Can't seem to produce it with sysinfo command.

**Comment by threedeyes** [comment]
Just make screenshot of About System window. The name of the CPU is enough.

**Comment by AlienSoldier2** [comment]
Ho, that was in the file i linked: AMD Athlon™ 5350

**Comment by AlienSoldier2** [comment]
dmi decode report: AMD Athlon(tm) 5350 APU with Radeon(tm) R3

**Comment by AlienSoldier2** [comment]
And if you need the kernel date:
hrev53102
x86_gcc2
may 1, 2019 at 7:26:40 AM

**Comment by diversys** [comment]
Should be fixed now. Could you check?

**Comment by AlienSoldier2** [comment]
Yes, all seem fine now.  Thank you for the fast work!
