### ISSUE TITLE
libSDL* recipes needs cleanup for lib:libSDL*_*

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#3878]
There are a lot of recipes using lib:libSDL/lib:libSDL2 in their recipes, libSDL/libSDL2 aren't provided in the base package (they however are provided in the devel package)
These recipes should be changed to use **lib:libSDL_1.2** and **devel:libSDL_1.2** instead (just like the issue for libpng16 (https://github.com/haikuports/haikuports/issues/3779).
This involves all the subpackages like sdl_mixer, sdl_image etc (should be **lib:libSDL_image_1.2** etc ...

**Comment by pulkomandy** [comment]
The subpackages can be different I think (for example sdl_ttf is version 2 even for SDL 1.2).
How to check:

package list libsdl_image-*

If there is a libsdl_image-1.2.so* (version number BEFORE the .so), we need lib:libsdl_image_1.2
But if there is a libsdl_image.so.1.2 or similar, we need lib:libsdl_image

package list libsdl_image_devel-*

If there is a libsdl_image.so in the develop/lib dir, then we need devel:libsdl_image

**Comment by Begasus** [comment]
Didn't check the libSDL_ttf one :) The others I've checked so far provide lib:libSDL_*_1.2, but yes, things need to be checked before changing the actual recipes

**Comment by Begasus** [comment]
Packages ok (with a quick look):
´´´
lib:libSDL_gfx
```
Packages affected:
´´´
lib:libSDL_1.2
lib:libSDL_image_1.2
lib:libSDL_mixer_1.2
lib:libSDL_net_1.2
lib:libSDL_rtf_0.1
lib:libSDL_sound_1.0
lib:libSDL_ttf_2.0
```

**Comment by lonemadmax** [comment]
I may try and update some recipes so that they at least compile and comply with this, but there's surely something I don't understand. As far as I can see, (from libsdl and libsdl2, I've not checked the rest yet) only lib:libSDL2 is not provided. The rest: devel:libSDL2, lib:libSDL and devel:libSDL do exist. Is it that the objective is to remove those from the packages and only provide the numbered version, and so the four references should always be changed to x_n.m?

**Comment by pulkomandy** [comment]
Yes. The sdl recipe currently provides some lib: and devel: entries that do not match the actual library name. These should be removed, but it would break a lot of things that rely on it. So first we have to fix all other packages.

**Comment by Begasus** [comment]
libSDL fixed in: https://github.com/haikuports/haikuports/pull/8960

**Comment by Begasus** [comment]
OK, as far as I know everything (recipes) have been updated and the wrong provides removed, reports at the buildmasters are clean (well a few at "this" moment are still building) from the wrong requirements.
Closing.
