### ISSUE TITLE
PugiXML broken on gcc2h

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#3898]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2979/builds/32651.log

**Comment by extrowerk** [comment]
pugixml 1.9 already have "include(GNUInstallDirs)" in cmakelist.txt, so it should be as easy as bversion bump + $cmakeDirArgs.

**Comment by Begasus** [comment]
Is this fixed? If so it can be closed :)
