### ISSUE TITLE
PovRay build fails on x86

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#3908]
It seems it cant find the boost libs.
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/3000/builds/32677.log

**Comment by extrowerk** [comment]
@Begasus could you check it please on x86? All the dependencies should be available in the Depot.
Thanks!

**Comment by Begasus** [comment]
@extrowerk this is merged already?

**Comment by Begasus** [comment]
The next thing should do it todetect the boost libraries (used in multiple recipe including libreoffice):
```
--with-boost-libdir=`finddir B_SYSTEM_DIRECTORY`/$relativeDevelopLibDir
```

**Comment by Begasus** [comment]
But getting another error (with boost v1.69) from util.hpp:137
```
error: invalid use of incomplete type ... (struct compressed_base : private T)
```

**Comment by Begasus** [comment]
With boost v1.65 it seems to be ok

**Comment by Begasus** [comment]
PR created at https://github.com/haikuports/haikuports/pull/3914
