### ISSUE TITLE
Cannot import PyQt5

### ISSUE THREAD

**Issue by ocerman** [haikuports/haikuports#3916]
Hello,
I have tested this in VirtualBox with nightly 53183.
The PyQt was installed from HaikuDepot.

The problem is that PyQt5.QtCore cannot be imported. After first try I got error: `ImportError: Symbol not found`. When I try to import it again, whole python crashed.

![pyqt](https://user-images.githubusercontent.com/10187350/59158899-98e55b80-8ac1-11e9-9815-98471218053c.png)

**Comment by extrowerk** [comment]
Afaik Python compiled with gcc2 on x86, só it wont work.

**Comment by extrowerk** [comment]
Try to install and use python_x86

**Comment by ocerman** [comment]
@extrowerk You are right - I am new to this dual gcc thing. I could not find `python_x86` package, however I got it working with `python36_x86`. This issue can be closed.
