### ISSUE TITLE
povray: Create an icon

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#3918]
![povray](https://user-images.githubusercontent.com/5168719/59163374-325a4080-8ab5-11e9-9cf3-0ad470848d5f.jpg)

**Comment by extrowerk** [comment]
But isn’t it a CLI program? Why does it needs any icon?

If it is truly required, you can check the Haiku icon guides and redraw it in Icon-o-Matic.

**Comment by kenmays** [comment]
Ah, Haiku Depot icons are for GUI apps - not CLI-only apps.
Thanks.
