### ISSUE TITLE
Pkg-config uses old Haiku Paths

### ISSUE THREAD

**Issue by agmsmith** [haikuports/haikuports#392]
pkg-config in the current Haiku gcc2 build (hrev49974) is version 0.27, which has the old search paths (including /boot/common) and doesn't have new ones (/boot/home/config/develop/lib/pkgconfig and all the non-packaged ones).  But it looks like the recipe for 0.29 has them, just needs a rebuild for more architectures than x86_64 (which has 0.29) I guess.

That would be useful for people trying to port things, since ./configure uses pkg-config to find out what libraries and modules are available.

By the way, the Lua port has the same problem, old recipe with bugs (no lua.pc file, which is what pkg-config looks for) is what's in Haiku, but there's a recipe with that fixed.

**Comment by pulkomandy** [comment]
Fixed in  hrev50011.
