### ISSUE TITLE
Found a way to hang SoundPlay 4.7.3 with the playlist editor

### ISSUE THREAD

**Issue by AlienSoldier2** [haikuports/haikuports#3922]
If i drag a mp3 directory on soundplay and that directory contain a large .png file, everything is fine until i launch the playlist editor, then soundplay hang at the first large .pgn file (like a hi-res cover art).

I dont know what is the cut off limit but i needed to remove 6.68M one and a 3.93M one from the directory.  The following big one that was accepted is 1.78M, so at some size (that may depend on the memory in the computer or cpu clock speed) soundplay time duration calculator may hit a hard coded limit of some kind.  I dont even know why it would bother with a .png file as it is not even a sound file and Soundplay does not have cover display feature anyway.

At one point playing with that bug i even froze the whole OS.

**Comment by extrowerk** [comment]
SoundPlay is closed source, so it is not really a bug what we can solve, except if it happens in the ffmpeg code.
I would say: create a ticket at the haiku bug tracker too, and it would be great if you can test the same folder with the same SoundPlay version on BeOS.

**Comment by waddlesplash** [comment]
Whole OS freezes we should fix, but those should be reported on Haiku's bugtracker. Otherwise, yes, not much we can do.
