### ISSUE TITLE
Pip3 not working - No module named `pkg_resources`

### ISSUE THREAD

**Issue by HelgeCPH** [haikuports/haikuports#3923]
Hi all, I am new here. Unfortunately, I do not know anything about the build process of Haiku Ports yet :)

It all started yesterday when I tried if I could replicate my usual Python 3 development setup on Haiku.

**Problem** in short: on Haiku version R1/beta1 (Revision hrev52295+129) `pip3` is not working with Python 3.7.

Here is what I did:

```bash
~> pkgman install python3
~> pkgman install pip_python3
```

The installation process works fine and Python itself seems to work. But `pip` cannot be used as it cannot locate the module `pkg_resources`

```bash
~> python3 --version 
Python 3.7.3
~> pip3 --version
Traceback (most recent call last):
  File "/bin/pip3", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

The underlying reason is that the `pip3` script in `/bin` points to the Python 3.6 interpreter instead of the Python 3.7 interpreter, see:

```bash
~> head -1 /bin/pip3
#!/bin/python3.6
```

As [extrowerk](https://discuss.haiku-os.org/u/extrowerk) pointed out in his [last post this morning](https://discuss.haiku-os.org/t/pip3-not-working-no-module-named-pkg-resources/8655/9?u=helgecph) in [the original thread](https://discuss.haiku-os.org/t/pip3-not-working-no-module-named-pkg-resources/8655), the issue comes likely from the [build recipe of `pip`](https://github.com/haikuports/haikuports/blob/master/dev-python/pip/pip-9.0.0.recipe). In particular lines 23 and 24. extrowerk suggests to change (if I understand it correctly) the two lines from

```
PYTHON_PACKAGES=(python python3)
PYTHON_VERSIONS=(2.7 3.6)
```

to 

```
PYTHON_PACKAGES=(python python36 python3)
PYTHON_VERSIONS=(2.7 3.6 3.7)
```

respectively.

One can see in the history, that the [`setuptools` build recipe](https://github.com/haikuports/haikuports/blob/master/dev-python/setuptools/setuptools-28.8.0.recipe) was [recently changed accordingly](https://github.com/haikuports/haikuports/commit/bd0863557eb3baf164a9b8fc26b80874f918b43d#diff-221aa4ae5f6f8ab0fdc4058b55d26424).

However, I think the correct way to install `pip3` today would be to provide the command directly from the Python 3.7 [recipe python3-3.7.3.recipe](https://github.com/haikuports/haikuports/blob/master/dev-lang/python/python3-3.7.3.recipe). Since Python 3.4, `pip` is provided by the language by default, see e.g., https://docs.python.org/3.4/whatsnew/3.4.html

That is, (if I understand it correctly) the following two lines could be added to the [`PROVIDES` block](https://github.com/haikuports/haikuports/blob/59018c8ec20fe47cf5a14066df39d495bfdcffd2/dev-lang/python/python3-3.7.3.recipe#L36
) of the `python3-3.7.3.recipe`:

```
    cmd:pip3 = $portVersion compat >= 3.7
    cmd:pip3.7 = $portVersion compat >= 3.7
```

Currently, I cannot try if that would really work as I do not know anything about building and installing Haiku packages yet. During the weekend I will have some time to see if I can read and understand how the HaikuPorter works and afterwards I could check if the above solution would work.

However, I know that when one builds Python from source on Linux or Unix (as it is done by the build recipe to my understanding), then the `exec_prefix/bin` directory contains a lot of scripts after the build, one of which is `pip`. That one would have just to be moved to Haiku's `bin` directory.

**Comment by extrowerk** [comment]
Sorry, my mistake!

**Comment by waddlesplash** [comment]
This is another Python 3.6/3.7 mixup...

We really need to just switch to one version and stick to it as much as possible IMO. Was there any reason to not just go with 3.7?

**Comment by pulkomandy** [comment]
https://github.com/haikuports/haikuports/issues/3822

**Comment by HelgeCPH** [comment]
I think I got it to work...

The `python3-3.7.3.recipe` could be modified as in the following:
https://github.com/HelgeCPH/haikuports/commit/e7a604f3d58b2b74b5aaf100ea74aa567abaa904

In essence, the main change is to build `pip` directly from the language distribution via `--with-ensurepip` in the configuration and adding the two corresponding commands (for some reason it was configured with `--without-ensurepip`). That builds a package containing Python 3.7 and the corresponding `pip` and `setuptools`. Nicely enough the built `pip` is also in a more recent version than the independently built `pip` from `pip_python3`, which is in version 9 something.

```bash
pip3 --version
pip 19.0.3 from /packages/python3-3.7.3-2/.self/lib/python3.7/vendor-packages/pip (python 3.7)
```

The installed `pip` works _almost_ fine :) One can install packages from PyPi, e.g.:

```bash
pip3 install autopep8
Collecting autopep8
  Downloading https://files.pythonhosted.org/packages/45/f3/24b437da561b6af4840c871fbbda32889ca304fc1f7b6cc3ada8b09f394a/autopep8-1.4.4.tar.gz (114kB)
    100% |████████████████████████████████| 122kB 3.2MB/s
Collecting pycodestyle>=2.4.0 (from autopep8)
  Downloading https://files.pythonhosted.org/packages/0e/0c/04a353e104d2f324f8ee5f4b32012618c1c86dd79e52a433b64fceed511b/pycodestyle-2.5.0-py2.py3-none-any.whl (51kB)
    100% |████████████████████████████████| 51kB 2.3MB/s
Installing collected packages: pycodestyle, autopep8
  The script pycodestyle is installed in '/packages/python3-3.7.3-2/.self/non-packaged/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py install for autopep8 ... done
Successfully installed autopep8-1.4.4 pycodestyle-2.5.0
```

I did not send a pull request to the recipe yet, as I **need a bit more of help**. Even though one can install packages nicely as described above. The installation process does not stop (keeps hanging). The reason is that `pip` tries to link some intermediate file to a lock file (I have no idea about why it tries to do this). Anyways, when hitting `CTRL-C` after installation of a package the error message starts with the following:

```
Traceback (most recent call last):
  File "/packages/python3-3.7.3-2/.self/lib/python3.7/vendor-packages/pip/_vendor/lockfile/linklockfile.py", line 31, in acquire
    os.link(self.unique_name, self.lock_file)
PermissionError: [Errno -2147483633] Operation not allowed: '/boot/home/config/cache/pip/shredder-9064f420.258272919010241199300258' -> '/boot/home/config/cache/pip/selfcheck.json.lock'
```

I think that is the same issue as described in issue [#3420](https://github.com/haikuports/haikuports/issues/3420).

I tried to modify the build recipe even further by adding a line to the `GLOBAL_WRITABLE_FILES` section as in the following:

```
GLOBAL_WRITABLE_FILES="
non-packaged/lib/python3.7/site-packages directory keep-old
/boot/home/config/cache/pip/ directory
"
```

However, this does not seem to solve the issue. How would I allow `pip` to link files in that respective directory, i.e., what do I have to add to the recipe and where?


Thank you for a well written `haikuporter` documentation on the wiki! Without any clue about Haiku packaging, I was quickly able to build a package.


--------

To reproduce what I did on a clean Haiku in the version specified above...

```
pkgman install -y haiku_devel
pkgman install -y libtool
pkgman install -y bzip2_devel
pkgman install -y expat_devel
pkgman install -y libffi_devel
pkgman install -y xz_utils_devel
pkgman install -y ncurses6_devel
pkgman install -y sqlite_devel
pkgman install -y readline_devel

git clone https://github.com/haikuports/haikuporter.git
cp haikuporter/haikuports-sample.conf /boot/home/config/settings/haikuports.conf

git clone https://github.com/HelgeCPH/haikuports.git --depth=10
cd ./haikuports/dev-lang/python/

git fetch origin 'python3':'python3'
git checkout python3

~/haikuporter/haikuporter python3-3.7.3

pkgman install -y /boot/home/haikuports/packages/python3-3.7.3-2-x86_64.hpkg

pip3 install autopep8
```

**Comment by pulkomandy** [comment]
+1 to using Python builtin Pip. I would prefer that we discuss the lock issue in the dedicated ticket, see you there.

**Comment by probonopd** [comment]
Cross-reference: https://github.com/pypa/pip/issues/6761

**Comment by waddlesplash** [comment]
It appears Pip fixed the upstream issue, so is there anything else to do here?

**Comment by HelgeCPH** [comment]
Hej @waddlesplash, thank you for taking this issue up again and congratulations for getting the possibility to work on Haiku full-time! After reading the news on HackerNews recently, I started having a look into the state of Python on Haiku again.

I just tried installing and using `pip` again. You are right that the issue as described in the headline and in the original issue description is resolved. The `ModuleNotFoundError: No module named 'pkg_resources'` exception is not raised anymore. I tried it on a fresh install of Haiku (hrev55370).

To test it, I did:

```
pkgman install -y python38
pkgman install -y pip_python38

pip3.8 install requests
```

and the `requests` module works after installation (`python3.8 -c "import requests"`).

Consequently, **this issue can be closed**.

However, while testing I identified an issue that is related to my earlier comments above. In essence, it seems that not all Python packages can be installed correctly with `pip3.8` due to that `pip` cannot write to all required directories. For example, installing `ipython` as in the following does not install the `ipython` CLI command since `pip` cannot write to `/packages/python38-3.8.8-5/.self/non-packaged`. I will describe that in a new issue.


```
~> pip3.8 install ipython
Collecting ipython
  Downloading https://files.pythonhosted.org/packages/50/b1/618daafee1bbc6e7e9dceb105eca919ca8eceeeda8b80282e25d416df39b/ipython-7.27.0-py3-none-any.whl (787kB)
     |████████████████████████████████| 788kB 1.6MB/s
Requirement already satisfied: setuptools>=18.5 in /boot/system/lib/python3.8/vendor-packages (from ipython) (42.0.0.post20210126)
Collecting decorator
  Downloading https://files.pythonhosted.org/packages/6a/36/b1b9bfdf28690ae01d9ca0aa5b0d07cb4448ac65fb91dc7e2d094e3d992f/decorator-5.0.9-py3-none-any.whl
Collecting jedi>=0.16
  Downloading https://files.pythonhosted.org/packages/f9/36/7aa67ae2663025b49e8426ead0bad983fee1b73f472536e9790655da0277/jedi-0.18.0-py2.py3-none-any.whl (1.4MB)
     |████████████████████████████████| 1.4MB 2.1MB/s
Collecting pexpect>4.3; sys_platform != "win32"
  Downloading https://files.pythonhosted.org/packages/39/7b/88dbb785881c28a102619d46423cb853b46dbccc70d3ac362d99773a78ce/pexpect-4.8.0-py2.py3-none-any.whl (59kB)
     |████████████████████████████████| 61kB 3.1MB/s
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Downloading https://files.pythonhosted.org/packages/c6/37/ec72228971dbaf191243b8ee383c6a3834b5cde23daab066dfbfbbd5438b/prompt_toolkit-3.0.20-py3-none-any.whl (370kB)
     |████████████████████████████████| 378kB 1.8MB/s
Collecting traitlets>=4.2
  Downloading https://files.pythonhosted.org/packages/38/4c/466298b114eea62f300dbef98cc2c33c6cbc439f1f71bc199c674ae23c2c/traitlets-5.1.0-py3-none-any.whl (101kB)
     |████████████████████████████████| 102kB 1.4MB/s
Collecting pickleshare
  Downloading https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
Collecting pygments
  Downloading https://files.pythonhosted.org/packages/78/c8/8d9be2f72d8f465461f22b5f199c04f7ada933add4dae6e2468133c17471/Pygments-2.10.0-py3-none-any.whl (1.0MB)
     |████████████████████████████████| 1.0MB 2.7MB/s
Collecting backcall
  Downloading https://files.pythonhosted.org/packages/4c/1c/ff6546b6c12603d8dd1070aa3c3d273ad4c07f5771689a7b69a550e8c951/backcall-0.2.0-py2.py3-none-any.whl
Collecting matplotlib-inline
  Downloading https://files.pythonhosted.org/packages/7f/de/6c111d687335729cf8c156394c8d119b0dc3c34b6966ff2a2f7fe4aa79cf/matplotlib_inline-0.1.2-py3-none-any.whl
Collecting parso<0.9.0,>=0.8.0
  Downloading https://files.pythonhosted.org/packages/a9/c4/d5476373088c120ffed82f34c74b266ccae31a68d665b837354d4d8dc8be/parso-0.8.2-py2.py3-none-any.whl (94kB)
     |████████████████████████████████| 102kB 3.8MB/s
Collecting ptyprocess>=0.5
  Downloading https://files.pythonhosted.org/packages/22/a6/858897256d0deac81a172289110f31629fc4cee19b6f01283303e18c8db3/ptyprocess-0.7.0-py2.py3-none-any.whl
Collecting wcwidth
  Downloading https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
Installing collected packages: decorator, parso, jedi, ptyprocess, pexpect, wcwidth, prompt-toolkit, traitlets, pickleshare, pygments, backcall, matplotlib-inline, ipython
  WARNING: The script pygmentize is installed in '/packages/python38-3.8.8-5/.self/non-packaged/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: Could not install packages due to an EnvironmentError: [Errno -2147459064] Read-only file system: '/packages/python38-3.8.8-5/.self/non-packaged'
```
