### ISSUE TITLE
Linux compatibility layer feature request

### ISSUE THREAD

**Issue by megastallman** [haikuports/haikuports#3941]
Hi guys!

What about the idea of running Linux x86_64 binaries? You have already got BeOS programs support, why not add a possibility to run Linux chroots? It think it can increase the userbase. As I know, you can get the hardware that runs Haiku fine, why not also try to get the software we all used to run...
 Of course it would also require about a half of Linux kernel syscalls support, either as a kernel module, or a userspace wrapper. VFS and networking. And maybe Wayland in future.
Anyway, it is a great amount of work, if anyone could do it.

**Comment by extrowerk** [comment]
This is not the right place to ask for linux compatibility.
You can open an enhancement ticket at Haiku bugtracker, but don1t hold your breath as it isn't the scope of the os.
