### ISSUE TITLE
Update freetype to 2.10.1

### ISSUE THREAD

**Issue by luzpaz** [haikuports/haikuports#3950]
https://github.com/haikuports/haikuports/blob/master/media-libs/freetype/freetype-2.9.1.recipe

https://sourceforge.net/projects/freetype/files/freetype2/2.10.0/

**Comment by Begasus** [comment]
freetype is a very common library used by many others, just updating means checking all dependencies, maybe you could chip in to do that? :)

**Comment by korli** [comment]
Let's wait for 2.10.1 (see https://www.mail-archive.com/freetype-devel@nongnu.org/msg11206.html )

**Comment by kenmays** [comment]
```
Freetype 2.10.1 stable release: https://sourceforge.net/projects/freetype/files/freetype2/2.10.1/freetype-2.10.1.tar.xz/download

  I. IMPORTANT BUG FIXES
  - The bytecode hinting of OpenType variation fonts was flawed, since
    the data in the `CVAR' table wasn't correctly applied.
```

**Comment by korli** [comment]
updated to 2.10.4
