### ISSUE TITLE
Update krita to 4.2.2

### ISSUE THREAD

**Issue by luzpaz** [haikuports/haikuports#3960]
4.2.2 has been released
https://github.com/KDE/krita/releases/tag/v4.2.2

**Comment by diversys** [comment]
New version of Krita depends on OpenGL support in QPA (https://github.com/threedeyes/qthaikuplugins/)
Which it still doesn't have. The latest version of Krita which doesn't use it is 4.1.8.

**Comment by luzpaz** [comment]
Thanks

**Comment by threedeyes** [comment]
Krita has been updated to the latest possible version (4.1.8) - 13ccc056e00a70f781ebd3c8e17d49b2778571c7
