### ISSUE TITLE
Update masterpiece recipe to point to HaikuArchives

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#3961]
https://github.com/HaikuArchives/Masterpiece

haiku-apps/masterpiece/

**Comment by Begasus** [comment]
Updating the recipe is working fine, also the install part, but it can't find the .db file (or if copied can't read/write to it?) So I think the source needs to be rewritten so it searches the database file in $settingsDir or ~/config/settings ...

**Comment by Begasus** [comment]
Done in: https://github.com/haikuports/haikuports/pull/10651
