### ISSUE TITLE
[Wishlist] MacDecorator

### ISSUE THREAD

**Issue by probonopd** [haikuports/haikuports#3977]
I'd like to see a [MacDecorator](https://github.com/haiku/haiku/tree/master/src/add-ons/decorators/MacDecorator) package.

![](https://pbs.twimg.com/media/Do7EJqaXkAACRZ-.jpg)

**Comment by waddlesplash** [comment]
MacDecorator is (for now) part of the Haiku repository itself.

There is a reason we do not ship it at all, though: it does not properly support Stack & Title (i.e you cannot tab windows together) which we consider a crucial feature of our window management system. Once that's fixed we will probably add it to the `haiku_extras` package.

**Comment by diversys** [comment]
For the time being you can compile it yourself using `jam MacDecorator` in haiku sources.
