### ISSUE TITLE
SDL is somewhat broken

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#3986]
Lately mpv repeatedly crashes with every mediafiles. Rebuild doesn't helps.
According to the crashlog it a bug lurking in the SDL2 port.

Crashlog with LD_PRELOAD=libroot_debug.so: https://pastebin.com/raw/4qJpSmit

**Comment by waddlesplash** [comment]
CC @threedeyes, @pulkomandy ?

**Comment by extrowerk** [comment]
LD_PRELOAD=libroot_debug.so MALLOC_DEBUG=g : https://pastebin.com/raw/z1iRGETW

**Comment by pulkomandy** [comment]
Seems tobe a bug in either one of SDL, BGLView, or BDirectWindow. Is this SDL1 or SDL2?

**Comment by extrowerk** [comment]
@PulkoMandy : mpv built against SDL2.

**Comment by extrowerk** [comment]
mpv seems to be working now.

**Comment by diversys** [comment]
Doesn't crash for me either using sample .mp4 file. Closing.
