### ISSUE TITLE
Qutebrowser crashes on startup

### ISSUE THREAD

**Issue by tidux** [haikuports/haikuports#3988]
````
/boot/system/apps> ./QuteBrowser 
Traceback (most recent call last):
  File "./QuteBrowser", line 8, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
````

**Comment by tidux** [comment]
This appears to be an issue with Pip.

https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

**Comment by kenmays** [comment]
![qutebrowser-1 7 0_haiku](https://user-images.githubusercontent.com/5168719/63386560-3e396d00-c358-11e9-9bd2-45dcb2413061.jpeg)
Screenshot from my qutebrowser 1.7.0 build from today.

Both 1.6.x and 1.7.0 compiles fine. Got it working. Think it is a config issue, but got a debug report for review.

**Comment by kenmays** [comment]
Retested on hrev53393 x86_64 and qutebrowser-1.6.1-1-x86_64.hpkg.
**Issues resolved.** No crash issues upon boot or during usage,
