### ISSUE TITLE
Krita: Use crosshair cursor rather than Haiku hand cursor for Crop tool

### ISSUE THREAD

**Issue by probonopd** [haikuports/haikuports#3994]
The "hand" cursor in Haiku gets annoying when trying to use the Crop tool in Krita, resulting in imprecise cutouts. A crosshair cursor would do wonders for the crop tool

@waddlesplash says:
> Krita should probably use a crosshair cursor, then. (Possibly it does and it's a Qt port bug that it doesn't show up.) The "hand" cursor is not supposed to be used everywhere...

**Comment by probonopd** [comment]
Just verified with `krita-4.1.0-beta.2-x86_64.appimage` on Linux, it does change to a crosshairs cursor when selecting the crop tool:

![](https://user-images.githubusercontent.com/2480569/61252586-88be3d00-a74d-11e9-8236-865aaba3f72d.png)

**Comment by threedeyes** [comment]
Krita uses custom "xpm" cursors for this - https://github.com/KDE/krita/blob/2d26883f193e149969d7563ec813912590c06c21/libs/ui/kis_cursor.cc#L46
My QPA (Qt Platform Abstraction) plugin does not support custom bitmap cursors. There is only the standard cursors mapper - https://github.com/threedeyes/qthaikuplugins/blob/master/platforms/qhaikuplatform/haiku/qhaikucursor.cpp#L56

I see two ways: 
1. implement custom cursors in Qt (hard)
2. patch Krita to use standard cursors from the list of mapped ones (simple)

**Comment by probonopd** [comment]
Thanks for looking into this @threedeyes. I can't say which approach is better.

**Comment by waddlesplash** [comment]
Custom cursors can be added to BCursor rather easily. Why would implementing support for this in the QPA be difficult?

**Comment by threedeyes** [comment]
Our cursors have a fixed size 16x16, but in Qt used custom sizes (mostly used bitmap size 32x32).

**Comment by waddlesplash** [comment]
OK, then just re-scale the cursor to 16x16... One-line call to QImage to do so.

**Comment by threedeyes** [comment]
It is a not good idea to resize for low-resolution pixel images. Rescaled сursors will be of ugly quality.
And we need recalc hotsport point for it.

**Comment by pulkomandy** [comment]
Just extend our API on Haiku side to allow custom/larger sizes?

**Comment by threedeyes** [comment]
> Just extend our API on Haiku side to allow custom/larger sizes?

That would be perfect. And for one would solve the problem of the very small cursor on HiDPI displays.
But it does not break BeOS compatibility?

**Comment by pulkomandy** [comment]
https://git.haiku-os.org/haiku/tree/headers/os/app/Cursor.h

It looks like we can just add a new constructor (taking a BBitmap?) here. The cursor data is stored on app_server side so I don't see what would break by doing that.

**Comment by pulkomandy** [comment]
https://dev.haiku-os.org/ticket/15169#ticket

**Comment by threedeyes** [comment]
>OK, then just re-scale the cursor to 16x16... One-line call to QImage to do so.

I try make it. It's ugly:

http://haikuware.ru/files/screenshots/krita_cursor.png

**Comment by probonopd** [comment]
I think a simple cursor like this would do:

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTl0C-YQ7LYU3nV3AB94VkKNr1MZxpPwG2TG9w_u0NP4l7CGEFA)

**Comment by threedeyes** [comment]
Added custom pixmap cursors in https://github.com/haikuports/haikuports/commit/19e0e3da07b9cbfa02b8067a1734b9a47643d3ad

**Comment by probonopd** [comment]
Thank you @threedeyes
