### ISSUE TITLE
Each and every Boost version busted

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#3998]
```
In file included from /boot/system/develop/headers/boost/dll/detail/posix/shared_library_impl.hpp:13,
                 from /boot/system/develop/headers/boost/dll/shared_library.hpp:26,
                 from /sources/s25client-90d4fe80cff72e57b7e604ba6eefb85a7985f97c/libs/s25main/drivers/DriverWrapper.cpp:29:
/boot/system/develop/headers/boost/dll/detail/posix/path_from_handle.hpp:109:13fatal error: link.h: No such file or directory
 #   include <link.h>    // struct link_map
             ^~~~~~~~
compilation terminated.
```

AFAIK Haiku doesn't provides link.h, which is a part of glibc. It should be either patched in every boost port or Haiku should provide (if possible) this header.

Affected: boost 1.64, 1.65, 1.66, 1.69 for sure, 1.63 probably too.

**Comment by pulkomandy** [comment]
On Tue, Jul 16, 2019 at 10:18:30AM -0700, miqlas wrote:
> /boot/system/develop/headers/boost/dll/detail/posix/path_from_handle.hpp:109:13fatal error: link.h: No such file or directory
> AFAIK Haiku doesn't provides link.h, which is a part of glibc. It should be either patched in every boost port or Haiku should provide (if possible) this header.

It seems easy enough to import the headers (or the relevant parts) from
the FreeBSD version:

https://github.com/freebsd/freebsd/blob/master/sys/sys/link_elf.h

**Comment by extrowerk** [comment]
I can do that if we can import it as-is.

**Comment by waddlesplash** [comment]
Are there any associated .c files? If not, putting these in the "BSD" headers directory behind _BSD_SOURCE sounds like the way to go.

**Comment by extrowerk** [comment]
Should it go then to bsd/sys, right?
I can guard it with _BSD_SOURCE, thats not a big deal i think, i just don't know if i should rename it to link.h or not. For maintainability it shouldn't be renamed, then every boost version have to be patched i fear.

**Comment by extrowerk** [comment]
Ok, i see there is a https://github.com/freebsd/freebsd/blob/1d6e4247415d264485ee94b59fdbc12e0c566fd0/include/link.h too which doesn't do anything just includes link_elf.h, then we could import that too.

Otherwise the link_elf.h tries to use "dl_iterate_phdr" here: https://github.com/freebsd/freebsd/blob/master/sys/sys/link_elf.h#L96
which is afaik not available on Haiku. Should i just remove it?

**Comment by extrowerk** [comment]
Headers successfully merged from FreeBSD, so lets close this.
