### ISSUE TITLE
[Wishlist] lddtree

### ISSUE THREAD

**Issue by probonopd** [haikuports/haikuports#4000]
`lddtree`, a `ldd` replacement for Haiku

https://github.com/diversys/lddtree

**Comment by Begasus** [comment]
Maybe nice as an GCI task @scottmc ?

**Comment by augiedoggie** [comment]
lddtree is available in the pax-utils package for x86_64 and x86.  Is there a need for a separate package for lddtree?

**Comment by probonopd** [comment]
No. Thanks for hinting at pax-utils!
