### ISSUE TITLE
[Wishlist] switchers_commands

### ISSUE THREAD

**Issue by probonopd** [haikuports/haikuports#4001]
https://github.com/probonopd/switchers_compat

Commands to make it easier for switchers coming from other operating systems such as Linux, macOS, and Windows to use Haiku

**Comment by waddlesplash** [comment]
-1.

No other OSes seem to provide this, and I have not heard of users that need it. Most people seem to find the task of learning a new CLI easy enough. If they don't learn the OS itself, but just a bunch of compatibility shims, have they really "switched to Haiku"?

Leaving this open for now in case the other maintainers have other thoughts, but otherwise, I don't really see the point.

**Comment by probonopd** [comment]
Easing transition. Making newcomers feel at home immediately.

**Comment by waddlesplash** [comment]
The transition should be eased by more documentation, not compatibility shims or hacks. We want users to be themselves integrated into Haiku. :)

**Comment by extrowerk** [comment]
Strong -1, we definetely dont want newconers giving telling eachother: “just use apt”.
If one needs something like this, could use own alias.

Fun fact: i used a “pkgman” alias to “sudo apt” on ubuntu for years because muscle memory.

**Comment by probonopd** [comment]
This is what I have so far:

```
Welcome to the Haiku shell.

~> apt-get install foo
Use instead:
pkgman
```

Isn't that a good balance between not having anything and “just use apt”? Do you have a better suggestion, apart from "do nothing"?

Besides, I _like_ that `shutdown` command ;-)

**Comment by pulkomandy** [comment]
"do nothing" sounds fine to me as well. Either you are an inexperienced user and you don't know about apt-get (or is it aptitude? or apt? even Debian/Ubuntu can't decide) and this will not help you. Or, you already know how to use a package manager, and you already know all too well that every Linux distro or OS does its own thing.

If there were a freedesktop standard or similar for naming, we might consider it. But it will be something silly like xdg-package (hello xdg-open!) that no one uses :)

**Comment by extrowerk** [comment]
It prooves 2 things:
- i haven't checked your code
- i dislike linux so much i don't even want to know about it

**Comment by probonopd** [comment]
;-)

**Comment by waddlesplash** [comment]
Well, closing this as wont-fix then.
