### ISSUE TITLE
[Wishlist] FontMonkey

### ISSUE THREAD

**Issue by probonopd** [haikuports/haikuports#4003]
A font manager for Haiku

http://clasquin-johnson.co.za/michel/haiku/blog/2016/new-app-fontmonkey-for.html

**Comment by waddlesplash** [comment]
Nah, I've looked at it before and it's just a hack. It doesn't automatically make those pretty previews, they're static PNGs included with the font files, that are just shipped with it. The concept is good, but I don't think this one should get a recipe, it's too low-quality.

**Comment by probonopd** [comment]
So a rewrite would be in order? Would Python bindings and native Haiku UI be an acceptable choice for writing something like this or does it have to be C++?

**Comment by waddlesplash** [comment]
For a third-party app, anything is acceptable so long as it's well-written of course. For an in-tree app in Haiku itself, as this should be, it needs to be C++, indeed.

**Comment by extrowerk** [comment]
Afaik one cannot draw a preview about a not yet installed font, at least there is some limitation in app_server which doesnt allows proper use of webfonts in WebPositive. Am i correct here?
If so currently would be tricky to create a preview about arbitary fonts, probably requires app_server changes.

**Comment by pulkomandy** [comment]
That's right.
Also we already have fontdemo in Haiku and fontboy (not sure there is a recipe for it yet)

**Comment by probonopd** [comment]
Fontboy is a start indeed. Thanks for the hint.
