### ISSUE TITLE
[Wishlist] qTox

### ISSUE THREAD

**Issue by probonopd** [haikuports/haikuports#4013]
https://tox.chat/clients.html

> qTox is a powerful client based on Qt, with an intuitive and feature rich user interface as well as a fast core written in C++. qTox runs on Windows, Linux, MacOS and FreeBSD and offers text messaging, audio and video calls, screen sharing and file transfers. Additionally it has support for text and audio group chats as well as Identicons as avatars. New features are regularly added by our active and welcoming community.

https://discuss.haiku-os.org/t/utox-qtox-open-source-peer2peer-skype-alternative/3825/8

> qTox is C++ and uses Qt so there’s no reason why it couldn’t be ported. You just need to find a developer

**Comment by extrowerk** [comment]
After a quick scan: yeah, looks possible, for sure, just.... many dependencies.

**Comment by Begasus** [comment]
You need libtoxav (which can only be enabled by using libvpx) (latest version for tox still builds) but you'll encounter other issues ...

**Comment by return** [comment]
I'm sure it is possible to port this over. Also sounds like a good GCI task too.

**Comment by pulkomandy** [comment]
If you want to turn this into a GCI task, better have a good idea where we're going (at least identify all needed dependencies)

**Comment by Begasus** [comment]
As far as the requirements, you need to enable libvpx in tox to get the library libtoxav (needed)
Check here for the other requirements: https://pastebin.com/UxqGnw8b

**Comment by Begasus** [comment]
OK, looks like it's not too hard :)
![qTox](https://user-images.githubusercontent.com/16057090/69147610-b4be4600-0ad2-11ea-9ca8-04d27bf2cccb.png)

**Comment by Begasus** [comment]
Checked on 32bit and 64bit, both working fine (build from Terminal)

**Comment by Begasus** [comment]
Most of the dependencies are available for Haiku, only the libtoxav thing needs to be solved (aside from some other issues to be dealt by when building), so that one needs to be fixed first, issue filed at: https://github.com/haikuports/haikuports/issues/4394

**Comment by probonopd** [comment]
Very cool @Begasus :+1:

**Comment by Begasus** [comment]
tox has been fixed for cmake, checking a final build for latest qtox here :)

**Comment by Begasus** [comment]
Merged in https://github.com/haikuports/haikuports/pull/5489
