### ISSUE TITLE
nodejs not available for installation

### ISSUE THREAD

**Issue by probonopd** [haikuports/haikuports#4032]
nodejs is not available for installation (`pkgman i nodejs`) despite there seems to be a recipe:

https://github.com/haikuports/haikuports/blob/b9b46ae37528ce3312e4eb6aaeea3c5204d6886e/net-libs/nodejs/nodejs-12.3.1.recipe#L38

**Comment by return** [comment]
@probonopd It is ported but there is no package because of an issue with the beta1 buildbots.

See: https://github.com/haikuports/haikuports/pull/3897#issuecomment-501426930

**Comment by probonopd** [comment]
Thanks @return. Btw, I like your icon ;-)

**Comment by return** [comment]
Node.js is now available in the package repos for x86_64. This can be closed.

**Comment by probonopd** [comment]
Thank you very much. :+1:
