### ISSUE TITLE
lighttpd - recipe REQUIRES lib:libuuid >=1.3, found in util_linux package.

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#4071]
lighttpd 1.4.5 recipe has a REQUIRES for libuuid >=1.3. I believe that's incorrect, and should instead be 1.0.3. As a result, package will not build on 64 bit.

**Comment by korli** [comment]
Just tested the package is buildable on x86_64. it installs also correctly.

**Comment by Vidrep** [comment]
problem 1: package lighttpd-1.4.51-1 requires lib:libuuid>=1.3.0, but none of the providers can be installed

**Comment by korli** [comment]
lib:libuuid>=1.3.0 is provided by util_linux. Please try to install it.

**Comment by Begasus** [comment]
If lib:libuuid >= 1.3.0 is needed maybe the recipe for lighttpd should use util_linux instead then?

**Comment by Begasus** [comment]
Just checked, they conflict (util_linux and libuuid) so you can't have both installed ...

**Comment by Begasus** [comment]
lighttpd latest build is ok with using util_linux (in REQUIRES) and util_linux_devel (in REQUIRES_devel) withouth lib:libuuid ... (on x86_64), grabbing lighttpd-1.4.54-1-x86_64.hpkg and moving it to /boot/home/haikuports/packages/lighttpd-1.4.54-1-x86_64.hpkg

**Comment by korli** [comment]
@Vidrep please check with "pkgman uninstall libuuid" which packages depend on it?

**Comment by Vidrep** [comment]
Installing util_linux solved the initial issue with building lighttpd. However, attempting to uninstall util_linux so I can install libuuid, results in a very long list of apps to be removed which depend on it. Is this the list you need to see?

**Comment by Vidrep** [comment]
Welcome to the Haiku shell.

~> pkgman uninstall util_linux
The following changes will be made:
  in system:
    uninstall package filwip-2.0.0-1
    uninstall package p7zip-9.20.1-7
    uninstall package zip-3.0-4
    uninstall package llvm8_clang_analysis-8.0.0-1
    uninstall package dos2unix-7.4.0-2
    uninstall package cmake-3.9.5-2
    uninstall package automake-1.16.1-1
    uninstall package findutils-4.6.0-1
    uninstall package xz_utils-5.2.4-2
    uninstall package sharutils-4.15.2-3
    uninstall package tcpdump-4.9.2-1
    uninstall package makefile_engine-r1~beta1_hrev53340_2-1
    uninstall package autoconf-2.69-8
    uninstall package scons-2.5.1-3
    uninstall package wpa_supplicant-2.7~devel.haiku.1-1
    uninstall package vision-0.10.3-2
    uninstall package git_daemon-2.21.0-5
    uninstall package bison-3.0.5-1
    uninstall package lighttpd-1.4.51-1
    uninstall package pe-2.4.5-8
    uninstall package mesa_swpipe-17.1.10-4
    uninstall package burnitnow-1.2-4
    uninstall package jam-2.5_2018_11_21-6
    uninstall package openssl_man-1.0.2s-1
    uninstall package bc-1.07.1-2
    uninstall package netcat-1.10-4
    uninstall package gperf-3.1-1
    uninstall package openssh-7.9p1-3
    uninstall package patch-2.7.6-2
    uninstall package which-2.21-5
    uninstall package ruby-2.6.3-2
    uninstall package nasm-2.12.02-1
    uninstall package libxslt_devel-1.1.32-1
    uninstall package libwebp_devel-1.0.2-1
    uninstall package libpcre_devel-8.42-1
    uninstall package libexecinfo_devel-1.1-5
    uninstall package jpeg_devel-9c-2
    uninstall package curl_devel-7.64.1-1
    uninstall package nghttp2_devel-1.34.0-1
    uninstall package sqlite_devel-3.28.0.0-1
    uninstall package mesa_devel-17.1.10-4
    uninstall package haiku_devel-r1~beta1_hrev53340_2-1
    uninstall package gnutls_devel-3.6.4-1
    uninstall package glu_devel-9.0.0-7
    uninstall package freetype_devel-2.9.1-1
    uninstall package bepodder-1.5.0-1
    uninstall package pywebsocket-0.8-1
    uninstall package wget-1.20.1-1
    uninstall package webpositive-r1~beta1_hrev53340_2-1
    uninstall package flex-2.6.4-1
    uninstall package libvorbis_debuginfo-1.3.6-1
    uninstall package libunistring_debuginfo-0.9.10-1
    uninstall package libtasn1_debuginfo-4.13-1
    uninstall package libopenmpt_debuginfo-0.4.4-3
    uninstall package libidn2_debuginfo-2.0.5-1
    uninstall package libiconv_debuginfo-1.15-4
    uninstall package ffmpeg_debuginfo-4.1.4-1
    uninstall package openssl_debuginfo-1.0.2s-1
    uninstall package texinfo-6.5-4
    uninstall package gnutls_debuginfo-3.6.4-1
    uninstall package gcc_debuginfo-8.3.0_2019_05_24-5
    uninstall package bzip2_debuginfo-1.0.6-8
    uninstall package ctags-5.8-5
    uninstall package pkgconfig-0.29.2-3
    uninstall package streamradio-0.0.3_14-4
    uninstall package llvm8_clang-8.0.0-1
    uninstall package rhash-1.3.8-1
    uninstall package libpcap-1.8.1-4
    uninstall package mkdepend-1.7-5
    uninstall package make-4.1-3
    uninstall package git-2.21.0-5
    uninstall package lua51-5.1.5-1
    uninstall package openldap-2.4.46-1
    uninstall package llvm7_libs-7.0.1-2
    uninstall package cdrtools-3.02~a09-1
    uninstall package grep-3.3-1
    uninstall package sed-4.4-3
    uninstall package libxml2_devel-2.9.9-4
    uninstall package libpcre-8.42-1
    uninstall package openssl_devel-1.0.2s-1
    uninstall package nettle_devel-3.4.1-1
    uninstall package libgcrypt_devel-1.8.4-1
    uninstall package libtasn1_devel-4.13-1
    uninstall package glu-9.0.0-7
    uninstall package bzip2_devel-1.0.6-8
    uninstall package libpng16_devel-1.6.37-1
    uninstall package haikuwebkit-1.6.9-1
    uninstall package m4-1.4.18-3
    uninstall package gcc-8.3.0_2019_05_24-5
    uninstall package llvm8_libs-8.0.0-1
    uninstall package perl-5.30.0-1
    uninstall package libpcre2-10.33-1
    uninstall package man-1.6g-6
    uninstall package python-2.7.16-3
    uninstall package nano-4.2-2
    uninstall package zlib_devel-1.2.11-3
    uninstall package icu_devel-57.1-3
    uninstall package libgpg_error_devel-1.36-1
    uninstall package mesa-17.1.10-4
    uninstall package libexecinfo-1.1-5
    uninstall package libxslt-1.1.32-1
    uninstall package mpc-1.1.0-1
    uninstall package binutils-2.31.1-1
    uninstall package libedit-20180525_3.1-2
    uninstall package gawk-4.2.1-1
    uninstall package less-550-2
    uninstall package diffutils-3.7-1
    uninstall package libffi-3.2.1-4
    uninstall package sqlite-3.28.0.0-1
    uninstall package groff-1.22.3-1
    uninstall package mpfr-3.1.6-3
    uninstall package unzip-6.10c23-4
    uninstall package haiku-r1~beta1_hrev53340_2-1
    uninstall package gzip-1.10-1
    uninstall package ffmpeg-4.1.4-1
    uninstall package libvorbis-1.3.6-1
    uninstall package gnutls-3.6.4-1
    uninstall package libtasn1-4.13-1
    uninstall package libidn2-2.0.5-1
    uninstall package nettle-3.4.1-1
    uninstall package gmp-6.1.2-3
    uninstall package libunistring-0.9.10-1
    uninstall package libgcrypt-1.8.4-1
    uninstall package libgpg_error-1.36-1
    uninstall package libopenmpt-0.4.4-3
    uninstall package libtheora-1.1.1-7
    uninstall package libvpx3-1.5.0-3
    uninstall package speex-1.2.0-4
    uninstall package libogg-1.3.3-2
    uninstall package curl-7.64.1-1
    uninstall package nghttp2-1.34.0-1
    uninstall package fontconfig-2.13.1-2
    uninstall package freetype-2.9.1-1
    uninstall package bzip2-1.0.6-8
    uninstall package coreutils-8.29-2
    uninstall package libsolv-0.3.0_haiku_2014_12_22-3
    uninstall package libicns-0.8.1-8
    uninstall package openjpeg-2.3.1-2
    uninstall package lcms-2.9-2
    uninstall package bash-4.4.023-2
    uninstall package readline-7.0.3-4
    uninstall package gettext_libintl-0.19.8.1-7
    uninstall package libwebp-1.0.2-1
    uninstall package giflib-5.1.4-2
    uninstall package libpng16-1.6.37-1
    uninstall package libiconv-1.15-4
    uninstall package libxml2-2.9.9-4
    uninstall package ncurses6-6.1-1
    uninstall package gutenprint8-5.3.1-1
    uninstall package tar-1.32-1
    uninstall package expat-2.2.6-1
    uninstall package gcc_syslibs-8.3.0_2019_05_24-5
    uninstall package tiff4-4.0.10-1
    uninstall package openexr-2.2.1-2
    uninstall package ilmbase-2.2.1-2
    uninstall package openssl-1.0.2s-1
    uninstall package zstd-1.4.1-1
    uninstall package icu-57.1-3
    uninstall package jasper-2.0.16-1
    uninstall package jpeg-9c-2
    uninstall package zlib-1.2.11-3
    uninstall package util_linux-2.33-2
Continue? [yes/no] (yes) :

**Comment by korli** [comment]
No, I wanted the list of packages uninstalled along with libuuid.

**Comment by Vidrep** [comment]
Welcome to the Haiku shell.

~> pkgman uninstall libuuid
The following changes will be made:
  in system:
    uninstall package libuuid-1.0.3-6
Continue? [yes/no] (yes) :

**Comment by Vidrep** [comment]
libuuid and util_linux cannot co-exist together. It appears what is required for lighttpd is the util_linux package and not libuuid.

**Comment by korli** [comment]
Yes that's normal, the two provides one conflicting library. I've switched most of the consumers to util_linux version. @Vidrep  is this bug still valid?

**Comment by Vidrep** [comment]
What Begasus said earlier. The package requires util_linux instead of the stand alone libuuid packages.

**Comment by Begasus** [comment]
I think this should be dealt with haikuporter instead, libuuid >= 1.3 is provided by util_linux, but haikuporter won't install that (if you haven't got it) (seen it happen a few times ... lib:libsomething >= someversion isn't picked up by haikuporter, you have to manually install the other one ...

**Comment by Vidrep** [comment]
Installing lighttpd is working now since the inclusion of util_linux package in the builds. Closing as resolved. Thanks.

**Comment by kallisti5** [comment]
@Vidrep I forked libuuid and added it to the repos.   (So we no longer require util_linux for libuuid)
