### ISSUE TITLE
[Wishlist] Bump Netsurf to the newly released 3.9 version

### ISSUE THREAD

**Issue by Konrad77** [haikuports/haikuports#4077]
Would be nice if we could get the new version of Netsurf available for Haiku. It was just released.

**Comment by pulkomandy** [comment]
The NetSurf team has not distributed tarballs of the dependencies releases: http://download.netsurf-browser.org/libs/releases/

Therefore it cannot be packaged in HaikuPorts. Please ask them to publish the release if you want NetSurf to be updated here.

Meanwhile, you can download it from the NetSurf builds: https://ci.netsurf-browser.org/builds/haiku/release/ (which they have not linked to anywhere in their website despite me asking repeatedly either, so please complain on their mailing list until they do).

**Comment by Konrad77** [comment]
Thanks. Will do!

**Comment by korli** [comment]
@pulkomandy I see the dependencies released. 
http://download.netsurf-browser.org/netsurf/releases/ChangeLog.txt
Hubbub library 0.3.6
LibCSS library 0.9.0
LibDOM library 0.3.4 and 0.4.0 (not sure which one)
LibNSPSL library 0.1.5

**Comment by kenmays** [comment]
![netsurf-3 9_haiku](https://user-images.githubusercontent.com/5168719/62586943-9b232680-b874-11e9-9b02-5ea8e889cd16.png)
@Konrad77 - I created a build for Haiku, Will check with the NetSurf devs.

**Comment by pulkomandy** [comment]
The Netsurf devs already provide an official build for Haiku which I linked to. So they are aware it builds and runs fine.
Since it seems the libraries are indeed in the release directory now, I will see about updating the packages in the evening.

**Comment by Konrad77** [comment]
I can't just download run the packages from https://ci.netsurf-browser.org/builds/haiku/release/ as Tracker says it doesn't know how to "open" the application. Do I need to change some attributes first?

**Comment by pulkomandy** [comment]
I think you need to mark it as executable (chmod +x)
Or more conveniently you can get one of the nightly builds instead, these are distributed as hpkg files: https://ci.netsurf-browser.org/builds/haiku/

**Comment by Konrad77** [comment]
Hmm I guess this is only for 32 bit versions of Haiku. Right?

**Comment by pulkomandy** [comment]
It seems so, yes.

I'm looking into updating our packages, but at least netsurf_buildsystem 1.8 is not available in the releases . It seems to be only a change specific to Fedora, so I'll see if I can use buildsystem 1.7 to build the other libs.

**Comment by kenmays** [comment]
The x86_64 build works as well.

![netsurf-3 9-x86_64](https://user-images.githubusercontent.com/5168719/62815570-65c64500-bacf-11e9-9501-145142e14949.jpeg)

**Comment by Konrad77** [comment]
Hmm x64 crashes in Qemu and VirtualBox for me.
