### ISSUE TITLE
[Wishlist] nnn

### ISSUE THREAD

**Issue by jarun** [haikuports/haikuports#4083]
This is a request to package `nnn` - a full-featured file manager for low-end devices and the regular desktop.

Homepage: https://github.com/jarun/nnn

Would highly appreciate if `nnn` can be added to HaikuPorts.

**Comment by waddlesplash** [comment]
It appears you are the author of nnn, would you care to submit a recipe yourself? We'll be happy to help you learn the process :)

**Comment by jarun** [comment]
I would already have done that if I had the bandwidth. Hence the request for someone accustomed to the process.

**Comment by Begasus** [comment]
First error, sysmacros.h isn't in Haiku ...

**Comment by Begasus** [comment]
Second error sys/event doesn't seem included ...

**Comment by jarun** [comment]
> sys/sysmacros.h isn't in Haiku

does it compile without it? I see on Ubuntu, the include is not required.
If yes, is there any Haiku-specific macro I can use to block the inclusion?

> sys/event doesn't seem included

I think we can include it. Somehow it feels like haiku should go with line 48:

    #if defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__) || defined(__APPLE__)

Does Haiku use BSD KQUEUE for eventing or is it Linux inotify based?

**Comment by waddlesplash** [comment]
Neither. We have our own filesystem event notification system.

**Comment by jarun** [comment]
Ahh, I see. In that case I'll close the issue and wait for someone to implement and test the eventing on Haiku.

While it's easy to block eventing in `nnn`, it's a necessary feature in a FM so I think this is the best course of action for now.

Thanks a lot for your time!

**Comment by waddlesplash** [comment]
For reference, our node monitoring system API is documented here: https://www.haiku-os.org/docs/api/NodeMonitor_8h.html

**Comment by jarun** [comment]
Thanks for sharing! I took a look at it already but with my past experience with Linux inotify (it uses a variable length field and the manipulation is clumsy at best) I would leave it for someone who uses Haiku often and is more likely to find out defects in the implementation sooner.

For future reference, I would be glad to help with the way filesystem events are handled in `nnn`.

**Comment by scottmc** [comment]
@waddlesplash, think we should keep this open?  Might make for a good Google Code-In task.

**Comment by jarun** [comment]
I am re-opening the defect. Missed earlier that I have closed it. I made a fresh request in another forum today for someone to pitch in. Let's see.

**Comment by jarun** [comment]
We have raised a PR for `nnn` here: https://github.com/haikuports/haikuports/pull/4499.

Please review and if everything looks good, we can have `nnn` in Haiku.

**Comment by Begasus** [comment]
Looks OK, think we can merge soon, thanks!
