### ISSUE TITLE
otter-browser won't recompile with Qt5 GUI

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4102]
During compile configuration, otter-browser v1.0.01 complains that Qt5 GUI config is not finding mesa 17.1.10-4 develop headers mentioned within the config file. The mesa files are properly installed. **Everything was reinstalled and rechecked with pkgman full-sync on hrev53368 x86_64.**

NOTE: otter-browser package won't reinstall due to a older hunspell release dependency.

**Comment by Begasus** [comment]
Otter browser is one of the packages infected to the bump for hunspell, it needs a revbump for that (in progress)

**Comment by waddlesplash** [comment]
Appears otter rebuilt successfully.
