### ISSUE TITLE
mudlet: broken build

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#4115]
switched to hunspell 1.7, patch needed.
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/3355/builds/13874.log

**Comment by Begasus** [comment]
The far a got was getting the build started with an extra option to set the path to the hunspell library (cmake -D* can't check without booting into Haiku atm) cmake -L . should show the correct option to use, seems the headers are found ok (after looking into the Makefile created by cmake)

**Comment by korli** [comment]
new version fails to build:
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/3399/builds/13948.log

**Comment by korli** [comment]
fixed in 43c6283463d7e0563a6319149dd9288dfab24942
