### ISSUE TITLE
 bezilla 2.0.0.22-7 build issue on x86_64

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4156]
Ref: https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/1971/builds/11821.log
nsPKCS11Slot.cpp: In member function 'virtual nsresult nsPKCS11ModuleDB::GetInternal(nsIPKCS11Module**)':
**../../../../dist/public/nss/secmodt.h:341:71: error: unable to find string literal operator 'operator""fips' with 'const char [136]', 'long unsigned int' arguments**
"Flags=internal,critical"fips" slotparams=("#slot"={"SECMOD_SLOT_FLAGS"})

**Comment by diversys** [comment]
I couple years ago when we were still using gcc5 I tried to fix firefox build on x86_64. I found this bug which seemed connected to the compile errors I was having: https://bugzilla.mozilla.org/show_bug.cgi?id=315401. I reworked the patch from that ticket and it made it compile much further.
[bezilla2_x86_64.txt](https://github.com/haikuports/haikuports/files/3564738/bezilla2_x86_64.txt)

**Comment by extrowerk** [comment]
I dont think its a relevant bug, i see no point investing work fixing it.
