### ISSUE TITLE
Create an icon for Godot

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4157]
![godot-2 1 6_haiku](https://user-images.githubusercontent.com/5168719/64135952-d09f2f00-cda2-11e9-86b9-f6b8eb26a0ba.png)

Ref: https://depot.haiku-os.org/#!/?bcguid=bc1-LWPR&repos=haikuports&arch=x86_64&viewcrttyp=FEATURED&srchexpr=godot

Review the official Godot icon as a starting point.
![godot](https://user-images.githubusercontent.com/5168719/64120437-0c110d80-cd51-11e9-90d3-387e430468dd.png)

NOTE: Goal is to add a icon and screenshot to the Haiku Depot Server (HDS) for the Godot package.

**Comment by extrowerk** [comment]
@kenmays: you don't really have to post screenshots from other OSs, just use a Haiku screenshot.

**Comment by kenmays** [comment]
@extrowerk - Updated.

**Comment by extrowerk** [comment]
Nice!

**Comment by kenmays** [comment]
Complete. Can add screenshot and icon to HDS as time permits.
Official icon is within desktop app menu (good enough for now).
