### ISSUE TITLE
hunspell/myspell dicts add friulian

### ISSUE THREAD

**Issue by tmtfx** [haikuports/haikuports#4164]
is it possible to add friulian dictionary?
It's present in this repo on github:
https://github.com/wooorm/dictionaries

**Comment by tmtfx** [comment]
after looking at myspell recipe, I think a new recipe should be done...

**Comment by Begasus** [comment]
You can leave this open untill it's added, one could add this to the myspell recipe, just need the correct dic/aff filename (looking at the link you posted it's using "index.dic")

**Comment by tmtfx** [comment]
ok, thank you

**Comment by Begasus** [comment]
According to wiki https://wiki.documentfoundation.org/Language_support_of_LibreOffice the official place to look would be https://digilander.libero.it/paganf/coretors/dizionaris.html (the download there contains the correct filenames in the archives eg. fur-it.dic/aff) (outdated)
Adding this in the myspell recipe would be a start I guess :)

**Comment by Begasus** [comment]
Think this could work :)
![Furlan-It](https://user-images.githubusercontent.com/16057090/64476727-02ddd180-d193-11e9-8648-818585c3947a.png)

**Comment by Begasus** [comment]
Added in https://github.com/haikuports/haikuports/pull/4165 should be up after the buildbot picks it up :)
