### ISSUE TITLE
gcc: disable -gcolumn-info

### ISSUE THREAD

**Issue by KapiX** [haikuports/haikuports#4174]
https://dev.haiku-os.org/ticket/15159

I didn't create an issue here because I didn't realize the impact of this change. Not only makefile_engine is affected; any app built from Haiku source tree cannot be debugged without doing manual workarounds.

DWARF column info should be disabled globally in GCC until support in Debugger is implemented.

**Comment by waddlesplash** [comment]
I don't think that's right. Debugger can just be tweaked to discard the column information for now; that should be a 2-3 line change, yeah?

**Comment by KapiX** [comment]
In the ticket Rene pointed out why that's not so simple. Please discuss further with him because I'm not knowledgeable in this topic.

**Comment by KapiX** [comment]
Worked around in Debugger.
