### ISSUE TITLE
PyQt: Use system installed Qt libraries

### ISSUE THREAD

**Issue by phw** [haikuports/haikuports#4184]
I just now noticed that the HaikuPorts version of PyQt bundles its own Qt5 library. Would it make more sense to depend on the Qt5 package and reuse the libraries there?

**Comment by waddlesplash** [comment]
Where do you see that? The recipe clearly depends on the main qt5 libraries: https://github.com/haikuports/haikuports/blob/master/dev-python/pyqt/pyqt-5.12.1.recipe

**Comment by phw** [comment]
Yes, indeed, so the intention was to use the libraries from the qt5 packages. But the pyqt_python3 package include a copy of the Qt libraries in `lib/python3.6/vendor-packages/PyQt5`. And if you look at the versions from inside a Python script it shows that the bundled libraries are used (and that it is Qt 5.12.2 currently):

```python
from PyQt5.QtCore import PYQT_VERSION_STR, QT_VERSION_STR
print("PyQt: %s" % PYQT_VERSION_STR)
print("PyQt: %s" % QT_VERSION_STR)
```

Output:

```
PyQt: 5.12.1
Qt: 5.12.2
```

The current recipe overwhelms me a bit. Might make sense to start anew based on an existing cleaner Python package recipe which already builds a pip package for all Python versions.

**Comment by phw** [comment]
Sorry, I was mistaken. The check for `QT_VERSION_STR` is wrong, this only returns the version PyQt was build against. Proper way would be to use `PyQt5.QtCore.qVersion()`, and that returns "5.13.1", so the system libraries are used.
