### ISSUE TITLE
PyQt: Support Python 3.7

### ISSUE THREAD

**Issue by phw** [haikuports/haikuports#4185]
Update the PyQt package to support Python 3.7.

I tried to look at this, but found the PyQt package to be a bit messy and very different from other Python packages (which build for all Python 2, 3.6 and 3.7).

**Comment by phw** [comment]
https://github.com/haikuports/haikuports/pull/4233

**Comment by korli** [comment]
14f0302c02ef58599aac94c5b351fe306df3902b
