### ISSUE TITLE
hunspell doesn't find default dictionary

### ISSUE THREAD

**Issue by tmtfx** [haikuports/haikuports#4195]
My system is set as Friulian (fur_IT) but I think that this error happens in every localization; Executing hunspell from commandline it says:

Can't open affix or dictionary files for dictionary named "fur_IT"

launching hunspell -D shows these paths:

SEARCH PATH:
.::/usr/share/hunspell:/usr/share/myspell:/usr/share/myspell/dicts:/Library/Spelling:/boot/home/.openoffice.org/3/user/wordbook:/boot/home/.openoffice.org2/user/wordbook:/boot/home/.openoffice.org2.0/user/wordbook:/boot/home/Library/Spelling:/opt/openoffice.org/basis3.0/share/dict/ooo:/usr/lib/openoffice.org/basis3.0/share/dict/ooo:/opt/openoffice.org2.4/share/dict/ooo:/usr/lib/openoffice.org2.4/share/dict/ooo:/opt/openoffice.org2.3/share/dict/ooo:/usr/lib/openoffice.org2.3/share/dict/ooo:/opt/openoffice.org2.2/share/dict/ooo:/usr/lib/openoffice.org2.2/share/dict/ooo:/opt/openoffice.org2.1/share/dict/ooo:/usr/lib/openoffice.org2.1/share/dict/ooo:/opt/openoffice.org2.0/share/dict/ooo:/usr/lib/openoffice.org2.0/share/dict/ooo

there is no /boot/system/data/hunspell
so it will never find the default dictionary

**Comment by Begasus** [comment]
AFAIK Haiku doesn't use the hunspell dictionaries, they are used by the applications using myspell/hunspell dictionaries, I could have a look into the hunspell recipe (source) to see if I can add the path, maybe @humdingerb could step in for this? (explaining the Haiku translation system)

**Comment by humdingerb** [comment]
@tmtfx , just to be clear, you don't mean that there's something wrong with Haiku's localization system in general, but the hunspell package is slightly wrong and doesn't find its deauilt dictionary (not fur_IT specific), right?

**Comment by tmtfx** [comment]
@humdingerb, yes it's what I meant. the problem is hunspell, as I wrote, it is not looking at /system/data/hunspell directory. If I thought that it was a Haiku problem I would have opened a ticket on its bug trac on dev.haiku-os.org . Sorry for the misunderstanding

**Comment by Begasus** [comment]
There is a simple fix to add /system/data/hunspell to the source, but @alaviss said he would be looking for a proper fix that would be better :)

**Comment by Begasus** [comment]
Quick fix in https://github.com/haikuports/haikuports/pull/9015 (untill there is a proper(?) fix)
