### ISSUE TITLE
openvdb: build failed on x86_gcc2

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#4197]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/3294/builds/33227.log

**Comment by korli** [comment]
The paths for tbb are not correct ( https://github.com/haikuports/haikuports/blob/236a34f2374ccf1633b3919bfd41848d44b2d1e7/media-gfx/openvdb/openvdb-6.1.0.recipe#L85 )
but the build fails by linking (missing references).

**Comment by Begasus** [comment]
This could be bumped to the latest version when checking this

**Comment by korli** [comment]
fixed in 6e175c7eefe5784f638bdce3d35820e02dabba5c and 068886411daaaa2caaf316151aefabc94a646803
