### ISSUE TITLE
openimageio: build broken on x86_64

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#4198]
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/3463/builds/14052.log

**Comment by extrowerk** [comment]
I have an updated recipe, will push it afternoon.

**Comment by korli** [comment]
you mean https://github.com/haikuports/haikuports/pull/2449 ?

**Comment by extrowerk** [comment]
Yep, sorry.
