### ISSUE TITLE
InetAddressImplFactory_isIPv6Supported+0xb2c

### ISSUE THREAD

**Issue by cbm64chris** [haikuports/haikuports#4212]
Haiku Revision hrev52295+129 on an old AMD Turion 64
OpenJDK 11.0.4+11

I have built NetBeans 11.0 from source but I cannot get it to run - I get a SIGSEV on libnet.so+0x71ec Java_java_net_InetAddressImplFactory_isIPv6Supported.

**Comment by allewell** [comment]
For what it's worth, I also receive this error when attempting to start Jira Server v8.5.7 on Haiku Beta2 hrev54154+111 x86_64 (first i tested)

This is on JDK8, too. So it's a problem across JDK8/JDK11

 `#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000031e68958c, pid=1602, tid=0x000010d2db031460
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode haiku-amd64 compressed oops)
# Problematic frame:
# C  [libnet.so+0x758c]  Java_java_net_InetAddressImplFactory_isIPv6Supported+0xb1c
#`

**Comment by allewell** [comment]
For what it's worth, I also receive this error when attempting to start Jira Server v8.5.7 on Haiku Beta2 hrev54154+111 x86_64 (first i tested)

This is on JDK8, too. So it's a problem across JDK8/JDK11

 `#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000031e68958c, pid=1602, tid=0x000010d2db031460
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode haiku-amd64 compressed oops)
# Problematic frame:
# C  [libnet.so+0x758c]  Java_java_net_InetAddressImplFactory_isIPv6Supported+0xb1c
#`

**Comment by allewell** [comment]
For what it's worth, I also receive this error when attempting to start Jira Server v8.5.7 on Haiku Beta2 hrev54154+111 x86_64 (first i tested)

This is on JDK8, too. So it's a problem across JDK8/JDK11

 `#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000031e68958c, pid=1602, tid=0x000010d2db031460
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode haiku-amd64 compressed oops)
# Problematic frame:
# C  [libnet.so+0x758c]  Java_java_net_InetAddressImplFactory_isIPv6Supported+0xb1c
#`

**Comment by allewell** [comment]
For what it's worth, I also receive this error when attempting to start Jira Server v8.5.7 on Haiku Beta2 hrev54154+111 x86_64 (first i tested)

This is on JDK8, too. So it's a problem across JDK8/JDK11

 `#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000031e68958c, pid=1602, tid=0x000010d2db031460
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode haiku-amd64 compressed oops)
# Problematic frame:
# C  [libnet.so+0x758c]  Java_java_net_InetAddressImplFactory_isIPv6Supported+0xb1c
#`

**Comment by allewell** [comment]
For what it's worth, I also receive this error when attempting to start Jira Server v8.5.7 on Haiku Beta2 hrev54154+111 x86_64 (first i tested)

This is on JDK8, too. So it's a problem across JDK8/JDK11

 `#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000031e68958c, pid=1602, tid=0x000010d2db031460
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode haiku-amd64 compressed oops)
# Problematic frame:
# C  [libnet.so+0x758c]  Java_java_net_InetAddressImplFactory_isIPv6Supported+0xb1c
#`

**Comment by allewell** [comment]
For what it's worth, I also receive this error when attempting to start Jira Server v8.5.7 on Haiku Beta2 hrev54154+111 x86_64 (first i tested)

This is on JDK8, too. So it's a problem across JDK8/JDK11

 `#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000031e68958c, pid=1602, tid=0x000010d2db031460
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode haiku-amd64 compressed oops)
# Problematic frame:
# C  [libnet.so+0x758c]  Java_java_net_InetAddressImplFactory_isIPv6Supported+0xb1c
#`

**Comment by allewell** [comment]
For what it's worth, I also receive this error when attempting to start Jira Server v8.5.7 on Haiku Beta2 hrev54154+111 x86_64 (first i tested)

This is on JDK8, too. So it's a problem across JDK8/JDK11

 `#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000031e68958c, pid=1602, tid=0x000010d2db031460
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode haiku-amd64 compressed oops)
# Problematic frame:
# C  [libnet.so+0x758c]  Java_java_net_InetAddressImplFactory_isIPv6Supported+0xb1c
#`

**Comment by allewell** [comment]
For what it's worth, I also receive this error when attempting to start Jira Server v8.5.7 on Haiku Beta2 hrev54154+111 x86_64 (first i tested)

This is on JDK8, too. So it's a problem across JDK8/JDK11

 `#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000031e68958c, pid=1602, tid=0x000010d2db031460
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode haiku-amd64 compressed oops)
# Problematic frame:
# C  [libnet.so+0x758c]  Java_java_net_InetAddressImplFactory_isIPv6Supported+0xb1c
#`

**Comment by allewell** [comment]
For what it's worth, I also receive this error when attempting to start Jira Server v8.5.7 on Haiku Beta2 hrev54154+111 x86_64 (first i tested)

This is on JDK8, too. So it's a problem across JDK8/JDK11

 `#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000031e68958c, pid=1602, tid=0x000010d2db031460
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode haiku-amd64 compressed oops)
# Problematic frame:
# C  [libnet.so+0x758c]  Java_java_net_InetAddressImplFactory_isIPv6Supported+0xb1c
#`

**Comment by korli** [comment]
Should be fixed in openjdk11-11.0.6.9-3 and openjdk8-1.8.u242_b8-3
It's difficult to identify because the compiler puts code for multiple functions together after the symbol Java_java_net_InetAddressImplFactory_isIPv6Supported
This should be triggered whenever a network interface has no IPv6 address.
