### ISSUE TITLE
Wonderbrush: Save Canvas feature crashes on x86_64

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4265]
Wonderbrush 2.1.2-8 crashes during use of 'Save Canvas' feature on Haiku R1B1 x86_64 and
won't let you keep changing storage volumes. Select 'Save As', then Format button. Also, change storage volumes 2-5 times to see if it "sticks".
![wonderbrush](https://user-images.githubusercontent.com/5168719/66150240-93a8a100-e5c9-11e9-87ca-8accc6835cec.png)
[WonderBrush-686-debug-03-10-2019-17-22-36.txt](https://github.com/haikuports/haikuports/files/3687355/WonderBrush-686-debug-03-10-2019-17-22-36.txt)

**Comment by humdingerb** [comment]
Bugs in WonderBrush should be reported at [its issue tracker](https://github.com/stippi/WonderBrush-v2).
Make sure it's still an issue with the latest nightly. I cannot reproduce with a 32bit nightly.
