### ISSUE TITLE
Rust FFI does not work on x86 secondary arch

### ISSUE THREAD

**Issue by Crestwave** [haikuports/haikuports#4269]
This is used by the Termios crate, which is used by sys-apps/bat.

@waddlesplash suspects it's because it tries to use the x86_gcc2 libs. CC @nielx

**Comment by Crestwave** [comment]
I simply clone it and run `cargo-x86 test`

**Comment by nielx** [comment]
I just tried. First of all, I used `setarch x86`, so it was unlikely I was linking to anything gcc2. 

I am getting undefined references to `cfsetspeed` and `tcgetsid`. These are actually not defined in [termios.h](https://github.com/haiku/haiku/blob/master/headers/posix/termios.h).

Your remedies are altering the patch so that these functions are not available on Haiku (with the risk that bat is using them), or adding them to Haiku.

**Comment by Crestwave** [comment]
> I just tried. First of all, I used `setarch x86`, so it was unlikely I was linking to anything gcc2.

Yes, I tried that and suspected it meant that but wasn't sure. Not to mention that I built it in the HaikuPorter chroot, so I'm not sure if any gcc2 libs were even available. But I figured waddlesplash knew something I didn't.

> I am getting undefined references to `cfsetspeed` and `tcgetsid`. These are actually not defined in [termios.h](https://github.com/haiku/haiku/blob/master/headers/posix/termios.h).

Yes, I know. It's the same on x86_64; however, when I build it on x86, I get undefined references to *all* the FFI functions, including `cfsetispeed`, `cfsetospeed`, etc. Did you not get these errors?

> Your remedies are altering the patch so that these functions are not available on Haiku (with the risk that bat is using them), or adding them to Haiku.

`bat` doesn't use them as far as I'm aware of. But because of that, it builds fine without patching them out and passes all of its tests, so it doesn't seem relevant for now. An upstream patch would be great, but unfortunately the maintainer seems inactive and hasn't even merged the original patch.

**Comment by nielx** [comment]
> I am getting undefined references to cfsetspeed and tcgetsid. These are actually not defined in termios.h.
> 
> Yes, I know. It's the same on x86_64; however, when I build it on x86, I get undefined references to all the FFI functions, including cfsetispeed, cfsetospeed, etc. Did you not get these errors?

No, I did not actually. I did do `setarch x86` before running `cargo` (not cargo-x86).

**Comment by Crestwave** [comment]
But I already tried that... strange. Are you able to build `bat`?

**Comment by Crestwave** [comment]
My bad; it does not complain about the other functions beinng undefined, it just fails their tests. I patched out references `cfsetspeed` and `tcgetsid`, and they succeeded. I'm not sure why it causes everything to fail here and not on x86_64, though.

**Comment by nielx** [comment]
Thanks for trying out rust-based tools, it helps finding the gaps in the Rust implementation on Haiku.
