### ISSUE TITLE
Update python modules

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#4284]
- [x] aiodns-2.0.0 (#4223 )
- [x] alembic-1.2.1
- [x] asn1crypto-1.2.0
- [x] beautifulsoup-4.8.0
- [x] cryptography-2.8
- [x] cryptography-vectors-2.7
- [x] cython-0.29.13
- [x] dulwich-0.19.13
- [x] ecdsa-0.13.3
- [x] gitpython-3.0.3
- [x] html2text-2019.9.26
- [x] html5-parser-0.4.8
- [x] jinja-2.10.3
- [x] mako-1.1.0
- [x] markups-3.0.0
- [x] mechanize-0.4.3
- [x] mock-3.0.5
- [x] numpy-1.17.2
- [x] paramiko-2.6.0  => cryptography
- [x] pbr-5.4.3
- [ ] pillow-6.2.1
- [x] pluggy-0.13.0  => setuptools-scm
- [x] py-1.8.0  => setuptools-scm
- [x] pyaes-1.6.1
- [x] pyasn1-0.4.7
- [x] pyasn1-modules-0.2.6
- [x] pycares-3.0.0
- [x] pycurl-7.43.0.3
- [ ] pydispatcher-2.0.5
- [ ] pyenet-1.3.13.
- [ ] pygame-1.9.6
- [x] pylzma-0.5.0
- [ ] pyopengl-3.1.0
- [ ] pyopenssl-19.0.0
- [ ] pyserial-3.4
- [x] pytest-5.2.1  => setuptools-scm
- [x] pytz-2019.3
- [x] rdflib-4.2.2
- [x] requests-futures-1.0.0
- [x] setuptools-41.4.0
- [x] simpleparse-2.2.0
- [ ] sip-5.0.0
- [x] slixmpp-1.4.2
- [x] sqlalchemy-1.3.9
- [x] twisted-19.7.0
- [x] tzlocal-2.0.0
- [x] voluptuous-0.11.7
- [x] waitress-1.3.1
- [x] watchdog-0.9.0
- [x] zope-interface-4.6.0

**Comment by Begasus** [comment]
Raising a voice here, there are recipes using python 2.7 still, these should be cleaned, others only provide packages for python 3.6 or 3.7 (didn't check if 3.8 is used atm), maybe we should set them all to use at least 3.6 and 3.7

**Comment by Begasus** [comment]
Working on some recipes and dropping python 2.7 where it can be done:
- [x] pytest-6.1.1
    - [x] importlib_metadata-2.0.0
        - [x] zipp-3.3.2 (new recipe)
            - [x] setuptools-42.0.0 (merged)
    - [x] more_itertools-8.5.0
    - [x] attrs-20.2.0
    - [x] pluggy-0.13.1
        - [x] six-1.15.0-2 (revbump)
    - [x] atomicwrites-1.4.0
    - [x] packaging-20.4
    - [x] py-1.9.0
    - [x] toml-0.10.1 (new recipe)
    - [x] iniconfig-1.1.1 (new recipe)
    - [x] pyparsing-2.4.7 (new recipe)

**Comment by Begasus** [comment]
Should this still be active? python modules change so fast that it's hard to keep track ;)

**Comment by korli** [comment]
Sure. This should automated probably.
