### ISSUE TITLE
mesa: fix build issue

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4285]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/3385/builds/33388.log

Add to BUILD() before reconfigure: 
`
export LDFLAGS="-lstdc++"
`
This wasn't needed beforehand. Possibly due to GCC updates.

**Comment by extrowerk** [comment]
It is a possible workaround, but it would be much nicer to change the build system to use g++ instead of gcc.
