### ISSUE TITLE
gcc-2.95.3_2017_07_20-2: ld cannot find -lstdc++

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4286]
/packages/gcc-2.95.3_2017_07_20-2/.self/develop/tools/i586-pc-haiku/bin/ld: cannot find -lstdc++

**Comment by pulkomandy** [comment]
The lib is named libstdc++.r4 and we can't change that for compatibility with BeOS.
Use g++ instead of using gcc or ld directly, it will link it automatically.
