### ISSUE TITLE
libreoffice: fix orcus pkg dependency

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4325]
libreoffice_x86-6.3.0.4-4-x86_gcc2.hpkg

Requests:
lib:liborcus_0.14$secondaryArchSuffix

Provided:
orcus_x86-0.15.2-3-x86_gcc2.hpkg

**Comment by korli** [comment]
libreoffice-6.3.0.4-4:
	requires "lib:liborcus_0.14" of package "libreoffice-6.3.0.4" could not be resolved
