### ISSUE TITLE
add game frogatto

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#433]
goes in games-arcade/frogatto

Frogatto & Friends is an old-school 2D platformer game, starring a certain quixotic frog. Give it a try!
It's a big adventure with all the classic fun - you fight monsters, collect coins, talk to people, and buy new stuff.
 http://www.frogatto.com/

old .bep and /patch attached
[frogtatto.zip](https://github.com/haikuports/haikuports/files/105643/frogtatto.zip)
![frogatto-screenshot1](https://cloud.githubusercontent.com/assets/1039279/12594475/24980bf2-c42b-11e5-881c-75bdfe65a957.png)

**Comment by Begasus** [comment]
Done in https://github.com/haikuports/haikuports/pull/9645
Could probably use some finetuning (saves prefs etc in .frogatto in home dir), launching needs to be done from Terminal (checked some things there but couldn't get that to work properly).
