### ISSUE TITLE
add Python distutils-exta

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#434]
Enables you to easily integrate gettext support, themed icons and scrollkeeper based documentation into Python's distutils.
Dependecy of Unkown Horizons

[distutils-2.28.bep.txt](https://github.com/haikuports/haikuports/files/105647/distutils-2.28.bep.txt)

**Comment by Begasus** [comment]
Added in: https://github.com/haikuports/haikuports/pull/7007
