### ISSUE TITLE
[Wishlist] Tesseract FPS

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4341]
Tesseract FPS - http://tesseract.gg/

The Game
Tesseract is a first-person shooter game focused on instant deathmatch and capture-the-flag gameplay as well as cooperative in-game map editing.

Platform
The Tesseract renderer ideally targets OpenGL 3.0 or greater, using only Core profile functionality and extensions, as its graphics API and using SDL 2.0 as a cross-platform OS abstraction layer. However, it also functions on OpenGL 2.1 where extensions are available to emulate Core profile functionality. Mobile GPUs with OpenGL ES are, at the moment, not targeted. GLSL compatibility is provided across various incompatible versions using a small preprocessor-based prelude of macros abstracting texture access and attribute/interpolant/output specification that would otherwise be incompatible across GLSL versions.

The Tech
Tesseract provides a unique open-source engine derived from Cube 2: Sauerbraten technology but with upgraded modern rendering techniques. The new rendering features include fully dynamic omnidirectional shadows, global illumination, HDR lighting, deferred shading, morphological/temporal/multisample anti-aliasing, and much more.

It provides a bunch of new rendering features such as:

deferred shading
omnidirectional point lights using cubemap shadowmaps
perspective projection spotlight shadowmaps
orthographic projection sunlight using cascaded shadowmaps
HDR rendering with tonemapping and bloom
real-time diffuse global illumination for sunlight (radiance hints)
screen-space ambient occlusion
screen-space reflections and refractions for water and glass (use as many water planes as you want now!)
screen-space refractive alpha cubes
deferred MSAA, subpixel morphological anti-aliasing (SMAA 1x, T2x, S2x, and 4x), FXAA, and temporal AA
runs on both OpenGL Core (3.0+) and legacy (2.1+) contexts

NOTE: This will support the **Red Eclipse** (https://www.redeclipse.net/) project.

**Comment by extrowerk** [comment]
I got Sauerbraten running on Haiku in last year or so, i think it is possible to get the current version working. Let's see if i find time to check my backups.

**Comment by extrowerk** [comment]
![zgY0](https://user-images.githubusercontent.com/5569059/68327447-aa14b180-00cd-11ea-9cd0-019385b01f40.png)

So it was an easy ride.

**Comment by extrowerk** [comment]
FYI: i have no interest to write a recipe for this.

**Comment by kenmays** [comment]
Good enough.

**Comment by kenmays** [comment]
Compiled Tesseract 2014.05.12 fine on Haiku R1B2 x86. Made a recipe,  
There is Rev 2429 at this time as well. Closing.
