### ISSUE TITLE
[Wishlist] Tesseract FPS

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4342]
The Game
Tesseract is a first-person shooter game focused on instant deathmatch and capture-the-flag gameplay as well as cooperative in-game map editing.

The Tech
Tesseract provides a unique open-source engine derived from Cube 2: Sauerbraten technology but with upgraded modern rendering techniques. The new rendering features include fully dynamic omnidirectional shadows, global illumination, HDR lighting, deferred shading, morphological/temporal/multisample anti-aliasing, and much more. 

It provides a bunch of new rendering features such as:
* deferred shading
* omnidirectional point lights using cubemap shadowmaps
* perspective projection spotlight shadowmaps
* orthographic projection sunlight using cascaded shadowmaps
* HDR rendering with tonemapping and bloom
* real-time diffuse global illumination for sunlight (radiance hints)
* screen-space ambient occlusion
* screen-space reflections and refractions for water and glass (use as many water planes as you want now!)
* screen-space refractive alpha cubes
* deferred MSAA, subpixel morphological anti-aliasing (SMAA 1x, T2x, S2x, and 4x), FXAA, and temporal AA
* runs on both OpenGL Core (3.0+) and legacy (2.1+) contexts

See: http://tesseract.gg/

**Comment by korli** [comment]
merged in #4341

**Comment by kenmays** [comment]
NOTE: Tesseract >= Cube 2. Both backend renderers for **Red Eclipse** (https://www.redeclipse.net/) project.
