### ISSUE TITLE
blender: bump LLVM dependency

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4343]
Depends on LLVM8... should use LLVM9.

Tested with Blender 2.80 w/LLVM9.

**Comment by extrowerk** [comment]
And what are your experiences with 2.8?

**Comment by korli** [comment]
blender wouldn't be rebuilt because of openimageio build failure (tracked in #4198).
https://build.haiku-os.org/buildmaster/master/x86_64/?buildrunDir=3463&viewMode=expanded

**Comment by kenmays** [comment]
Fixed.
