### ISSUE TITLE
blender: fix libopenvdb dependency

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4346]
Nothing provides libopenvdb>=5.2.0 (openvdb-6.1.0-4 exists)

**Comment by korli** [comment]
blender wouldn't be rebuilt because of openimageio build failure (tracked in #4198).
https://build.haiku-os.org/buildmaster/master/x86_64/?buildrunDir=3463&viewMode=expanded

**Comment by kenmays** [comment]
Fixed.
