### ISSUE TITLE
clementine: audio cd buffering and KDL

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4348]
Erratic buffering issues during audio CD loading and playback. Adding audio WAV files to playlist from CD may cause a KDL in some cases.

Version: 1.3.1-git~4
Haiku hrev52295+129 x86_64

![clementine_cocobean](https://user-images.githubusercontent.com/5168719/68267596-cfd78300-0007-11ea-964a-49d40d849c27.jpg)

**Comment by korli** [comment]
Why isn't this a ticket at Haiku Bugtracker?

**Comment by kenmays** [comment]
Clementine is Haikuports-maintained so I was told we track those issues through Haikuports (or the related third-party github trackers (like HaikuArchives, ArtPaint or WonderBrush).

**Comment by diversys** [comment]
No userland app should end up in KDL. If this is the case there is certainly a bug in Haiku itself and not in a port.

**Comment by kenmays** [comment]
See: https://dev.haiku-os.org/ticket/15472
