### ISSUE TITLE
add wings, erlang-R13B04, makeself, and esdl

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#435]
From old site, .bep files for wings and some dependencies
[attachments-ticket-436.zip](https://github.com/haikuports/haikuports/files/105656/attachments-ticket-436.zip)

**Comment by waddlesplash** [comment]
All of those are in the tree except makeself

**Comment by waddlesplash** [comment]
Makeself appears to be a single-file .sh script for creating self-extractors, which we don't exactly need as a recipe. Closing as fixed.
