### ISSUE TITLE
[Wishlist] SuperTuxKart

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4351]
SuperTuxKart is a 3D open-source arcade racer with a variety characters, tracks, and modes to play. Our aim is to create a game that is more fun than realistic, and provide an enjoyable experience for all ages.

In Story mode, you must face the evil Nolok, and defeat him in order to make the Mascot Kingdom safe once again! You can race by yourself against the computer, compete in several Grand Prix cups, or try to beat your fastest time in Time Trial mode. You can also race or battle with up to eight friends on a single computer, play on a local network or play online with other players all over the world. 

Website: https://supertuxkart.net
GitHub: https://github.com/supertuxkart/stk-code

**Comment by scottmc** [comment]
As a first step on this one, you might try building it manually in terminal and put together a list of the dependencies first.   If we don't already have working recipes for all of those, post the list here of the ones we need to get working recipes for prior to jumping to the full recipe for SuperTuxKart.  Breaking this up, we can turn the dependency recipes into GCI tasks.

**Comment by kenmays** [comment]
Basic list:
> aalib-1.4.r5_13, ca_root_nss-3.47, cmake-3.15.5,
> curl-7.66.0, enet-1.3.14,1, expat-2.2.8, freetype2-2.10.1, fribidi-0.19.7,
> gettext-0.20.1_1, glew-2.1.0, gmp-6.1.2_1,
> indexinfo-0.3.1, jpeg-turbo-2.0.3, jsoncpp-1.8.1_7, libGLU-9.0.1,
> libICE-1.0.10,1, libSM-1.2.3,1, libarchive-3.4.0,1, libepoll-shim-0.0.20190311,
> libffi-3.2.1_3, liblz4-1.9.2,1, libnghttp2-1.39.2,
> libogg-1.3.4,4, libpciaccess-0.16, libpthread-stubs-0.4, libtextstyle-0.20.1,
> libunwind-20170615, libuv-1.33.1, libvorbis-1.3.6,3, libxcb-1.13.1,
> libxkbcommon-0.8.4, libxml2-2.9.9, libxshmfence-1.3, lzo2-2.10_1, 
> mesa-libs-17.1.10, nettle-3.5.1_1, ninja-1.9.0,2, openal-soft-1.19.1_3,
> pciids-20191012, png-1.6.37, python36-3.6.9, readline-8.0.0,
> rhash-1.3.5, sdl-1.2.15_14,2

**Comment by korli** [comment]
nothing required missing from https://github.com/supertuxkart/stk-code/blob/master/CMakeLists.txt and https://github.com/supertuxkart/stk-code/blob/master/Brewfile

**Comment by kenmays** [comment]
@alwayslivid - has built a recipe. WIP (in testing).

**Comment by kenmays** [comment]
![supertuxkart](https://user-images.githubusercontent.com/5168719/71636461-75ad0580-2be5-11ea-9a6e-08f94119a7b1.png)
@alwayslivid - Built the recipe. I did some patchwork yesterday and it compile 100%. Minor recipe cleanup and debugging. Looks good otherwise.

**Comment by alwayslivid** [comment]
> 
> 
> ![supertuxkart](https://user-images.githubusercontent.com/5168719/71636461-75ad0580-2be5-11ea-9a6e-08f94119a7b1.png)
> @alwayslivid - Built the recipe. I did some patchwork yesterday and it compile 100%. Minor recipe cleanup and debugging. Looks good otherwise.

I missed the notifications, how did you manage to get around the shared memory implementation?

Did you also use my recipe for it?

**Comment by kenmays** [comment]
Yes, I used your recipe and made minor mods to build the package install. I have a SuperTuxKart 1.0 test package for Haiku. I'll work on the SuperTuxKart 1.1 in the future with the STK devs. For clarity, I have to finish reviewing the client release component further with the STK devs on Haiku as I mainly fixed (i.e. patched) the server release build component on Haiku. Any POSIX shm stuff I'd bypassed as you know this is not implemented 'yet' on Haiku. Thanks for your help. 

We are done for now. I'll upstream my patches as my time permits.

**Comment by alwayslivid** [comment]
> Yes, I used your recipe and made minor mods to build the package install. I have a SuperTuxKart 1.0 test package for Haiku. I'll work on the SuperTuxKart 1.1 in the future with the STK devs. For clarity, I have to finish reviewing the client release component further with the STK devs on Haiku as I mainly fixed (i.e. patched) the server release build component on Haiku. Any POSIX shm stuff I'd bypassed as you know this is not implemented 'yet' on Haiku. Thanks for your help.
> 
> We are done for now. I'll upstream my patches as my time permits.

That's great! If you could also credit me for that, that would be appreciated.

I did look into it since the last reply and I realized that `shm` since SuperTuxKart is only really used by the Wayland source files, then it's possible to avoid using `shm` altogether by removing the Wayland functionality that's unnecessary on the Haiku operating system.

CC: @Benau
