### ISSUE TITLE
numpy: missing header file

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4353]
numpy-1.17.3 x86_64

Missing header include: **numpy/ndarrayobject.h**

Used in Blender 2.80 - extern/audaspace/bindings/python/PySound.cpp

NOTE: Need to fix for numpy Python 3.7 build.

**Comment by korli** [comment]
well, header is present in numpy package.

**Comment by kenmays** [comment]
Verified for numpy_python3-1.17.3-3-x86_64.
