### ISSUE TITLE
tbb: incorrect sonames

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4354]
tbb-2018.5-2

runtime_loader: Cannot open file libtbbmalloc.so: No such file...

Tested: Blender 2.80-1 on Haiku R1B1 x86_64

**Comment by korli** [comment]
well it should search for libtbbmalloc.so.2

**Comment by korli** [comment]
tbb builds its libs so:
gcc -fPIC -o libtbbmalloc.so.2 backend.o large_objects.o backref.o  tbbmalloc.o  itt_notify_malloc.o frontend.o   -lpthread -shared -m64

You can try to modify the haiku patch: https://github.com/haikuports/haikuports/blob/master/dev-cpp/tbb/patches/tbb-2018.5.patchset#L528

**Comment by kenmays** [comment]
@korli - Ok.

**Comment by korli** [comment]
Please try again with tbb-2018.5-3

**Comment by kenmays** [comment]
Added. 
No change.

**Comment by korli** [comment]
you have to rebuild against tbb-2018.5-3

**Comment by kenmays** [comment]
Ok. I created a symlink in non-packaged for a workaround and that worked. Will do a rebuild.

**Comment by kenmays** [comment]
No *.so in /system/lib with -3.

**Comment by korli** [comment]
There should be no *.so in /system/lib.

**Comment by kenmays** [comment]
Fixed. Build works.
