### ISSUE TITLE
jpeg: unit test failure

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4355]
jpeg-9c-2 x86_64:
make check reports: Unsupported output file format for:
**djpeg -dct int -ppm -outfile testout.ppm ./testorig.jpg**

**Comment by kenmays** [comment]
Tested PR #4369 with GCC2 and GCC8. Passed 100%.

**Comment by Begasus** [comment]
What's the point of opening a PR/closing it/reopen it? libjpeg is a widely used library in Haiku, one should be very careful to update it ...

**Comment by kenmays** [comment]
Bump revision and rebuild with updated recipe. Not changing the source version.
Close ticket when merged - if approved, I already tested it.

**Comment by Begasus** [comment]
Need to check (probably tomorrow, busy with something else atm), did you actually installed it to see if it doesn't break anything?

**Comment by kenmays** [comment]
Needs core dev review. This mainly fixed the unit testing issue.

**Comment by Begasus** [comment]
OK, I'll leave that up to the main devs :)

**Comment by kenmays** [comment]
@begasus - Actually, this is just a revision bump - not a version bump. So, no breakage in backward compat. I just retested it and all unit tests passed again. So, we can close it safely now. ;)
