### ISSUE TITLE
git: install issue

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4357]
git-2.24.0-1-x86_gcc2
Requires man>=1.14.3
man 1.6g-6 pkg exists.

**Comment by Begasus** [comment]
Confirmed, pkgman full-sync tells me the same

**Comment by korli** [comment]
Could you try to install mandoc and uninstall man?

**Comment by kenmays** [comment]
1. Installed mandoc 1.14.3 and uninstalled man.
Result: fixed

**Comment by korli** [comment]
We might as well remove man (which isn't maintained anymore). Does mandoc work as expected?

**Comment by kenmays** [comment]
Seems fine for now.
