### ISSUE TITLE
Koder: fails to start

### ISSUE THREAD

**Issue by Oreo639** [haikuports/haikuports#4358]
After the update to yaml_cpp koder fails to find libyaml-cpp.so.0.6 and it seems that while yaml_cpp_devel contains a static lib, there is no dynamic library in yaml_cpp. I doubt that is intended.

**Comment by korli** [comment]
Should be fixed with 0ce6930eda188118a16f78cf20216f549f11ccc9  and yaml_cpp-0.6.3-2
Thanks for the report!

**Comment by kenmays** [comment]
@korli - Tested with new yaml. Bump koder.
