### ISSUE TITLE
osl: broken build on x86_64

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4363]
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/3736/builds/14515.log

runtime_loader: Cannot open file libjpeg.so.62: No such file or directory

**Comment by korli** [comment]
I'm not able to find out which lib depends on libjpeg.so.62

**Comment by korli** [comment]
https://github.com/haikuports/haikuports/commit/930af096daf6bf5b3d73c5efb91378d7c6ab27f5#commitcomment-35862454

**Comment by Begasus** [comment]
I think it comes from jpeg-turbo ... libjpegVersion="62.2.0"

**Comment by korli** [comment]
yeah but which library looks for libjpeg from jpeg-turbo?

**Comment by Begasus** [comment]
Only lib is see using libjpeg (from osl dependencies) is openimageio?

**Comment by Begasus** [comment]
When trying to remove jpeg_turbo from the system I got some deppendencies that wanted to uninstall, not sure any are (directly) related: https://ibb.co/L1vJWCT

**Comment by Begasus** [comment]
seems to be fixed, build is running through now, thanks to @korli :+1:

**Comment by kenmays** [comment]
Build fixed: osl-1.10.7-2-x86_64.hpkg

https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/3745/builds/14524.log
