### ISSUE TITLE
blender: openimageio-2.x breaks build on x86_64

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4364]
openimageio 2.0.12-2, breaks blender 2.79b. May break existing functionality if system update.
Tested on: Haiku R1B1 hrev52295+129 x86_64. Tested with blender-2.27b-15 working with OSL 1.9.5-1 and OIIO-1.8.6-6. 

[blender-2.79b_OIIO-2.0.12_build.txt](https://github.com/haikuports/haikuports/files/3826097/blender-2.79b_OIIO-2.0.12_build.txt)

**Comment by korli** [comment]
"breaks build" means a build failure. Where is the build failure in this ticket?

**Comment by kenmays** [comment]
See attachment.

**Comment by kenmays** [comment]
Fixed:
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/3746/builds/14525.log
