### ISSUE TITLE
LibreOffice - Calc (spreadsheet) - "Paste Only Formula" function doesn't work

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#4367]
Hello.   I found that, if you copy the content of a cell containing a formula, and use the "Paste Only Formula" in a blank cell, you don't get the formula copied.

Tested in LibreOffice 6.3.3.2,  32 bit version.

**Comment by Begasus** [comment]
Confirmed here

**Comment by diversys** [comment]
Does it work on Linux with the kde5 (kf5) backend? Start LibreOffice like this:
`SAL_USE_VCLPLUGIN=kf5 soffice.bin --writer`

**Comment by Begasus** [comment]
Works ok when launched with "SAL_USE_VCLPLUGIN=kf5 soffice --calc" formula is copied over correctly.

**Comment by diversys** [comment]
Is the LO version the same? Also check About window to see if kf5 backend is the one that is active.

**Comment by Begasus** [comment]
![Libre-Office_version](https://user-images.githubusercontent.com/16057090/68961190-1a0fef80-07d2-11ea-973d-1db5b9cda643.png)

**Comment by diversys** [comment]
This version is way too old to compare and uses gtk3 VCL (backend).

**Comment by Begasus** [comment]
![LO_Haiku](https://user-images.githubusercontent.com/16057090/68961663-28124000-07d3-11ea-885f-7dc5ba812be5.png)

**Comment by Begasus** [comment]
My host system (Ubuntu) is updated pretty much on par, so I can only compare between the both of them :)

**Comment by diversys** [comment]
Yep, you need to install current version of LibreOffice if we want to have reasonable comparison.

**Comment by Begasus** [comment]
Updated my ubuntu install and the install for libreoffice (both on par), in calc it still works as expected

**Comment by Begasus** [comment]
Just did a re-check, seems to work ok now (=sum(A1:A4)) copied over to the next field seems to work ok.
![LO_CP](https://user-images.githubusercontent.com/16057090/69347019-1669e600-0c74-11ea-9d65-9b8de3d42eed.png)

**Comment by Begasus** [comment]
Only when I tried to create a screenshot (with the keyboard shortcut) it removed the formula in Calc?

**Comment by unspacyar** [comment]
@Begasus: Hi. I tested it and found the same issue: if I had selected a cell with a value in it, and press the "Print Screen" button, the cell get blank.

However, I still have the "Copy" and "Paste only Formula issue"

Apparently, there are two issues here.

**Comment by diversys** [comment]
Could be related to https://bugs.documentfoundation.org/show_bug.cgi?id=127666.

**Comment by threedeyes** [comment]
This is a very strange problem. I completely disable of the PrintScreen key mapping for Qt applications in QPA (platform plugin - https://github.com/threedeyes/qthaikuplugins/commit/5a4bbbae92d11c9112b5c463f066e7abbdf9ce76), but  the problem remained.

**Comment by threedeyes** [comment]
>Only when I tried to create a screenshot (with the keyboard shortcut) it removed the formula in Calc?

This bug fixed in -https://github.com/haikuports/haikuports/commit/9f354ffc6498098d1ab7645500e264e64ba0fd1d
