### ISSUE TITLE
QtWebkit linked against libjpeg_turbo on x86_64?

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#4368]
When checking the issue for osl I found out that qtwebkit is using libjpeg_turbo instead of libjpeg on x86_64, on x86_gcc2 it seems ok (from Terminal on x86_64):
```
~> grep libjpeg.so.62 /boot/system/lib/*.so
Binary file /boot/system/lib/libQt5WebKit.so matches
```

**Comment by korli** [comment]
rebuild in b2bb6cd26d5a615115ed133981240c662e43269f

**Comment by Begasus** [comment]
Fixed! Thanks @korli ... no need for libjpeg_turbo anymore :+1:
