### ISSUE TITLE
poppler recipes are broken

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#4374]
Checked with all 3 versions for poppler (need cmd:python3 instead of cmd:python2)
```
[ 44%] Building CXX object utils/CMakeFiles/pdftotext.dir/Win32Console.cc.o
[ 45%] Building CXX object utils/CMakeFiles/pdfunite.dir/pdfunite.cc.o
[ 45%] Generating poppler-enums.h
env: 'python3': No such file or directory
glib/CMakeFiles/poppler-glib.dir/build.make:90: recipe for target 'glib/poppler-enums.h' failed
make[2]: *** [glib/poppler-enums.h] Error 127
make[2]: *** Deleting file 'glib/poppler-enums.h'
 CMakeFiles/Makefile2:548: recipe for target 'glib/CMakeFiles/poppler-glib.dir/all' failed
make[1]: *** [glib/CMakeFiles/poppler-glib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by korli** [comment]
on x86_gcc2?

**Comment by Begasus** [comment]
Checked on x86_64 (with a build for the recipes), not checked on x86_gcc2 yet

**Comment by Begasus** [comment]
Checking on x86_gcc2 with "hp poppler_x86" it seems to be OK with using python2 (no error there), but I'm getting policy errors:
```
Warning: POLICY ERROR: no matching provides "devel:libpoppler_cpp_x86" for "develop/lib/libpoppler-cpp.so"
Warning: POLICY ERROR: no matching provides "devel:libpoppler_cpp_x86" for "develop/lib/libpoppler-cpp.so.0"
Warning: POLICY ERROR: no matching provides "devel:libpoppler_cpp_x86" for "develop/lib/libpoppler-cpp.so.0.3.0"
Warning: POLICY ERROR: no matching provides "devel:libpoppler_glib_x86" for "develop/lib/libpoppler-glib.so"
Warning: POLICY ERROR: no matching provides "devel:libpoppler_glib_x86" for "develop/lib/libpoppler-glib.so.8"
Warning: POLICY ERROR: no matching provides "devel:libpoppler_glib_x86" for "develop/lib/libpoppler-glib.so.8.9.0"
Warning: POLICY ERROR: no matching provides "devel:libpoppler_qt5_x86" for "develop/lib/libpoppler-qt5.so"
Warning: POLICY ERROR: no matching provides "devel:libpoppler_qt5_x86" for "develop/lib/libpoppler-qt5.so.1"
Warning: POLICY ERROR: no matching provides "devel:libpoppler_qt5_x86" for "develop/lib/libpoppler-qt5.so.1.12.0"
Warning: Error: packaging policy violation(s) in strict mode
```

**Comment by Begasus** [comment]
Only thing I could find in CmakeCache.txt is: 
```
CMAKE_INSTALL_LIBEXECDIR:PATH=/packages/poppler_x86-0.62.0-1/.self/lib
```
Maybe cmakeDirArgs doesn't take this one into account?

**Comment by Begasus** [comment]
Bumped  cmake to the latest version, looking at the "INSTALL" part in Terminal it all looks ok (installing libs in ./self/lib/x86/*), can't figure out where the error is coming from ...

**Comment by korli** [comment]
Is this still an issue?

**Comment by Begasus** [comment]
Need to re-check

**Comment by Begasus** [comment]
Still an issue, I can't full-sync atm (wanted to see if maybe some requirements were updated) due to an issue regarding gnutls vs nettle

**Comment by Begasus** [comment]
Thanks on the fix for gnutls, back on par on that one, unfortunately it didn't solve any problems after updating, tried using python3 on gcc2h but that ended up in the similar error on x86_64
```
/bin/env: /bin/python: No such file or directory
```

**Comment by korli** [comment]
Not sure how to reproduce. This is still yhen building poppler?

**Comment by Begasus** [comment]
Yes, just a simple "hp poppler(_x86)" in Terminal, nothing fancy (don't think I changed anything in the recipe, will check on another machine)

**Comment by Begasus** [comment]
I think I see the problem, for poppler and poppler062 there is the next in PROVIDES_devel (wrong):
```
	devel:libpoppler${secondaryArchSuffix}_cpp = $libCppVersionCompat
	devel:libpoppler${secondaryArchSuffix}_glib = $libGlibVersionCompat
	devel:libpoppler${secondaryArchSuffix}_qt5 = $libQt5VersionCompat
```
For poppler076 there is (that correct):
```
	devel:libpoppler_cpp$secondaryArchSuffix = $libCppVersionCompat
	devel:libpoppler_glib$secondaryArchSuffix = $libGlibVersionCompat
	devel:libpoppler_qt5$secondaryArchSuffix = $libQt5VersionCompat
```

**Comment by korli** [comment]
must be a problem in glib then. for more logs can you try with "make VERBOSE=1"?

**Comment by Begasus** [comment]
I already thought that, somehow glib generates python2 on gcc2(_x86) and python3 on x86_64
Output from Terminal: https://pastebin.com/GrHbVaaW

**Comment by korli** [comment]
please try with glib2_devel update.

**Comment by Begasus** [comment]
Update after glib2 bump, fails to find the gobject header? https://pastebin.com/MWrMwSwf

**Comment by Begasus** [comment]
No change in the recipe (there is also still cmd:python2) in it

**Comment by Begasus** [comment]
glib2 won't update to the latest _x86 version on gcc2h (maybe hrev related?), still on v2.57.1-2 there ...

**Comment by korli** [comment]
build failure actually: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/3623/builds/33865.log

**Comment by Begasus** [comment]
It has been a while since glib2 has seen any updates for gcc2h, so I don't think it's the first time ...

**Comment by korli** [comment]
couldn't reproduce with poppler076

**Comment by Begasus** [comment]
This can be closed, new PR for poppler is working fine for me (with the comments given there) :)
