### ISSUE TITLE
Write a recipe for ncdu.

### ISSUE THREAD

**Issue by return** [haikuports/haikuports#4375]
Write a recipe for ncdu - A disk usage analyser with a ncurses interface.

Should be a good GCI starter task in porting ncdu to Haiku.

https://dev.yorhel.nl/ncdu

**Comment by Ra-V2** [comment]
https://github.com/haikuports/haikuports/pull/4446

**Comment by return** [comment]
As of this [commit](https://github.com/haikuports/haikuports/commit/c9440e68d71e5fbde7bd3a5252aa545f689b4b3b) this recipe has been merged. Closing
