### ISSUE TITLE
Write a recipe for Frotz

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#4376]
Frotz is an interpreter for Infocom games and other Z-machine games.

https://davidgriffith.gitlab.io/frotz/

New version is release as mentioned in the next comment: this can be found at: https://gitlab.com/DavidGriffith/frotz/-/archive/2.50/frotz-2.50.tar.bz2

**Comment by DavidGriffith** [comment]
2.50 is released now.  I've since removed the beta dpwnloads.

**Comment by Begasus** [comment]
Thanks for replying to this @DavidGriffith ! I'll update the link(s) :)

**Comment by R4H33M** [comment]
I'd like to take this for GCI! I've gotten it working on Haiku, I just need to write a recipe for it.

**Comment by Begasus** [comment]
Actually there is already someone working on it @R4H33M sorry: https://github.com/haikuports/haikuports/pull/4443

**Comment by R4H33M** [comment]
oops.... okay, then!

**Comment by korli** [comment]
#4532
