### ISSUE TITLE
*** failed to commit transaction: Failed to change the package activation in packagefs: Name in use

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#4377]
I've seen this passing by a few times already, for some packages it's OK to just remove them from the system (after local updating), now I get this when trying "pkgman full-sync" and it fails on:
```
upgrade package lcms_x86-2.9-4 to 2.9-4 from repository HaikuPort
```
pkgman update worked OK (didn't involve lcms upgrade) so this was the only one the full-sync complains about, I can't just remove lcms from the system as it involves quite a lot of dependencies to be removed ...
Atleast pkgman should report what name is in use, and or check local and remote package for checksum?

**Comment by Begasus** [comment]
Reverting the "REVISION" in the local recipe and installing fixes it, but shouldn't be the correct sollution ...

**Comment by CodeforEvolution** [comment]
This is actually a flaw in packagefs I believe...I may have seen an issue within the code while looking around before, but I can't exactly remember what it was...

**Comment by Begasus** [comment]
It's still a pain in the * wanted to update the packages and again the same message ... no luck now trying to find out what package is in use ...

**Comment by Begasus** [comment]
Seems to come from here: https://github.com/haiku/haiku/blob/abb59d7351c7ddb50c63c40430a82d94fa61917a/src/kits/package/CommitTransactionResult.cpp#L482
Maybe I should create an issue at Haiku tracker?

**Comment by Begasus** [comment]
Already reported https://dev.haiku-os.org/ticket/15068
