### ISSUE TITLE
Upstream sdl2 patchset

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#4382]
From EXL:
> Most our patches are merged into the SDL2 upstream today but some questions remain:
>
>https://bugzilla.libsdl.org/show_bug.cgi?id=4442
>
>These are mainly questions on fixing autotools build files by @korli and @pulkomandy, also question about B_NO_POINTER_HISTORY patch by @threedeyes.
>
>I think it’s worth clarifying the situation in the official SDL2 BugTracker...
>Regards.

From Pulkomandy
> They contacted me over twitter as well to ask me to look into it. Maybe we need a recipe for the git version sowe can more easily keep track of what is upstreamed already?

**Comment by korli** [comment]
see https://github.com/haikuports/haikuports/pull/3481

**Comment by EXL** [comment]
@korli It seems that almost all patches were merged to the SDL2 upstream. Only that remains: 

```diff
--- a/Makefile.in	
+++ a/Makefile.in	
@@ -144,13 +144,13 @@ update-revision:
 .PHONY: all update-revision install install-bin install-hdrs install-lib install-data uninstall uninstall-bin uninstall-hdrs uninstall-lib uninstall-data clean distclean dist $(OBJECTS:.lo=.d)
 
 $(objects)/$(TARGET): $(GEN_HEADERS) $(GEN_OBJECTS) $(OBJECTS) $(VERSION_OBJECTS)
-	$(RUN_CMD_LTLINK)$(LIBTOOL) --tag=CC --mode=link $(CC) -o $@ $(OBJECTS) $(GEN_OBJECTS) $(VERSION_OBJECTS) $(LDFLAGS) $(EXTRA_LDFLAGS) $(LT_LDFLAGS)
+	$(RUN_CMD_LTLINK)$(LIBTOOL) --tag=CXX --mode=link $(CXX) -o $@ $(OBJECTS) $(GEN_OBJECTS) $(VERSION_OBJECTS) $(LDFLAGS) $(EXTRA_LDFLAGS) $(LT_LDFLAGS)
 
 $(objects)/$(SDLMAIN_TARGET): $(SDLMAIN_OBJECTS)
-	$(RUN_CMD_LTLINK)$(LIBTOOL) --tag=CC --mode=link $(CC) -static -o $@ $(SDLMAIN_OBJECTS) -rpath $(libdir)
+	$(RUN_CMD_LTLINK)$(LIBTOOL) --tag=CXX --mode=link $(CXX) -static -o $@ $(SDLMAIN_OBJECTS) -rpath $(libdir)
 
 $(objects)/$(SDLTEST_TARGET): $(SDLTEST_OBJECTS)
-	$(RUN_CMD_LTLINK)$(LIBTOOL) --tag=CC --mode=link $(CC) -static -o $@ $(SDLTEST_OBJECTS) -rpath $(libdir)
+	$(RUN_CMD_LTLINK)$(LIBTOOL) --tag=CXX --mode=link $(CXX) -static -o $@ $(SDLTEST_OBJECTS) -rpath $(libdir)
 
 install: all install-bin install-hdrs install-lib install-data
 install-bin:
--- a/configure.in	
+++ a/configure.in	
@@ -3733,9 +3733,6 @@ AC_HELP_STRING([--enable-render-d3d], [enable the Direct3D render driver [[defau
         # The Haiku platform requires special setup.
         SOURCES="$srcdir/src/main/haiku/*.cc $SOURCES"
         EXTRA_LDFLAGS="$EXTRA_LDFLAGS -lroot -lbe -lmedia -lgame -ldevice -ltextencoding"
-        # Haiku's x86 spins use libstdc++.r4.so (for binary compat?), but
-        #  other spins, like x86-64, use a more standard "libstdc++.so.*"
-        AC_CHECK_FILE("/boot/system/lib/libstdc++.r4.so", EXTRA_LDFLAGS="$EXTRA_LDFLAGS -lstdc++.r4", EXTRA_LDFLAGS="$EXTRA_LDFLAGS -lstdc++")
         ;;
     arm*-apple-darwin*|*-ios-*)
         ARCH=ios
-- 
```

[Additional information](https://bugzilla.libsdl.org/show_bug.cgi?id=4442#c14).

**Comment by korli** [comment]
> @korli It seems that almost all patches were merged to the SDL2 upstream. Only that remains:

Switching to CXX, g++ will automatically pick up libstdc++ or libstdc++.r4.so, thus removing the need to add link flag in EXTRA_LDFLAGS. This must be needed to build on x86_gcc2 secondary arch at least.
The patch could be improved, for instance adding LIBTOOL_TAG and LIBTOOL_LINKER variables that could be overriden for Haiku.

**Comment by waddlesplash** [comment]
Linker patch to use g++ to link was also upstreamed: https://github.com/libsdl-org/SDL/pull/4537/files
