### ISSUE TITLE
Koder crashes on startup

### ISSUE THREAD

**Issue by andimachovec** [haikuports/haikuports#4385]
Koder version 0.5.1, package version 0.5.1-1 on Haiku x86_64 hrev 53561 crashes immediately when started. Self built koder from the latest github sources works normally. I have the language set to German, if that matters.

**Comment by Begasus** [comment]
Confirmed (on x86_gcc2), didn't notice as I'm using Pe mostly

**Comment by Begasus** [comment]
On x86_64 I just installed it, with "Open with" Koder doesn't appear in the list also

**Comment by andimachovec** [comment]
Open with Koder is there on my system. But I have it installed for a long time. Didnt use my Haiku laptop for about 3 weeks. Today I updated it and noticed the crashing of Koder. So I can't really pin it down to a specific hrev. I will build it with haikuporter myself and report back if it worked.

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/4379
