### ISSUE TITLE
FFmpeg: moov atom not found

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4388]
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 000002a477298a80] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 000002a477298a80] moov atom not found
```
See: ffmpeg-4.2.1-1-x86_gcc2.hpkg

**Comment by korli** [comment]
broken video file?

**Comment by kenmays** [comment]
Newer method is moving the data to the front of the video stream versus the end of it for quicker setup.
A patch may exist to handle things overall.

**Comment by korli** [comment]
> Newer method is moving the data to the front of the video stream versus the end of it for quicker setup.
If it's a upstream bug, why do you report here?

**Comment by kenmays** [comment]
Confirmed, still an upstream issue.
