### ISSUE TITLE
add scourge

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#439]
From old site:

S.C.O.U.R.G.E. is a roguelike game with a 3D user interface. The game allows a group of four characters to search for treasure, kill enemies, gain levels, etc. The code is C++ using SDL, OpenGL and freetype.
 http://scourgeweb.org
Attachments

scourge-0.21.1.bep​ (778 bytes) - added by michaelvoliveira 5 years ago.
Initial .bep file. Builds fine with GCC4 only
scourge-0.21.1.patch​ (2.8 KB) - added by michaelvoliveira 5 years ago.
Patch to set a datadir and replace glXGetProcAddressARB for glutGetProcAddress
scourge-0.21.1-data.bep ​ (525 bytes) - added by michaelvoliveira 5 years ago.
Incomplete .bep file for datafiles. Don't know how I do it
Changed 5 years ago by michaelvoliveira

attachment scourge-0.21.1.bep​ added
Initial .bep file. Builds fine with GCC4 only
Changed 5 years ago by michaelvoliveira

attachment scourge-0.21.1.patch​ added
Patch to set a datadir and replace glXGetProcAddressARB for glutGetProcAddress
Changed 5 years ago by michaelvoliveira

attachment scourge-0.21.1-data.bep ​ added
Incomplete .bep file for datafiles. Don't know how I do it
comment:1 Changed 5 years ago by michaelvoliveira

Edit
Reply
Component changed from default to games-roguelike/scourge
Owner set to michaelvoliveira
comment:2 Changed 5 years ago by augiedoggie

Edit
Reply
The patch needs some work. You shouldn't remove the glX support.
comment:3 Changed 13 months ago by scottmc

Edit
Reply
Type changed from task to WIP - file(s) attached

[attachments-ticket-463.zip](https://github.com/haikuports/haikuports/files/105678/attachments-ticket-463.zip)

**Comment by Begasus** [comment]
I guess you should update the homepage (the link above doesn't provide anything usefull) :)
https://sourceforge.net/p/scourge/wiki/Home/

**Comment by Begasus** [comment]
Guess this could be closed (and maybe a new ticket created for the error) :)
Game source recipe: https://github.com/haikuports/haikuports/pull/3483
Data files recipe: https://github.com/haikuports/haikuports/pull/3484

**Comment by Begasus** [comment]
The error encountering when trying to launch scourge is maybe related to the glX fix (mentioned here in comment 3?
```
 ~> scourge 
  Constructing root path:
          not using binreloc...
          temp rootDir=/packages/scourge_x86-0.21.1-1/.self/data/scourge
  *** Can't find local version of data dir. You're running a distribution.
  Looking for localized resources in: /packages/scourge_x86-0.21.1-1/.self/data/scourge/translations
  Starting session. Final rootDir=/packages/scourge_x86-0.21.1-1/.self/data/scourge
  Setting video mode: 1024x768x32
  GalliumContext: CreateScreen: Using llvmpipe (LLVM 5.0, 128 bits) driver.
  Unlocking BLocker with sem 1841914 from wrong thread 65333, current holder -1 (see issue #6400).
```
