### ISSUE TITLE
Switch to cmake build for tox

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#4394]
With autotools tox is creating 3 seperate libraries (when libvpx is enabled), with cmake it's down to 1 library libtoxcore, see: https://github.com/TokTok/c-toxcore/issues/869

**Comment by 00p513-dev** [comment]
working on it...

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/5488 :)
