### ISSUE TITLE
Update BeScreenCapture to 2.5.0

### ISSUE THREAD

**Issue by jackburton79** [haikuports/haikuports#4397]
I released a new version of BeScreenCapture (2.5.0).
https://github.com/jackburton79/bescreencapture/releases/tag/v2.5.0

- Add an option to export to animated GIF (experimental, but working)
- Fixed saving/restoring selected file format (was broken for Export to Bitmap).
- Improved frame rate selection interface.
- Fixed deskbar menu drawing and changed colors.
- Various improvements and cleanups.

Recipe should be updated.

I noticed there is a patch in the haikuports recipe. Is build broken on some architecture ? Is it still needed ?

Thanks!

**Comment by humdingerb** [comment]
Yes. Without ```#include <algorithm>``` in OutputView.cpp the build fails under gcc2.

**Comment by Begasus** [comment]
Hi Jack, just checked a build for the new version, patch is still needed (checked on gcc2h with gcc2)
```
/sources/bescreencapture-2.5.0/OutputView.cpp: In method `void OutputView::_LayoutView()':
/sources/bescreencapture-2.5.0/OutputView.cpp:280: `::max' undeclared (first use here)
/boot/system/develop/etc/makefile-engine:297: recipe for target 'objects/OutputView.o' failed
```

**Comment by Begasus** [comment]
On x86_64 with gcc8 it builds ok with or without <algorithm>

**Comment by Begasus** [comment]
Bumped in https://github.com/haikuports/haikuports/pull/4398
