### ISSUE TITLE
add bencode-tools

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#440]
From old site:

bencode-tools

Reported by:    nicholas    Owned by:   scottmc
Priority:   normal  Milestone:  
Component:  dev-util/awka   Version:  
Severity:   normal  Keywords:   bencode-tools
Cc:  
Description 

Reply
bencode-tools' is a collection of C and Python tools for manipulating bencoded data. This was formerly named 'type validator'.
The collection consists of a C library for reading and writing bencoded data, and a Python implementation of bencode included with 'typevalidator' that can be used to verify typing and contents of bencoded messages. 
Attachments

bencode-tools-2011-03-15.bep​ (629 bytes) - added by nicholas 3 years ago.
Download all attachments as: .zip
Attach file
Change History

Changed 3 years ago by nicholas

attachment bencode-tools-2011-03-15.bep​ added

[bencode-tools-2011-03-15.bep.txt](https://github.com/haikuports/haikuports/files/105682/bencode-tools-2011-03-15.bep.txt)

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/773

**Comment by Begasus** [comment]
I gather this one can be closed? ;)
