### ISSUE TITLE
XaoS: crashes on x86_gcc2

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4401]
- Crashes when selecting certain filters (i.e. Antialiasing, Pseudo 3d).
- About Xaos shows 'XaoS 3.1'.

Tested: hrev53592 x86_gcc2, xaos-3.4-4-x86_gcc2.hpkg 

[XaoS-760-debug-24-11-2019-16-22-29.txt](https://github.com/haikuports/haikuports/files/3882837/XaoS-760-debug-24-11-2019-16-22-29.txt)

**Comment by diversys** [comment]
Dupe of #2721.
