### ISSUE TITLE
"git grep" now crashes inside PCRE

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#4403]
see https://github.com/haikuports/haikuports/commit/8e37daa428d43a15b4ed62180714ce3042fa0ccc#commitcomment-36109355

**Comment by korli** [comment]
disabled jit on x86_gcc2 with b7c2cbf316e0a954520ef2e409181c328c3123c5

**Comment by korli** [comment]
[git-896-debug-25-11-2019-18-03-57.txt](https://github.com/haikuports/haikuports/files/3893688/git-896-debug-25-11-2019-18-03-57.txt)

**Comment by korli** [comment]
upstream bug report https://bugs.exim.org/show_bug.cgi?id=2470

**Comment by korli** [comment]
@waddlesplash  @pulkomandy do we want to more investigate here? disabling jit seems more correct, given that the tests fail in 10.33 too. An idea might be to switch git to _x86.

**Comment by pulkomandy** [comment]
Switching to _x86 is fine if that works. There's no point maintaining gcc2 support forever for git.

**Comment by korli** [comment]
well git tests are a bit weird, they stop after a few failure. do you have a tip to have the debug_server not display the pop up?

**Comment by humdingerb** [comment]
> do you have a tip to have the debug_server not display the pop up?

You can edit ~/config/settings/system/debug_server/settings.
See the user guide's "Debugger" page:
https://www.haiku-os.org/docs/userguide/en/applications/debugger.html

**Comment by korli** [comment]
I thought of something I could use in the recipe, is it actually possible?

**Comment by pulkomandy** [comment]
does disable_debugger() inside the test main() function work?

We may want an environment variable for this, in fact.

**Comment by korli** [comment]
I added an action for /sources/git-* as a workaround.

**Comment by korli** [comment]
I suggested to pcre upstream to close the issue, as the pcre-10.33 tests already fail with gcc2. so no regression. Maybe git handles things differently, thus exposing the JIT issue.
