### ISSUE TITLE
wpa_supplicant: build issues on x86_gcc2, bump version

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4406]
Failures on src/drivers/driver_bsd.c : IEEE80211 ... undeclared
Tested on hrev53602 x86_gcc2,wpa_supplicant-2.7~devel.haiku.1-1-x86_gcc2

**Comment by waddlesplash** [comment]
This is expected, don't try to build the current wpa supplicant against a nightly, or an updated version against b1, it won't work.
