### ISSUE TITLE
add GRI

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#441]
From old site, this is a leftover from GCI2012:

Reported by:	richienyhus	Owned by:	
Priority:	normal	Milestone:	
Component:	default	Version:	
Severity:	normal	Keywords:	GCI .bep patch
Cc:			
Description 

Reply
From GCI2012
Attachments

gri-2.12.23.bep​ (701 bytes) - added by richienyhus 3 years ago.
gri.tar.gz​ (1008 bytes) - added by richienyhus 3 years ago.
Download all attachments as: .zip
Attach file
Change History

Changed 3 years ago by richienyhus

attachment gri-2.12.23.bep​ added
Changed 3 years ago by richienyhus

attachment gri.tar.gz​ added
comment:1 Changed 3 years ago by richienyhus

Edit
Reply
by student skycocker
comment:2 Changed 13 months ago by scottmc

Edit
Reply
Type changed from defect to WIP - file(s) attached

[attachments-ticket-710.zip](https://github.com/haikuports/haikuports/files/105687/attachments-ticket-710.zip)

**Comment by waddlesplash** [comment]
https://github.com/haikuports/haikuports/blob/master/sci-visualization/gri/gri-2.12.23.recipe
