### ISSUE TITLE
Add dave_gnukem

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#4413]
should go in games-action
https://github.com/davidjoffe/dave_gnukem

**Comment by Begasus** [comment]
Can be done with some patching :)
![Dave-Gnukem](https://user-images.githubusercontent.com/16057090/71166108-51027680-2252-11ea-95d9-a385f22d281f.png)

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/4498
