### ISSUE TITLE
ccextractor: needs libtesseract=3.02.02 (x86_64)

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4416]
ccextractor: nothing provides libtesseract>=3.02.02
Tested: hrev52285+132 x86_64, ccextractor-0.85-1-x86_64, tesseract-3.05.02-1-x86_64.hpkg

**Comment by kenmays** [comment]
@korli - Rebuilt ccextractor. This requires a previous rebuild of tessaract due to libpng15 dependency to fix.

**Comment by korli** [comment]
bumped in c6f228c655c3a1355a6eb813d411f496b143aa2d
