### ISSUE TITLE
blender: missing symbol (x86_64)

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4417]
During program launch, displays missing symbol error in GUI/terminal..
Tested: blender 2.79b-14, hrev52295+132 x86_64
![blender-bad](https://user-images.githubusercontent.com/5168719/70058815-76c22700-1594-11ea-9124-58e19c21ae96.jpg)

**Comment by extrowerk** [comment]
Which symbol is missing?

**Comment by kenmays** [comment]
@extrowerk @korli - Rebuilt blender pkg. Issue resolved.

**Comment by extrowerk** [comment]
I don't see revision bump in the commit log, thus the problem still exists if one installs it from the Depot, i assume (as @kenmays did not provided enoug information, and my Haiku machine is out of order right now, so i can't test).

**Comment by kenmays** [comment]
@extrowerk @korli - blender pkg still needs rebuild (bump recipe revision). I posted the error, but that issue is resolved once the rebuild is done. No current issues during local compilation.

**Comment by kenmays** [comment]
Fixed in blender 2.79b-15..
