### ISSUE TITLE
Update recipe for netpbm to use a "safe" source

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#4420]
netpbm uses an unsafe source and wont be build or show up in HaikuDepot, update the recipe to use the latest release and make the needed changes to the recipe.
Current recipe is found in media-libs/netpbm

**Comment by korli** [comment]
URL example: https://github.com/t6/netpbm/releases/download/v10.88.01/netpbm-10.88.01.tar.xz

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/4435
