### ISSUE TITLE
leptonica: rebuild due to libpng15 depend

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4421]
leptonica-1.78.0-1-x86_64.hpkg  still depends on libpng15 dependency. Needs rebuild.

**Comment by korli** [comment]
I can't confirm the issue sorry.

**Comment by kenmays** [comment]
No worries. I rebuilt it and it fixed the downstream issues.

**Comment by korli** [comment]
rebuilt against libpng16
