### ISSUE TITLE
Add a scipy_python3 recipe

### ISSUE THREAD

**Issue by iam-git** [haikuports/haikuports#4431]
And maybe put **scipy** to **haikuports/dev-python/**?

**Comment by korli** [comment]
No it should stay in sci-libs:
https://packages.gentoo.org/packages/sci-libs/scipy

**Comment by Begasus** [comment]
Also create one for scipy_python36 ...

While in the process bump version to 1.3.1 https://github.com/scipy/scipy/releases/tag/v1.3.1

**Comment by korli** [comment]
@Begasus can this be closed?

**Comment by Begasus** [comment]
The recipe is merged, so it should be ok :)
