### ISSUE TITLE
Write recipe for nesalizer

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#4439]
https://github.com/ulfalizer/nesalizer

**Comment by alwayslivid** [comment]
I am currently checking this out, but apparently, the `librt` library is needed and I cannot find it within the repository.

Are any additional ports necessary, or am I missing something?

**Comment by Begasus** [comment]
We don't have librt, try to patch the dependency out

**Comment by alwayslivid** [comment]
> We don't have librt, try to patch the dependency out

I've tried to experiment with a few options, but it boils down to this:

```sh
waiting for build package nesalizer-release-2 to be activated
Building ...
Using configuration "release"
Linking build/nesalizer
build/common.o: In function `fatal_signal_handler(int)':
/sources/nesalizer-[commit revision]/src/common.cpp:104:undefined source to `backtrace'
//sources/nesalizer-[commit revision]/src/common.cpp:110:undefined reference to `backtrace_symbols_fd'
collect2: error: ld returned 1 exit status
Makefile:143: recipe for target 'build/nesalizer' failed
make: *** [build/nesalizer] Error 1
```

The line that causes the trouble here seems to be the [Makefile](https://github.com/ulfalizer/nesalizer/blob/master/Makefile) on line 61.

`LDLIBS := $(shell sdl2-config --libs) -lrt`

The line adds sdl2-config's required libraries, as well as the `librt` library. It also adds a couple of other libraries (namely libraries such as `devel:libavcodec`, `devel:libavformat`, `devel:libavutil`, etc.) depending on the local configurations. (such as whether the `RECORD_MOVIE` and/or the `INCLUDE_DEBUGGER` variables are marked as true)
