### ISSUE TITLE
[blender] empty menus and toolbars

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#4459]
Component: media-gfx/blender
Platform: Haiku hrev53634 x86_64
Build on: Haiku hrev53634 x86_64
Compiled by: haikuporter --get-dependencies --no-source-packages blender

![blender](https://user-images.githubusercontent.com/45505339/71063203-9ae65080-21af-11ea-9e38-c45870b24468.png)
[blender-log.txt](https://github.com/haikuports/haikuports/files/3977054/blender-log.txt)

**Comment by extrowerk** [comment]
I think the ui elements are there, but they are invisible. Could you try to resize / move the window?
It is a bug nevertheless, but i think it is a bug in Haiku, not in Blender.
Currently Blender is not useful on Haiku, it is just kind of capability-benchmark, do not expect quick fix.

**Comment by X547** [comment]
No menus are empty even after resizing and clicking has no effect. Look like python problems.

**Comment by X547** [comment]
Menus were working in repo build before #4417 bug appear.

**Comment by X547** [comment]
> It is a bug nevertheless, but i think it is a bug in Haiku, not in Blender.
Haiku OpenGL implementation, including BGLView source, is hosted here (sys-libs/mesa).

**Comment by X547** [comment]
I changed python version to 3.6 and blender is working now:
![blender2](https://user-images.githubusercontent.com/45505339/71230470-191c3180-232d-11ea-8992-c6d5b8c84e6d.png)
Window draw method should be set to "Overlap Flip" to correct drawing. BDirectWindow should be changed to BWindow in SDL 2 (#4457) to avoid cursor artifacts.

**Comment by extrowerk** [comment]
Yould you create a PR with the Python change?
