### ISSUE TITLE
Freeciv, update recipes for the latest releases

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#4464]
Freeciv just released version 2.6.1 and 2.5.12: https://github.com/freeciv/freeciv/releases

**Comment by Begasus** [comment]
While in the process do some cleanup on the older recipes

**Comment by Begasus** [comment]
@korli maybe we could rename the 2.5* version to freeciv52-$portVersion.recipe?

**Comment by korli** [comment]
> @korli maybe we could rename the 2.5* version to freeciv52-$portVersion.recipe?

Why? Just remove them.

**Comment by Begasus** [comment]
> > @korli maybe we could rename the 2.5* version to freeciv52-$portVersion.recipe?
> 
> Why? Just remove them.

They still work on the 2.5.* versions, we could drop them, but then we need to be sure that we support upcoming versions for 2.6.* (3.0 is already marked as stable (not released), master branch is already wip for 3.1)

**Comment by korli** [comment]
we *are* on 2.6.0 at the moment. we can update to 2.6.1 and drop everything else.

**Comment by Begasus** [comment]
Have been checking (and been in contact with the freeciv devs in the past days), we could indeed drop 2.5.* series (they depend on lua5.2) in favour of the 2.6.* series (depend on lua5.3), checked out a latest srcGitRev build for the latest changes on the S2_6 and still builds and runs fine
