### ISSUE TITLE
[mesa] BGLView created after first BGLView not work properly

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#4466]
Component: sys-libs/mesa.
Version: 17.1.10-5.
Platform: x86_64.

Graphics rendered on BGLView created after first BGLView have glitches. Blender user preferences dialog:
![screenshot1](https://user-images.githubusercontent.com/45505339/71306606-d9854080-2425-11ea-9f76-383f47bc830a.png)
Same dialog opened in main window rendered properly:
![screenshot2](https://user-images.githubusercontent.com/45505339/71306621-1b15eb80-2426-11ea-86f8-c329b9f42944.png)

**Comment by X547** [comment]
I identified problem. Blender create shared context (`SDL_GL_SetAttribute(SDL_GL_SHARE_WITH_CURRENT_CONTEXT, 1)`), but it doesn't handled in libSDL2 port and Mesa HGL. I adjusted HGL to always create shared context and problem disappeared.

**Comment by diversys** [comment]
Has this been merged yet? https://cgit.freedesktop.org/mesa/mesa/log/?qt=author&q=X512
