### ISSUE TITLE
Port Allegro 5.x to Haiku 

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4468]
Allegro is a cross-platform library mainly aimed at video game and multimedia programming. It handles common, low-level tasks such as creating windows, accepting user input, loading data, drawing images, playing sounds, etc. and generally abstracting away the underlying platform.

Allegro 5 is not backwards compatible with Allegro 4.
```
URL: https://liballeg.org/
Src: https://github.com/liballeg/allegro5/releases/download/5.2.5.0/allegro-5.2.5.0.tar.gz
Release: 5.2.5.0
```

GOAL: Allegro 4.4 did support Haiku, but this support was dropped from the newer versions (starting from 5.0). The library should be ported to Haiku, allowing to run the bundled examples and possibly port some other software using it

**Comment by Begasus** [comment]
Already have a recipe local for version 5.2.5.0 :)

**Comment by pulkomandy** [comment]
On Sat, Dec 21, 2019 at 05:33:19PM +0000, kenmays wrote:
> Allegro is a cross-platform library mainly aimed at video game and multimedia programming. It handles common, low-level tasks such as creating windows, accepting user input, loading data, drawing images, playing sounds, etc. and generally abstracting away the underlying platform.
> 
> Allegro 5 is not backwards compatible with Allegro 4.

Allegro 5 needs to be ported to Haiku. It is a lot more work than just
writing a recipe. The code we used to run Allgro 4 is not directly
reusable.

**Comment by Begasus** [comment]
Maybe something for GSoC then? (mentioned I have a recipe, but haven't touched it in a while), if things cool down I can check some allegro ports we have atm

**Comment by Begasus** [comment]
I have a recipe, but it was to check it out (and to find out they removed the beos folder), so this probably would mean a full backport to allegro 5.*

**Comment by scottmc** [comment]
Yeah, they dropped support around 4.4 I think it was.  It would be a GSoC sized task, perhaps on the level of the SDL2 port.  A few years ago, they were open to co-mentoring a project if we found a student interested, I don't know if that is still the case.

**Comment by scottmc** [comment]
Any allegro ports we have or that were built on BeOS years ago, should work with allegro4.
Some of this list were allegro4 based, others SDL1.2: http://web.archive.org/web/20040810182854/http://www.bebits.com/devprofile/1716

**Comment by kenmays** [comment]
Archived.

**Comment by scottmc** [comment]
@Begasus maybe take a look at #7870 seems Allegro has an experimental SDL2 support.

**Comment by kenmays** [comment]
This is already posted as part of: https://www.haiku-os.org/community/gsoc/2022/ideas#ports

Not a current issue. Best to keep this request as part of GSoC, and track under PR.
