### ISSUE TITLE
Port SFML to Haiku

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4469]
SFML is a Simple and Fast Multimedia Library providing a simple interface to the various components of your PC, to ease the development of games and multimedia applications. It is composed of five modules: system, window, graphics, audio and network. 

```
URL: https://www.sfml-dev.org/
Src: https://www.sfml-dev.org/download/sfml/2.5.1/
Release: 2.5.1
```

GOAL: The library should be ported to Haiku, allowing to run any bundled examples and possibly port some other software using it.

**Comment by extrowerk** [comment]
SFML needs platform specific abstraction code to be written. Lets not inspire GCI members to dive into a big programming task with telling them only a recipe required.

**Comment by return** [comment]
> SFML needs platform specific abstraction code to be written.

Then this looks more like a GSoC task similar or even an alternative to the Allegro 5 porting task.

**Comment by kenmays** [comment]
Archived.

**Comment by extrowerk** [comment]
I am not aware of any SFML port, except the wip branch from @CodeforEvolution : https://github.com/CodeforEvolution/SFML/tree/feature/haiku_port
So could you please stop closing issues?

**Comment by kenmays** [comment]
@extrowerk - Thanks. Didn't know he was working it.

**Comment by kenmays** [comment]
@extrowerk  - I did an initial port of SFML-2.5.1 on Haiku R1B2 x86:
```
[ 34%] Built target sfml-system
[ 79%] Built target sfml-network
[100%] Built target sfml-audio
```

 I'll review his patches as time permits.

**Comment by kenmays** [comment]
Closed. Move efforts to libSDL.

**Comment by kenmays** [comment]
This is already posted as part of: https://www.haiku-os.org/community/gsoc/2022/ideas#ports

Not a current issue. Best to keep this request as part of GSoC, and track under a PR.
