### ISSUE TITLE
[sdl2] Deadlock when resizing window with selected OpenGL context

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#4470]
Component: media-libs/libsdl2.
Version: 2.0.10-1.
Platform: x86_64.

SDL_GL_MakeCurrent is implemented as BGLView::LockGL. When window is resized, LockGL is called inside BGLView::FrameResized and lock window thread until OpenGL context will be unset. Input events will be not sent and application will permanently lock.

**Comment by X547** [comment]
Maybe it's better to fix this issue by removing LockGL inside BGLView::FrameResized because it is not really required. OpenGL API is not called inside BGLView::FrameResized.

**Comment by waddlesplash** [comment]
I'm not sure that's correct...

**Comment by X547** [comment]
I tried to delete LockGL/UnlockGL inside of BGLView::FrameResized and deadlock disappear. It seems safe to remove LockGL because SoftwareRenderer::FrameResized has its own lock (fInfoLocker) and it only save size in class fields, no OpenGL API is called.

**Comment by waddlesplash** [comment]
Makes sense, I guess.
