### ISSUE TITLE
Icecast: You should not run icecast2 as root

### ISSUE THREAD

**Issue by stoltenhoff** [haikuports/haikuports#4474]
Today i wanted to pull Icecast from the Haiku depot, but i just fail at the beginning. 
After starting via Terminal:
`ERROR: You should not run icecast2 as root`
I tried everything possible in the configuration file and the official documentation
does not deal with such a special Haiku-specific question.

**Comment by korli** [comment]
You could patch src/main.c and replace line 504
`#ifdef HAVE_SETUID `
with 
`#if defined(HAVE_SETUID) && !defined(__HAIKU__) `

**Comment by Begasus** [comment]
Should be fixed in: https://github.com/haikuports/haikuports/pull/4479

**Comment by Begasus** [comment]
@stoltenhoff coudl you update and check? Never ran it myself, did the recipe to an open issue for it, if it's ok this can be closed

**Comment by extrowerk** [comment]
Seems to be ok
