### ISSUE TITLE
Update the recipe for 0 A.D.

### ISSUE THREAD

**Issue by StanleySweet** [haikuports/haikuports#4494]
Hello,

There was an attempt sometime ago but it doesn't seem to be finished. https://github.com/haikuports/haikuports/pull/1852

It would be nice for 0 A.D. A23.1 to run on haiku. And to port patches needed for that for the A24 release.

I'm available if you have any questions.

See the discussion today on IRC https://echelog.com/logs/browse/haiku-3rdparty/1577314800

**Comment by korli** [comment]
I updated the recipe last novembre. Haiku bfs crashed when packaging the data package, which is the reason I left the recipe disabled. The data package is so large that its packaging met a bug related to bfs journaling.

**Comment by StanleySweet** [comment]
Thanks for trying. Anything I can do to help fix it?

**Comment by kenmays** [comment]
@StanleySweet - I have 0ad-0.0.23b-alpha.. Good enough?

**Comment by kenmays** [comment]
@StanleySweet - Builds successfully with current recipe. on Haiku x86_64. Reviewing data package.

**Comment by kenmays** [comment]
@StanleySweet - Seems to work fine. Haiku currently is confined to OpenGL software rendering, Menu operation and settings seem OK. Seems stable for now.

**Comment by StanleySweet** [comment]
Thanks a lot!  How's performance?

**Comment by kenmays** [comment]
Performance is good for normal gameplay. No major graphical hurdles yet from GUI perspective.

**Comment by StanleySweet** [comment]
Nice. Can this be added to whatever haiku uses as depot?

**Comment by pulkomandy** [comment]
Not until someone else confirms that it works. I'm sorry kenmays but given the many past problems with your recipes and reports I cannot trust you on this, especially when korli says he had issues with a filesystem bug trying to build the package.

**Comment by kenmays** [comment]
@StanleySweet - You can look at the Haiku Depot Server on how other ported games are advertised there: https://depot.haiku-os.org/#!/?bcguid=bc1-LIWV&repos=haikuports&arch=x86_64&viewcrttyp=CATEGORIES&pkgcat=games

Usually its the official game icon, some screenshots, game description.

The recipe maintainer(s) and Haiku Depot maintainers can help you there.

**Comment by StanleySweet** [comment]
Sure I'll use the same stuff as here https://snapcraft.io/0ad

**Comment by korli** [comment]
enabled in b3324855f7dabedd4f6dff9daf6aee67969cb131

**Comment by StanleySweet** [comment]
Thanks a lot guys!

**Comment by kenmays** [comment]
Successful builds: https://build.haiku-os.org/buildmaster/master/x86_64/?buildrunDir=3932&viewMode=expanded
