### ISSUE TITLE
luckyBackup says it cannot create default profile (when opens) under certain circumastances

### ISSUE THREAD

**Issue by fkap69** [haikuports/haikuports#4495]
When app opens through the "Applications" Tracker menu it creates default profile without problem. 
If I invoke it through QuickLaunch or through HaikuDepot then it displays an error that cannot create default profile. This is an issue since it means that you cannot save a backup configuration. Not fatal though because you can bypass it as described above, just annoying. So, I thought I should report it.

**Comment by humdingerb** [comment]
Maybe related to https://dev.haiku-os.org/ticket/12534 ?

**Comment by fkap69** [comment]
Checking the issue you are mentioning I agree that it looks a lot like it. So, I am closing this one.
