### ISSUE TITLE
Write a recipe for Exult

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#4512]
http://exult.sourceforge.net/

And verify that with an up to date version, https://dev.haiku-os.org/ticket/13624 is no more an issue.

**Comment by Begasus** [comment]
Related when trying to build for SDL_1.2 https://github.com/VDrift/vdrift/issues/110

**Comment by Begasus** [comment]
Even after switching to SDL2 I'm still stuck at "'Display' was not declared in this scope"

**Comment by Begasus** [comment]
Came a long way :)

![ExultUltima7Engine](https://github.com/haikuports/haikuports/assets/16057090/b8be9690-c3b6-4e83-a9fa-d542c4e683f7)

**Comment by Begasus** [comment]
PR created, no patching done (yet), for instance saves file in ~/.exult ... https://github.com/haikuports/haikuports/pull/9008
I don't have the games to test it so would be nice if someone could do a check on it :)

**Comment by Begasus** [comment]
Done in https://github.com/haikuports/haikuports/pull/9008
No more issues playing midi (sound), this closes the track ticket also.
