### ISSUE TITLE
[qt5] "\_" key in japanese layout is not working

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#4527]
Platform: Haiku hrev53693 gcc2hybrid
Version: 5.14.0-1

When text field is focused, pressing "\_" key in japanese layout (most right bottom key) have no effect. This key work in native applications.

**Comment by diversys** [comment]
Please move it to this issue tracker https://github.com/threedeyes/qthaikuplugins/issues

**Comment by diversys** [comment]
Done in https://github.com/threedeyes/qthaikuplugins/issues/12
