### ISSUE TITLE
[scintilla] improve drag&drop support

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#4530]
Version: 4.2.0.

Currently scintilla don't mark drop position and drop position is wrong. I fixed that.

**Comment by X547** [comment]
[0001-fix-text-drag-drop.patch.txt](https://github.com/haikuports/haikuports/files/4035848/0001-fix-text-drag-drop.patch.txt)

**Comment by diversys** [comment]
Could you create a PR instead?

**Comment by X547** [comment]
It seems that scintilla is hosted on Sourceforge and mercurial repository. I do now know how to make pull requests there.

**Comment by diversys** [comment]
I mean just add the patch to haikuports.

**Comment by X547** [comment]
Version 2:
[0001-fix-text-drag-drop.patch.txt](https://github.com/haikuports/haikuports/files/4035908/0001-fix-text-drag-drop.patch.txt)

**Comment by X547** [comment]
> I mean just add the patch to haikuports.

Do you mean patchset mechanism of recipe?

**Comment by return** [comment]
@X547
You can bump the revision, add in your new patch into the patchset and then submit a PR for us to review.

The recipe to edit is here:
https://github.com/haikuports/haikuports/blob/master/x11-libs/scintilla/scintilla-4.2.0.recipe

**Comment by X547** [comment]
Done:https://github.com/haikuports/haikuports/pull/4531.
