### ISSUE TITLE
Octave is broken

### ISSUE THREAD

**Issue by iam-git** [haikuports/haikuports#4538]
Octave is broken on latest Haiku revs (or at least on my hrev53658, Octave was worked before).

this is an output:
runtime_loader: /boot/system/lib/liboctave.so.4.0.0: Could not resolve symbol 'zgetri_'
resolve symbol "zgetri_" returned: -2147478780
runtime_loader: /boot/system/lib/liboctave.so.4.0.0: Troubles relocating: Symbol not found

**Comment by extrowerk** [comment]
"zgetri_" Comes from lapack which was udated recently. The Octave tecie needs a revbump probably.

**Comment by korli** [comment]
but octave recipe hasn't lapack enabled: https://github.com/haikuports/haikuports/blob/master/sci-mathematics/octave/octave-4.2.1.recipe#L84

**Comment by extrowerk** [comment]
Maybe openblas then?

-- Z.

2020.01.10. dátummal, 12:14 időpontban Jérôme Duval <notifications@github.com> írta:
