### ISSUE TITLE
imagemagick: unit test failure

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4539]
cd /boot/home/test;convert file.pdf outputfile.jpg does not run
(reported by Lelldorin1)

**Comment by extrowerk** [comment]
Works on 64 bit.
Version: ImageMagick 6.9.10-62 Q16 x86_64 2019-08-28 https://imagemagick.org
imagemagick-6.9.10.62-1-x86_64.hpkg

**Comment by kenmays** [comment]
Fails on x86_gcc2 with unresolved symbol 'jbig2_ctx_new'. Tested: 6.9.10.62-1-x86_gcc2.

**Comment by kenmays** [comment]
Duplicates #4545. Consolidating.
