### ISSUE TITLE
Update Haiku's GL swpipe driver for Mesa 20.x

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4540]
Haiku maintains a generic OpenGL driver wrapper (i.e. HGL software pipe (i.e. swpipe)) for Mesa's Gallium llvmpipe software rasterizer.  Mesa's Gallium llvmpipe driver is multithreaded taking advantage of multiple CPU cores (up to 8 at this time). It's the fastest OpenGL software rasterizer for Mesa. 

The goal of this project is to update the HGL swpipe driver wrapper code for the Mesa 20.x llvmpipe driver release and fix different implementation problems related to OpenGL 3.3 context creation. 

The Mesa development team provides driver documentation for the llvmpipe software rasterizer. 

The Haiku development team provides driver support, documentation, and maintenance for the HGL swpipe driver wrapper. 

Homepage: https://www.mesa3d.org/

Mentors: @kallisti5, @X547 (aka X512)

**Comment by X547** [comment]
I tried to adjust HGL code for Mesa 19.3.2, but test application freeze in src/mesa/state_tracker/st_manager.c:572 (st_framebuffer_iface_insert: simple_mtx_lock(&smPriv->st_mutex);) for now. It seems that internal interfaces of Mesa was changed comparing with 17.1.10. OSMesa implementation can be used as reference for adjusting.

Also does it OK that 2 group of threads for each CPU are created? For 17.1.10 only 1 group was created. First group thread entry is thread_function and thread name is "llvmpipe-<number>", Second group thread entry is lp_cs_tpool_worker and has no name.

**Comment by X547** [comment]
> The goal of this project is to update the HGL swpipe driver wrapper code for the Mesa 19.x llvmpipe driver release and fix different implementation problems related to OpenGL 3.3 context creation.

When OSMesa interface is used, only OpenGL 3.1 version is avalible:
{{{
GL_VENDOR: VMware, Inc.
GL_RENDERER: llvmpipe (LLVM 9.0.1, 128 bits)
GL_VERSION: 3.1 Mesa 19.3.2
GL_SHADING_LANGUAGE_VERSION: 1.40
}}}
Is it possible to use higher OpenGL version with software renderer? Blender 2.8 require OpenGL 3.3 to run.

**Comment by kenmays** [comment]
Here is my output setup on Haiku R1B1 with OpenGL 4.5 env overrides:
> GL_VERSION: 4.5 Mesa 17.1.10
> GL_RENDERER: Gallium 0.4 on llvmpipe (LLVM 7.0, 128 bits)
> GL_VENDOR: VMware, Inc.
> GL_EXTENSIONS: GL_ARB_multisample ... GL_MESA_shader_integer_functions 
> GL_SHADING_LANGUAGE_VERSION = 4.50
> GLU_VERSION: 1.3
> GLU_EXTENSIONS: GLU_EXT_nurbs_tessellator GLU_EXT_object_space_tess 
> GLUT_API_VERSION: 5
> GLUT_XLIB_IMPLEMENTATION: 15

Have a script run your programs with the env overrides for testing.

I did this for my Blender 2.80 and GoDot 3.1.1 builds back in Nov 2019.

**Comment by kenmays** [comment]
NOTE: The Progress with Mesa 19.3.3/Blender 2.81a on Haiku - https://discuss.haiku-os.org/t/blender-2-81-is-working-on-haiku/9235

**Comment by X547** [comment]
My current work: https://github.com/haikuports/haikuports/pull/4738.

**Comment by kenmays** [comment]
Mesa 20.0.0 - verified major unit tests PASSED with recent Mesa patches on Haiku R1B1.

**Comment by kenmays** [comment]
Bumped to Mesa 20.0.1 on on Haiku R1B1. No major issues.

**Comment by kenmays** [comment]
Bumped to Mesa 20.0.2 on Haiku R1B1. No major issues. Build strategy for Haiku:
libdrm-2.4.100 - w-i-p
mesa 20.0.2 - Needs HGL driver update, passes unit testing.
blender 2.82 - done
llvm9-9.0.1-2 - done

**Comment by kenmays** [comment]
Resolved. See: https://github.com/haikuports/haikuports/pull/5792
