### ISSUE TITLE
ghostscript error

### ISSUE THREAD

**Issue by lelldorin** [haikuports/haikuports#4545]
by testing converting pdf to jpg i see that gs have a problem:

Sa. Jan. 11 | 17:36:27:gs
runtime_loader: /boot/system/bin/gs: Could not resolve symbol 'jbig2_ctx_new'
resolve symbol "jbig2_ctx_new" returned: -2147478780
runtime_loader: /boot/system/bin/gs: Troubles relocating: Symbol not found

Haiku 32Bit hrev52295+132 x86_gcc2

**Comment by kenmays** [comment]
Package with issue: ghostscript_gpl_x86-9.26-3-x86_gcc2

**Comment by kenmays** [comment]
ghostscript_gpl_x86-9.50-1 package build needed.
