### ISSUE TITLE
yab.recipe

### ISSUE THREAD

**Issue by lelldorin** [haikuports/haikuports#4546]
I think it sounds not good and make the work of Jan Bungeroth sade to say that he does only does "yab improvements". yab is build out of yabasic with api command and renamed from "yabasic" to "yab", so it need to be "2006-2009 Jan Bungeroth (yab)"

**Comment by korli** [comment]
Pull Request?

**Comment by bbjimmy** [comment]
I agree, it should say "yab" instead of "yab improvements." This will need to be changed in the yab source as well.

**Comment by Begasus** [comment]
1.7.6 is from 2019, so 2013-2018 Jim Saxton (yab improvements) should be updated too

**Comment by lorglas** [comment]
Can be closed, because it was fixes with issue #4913

**Comment by Begasus** [comment]
Thanks for the contributions, this can be closed now :)
