### ISSUE TITLE
Find a working download link for fheroes2

### ISSUE THREAD

**Issue by alwayslivid** [haikuports/haikuports#4576]
The [fheroes2](https://github.com/haikuports/haikuports/commit/31d3edcf487fc9332f878cabe312f5ad309b5326) recipe was recently disabled, after it was discovered that the `SOURCE_URI` of the `r3279` release is not valid anymore.

The link needs to get replaced with a link that actually works and the recipe needs to be modified accordingly.

**Comment by pulkomandy** [comment]
The link still works fine for me.

https://sourceforge.net/code-snapshots/svn/f/fh/fheroes2/code/fheroes2-code-r3279-trunk.zip

**Comment by pulkomandy** [comment]
But maybe we could update to the "enhanced" version from github:

https://github.com/ciplogic/fheroes2enh/releases

**Comment by Begasus** [comment]
There's also https://github.com/ihhub/fheroes2 (haven't checked the difference between the both)

**Comment by Begasus** [comment]
> The link still works fine for me.
> 
> https://sourceforge.net/code-snapshots/svn/f/fh/fheroes2/code/fheroes2-code-r3279-trunk.zip

Tried earlier (with no changes to the recipe) and it failed to download it?

**Comment by alwayslivid** [comment]
I had my own issues with downloading the sources from that link myself in the recipe itself. (404 Not Found)

I'd normally ask whether there are any redirects that HaikuPorter may not be able to handle, but I took it upon myself and made sure to check what happens-- there's only a simple GET request that just transfers the ZIP file without anything that looks too complicated for the circumstances here. 

So yeah, it does look solid, should we test and re-enable the recipe for the time being?

**Comment by pulkomandy** [comment]
Sourceforge downloads are sometiñes unreliable. So if this happens again be sure to wait a few hours and try again, just in case.

**Comment by alwayslivid** [comment]
> Sourceforge downloads are sometimes unreliable.

Perhaps, it would be a good idea to keep the issue up, just in case there's possibly a better alternative way of obtaining the source out there.

**Comment by korli** [comment]
The fallback ports-mirror dot haiku-os.org should handle this case nicely anyway.
