### ISSUE TITLE
Avidemux: Filter windows can't be focused

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#4636]
If you want to add a filter to the video, like "Contrast", its configuration window opens behind the "Video Filter Manager" window and cannot be focused. All dials and buttons are dead and all you can do is click the close widget in the window tab to close it.

**Comment by threedeyes** [comment]
Hmm. Modality inheritance bug in QPA.

**Comment by diversys** [comment]
Sounds a lot like LibreOffice's File->Remote Files->SSH bug.

**Comment by threedeyes** [comment]
Fixed in https://github.com/haikuports/haikuports/commit/38feef0bbd2ea377cac161b4d863e0604410e249
