### ISSUE TITLE
opensound: update to 4.2 build2019

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#4644]
Opensound made a new release. We should update our port, and see about upstreaming our patches if not done already.

**Comment by diversys** [comment]
New release doesn't include anything apart from compatibility fixes with new Linux kernel.
You can see history here https://sourceforge.net/p/opensound/git/ci/master/tree/

**Comment by waddlesplash** [comment]
Well, then we don't need to do this.
