### ISSUE TITLE
Port Samba 4.x to Haiku 

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4645]
GOAL: Provide SMB1->SMB3 file-sharing support on Haiku. 

Ref: https://github.com/haikuports/haikuports/pull/1199

Recent SRC: https://download.samba.org/pub/samba/stable/samba-4.11.5.tar.gz

**Comment by extrowerk** [comment]
Notes: FuseSMB needs to be adjusted to smb4, as they are incompatible.

**Comment by extrowerk** [comment]
If somebody ewant to mess with it: https://github.com/extrowerk/haikuports/commit/7a3aca3ca8c96fb5f5ae8bc37ce62bd66a342d0f

**Comment by kenmays** [comment]
NOTE: This was mentioned by developer as having some remaining issues - but already ported. Retracting my request.
W-I-P by @juafromspace

**Comment by volo-droid** [comment]
@kenmays it makes to reopen this ticket, as Samba 4 hasn't been ever ported. @juafromspace didn't create a PR, and they are not active on GitHub overall from the end of 2017.

**Comment by kenmays** [comment]
@volo-droid - Ok.

**Comment by kenmays** [comment]
@volo-droid - Recipe created. Migrating this to: https://github.com/haikuports/haikuports/pull/5965
