### ISSUE TITLE
runtime_loader: haikuporter issues with libcurl and libssl after pkgman update

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4659]
Haiku R1B1: Issues with haikuporter after pkgman update on 26-Jan: 

> Warning: failure creating the build package: runtime_loader: /boot/system/lib/libssl.so.1.0.0: No version information available (required by /boot/system/lib/libcurl.so.4.6.0)
> Warning: runtime_loader: /boot/system/lib/libssl.so.1.0.0: No version information available (required by /boot/system/lib/libcurl.so.4.6.0)
> Warning: runtime_loader: /boot/system/lib/libssl.so.1.0.0: No version information available (required by /boot/system/lib/libcurl.so.4.6.0)
> Warning: runtime_loader: /boot/system/lib/libcrypto.so.1.0.0: No version information available (required by /boot/system/lib/libcurl.so.4.6.0)
> Warning: **runtime_loader: /boot/system/lib/libcurl.so.4.6.0: Could not resolve symbol 'SSL_CTX_use_PrivateKey_file**'
> Warning: **resolve symbol "SSL_CTX_use_PrivateKey_file" returned: -2147478780**
> Warning: runtime_loader: /boot/system/lib/libcurl.so.4.6.0: Troubles relocating: Symbol not found)

**Comment by kenmays** [comment]
See: curl-7.68.0-1-x86_64.hpkg

**Comment by korli** [comment]
what do you mean exactly by "haikuporter runtime_loader"?

**Comment by kenmays** [comment]
I reinstalled just Haiku R1B1 x86_64 and the new haikuporter 1.2.3. Just did 'haikuporter -S clementine --get-dependencies --no-source-packages'... the error was generated once the src/dependencies were downloaded/installed.

**Comment by kenmays** [comment]
1. Reformatted disk.
2. Installed Haiku R1B1 x86_64 and haikuporter 1.2.3-2.
3. pkgman full-sync
4. haikuporter -S clementine --get-dependencies --no-source-packages

RESULT: No issues as of Feb 9, 2020. Closing ticket.
