### ISSUE TITLE
curl: unit test failures

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4661]
curl-7.68.0-1 x86_64 - Segment violation issues with these test cases:

TESTDONE: 1015 tests out of 1019 reported OK: 99%
TESTFAIL: These test cases failed: 116 1592 (20, 507 for review)
TESTDONE: 1290 tests were considered during 966 seconds.

NOTE: curl 7.67 comparison -
TESTFAIL: These test cases failed: 116

**Comment by korli** [comment]
> curl-7.68.0-1 x86_64 - Segment violation issues with these test cases:

Why do you think there are segment violation issues?

**Comment by kenmays** [comment]
Mentions it in resulting test reports on Haiku R1B1. Nothing on your end?

**Comment by korli** [comment]
Test cases can use abort() which triggers the Debugger, therefore reports are not only generated for segmentation faults. Please check what they say, then adjust the bug description.

**Comment by kenmays** [comment]
Both packages seem OK and similar issue (both, 99% pass). Closing.
