### ISSUE TITLE
Get Kerberos running on Haiku

### ISSUE THREAD

**Issue by n0toose** [haikuports/haikuports#4664]
Here's a relevant [Wikipedia article](https://en.wikipedia.org/wiki/Kerberos_(protocol)) which explains what the Kerberos protocol is in detail.

The homepage of the project can be found here: https://web.mit.edu/kerberos/krb5-latest/

This is necessary for porting certain very useful applications that depend on it with full functionality.

**Comment by extrowerk** [comment]
This is not an easy task. But what are the useful applications what depends on krb?

**Comment by alwayslivid** [comment]
> This is not an easy task. But what are the useful applications which depends on krb?

In case that I accidentally misrepresented the urgency of such a port, I'll reiterate that Kerberos is an optional dependency for the vast majority of programs that use it.

`dotnet-runtime` contains optional support for it (which is listed as a requirement on Linux distributions, but not on BSD-like systems IIRC), as well as `dovecot`, `wireshark`,  `freeradius` and the relevant [Python packages](https://pypi.org/project/pykerberos/). The aforementioned software (apart from `wireshark`) has not been ported over to Haiku, but I figured that it's a cause that's worth exploring while I was looking into `dotnet-runtime`.

Haiku does not currently implement a password mechanism, so the possible uses that could be of advantage to the user would be limited to tools like `kgetcred`, SSH over Kerberos (and the use of Kerberos as alternative means of secure authentication apart from SSH keys), as well as other means of remote administration (e.g. NTP, Samba, AD). It would be also kind of good, in the sense that there's also some ongoing progression with the support for the U2F protocol; some further versatility on top of additional versatility wouldn't hurt.

**Comment by jonx** [comment]
@AlwaysLivid are you talking about the dotnet-runtime requirements for [FreeBSD](https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/freebsd-requirements.md)?
I was just looking into that as well (just curious for now).

Correct me if I'm wrong but it seems both lttng-ust and krb5 would be missing from that list:
- cmake
- autoconf
- automake
- libtool
- icu
- libunwind
- lttng-ust
- krb5
- openssl (optional)

Is there a given place where people interested in getting dotnet-core on Haiku are talking?

**Comment by AlwaysLivid** [comment]
As far as I'm aware, there isn't, @jonx. But hey, if we got dotnet running, maybe we could get osu!Lazer running on Haiku eventually as well!

**Comment by jonx** [comment]
I never heard of osu. They seem to have a really nice cross platform 2D game engine.

@AlwaysLivid have you tried to compile anything around dotnet? I'm a fair dotnet developer but that's about it. My experience with Haiku is close to zéro, sooo.

Where can we take this conversation further?

**Comment by jonx** [comment]
Now that I took a good look, I think that taking care of this port is out of reach for my capabilities.

I struggle already with building dotnet-cor under Ubuntu (through WSL2). I get "Warning: File `filename' has modification time in the future" kind of errors.

**Comment by trungnt2910** [comment]
Did #7009 solve this issue? I don't come from a security background so I don't know what Kerberos really is and what it does, but when porting it I ensured that all the built-in tests passed.

**Comment by korli** [comment]
> Did #7009 solve this issue? I don't come from a security background so I don't know what Kerberos really is and what it does, but when porting it I ensured that all the built-in tests passed.

I suppose trying to build curl with kerberos support would be a good check. Only to check that the headers are correctly located.

**Comment by trungnt2910** [comment]
.NET builds correctly with this package, so I guess there aren't any header issues.

**Comment by korli** [comment]
OK!
