### ISSUE TITLE
audacity: build issue on x86

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4695]
Tested on hrev53819 x86_gcc2 w/ audacity-2.1.2-3.
[audacity_log_gcc2.txt](https://github.com/haikuports/haikuports/files/4162398/audacity_log_gcc2.txt)

**Comment by return** [comment]
The logs clearly say that the Audacity FileDialog implementation is missing for the wxqt port. See this: https://github.com/audacity/audacity/tree/master/lib-src/FileDialog

They have imported the FileDialog implementation from WxWidgets (3.0.2) and modified it for each GUI platform, for example gtk [0]. Perhaps you could try doing the same for the wxqt port?

[0] https://github.com/audacity/audacity/blob/master/lib-src/FileDialog/gtk/FileDialogPrivate.cpp#L2
