### ISSUE TITLE
OpenMW mouse behavior makes it unusable

### ISSUE THREAD

**Issue by tthoms** [haikuports/haikuports#4702]
the slightest pressure on the mouse caused the camera to point up and spin around.  At times, I can get the perspective to level, but it only lasts for a moment.

**Comment by tthoms** [comment]
hrev52295+132 x86_gcc2 running in Virtualbox 6.1.2_Debian r135662

**Comment by extrowerk** [comment]
Probably the good-old mouse handling bug in SDL. Let's ask @threedeyes .

**Comment by Crestwave** [comment]
Are you using seamless mode instead of mouse capture?

**Comment by waddlesplash** [comment]
No reply; other bugs were already fixed.
