### ISSUE TITLE
WonderBrush build fails, stuck on v2.1.2-5 in HaikuDepot

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#4708]
(For 32bit) WonderBrush is stuck in HaikuDepot at v2.1.2-5, though the recipe is at -9 already.

Looks like the build failure is quite old, -6 was from July 3rd 2019.
The build failure has a ticket at https://github.com/stippi/WonderBrush-v2/issues/17.

**Comment by korli** [comment]
Should be fixed.

**Comment by kenmays** [comment]
@humdingerb - wonderbrush 2.1.2-9 (x86_gcc2) package built and works great.

**Comment by humdingerb** [comment]
@korli: can thefix be upstreamed to https://github.com/stippi/WonderBrush-v2 ?
