### ISSUE TITLE
xmoto build but fails to start (fatal exeption: Unable to get xmDb version:)

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#4710]

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/3894

**Comment by threedeyes** [comment]
Fixed in https://github.com/haikuports/haikuports/commit/c163de3ecd5570d7b4c5e64156643bb7c1d5467a

Update and try again please.

**Comment by Begasus** [comment]
Just grabbed https://eu.hpkg.haiku-os.org/haikuports/master/repository/x86_gcc2/current/packages/xmoto_x86-0.5.12-3-x86_gcc2.hpkg ... installed ... same problem here

**Comment by diversys** [comment]
Same Unable to get xmDb version?

**Comment by Begasus** [comment]
Same here, after an updated libSDL it's working, closing this one :+1:
