### ISSUE TITLE
Write recipe for Gerbera

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4719]
Gerbera is a UPnP media server which allows you to stream your digital media through your home network and consume it on a variety of UPnP compatible devices. Gerbera is based on MediaTomb 0.12.1.

NOTE: MediaTomb 0.12.1 was ported to Haiku.

URL: https://github.com/gerbera/gerbera

> Features
> 
>     Browse and playback your media via your network on all kinds of devices.
>     Web UI with a tree view of the database and the file system, allowing to add/remove/edit/browse your media
>     Metadata extraction from MP3, OGG, AAC, M4A, FLAC, JPG (and many more!) files.
>     Media thumbnail support
>     Highly flexible media format transcoding via plugins / scripts
>     Automatic directory rescans (timed, inotify)
>     User defined server layout based on extracted metadata
>     Supports last.fm scrobbing
>     On the fly video thumbnail generation
>     Support for external URLs (create links to internet content and serve them via UPnP to your renderer)
>     Runs on Linux, BSD, Mac OS X, and more!
>     Runs on x86, ARM, MIPS, and more!

**Comment by extrowerk** [comment]
I dont really see why we need an alternative to mediatomb, i think one should be enough. Instead porting all the things (TM), we should try to create an network preferences addon to control an existing one to make it easier discoverable and easier to use for the users.

Nevertheless if somebody want to port gerbera, should port its dependencies too: fmtlib and spdlog.

**Comment by diversys** [comment]
_Gerbera is proudly built upon MediaTomb 0.12.1 continuing that projects great legacy._
Is MediaTomb still in development?

**Comment by Begasus** [comment]
Looks like it's working for me? (mediatomb)
![MediaTomb_Connection](https://user-images.githubusercontent.com/16057090/74372908-c5354280-4ddb-11ea-9310-0b3df48f0a28.png)

**Comment by kenmays** [comment]
@diversys - No. MediaTomb development is being continued by the Gerbera project.  
@Begasus - If it works fine,  I'll close this one per extrowerk's suggestion.

**Comment by extrowerk** [comment]
I did not suggested that. if mediathomb deprecated we should have a supported product, if there is any.
Anyway.

**Comment by Begasus** [comment]
Building Gerbera worked (32bit), trying to launch it fails however (same issue reported here https://github.com/haikuports/haikuports/issues/4722)

**Comment by Begasus** [comment]
Recipe created https://github.com/haikuports/haikuports/pull/4734
Not functional (see other issue in regards to mediatomb)
Also, it searches for the config.xml in $HOME ... wip
