### ISSUE TITLE
SuperPrefs: Recipe has been updated but not the package in HD

### ISSUE THREAD

**Issue by Briseur** [haikuports/haikuports#4720]
Though recipe has been updated in 2018, package in HaikuDepot has not.
Since introduction of input setting in nightlies the app needs an update, so perhaps it can wait.
In fact, I ended here because I wanted to open an issue about ghost mouse and keyboard settings and given URL lead to limbo...
I found the new URL in the recipe commit

**Comment by Begasus** [comment]
Package in the depot is uptodate, think this has been fixed a while ago, closing.
