### ISSUE TITLE
True color is not supporting in Haiku ncurses

### ISSUE THREAD

**Issue by kloun** [haikuports/haikuports#4724]
![Снимок экрана от 2020-02-16 12-13-03](https://user-images.githubusercontent.com/1122903/74602110-91496e00-50b6-11ea-9036-b95b0a346d94.png)
where is this problem?

**Comment by diversys** [comment]
Most likely in Haiku's Terminal, please report here https://dev.haiku-os.org/newticket.
There is QPutty in the depot, you can check if it works there.

**Comment by waddlesplash** [comment]
24-bit true color is now supported by Terminal.
