### ISSUE TITLE
SCons header checks broken after scons-3.1.2 update.

### ISSUE THREAD

**Issue by kallisti5** [haikuports/haikuports#4729]
As seen in #4726, using the SCons "CheckCHeader" tool is broken on x86_gcc2.

Example Usage: https://gitlab.com/kallisti5/libuuid/-/blob/master/SConstruct#L96

```"No such file or directory: 'sh': 'sh'"```

**Comment by kallisti5** [comment]
![Screen Shot 2020-02-17 at 8 03 58 AM](https://user-images.githubusercontent.com/100110/74660884-952fcb80-515c-11ea-97b4-7e5f9d9d27a1.png)

**Comment by kallisti5** [comment]
Actually... both x86_64 and x86_gcc2 fail now :-|

```
x86_gcc2:   scons-3.1.2-1
x86_64: scons-3.1.2-1
```

@korli you're actually suspect here :-)

https://github.com/haikuports/haikuports/commit/fa27b298bfc41361dc0353c94fff3b82883f207c

**Comment by kallisti5** [comment]
I downgraded SCons to 2.5.1-3, and cleared the .scons* caches.  libuuid compiles successfully. 

The scons-3.1.2-1 update is confirmed as the cause.

**Comment by korli** [comment]
Who can better python3, please have a look at this issue.

**Comment by kallisti5** [comment]
lol, I suck at python.   My haikuporter work was based on mmlr's original code :-)

**Comment by korli** [comment]
fixed in ceb01b98c03d1b3ca5cd3cc4cac744d926843fdd
