### ISSUE TITLE
Port pciaccess

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#4746]
pciaccess is a dependency of libdrm. It provides access to PCI devices from userland.

Repository: https://gitlab.freedesktop.org/xorg/lib/libpciaccess.

Note that libpciaccess is using autotools with custom additions. I can't build pciaccess with autotools. I managed to build it with my simple Meson scripts.

**Comment by Begasus** [comment]
Doesn't this one work? https://github.com/haikuports/haikuports/blob/c2a214e6473117adfdbf84d0f792341b30e1bbd7/x11-libs/libpciaccess/libpciaccess-0.14.recipe

**Comment by X547** [comment]
Sorry, I missed that. Existing libpciaccess is fine.

**Comment by Begasus** [comment]
> Sorry, I missed that. Existing libpciaccess is fine.

No problem, maybe an update (I saw that they are at version 0.16 atm)?
