### ISSUE TITLE
blender: missing symbol error on x86-64

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4750]
blender-2.79b-15-x86_64.hpkg on Haiku R1B1 x86_64 during program load.
![blender_haiku_debug-cocobean](https://user-images.githubusercontent.com/5168719/75180422-063d2900-56f1-11ea-9fd8-cae607ae2b26.jpg)

**Comment by kenmays** [comment]
Fixed for LLVM 9.0.,1. Builds.
Some segment violation issues with boost:detail:set_tss_data (tss_cleanup_function)

**Comment by kenmays** [comment]
@X547 - Small bugs rebuilding blender 2.79b-15. Working on blender 2.82 on Haiku R1B1. I'm going to focus on debugging these this week and await Mesa 19.3.5 stable release.

Test image:
![Miku_blender-2 82-haiku_cocobean_4](https://user-images.githubusercontent.com/5168719/75189203-8e77fa00-5702-11ea-863f-34b993b36d12.jpg)

**Comment by X547** [comment]
Blender need this SDL2 patches to work properly: https://github.com/haikuports/haikuports/pull/4535.

This model is made for pre 2.80 Blender, it is not fully compatible with Blender 2.80+.

**Comment by kenmays** [comment]
@korli - blender 2.79b-16 fixes the build issue on Haiku R1B1 x86_64.
PR: https://github.com/haikuports/haikuports/pull/4666
