### ISSUE TITLE
protrekkr: Update SOURCE_URI

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#4754]
![haiku-protrekkr-2 5 4_cocobean](https://user-images.githubusercontent.com/5168719/75392195-59a1a980-58a0-11ea-8659-6871c6f04bb1.png)

Built and tested Protrekkr. No major issues on R1B1, hrev53903-53919.

Update to SOURCE_URI="https://github.com/falkTX/protrekkr/archive/0b96ba56379eb179423e9dcbec31a08bf0326c9f.tar.gz"

`Main features:

- 16 multi-notes tracks (with 256 virtual channels).
- Samples editor (can load up to 64 bits stereo samples).
- Patterns based tracker style sequencer.
- Synthesizer with custom waveforms support.
- Samples loop editor.
- 2 303s units.
- Cubic spline interpolation.
- Wav files import/export.
- 16 or 32 bits wav rendering.
- Multi effects engine with reverb, distortion, filters, delay, EQs, flanger, etc...
- Fully customizable 10 combs reverb.
- Protracker .mod files import.
- Samples compressor handling Gsm/Mp3/TrueSpeech/ADPCM/8 Bit (not on Linux or Mac OS X yet).
- And maybe more...
`

**Comment by Begasus** [comment]
Crashes on gcc2h (_x86) hrev54088

**Comment by kenmays** [comment]
Updated PR. I have this on R1B1-133 and hrev54131 x86. Works fine from GUI and went through all the included songs without any major issues.

**Comment by kenmays** [comment]
@waddlesplash @Begasus @pulkomandy - Remaining issue was launching app from the Deskbar. GUI/terminal app launches are fine. Will put that in separate ticket. Otherwise, good to go.
