### ISSUE TITLE
Invalid SOURCE_URI for ukijorgfonts

### ISSUE THREAD

**Issue by AlwaysLivid** [haikuports/haikuports#4760]
I'm opening this issue, because the main mirror for [ukijorgfonts](media-fonts/ukijorgfonts/ukijorgfonts-1.0.recipe) seems to be down as of the time being, which is effectively breaking the recipe, and I'm not quite sure as to where a proper alternative mirror could be found.

However, the homepage seems to be up-- the Uyghur Computer Science Association seems to be self-hosting individual `.ttf` files, but there's no `.zip` version that just bundles all of them.

**Comment by kenmays** [comment]
@AlwaysLivid - You could use: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/ukijorgfonts/ukijorgfonts.zip

**Comment by AlwaysLivid** [comment]
> @AlwaysLivid - You could use: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/ukijorgfonts/ukijorgfonts.zip

Will look into it, thank you.
