### ISSUE TITLE
Port lld-link

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#4786]
lld-link is LLVM project linker and alternative to GNU ld. It is more efficient that GNU ld and allows linking PE executables for UEFI, eliminating requirements of linker scripts and PE stub for haiku_loader.efi.

**Comment by X547** [comment]
lld-link can be used to produce native PE UEFI executables: https://dvdhrm.github.io/2019/01/31/goodbye-gnuefi/.

**Comment by X547** [comment]
lld-link is compiled successfully with
```
cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS=lld -DCMAKE_INSTALL_PREFIX=$PWD/install ../llvm -G ninja
ninja install
```
Compiled result seems working.

**Comment by return** [comment]
Does lld have any specific unit-tests defined in the LLVM test-suite?

I think it would be worth running them to check to see if lld actually works properly in Haiku.

**Comment by X547** [comment]
I don't know about unit tests.

I managed to link and run EFI applications with lld-link. lld-link may need adjustments for linking regular Haiku applications because ELF modules used by Haiku are a bit different from Linux and FreeBSD. lld-link is still useful even if it can't link Haiku applications for now.

Currently clang can't use lld-link for Haiku target, it always use gcc for linker, -fuse-ld don't work. Haiku target for clang need to be adjusted.

**Comment by X547** [comment]
Compared to gnu ld, lld-link also provides excellent debug messages:
{{{
lld-link: error: undefined symbol: atexit
>>> referenced by console.o:(__cxx_global_var_init)
>>> referenced by console.o:(__cxx_global_var_init.1)
>>> referenced by kernel_args.o:(__cxx_global_var_init)
>>> referenced by vfs.o:(__cxx_global_var_init)
>>> referenced by vfs.o:(__cxx_global_var_init.1)

lld-link: error: undefined symbol: operator delete(void*)
>>> referenced by console.o:(Console::~Console())
>>> referenced by devices.o:(EfiDevice::~EfiDevice())
>>> referenced by FileMapDisk.o:(FileMapDisk::~FileMapDisk())
>>> referenced by mmu.o:(platform_allocate_region)
>>> referenced by package_support.o:(PackageVolumeInfo::~PackageVolumeInfo())
>>> referenced by package_support.o:(PackageVolumeInfo::~PackageVolumeInfo())
>>> referenced by package_support.o:(PackageVolumeInfo::_AddState(char const*))
>>> referenced by package_support.o:(PackageVolumeInfo::LoadOldStates())
>>> referenced by partitions.o:(boot::Partition::~Partition())
>>> referenced by PathBlacklist.o:(PathBlacklist::MakeEmpty())
>>> referenced 9 more times
}}}
(Trying to build ARM haiku_loader by clang and lld-link.)
