### ISSUE TITLE
No input devices initialized in openal?

### ISSUE THREAD

**Issue by khallebal** [haikuports/haikuports#479]
Anyone could shed some light on this? i need to use the mic with openal in an app i'm porting.

Welcome to the Haiku shell.

~/Desktop> openal-info 
Available playback devices:
    Haiku Software
    No Output
Available capture devices:
    !!! none !!!
Default playback device: Haiku Software
Default capture device: 
ALC version: 1.1

*\* Info for device "Haiku Software" **
ALC version: 1.1
ALC extensions:
    ALC_ENUMERATE_ALL_EXT, ALC_ENUMERATION_EXT, ALC_EXT_CAPTURE,
    ALC_EXT_disconnect, ALC_EXT_EFX, ALC_EXT_thread_local_context
OpenAL vendor string: OpenAL Community
OpenAL renderer string: OpenAL Soft
OpenAL version string: 1.1 ALSOFT 1.13
OpenAL extensions:
    AL_EXT_DOUBLE, AL_EXT_EXPONENT_DISTANCE, AL_EXT_FLOAT32, AL_EXT_IMA4,
    AL_EXT_LINEAR_DISTANCE, AL_EXT_MCFORMATS, AL_EXT_MULAW,
    AL_EXT_MULAW_MCFORMATS, AL_EXT_OFFSET, AL_EXT_source_distance_model,
    AL_LOKI_quadriphonic, AL_SOFT_buffer_sub_data, AL_SOFT_loop_points
EFX version: 1.0
Max auxiliary sends: 1
Supported filters:
    Low-pass
Supported effects:
    EAX Reverb, Reverb, Echo, Ring Modulator
~/Desktop>

**Comment by mmuman** [comment]
I'm not sure audio input is implemented there...

Looking at:
https://github.com/haikuports/haikuports/blob/master/media-libs/openal/patches/openal-1.13.0.patchset

indeed HaikuOpenCapture() is just a stub.

**Comment by khallebal** [comment]
Unfortunately i don't have the skills nor the time to do it, i searched the bebook for something to start with i didn't find anything, it just to much work for a newbie like me, it'll take me a couple of months.
I guess i'm gonna have to give up on porting qtox too.

**Comment by khallebal** [comment]
Closing, fixed by @threedeyes [here](de3c36296f83eb9cabcad95789797b5e7ab7316f).
