### ISSUE TITLE
Package naming: "gnutls36" vs "gnutls3.6"

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#4794]
(Yes, I know there is no "gnutls36" package anymore, but I couldn't think of a better example ATM.)

Currently, we have a number of packages for which there is more than one version. The names of these packages have suffixes of the newer version; in this example, "3.6" (vs 2.x.) When writing the package name, we drop the ".". Is there any reason for this? I just tested building "openssl1.0" (instead of openssl10...) and it built and installed just fine.

Many Linux distributions seem to choose the latter format, and it has the advantage of not having a collision between "version 36" and "version 3.6". Thoughts?

**Comment by waddlesplash** [comment]
cc @korli, @pulkomandy, @alaviss.

**Comment by pulkomandy** [comment]
I think we just followed what debian does for libpng (they have a libpng16 package).

**Comment by X547** [comment]
I think that not using dot is a bad idea because number after dot can be more than 9. For example Blender 2.79. If 279 will be used, 2 interpretations are exist: 2.79 and 27.9.
