### ISSUE TITLE
Enable all availiable translations in LibreOffice

### ISSUE THREAD

**Issue by iam-git** [haikuports/haikuports#4803]
*kind of discussion*

Why not to pack entire set of translations in LibreOffice (currently only small subset of selected languages packed)? Warring about people will lost in long list of languages they're never heard? Haiku itself offers plenty of delicate flavours in locale settings. And even Haiku's user guide is translated to measurable amount of languages. I build desired package for me, but average single user will not be able (or happy) to build LibreOffice by himself for sure.

**Comment by diversys** [comment]
Done in adfc6f5.
