### ISSUE TITLE
Build Python with -fno-semantic-interposition

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#4806]
> This has the effect of speeding up the interpreter up to 27%, depending on the workload

https://src.fedoraproject.org/rpms/python3/pull-request/151

**Comment by waddlesplash** [comment]
We could probably enable this for Haiku's kernel (and maybe app_server also.)

**Comment by pulkomandy** [comment]
19 mars 2020 14:55 "waddlesplash" <notifications@github.com> a écrit:

> We could probably enable this for Haiku's kernel (and maybe app_server also.)

I would consider it even for libbe (not libroot because we use libroot_debug).
I think not allowing the user to override symbols there is a feature?

-- 
Adrien.

**Comment by X547** [comment]
> not libroot because we use libroot_debug

Does semantic interposition is actually needed for libroot_debug? Can it just replace libroot and cause not load it at all? Maybe setting SO_NAME in dynamic section for libroot_debug to "libroot.so" helps.

Maybe -fno-semantic-interposition flag can be included in compiler by default.

**Comment by waddlesplash** [comment]
No, there are a variety of symbols in libroot that POSIX says should/must be overrideable, so we cannot use it for libroot for sure.

**Comment by X547** [comment]
> No, there are a variety of symbols in libroot that POSIX says should/must be overrideable, so we cannot use it for libroot for sure.

So for any other Haiku libraries (libbe.so, libtracker.so etc.) and executable using -fno-semantic-interposition is fine?

**Comment by korli** [comment]
This will be handled upstream with python 3.10.

**Comment by diversys** [comment]
Should we move it to Haiku's Trac?

**Comment by korli** [comment]
Sure, though the idea sounds something to discuss and test before actually implementing.
