### ISSUE TITLE
qBittorent no longer start after an update

### ISSUE THREAD

**Issue by AlienSoldier2** [haikuports/haikuports#4815]
haiku update is 53992.  There was a change to QT that i remember in the progress update but the QT browser still work.  When launched from terminal i get:
terminate called after throwing an instance of 'boost::system::system_error'
  what():  context: malloc failure

**Comment by korli** [comment]
x86_64 or x86_gcc2? 
qbittorrent was rebuilt (with boost 1.69.0)
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/4172/builds/15717.log
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/3980/builds/34765.log

**Comment by AlienSoldier2** [comment]
x86_gcc2

**Comment by korli** [comment]
no crash report or stacktrace in syslog?

**Comment by AlienSoldier2** [comment]
no crash.  when i run it, only this add to the syslog after:
Last message repeated 1 time
KERN: slab memory manager: created area 0xf7801000 (476776)
KERN: acquire_advisory_lock(vnode = 0xf663e198, flock = 0x8221cefc, wait = no)

I deleted the conf file and because of this it show me the legal notice at start, so i can see the notice window and the icon register in the deskbar at that point (even if it say no window, i guess BAlert window does that?).  As it continue, when i click "i agree" the icon disapear from the deskbar and so is the process in process controler.

**Comment by diversys** [comment]
qbittorrent-4.2.1-3-x86_64.hpkg works here in hrev54010. However, it doesn't quit correctly, I have to press Ctrl+C twice to quit it, not sure if it's a new problem or not.

**Comment by AlienSoldier2** [comment]
diversys:  Some QT app are not always closing correctly.  In case of that one, are you sure it is not simply minimizing to the tray when you close it?  There is a setting to prevent that in the app.

I reverted it to 4.2.1-2 (4.2.1-3 is the one giving me trouble) and it now start normally.  When i launch software updater it does not mention me to update any main QT5 download so i guess it did not need to downgrade QT itself and the problem is self confined to the Qbittorent 4.2.1-3) package.

**Comment by AlienSoldier2** [comment]
qbittorrent_x86-4.2.5-1 still don't want to start on my 32bit install.

**Comment by AlienSoldier2** [comment]
And btw, reverting to 4.2.1-2 no longer work either

**Comment by AlienSoldier2** [comment]
Something weird that i found in /boot/system/package-links/qbittorrent_x86-4.2.5-1

If i desinstall qbittorrent and install it back, all the link there seem fine (none broken).  When i reboot and check again, only those two links are broken:
lib~libboost_system_x86
lib~libssl_x86

**Comment by AlienSoldier2** [comment]
qbittorrent_x86-4.2.5-1-x86_gcc2.hpkg installed and it still don't work on the 32bit rev i have (at this moment hrev54172)

**Comment by diversys** [comment]
Fixed in 7290646d4e245e45c2816720904f819b83aa490f.
