### ISSUE TITLE
Netsurf crash when clicking links on gcc2 haiku

### ISSUE THREAD

**Issue by AlienSoldier2** [haikuports/haikuports#4831]
reverting to 3.9.3 don't make the problem go away.

included syslog

according to: <waddlesplash> oh, it's using both variants of openssl, that's probably the issue

**Comment by waddlesplash** [comment]
Crash log: https://paste.centos.org/view/fa3ebaef

It's very odd that *both* OpenSSL versions are loaded; this seems likely to be the culprit?

**Comment by waddlesplash** [comment]
I looked through all the libraries in that list, and I can't figure out which one depends on the older OpenSSL. At least as far as I can see, all the revbumps of libraries in that list against the new SSL succeeded. So I guess this will need to be examined on a case by case basis?

**Comment by waddlesplash** [comment]
Should be fixed by CURL app rebuilds.
