### ISSUE TITLE
ffmpeg not convert to mp3

### ISSUE THREAD

**Issue by unarix** [haikuports/haikuports#4841]
Hello all; im trying to convert an ogg music file to mp3 (i do exactly the same as in my linux box) but ffmpeg in haiku, says that selection of encoder fails. I use x64 nightly build hrev54019.

command:
ffmpeg -i Lucy.ogg Lucy.mp3

error:
Automatic encoder selection failed for output stream #0:0. Default encoder for format mp3 (codec mp3) is probably disabled. Please choose an encoder manually.
Error selecting an encoder for stream 0:0

**Comment by diversys** [comment]
Should be fixed in 9417b417a.
