### ISSUE TITLE
Guitar, Git QT client have some bugs and lost control

### ISSUE THREAD

**Issue by skarmiglione** [haikuports/haikuports#4848]
Hello i love that app called guitar to download git repositorys but in haiku it have some bugs randomly, but one i can reproduce is that: when i click the clone button + github it make emerge a search window, but now i searh for example Haiku repo, then when i click over that repo it show me the clone window and lost all the control over the program, sometimes it work in other cases if i paste the url directly.

**Comment by extrowerk** [comment]
Please raise an issue at the guitar github site too, maybe this is a bug in Guitar itself.

**Comment by skarmiglione** [comment]
I did test on my linux setup and work very normal, that is why i came here first.

**Comment by extrowerk** [comment]
Which Guitar version does your linux ships?

**Comment by skarmiglione** [comment]
1.1.999 and haiku have 1.1.1

**Comment by extrowerk** [comment]
There is no 1.1.999, that must be a git master version. Would be good to know what the actual commit is.
In the meantime if you like adventures you could build and test Guitar master on Haiku.

**Comment by skarmiglione** [comment]
oh, well can try

**Comment by skarmiglione** [comment]
I get a kdl xD

**Comment by extrowerk** [comment]
Problem exists in the current git version too.
It seems you haven't created an issue at Guitar github site, please make one.
