### ISSUE TITLE
cherokee: incorrect directory structure in x86_64

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#4849]
Package: cherokee-1.2.104-1-x86_64

When attempt to start server following error will be displayed:
```
Could not find a Cherokee resource: /packages/cherokee-1.2.104-1/.self/bin/cherokee-worker-x86

You may need to reinstall the Web Server in order to sort out this issue. 
```
`-x86` suffix is not needed in x86_64 architecture.

**Comment by waddlesplash** [comment]
Cherokee looks pretty dead, IMHO we should just remove it.

**Comment by X547** [comment]
What are alternatives?

**Comment by waddlesplash** [comment]
Apache, Lighttpd, etc.?

Cherokee has not seen a release in 5 years, and no commits in multiple months. We should just delete the recipe.

**Comment by pulkomandy** [comment]
lighttpd is working (I use it for webkit test suite)

**Comment by waddlesplash** [comment]
Removed cherokee.
