### ISSUE TITLE
Switch universally to libjpeg-turbo

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#4873]
We currently ship both libjpeg and libjpeg-turbo. Most distributions (e.g. Fedora, Ubuntu) either only ship "turbo", or ship the original libjpeg for a very small set of applications that need v9, as turbo is compatible with v6-8 (they refuse to support v9, and explain their rationale here: https://libjpeg-turbo.org/About/Jpeg-9)

Our usage of both occasionally leads to conflicts, e.g. from IRC today:
> 1:55 PM <jmairboeck> waddlesplash: I have a conflict between poppler_devel and gd_devel; gd_devel depends on devel:libjpeg>=9.3.0 (which is provided by jpeg_devel) while all 3 versions of poppler_devel depend on devel:libjpeg>62.3.0 (which is provided by libjpeg_turbo_devel. What can be done about this?

So, I see no reason to keep libjpeg around, especially if it's going to support non-standardized features that have dubious value.

**Comment by waddlesplash** [comment]
It appears Firefox and Chrome also depend on libjpeg-turbo alone, also.

**Comment by Begasus** [comment]
This probably means a rewrite of all recipes using libjpeg to start using:
```
lib:libjpeg$secondaryArchSuffix >= 62
devel:libjpeg$secondaryArchSuffix >= 62
```

**Comment by waddlesplash** [comment]
No, you don't need to do that, as the recipes themselves could built with either libjpeg. HaikuPorter will add the right version dependency on the built package based on what it was built against, like anything else.

**Comment by Begasus** [comment]
There are still some recipes depending on libjpge >= 9, I'm guessing they would need a rewrite?

```
sci-libs/libgeotiff/libgeotiff-1.5.1.recipe
sci-visualization/gnuplot/gnuplot-5.2.5.recipe
media-libs/lcms/lcms-2.9.recipe
media-libs/libgphoto2/libgphoto2-2.5.23.recipe
dev-qt/wxqt/wxqt-3.1.3.recipe
app-admin/testdisk/testdisk-7.1.recipe
app-emulation/qemu/qemu-3.1.0.recipe
games-emulation/mame/mame-0.210.recipe
sci-libs/gdal/gdal-3.0.2.recipe
games-engines/openscenegraph/openscenegraph-3.6.3.recipe
```

**Comment by jmairboeck** [comment]
`gd_devel` (the package that originally triggered my problem) also depends on `devel:libjpeg>=9.3.0` and cannot be installed right now.

**Comment by waddlesplash** [comment]
gd does not depend on it in the recipe, but rather the build of gd failed after the switch to jpeg turbo (not because of jpeg turbo, I've lost the logs.)

**Comment by waddlesplash** [comment]
> There are still some recipes depending on libjpgeg >= 9, I'm guessing they would need a rewrite?

Yes, just removing the requirement and then rebuilding should be enough.
