### ISSUE TITLE
Vim: gVim crashes when entering an ex command

### ISSUE THREAD

**Issue by bitigchi** [haikuports/haikuports#4899]
If gVim is compiled with `big` features, it crashes upon `:version`. This is reproducible with the latest Vim version (8.2.~).

<details><summary>Crash output below:</summary>

Debug information for team /boot/system/bin/gvim (552):
CPU(s): 1x Intel Core™ i5-8259U
Memory: 1.95 GiB total, 298.12 MiB used
Haiku revision: hrev54064 Apr 19 2020 07:44:10 (x86_64)

Active Threads:
	thread 552: gvim (main)
	thread 557: w>[Adsız] - VIM 
	thread 558: team 552 debug task 
	thread 553: vim main() 
		state: Call (looper must be locked before proceeding
)

		Frame		IP			Function Name
		-----------------------------------------------
		00000000	0x20289ac1bf	_kern_debugger + 0x7 
			Disassembly:
				_kern_debugger:
				0x00000020289ac1b8:   48c7c0e1000000  mov $0xe1, %rax
				0x00000020289ac1bf:             0f05  syscall  <--

		0x7f3d090c3170	0x3931adedc2	BLooper::AssertLocked() const + 0x22 
		0x7f3d090c3190	0x3931adf1fc	BLooper::Unlock() + 0xc 
		0x7f3d090c31a0	0x1e62c14a26c	vim_unlock_screen + 0x28 
		0x7f3d090c3200	0x1e62c098bdf	screen_del_lines + 0x56b 
		0x7f3d090c3210	0x1e62c18b1bf	/boot/system/bin/gvim + 0x31c1bf 
		0x7f3d090c3280	0x1e62c18ab07	/boot/system/bin/gvim + 0x31bb07 
		0x7f3d090c32a0	0x1e62c18a8ee	/boot/system/bin/gvim + 0x31b8ee 
		0x7f3d090c32d0	0x1e62c18a807	msg_puts_attr + 0x1e 
		0x7f3d090c3310	0x1e62c189733	msg_putchar_attr + 0x8f 
		0x7f3d090c3330	0x1e62c18969c	msg_putchar + 0x15 
		0x7f3d090c3350	0x1e62c10cd21	ex_version + 0x1f 
		0x7f3d090c35a0	0x1e62bf89d50	/boot/system/bin/gvim + 0x11ad50 
		0x7f3d090c3bc0	0x1e62bf87223	do_cmdline + 0x9b3 
		0x7f3d090c3bf0	0x1e62c01d1a0	/boot/system/bin/gvim + 0x1ae1a0 
		0x7f3d090c3cf0	0x1e62c018bdd	normal_cmd + 0x1447 
		0x7f3d090c3dc0	0x1e62c181e27	main_loop + 0x872 
		0x7f3d090c3df0	0x1e62c181129	vim_main2 + 0x9f5 
		0x7f3d090c3e30	0x1e62c180728	main + 0x497 
		0x7f3d090c3e60	0x1e62c14a29b	call_main(void*) + 0x27 
		0x7f3d090c3e80	0x20289aaf67	thread_entry + 0x17 
		00000000	0x7fff8f422260	commpage_thread_exit + 0 

		Registers:
			  rip:	0x00000020289ac1c1
			  rsp:	0x00007f3d090c3148
			  rbp:	0x00007f3d090c3160
			  rax:	0x00000000000000e1
			  rbx:	0x0000015d175da8b0
			  rcx:	0x00000020289ac1c1
			  rdx:	0x00007f3d090c2c68
			  rsi:	0x0000000000000001
			  rdi:	0x0000003931c27648
			   r8:	0x0000000000000002
			   r9:	0x00000000ffffffd8
			  r10:	0x0000003931c27648
			  r11:	0x0000000000003202
			  r12:	0x0000015d172541a0
			  r13:	0x0000000000000000
			  r14:	0x0000000000000000
			  r15:	0x0000000000000000
			   cs:	0x002b
			   ds:	0x0000
			   es:	0x0000
			   fs:	0x0000
			   gs:	0x0000
			   ss:	0x0023
			  st0:	0
			  st1:	0
			  st2:	0
			  st3:	0
			  st4:	0
			  st5:	0
			  st6:	0
			  st7:	0
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0, 0, 0, 0}
			  mm2:	{0, 0, 0, 0}
			  mm3:	{0, 0, 0, 0}
			  mm4:	{0, 0, 0, 0}
			  mm5:	{0, 0, 0, 0}
			  mm6:	{0, 0, 0, 0}
			  mm7:	{0, 0, 0, 0}
			 xmm0:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm1:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm8:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm9:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm10:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm11:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm12:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm13:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm14:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm15:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	2192	0xdf3676000	0xdf36a7000	0xdf38a6000	0xdf38a7000	lib    	/boot/system/lib/libpng16.so.16.37.0
	2205	0x16aa03d000	0x16aa07f000	0x16aa27e000	0x16aa27f000	lib    	/boot/system/lib/libHalf.so.23.0.0
	2156	0x202896e000	0x2028a7a000	0x2028c7a000	0x2028ccc000	lib    	/boot/system/lib/libroot.so
	2166	0x2bab144000	0x2bab3c0000	0x2bab5c0000	0x2bab5d5000	lib    	/boot/system/lib/libicui18n.so.57.2
	2155	0x3931987000	0x3931c9b000	0x3931e9a000	0x3931ec8000	lib    	/boot/system/lib/libbe.so
	2168	0x3c44a0d000	0x3c44a61000	0x3c44c61000	0x3c44c64000	lib    	/boot/system/lib/libicule.so.57.2
	2202	0x49b5e1a000	0x49b5e26000	0x49b6026000	0x49b6027000	add-on 	/boot/system/add-ons/Translators/HVIFTranslator
	2199	0x4b732cd000	0x4b732dc000	0x4b734db000	0x4b734dc000	lib    	/boot/system/lib/libicns.so.1.2.0
	2152	0x5404392000	0x54043b3000	0x54045b2000	0x54045b4000	lib    	/boot/system/runtime_loader
	2207	0x5908ccd000	0x5908cd0000	0x5908ecf000	0x5908ed0000	lib    	/boot/system/lib/libIexMath-2_2.so.23.0.0
	2178	0x599f153000	0x599f164000	0x599f364000	0x599f365000	lib    	/boot/system/lib/libroot-addon-icu.so
	2187	0x6802fbb000	0x6802fcd000	0x68031cc000	0x68031ce000	add-on 	/boot/system/add-ons/Translators/RTFTranslator
	2164	0x7070996000	0x7070af8000	0x7070cf8000	0x7070d0c000	lib    	/boot/system/lib/libstdc++.so.6.0.25
	2193	0x88be316000	0x88be322000	0x88be522000	0x88be523000	add-on 	/boot/system/add-ons/Translators/PCXTranslator
	2158	0x9a586d5000	0x9a586ea000	0x9a588e9000	0x9a588eb000	lib    	/boot/system/lib/libtranslation.so
	2182	0xadef203000	0xadef211000	0xadef411000	0xadef412000	add-on 	/boot/system/add-ons/Translators/TIFFTranslator
	2209	0xb233929000	0xb23393b000	0xb233b3a000	0xb233b3b000	lib    	/boot/system/lib/libImath-2_2.so.23.0.0
	2172	0xb408f0c000	0xb408f28000	0xb409127000	0xb409128000	lib    	/boot/system/lib/libz.so.1.2.11
	2167	0xb71dd9c000	0xb71dda8000	0xb71dfa7000	0xb71dfa9000	lib    	/boot/system/lib/libicuio.so.57.2
	2162	0xbeb4808000	0xbeb4811000	0xbeb4a11000	0xbeb4a12000	lib    	/boot/system/lib/libintl.so.8.1.5
	2206	0xc962e12000	0xc962e27000	0xc963026000	0xc963029000	lib    	/boot/system/lib/libIex-2_2.so.23.0.0
	2197	0xc96b263000	0xc96b29c000	0xc96b49c000	0xc96b49d000	lib    	/boot/system/lib/libjpeg.so.9.3.0
	2212	0xda34def000	0xda34dfd000	0xda34ffd000	0xda34ffe000	add-on 	/boot/system/add-ons/Translators/BMPTranslator
	2196	0xe253858000	0xe25386f000	0xe253a6f000	0xe253a71000	add-on 	/boot/system/add-ons/Translators/JPEGTranslator
	2194	0xea81407000	0xea8141b000	0xea8161b000	0xea8161d000	add-on 	/boot/system/add-ons/Translators/JPEG2000Translator
	2210	0xed8a291000	0xed8a45b000	0xed8a65b000	0xed8a761000	lib    	/boot/system/lib/libIlmImf-2_2.so.23.0.0
	2200	0xf08f474000	0xf08f4e6000	0xf08f6e5000	0xf08f6e7000	lib    	/boot/system/lib/libopenjp2.so.2.3.1
	2188	0xfde0aa5000	0xfde0ac1000	0xfde0cc0000	0xfde0cc3000	add-on 	/boot/system/add-ons/Translators/RAWTranslator
	2185	0xfdef301000	0xfdef311000	0xfdef511000	0xfdef512000	add-on 	/boot/system/add-ons/Translators/TGATranslator
	2213	0x1119ad04000	0x1119ad11000	0x1119af11000	0x1119af12000	add-on 	/boot/system/add-ons/Translators/STXTTranslator
	2201	0x1156a22b000	0x1156a239000	0x1156a439000	0x1156a43a000	add-on 	/boot/system/add-ons/Translators/ICOTranslator
	2170	0x12556af9000	0x12556b27000	0x12556d27000	0x12556d5b000	lib    	/boot/system/lib/libicutu.so.57.2
	2165	0x126ccb2c000	0x126ce3ac000	0x126ce5ab000	0x126ce5ac000	lib    	/boot/system/lib/libicudata.so.57.2
	2195	0x12f19b83000	0x12f19bec000	0x12f19deb000	0x12f19df6000	lib    	/boot/system/lib/libjasper.so.4.0.0
	2175	0x133d2208000	0x133d220f000	0x133d240e000	0x133d240f000	lib    	/boot/system/lib/libbsd.so
	2171	0x13ccbeb4000	0x13ccc048000	0x13ccc248000	0x13ccc25d000	lib    	/boot/system/lib/libicuuc.so.57.2
	2174	0x141b0a7c000	0x141b0b77000	0x141b0d76000	0x141b0d79000	lib    	/boot/system/lib/libtextencoding.so
	2159	0x141c94ec000	0x141c9543000	0x141c9743000	0x141c9748000	lib    	/boot/system/lib/libncurses.so.6.2.0
	2203	0x14bac867000	0x14bac87d000	0x14baca7c000	0x14baca7e000	add-on 	/boot/system/add-ons/Translators/GIFTranslator
	2189	0x14cda01d000	0x14cda02f000	0x14cda22e000	0x14cda230000	add-on 	/boot/system/add-ons/Translators/PSDTranslator
	2157	0x14d8616d000	0x14d86328000	0x14d86527000	0x14d86542000	lib    	/boot/system/lib/libtracker.so
	2211	0x16ed0e60000	0x16ed0e81000	0x16ed1080000	0x16ed1082000	lib    	/boot/system/lib/libIlmImfUtil-2_2.so.23.0.0
	2181	0x16f8c977000	0x16f8c9df000	0x16f8cbde000	0x16f8cbe1000	lib    	/boot/system/lib/libwebp.so.7.1.0
	2179	0x172e6b4c000	0x172e6b5e000	0x172e6d5d000	0x172e6d5f000	add-on 	/boot/system/add-ons/Translators/WonderBrushTranslator
	2169	0x17868fbc000	0x17868fc7000	0x178691c7000	0x178691c8000	lib    	/boot/system/lib/libiculx.so.57.2
	2208	0x18a42870000	0x18a42876000	0x18a42a75000	0x18a42a76000	lib    	/boot/system/lib/libIlmThread-2_2.so.23.0.0
	2173	0x19052b06000	0x19052bcf000	0x19052dce000	0x19052dcf000	lib    	/boot/system/lib/libzstd.so.1.4.4
	2160	0x191023b7000	0x191023f8000	0x191025f7000	0x19102600000	lib    	/boot/system/lib/libnetwork.so
	2163	0x1a1ea0f2000	0x1a1ea108000	0x1a1ea307000	0x1a1ea308000	lib    	/boot/system/lib/libgcc_s.so.1
	2186	0x1a67c8df000	0x1a67c8ef000	0x1a67caee000	0x1a67caef000	add-on 	/boot/system/add-ons/Translators/SGITranslator
	2161	0x1a6e317a000	0x1a6e325e000	0x1a6e345d000	0x1a6e345f000	lib    	/boot/system/lib/libiconv.so.2.6.0
	2154	0x1ad83f32000	0x1ad83f34000	0x1ad84133000	0x1ad84134000	lib    	/boot/system/lib/libssp.so.0.0.0
	2190	0x1b99e47b000	0x1b99e487000	0x1b99e687000	0x1b99e689000	add-on 	/boot/system/add-ons/Translators/PPMTranslator
	2184	0x1b9b46b9000	0x1b9b474a000	0x1b9b494a000	0x1b9b494b000	lib    	/boot/system/lib/libjpeg.so.62.3.0
	2180	0x1bb9552c000	0x1bb9553a000	0x1bb9573a000	0x1bb9573b000	add-on 	/boot/system/add-ons/Translators/WebPTranslator
	2191	0x1d003faa000	0x1d003fb9000	0x1d0041b9000	0x1d0041ba000	add-on 	/boot/system/add-ons/Translators/PNGTranslator
	2198	0x1dce6a73000	0x1dce6a80000	0x1dce6c80000	0x1dce6c81000	add-on 	/boot/system/add-ons/Translators/ICNSTranslator
	2204	0x1ded02d8000	0x1ded02e5000	0x1ded04e5000	0x1ded04e6000	add-on 	/boot/system/add-ons/Translators/EXRTranslator
	2153	0x1e62be6f000	0x1e62c1ec000	0x1e62c3eb000	0x1e62c432000	app    	/boot/system/bin/gvim
	2183	0x2189f983000	0x2189f9f5000	0x2189fbf5000	0x2189fbf9000	lib    	/boot/system/lib/libtiff.so.5.5.0
	2151	0x7fff8f422000	0x7fff8f42a000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	6412	0x1fa25000	0x1fa56000	       196	r--        	full          	libintl.so.8 mmap area
	6409	0x60000000	0x60001000	         4	rw-S, u:(0x100)	full          	server_memory
	6411	0x68000000	0x68020000	       128	rw-S, u:(0x100)	full          	server_memory
	6395	0x91d0a000	0x91d22000	        96	rw-        	full          	rld heap
	6394	0x242413000	0x24242b000	        96	rw-        	full          	rld heap
	6393	0x64a6b9000	0x64a6c9000	        64	rw-        	full          	rld heap
	6392	0x9da190000	0x9da1a0000	        64	rw-        	full          	rld heap
	6442	0xdf3676000	0xdf36a7000	       196	r-x        	full          	libpng16.so.16.37.0_seg0ro
	6443	0xdf38a6000	0xdf38a7000	         4	rw-        	full          	libpng16.so.16.37.0_seg1rw
	6391	0xee35fa000	0xee3602000	        32	rw-        	full          	rld heap
	6390	0x103761a000	0x1037622000	        32	rw-        	full          	rld heap
	6469	0x16aa03d000	0x16aa07f000	       264	r-x        	full          	libHalf.so.23.0.0_seg0ro
	6470	0x16aa27e000	0x16aa27f000	         4	rw-        	full          	libHalf.so.23.0.0_seg1rw
	6345	0x202896e000	0x2028a7a000	      1072	r-x        	full          	libroot.so_seg0ro
	6346	0x2028c7a000	0x2028c88000	        56	rw-        	full          	libroot.so_seg1rw
	6347	0x2028c88000	0x2028ccc000	       272	rw-        	full          	libroot.so_seg2rw
	6369	0x2bab144000	0x2bab3c0000	      2544	r-x        	full          	libicui18n.so.57.2_seg0ro
	6370	0x2bab5c0000	0x2bab5d5000	        84	rw-        	full          	libicui18n.so.57.2_seg1rw
	6343	0x3931987000	0x3931c9b000	      3152	r-x        	full          	libbe.so_seg0ro
	6344	0x3931e9a000	0x3931ec8000	       184	rw-        	full          	libbe.so_seg1rw
	6373	0x3c44a0d000	0x3c44a61000	       336	r-x        	full          	libicule.so.57.2_seg0ro
	6374	0x3c44c61000	0x3c44c64000	        12	rw-        	full          	libicule.so.57.2_seg1rw
	6337	0x3fe9988000	0x3fe9989000	         4	rw-S, u:(0x100)	full          	_rld_debug_
	6463	0x49b5e1a000	0x49b5e26000	        48	r-x        	full          	HVIFTranslator_seg0ro
	6464	0x49b6026000	0x49b6027000	         4	rw-        	full          	HVIFTranslator_seg1rw
	6457	0x4b732cd000	0x4b732dc000	        60	r-x        	full          	libicns.so.1.2.0_seg0ro
	6458	0x4b734db000	0x4b734dc000	         4	rw-        	full          	libicns.so.1.2.0_seg1rw
	6336	0x526d0b4000	0x526d0c4000	        64	rw-        	full          	rld heap
	6334	0x5404392000	0x54043b3000	       132	r-x        	full          	runtime_loader_seg0ro
	6335	0x54045b2000	0x54045b4000	         8	rw-        	full          	runtime_loader_seg1rw
	6473	0x5908ccd000	0x5908cd0000	        12	r-x        	full          	libIexMath-2_2.so.23.0.0_seg0ro
	6474	0x5908ecf000	0x5908ed0000	         4	rw-        	full          	libIexMath-2_2.so.23.0.0_seg1rw
	6401	0x599f153000	0x599f164000	        68	r-x        	full          	libroot-addon-icu.so_seg0ro
	6402	0x599f364000	0x599f365000	         4	rw-        	full          	libroot-addon-icu.so_seg1rw
	6432	0x6802fbb000	0x6802fcd000	        72	r-x        	full          	RTFTranslator_seg0ro
	6433	0x68031cc000	0x68031ce000	         8	rw-        	full          	RTFTranslator_seg1rw
	6364	0x7070996000	0x7070af8000	      1416	r-x        	full          	libstdc++.so.6.0.25_seg0ro
	6365	0x7070cf8000	0x7070d04000	        48	rw-        	full          	libstdc++.so.6.0.25_seg1rw
	6366	0x7070d04000	0x7070d0c000	        32	rw-        	full          	libstdc++.so.6.0.25_seg2rw
	6444	0x88be316000	0x88be322000	        48	r-x        	full          	PCXTranslator_seg0ro
	6445	0x88be522000	0x88be523000	         4	rw-        	full          	PCXTranslator_seg1rw
	6351	0x9a586d5000	0x9a586ea000	        84	r-x        	full          	libtranslation.so_seg0ro
	6352	0x9a588e9000	0x9a588eb000	         8	rw-        	full          	libtranslation.so_seg1rw
	6422	0xadef203000	0xadef211000	        56	r-x        	full          	TIFFTranslator_seg0ro
	6423	0xadef411000	0xadef412000	         4	rw-        	full          	TIFFTranslator_seg1rw
	6477	0xb233929000	0xb23393b000	        72	r-x        	full          	libImath-2_2.so.23.0.0_seg0ro
	6478	0xb233b3a000	0xb233b3b000	         4	rw-        	full          	libImath-2_2.so.23.0.0_seg1rw
	6382	0xb408f0c000	0xb408f28000	       112	r-x        	full          	libz.so.1.2.11_seg0ro
	6383	0xb409127000	0xb409128000	         4	rw-        	full          	libz.so.1.2.11_seg1rw
	6371	0xb71dd9c000	0xb71dda8000	        48	r-x        	full          	libicuio.so.57.2_seg0ro
	6372	0xb71dfa7000	0xb71dfa9000	         8	rw-        	full          	libicuio.so.57.2_seg1rw
	6360	0xbeb4808000	0xbeb4811000	        36	r-x        	full          	libintl.so.8.1.5_seg0ro
	6361	0xbeb4a11000	0xbeb4a12000	         4	rw-        	full          	libintl.so.8.1.5_seg1rw
	6471	0xc962e12000	0xc962e27000	        84	r-x        	full          	libIex-2_2.so.23.0.0_seg0ro
	6472	0xc963026000	0xc963029000	        12	rw-        	full          	libIex-2_2.so.23.0.0_seg1rw
	6453	0xc96b263000	0xc96b29c000	       228	r-x        	full          	libjpeg.so.9.3.0_seg0ro
	6454	0xc96b49c000	0xc96b49d000	         4	rw-        	full          	libjpeg.so.9.3.0_seg1rw
	6484	0xda34def000	0xda34dfd000	        56	r-x        	full          	BMPTranslator_seg0ro
	6485	0xda34ffd000	0xda34ffe000	         4	rw-        	full          	BMPTranslator_seg1rw
	6451	0xe253858000	0xe25386f000	        92	r-x        	full          	JPEGTranslator_seg0ro
	6452	0xe253a6f000	0xe253a71000	         8	rw-        	full          	JPEGTranslator_seg1rw
	6446	0xea81407000	0xea8141b000	        80	r-x        	full          	JPEG2000Translator_seg0ro
	6447	0xea8161b000	0xea8161d000	         8	rw-        	full          	JPEG2000Translator_seg1rw
	6479	0xed8a291000	0xed8a45b000	      1832	r-x        	full          	libIlmImf-2_2.so.23.0.0_seg0ro
	6480	0xed8a65b000	0xed8a760000	      1044	rw-        	full          	libIlmImf-2_2.so.23.0.0_seg1rw
	6481	0xed8a760000	0xed8a761000	         4	rw-        	full          	libIlmImf-2_2.so.23.0.0_seg2rw
	6459	0xf08f474000	0xf08f4e6000	       456	r-x        	full          	libopenjp2.so.2.3.1_seg0ro
	6460	0xf08f6e5000	0xf08f6e7000	         8	rw-        	full          	libopenjp2.so.2.3.1_seg1rw
	6434	0xfde0aa5000	0xfde0ac1000	       112	r-x        	full          	RAWTranslator_seg0ro
	6435	0xfde0cc0000	0xfde0cc3000	        12	rw-        	full          	RAWTranslator_seg1rw
	6428	0xfdef301000	0xfdef311000	        64	r-x        	full          	TGATranslator_seg0ro
	6429	0xfdef511000	0xfdef512000	         4	rw-        	full          	TGATranslator_seg1rw
	6486	0x1119ad04000	0x1119ad11000	        52	r-x        	full          	STXTTranslator_seg0ro
	6487	0x1119af11000	0x1119af12000	         4	rw-        	full          	STXTTranslator_seg1rw
	6461	0x1156a22b000	0x1156a239000	        56	r-x        	full          	ICOTranslator_seg0ro
	6462	0x1156a439000	0x1156a43a000	         4	rw-        	full          	ICOTranslator_seg1rw
	6377	0x12556af9000	0x12556b27000	       184	r-x        	full          	libicutu.so.57.2_seg0ro
	6378	0x12556d27000	0x12556d29000	         8	rw-        	full          	libicutu.so.57.2_seg1rw
	6379	0x12556d29000	0x12556d5b000	       200	rw-        	full          	libicutu.so.57.2_seg2rw
	6367	0x126ccb2c000	0x126ce3ac000	     25088	r-x        	full          	libicudata.so.57.2_seg0ro
	6368	0x126ce5ab000	0x126ce5ac000	         4	rw-        	full          	libicudata.so.57.2_seg1rw
	6448	0x12f19b83000	0x12f19bec000	       420	r-x        	full          	libjasper.so.4.0.0_seg0ro
	6449	0x12f19deb000	0x12f19def000	        16	rw-        	full          	libjasper.so.4.0.0_seg1rw
	6450	0x12f19def000	0x12f19df6000	        28	rw-        	full          	libjasper.so.4.0.0_seg2rw
	6388	0x133d2208000	0x133d220f000	        28	r-x        	full          	libbsd.so_seg0ro
	6389	0x133d240e000	0x133d240f000	         4	rw-        	full          	libbsd.so_seg1rw
	6380	0x13ccbeb4000	0x13ccc048000	      1616	r-x        	full          	libicuuc.so.57.2_seg0ro
	6381	0x13ccc248000	0x13ccc25d000	        84	rw-        	full          	libicuuc.so.57.2_seg1rw
	6386	0x141b0a7c000	0x141b0b77000	      1004	r-x        	full          	libtextencoding.so_seg0ro
	6387	0x141b0d76000	0x141b0d79000	        12	rw-        	full          	libtextencoding.so_seg1rw
	6353	0x141c94ec000	0x141c9543000	       348	r-x        	full          	libncurses.so.6.2.0_seg0ro
	6354	0x141c9743000	0x141c9748000	        20	rw-        	full          	libncurses.so.6.2.0_seg1rw
	6465	0x14bac867000	0x14bac87d000	        88	r-x        	full          	GIFTranslator_seg0ro
	6466	0x14baca7c000	0x14baca7e000	         8	rw-        	full          	GIFTranslator_seg1rw
	6436	0x14cda01d000	0x14cda02f000	        72	r-x        	full          	PSDTranslator_seg0ro
	6437	0x14cda22e000	0x14cda230000	         8	rw-        	full          	PSDTranslator_seg1rw
	6348	0x14d8616d000	0x14d86328000	      1772	r-x        	full          	libtracker.so_seg0ro
	6349	0x14d86527000	0x14d86541000	       104	rw-        	full          	libtracker.so_seg1rw
	6350	0x14d86541000	0x14d86542000	         4	rw-        	full          	libtracker.so_seg2rw
	6396	0x15d171e3000	0x15d17ac3000	      9088	rw-, u:(0x100)	full          	heap
	6482	0x16ed0e60000	0x16ed0e81000	       132	r-x        	full          	libIlmImfUtil-2_2.so.23.0.0_seg
	6483	0x16ed1080000	0x16ed1082000	         8	rw-        	full          	libIlmImfUtil-2_2.so.23.0.0_seg
	6419	0x16f8c977000	0x16f8c9df000	       416	r-x        	full          	libwebp.so.7.1.0_seg0ro
	6420	0x16f8cbde000	0x16f8cbdf000	         4	rw-        	full          	libwebp.so.7.1.0_seg1rw
	6421	0x16f8cbdf000	0x16f8cbe1000	         8	rw-        	full          	libwebp.so.7.1.0_seg2rw
	6415	0x172e6b4c000	0x172e6b5e000	        72	r-x        	full          	WonderBrushTranslator_seg0ro
	6416	0x172e6d5d000	0x172e6d5f000	         8	rw-        	full          	WonderBrushTranslator_seg1rw
	6375	0x17868fbc000	0x17868fc7000	        44	r-x        	full          	libiculx.so.57.2_seg0ro
	6376	0x178691c7000	0x178691c8000	         4	rw-        	full          	libiculx.so.57.2_seg1rw
	6475	0x18a42870000	0x18a42876000	        24	r-x        	full          	libIlmThread-2_2.so.23.0.0_seg0
	6476	0x18a42a75000	0x18a42a76000	         4	rw-        	full          	libIlmThread-2_2.so.23.0.0_seg1
	6384	0x19052b06000	0x19052bcf000	       804	r-x        	full          	libzstd.so.1.4.4_seg0ro
	6385	0x19052dce000	0x19052dcf000	         4	rw-        	full          	libzstd.so.1.4.4_seg1rw
	6355	0x191023b7000	0x191023f8000	       260	r-x        	full          	libnetwork.so_seg0ro
	6356	0x191025f7000	0x191025fa000	        12	rw-        	full          	libnetwork.so_seg1rw
	6357	0x191025fa000	0x19102600000	        24	rw-        	full          	libnetwork.so_seg2rw
	6362	0x1a1ea0f2000	0x1a1ea108000	        88	r-x        	full          	libgcc_s.so.1_seg0ro
	6363	0x1a1ea307000	0x1a1ea308000	         4	rw-        	full          	libgcc_s.so.1_seg1rw
	6430	0x1a67c8df000	0x1a67c8ef000	        64	r-x        	full          	SGITranslator_seg0ro
	6431	0x1a67caee000	0x1a67caef000	         4	rw-        	full          	SGITranslator_seg1rw
	6358	0x1a6e317a000	0x1a6e325e000	       912	r-x        	full          	libiconv.so.2.6.0_seg0ro
	6359	0x1a6e345d000	0x1a6e345f000	         8	rw-        	full          	libiconv.so.2.6.0_seg1rw
	6341	0x1ad83f32000	0x1ad83f34000	         8	r-x        	full          	libssp.so.0.0.0_seg0ro
	6342	0x1ad84133000	0x1ad84134000	         4	rw-        	full          	libssp.so.0.0.0_seg1rw
	6438	0x1b99e47b000	0x1b99e487000	        48	r-x        	full          	PPMTranslator_seg0ro
	6439	0x1b99e687000	0x1b99e689000	         8	rw-        	full          	PPMTranslator_seg1rw
	6426	0x1b9b46b9000	0x1b9b474a000	       580	r-x        	full          	libjpeg.so.62.3.0_seg0ro
	6427	0x1b9b494a000	0x1b9b494b000	         4	rw-        	full          	libjpeg.so.62.3.0_seg1rw
	6417	0x1bb9552c000	0x1bb9553a000	        56	r-x        	full          	WebPTranslator_seg0ro
	6418	0x1bb9573a000	0x1bb9573b000	         4	rw-        	full          	WebPTranslator_seg1rw
	6440	0x1d003faa000	0x1d003fb9000	        60	r-x        	full          	PNGTranslator_seg0ro
	6441	0x1d0041b9000	0x1d0041ba000	         4	rw-        	full          	PNGTranslator_seg1rw
	6455	0x1dce6a73000	0x1dce6a80000	        52	r-x        	full          	ICNSTranslator_seg0ro
	6456	0x1dce6c80000	0x1dce6c81000	         4	rw-        	full          	ICNSTranslator_seg1rw
	6467	0x1ded02d8000	0x1ded02e5000	        52	r-x        	full          	EXRTranslator_seg0ro
	6468	0x1ded04e5000	0x1ded04e6000	         4	rw-        	full          	EXRTranslator_seg1rw
	6338	0x1e62be6f000	0x1e62c1ec000	      3572	r-x        	full          	gvim_seg0ro
	6339	0x1e62c3eb000	0x1e62c424000	       228	rw-        	full          	gvim_seg1rw
	6340	0x1e62c424000	0x1e62c432000	        56	rw-        	full          	gvim_seg2rw
	6424	0x2189f983000	0x2189f9f5000	       456	r-x        	full          	libtiff.so.5.5.0_seg0ro
	6425	0x2189fbf5000	0x2189fbf9000	        16	rw-        	full          	libtiff.so.5.5.0_seg1rw
	6404	0x7f3d09080000	0x7f3d090c5000	       276	rw-s       	full          	vim main()_553_stack
	6332	0x7f6da0da8000	0x7f6da1dae000	     16408	rw-s       	full          	gvim_552_stack
	6489	0x7fb893926000	0x7fb89396b000	       276	rw-s       	full          	w>Vim_557_stack
	6331	0x7ffb92d28000	0x7ffb92d2c000	        16	rw-        	full          	user area
	6333	0x7fff8f422000	0x7fff8f42a000	        32	r-xS       	full          	commpage

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	2931	    0	          0	some BBlockCache lock
	2932	    0	          0	token space
	2933	    0	          0	BLooperList lock
	2934	    0	          0	AppServerLink_sLock
	2935	    0	          0	some BLocker
	2936	    0	          0	some BLocker
	2937	    0	          0	Catalog
	2938	    0	          0	LocaleRosterData
	2939	    0	          0	some BLocker
	2940	    0	          0	Catalog
	2941	    0	          0	some BLocker
	2942	    0	          0	some BLocker
	2943	    0	          0	undo
	2944	    0	          0	Light Lock
	2945	    0	          0	Light Lock
	2946	    0	          0	PeriodicUpdatePoses
	2950	    0	          0	BMessageQueue Lock
	2951	    0	          0	AppLooperPort
	2963	    0	          0	screen list
	2964	    0	          0	clipboard
	2965	    0	          0	width buffer
	2966	    0	          0	BMessageQueue Lock
	2967	    0	        557	Vim
	2973	    0	          0	translator list
	2974	    0	          0	Catalog
	2975	    0	          0	TranslatorSettings Lock
	2976	    0	          0	Catalog
	2977	    0	          0	TranslatorSettings Lock
	2978	    0	          0	Catalog
	2979	    0	          0	TranslatorSettings Lock
	2980	    0	          0	Catalog
	2981	    0	          0	TranslatorSettings Lock
	2982	    0	          0	Catalog
	2983	    0	          0	TranslatorSettings Lock
	2984	    0	          0	Catalog
	2985	    0	          0	Catalog
	2986	    0	          0	TranslatorSettings Lock
	2987	    0	          0	Catalog
	2988	    0	          0	TranslatorSettings Lock
	2989	    0	          0	PPM settings lock
	2990	    0	          0	Catalog
	2991	    0	          0	TranslatorSettings Lock
	2992	    0	          0	Catalog
	2993	    0	          0	TranslatorSettings Lock
	2994	    0	          0	Catalog
	2995	    0	          0	TranslatorSettings Lock
	2996	    0	          0	Catalog
	2997	    0	          0	TranslatorSettings Lock
	2998	    0	          0	Catalog
	2999	    0	          0	TranslatorSettings Lock
	3000	    0	          0	Catalog
	3001	    0	          0	TranslatorSettings Lock
	3002	    0	          0	Catalog
	3003	    0	          0	TranslatorSettings Lock
	3004	    0	          0	Catalog
	3005	    0	          0	TranslatorSettings Lock
	3006	    0	          0	Catalog
	3007	    0	          0	TranslatorSettings Lock
	3008	    0	          0	Catalog
	3009	    0	          0	TranslatorSettings Lock
	3010	    0	          0	Catalog
	3011	    0	          0	TranslatorSettings Lock
	3015	    0	          0	font list
	3016	    0	          0	tool tip manager
</details>

**Comment by bitigchi** [comment]
Update: Apparently it crashes with `huge` as well.

**Comment by bitigchi** [comment]
@pulkomandy, can you please have a look at this when you are available?

**Comment by pulkomandy** [comment]
I'm not particularly familiar with vim internals. Anyone else can look as well. From the backtrace it looks like something is calling vim_unlock_screen without calling vim_lock_screen before.

**Comment by bitigchi** [comment]
Apparently that was it, thank you! I'll close this once the fix is upstream.

**Comment by bitigchi** [comment]
Fixed with #4900.
