### ISSUE TITLE
sane_backends issue with patchset

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#4903]
After attempting a build of sane_backends 1.0.29 I get an error message about the patchset.

Applying patchset "/boot/home/haikuports/media-gfx/sane_backends/patches/sane_backends-1.0.29.patchset" ...
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
Command '['git', 'am', '--ignore-whitespace', '-3', '--keep-cr', '/boot/home/haikuports/media-gfx/sane_backends/patches/sane_backends-1.0.29.patchset']' returned non-zero exit status 128.

**Comment by waddlesplash** [comment]
Try deleting your `work-*` directories in sane_backends.

**Comment by Vidrep** [comment]
After deleting the work directory I get this new error message.
Applying patchset "/boot/home/haikuports/media-gfx/sane_backends/patches/sane_backends-1.0.29.patchset" ...
error: sha1 information is lacking or useless (backend/epsonds-jpeg.c).
error: could not build fake ancestor
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Command '['git', 'am', '--ignore-whitespace', '-3', '--keep-cr', '/boot/home/haikuports/media-gfx/sane_backends/patches/sane_backends-1.0.29.patchset']' returned non-zero exit status 128.

**Comment by threedeyes** [comment]
In the new sane_backends version, quite significant changes have occurred in the code. The old patchset cannot be applied directly. In this case, you need to make all the changes from the old patchset in the new version manually. Step by step. Patch by patch.

**Comment by kenmays** [comment]
@Vidrep - We can import 1.0.28, as we previously tested it, for R1B2..
Ref: https://github.com/haikuports/haikuports/pull/4162/commits/226ea11a20cf875296f2a11a1e7d49ef5db7cd57

**Comment by Vidrep** [comment]
Current revision is 1.0.29.

**Comment by kenmays** [comment]
@Vidrep - Bumped to 1.0.29,

**Comment by Vidrep** [comment]
Builds on 64 bit, installs correctly, and tested with Canon and Epson multifunction printer/scanners.
Good to push.
