### ISSUE TITLE
Allow Vim to install without reliance on HP

### ISSUE THREAD

**Issue by bitigchi** [haikuports/haikuports#4907]
When building Vim from source with [these](https://github.com/vim/vim/blob/master/runtime/doc/os_haiku.txt) instructions, even though `make` finishes okay, during `make install`, the recipe fails here:

> rc: Error! -:8 syntax error, unexpected $undefined
> Makefile:3386: recipe for target 'objects/os_haiku.rsrc' failed

What happens here is, `make install` does not understand what to do with `os_haiku.rdef` file, therefore when gvim is launched from the source directory, icons are not visible, there are black boxes instead. Ideal way is, Vim should be able to handle the assets itself.

Instead of solely relying on Haikuports for Vim builds, it should be possible to build Vim on its own. Vim has infinite configurability regarding how its features are handled, users should be able to compile and install Vim as they please.

**Comment by Begasus** [comment]
Haven't checked this (build in Terminal), I usually use a prefix pointing to a seperate destdir for those ...

**Comment by bitigchi** [comment]
@Begasus, the related Makefile section is [here](https://github.com/vim/vim/blob/49b2fb36ca94be14b98caf86420863d9bbe81a24/src/Makefile#L3655).

**Comment by Begasus** [comment]
Maybe look at https://github.com/vim/vim/blob/49b2fb36ca94be14b98caf86420863d9bbe81a24/src/Makefile#L3385?

**Comment by Begasus** [comment]
If so, you could try to fix it and upstream a patch for it :)

**Comment by bitigchi** [comment]
@Begasus, I'm afraid this needs someone more experienced.

**Comment by extrowerk** [comment]
> rc: Error! -:8 syntax error, unexpected $undefined
> Makefile:3386: recipe for target 'objects/os_haiku.rsrc' failed

I think a malformed rdef is the reason for this error. I had the exact same error as this line had a comment in it. Make sure your rdef file have exactly the same line for the icon section like this:
https://github.com/haikuports/haikuports/blob/61f96eb4b45dcb10bb160d434bc61edf1e11eb1e/media-gfx/yacreader/additional-files/yacreader.rdef.in#L28

**Comment by extrowerk** [comment]
Ummm... I just checked an old vim recipe and the rdef file looks ok. But i see the rdef gets sed'ed in the recipe. Probably this is what missing if one does a manual build. No idea how to fix it for both environment (hp and vanilla) tho.

**Comment by pulkomandy** [comment]
Yes that's probably the problem. Replacing the version there should be done in vim configure script or makefile instead of in the recipe.

**Comment by pulkomandy** [comment]
(simplest fix is to move the sed commands in the makefile, I guess, and ask vim people how they normally handle this)

**Comment by bitigchi** [comment]
Below approach did not work:

```diff --git a/src/Makefile b/src/Makefile
index 19453c742..dc15d13f9 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -3684,6 +3684,13 @@ HAIKU_GLINKS =   $(DEST_BIN)/$(GVIMTARGET) \
 #              - in case gui-less vim.con executable available use it.
 #
 installglinks_haiku: $(HAIKU_GLINKS) install_haiku_extra
+       MAJOR="`echo "$portVersion" | cut -d. -f1`"
+       MIDDLE="`echo "$portVersion" | cut -d. -f2`"
+       MINOR="`echo "$portVersion" | cut -d. -f3`"
+               sed -i "s|@MAJOR@|$MAJOR|" os_haiku.rdef
+               sed -i "s|@MIDDLE@|$MIDDLE|" os_haiku.rdef
+               sed -i "s|@MINOR@|$MINOR|" os_haiku.rdef
+
        @catattr -r "BEOS:ICON" $(DEST_BIN)/$(GVIMTARGET) > ~icon.attr
        for i in $(HAIKU_GLINKS); do \
                rm $$i ; \
```

If anyone would like to poke, [this](https://github.com/vim/vim/blob/939b5db4808770d3a2ec35e3902a9d5165adc0cf/src/Makefile#L3655) is where all the mambo jambo happens.

**Comment by pulkomandy** [comment]
It needs to be done when generating the rdef file:

https://github.com/vim/vim/blob/939b5db4808770d3a2ec35e3902a9d5165adc0cf/src/Makefile#L3385

Also $portVersion is of course not available (it is set by haikuporter), so you need another way to know the vim version. That is fortunately easy because there are variables already set: $(VIMMAJOR).$(VIMMINOR)

+               sed -i "s|@MAJOR@|$(VIMMAJOR)|" os_haiku.rdef
+               sed -i "s|@MIDDLE@|$(VIMMINOR)|" os_haiku.rdef

However I see no way to get the "patch" version? It seems the only way is to get it from version.c, which is not easy to do from the Makefile. For now you could set it to 0:

+                sed -i "s|@MINOR@|0|" os_haiku.rdef

And ask Vim developers what they think about how this should be handled.

**Comment by bitigchi** [comment]
Below patch works fine: 

```
diff --git a/src/Makefile b/src/Makefile
index 19453c742..f18686a99 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -3383,6 +3383,9 @@ objects/os_qnx.o: os_qnx.c
        $(CCC) -o $@ os_qnx.c
 
 objects/os_haiku.rsrc: os_haiku.rdef
+       sed -i "s|@MAJOR@|$(VIMMAJOR)|" os_haiku.rdef
+       sed -i "s|@MINOR@|$(VIMMINOR)|" os_haiku.rdef
+
        cat $< | $(CCC) -E - | grep -v '^#' | rc -o "$@" -
 
 objects/os_macosx.o: os_macosx.m
diff --git a/src/os_haiku.rdef b/src/os_haiku.rdef
index bf55aa9a9..195e246e8 100644
--- a/src/os_haiku.rdef
+++ b/src/os_haiku.rdef
@@ -5,9 +5,8 @@
 resource app_signature "application/x-vnd.Haiku-Vim-8";
 
 resource app_version {
-       major  = @MAJOR@,
-       middle = @MIDDLE@,
-       minor  = @MINOR@,
+       major  = @MAJOR,
+       minor  = @MINOR,
 
        variety = B_APPV_FINAL,
        internal = 0,
```

**Comment by bitigchi** [comment]
This is fixed and merged upstream.
