### ISSUE TITLE
Otter browser internet connection is not working.

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#4918]
Haiku: hrev54101
Otter: 1.0.01-9
Qt: qt5-5.14.2-1
qtwebkit: 5.212.0~pre20200414-1

When attempting to open some web page in Otter browser, it show loading forever. WebPositive is working fine.

**Comment by threedeyes** [comment]
Strange.
Any error messages when run otter from terminal?

**Comment by threedeyes** [comment]
It's DNS problem in Qt apps after this commit (probably)  - https://git.haiku-os.org/haiku/commit/?id=04fac889f75b32790b39753276f33b6b756fc779
Opening by IP-address works fine.

**Comment by threedeyes** [comment]
I found a single call getpeername function in QtBase - https://github.com/qt/qtbase/blob/dev/src/network/socket/qnativesocketengine_unix.cpp#L1258.

If remove the error check after the getpeername call, the browser works fine.

**Comment by waddlesplash** [comment]
Supposedly the change in Haiku was the same behavior as Linux, but clearly if Qt does this, then we differ in some significant way. I'll revert the change for now.

**Comment by waddlesplash** [comment]
I reverted the change in Haiku. Discussion should continue on this ticket: https://dev.haiku-os.org/ticket/15081
