### ISSUE TITLE
Update Tor

### ISSUE THREAD

**Issue by AlwaysLivid** [haikuports/haikuports#4927]
Recently, I noticed people talking about deprecating versions of the Tor daemon that range up to 0.3.5.7 in the development IRC channel.

The most recent version of the Tor daemon available on Haiku is [0.3.5.8](https://github.com/haikuports/haikuports/tree/e23e9be3cfb803c37f421dcc5056a6c1e3d3a292/net-vpn/tor). It would likely be a good idea to update this recipe at some point in the near future.

**Comment by Begasus** [comment]
Patches welcome ;)

**Comment by AlwaysLivid** [comment]
> Patches welcome ;)

Yeah, I'm taking a look at this myself right now, I'm just trying to set up a Hybrid environment again.

**Comment by Begasus** [comment]
Looking at the patchset it shouldn't be too hard

**Comment by AlwaysLivid** [comment]
> Looking at the patchset it shouldn't be too hard

Not sure, haven't checked whether there are any other *BSD references that need proper adjustments. I'm going to take a look at it.

**Comment by AlwaysLivid** [comment]
Oh, thanks @diversys!
