### ISSUE TITLE
jq: crashes immediately

### ISSUE THREAD

**Issue by kwyxz** [haikuports/haikuports#4964]
Looks like jq 1.6.1 crashes immediately upon startup.

```
~> jq
runtime_loader: /boot/system/bin/jq: Could not resolve symbol 'gamma'
resolve symbol "gamma" returned: -2147478780
runtime_loader: /boot/system/bin/jq: Troubles relocating: Symbol not found
~> jq --version
runtime_loader: /boot/system/bin/jq: Could not resolve symbol 'gamma'
resolve symbol "gamma" returned: -2147478780
runtime_loader: /boot/system/bin/jq: Troubles relocating: Symbol not found
```

Any kind of option ends up with the same result.

**Comment by kwyxz** [comment]
I ended up removing the package downloaded from the repository and rebuilt it using haikuporter... and it now works. Odd.

**Comment by waddlesplash** [comment]
Probably trying to use some symbol that Haiku lacks, and it detects this now, I guess? Probably a rebuild should help.

**Comment by waddlesplash** [comment]
Should be fixed by https://github.com/haikuports/haikuports/commit/5d5606c45e0d000dd0750dfb91486b6acc5c220c.

**Comment by kwyxz** [comment]
Thanks @waddlesplash !
