### ISSUE TITLE
Gutenprint - new driver package does not replace old

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#4980]
The most recent Gutenprint driver package 5.3.3 when installed does not replace the previous 5.3.1 package and is not used by Haiku when printing.  Attempting to uninstall the old package gives a long list of dependencies to remove which would break the system. Is there a better way moving forward?

**Comment by korli** [comment]
5.3.3 is not compatible with 5.3.1. Haiku needs to rebuild against 5.3.3.

**Comment by korli** [comment]
Not a haikuports issue.
