### ISSUE TITLE
QEMU: Dependency Issue

### ISSUE THREAD

**Issue by CodeforEvolution** [haikuports/haikuports#4982]
Good day! I was trying to install QEMU on my x86_gcc2 Haiku machine (hrev 54185) and it complained  with this error message: "nothing provides lib:libcapstone_x86>=3 needed by qemu_x86_x86-3.1.0-5". Should the capstone recipe be checked? Or is this an issue with the QEMU recipe possibly?

**Comment by threedeyes** [comment]
Fixed in https://github.com/haikuports/haikuports/commit/98899d4434402463de8aab5f0390ff014d104f78
Try now please.

**Comment by CodeforEvolution** [comment]
Thank you very much! I was able to install QEMU!
