### ISSUE TITLE
Haiku depot not providing last version for SIDplayer and for APlayer

### ISSUE THREAD

**Issue by AlienSoldier2** [haikuports/haikuports#4984]
32 bit flavor here.
Software updater always want to overwrite at each update my SIDplayer 4.4-2 (with GUI available) by a 4.4-1 (no GUI) and my APlayer 4.0.1-2 (working well) by 4.0_SVN (not working well)

**Comment by pulkomandy** [comment]
SIDPlayer 4.4-2 recipe (with GUI) added. I don't know where you got your 4.4-2 package from because there was no such recipe in haikuports, but now there's one and it does include the GUI.
I have also fixed the APlayer 4.0_SVN package which had a missing dependency.
