### ISSUE TITLE
gcc should generate DWARF4 debug info by default

### ISSUE THREAD

**Issue by KapiX** [haikuports/haikuports#4987]
`-gdwarf-4 -gstrict-dwarf` should be added.

Otherwise CLI debugger is unusable when app_server crashes - it just spams Bad data.

**Comment by korli** [comment]
Bug in debugger?

**Comment by KapiX** [comment]
Debugger doesn't support DWARF5 and @anevilyak on IRC has said that it would be significant amount of effort to implement it.

**Comment by korli** [comment]
from https://gcc.gnu.org/onlinedocs/gcc/Debugging-Options.html
> -gdwarf-version
>Produce debugging information in DWARF format (if that is supported). The value of version may be either 2, 3, 4 or 5; the default version for most targets is 4. DWARF Version 5 is only experimental.

Maybe the problem is more about DWARF extensions?

**Comment by KapiX** [comment]
Perhaps. That would be solved by `-gstrict-dwarf`. Still, something has to be added, because it's not working as is.

**Comment by waddlesplash** [comment]
If it is still generating DWARF4 with Extensions, maybe Debugger can be modified to ignore these "extensions" without too much effort?

**Comment by X547** [comment]
In my case Bad data errors don't repeat forever and it is possible to call backtrace when errors are finished.

**Comment by korli** [comment]
is it specific to app_server debugging? I tried with sed_debuginfo, Debugger could behave correctly.

**Comment by KapiX** [comment]
That's doesn't prove much, for example libJavaScriptCore.so will crash the Debugger (regardless of DWARF version used), but you can use it for debugging other apps without issues.

Summon @anevilyak, I don't know much about this problem beyond what I wrote in the description.

**Comment by korli** [comment]
implemented in 6b7ae7d3f50a5512d0c49c88fc73c12f074fbebe
