### ISSUE TITLE
WebKit: crash in WebCore::FrameLoader::frameDetached()

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#4993]
Haiku: hrev54212
WebKit: https://github.com/haiku/webkit/commit/aeb81f69c0b6e210aa5ad0363270ca444ac92bff

[WebPositive-33519-debug-19-05-2020-05-09-43.report.txt](https://github.com/haikuports/haikuports/files/4648355/WebPositive-33519-debug-19-05-2020-05-09-43.report.txt)

**Comment by waddlesplash** [comment]
We generally track these at the Haiku bugtracker, not here (sorry for the confusion); so please report the problem there.
