### ISSUE TITLE
Vim: Need gcc2h Build

### ISSUE THREAD

**Issue by agmsmith** [haikuports/haikuports#4995]
It would be nice to have vi in the 32 bit version of Haiku.  The latest recipe 8.2.0746 is broken for gcc2 and x86 (only x64 works).  Was able to manually build CLI vim commands for gcc2 by removing a lot of the interpreters (ruby, tcl, lua, python).  Possibly someone can update the recipe to build that subset (no interpreters, no graphics (due to libsupc)) for gcc2.

You can get the 32 bit x86 build working by just removing the tcl interpreter options.

**Comment by extrowerk** [comment]
Earlier VIM versions had native GUI on GCC2h, and i think it should be still possible. If somebody tries to fix the vim recipe, should make sure the gui is also works.

**Comment by extrowerk** [comment]
Lets summon @bitigchi

**Comment by bitigchi** [comment]
I remember @Begasus tested the current recipe on his 32-bit system before I pushed it. Both GUI and console version should build okay. But I admit there might be an issue, since it's a modified recipe than the older one.

FYI @agmsmith, you don't have to tinker with the recipe to build Vim yourself, you can also grab the latest source from Vim Github repository and use the build instructions in runtime/doc/os_haiku.txt.

**Comment by extrowerk** [comment]
@bitigchi : it seems the tcl runtime breaks it:
https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=169&viewMode=compact

**Comment by pulkomandy** [comment]
We have to remove the gcc2 version because of switching to python3. But building on 32bit should still be fine. It seems that require is missing a $secondaryArchSuffix.

Is the TCL really useful? Do we really need to enable every possible language in vim? Which plugins do use it?

**Comment by extrowerk** [comment]
> Is the TCL really useful? Do we really need to enable every possible language in vim? Which plugins do use it?

I think we can safely disable all the different languages for start and see if somebody complains.

**Comment by bitigchi** [comment]
I guess we can disable the language interpreters, if someone needs them it's possible to build Vim manually anyway.

**Comment by pulkomandy** [comment]
At least Python is needed in my setup (for YouCompleteMe) so I'd prefer to keep this one. I don't know about usage of the other languages, so that's why I ask: are there plugins written in tcl around?

**Comment by bitigchi** [comment]
Not much, really. To my knowledge, all built-in interpreters are deprecated anyway, they are only there for backwards-compatibility. Vim-dev encourages using external tools instead.

**Comment by agmsmith** [comment]
Now with fewer interpreters to avoid compile hassles (just python2 for @pulkomandy), and builds on all x86 platforms, including gcc2 32 bit.

**Comment by waddlesplash** [comment]
https://github.com/haikuports/haikuports/commit/cf9654fef871c67ed8578981862b93889777ee10
