### ISSUE TITLE
freedroidrpg error on open

### ISSUE THREAD

**Issue by mazbrili** [haikuports/haikuports#4996]
error: encoutered problem in function: load_image_surface ..
,....failed loading libpng15.so.15 no such file or directory
haiku version : hrev54229+3

**Comment by threedeyes** [comment]
I am updating this package now.
Please wait...

![screenshot90](https://user-images.githubusercontent.com/2559260/82399618-e96a8480-9a98-11ea-813c-b0a465873065.png)

**Comment by mazbrili** [comment]
ok thanks

**Comment by threedeyes** [comment]
Fixed in https://github.com/haikuports/haikuports/commit/012a43da1345382134563a20f319af32001a95b4

Update and try again please.

**Comment by mazbrili** [comment]
> Fixed in [012a43d](https://github.com/haikuports/haikuports/commit/012a43da1345382134563a20f319af32001a95b4)
> 
> Update and try again please.

ok.. in process updating.. i'll report asap after test

**Comment by mazbrili** [comment]
> > Fixed in [012a43d](https://github.com/haikuports/haikuports/commit/012a43da1345382134563a20f319af32001a95b4)
> > Update and try again please.
> 
> ok.. in process updating.. i'll report asap after test

sorry @threedeyes  my vm failed to update  .. after some crash i cannot longer update.. sigh.. 
maybe i cannot access my testing vm on this week.. i'll check next week

**Comment by Begasus** [comment]
Broken for x86_gcc2 atm https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/209/builds/410.log
Strange that it worked for x86_64 given the error: freedroidrpg vs freedroidRPG in line https://github.com/haikuports/haikuports/blob/7397478c137ee2f25c2559f2e4c38b73c33b450c/games-rpg/freedroidrpg/freedroidrpg-1.0~rc2.recipe#L142

**Comment by Begasus** [comment]
Failed to launch after a local build:
```
Welcome to the Haiku shell.

/boot/system/apps/FreedroidRPG> ./FreedroidRPG 

Hello, this is FreedroidRPG, version 1.0RC2.

Unable to open configuration file /boot/home/config/settings/FreedroidRPG/fdrpg.cfg

Video system type: bwindow.
Using screen resolution 800 x 600.

Testing if color depth 32 bits is available... YES.GalliumContext: CreateScreen: Using llvmpipe (LLVM 7.0, 128 bits) driver.
Unlocking BLocker with sem 167931 from wrong thread 21888, current holder -1 (see issue #6400).

video mode set (bpp=128 RGBA=197062743318698194917753700300 depth=1651076143)
pixel format (shift/mask) : red: 16/0x00ff0000, green: 8/0x0000ff00, blue: 0/0x000000ff, alpha: 0/0x00000000

-OpenGL--------------------------------------------------------------------------
Vendor     : (null)
Renderer   : (null)
Version    : (null)
Extensions : (null)


---------------------------------------------------------------------------------
FreedroidRPG 1.0RC2 encountered a problem in function: init_open_gl
glewInit failed: Missing GL version


FreedroidRPG will terminate now to draw attention to the problems it could
not resolve. We are sorry if that interrupts a major game of yours.
---------------------------------------------------------------------------------

---------------------------------------------------------------------------------
Termination of freedroidRPG initiated... Thank you for playing freedroidRPG.

Unlocking BLocker with sem 167932 from wrong thread 21891, current holder -1 (see issue #6400).
Abort
Kill Thread
```

**Comment by Begasus** [comment]
Fix for the binary name in the recipe is in https://github.com/haikuports/haikuports/pull/5004, this should atleast enable the buildbot to finish the build

**Comment by Begasus** [comment]
Strike the above comments, build is fixed and had to update libSDL here, guess this can be closed, thanks for the fix @threedeyes !
