### ISSUE TITLE
java application .. font become square block

### ISSUE THREAD

**Issue by mazbrili** [haikuports/haikuports#5031]
tested on jdk8 and jdk11 (haiku 64 bit)
when jdk installed but not include dejavu font package .. font become square block 
![image](https://user-images.githubusercontent.com/25004583/83241950-d0af4c80-a1c5-11ea-9841-5191fad7e59e.png)

if we install dejavu font package problem dissapear

**Comment by diversys** [comment]
https://github.com/korli/haiku-jdk11u/blob/haiku-jdk-11.0.1%2B13/make/data/fontconfig/haiku.fontconfig.properties#L168

**Comment by VISTALL** [comment]
Also tested with jd13, haiku R1/beta 2

**Comment by korli** [comment]
Should be fixed in openjdk8-1.8.u242_b8-3 openjdk13-13.0.2.8-3 openjdk11-11.0.6.9-3
