### ISSUE TITLE
Error: strangely tray icons when "Locale translate option" in preference is activated

### ISSUE THREAD

**Issue by unarix** [haikuports/haikuports#5043]
When locale option "translate names of aplications and folders in the deskbar and tracker" is activated, the tray icons behaves strangely.

See the atached pictures:

![ok](https://user-images.githubusercontent.com/44549089/83363601-05133c00-a371-11ea-8050-d065eb569882.png)

![error](https://user-images.githubusercontent.com/44549089/83363598-03e20f00-a371-11ea-8653-1bed0fd9fde7.png)

**Comment by unarix** [comment]
As waddlesplash says in haiku-os ticket #16186 (closed), its not a bug in haiku; its a bug in QT port.

"Considering QuickLaunch and the other native apps work, I'm guessing this is a Qt issue. Please add to bitigchi's ticket at HaikuPorts instead."

**Comment by bitigchi** [comment]
Duplicate of #4881.
