### ISSUE TITLE
Create _debuginfo subpackage for Qt5

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#5048]
Running `strip` on Qt5 libraries shaves off about 1-1.5MB per lib, which is significant when the libs are around 7-8MB.

**Comment by waddlesplash** [comment]
CC @diversys.

**Comment by threedeyes** [comment]
Strange. I added the debuginfo package generation for all libraries and binaries (except plugins).
I got a 16 MB package. The size of binary files decreased, but the size of libraries remained the same.
