### ISSUE TITLE
LibreOffice: Offer both Stable and Fresh branches

### ISSUE THREAD

**Issue by bitigchi** [haikuports/haikuports#5096]
LibreOffice always offers two branches for download: Fresh and Stable (https://www.libreoffice.org/download/download/).

Stable branch at least gets two more releases after the first version of the Fresh branch, therefore mostly preferred by corporations or users who tend to value stability more, and because LibreOffice is mostly buggy and tends to introduce a lot of regressions in their Fresh branch.

I guess it would make sense to offer two packages, `libreoffice-fresh` and `libreoffice-stable`, so that users can choose which version they want.

**Comment by waddlesplash** [comment]
IMHO we should only offer the "stable" and not the "fresh" at this point.

**Comment by bitigchi** [comment]
> IMHO we should only offer the "stable" and not the "fresh" at this point.

That's a valid thought, but then there's no way to offer the fresh release for the ones who'd like to upgrade immediately. And unlike other OSs, there's no way to offer it as a separate download.

Maybe upstream patches and talk TDF into providing a Haiku (.hpkg) build? :)

**Comment by bitigchi** [comment]
Reminder: 7.0 is out, so right now would be the correct time to decide on this.

**Comment by kenmays** [comment]
@bitigchi - libreoffice-7.0.0.1-1-x86_64.hpkg is now available for installation.

**Comment by guzzisti** [comment]
My 2 cents:

Given the permanent lack of package maintainers there are more important issues from my point of view than having LibreOffice Fresh in the repo.

**Comment by kenmays** [comment]
@bitigchi - LibreOffice 7.0.1.2-2 - built and working now on Haiku. This is the latest source branch release available as of today...
