### ISSUE TITLE
php-5.6.37 does not build. 

### ISSUE THREAD

**Issue by bbjimmy** [haikuports/haikuports#5103]
php-5.6.37
After troubleshooting a missing package, required but not listed ... libz devel.  php stops compiling with:

Makefile:527: recipe for target 'ext/openssl/openssl.lo' failed
make: *** [ext/openssl/openssl.lo] Error 1

**Comment by kenmays** [comment]
Duplicated error on hrev54368 x86 (GCC2) w/ PHP 5.6.40 build.

**Comment by kenmays** [comment]
@bbjimmy - php 5.6 decommissioned. php 7.4.8-1 available for x86 (GCC8).
