### ISSUE TITLE
retroarch - blank windows

### ISSUE THREAD

**Issue by mazbrili** [haikuports/haikuports#5108]
on haiku64 (tested on beta2) bit open retroach will give black black windows..

**Comment by threedeyes** [comment]
try to remove settings folder - /boot/home/config/settings/retroarch

**Comment by mazbrili** [comment]
oh.. that fix the problem..  any explanation? and did this trick apply to other apps?

**Comment by threedeyes** [comment]
Did this solve the problem?
I think the reason is the incompatibility of the settings when updating the app version.

**Comment by mazbrili** [comment]
> Did this solve the problem?
> I think the reason is the incompatibility of the settings when updating the app version.

yes.. so i can close this ticket.. thank you
