### ISSUE TITLE
Python ctypes callbacks triggers segfault

### ISSUE THREAD

**Issue by falkTX** [haikuports/haikuports#5109]
When setting a ctypes callback using ctypes in python, and the C-side binary calls into the callback, a segfault happens.
Tested with python3.7 and 3.8, same behaviour on both.

I made a simple test-case at https://github.com/falkTX/haiku-python-ctypes-bug
Simply run make to build, it will run the test-case automatically.

The test-case works on bsd, linux, macos, windows and others (it is how I communicate with C libraries within my applications)

According to the debugger, the crash happens in `ffi_call_unix64`

**Comment by mmlr** [comment]
Thanks for the nice test case!

The reason for the segfault is apparent in the syslog: `instruction fetch attempted on execute-protected area 0x... at 0x...`, so it tries to execute a function in memory marked as non-executable. Looking up the area containing that address tells that this is a normal heap area, which is rightfully protected in that way.

Other OSes almost certainly have the heap protected this way as well, so the problem would seem to be that ctypes shouldn't be using memory from there at all to produce function pointers. I have not looked into the implementation yet, so I don't know what's going on, but probably there's some platform specific code that we're missing and it uses the heap as a fallback.

**Comment by mmlr** [comment]
The problem was as expected, but inside libffi which cpython uses for this instead of cpython itself. The default here was used instead of mapping memory executable with PROT_EXEC: https://github.com/libffi/libffi/blob/master/src/closures.c#L975

**Comment by falkTX** [comment]
Great! Thank for the fix.
How do we proceed so that the haiku repositories get a rebuild with the fixed python? (I am new to Haiku, so just wondering what is the procedure here)

**Comment by mmlr** [comment]
> How do we proceed so that the haiku repositories get a rebuild with the fixed python? (I am new to Haiku, so just wondering what is the procedure here)

The push of the fixed version of the libffi recipe already triggered a buildrun on the buildmaster which made the packages available in the respective HaikuPorts repositories:

https://build.haiku-os.org/buildmaster/master/x86_64/?buildrunDir=4594&viewMode=expanded
https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=357&viewMode=expanded

Just update your system and the new package versions should show up.

**Comment by falkTX** [comment]
Just to give a confirmation that indeed the issue is fixed for me.
My little application (Carla) now works fine under Haiku. I just need to implement a way to make sound (either MediaKit, or a library like SDL2)
