### ISSUE TITLE
Can't install vala on haiku x86

### ISSUE THREAD

**Issue by fsb4000** [haikuports/haikuports#5112]
```
pkgman install vala_x86
Encountered problems:
problem 1: nothing provides lib:libjpeg_x86>=9.3.0 needed by graphviz_x86-2.40.1-3
```

**Comment by Begasus** [comment]
Latest graphiz failed to build for gcc2h (_x86) ... https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/360/builds/634.log

**Comment by threedeyes** [comment]
graphviz fixed and updated - try now pls.

**Comment by fsb4000** [comment]
Thank you! Vala can be installed and able to build at least some "hello worlds".
