### ISSUE TITLE
sanity: fix x86 build with sane_backends 1.0.29

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#5124]
For Sanity GUI enhancement, fix recipe for x86 (2nd arch) with sane_backends 1.0.29.
NOTE: Sanity 0.6 tested on hrev54346 x86 with sane_backends 1.0.29. Works fine.

**Comment by Begasus** [comment]
Altered some things in the recipe for sane_backends 1.0.25 to have a build for gcc2, works ok also with Sanity, but maybe it's better to go for a gcc8 version now with the updated sane_backends :+1:

**Comment by kenmays** [comment]
Resolved.
