### ISSUE TITLE
Please have a look at porting PaleMoon to Haiku

### ISSUE THREAD

**Issue by hoper-a11y** [haikuports/haikuports#5132]
Forum thread here: https://discuss.haiku-os.org/t/port-palemoon-to-haiku/9702/3

**Comment by waddlesplash** [comment]
We do not have any interest in working on a Firefox derivative that is downstream from actual Firefox, and is not really even getting security updates. You can work on it, and we would probably accept a PR that added it as a recipe, but there's not much point in tracking it here.

**Comment by hoper-a11y** [comment]
Please reopen this issue.

**Comment by X547** [comment]
If you want to get PaleMoon port, you need to do it yourself or find developers that help you. Fact of this ticket being opened don't change anything.

**Comment by korli** [comment]
For reference: https://github.com/jasperla/openbsd-wip/issues/86

**Comment by volo-droid** [comment]
> For reference: [jasperla/openbsd-wip#86](https://github.com/jasperla/openbsd-wip/issues/86)

Uh oh, what an assholes
