### ISSUE TITLE
Please fix openjdk java font antialiasing

### ISSUE THREAD

**Issue by hoper-a11y** [haikuports/haikuports#5133]
Font smoothing is a known problem for java swing applications on platforms other than windows and mac. Some vendor decided to patch openjdk to make the fonts look good. e.g: JetBrains, which bundled their own patched java (https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under), Azul System (https://www.azul.com/downloads/zulu-community/?version=java-8-lts&os=debian&architecture=x86-64-bit&package=jdk&show-old-builds=true), unfortunately, build newer than 8u222-b10 also broke the font smoothing, but so far still better than unpatched java on linux.

Please consider doing the same for openjdk on Haiku. This will make the font prettier if not the same smoothness as Haiku's native apps' font.

**Comment by scottmc** [comment]
Was this fixed?  When closing issues it's nice to provide a link to the commit that fixed it.
