### ISSUE TITLE
clangd: Crash while using with vim

### ISSUE THREAD

**Issue by bitigchi** [haikuports/haikuports#5139]
I was trying to see if I can get coc.nvim to work with Haiku, when I install the latest llvm from HaikuPorts, clangd crashes upon opening a C file with vim.

If I do `pkgman install llvm`, vim launches and works fine, basic completion is there, but coc.nvim complains that clangd is not installed. When I install the llvm7* packages from HaikuDepot, get the below crash.

Crash log:
https://paste.ubuntu.com/p/c57cYPwBYz/

**Comment by korli** [comment]
crash log can't be seen

**Comment by augiedoggie** [comment]
is this still valid? the paste of the crash log is not available and we've had many LLVM updates since

**Comment by augiedoggie** [comment]
no response
