### ISSUE TITLE
Krita package missing libboost_system dependancy

### ISSUE THREAD

**Issue by smallstepforman** [haikuports/haikuports#5144]
Fresh install of Haiku R1B2, and fresh install of Krita complains about missing dependancy libboost_system 1.69.  Easy to resolve manually, but the hpkg should specifiy the missing dependancy so that less technical users can run the application.

**Comment by waddlesplash** [comment]
@diversys: On x64, Krita installs, but needs "boost169"; for some reason a different Boost package is installed.

**Comment by threedeyes** [comment]
Fixed in https://github.com/haikuports/haikuports/commit/2e9f3bd9b9e01b1271f5dba3ae83e779f4efd4f6 and https://github.com/haikuports/haikuports/commit/b790baf846c7cd6b6d151663827f670c4251c14e
