### ISSUE TITLE
Residualvm does not install, libjpeg 9.3.0 needed

### ISSUE THREAD

**Issue by Brunobasta** [haikuports/haikuports#5158]
I have a lib:libjpeg_x86 problem:
Trying to download and install Residualvm in HaikuDepot i get this alert:
 lib:libjpeg_x86 greater same 9.3.0 needed by residualvm_x86-0.3.1-2

**Comment by threedeyes** [comment]
Fixed in https://github.com/haikuports/haikuports/commit/c07580b126524f97723768142194912798e9c3a9 and https://github.com/haikuports/haikuports/commit/2758c69cbcd1f91f611a67bf0b2f12a2a4ba8df4

Try again please

**Comment by Brunobasta** [comment]
I will try again.
If it works I like to try the new mod of "The longest Journey" since I own the original game and it is a great game I still remember.

**Comment by Brunobasta** [comment]
Install works fine... Have to test it with the game later, have to sleep now... I know if I try now I will not get enogh sleep.

**Comment by Brunobasta** [comment]
Works great, Monkey Island 3d (0.3.0) and The longest Journey (0.4.0) works nicely.
