### ISSUE TITLE
Paladin: is there a need to have the old v1.4~git?

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#5168]
There are two Paladin packages for 32bit Haiku, the current v2.7 by @adamfowleruk and the old v1.4~git from HaikuArchives. Is the old one still needed?

**Comment by kenmays** [comment]
@humdingerb - Verified Paladin 2.7-1 built successfully on hrev54418 x86_gcc2 (GCC2).

**Comment by kenmays** [comment]
Fixed 2.8~git build for gcc2. Removed outdated recipes.
