### ISSUE TITLE
libssl error when trying to install Beam through HaikuDepot on Beta2

### ISSUE THREAD

**Issue by BeOSR** [haikuports/haikuports#5170]
error "Nothing provides lib: libssl>=1.0.0 needed by Beam 1.2.1-2

libssl.so, libssl.so.1.1 and libssl3.so are present in system/lib and system/develop/lib

R1/Beta2+115 

an old version of Beam I had lying around works fine (Beam 1-1-2-r5-with-libs, but libssl isn't part of these libs)

**Comment by korli** [comment]
fixed in e83335a7caa804cbcf4ae41fc43ba538bb828886
