### ISSUE TITLE
gptfdisk linkage error (libuuid.so) 

### ISSUE THREAD

**Issue by smallstepforman** [haikuports/haikuports#5174]
Haiku R1B2, gptfdisk asks for libuuid.so.1.3.0, however system has 1.3.1-4.  Failed to start gdisk, with following error:

runtime_loader: /boot/system/lib/libuuid.so.1.3.0: No version information available (required by /boot/system/bin/gdisk)
runtime_loader: /boot/system/bin/gdisk: Could not resolve symbol 'uuid_generate'
resolve symbol "uuid_generate" returned: -2147478780
runtime_loader: /boot/system/bin/gdisk: Troubles relocating: Symbol not found

**Comment by Begasus** [comment]
Probably related ... https://github.com/haikuports/haikuports/issues/4266

**Comment by kallisti5** [comment]
Should be fixed via:
https://github.com/haikuports/haikuports/commit/f8b6d17ea426687c747c8bbdbbe4b9b57fc95470

A new build (-4) of gptfdisk should fix this one.


Pretty much, gptfdisk had a bunch of hacks around making the util_linux libuuid work. 

Some history:

* BSD licensed libuuid seemingly abandoned.
* util_linux (GPL) took it upon themselves to "suck it up", also adding all of the util_linux dependencies.
* I took the libuuid back out of util_linux and removed all the GPL and extra dependencies again making it BSD.
  * https://gitlab.com/kallisti5/libuuid
