### ISSUE TITLE
NSS: bump x86_64 to NSS 3.52.1

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#5178]
Depends on:
- [ ]  nspr 4.26

Rebuild/Check these packages after installation:
- [ ]  xmlsec
- [ ]  qca
- [ ]  okular
- [ ]  calligra
    - [ ]  calligra_okular_plugins
    - [ ]  calligraplan
- [ ]  libreoffice

**Comment by kenmays** [comment]
Rebuilt packages:
- [ ]  xmlsec
- [ ]  qca
- [ ]  okular
- [ ]  calligra
    - [ ]  calligra_okular_plugins
    - [ ]  calligraplan

**Comment by Begasus** [comment]
For gcc2h there are still changes needed for nspr to get xmlsec to build

**Comment by kenmays** [comment]
Reviewed and resolved with Begasus for merging
