### ISSUE TITLE
GnuPG: gpg: agent_genkey failed: Operation not allowed

### ISSUE THREAD

**Issue by cwross** [haikuports/haikuports#5193]
Tested in both Haiku R1/beta2 and hrev54418, gpg will not permit the generation of a new key using the command 'gpg --generate-key'.

It results in the following output:

gpg: agent_genkey failed: Operation not allowed
Key generation failed: Operation not allowed

GnuPG 2.2.14

**Comment by cwross** [comment]
Attempting to import a secret key created on another system also results in failure:

gpg: key <KEYID REMOVED>: error sending to agent: Operation not allowed
gpg: error building skey array: Operation not allowed
gpg: error reading 'test.key': Operation not allowed
gpg: import from 'test.key' failed: Operation not allowed

**Comment by cwross** [comment]
GnuPG 2.2.14 appears very broken on Haiku at the moment. I cannot decrypt files, either:

`gpg --decrypt test.gpg` results in:

gpg: public key decryption failed: Operation not allowed
gpg: decryption failed: No secret key

Yet the secret key is definitely imported, as it shows up as expected when running `gpg --list-secret-keys`

**Comment by extrowerk** [comment]
closed trough https://github.com/haikuports/haikuports/pull/5196
