### ISSUE TITLE
QMplay2: youtube search, doesn't work

### ISSUE THREAD

**Issue by unarix** [haikuports/haikuports#5194]
When search in youtube from qmplay2, seems to not work propertly... after hit enter in the search box, the status bar appears but no results showed in the list.

Tested in hrev 54418 x64.

**Comment by unspacyar** [comment]
Hello!  If I remember correctly, the problem was related to some change on Youtube site.  Qmplay2 was updated recently, and yesterday tha recipe was updated too in Haikuports.

Did you tried using the 20.07.04 version?

**Comment by unarix** [comment]
Yes! the new vertion works ok! Closed! thanks @unspacyar!
