### ISSUE TITLE
Otter Browser Crash on Open

### ISSUE THREAD

**Issue by tbn97** [haikuports/haikuports#5216]
On (at least*) the last few nightlies, Otter Browser crashes on opening. Do not pass go, do not collect $200...

Window opens, app crashes. Finito la Musica. Will attach the dump report.

Platform: 2-core/4-thread (H/T) i7 8GB MacBook Pro (Early 2011) 64 bit hrev54459

*NB - I was running the "stable" beta until a few days ago - under that Otter Browser opened and worked, but I'd get random Kernel panics due to what looked like something ethernet-related. That has been resolved in the latest nightlies.

**Comment by tbn97** [comment]
[Otter-Browser-901-debug-24-07-2020-06-11-11.txt](https://github.com/haikuports/haikuports/files/4974730/Otter-Browser-901-debug-24-07-2020-06-11-11.txt)

**Comment by kenmays** [comment]
1. pkgman full-sync (hrev54460 x86_64)

NOTE: I tested Haiku hrev54447 and hrev54460 x86_64  w/ Otter Browser 1.0.01 and 1.0.81-dev. No issues with crash on open.

![otter_browser-cocobean-3](https://user-images.githubusercontent.com/5168719/88466982-de601600-ce86-11ea-9de6-e82e9c25961c.png)

**Comment by tbn97** [comment]
Went digging further - turns out it was a nastily corrupt default config file.  Moved that out of the way and Otter is... Ottering once again!   :)
