### ISSUE TITLE
WonderBrush crashes on launch on hrev54460

### ISSUE THREAD

**Issue by bbjimmy** [haikuports/haikuports#5217]
using wonderbrush-2.1.2-9-x86_gcc2.hpkg

**Comment by bbjimmy** [comment]
crash report: http://fatelk.com/jim/WonderBrush-555-debug-25-07-2020-15-52-37.report.zip

**Comment by humdingerb** [comment]
Here's a report with debugging: https://oshi.at/pSRqRX/WonderBrush-2572-debug-26-07-2020-08-54-01.report
It Terminal, it says: `ExportPanel::ExportPanel() - couldn't find necessary controls.`

I wonder what Haiku commit broke this. It's working fine in Beta2...

**Comment by pulkomandy** [comment]
hrev54407 changed various things in the BFilePanel, sounds likely it could have broken this.

@waddlesplash

**Comment by waddlesplash** [comment]
https://github.com/stippi/WonderBrush-v2/blob/f6e64b578fe4d0e1ca3b6bfd4c3417300cdec655/WonderBrush/src/gui/panels/ExportPanel.cpp#L77

It looks like WonderBrush casts a scroll bar to BScrollBar; for no apparent reason as it only ever calls MoveBy on it. The Be Book says they are "scroll bars" but not that they are specifically BScrollBars...

Should we change the code in Tracker or in WonderBrush here?

**Comment by waddlesplash** [comment]
Fixed in https://git.haiku-os.org/haiku/commit/?id=d548fb2b3e493004761739c3e3fcc008ec497860
