### ISSUE TITLE
Cannot update cppcheck from 1.87-1 to 1.87-2

### ISSUE THREAD

**Issue by KapiX** [haikuports/haikuports#5218]
pkgman fails with:

```
*** failed to commit transaction: Failed to copy file "/boot/system/packages/administrative/writable-files/cppcheck-1.87-2/settings/cppcheck" to "/boot/system/settings/cppcheck": File or Directory already exists
```

I had settings there, but even after removing that directory, I can't update.

**Comment by augiedoggie** [comment]
I could've sworn that I tested the package as it was and didn't get the error, but I do now.  Although I admit I was toying around with different options and the package I had installed locally was different.
