### ISSUE TITLE
speedcrunch: build is broken after recent icon changes

### ISSUE THREAD

**Issue by augiedoggie** [haikuports/haikuports#5224]
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/4693/builds/17382.log

**Comment by humdingerb** [comment]
Sorry about that. Should be fixed...

**Comment by augiedoggie** [comment]
No problems.  Does it need a revision bump in order to rebuild though?

**Comment by humdingerb** [comment]
It did not: https://build.haiku-os.org/buildmaster/master/x86_64/?buildrunDir=4701
