### ISSUE TITLE
ICU 66.1: Unit testing issues on x86_64

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#5230]
icu66-66.1-1-x86_64.hpkg                           02-Aug-2020 12:27            13861015
icu66_devel-66.1-1-x86_64.hpkg                     02-Aug-2020 12:27              983302
[icu66_error_report.txt](https://github.com/haikuports/haikuports/files/5019580/icu66_error_report.txt)

**Comment by pulkomandy** [comment]
You have carefully removed the message from ICU reports that says this is normal and expected because we are building it with customized data.

**Comment by waddlesplash** [comment]
@kenmays, you have previously removed information from logs you have posted in a deceptive manner and I believe we have warned you about this. Why do you continue to do it?

**Comment by kenmays** [comment]
If the claim is that ICU 66.1 passed all unit tests as expected by Haiku dev,  that is fine. If you have your own tsst report that shows this info -  stating that is more helpful than accusing deception.
