### ISSUE TITLE
Vim crashes with segmentation violation

### ISSUE THREAD

**Issue by roired** [haikuports/haikuports#5237]
Good day,

As of today, 20200806, with new gVim update I started to face crashes when opening certain files, mostly .py files. Error is a 'segmentation violation':

```
/gui> gvim gui.py 
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation violation
```

Trying to open the .py file with double click attempts to launch gVim and does nothing, so the only way I found to get the error is using the terminal.

Outcome of uname-a:
`Haiku bellatrix 1 hrev54487 Aug  4 2020 06:46:20 x86_64 x86_64 Haiku
`

Vim version:
```
 gvim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug  5 2020 19:42:54)
Included patches: 1-1313
Compiled by HaikuPorts
```

If you need any more info, tell me what is needed in order to provide it.

Regards,
RR

**Comment by bitigchi** [comment]
It looks like the Python3 interpreter is not working. I'll revert the change. In the meantime can you also open an issue on Vim issue tracker with the instructions there?

**Comment by bitigchi** [comment]
It should be working with the updated recipe.

**Comment by roired** [comment]
Good day @bitigchi,
Yes, so it seems that it was due to the Python3 issue. I just turned on the box today, there was the Vim update and after the update and checking that Vim wasn't compiled with Python3, it does work.
Too bad Python3 does not work with Vim.

I'll open the issue on the Vim issue tracker too as you pointed out.

Thanks a lot.
Regards,
RR

**Comment by roired** [comment]
Good day @bitigchi,
Yes, so it seems that it was due to the Python3 issue. I just turned on the box today, there was the Vim update and after the update and checking that Vim wasn't compiled with Python3, it does work.
Too bad Python3 does not work with Vim.

I'll open the issue on the Vim issue tracker too as you pointed out.

Thanks a lot.
Regards,
RR

**Comment by roired** [comment]
Good day @bitigchi,
Yes, so it seems that it was due to the Python3 issue. I just turned on the box today, there was the Vim update and after the update and checking that Vim wasn't compiled with Python3, it does work.
Too bad Python3 does not work with Vim.

I'll open the issue on the Vim issue tracker too as you pointed out.

Thanks a lot.
Regards,
RR

**Comment by roired** [comment]
Good day @bitigchi,
Yes, so it seems that it was due to the Python3 issue. I just turned on the box today, there was the Vim update and after the update and checking that Vim wasn't compiled with Python3, it does work.
Too bad Python3 does not work with Vim.

I'll open the issue on the Vim issue tracker too as you pointed out.

Thanks a lot.
Regards,
RR

**Comment by roired** [comment]
Good day @bitigchi,
Yes, so it seems that it was due to the Python3 issue. I just turned on the box today, there was the Vim update and after the update and checking that Vim wasn't compiled with Python3, it does work.
Too bad Python3 does not work with Vim.

I'll open the issue on the Vim issue tracker too as you pointed out.

Thanks a lot.
Regards,
RR

**Comment by roired** [comment]
Good day @bitigchi,
Yes, so it seems that it was due to the Python3 issue. I just turned on the box today, there was the Vim update and after the update and checking that Vim wasn't compiled with Python3, it does work.
Too bad Python3 does not work with Vim.

I'll open the issue on the Vim issue tracker too as you pointed out.

Thanks a lot.
Regards,
RR

**Comment by roired** [comment]
Good day @bitigchi,
Yes, so it seems that it was due to the Python3 issue. I just turned on the box today, there was the Vim update and after the update and checking that Vim wasn't compiled with Python3, it does work.
Too bad Python3 does not work with Vim.

I'll open the issue on the Vim issue tracker too as you pointed out.

Thanks a lot.
Regards,
RR

**Comment by roired** [comment]
Good day @bitigchi,
Yes, so it seems that it was due to the Python3 issue. I just turned on the box today, there was the Vim update and after the update and checking that Vim wasn't compiled with Python3, it does work.
Too bad Python3 does not work with Vim.

I'll open the issue on the Vim issue tracker too as you pointed out.

Thanks a lot.
Regards,
RR

**Comment by roired** [comment]
Good day @bitigchi,
Yes, so it seems that it was due to the Python3 issue. I just turned on the box today, there was the Vim update and after the update and checking that Vim wasn't compiled with Python3, it does work.
Too bad Python3 does not work with Vim.

I'll open the issue on the Vim issue tracker too as you pointed out.

Thanks a lot.
Regards,
RR

**Comment by roired** [comment]
Good day @bitigchi,
Yes, so it seems that it was due to the Python3 issue. I just turned on the box today, there was the Vim update and after the update and checking that Vim wasn't compiled with Python3, it does work.
Too bad Python3 does not work with Vim.

I'll open the issue on the Vim issue tracker too as you pointed out.

Thanks a lot.
Regards,
RR

**Comment by Begasus** [comment]
Checked with a local .py file, no problem, closing.
If this pops up again please reopen.
