### ISSUE TITLE
haikuwebkit: x86_64-1.7.0-2 build fails

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#5249]
Nightly:
[haikuwebkit-1.7.0-2-x86_64_buildlog.txt](https://github.com/haikuports/haikuports/files/5065049/haikuwebkit-1.7.0-2-x86_64_buildlog.txt)

R1B2 build issue:
https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/4707/builds/17399.log

**Comment by bitigchi** [comment]
https://github.com/haiku/webkit/commit/461de5e4deaf2e71a2efeb1e55276f19b82fcf30

**Comment by kenmays** [comment]
Fixed by Pulkomandy.. Build verified by VidRep.
