### ISSUE TITLE
git: crash on NULL dereference in git_config_set_multivar_in_file_gently

### ISSUE THREAD

**Issue by mikedld** [haikuports/haikuports#5270]
Steps to reproduce:
```
mkdir test
cd test
git init --bare .
git config foo.bar baz
```

Result:
![image](https://user-images.githubusercontent.com/298203/92012262-e5672780-ed54-11ea-8f0f-33d34d389678.png)

**Comment by korli** [comment]
fixed in 6d8b3756ea5a3dbad04f489d927143a27fd5dd21
