### ISSUE TITLE
SuperTuxKart Port

### ISSUE THREAD

**Issue by panos** [haikuports/haikuports#5294]
I'm opening this issue, because, although I've been meaning to get around to it for a while now, I simply haven't found the time to do it from scratch by myself. I asked the lead developer (@Benau) as to whether anyone else tried playing the game online and was told that nobody has.

A few months ago, I managed to port SuperTuxKart over to Haiku (see: https://github.com/supertuxkart/stk-code/pull/4309). The port has been maintained by its community's members. Although there's no 3D acceleration, the SDL2 port performs VERY well for some weird reason. I have lost my WIP recipe (nearly complete, although it was written before SuperTuxKart was ported to SDL2) and a few of my most recent attempts have been halted by arbitrary errors. (e.g. Subversion not working properly at that time, which prevented me from creating a `supertuxkart_data` package)

I'm sharing the following in order to help as much as I can:

- The initial release that shipped with Haiku support was `1.2-rc1`.
- SuperTuxKart has a document on how to compile the game, which can be accessed [here](https://github.com/supertuxkart/stk-code/blob/master/INSTALL.md).
- The data assets for SuperTuxKart can be found here; https://svn.code.sf.net/p/supertuxkart/code/stk-assets. The files over there aren't versioned or "intertwining" with the main codebase, so it'd be best to have the latest available version.
- Wiiuse, according to @Benau, can be safely disabled and it may get discontinued at some point in the foreseeable future.
- [Here's how Arch Linux (AUR) does it.](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=supertuxkart-git)

Porting this game will be quite time-consuming and, essentially, a cat-and-mouse game. However, I believe that it'd be quite rewarding, considering that this game natively supports Haiku now, and I think that it underlines what the system is capable of in a pretty fun manner. I will make myself available and I'd gladly contribute to figuring out details, contributing to the authoring of the recipe and testing. It's just that I seriously don't have the ability to undertake something like that completely by myself right now.

**Comment by kenmays** [comment]
I had the packaging working last year. I may need to revisit for current nightly builds.

**Comment by panos** [comment]
Good! I can definitely make use of that myself, it's just that I cannot get the data recipe to work. (SVN = seems sort of broken)

**Comment by pulkomandy** [comment]
SVN like any source control system is considered "unsafe" because there is no way to do a checksum of what you download, so we couldn't check what we're packaging.

You need an archive or a single file to download using http(s).

**Comment by kenmays** [comment]
Added recipe: #5306

**Comment by panos** [comment]
Smart idea to just get rid of the `_data` problem by just keeping things in one package, @kenmays

**Comment by kenmays** [comment]
Built the Supertuxkart v1.2 64-bit package and reviewing the 32-bit package. Comes with 21+ tracks. Decent performance on native Haiku install and running from GUI.. Story Mode looks great.

**Comment by panos** [comment]
I posted a video on Twitter where I tried it out under Gallium and QEMU (I expected like 3-4 frames, if not a crash)-- it's really amazing how amazingly well the game runs on an operating system without 3D acceleration.

Then again, the reason why I agreed to do this is because it ran on Android.

**Comment by panos** [comment]
Gamepad support may need to be worked on. It's SDL2, though, so it should work. :D

**Comment by kenmays** [comment]
SuperTuxkart v1.2 works on Haiku x86 and x86_64 with no issues. Recipe just needs some further tweaks. I posted some test packages in my repo for both platforms.

**Comment by diversys** [comment]
Should it be closed now?

**Comment by panos** [comment]
Yup!
