### ISSUE TITLE
Update dev-util/radare2 to 4.5.1

### ISSUE THREAD

**Issue by XVilka** [haikuports/haikuports#5295]
There was a tremendous amount of new features and bugfixes since. We also did some fixes specifically for Haiku.
See
- https://github.com/radareorg/radare2/releases/tag/4.5.1

The mentioned Haiku fixes are:
- https://github.com/radareorg/radare2/commit/f56ae25d352eb82b2ca362e205c70086b13555d5
- https://github.com/radareorg/radare2/commit/d30ca79e2de175226fc76d6bcb38364a9943f027
- https://github.com/radareorg/radare2/commit/4d22e92d6dcbf33c8bec1ba1438115f51fdced29
- https://github.com/radareorg/radare2/commit/46874bae1769b67a897a44d23e77bce895ce15d3

Many other distributions and operating systems already did the upgrade: https://repology.org/project/radare2/versions

**Comment by Begasus** [comment]
@XVilka Did a local build for version 4.5.1, recipe is ok but I had to import the last patch manual (didn't seem to be included in the last release): https://github.com/radareorg/radare2/commit/46874bae1769b67a897a44d23e77bce895ce15d3
Checking a build for cutter (1.12.0) with the new release

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/5433
Cutter launching (but only through Terminal, maybe opening an another issue for that one)
![Cutter](https://user-images.githubusercontent.com/16057090/99963582-47eb2500-2d92-11eb-9afd-f5b09100a959.png)
