### ISSUE TITLE
Audacious 4.0.5: Wrong copyright in recipe

### ISSUE THREAD

**Issue by Briseur** [haikuports/haikuports#5304]
Błażej Szczygieł is author of multiple projects (QMplay2,  ) but  not this one. ;)
https://github.com/audacious-media-player/audacious/blob/master/AUTHORS
They seem to use Copyright © 2001-2020 Audacious developers and others
https://github.com/audacious-media-player/audacious/blob/master/COPYING

**Comment by Begasus** [comment]
Looks correct to me :) Nice catch, could you make the needed changes and file a PR? :)
