### ISSUE TITLE
Add recipe for Faber

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#533]
https://github.com/Barrett17/Faber

**Comment by waddlesplash** [comment]
I don't think Faber is ready for a release -- @Barrett17, can you comment here?

**Comment by Barrett17** [comment]
Please don't make a recipe for it.

**Comment by richienyhus** [comment]
@Barrett17  Sorry, I thought that having more eyes on the project would mean more motivation for you.

**Comment by Barrett17** [comment]
@richienyhus don't worry at all. I know there's desire to see this app in HaikuDepot :-)
