### ISSUE TITLE
dev-lang/openjdk Unable to build openjdk11

### ISSUE THREAD

**Issue by volo-droid** [haikuports/haikuports#5376]
### Issue

While building openjdk11 I've got the following compilation error:
```
/sources/src/build/haiku-x86_64-normal-server-release/support/gensrc/java.base/sun/nio/ch/SocketOptionRegistry.java:53: error: incompatible types: int cannot be converted to boolean
                                  0
                                  ^
/sources/src/build/haiku-x86_64-normal-server-release/support/gensrc/java.base/sun/nio/ch/SocketOptionRegistry.java:58: error: incompatible types: int cannot be converted to boolean
                                                    0
                                                    ^
/sources/src/build/haiku-x86_64-normal-server-release/support/gensrc/java.base/sun/nio/ch/SocketOptionRegistry.java:64: error: incompatible types: int cannot be converted to boolean
                                               0
                                               ^
/sources/src/build/haiku-x86_64-normal-server-release/support/gensrc/java.base/sun/nio/ch/SocketOptionRegistry.java:69: error: incompatible types: int cannot be converted to boolean
                                                   0
                                                   ^
/sources/src/build/haiku-x86_64-normal-server-release/support/gensrc/java.base/sun/nio/ch/SocketOptionRegistry.java:74: error: incompatible types: int cannot be converted to boolean
                  1
                  ^
```

This happens after the following command in `GensrcMisc.gmk` (line 80) preprocess `SocketOptionRegistry.java.template` and replaces all `true` and `false` with `1` and `0`:
```shell
( /bin/gawk '/@@END_COPYRIGHT@@/{exit}1' \
/sources/src/src/java.base/share/classes/sun/nio/ch/SocketOptionRegistry.java.template && \
/bin/gcc -E -x c  \
    -I/sources/src/build/haiku-x86_64-normal-server-release/support/modules_include/java.base \
    -I/sources/src/build/haiku-x86_64-normal-server-release/support/modules_include/java.base/haiku \
    -I/sources/src/src/java.base/share/native/libjava \
    -I/sources/src/src/java.base/unix/native/libjava \
    -I/sources/src/src/hotspot/share/include \
    -I/sources/src/src/hotspot/os/posix/include \
    -DHAIKU -DNDEBUG -D_LITTLE_ENDIAN -DARCH='"amd64"' -Damd64 \
    -pipe -Wall -Wextra -Wno-unused -Wno-unused-parameter -Wformat=2  -fno-strict-aliasing \
    -m64 -fno-omit-frame-pointer -fno-delete-null-pointer-checks -fno-lifetime-dse -fPIC \
    /sources/src/src/java.base/share/classes/sun/nio/ch/SocketOptionRegistry.java.template \
    2> >(/bin/grep -v '^SocketOptionRegistry.java.template$' >&2) \
    | /bin/gawk '/@@START_HERE@@/,0' \
    |  /bin/sed -e 's/@@START_HERE@@/\/\/ AUTOMATICALLY GENERATED FILE - DO NOT EDIT/' -e 's/PREFIX_//' -e 's/^#.*//' ) \
    > /sources/src/build/haiku-x86_64-normal-server-release/support/gensrc/java.base/sun/nio/ch/SocketOptionRegistry.java
```
Since OpenJDK uses C-preprocessor to process those `.java.template` files (dangerous idea IMHO, but well…), there's probably a `#define true 1` and `#define false 0` somewhere in the included header files. I also assume the issue is local to my configuration since the HaikuDepot builds openjdk11 just fine. 

Not sure if that's helpful, but I've opened an openjdk11 working directory during the build and run:
```
grep --include='*.h' -rnw ./ -e "define\s*true\s*1"
```
The results are:
```
./boot/system/develop/tools/lib/gcc/x86_64-unknown-haiku/8.3.0/plugin/include/system.h:816:# define true 1
./boot/system/develop/tools/lib/gcc/x86_64-unknown-haiku/8.3.0/include/stdbool.h:34:#define true        1
./sources/src/src/java.desktop/share/native/common/font/fontscalerdefs.h:57:        #define true            1
./sources/src/src/java.desktop/share/native/libsplashscreen/giflib/gif_lib.h:53:#define true 1
./sources/src/src/jdk.hotspot.agent/linux/native/libsaproc/libproc.h:83:#define true  1
./sources/src/src/jdk.hotspot.agent/macosx/native/libsaproc/libproc.h:48:#define true  1
./sources/src/src/jdk.hotspot.agent/macosx/native/libsaproc/libproc.h:79:#define true  1
```
Upon further investigation both of the following 2 headers files specified in `SocketOptionRegistry.java.template` include somehow one of the above mentioned headers with `#define true 1` (most probably `stdbool.h` or `system.h`):
```c
#include <netinet/in.h>
#include <netinet/tcp.h>
```

### Quick-fix
I've added these lines to `SocketOptionRegistry.java.template`:
```c
#undef true
#undef false
```

**Comment by korli** [comment]
Thanks, the patch was missing. Sorry for the trouble.

**Comment by korli** [comment]
@volo-droid if you have time/interest there is still the problem with hanging "tee" processes after the openjdk build. Again probably a Haiku bug related to pipe or signal handling. The buildbot is of course concerned by this issue.

**Comment by volo-droid** [comment]
@korli Is there a ticket opened in GitHub with more details? If no, can you provide them here? Does it happen always, so I can easily reproduce it? And btw, what's your OpenJDK build configuration, since it takes quite some time on machine to build with 4 cores and 8GB dedicated to VMWare

**Comment by korli** [comment]
@volo-droid  no ticket, because it might just be a problem in Haiku. See https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/4922/builds/17736.log 
the chroot can't be unmounted: "unmount: unmounting failed: Device/File/Resource busy"

I build on real hardware on a 4 cores 8GB i5, with --with-num-cores=3  I know some VM software aren't so good with I/O and multithreaded builds with Haiku.
The buildbot logs: 
1h15 for openjdk8
2020-11-01 09:28:21,744: starting build 17738, openjdk8-1.8.u242_b8 on builder mmlr_x86_64
2020-11-01 10:43:08,874: build 17738, openjdk8-1.8.u242_b8 succeeded

**Comment by volo-droid** [comment]
@korli I had that issue once, and after it happens the subsequent openjdk builds fail to start with the same error: "unmount: unmounting failed: Device/File/Resource busy", and reboot didn't help. Could it be a bug in haikuporter?

Regarding build time, it's around 40 minutes for me. I think rebuilds time can be greatly improved if I manage to bind `ccache` cache folder into recipe's chroot environment.

**Comment by pulkomandy** [comment]
> "unmount: unmounting failed: Device/File/Resource busy", and reboot didn't help. Could it be a bug in haikuporter?

It happens when a process from the build did not stop. As long as something is still running, it is not possible to unmount the filesystem. Maybe the build is running some background process and failing to stop it correctly?

**Comment by mmlr** [comment]
I think it's a Haiku bug regarding signals or some such. In the openjdk case appending tee processes are left running and block the unmount. I've been manually killing them with `kill tee` and then force unmount to continue. Apart from the delay this causes, that has worked reliably. The different versions of openjdk cause different numbers of such tee processes hanging, but it's always the exact same pattern. Something is always piped into tee to output to some file, so signal propagation in such cases should be reviewed. It might also be a bash or a bash port issue.
