### ISSUE TITLE
live iso: `touch foo && cp -a foo bar` copies the file but prints an error

### ISSUE THREAD

**Issue by avih** [haikuports/haikuports#5394]
Steps to reproduce:

- Boot the live ISO - tested inside virtualbox with nightly 54702 and 54629 - both 32 and 64 bits.
- Press enter at the language selection screen.
- Open a terminal.
- Write the following command: `touch foo && cp -a foo bar` (I also tried `--archive` or `--preserve=all` instead of `-a` - same result as below).

Expected result:
- The file copied, no output.

Actual result:
- The file is copied, but the following message is printed: `cp: preserving times for 'bar': invalid argument`, and the exit status is 1 (failure).

This was confirmed also using live USB boot by @bitigchi on IRC.

**Comment by lonemadmax** [comment]
You are asking to preserve metadata in the copy but the underlying filesystem or something in between does not like setting the timestamp. May be expected with whatever magic is used in the live image or may be an unknown bug, but it looks like it's for https://dev.haiku-os.org/, not haikuports.

If you don't care about the timestamps you can workaround it adding `--no-preserve=timestamps`.

**Comment by waddlesplash** [comment]
Indeed, this is likely a bug in `write_overlay` which is an internal Haiku component, so please report it to dev.haiku-os.org, not here.

**Comment by avih** [comment]
I don't have an account there and I probably won't open one only to report this issue, because I don't use Haiku regularly. When mentioned it on IRC I was requested to file an issue in this repo.

I understand your point, so if you have access I'd appreciate if you could open a bug there. I probably won't.

Thanks.

**Comment by humdingerb** [comment]
I created ticket [#16606](https://dev.haiku-os.org/ticket/16606) for this.

**Comment by avih** [comment]
Much appreciated.
