### ISSUE TITLE
Add Sinus and patch

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#544]
[sinus-0.1.3.tar.gz](https://github.com/haikuports/haikuports/files/200831/sinus-0.1.3.tar.gz)

**Comment by richienyhus** [comment]
While Sinus can be found [elsewhere](ftp://ftp.gwdg.de/pub/linux/misc/blinux/sinus-0.1.3.tar.gz) on the Internet, this version allegedly contains fixes for the BeOS.

**Comment by waddlesplash** [comment]
The changes don't appear to be too substantial, it should just be added to HaikuPorts with a patch.
