### ISSUE TITLE
libboost-1.57.0.recipe can't be build on hrev54742 x86_gcc2

### ISSUE THREAD

**Issue by lorglas** [haikuports/haikuports#5462]
the libboost 1.57.0 can't be build on hrev54742 x86_gcc2

Checking if any dependency-infos need to be updated ...
Looking for stale dependency-infos ...
Warning: skipping boost-1.57.0, as it is broken on the target architecture.
Error: No version of boost can be built

this is needed to build wesnoth and some more.

**Comment by pulkomandy** [comment]
Are you trying to build it for gcc2? That's not possible (boost use very modern C++ features). But the _x86 version should work.

Morever, version 1.57 is super old, you should use the "boost169" recipe instead.

So try this:

haikuporter boost169_x86

Or just install it from the depot (it will save a lot of compiling time): https://depot.haiku-os.org#!/pkg/boost169_x86/haikuports/1/69/0/-/2/x86_gcc2?bcguid=bc259-EMKI

**Comment by Begasus** [comment]
@lorglas is this fine now?

**Comment by lorglas** [comment]
I think so.
