### ISSUE TITLE
GNU tar gives an error when unpacking the archive with hardlink

### ISSUE THREAD

**Issue by diger** [haikuports/haikuports#5463]
For example [libxml](http://xmlsoft.org/sources/libxml2-2.9.10.tar.gz)
Several years ago I received a patch from Siaržuk Žarski fixing this problem.
[tar.30.10.12-hardlinks.diff.zip](https://github.com/haikuports/haikuports/files/5635738/tar.30.10.12-hardlinks.diff.zip)

**Comment by diversys** [comment]
Apparently, an option to replace hardlinks was accidentally removed in 208a8aa3a071a696e126829b159c07e621b57771.
Restored it in 9665e4c01.

Also hi! :)

**Comment by Begasus** [comment]
@diversys this can be closed?
