### ISSUE TITLE
Otter browser: deadlock

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#5471]
Haiku hrev54752
otter_browser-1.0.81.333-1-x86_64.hpkg
qtwebkit-5.212.0~pre20200915-1-x86_64.hpkg
qthaikuplugins-5.15.1.3-1-x86_64.hpkg
qt5-5.15.1-2-x86_64.hpkg

Otter window freeze forever because of deadlock.

![screenshot13](https://user-images.githubusercontent.com/45505339/101273471-04a0a580-37d9-11eb-976c-244dcd8acdc6.png)
![screenshot10](https://user-images.githubusercontent.com/45505339/101273466-ffdbf180-37d8-11eb-8271-43b18f36a341.png)
![screenshot11](https://user-images.githubusercontent.com/45505339/101273468-01a5b500-37d9-11eb-81a5-11866d4b1f1d.png)
![screenshot12](https://user-images.githubusercontent.com/45505339/101273469-036f7880-37d9-11eb-9331-b86ccffd311c.png)

**Comment by threedeyes** [comment]
Is this a reproducible bug?

**Comment by X547** [comment]
I accidentally get it. Currently I don't know way to reproduce.

**Comment by threedeyes** [comment]
Ok.
Deadlock happens not in the Otter code, but in the platform plugin - most likely a bug in the QPA.

**Comment by X547** [comment]
It looks like another thread is attempting to change window title while window is quitting.

**Comment by threedeyes** [comment]
> It looks like another thread is attempting to change window title while window is quitting.

Did this happen when the window was closed?

**Comment by X547** [comment]
Yes I think. But window was still displayed with stopped updating.
