### ISSUE TITLE
APFS: Implement for Haiku

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#5480]
APFS is Apple's next-generation '64-bit oriented' File System for Apple Watch, Apple TV, iPhone, iPad, MacBook, iMac, and Mac Pro  optimized for flash and solid-state storage devices. APFS replaces Apple's HFS+ file system (i.e. on all current and newer devices).

NOTE: APFS implementation may not perform efficiently or properly on Haiku 32-bit platforms (i.e. if ported). Read/write/modify and file attributes may depend entirely on underlying APFS driver support. We should also review read support for Apple HFS+ for legacy reasons. Apple's HFS read support was dropped as of macOS 10.15 stable release.
 
1. Ref: https://dev.haiku-os.org/ticket/16333
2. Ref: https://github.com/sgan81/apfs-fuse

**Comment by bugcrazy** [comment]
Here interesting apfstests and code links for references or ideas:

https://github.com/linux-apfs/apfstests

https://github.com/orgs/linux-apfs/repositories

**Comment by kenmays** [comment]
Migrate this to GSoC for sponsorship.
