### ISSUE TITLE
Add some sort of "used by" in the recipes?

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#5481]
Maybe adding some part in the recipes (not used by haikuporter) could help narrow down the need to search which recipe is being used by others, and could help in checking if those recipe still build fine with the changes?

**Comment by Begasus** [comment]
As an example, "lib:libarmadillo$secondaryArchSuffix" is being used by gdal and mlpack, knowing this upfront would help the need to search what is using "lib:libarmadillo$secondaryArchSuffix"?

**Comment by Begasus** [comment]
This or a check on PR's mentioning successful checks on the other builds (mentioning their architecture):
Exampe:
```
- [x] gdal (64 bit)
- [x] mlpack (64 bit)
```

**Comment by korli** [comment]
`pkgman search -r lib:libarmadillo`
=> gdal, mlpack, mlpack_cli

**Comment by Begasus** [comment]
Yeah, but opencv deppends on gdal (which (gdal) needs at least a revbump for armadillo)

**Comment by korli** [comment]
I don't think you need to check opencv, with no direct dependency on armadillo.

**Comment by Begasus** [comment]
I know ;) gdal didn't change after a revbump and opencv is still ok with that, I meant that gdal (without a revbump) can't be installed with the newer armadillo hence opencv can't either

**Comment by korli** [comment]
yes, but you won't find this information by looking at the recipes, but at the built packages (per architecture)

**Comment by Begasus** [comment]
Granted, it takes some time to check for that kind of information, maybe a checklist added to the PR could provide this kind of information also?

**Comment by waddlesplash** [comment]
There is a script in the `haikuporter` repo that attempts to find (and bump revisions of) all recipes that depend on another. It is not perfect, but the best that can be done without `pkgman -r`.

**Comment by Begasus** [comment]
Closing this one as invalid (some solutions around for it)
