### ISSUE TITLE
Flesh out Dolphin recipe

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#5498]
In https://github.com/haikuports/haikuports/commit/7a0913706247ba291397e15183d78062481d09ee I added a stub recipe for Dolphin along with an actual patch, upstreamed in https://github.com/dolphin-emu/dolphin/pull/9323. Unfortunately I do not really have time to finish the recipe, so someone else will have to take that up...

Notably:
 1. You may not want to turn on the SDL support, it may cause the frontend to crash. (I did not test either way.)
 2. We want to use packaged versions of most of the thinks CMake looks for, of course, but at least a few, we will have to stick with Dolphin's bundled versions (e.g. SFML and Minizip, which I modified in the patch as necessary.)

I recommend reading through the CMake output carefully (and doing a clean build in-between modifications to REQUIRES/BUILD_REQUIRES) to determine what dependencies can be added.

**Comment by threedeyes** [comment]
![Dolphine](https://user-images.githubusercontent.com/2559260/102964640-d7bdf380-4537-11eb-816a-3f3c587232e1.png)

**Comment by threedeyes** [comment]
![dolphin2](https://user-images.githubusercontent.com/2559260/102966947-a72c8880-453c-11eb-90a0-711866988fce.png)

**Comment by threedeyes** [comment]
Fix build and add application icon:  https://github.com/haikuports/haikuports/commit/e2d57f2a19335e62313e3e40849f33ddd77ecd7c

**Comment by waddlesplash** [comment]
Now we need to just port Cubeb so we can actually have audio output ;)

**Comment by threedeyes** [comment]
>Now we need to just port Cubeb so we can actually have audio output ;)

Hm, or try rework windows OpenAL backend -https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/AudioCommon/OpenALStream.cpp ?

**Comment by threedeyes** [comment]
And keyboard controller not worked for me, but GamePad controller works fine.

**Comment by waddlesplash** [comment]
Yeah, same here. I did not look into that. It probably has something to do with SDL vs. Qt keyboard events or something like that, or there is something else we did not implement.

IIRC, the OpenAL backend uses some strange OpenAL variant that is not stock. Cubeb is also used in Mozilla products (Firefox) as well as an increasing number of open-source projects, so we should just port it at some point anyway.

**Comment by threedeyes** [comment]
> Now we need to just port Cubeb so we can actually have audio output ;)

Done! Audio works!

![Dolphin_cubeb](https://user-images.githubusercontent.com/2559260/103056464-bc5ef100-45e8-11eb-9054-0f0f78cbe1df.png)

**Comment by waddlesplash** [comment]
Well that was fast! Maybe Cubeb will also accept PR to add support for Haiku directly to upstream? :)

Now we just need to actually port DRM...

**Comment by threedeyes** [comment]
This is still dirty code. I only implemented the minimum functionality for 16 bit stereo. The code needs to be improved. But the sound is already playing!

**Comment by threedeyes** [comment]
Done.
1. cubeb recipe added (now u16 and float streams supported up to 32 channels) - https://github.com/haikuports/haikuports/commit/384f269798d253589db3b326fe16b066b4b6c2e8
2.  Dolphin use system cubeb, miniupnpc and ffmpeg libs - https://github.com/haikuports/haikuports/commit/d9feb65302a80a69170826e9bf8248177c498234
