### ISSUE TITLE
Blender is broken on 32bit

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#5500]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/870/builds/1490.log

Think this is the root cause: undefined reference to `___tls_get_addr'

**Comment by extrowerk** [comment]
export LDFLAGS=“-lssp”
maybe?

**Comment by Begasus** [comment]
Wanted to have a go at it yesterday, but it's a monster to build, only thing left is to push changes and see if the buildbot is ok with it (from my side, and if no one steps up check do a local build) :)

**Comment by Begasus** [comment]
Pushed the change, lets see how it goes ...

**Comment by Begasus** [comment]
Didn't work, so have to revert these last changes on a next push ...

**Comment by Begasus** [comment]
Maybe -DCMAKE_SKIP_RPATH=ON

_Originally posted by @korli in https://github.com/haikuports/haikuports/issues/3061#issuecomment-422427687_
