### ISSUE TITLE
retroshare unresolvable issue for s6_addr16

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#5511]
Marked the recipe as broken in: https://github.com/haikuports/haikuports/pull/5510

**Comment by korli** [comment]
Should be handled in master und beta3:
https://github.com/haiku/haiku/commit/7335fb0d5c8025c9f46f978085cfdabc7da0da99

**Comment by korli** [comment]
should be fixed in c9cb90a1059689b4225370776f710b354eab6e23
