### ISSUE TITLE
Non-standard license

### ISSUE THREAD

**Issue by tommyjanna** [haikuports/haikuports#5541]
Hey,

I'm currently at work porting the program, sl.

However, the accompanying [LICENSE](https://github.com/mtoyoda/sl/blob/5.02/LICENSE) file is not a standard distribution that haikuporter recognizes. It seems to be a slightly modified ISC license from my best perspective.

What's the general procedure for such an issue? Should I try contacting the dev and asking him to use a standard license?
Thanks.

EDIT: On most Linux distro recipe files, the license field usually just reads "custom" or some sort.

**Comment by augiedoggie** [comment]
https://github.com/haikuports/haikuports/wiki/HaikuPorter-BuildRecipes#license

**Comment by tommyjanna** [comment]
What should the LICENSE variable be set to in this case, given the license is included next to the recipe?

**Comment by augiedoggie** [comment]
Put the text of the license into a licenses/SL file and then use SL in the variable.  (There might be a better name than SL, that's just an example)

**Comment by tommyjanna** [comment]
Thank you very much for explaining this to me. I got it working. And thanks for pointing me to an example. I will look to other packages as an example in the future.
