### ISSUE TITLE
BeGet - crash when closing app

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#558]
After download is completed, closing app causes a crash.

**Comment by humdingerb** [comment]
haikuports only hosts recipes. If you find anything wrong with a recipe, file an issue in this bugtracker. Bugs and enhancements on the software itself have to be reported at that software's bugtracker.

This particular bug is already filed at https://github.com/HaikuArchives/BeGet/issues/8

You can work around this bug by making sure to clear the download list before quitting. There's also a setting in the preferences to auto-remove an item after download.
