### ISSUE TITLE
List of recipes using cmake but not passing $cmakeDirArgs

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#5594]
Passing cmakeDirArgs allows us in many cases to simplify our recipes.
Passing it is useful for libs and for cli programs, but not necessarily in other cases, like gui apps.
List made today with up-to-date git repo.
The version number is just for information. If there is a newer recipe with cmakeDirArgs then no change required (i was unable to craft a find/grep command to check that too).

- [ ] /app-admin/conky/conky-1.11.6_pre.recipe
- [ ] /app-admin/keepassxc/keepassxc-2.6.2.recipe
- [ ] /app-arch/brotli/brotli-1.0.9.recipe
- [ ] /app-arch/zopfli/zopfli-1.0.3.recipe
- [ ] /app-crypt/gpgme/gpgme-1.12.0.recipe
- [ ] /app-crypt/minisign/minisign-0.7.recipe
- [ ] /app-crypt/qca/qca-2.2.1.recipe
- [ ] /app-emulation/aqemu/aqemu-0.9.2.recipe
- [ ] /app-emulation/previous/previous-1.8~svn.recipe
- [ ] /app-forensics/snowman/snowman-0.1.3.recipe
- [ ] /app-i18n/tagainijisho/tagainijisho-1.2~20180610.recipe
- [ ] /app-i18n/uchardet/uchardet-0.0.6.recipe
- [ ] /app-misc/binwalk/binwalk-2.2.0.recipe
- [ ] /app-misc/far/far-2~git.recipe
- [ ] /app-misc/peaclock/peaclock-0.1.7.recipe
- [ ] /app-office/calligra/calligra-3.2.1.recipe
- [ ] /app-office/calligraplan/calligraplan-3.2.2.recipe
- [ ] /app-office/scribus/scribus-1.5.6.1.recipe
- [ ] /app-pda/libplist/libplist-2.1.0.recipe
- [ ] /app-text/calibre/calibre-3.48.0.recipe
- [ ] /app-text/coolreader3/coolreader3-3.1.2.52.recipe
- [ ] /app-text/ebook_tools/ebook_tools-0.2.2.recipe
- [ ] /app-text/htmltidy/tidy57-5.7.0~git.recipe
- [ ] /app-text/multimarkdown/multimarkdown-6.4.0.recipe
- [ ] /app-text/podofo/podofo-0.9.6.recipe
- [ ] /app-text/sigil/sigil-0.9.14.2.recipe
- [ ] /app-text/xpdf/xpdf-4.00.recipe
- [ ] /dev-cpp/clucene/clucene-2.3.3.4.recipe
- [ ] /dev-cpp/eigen/eigen-3.3.9.recipe
- [ ] /dev-cpp/gflags/gflags-2.2.1.recipe
- [ ] /dev-cpp/websocketpp/websocketpp-0.8.1.recipe
- [ ] /dev-cpp/yaml_cpp/yaml_cpp-0.6.3.recipe
- [ ] /dev-db/libmysqlclient/libmysqlclient-6.1.6.recipe
- [ ] /dev-db/sqlitebrowser/sqlitebrowser-3.11.2.recipe
- [ ] /dev-embedded/libftdi/libftdi-1.4.recipe
- [ ] /dev-embedded/stlink/stlink-1.6.1.recipe
- [ ] /dev-games/box2d/box2d-2.3.1.recipe
- [ ] /dev-games/cegui/cegui-0.8.7.recipe
- [ ] /dev-games/mygui/mygui-3.2.3~git.recipe
- [ ] /dev-games/physfs/physfs-3.0.2.recipe
- [ ] /dev-lang/fpc/fpc-3.2.0.recipe
- [ ] /dev-lang/fpc_bootstrap/fpc_bin-3.2.0.recipe
- [ ] /dev-lang/julia/julia-0.3.5.recipe
- [ ] /dev-lang/rust/rust-1.48.0.recipe
- [ ] /dev-lang/swift_lang/swift_lang-4.1.0~git.recipe
- [ ] /dev-libs/caffe/caffe-1.0.recipe
- [ ] /dev-libs/cereal/cereal-1.2.2.recipe
- [ ] /dev-libs/libclaw/libclaw-1.7.4.recipe
- [ ] /dev-libs/libconfig/libconfig-1.7.2.recipe
- [ ] /dev-libs/libgit2/libgit2-0.27.0.recipe
- [ ] /dev-libs/libical/libical-2.0.0.recipe
- [ ] /dev-libs/libsolv/libsolv-0.7.2.recipe
- [ ] /dev-libs/libxml2/libxml2-2.9.10.recipe
- [ ] /dev-libs/libyajl/libyajl-2.1.0.recipe
- [ ] /dev-libs/libzip/libzip-0.10.1.recipe
- [ ] /dev-libs/msgpack_c_cpp/msgpack_c_cpp-3.2.0.recipe
- [ ] /dev-libs/pegtl/pegtl-2.3.3.recipe
- [ ] /dev-libs/tinyxml2/tinyxml2-7.0.1.recipe
- [ ] /dev-libs/unittest++/unittest++-1.6.1.recipe
- [ ] /dev-libs/vc/vc-1.4.1.recipe
- [ ] /dev-libs/xapian/xapian-1.4.13.recipe
- [ ] /dev-lua/toluapp/tolua++-1.0.recipe
- [ ] /dev-qt/prison/prison-5.65.0.recipe
- [ ] /dev-qt/qmdnsengine/qmdnsengine-0.1.0.recipe
- [ ] /dev-qt/qt5/qt5-5.15.2.recipe
- [ ] /dev-qt/qt6/qt6-6.0.0.recipe
- [ ] /dev-util/apitrace/apitrace-7.1.recipe
- [ ] /dev-util/bear/bear-2.4.2.recipe
- [ ] /dev-util/clazy/clazy-1.6.recipe
- [ ] /dev-util/cutter/cutter-1.12.0.recipe
- [ ] /dev-util/keystone/keystone-0.9.1.recipe
- [ ] /dev-util/lxqt_build_tools/lxqt_build_tools-0.6.0.recipe
- [ ] /dev-util/redasm/redasm-2.1.1.recipe
- [ ] /dev-util/sourcetrail/sourcetrail-2019.4.102.recipe
- [ ] /games-action/aaaa/aaaa-1.1.recipe
- [ ] /games-action/lugaru/lugaru-1.2.recipe
- [ ] /games-action/minetest/minetest-5.3.0.recipe
- [ ] /games-action/openclonk/openclonk-9.0~git.recipe
- [ ] /games-action/supermariowar/supermariowar-beta1.1.recipe
- [ ] /games-action/supertuxkart/supertuxkart-1.2.recipe
- [ ] /games-action/xash3d/xash3d-0.19.3~git.recipe
- [ ] /games-arcade/astromenace/astromenace-1.4.1.recipe
- [ ] /games-arcade/caveexpress/caveexpress-2.5.1.recipe
- [ ] /games-arcade/cavepacker/cavepacker-2.5.1.recipe
- [ ] /games-arcade/freegish/freegish-1.0~20170110.recipe
- [ ] /games-arcade/gish/gish-1.2~git.recipe
- [ ] /games-arcade/openclaw/openclaw-1.0.3_20190402.recipe
- [ ] /games-arcade/plee_the_bear/plee_the_bear-0.7.1.recipe
- [ ] /games-arcade/slimevolley/slimevolley-2.4.2.recipe
- [ ] /games-arcade/vangers/vangers-1.0.0~git.recipe
- [ ] /games-arcade/vvvvvv/vvvvvv-2.3~git.recipe
- [ ] /games-board/dreamchess/dreamchess-0.3.0.recipe
- [ ] /games-board/gambit/gambit-1.0.4.recipe
- [ ] /games-emulation/dolphin/dolphin-5.0.13178.recipe
- [ ] /games-emulation/ppsspp/ppsspp-1.10.3.recipe
- [ ] /games-engines/fifechan/fifechan-0.1.5.recipe
- [ ] /games-engines/openmw/openmw-0.45.0.recipe
- [ ] /games-engines/solarus/solarus-1.6.4.recipe
- [ ] /games-fps/dhewm3/dhewm3-1.5.1.recipe
- [ ] /games-fps/gzdoom/gzdoom-3.8.2.recipe
- [ ] /games-fps/openjk_academy/openjk_academy-2020.03.09.recipe
- [ ] /games-fps/openjk_outcast/openjk_outcast-2020.03.09.recipe
- [ ] /games-fps/serious_sam/serious_sam-1.10~git.recipe
- [ ] /games-fps/shockolate/shockolate-0.7.7.recipe
- [ ] /games-fps/yamagi-quake2/yamagi_quake2-7.45.recipe
- [ ] /games-kids/gcompris/gcompris-0.70.recipe
- [ ] /games-kids/tuxmath/tuxmath-1.7.2.recipe
- [ ] /games-kids/tuxtype/tuxtype2-1.5.2.recipe
- [ ] /games-mud/mudlet/mudlet-4.0.3.recipe
- [ ] /games-puzzle/tbe/tbe-0.9.3.1.recipe
- [ ] /games-roguelike/sais/sais-1.6.3~git.recipe
- [ ] /games-rpg/arx_libertatis/arx_libertatis-1.2~git.recipe
- [ ] /games-rpg/devilutionx/devilutionx-1.1.0.recipe
- [ ] /games-rpg/flare/flare-0.19.recipe
- [ ] /games-simulation/corsix_th/corsix_th-0.62.recipe
- [ ] /games-simulation/thepowdertoy/thepowdertoy-91.5.330.recipe
- [ ] /games-sports/speed-dreams/speed_dreams-2.2.2.recipe
- [ ] /games-strategy/0ad/0ad-0.0.23b~alpha.recipe
- [ ] /games-strategy/colobot/colobot-0.1.12.recipe
- [ ] /games-strategy/colobot_data/colobot_data-0.1.12.recipe
- [ ] /games-strategy/ja2_stracciatella/ja2_stracciatella-0.16.1.recipe
- [ ] /games-strategy/julius/julius-1.3.1.recipe
- [ ] /games-strategy/openxcom/openxcom-1.0.recipe
- [ ] /games-strategy/vcmi/vcmi-0.99.recipe
- [ ] /games-strategy/wesnoth/wesnoth-1.12.6.recipe
- [ ] /haiku-apps/beae/beae-1.2.recipe
- [ ] /haiku-apps/beezer/beezer-0.99.recipe
- [ ] /haiku-apps/beget/beget-1.2.3.recipe
- [ ] /haiku-apps/cmake_haiku/cmake_haiku-git.recipe
- [ ] /haiku-apps/haikutodo/haikutodo-0.0.recipe
- [ ] /haiku-apps/hare/hare-1.1.1.recipe
- [ ] /haiku-apps/kovel/kovel-1.0.0.recipe
- [ ] /haiku-apps/renga/renga-1.2.1~git.recipe
- [ ] /haiku-apps/sawteeth/sawteeth-1.4.1.recipe
- [ ] /haiku-apps/voxophone/voxophone-1.0.recipe
- [ ] /haiku-games/criticalmass/criticalmass-2.2.recipe
- [ ] /haiku-games/nogravity/nogravity-2.0.recipe
- [ ] /haiku-games/superfreecell/superfreecell-0.1.0.recipe
- [ ] /haiku-libs/ale/ale-0.9.1.recipe
- [ ] /haiku-libs/haikuwebkit/haikuwebkit-1.7.1.recipe
- [ ] /kde-apps/blinken/blinken-20.12.0.recipe
- [ ] /kde-apps/bovo/bovo-20.12.0.recipe
- [ ] /kde-apps/granatier/granatier-20.12.0.recipe
- [ ] /kde-apps/kapman/kapman-20.12.0.recipe
- [ ] /kde-apps/katomic/katomic-20.12.0.recipe
- [ ] /kde-apps/kblocks/kblocks-20.12.0.recipe
- [ ] /kde-apps/kbreakout/kbreakout-20.12.0.recipe
- [ ] /kde-apps/kdiamond/kdiamond-20.12.0.recipe
- [ ] /kde-apps/kgoldrunner/kgoldrunner-20.12.0.recipe
- [ ] /kde-apps/kig/kig-20.12.0.recipe
- [ ] /kde-apps/kigo/kigo-20.12.0.recipe
- [ ] /kde-apps/kjumpingcube/kjumpingcube-20.12.0.recipe
- [ ] /kde-apps/klickety/klickety-20.12.0.recipe
- [ ] /kde-apps/klines/klines-20.12.0.recipe
- [ ] /kde-apps/kmahjongg/kmahjongg-20.12.0.recipe
- [ ] /kde-apps/knavalbattle/knavalbattle-20.12.0.recipe
- [ ] /kde-apps/knights/knights-20.12.0.recipe
- [ ] /kde-apps/konsole/konsole-20.12.0.recipe
- [ ] /kde-apps/kreversi/kreversi-20.12.0.recipe
- [ ] /kde-apps/kshisen/kshisen-20.12.0.recipe
- [ ] /kde-apps/ksudoku/ksudoku-20.12.0.recipe
- [ ] /kde-apps/ktuberling/ktuberling-20.12.0.recipe
- [ ] /kde-apps/lskat/lskat-20.12.0.recipe
- [ ] /kde-apps/okular/okular-20.08.0.recipe
- [ ] /kde-apps/umbrello/umbrello-20.12.0.recipe
- [ ] /kde-base/gwenview/gwenview-20.12.0.recipe
- [ ] /kde-base/kate/kate-20.12.0.recipe
- [ ] /kde-base/kolourpaint/kolourpaint-20.12.0.recipe
- [ ] /kde-base/kstars/kstars-3.5.0.recipe
- [ ] /kde-base/kwave/kwave-20.12.0.recipe
- [ ] /kde-base/kwrite/kwrite-20.12.0.recipe
- [ ] /kde-base/marble/marble-20.12.0.recipe
- [ ] /kde-frameworks/extra-cmake-modules/extra_cmake_modules-5.77.0.recipe
- [ ] /kde-misc/kdiff3/kdiff3-1.8.4.recipe
- [ ] /kde-misc/krusader/krusader-2.7.2.recipe
- [ ] /mail-client/trojita/trojita-0.7.0~git.recipe
- [ ] /media-gfx/blender/blender-2.79b.recipe
- [ ] /media-gfx/curaengine/curaengine-4.8.0.recipe
- [ ] /media-gfx/digikam/digikam-7.1.0.recipe
- [ ] /media-gfx/drawpile/drawpile-2.1.17.recipe
- [ ] /media-gfx/flameshot/flameshot-0.8.5.recipe
- [ ] /media-gfx/graphite2/graphite2-1.3.14.recipe
- [ ] /media-gfx/krita/krita-4.4.1.recipe
- [ ] /media-gfx/kumoworks/kumoworks-1.0.1~git.recipe
- [ ] /media-gfx/opentoonz/opentoonz-1.1.2.recipe
- [ ] /media-gfx/photivo/photivo-0~pre20201120.recipe
- [ ] /media-libs/allegro/allegro-4.4.3.1.recipe
- [ ] /media-libs/assimp/assimp-5.0.1.recipe
- [ ] /media-libs/chromaprint/chromaprint-1.5.0.recipe
- [ ] /media-libs/coin/coin-4.0.0.recipe
- [ ] /media-libs/devil/devil-1.8.0.recipe
- [ ] /media-libs/game-music-emu/game_music_emu-0.6.3.recipe
- [ ] /media-libs/gosu/gosu-0.8.7.2.recipe
- [ ] /media-libs/gst_libav/gst_libav-1.18.0.recipe
- [ ] /media-libs/gst_plugins_bad/gst_plugins_bad-1.18.0.recipe
- [ ] /media-libs/gst_plugins_good/gst_plugins_good-1.18.0.recipe
- [ ] /media-libs/gst_plugins_ugly/gst_plugins_ugly-1.18.0.recipe
- [ ] /media-libs/harfbuzz/harfbuzz-2.1.3.recipe
- [ ] /media-libs/harfbuzz/harfbuzz-2.7.4.recipe
- [ ] /media-libs/im/im-3.13.recipe
- [ ] /media-libs/im/im-3.8.recipe
- [ ] /media-libs/lensfun/lensfun-0.3.2.recipe
- [ ] /media-libs/lib3ds/lib3ds-2.0.0.recipe
- [ ] /media-libs/libcoverart/libcoverart-1.0.0.recipe
- [ ] /media-libs/libcuefile/libcuefile-475.recipe
- [ ] /media-libs/libebur128/libebur128-1.2.4.recipe
- [ ] /media-libs/libharu/libharu-2.3.0.recipe
- [ ] /media-libs/libinstpatch/libinstpatch-1.1.3.recipe
- [ ] /media-libs/libreplaygain/libreplaygain-475.recipe
- [ ] /media-libs/libsdl2/libsdl2-2.0.10.recipe
- [ ] /media-libs/libxcm/libxcm-0.5.4.recipe
- [ ] /media-libs/musicbrainz/musicbrainz-5.1.0.recipe
- [ ] /media-libs/openal/openal-1.13.0.recipe
- [ ] /media-libs/opencolorio/opencolorio-1.1.1.recipe
- [ ] /media-libs/opencv/opencv3-3.4.3.recipe
- [ ] /media-libs/openexr/openexr-2.4.1.recipe
- [ ] /media-libs/openimageio/openimageio-1.7.15.recipe
- [ ] /media-libs/openjpeg/openjpeg-2.4.0.recipe
- [ ] /media-libs/opensubdiv/opensubdiv-3.4.3.recipe
- [ ] /media-libs/partio/partio-1.1.0.recipe
- [ ] /media-libs/ptex/ptex-2.1.28.recipe
- [ ] /media-libs/soxr/soxr-0.1.3.recipe
- [ ] /media-libs/taglib/taglib-1.11.1.recipe
- [ ] /media-libs/vigra/vigra-1.11.1.recipe
- [ ] /media-libs/x265/x265-3.4.recipe
- [ ] /media-sound/audacity/audacity-2.1.2.recipe
- [ ] /media-sound/cantata/cantata-2.4.1.recipe
- [ ] /media-sound/csound/csound-6.13.0.recipe
- [ ] /media-sound/flacon/flacon-6.1.0.recipe
- [ ] /media-sound/fluidlite/fluidlite-1.0.0.recipe
- [ ] /media-sound/fluidsynth/fluidsynth2-2.1.1.recipe
- [ ] /media-sound/lmms/lmms-1.2.2.recipe
- [ ] /media-sound/musepack_tools/musepack_tools-475.recipe
- [ ] /media-sound/musescore/musescore-3.3.4.recipe
- [ ] /media-sound/spotify_qt/spotify_qt-2.5~git.recipe
- [ ] /media-video/avidemux/avidemux-2.7.6.recipe
- [ ] /media-video/handbrake/handbrake-1.2.2.recipe
- [ ] /media-video/qmplay2/qmplay2-20.12.16.recipe
- [ ] /media-video/qtav/qtav-1.12.0.recipe
- [ ] /media-video/subtitlecomposer/subtitlecomposer-0.7.0.recipe
- [ ] /net-im/psi_plus/psi_plus-1.4.1407.recipe
- [ ] /net-im/qtox/qtox-1.17.3.recipe
- [ ] /net-im/quaternion/quaternion-0.0.9.4e.recipe
- [ ] /net-im/telegram-desktop/telegram_desktop-2.5.2.recipe
- [ ] /net-irc/quassel/quassel-0.14~git.recipe
- [ ] /net-irc/weechat/weechat-2.8.recipe
- [ ] /net-libs/libcec/libcec-4.0.3.recipe
- [ ] /net-libs/libp8_platform/libp8_platform-2.1.0.1.recipe
- [ ] /net-libs/librsync/librsync-2.0.0.recipe
- [ ] /net-libs/libwebsockets/libwebsockets-3.0.0.recipe
- [ ] /net-libs/mbedtls/mbedtls-2.25.0.recipe
- [ ] /net-libs/miniupnpc/miniupnpc-2.1.recipe
- [ ] /net-misc/gerbera/gerbera-1.4.0.recipe
- [ ] /net-p2p/eiskaltdcpp/eiskaltdcpp-2.4.0.recipe
- [ ] /net-p2p/ktorrent/ktorrent-5.1.2.recipe
- [ ] /net-p2p/retroshare/retroshare-0.6.4.recipe
- [ ] /net-wireless/nitroshare/nitroshare-0.3.4.recipe
- [ ] /sci-calculators/speedcrunch/speedcrunch-0.12.0.recipe
- [ ] /sci-chemistry/maeparser/maeparser-1.2.3.recipe
- [ ] /sci-electronics/ktechlab/ktechlab-0.50.0~git.recipe
- [ ] /sci-electronics/qelectrotech/qelectrotech-0.7.0.recipe
- [ ] /sci-libs/mlpack/mlpack-3.4.2.recipe
- [ ] /sci-libs/openblas/openblas-0.3.9.recipe
- [ ] /sci-libs/opencascade/opencascade-0.18.3.recipe
- [ ] /sci-libs/primesieve/primesieve-7.4.recipe
- [ ] /sci-libs/scalapack/scalapack-2.0.2.recipe
- [ ] /sci-libs/superlu/superlu-5.2.1.recipe
- [ ] /sys-apps/dbus/dbus-1.12.20.recipe
- [ ] /sys-block/partitionmanager/partitionmanager-3.3.1~git.recipe
- [ ] /sys-devel/llvm/llvm9-9.0.1.recipe
- [ ] /sys-fs/android_file_transfer/android_file_transfer-3.9.recipe
- [ ] /sys-libs/zlib/zlib-1.2.11.recipe
- [ ] /www-client/otter-browser/otter_browser-1.0.02.recipe
- [ ] /x11-libs/cd/cd-5.12.recipe
- [ ] /x11-misc/synergy/synergy-1.5.0.recipe

**Comment by pulkomandy** [comment]
Note that cmakeDirArgs only works if the recipe uses CMake GNUInstallDirs (https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) or happens to use the same variable names as it.

This feature has been present for a long time in CMake, but is not mandatory and was originally not documented (they fixed that after we asked them how to handle our problems).

**Comment by waddlesplash** [comment]
Indeed. Some of these actually intentionally do not use GNUInstallDirs, and I imagine most of the rest will ignore it, but it is worth investigating.

**Comment by Begasus** [comment]
Quite a list to check ;) I gather some don't even use it and have been patched locally, some maybe could be send upstream (but I gather that for most there have been mentions upstream also, at least I've seen a few that had mentioning using GNUInstallDirs and didn't go through with it)

**Comment by kallisti5** [comment]
I opened this which is a good example of how confusing cmake gets around this stuff.

https://github.com/boostorg/boost_install/issues/49

**Comment by korli** [comment]
documentation issue: https://github.com/haikuports/haikuports/issues/2074

**Comment by korli** [comment]
IMO this list isn't useful, it's already outdated and doesn't filter recipes which actually use GNUInstallDirs.
