### ISSUE TITLE
Add recipe for bemobile

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#560]
https://github.com/ytmytm/beos-bemobile

Feature phone sync app. Could be modified to allow Creative and iPod mp4 players as well.

**Comment by Begasus** [comment]
Recipe is in the tree now: https://github.com/haikuports/haikuports/blob/bfb4d8231778873dae0a71aa66c1248ad0519c28/haiku-apps/bemobile/bemobile-0.9.recipe
