### ISSUE TITLE
[Wishlist] kiwix-tools

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#5605]
Kiwix is an application to read ZIM files, i.e. indexed MediaWiki archives, from Wikipedia or other such sites.

The main Kiwix application requires QtWebEngine, I believe, but there is the "tools" package which can run a server that you can then connect to from any web browser: https://github.com/kiwix/kiwix-tools

**Comment by Begasus** [comment]
Quick look reveals: kiwix-tools require kiwix-lib which require libzim ...

**Comment by waddlesplash** [comment]
I think other distros may package kiwix-lib and kiwix-tools together. libzim is indeed separate.

**Comment by Begasus** [comment]
Fixed in: https://github.com/haikuports/haikuports/pull/7491
