### ISSUE TITLE
Qt5 based browsers (Otter, Dooble) - issues rendering Haiku forum (regression)

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#5627]
Hello. I'm using Haiku 32 bit version, hrev54907. I found some regressions in the Qt browsers, after the last update of Qt (not sure if is related to the QtWebkit update from late december, or the more recent QtHaikuPlugins).  Basically, the issues was found when rendering the Haiku Forums itself:

1) the search bar don't show correctly.
2) the vertical scroll that appears when enter into a forum thread, it's rendered in the left, instead of the right. 

Search bar issue:
![image](https://user-images.githubusercontent.com/1316513/105642921-b5ecbf00-5e9d-11eb-92fe-fabeb4bdae79.png)

"virtual" scroll bar issue:

![image](https://user-images.githubusercontent.com/1316513/105642929-c00ebd80-5e9d-11eb-9f69-b4fc33550f96.png)

**Comment by unspacyar** [comment]
There is the screenshots:
Search bar issue: http://0x0.st/--cb.png
"virtual" scroll bar issue: http://0x0.st/--cc.png

**Comment by Begasus** [comment]
I guess this can be closed?

**Comment by unspacyar** [comment]
I guess yes. Anyways, today the forum is almost useless on Otter or Dooble browsers, but just because Discourse did not support them.  So, is a complete different problem :-)

You can go ahead an close it 👍 
Thank you!

**Comment by Begasus** [comment]
Thanks on reporting back! 👍
