### ISSUE TITLE
stat command does not show Birth entry

### ISSUE THREAD

**Issue by Katharina141** [haikuports/haikuports#5628]
Hello,

I have created a .txt file on desktop. In default file manager under list view (manually add "Created" to column) birth time = creation time is displayed.

But when I do with `stat` command it shows me this. Birth entry is not displayed, it shows an empty character -.

Access: 2021-01-21 02:24:51.235050163 +0000

Modify: 2021-01-21 02:24:49.608383509 +0000

Change: 2021-01-21 02:24:49.608383509 +0000

Birth: -

The problem can be fixed when using coreutils 8.31 and later, because since version 8.31 `stat` command can display the creation time when the file system stores it. ​https://lists.gnu.org/archive/html/coreutils/2019-03/msg00042.html

Since version 8.32 it can also display the birth entry via `ls` command
http://savannah.gnu.org/forum/forum.php?forum_id=9693

It would be good if always the latest coreutils version is used in Haiku.

**Comment by extrowerk** [comment]
Can you create a PR for this? Bumping the recipe shouldnt be too hard. Dont forget to test the bumped recipe.
