### ISSUE TITLE
Add Python Bindings to Qscintilla

### ISSUE THREAD

**Issue by JakobDev** [haikuports/haikuports#5643]
I have a Python Project which uses Qscintilla, so it would be nice if the Python bindings are added to the Qscintilla package. According to the [Arch Linux Package](https://github.com/archlinux/svntogit-packages/blob/packages/qscintilla/trunk/PKGBUILD) you can do this with sip-build.

**Comment by korli** [comment]
added in e86a9c5cdc6d302a67465a5c1fbad2252cc022d7
