### ISSUE TITLE
[Tuxpaint] svg support disable

### ISSUE THREAD

**Issue by mazbrili** [haikuports/haikuports#5654]
Dear folks..

i find that svg support on haiku is disable... can it be enable?
because some stamp cannot be loaded because of that

best regards

**Comment by korli** [comment]
Did you try to add librsvg as a dependency?

**Comment by Begasus** [comment]
@korli mentioned, librsvg hasn't been included that long, I think I did some checks on it earlier for TuxPaint but with no success, maybe it's improved by now

**Comment by mazbrili** [comment]
@korli  and @Begasus  i try to build librsvg and add to dependency but seem that not solve the problem..btw package build but  i'm not test it due see the message..  it seem it need libcairo...
i try another build and inform here 
![image](https://user-images.githubusercontent.com/25004583/106569582-4fcffe00-6567-11eb-9305-f4d0af2c0e8a.png)

**Comment by mazbrili** [comment]
.. i've create libsrvg package and install
modify recipe to libgdk_pixbuf cairo and sdl_pango make error build less.. but svg build still disable.. and now issue on klik next on stamp... hmm
![image](https://user-images.githubusercontent.com/25004583/106583222-7007b900-6577-11eb-97f5-22a7b48bc270.png)

**Comment by Begasus** [comment]
Haven't checked into this lately, but maybe related to: https://github.com/haikuports/haikuports/pull/1203 ?

**Comment by Begasus** [comment]
Some other things are missing in the recipe, how can I check if it loads the stamps you mention @mazbrili

**Comment by Begasus** [comment]
Seems to be ok now :)
![TuxPaint_svg](https://user-images.githubusercontent.com/16057090/107155479-e726be00-6978-11eb-8b39-51025a1ffc03.png)

**Comment by mazbrili** [comment]
IDK whats wrong but right now i cannot change stamp..  do i need waiting package rebuild?

**Comment by Begasus** [comment]
There hasn't been an update (yet), need to check on how dependencies are needed (on the side for librsvg, or on the side of TuxPaint). Give me some time (during the week I don't have that much time to spare) :)

**Comment by perepujal** [comment]
@mazbrili Just to understand: when you say you can not change stamps do you mean?:

a) you just see 6 penguins and can not display the animals, symbols, household, etc stamps categories
b) you can browse throught different stamp categories but can not select any stamp of those categories
c) other, please try to describe as acurately as you can

**Comment by mazbrili** [comment]
> @mazbrili Just to understand: when you say you can not change stamps do you mean?:
> 
> a) you just see 6 penguins and can not display the animals, symbols, household, etc stamps categories
> b) you can browse throught different stamp categories but can not select any stamp of those categories
> c) other, please try to describe as acurately as you can

sorry.. @perepujal  and @Begasus  maybe i'm not clear enough before.. 
today i try again procedure.. install tuxpaint again tuxpaint stamp and librsvg from depot..
right now i can change stamp.. i dont know what happen yesterday.(on virtualbox). but i'm pretty sure do installing both tuxpaint and tuxpaint-stamp.. i'm sorry for that..

for svg stamp issue.. i see it still there.. as you can see that fireman.png show on stamp but woman_chemist.svg dont seem load..
and this issue seem apply on all svg stamp.

![image](https://user-images.githubusercontent.com/25004583/107299791-cfe7ed80-6aaa-11eb-965b-430f4f8dc301.png)


> There hasn't been an update (yet), need to check on how dependencies are needed (on the side for librsvg, or on the side of TuxPaint). Give me some time (during the week I don't have that much time to spare) :)

thanks for your kindness and patient

**Comment by mazbrili** [comment]
i rebuild tuxpaint this time with haikuporter ...still show no svg support
svg stamp not load.. R1B2 (hrev 54154+123) 64bit
tuxpaint-0.9.25

![image](https://user-images.githubusercontent.com/25004583/107324226-4b14c800-6ada-11eb-8a13-4fc06b579ef8.png)

**Comment by mazbrili** [comment]
finally i can build with svg support  with some addition

![image](https://user-images.githubusercontent.com/25004583/107337148-8d470500-6aec-11eb-9186-b135cf08e270.png)

but with some warning

![image](https://user-images.githubusercontent.com/25004583/107337236-a8b21000-6aec-11eb-8a39-77ec234462b7.png)

all svg stamp show..

**Comment by mazbrili** [comment]
> There hasn't been an update (yet), need to check on how dependencies are needed (on the side for librsvg, or on the side of TuxPaint). Give me some time (during the week I don't have that much time to spare) :)

i'm really appreciate it.. thanks

**Comment by Begasus** [comment]
Indeed the libraries "librsvg" "libcairo" "libgdk_pixbuf" are needed for SVG support, for REQUIRES you need to add the missing glib deppendencies, as I still don't have time to see if this could be fixed from librsvg side or TP side feel free to make a PR for this :)

**Comment by mazbrili** [comment]
PR send https://github.com/haikuports/haikuports/pull/5714/files please check @Begasus

**Comment by mazbrili** [comment]
have been fixed by @Begasus  on https://github.com/haikuports/haikuports/pull/5733

**Comment by Begasus** [comment]
A big thanks to @mazbrili and @perepujal for stepping in here! :+1:
