### ISSUE TITLE
libx11 has no pkgconfig file

### ISSUE THREAD

**Issue by JakobDev** [haikuports/haikuports#5692]
I'm currently trying to build a program which needs libx11 but doesn't find it, even it's installed. After looking at it, I found out that libx11 has no .pc file.

**Comment by extrowerk** [comment]
FYI: Haiku don't have any X server, thus it can't drawn anything on Haiku. It is usable only to run programs on Haiku, but display their UI on a different, X11 enabled machine trough net (i wasnt even sucessful with that, but ymmv).

**Comment by JakobDev** [comment]
I had though that Haiku full supports the X server. Then I'm going to close this.
