### ISSUE TITLE
OpenMW: Unable to launch game after install

### ISSUE THREAD

**Issue by TheLastBilly** [haikuports/haikuports#5707]
OpenMW 0.45.0-6

After downloading the game from HaikuDepot, I get the following pop-up after launching it:
Could not open "Morrowind" (Missing libraries: libBulletCollision.so.3.05, libLinearMath.so.3.05).

**Comment by threedeyes** [comment]
Fixed in https://github.com/haikuports/haikuports/commit/8335a5670235bd8581045e2c8800d7728e201cd4
