### ISSUE TITLE
Add a recipe for libressl

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#574]
in dev-libs/libressl

Should be committed disabled to avoid clashes with openssl.

https://github.com/libressl-portable/portable
or
http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/

**Comment by pulkomandy** [comment]
It was not done yet because we are not sure our OS provides the required functionalities (proper random number generator, security features etc). LibreSSL relies on OpenBSD doing the right thing there, while OpenSSL will do things by itself and workaround problems in the OS.

**Comment by jessicah** [comment]
There is http://marc.info/?l=openbsd-bugs&m=140651474131660&w=2 fwiw. When I discussed merging Haiku support upstream, they weren't keen on merging until we had kernel support implemented. Not being a security developer, it's not something I wanted to really tackle.

**Comment by korli** [comment]
Well even then having a recipe working for the most part is useful. If that gets upstream is another issue.

**Comment by bugcrazy** [comment]
Added [arc4random](https://cgit.haiku-os.org/haiku/commit/?id=e86afc8f75ca705e0ad09775c4bd72d83d784ba1)  and implemented [getentropy](https://cgit.haiku-os.org/haiku/commit/?id=6bde05aebd17e946ea8af7ef4e55cb609aa4c68e)  in Haiku, it should be easier to accept patches for LibreSSL to support Haiku.

Would a better way be to open a [PR]( https://github.com/libressl/portable/pulls)  on github or send patches directly to OpenBSD?

**Comment by waddlesplash** [comment]
I think we don't have a reason to support more SSL libs; we've moved forward with OpenSSL 3 instead.
