### ISSUE TITLE
fontforge has no working GUI

### ISSUE THREAD

**Issue by Brunobasta** [haikuports/haikuports#5761]
This app is on HaikuDepot.
However this app wont start because it is missing the grafic parts of the app.
It should therefore taken away from HaikuDepot until it is working...

**Comment by extrowerk** [comment]
It is compiled correctly, the GUI is X11/Gnome based and none of them available for Haiku, so no GUI for us, but the cli functionality should work. Have you tested it?

**Comment by Brunobasta** [comment]
extrowerk <notifications@github.com> wrote:
> It is compiled correctly, the GUI is X11/Gnome based and none of them available 
> for Haiku, so no GUI for us, but the cli functionality should work. Have you 
tested it?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/haikuports/haikuports/issues/5761#issuecomment-791873898
How to create Fonts without a GUI? I did not get it?

**Comment by extrowerk** [comment]
> How to create Fonts without a GUI? I did not get it?

https://fontforge.org/docs/techref/cliargs.html

**Comment by extrowerk** [comment]
Just tested fontforge, seems to be working on 64 bit (obviously in cli).
Should we close this issue?

**Comment by Brunobasta** [comment]
Ah ok makes sense then.. but you should rename the App fontforge to fontforge CLI and give additional information about it in HaikuDepot. Thank you.

**Comment by korli** [comment]
Description adjusted with 7586dcd15d39c12aea9f6aad3290ae527e253fba
