### ISSUE TITLE
Grafx2 Immediate Crash Upon Opening

### ISSUE THREAD

**Issue by davidpgil** [haikuports/haikuports#5771]
Upon opening GrafX2 I get an immediate crash. Here is the crash report:
[https://pastebin.com/r5gmCMKL](https://pastebin.com/r5gmCMKL)

**Comment by kenmays** [comment]
@davidpgil - Do a "plgman full-sync" as of today. There were some recent SDL updates. Seems stable on R1B2 x86

**Comment by pulkomandy** [comment]
Maybe you need to delete your setting file in config/settings/grafx2. A corrupt settings file may lead to a crash (keep a backup of the files, if that fixes the problem, send them to me)

**Comment by korli** [comment]
[Grafx2 Immediate Crash Upon Opening.txt](https://github.com/haikuports/haikuports/files/6111003/Grafx2.Immediate.Crash.Upon.Opening.txt)

**Comment by davidpgil** [comment]
As @kenmays suggested I ran a `pkgman full-sync` and rebooted. This did not help my GrafX2 crash.

@pulkomandy suggested I delete `config/settings/grafx2` and after looking for a `grafx2` file/folder I noticed it doesnt exist. Keep in mind I have never gotten GrafX2 to work. It just crashes immediately for me.

**Comment by kenmays** [comment]
@davidpgil  - do a 'pkgman uninstall grafx2' and then 'pkgman install grafx2' - and recheck your 'config/settings/grafx2' directory.

You shouldn't get any errors on uninstalling/reinstalling the application.

**Comment by pulkomandy** [comment]
I still don't reproduce this issue. I tried deleting the settings and GrafX2 restarted just fine for me and recreated the directory.

Does it happen only on x86_64? What is the version of the package?

**Comment by davidpgil** [comment]
I am using the latest x86_64 version of Haiku. I uninstalled and reinstalled GrafX2 which is version 2.7-3 and the issue still occurs. No config is generated as well. It just crashes immediately.

**Comment by humdingerb** [comment]
FWIW, I get the same crash when
* clicking the "Open Grafx" button in HaikuDepot
* when launched the first time with QuickLaunch
* when starting from Terminal
* when starting from the Deskbar

I don't get a crash when starting via QuickLaunch (besides the first time after installing)

That's on 64bit Haiku, hrev54979. I haven't rebooted since I've just installed Grafx.

**Comment by humdingerb** [comment]
Hmmm... now it also always crashes when started via QuickLaunch... worked twice before...

**Comment by pulkomandy** [comment]
I have updated GrafX2 to version 2.8 with various fixes in that area. Let me know if that helps.

**Comment by davidpgil** [comment]
The immediate crash still occurs after a `full-sync` and I even tried reinstalling Grafx2. Are you testing this on a 64-bit machine?

**Comment by pulkomandy** [comment]
No, I don't have a 64bit install.

**Comment by korli** [comment]
it should be better handled in f0dafa02a504eace741a659cfbb05e6993144edb 
the buildbots seem to be stucked, new packages are not yet available.

**Comment by korli** [comment]
the x86_64 package is available

**Comment by kenmays** [comment]
@davidpgil - Tested the recent grafx2 (2.8-2) on x86_64. I opened and reviewed the app from the HaikuDepot, terminal, and deskbar - without issue. Seems resolved now.

**Comment by pulkomandy** [comment]
Yes, korli's change have fixed the problem (and are integrated upstream for the next release). Thanks!

**Comment by davidpgil** [comment]
Confirmed fixed! Thank you all. Great work!
