### ISSUE TITLE
[Wishlist] Please Port LDmicroQt

### ISSUE THREAD

**Issue by mazbrili** [haikuports/haikuports#5774]
### About LDMicro
LDmicro is a ladder logic editor, simulator and compiler for 8-bit microcontrollers. It can generate native code for Atmel AVR and Microchip PIC16 CPUs from a ladder diagram

source code is at https://github.com/FOSSEE/LDmicroQt

I wish i can port it but.. cmakelist modification haunted me..
so i wish somebdory at haikuport can make it..

thanks

**Comment by korli** [comment]
this doesn't seem popular, because it doesn't exist anywhere: https://repology.org/projects/?search=LDMicro

**Comment by mazbrili** [comment]
> this doesn't seem popular, because it doesn't exist anywhere: https://repology.org/projects/?search=LDMicro

yeah.. maybe not very popular.. but electrician maybe love it..
@threedeyes  wow.. awesome.  thank you.. did you rewrite cmakefile?

**Comment by threedeyes** [comment]
> wow.. awesome. thank you.. did you rewrite cmakefile?

https://pastebin.com/k2mX3XeM

**Comment by korli** [comment]
> > this doesn't seem popular, because it doesn't exist anywhere: https://repology.org/projects/?search=LDMicro
> 
> yeah.. maybe not very popular.. but electrician maybe love it..

My point is, this project doesn't have any bugs, any PR: https://github.com/FOSSEE/LDmicroQt/issues
You could also ask there to port to Haiku.

**Comment by mazbrili** [comment]
> > > this doesn't seem popular, because it doesn't exist anywhere: https://repology.org/projects/?search=LDMicro
> > 
> > 
> > yeah.. maybe not very popular.. but electrician maybe love it..
> 
> My point is, this project doesn't have any bugs, any PR: https://github.com/FOSSEE/LDmicroQt/issues
> You could also ask there to port to Haiku.

thanks @korli  .. i have ask there

**Comment by Begasus** [comment]
@mazbrili you did a few ports by now, this one is still not reported at repology, but if you have a use for it why not create your own recipe?

**Comment by mazbrili** [comment]
my bad.. i can compile now.. i try to make recipe then close this ticket
![image](https://user-images.githubusercontent.com/25004583/140008478-60fdb41d-bfee-4c15-96fd-01ed952a4e54.png)

**Comment by mazbrili** [comment]
create recipe here https://github.com/haikuports/haikuports/pull/6448

**Comment by Begasus** [comment]
Pushed some changes to the PR and it's merged now. Thanks (closing as complete).
