### ISSUE TITLE
qemu: add RISC-V platform

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#5778]
`qemu-system-riscv64` is not available, but it is available on Linux.

Haiku provides RISC-V builds, but currently there are no way to test them inside Haiku. It would be nice to have RISC-V emulator that run on Haiku.

**Comment by threedeyes** [comment]
Enabled in https://github.com/haikuports/haikuports/commit/b16b9244eee6745c9ed3200d4401c0927205f4c8
