### ISSUE TITLE
fpc 3.0.4 64bit needed, can't be build

### ISSUE THREAD

**Issue by lorglas** [haikuports/haikuports#5798]
i need fpc 3.0.4 on 64bit, the recipe can't be build.

**Comment by Begasus** [comment]
Did manage to get a build for 3.2.0 on 64bit, also a seperate package for fpc_source as it's needed for lazarus, maybe @roired can chip in on this? ;)

**Comment by Begasus** [comment]
In response to the discussion at the forum: https://discuss.haiku-os.org/t/cudatext-64bit-almost-ready/10750/10

**Comment by roired** [comment]
Good day, @begasus,

Thanks for your trust and confidence, though I should disappoint you right now. Actually, I'm using FreePascal 3.2 (fpc 3.2.0, binary and sources), but I've done all that installing the packages from the Hakilo repository, so just added the repo to HaikuDepot/pkgman and install from there. FPC 3.2.0 official build and sources are available at that repo, and also Lazarus Qt5, libqt5pas. So I really have no clue on how to build them.

For CudaText, I followed the steps detailed in the CudaText's wiki, though with some issues, mostly due (I presume) to the status of Lazarus on Haiku. I still need to figure out why some things still don't work as they should in CudaText, but I want to try to make the package first, then start testing.

Nonetheless, let me know how can I help, and if I can do or can learn, I will.

Regards,
RR

**Comment by Begasus** [comment]
@roired So far I've been able to build a package for fpc and fpc_source (which is needed for lazarus), side tracked atm with texlive, will report later :)

**Comment by roired** [comment]
By the way, I added a repo: https://github.com/roired/CudaText-Haiku 
to add Haiku related files regarding CudaText.

**Comment by Begasus** [comment]
Not there yet, but will keep it in mind :)

**Comment by Begasus** [comment]
Related: there is a bootstrapped version for 3.2.0 at sf that could be used to build the latest 3.2.2 version then, point is, the downloads are called different for the bootstrapped version (i386 vs x86_64) and there are a few changes in the cmd's also.
Maybe we could use fpc_bin32, fpc_bin64, fpc32 and fpc64 in the recipe names to make clear which version should be build for the right architecture? Summoning @korli :)

**Comment by Begasus** [comment]
Builds for both 32bit and 64bit completed and are ready to be installed, fixed in https://github.com/haikuports/haikuports/pull/6033
