### ISSUE TITLE
WPA Supplicant could have an icon

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#5805]
Currently it uses the standard executable icon. wpa_supplicant runs always, if you happen to have a wireless card, so it would look much nicer with an own icon.

**Comment by extrowerk** [comment]
Zumi have 2 antenna icon, maybe we could use one of that.

**Comment by diversys** [comment]
cc @threedeyes

**Comment by extrowerk** [comment]
I am thinking about what could be a "supplicant" related to radio towers. Maybe a small house beside a radio tower?
