### ISSUE TITLE
Scribus. Cannot open Scribus (Signal#6) error

### ISSUE THREAD

**Issue by Brunobasta** [haikuports/haikuports#5814]
I tried to open Scribus. and it just crash with Signal#6 errror.
http://0x0.st/-cqH.png
After that i deinstalled it and tried to install again.
But the install is staled (Status: In process)
See the pic for Terminal output...
Thx

**Comment by Begasus** [comment]
Confirmed here on 32bit (R1B2)

**Comment by korli** [comment]
Should be fixed in b3936b7f80eae509f879b36771c07dc82676d8db
It seems libpython3.7 isn't compatible from 3.7.9 to 3.7.10, thus needing a rebuild.
