### ISSUE TITLE
expect 5.45.4 package is non-functional on Haiku (tested Hybrid, hrev55027); Fails to open a pty.

### ISSUE THREAD

**Issue by johnsonjh** [haikuports/haikuports#5820]
Tested on Hybrid Haiku (Walter/hrev55027):

* `expect` package from HaikuPorts is non-functional.

Steps to reproduce:
1. Install `expect` using `pkgman`;
2. Execute `expect -c "spawn -pty"`

Expected result:
  - No error message.

Error message when executed from terminal:
```text
spawn -pty
The system has no more ptys.  Ask your system administrator to create more
    while executing
"spawn -pty"
```

Additional information:
  - `strace` indicates that `expect` is trying to open `/dev/ptyp0`, which does not exist.

**Comment by pulkomandy** [comment]
Still a problem. @korli you did the original recipe for expect 5.45 (several years ago...), do you remember if that older version worked fine?

**Comment by pulkomandy** [comment]
The main problem was missing detection of the openpty function. I fixed this and I get another crash now, apparently because Tcl_ErrnoMsg did not manage to convert an error code into a string?
