### ISSUE TITLE
Kate: Missing symbol: _ZN3KIO11TransferJob13mimeTypeFoundEPNS_3JobERK7QString

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#5822]
Haiku hrev54982 x86_gcc2
Kate: kate_x86-20.12.0-2-x86_gcc2.hpkg

Demangled name: `KIO::TransferJob::mimeTypeFound(KIO::Job*, QString const&)`.

**Comment by diversys** [comment]
Does it work after updating to 20.12.3?

**Comment by X547** [comment]
`kate_x86-20.12.3-1-x86_gcc2.hpkg` still fails with same error.

**Comment by diversys** [comment]
Hm, the same package works here just fine. Are you sure you don't have some stray lib in `~/config/lib` or something like that? Also what version of `kio` package is installed?

**Comment by humdingerb** [comment]
Off-topic, but should there be another REVISION bump for kate:
I think the DESCRIPTION of kate is excessively long. Few people will read it all in HaikuDepot and the few that do want to know all its features can click on the homepage and take the big screenshot tour and what have you.

Besides "too much information", I admit that another reason is that I never can work up the motivation to translate it all... :)

I'd like to make recipe writers aware of the issue, but don't know exactly where. Shall I create a post in the Haiku forums?

**Comment by diversys** [comment]
> Shall I create a post in the Haiku forums?

Sure.

**Comment by X547** [comment]
>  Also what version of kio package is installed?

kio_x86-5.80.0-1-x86_gcc2.hpkg

**Comment by X547** [comment]
More details:
```
runtime_loader: /boot/system/lib/x86/libKF5Parts.so.5.80.0: Could not resolve symbol '_ZN3KIO11TransferJob13mimeTypeFoundEPNS_3JobERK7QString'
resolve symbol "_ZN3KIO11TransferJob13mimeTypeFoundEPNS_3JobERK7QString" returned: -2147478780
runtime_loader: /boot/system/lib/x86/libKF5Parts.so.5.80.0: Troubles relocating: Symbol not found
```

**Comment by X547** [comment]
I found problem, kio_x86 package was also installed at `/boot/home/config/packages`:
```
> query -a libKF5KIOCore.so.5
/boot/system/lib/x86/libKF5KIOCore.so.5
/boot/home/config/lib/x86/libKF5KIOCore.so.5
```
After uninstalling it, problem was solved.
