### ISSUE TITLE
godot: bump to 3.3.1

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#5848]
"Godot 3.3 focuses on optimization and reliability, with core and rendering features such as 2D batching, dynamic BVH, CPU lightmapper, modernized threading APIs, and more!"

Release notes: https://godotengine.org/article/godot-3-3-has-arrived
Ref: https://github.com/godotengine/godot/releases/tag/3.3-stable

**Comment by CodeforEvolution** [comment]
Haiku support was removed from Godot following 3.2.2, and was moved to a separate repository/submodule. As such, the Haiku port needs some work, and I hope to deliver soon. :) Summer is approaching after all!

**Comment by kenmays** [comment]
Migrating this to Godot 4.0 project.
