### ISSUE TITLE
gcc 11: Port to Haiku

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#5852]
Release notes: https://gcc.gnu.org/gcc-11/changes.html
Src: https://gcc.gnu.org/pub/gcc/releases/gcc-11.1.0/gcc-11.1.0.tar.xz

Ref: #5855
Ref: #5858
Ref: #5857

**Comment by extrowerk** [comment]
It would be great if you would try to concentrate to only one specific version instead of dividing your attention between different versions.

**Comment by kenmays** [comment]
GCC 11.1 build issues resolved as of Haiku hrev55075.
