### ISSUE TITLE
Scribus Ver. 1.5.7 does not start

### ISSUE THREAD

**Issue by Brunobasta** [haikuports/haikuports#5892]
Scribus Ver. 1.5.7 does not start
Here the termainal output:
http://0x0.st/-BDA.png

**Comment by korli** [comment]
@kenmays ping

**Comment by kenmays** [comment]
@Brunobasta - Provide 'unarme -a' output.  Working on recent nightly before python3 updates.

**Comment by Brunobasta** [comment]
@kenmays
you mean uname -a?
Here:
http://0x0.st/-MTz.png

**Comment by kenmays** [comment]
Haiku shredder 1 hrev55079 May  8 2021 06:55:58 x86_64 x86_64 Haiku
```
/boot/system/apps/Scribus> /boot/system/apps/Scribus/Scribus
pathForIcon: Unable to load icon /packages/scribus-1.5.7-1/.self/data/scribus/icons/1_5_1/lab.png: File not found
pathForIcon: Unable to load icon /packages/scribus-1.5.7-1/.self/data/scribus/icons/1_5_1/spot.png: File not found
pathForIcon: Unable to load icon /packages/scribus-1.5.7-1/.self/data/scribus/icons/1_5_1/register.png: File not found
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
```

**Comment by kenmays** [comment]
Scribus 1.5.7-1 is working, so I'll update my system here:

1. pkgman full-sync (updates python39 3.9.2-1 to 3.9.2-3).

This seemed to break Scribus. Going to rebuild Scribus to see if that'll fix it.

**Comment by kenmays** [comment]
@korli - Tested on hrev55087 x86_64. Rebuild the scribus package. This will fix the issue.
