### ISSUE TITLE
Qmplay 2 does'nt search for YouTube files anymore

### ISSUE THREAD

**Issue by Brunobasta** [haikuports/haikuports#5904]
Haiku nightly 64bit newest.
I cannot search for YouTube files anymore. Was working some time (weeks or month) ago.
Playing the older (YouTube) files works.

**Comment by Brunobasta** [comment]
http://0x0.st/-MTW.png

**Comment by threedeyes** [comment]
I think it is better to report such problems to the author of the program - https://github.com/zaps166/QMPlay2/issues

**Comment by Brunobasta** [comment]
Ah ok thx reported to the author of the program

**Comment by Brunobasta** [comment]
The developer there answered: You have to compile QMPlay2 from current master branch (or use patch mentioned here). It's not a Haiku issue, it a Google's stupid behavior to add annoying consent page. 😞

**Comment by Brunobasta** [comment]
https://github.com/zaps166/QMPlay2/issues/426

**Comment by threedeyes** [comment]
Ok. A apply this patch from upstream soon
