### ISSUE TITLE
DISABLE_SOURCE_PACKAGE="yes"

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#5906]
When is this advised to be used? I think on actually developed sources we could use this as the source remains available?

**Comment by pulkomandy** [comment]
There is a requirement for all GPL licensed code that if we distribute the binaries, we must also distribute the sources. I think a link to already existing sources elsewhere is not enough.

For non-GPL code, it could possibly be disabled, but it's never clear (for example if you use a MIT licensed lib in a GPL program, you must also redistribute the sources of the MIT library).

So, don't use it. Instead run haikuporter with --no-source-packages locally if you don't need source packages (this could, and probably should be made the default).

**Comment by Begasus** [comment]
Thanks for the explanation @pulkomandy :) so far I haven't really used it, just wondered what the philosofy behind it was :)

**Comment by pulkomandy** [comment]
It was used in a few cases where the sources are really large and we don't want to store them, I think

**Comment by korli** [comment]
It is used for binary downloads, which are only repackaged as HPKG (for instance https://github.com/haikuports/haikuports/blob/master/dev-lang/rust_bin/rust_bin-1.52.0.recipe#L29)

**Comment by Begasus** [comment]
I think this information could be useful for others too, thanks for the replies!

**Comment by pulkomandy** [comment]
Updated https://github.com/haikuports/haikuports/wiki/HaikuPorter-BuildRecipes to clarify when to use it.
