### ISSUE TITLE
lame fails to build with gcc5

### ISSUE THREAD

**Issue by khallebal** [haikuports/haikuports#591]
Make fails with the following error msg:

In file included from xmm_quantize_sub.c:37:0:
/boot/system/develop/tools/lib/gcc/i586-pc-haiku/5.3.0/include/xmmintrin.h:895:1: error: inlining failed in call to always_inline '_mm_set_ps1': target specific option mismatch
 _mm_set_ps1 (float __F).

**Comment by korli** [comment]
Excerpt from http://www.linuxfromscratch.org/blfs/view/svn/multimedia/lame.html
> sed -i -e '/xmmintrin\.h/d' configure : with gcc-4.9.0 and above, the compiler issues an error on 32-bit machines, while compiling xmm_quantize_sub.c. The error message is: error: inlining failed in call to always_inline '_mm_loadu_ps'. This sed makes it appear as if xmmintrin.h is not present. Do not use this on other versions of gcc.

Another patch which looks better: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=206620

**Comment by pulkomandy** [comment]
Maybe we should use -msse on the command line anyway, and keep those enabled?

**Comment by korli** [comment]
Not sure what you mean. Detecting xmmintrinsic seems OK.
Applied the second patch in 34ca539.
