### ISSUE TITLE
Scribus 1.5.7.2 problems with iconset Haiku 64bit nightly (hrev 55094)

### ISSUE THREAD

**Issue by Brunobasta** [haikuports/haikuports#5929]
Terminal:
http://0x0.st/-jUO.png
Haiku cannot find the iconset.

At start there is some problem with Ghostscript:
http://0x0.st/-jU4.png

Bugreport:
http://0x0.st/-jUw.png

Ghostscript crash but Scribus will start, but crash soon...

**Comment by kenmays** [comment]
@Brunobasta - Uninstall ghostscript_gpl. See if you have any other issues during your normal daily worklfow use of Scribus.

**Comment by Brunobasta** [comment]
I deinstalled Ghostscript and started Scribus. Still I have problems with:
http://0x0.st/-j7v.png
Also in normal workflow, if I have two text boxes and one image box open, I often see the "Crash through Signal #11", I still did not find out what this particular Error is all about. I had this error with the older versions too.
If this problem is solved Scribus is a very professional tool for working with. So I hope we can solve this problem with the "Crash through Signal #11"

**Comment by Brunobasta** [comment]
http://0x0.st/-j73.png
Crash through Signal #11

**Comment by korli** [comment]
Signal 11 is segmentation violation, there should be a crash report.

**Comment by Brunobasta** [comment]
On 32bit Scribus wont start anymore.
http://0x0.st/-eiR.png
There  is not bug report! Where to find the crash report?

**Comment by kenmays** [comment]
Did you 'pkgman full-sync' on that platform?

**Comment by kenmays** [comment]
Scribus 1.5.7 worked on Haiku_x86 with Python 3.9. 
Now get a 'Signal #6'. Need to check with Python3 rebuild locally.

```
~/haikuports/app-office/scribus> /boot/system/apps/Scribus/Scribus
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0293b080 (most recent call first):
Abort
Scribus Crash
-------------
Scribus crashes due to Signal #6
Calling Emergency Save
QObject::~QObject: Timers cannot be stopped from another thread
```

**Comment by Brunobasta** [comment]
Ah there is some progress now?
There is still this icon set problem: http://0x0.st/-e_4.png
Looks like misconfiguration of the icon folder 1_5_0 and 1_5_1
See: http://0x0.st/-e_y.png

**Comment by kenmays** [comment]
May 21,2021: Progress. I updated Haiku R1B2 x86 today with 'pkgman full-sync'. The previous crash issue (i.e. Signal #6) disappeared, so everything loads now and Python3 (v3.7.10) is properly detected. The iconset directories 1_5_1 and 1_5_1_dark are missing those icons from the 1_5_0 directory. Copying the missing files to the 1_5_1 directories resolves the missing icons issue. Best to resolve that issue upstream in the long run.

See: https://discuss.haiku-os.org/t/scribus-1-5-7-with-ghostscript-gpl/10747/7

See if you can 'pkgman full-sync' your x86 install to fix the crash issue.

**Comment by Brunobasta** [comment]
Hmm, no way...
tried all I can, pkgman full-sync, reinstall and still same here gs crashes always. 
Scribus is starting now! But crashes easy with Signal #11 segment fault?

**Comment by Brunobasta** [comment]
I copied some files from the system folder to the home folder because the system folder is not writeable... but it still does not work?! What did I do wrong? I need some icons from the scribus 1.5.0 version in scribus 1.5.1 version... See example: http://0x0.st/-2Nz.png
I tried also the non-package folder in config: http://0x0.st/-2No.png
So my question where should my Icon folder go to make it work/writeable?
It is all about this bug: http://0x0.st/-2N8.png

**Comment by Brunobasta** [comment]
same peroblems on 32 bit nightly. pkgman full-sync wont help me here.

**Comment by Brunobasta** [comment]
How to: Copying the missing files to the 1_5_1 directories resolves the missing icons issue?
Since the system is write protected?
I tried to put the folder in boot/home/config/non-packaged/data/ folder
but it does not work! Where to put those files from 1.5.0 to the home folder?

**Comment by korli** [comment]
you can try to repackage: move the scribus hpkg in a directory then mkdir temp; cd temp; package extract ../scribus-....hpkg ;  copy missing files; package create ../scribus-..hpkg; copy the package back in /system/packages/

**Comment by Brunobasta** [comment]
Yes it works, and I learned something... thx
Icon problem solved.
but others still exist, not sure if related to iconset though!
http://0x0.st/-_jI.png

**Comment by korli** [comment]
> but others still exist, not sure if related to iconset though!
> http://0x0.st/-_jI.png

You can compare with other Qt apps, but I think some are pretty common.

**Comment by Brunobasta** [comment]
Still problems to open Scibus on 55560
http://0x0.st/-7N6.png

**Comment by korli** [comment]
Please try with 1.5.7-3

**Comment by Brunobasta** [comment]
It works again, but sometime crash to signal#11
At least it is usable again thanks.

**Comment by korli** [comment]
ghostscript itself still crashes when used with:
`gs -sDEVICE=tiffsep -c quit`
