### ISSUE TITLE
Recent python versions depend on python2.7?

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#5960]
Looking at the recipes they mention `cmd:python` in the `BUILD_PREREQUIRES`
Summining @korli for this one :)

**Comment by Begasus** [comment]
From Arch https://github.com/archlinux/svntogit-packages/blob/packages/python/trunk/PKGBUILD:

```
depends=('bzip2' 'expat' 'gdbm' 'libffi' 'libnsl' 'libxcrypt' 'openssl' 'zlib')
makedepends=('tk' 'sqlite' 'bluez-libs' 'mpdecimal' 'llvm' 'gdb' 'xorg-server-xvfb' 'ttf-font')
```

**Comment by korli** [comment]
Please try without?

**Comment by Begasus** [comment]
> Please try without?

Already did, python39 builds/packages OK without `cmd:python`

**Comment by Begasus** [comment]
Seems to be introduced in commit https://github.com/haikuports/haikuports/commit/8aeb2cfbf972cbbb197e6acc8e211471d107fef6#diff-97dbb585afbff18e3304932005686557385e126e17272a51d033bff0b34963bf ?

**Comment by Begasus** [comment]
So far builds for python3 python36 and python39 finished fine on x86_64 here, gonna try some builds on x86_gcc2 with other recipes depending on it (mainly python3)

**Comment by korli** [comment]
Ok cmd:python can be removed then.

**Comment by Begasus** [comment]
Will do a checkout on my latest PR's for numpy and scipy, if I get around to it I'll push changes later :)

**Comment by Begasus** [comment]
Fixed in https://github.com/haikuports/haikuports/pull/5962
