### ISSUE TITLE
[net-misc/Gerbera] does not work on Haiku 64bit nightly

### ISSUE THREAD

**Issue by Brunobasta** [haikuports/haikuports#5977]
Starting the server will kill thread.

Bugreport:
[GerberaReport 64bit H.nly.txt](https://github.com/haikuports/haikuports/files/6625207/GerberaReport.64bit.H.nly.txt)

**Comment by Brunobasta** [comment]
1. Install Gerbera (HaikuPorts)
2. Create the config.xml file in Terminal: gerbera --create-config
3. Copy'n Paste the created config file in: boot/home/config/settings/gerbera/config.xml
4. Start Gerbera with: gerbera -c /boot/home/config/settings/gerbera/config.xml

**Comment by korli** [comment]
[GerberaReport 64bit H.nly.txt](https://github.com/haikuports/haikuports/files/6625202/GerberaReport.64bit.H.nly.txt)

**Comment by extrowerk** [comment]
> 2\. Create the config.xml file in Terminal: gerbera --create-config

This shouldn't be needed, the postinstallscript should do it, but apparently it doesn1t gets triggered:
https://github.com/haikuports/haikuports/blob/master/net-misc/gerbera/gerbera-1.8.2.recipe#L117

**Comment by Begasus** [comment]
> but apparently it doesn't gets triggered:

The script should be made executable up front (in additional-files), then it works.
Still crashes here also though (looking into bumping some libraries and gerbera is connected to them)

**Comment by Begasus** [comment]
Updated gerbera to 1.9.2, crashes on launch (but if you leave the crash window open you can still reach the webinterface and add/download files, adding crash raport and a tail from syslog.
[syslog_gerbera.txt](https://github.com/haikuports/haikuports/files/7452227/syslog_gerbera.txt)
[gerbera_debug.raport.txt](https://github.com/haikuports/haikuports/files/7452231/gerbera_debug.raport.txt)

**Comment by Begasus** [comment]
Bumped version for gerbera, seems with the new gcc11 the crash is gone on 32bit: https://github.com/haikuports/haikuports/pull/6356

**Comment by Begasus** [comment]
![Gerbera_1 9 2_32bit](https://user-images.githubusercontent.com/16057090/139699513-9191a545-a27c-453a-820e-b95b42d2babf.jpg)

**Comment by Brunobasta** [comment]
Works with Firefox?
Hmm, it does not work with Web+ or Otter Browser.
Still same problem here...

yes, if you leave the crash window open you can still reach the webinterface
but cannot add/download files!

**Comment by Brunobasta** [comment]
with hrev 5560 Gerbera does not crash anymore...
Anyway Web+ and Otter dont like Gerbera. Mediatomb was working last year...

**Comment by Begasus** [comment]
I mostly check this over the local network here, so yes, on Ubuntu I use Firefox to connect to Gerbera on the Haiku install, that works fine for me :)

**Comment by Brunobasta** [comment]
Can you check out the current Gerbera master?
See here:

https://github.com/gerbera/gerbera/issues/1591#issuecomment-961861302

Can you run a test with current master, because there were some changes regarding cookies incl. security which may change the behaviour on your system.

**Comment by Begasus** [comment]
No changes when I rebuild from master, still not possible to login or click any of the items on the frontpage, strange thing is that when I connect over the network it doesn't ask me for a login ...

**Comment by Begasus** [comment]
Should be fixed in: https://github.com/haikuports/haikuports/pull/9032
Could you check? (should mark 32bit as broken, error on launch for missing symbol).
