### ISSUE TITLE
guile1: error invoking scheme script: "in procedure dynamic-link"

### ISSUE THREAD

**Issue by jmairboeck** [haikuports/haikuports#5993]
Now that texlive is mostly "done" (see #5963), I thought I'll try going further towards my goal of porting [LilyPond](http://lilypond.org).

However, this currently fails pretty early in the build process because I suppose, the guile1 package is somewhat broken on Haiku. When trying to invoke [lilypond-invoke-editor](http://git.savannah.gnu.org/gitweb/?p=lilypond.git;a=blob;f=scripts/lilypond-invoke-editor.scm;h=507345b1f89bcd2a26c42a02b757585bb6900ab7;hb=HEAD) during the build process, it fails with this error message:

```
ERROR: In procedure dynamic-link:
ERROR: file: "libguile-srfi-srfi-1-v-3", message: "file not found"
```

The package `guile1_devel` is installed, and it contains the mentioned library in `develop/lib` (and the runtime counterpart is in `lib` from the `guile1` package). I suspect that guile isn't prepared to look for development libs in the `develop` directory, but that is just a guess from my side.

`dynamic-link` is apparently a built-in function provided by guile, so I suppose the `guile1` package needs to be fixed.

Note: I could try building LilyPond with guile2 instead, but this is [not officially supported and not recommended](http://lilypond.org/doc/v2.22/Documentation/contributor/requirements-for-running-lilypond) yet.

**Comment by jmairboeck** [comment]
Using guile 2 instead of guile 1 seems to avoid this issue indeed, but as this is still not officially recommended to use, I'll keep this open for the time being.

Still not sure if I get Lilypond to actually work (it's still building...)

**Comment by jmairboeck** [comment]
I think I know what's wrong now: the error message comes from `lt_dlopenext` from libtool's libltdl. According to the [documentation](https://www.gnu.org/software/libtool/manual/html_node/Libltdl-interface.html#Libltdl-interface) this does the same as `dlopen`, but appends the file extension automatically and so on.

I have noticed that on my openSUSE system, the main `guile1` package contains version-less symlinks in /usr/lib64 (which normally are part of the `devel`-package).

Also, when setting the environment variable `LTDL_LIBRARY_PATH=/boot/system/develop/lib`, launching lilypond-invoke-editor with guile1 works.

So, I suggest adding version-less symlinks to $libDir for the guile libraries and add them to the main package (or the _tools package?) (and keep those in $developLibDir, of course).

**Comment by pulkomandy** [comment]
The reason we don't have unversionned names in the lib directory is that there is no binary compatibility guarantee. So, an application relying on a specific version of a library would fail when the library is updated.

Why does libtool always insist on doing things wrong? It's not the first time we need to patch it.

**Comment by jmairboeck** [comment]
In this specific case, I think it would not be a problem, because this is the legacy version, which doesn't get updates any more. From guile2 onwards, the srfi libraries don't exist any more as standalone .so files and are part of libguile.so itself, presumably. That is why this is not a problem using guile 2 (or even 3.0, for that matter).

Building LilyPond against Guile 2.2 is possible, but it is significantly slower, uses more memory, and guile causes warnings to be printed to the console at runtime. It is recommend to still use version 1.8 if possible for these reasons.

Should we patch the implementation of lt_dlopenext instead, so that it finds the versioned libraries also? Or patch guile so that it loads the correct versioned libraries directly?

**Comment by jmairboeck** [comment]
I tried a different approach to patch guile where it loads the built-in extensions to include the version numbers. But now it gives the following error message:

```
ERROR: In procedure dynamic-link:
ERROR: file: "libguile-srfi-srfi-1-v-3.so.3.0.2", message: "file not found"
```

It seems that it still tries to append a file extension to it or something similar.

The only other possibility I see is trying to fix this in libltdl.

**Comment by jmairboeck** [comment]
I looked at the [implementation of lt_dlopenext](https://git.savannah.gnu.org/cgit/libtool.git/tree/libltdl/ltdl.c#n1630). If the passed file name doesn't end in a known library extension, it tries to append one. Using lt_dlopen (non-ext) is not possible, because the general use-case of the `load-extension` function in guile should remain.

In summary, I think my solution in #6128 is the least "hacky" way to solve this (maybe just limited to the actual extension libraries, not all of them).
