### ISSUE TITLE
scipy-1.6.3: OpenBLAS packages not activating during x86_64 build

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#5996]
scipy-1.6.3 x86_64:

The recipe has the openblas build dependency, but during hp compilation for x86_64 - it does not activate the package:. The openblas packages are installed on the system. NOTE: The same recipe and patchset compiles successfully on a Haiku x86 system. This causes a build failure on Haiku x86_64.

```
       /boot/home/haikuports/packages/openblas-0.3.13-1-x86_64.hpkg
       /boot/home/haikuports/packages/openblas_devel-0.3.13-1-x86_64.hpkg
```

NOTE: I tested both openblas-0.3.13-1 and openblas-0.3.15-1 packages on Haiku x86_64 - no change.

**Comment by Begasus** [comment]
Did you manage to build openblas-0.3.15 on x86_64? last time I checked it failed to build (also on the buildbot): see issue https://github.com/haikuports/haikuports/issues/5953

**Comment by kenmays** [comment]
Yes.

**Comment by kenmays** [comment]
Fixed: https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/5878/builds/75598.log
