### ISSUE TITLE
Update BeShare

### ISSUE THREAD

**Issue by panos** [haikuports/haikuports#6012]
AGMS shared the link to BeShare 3.04 in the IRC channel. It can be found [here](http://web.ncf.ca/au829/BeOS/BeShare_3.04.zip)

```
[15:28:55] <B2IA> (AGMS) The trick is to not update to the lastest Muscle library, breaks compatibility.
[15:29:16] <B2IA> (AGMS) Also the source still compiles on ALL versions of BeOS and Haiku.
```

The latest version (2.35, as of the time of this writing) can be found [here](https://github.com/haikuports/haikuports/blob/master/haiku-apps/beshare/beshare-2.35.recipe).

**Comment by agmsmith** [comment]
D'oh, it's easier than I thought!  Make the recipe copy the executables for the appropriate platform out of the source .zip and build a package from it.  No need to compile or worry about other oddities.  I'll look into it.

**Comment by panos** [comment]
Can do so too, if that's of convenience to you. @agmsmith 

Just got a lot on my plate and that's why I didn't investigate this at all.

**Comment by agmsmith** [comment]
I'll try to do it today.  If I get stuck, I'll hand it over to you :-)

**Comment by agmsmith** [comment]
Got a recipe working, for Haiku x86_gcc2 and x86_64 and ppc!  See https://github.com/haikuports/haikuports/pull/6015
