### ISSUE TITLE
texindex misses dependency on mawk

### ISSUE THREAD

**Issue by jmairboeck** [haikuports/haikuports#6020]
running `texindex --help` (from the `texinfo` package) produces the following error:

```
/bin/texindex: line 116: exec: mawk: not found
```

It probably should declare that as a dependency.

**Comment by korli** [comment]
Please update texinfo and test.

**Comment by jmairboeck** [comment]
The error message is still the same. I have awk installed, but not mawk.

**Comment by korli** [comment]
which architecture?

**Comment by jmairboeck** [comment]
this time I tested on x86_gcc2 (beta 3), the original bug report is from x86_64 (nightly). But I can't test that currently because that laptop died unfortunately.

**Comment by Begasus** [comment]
Latest test reveal, on 64bit it requires mawk, on 32bit it requires gawk.

**Comment by jmairboeck** [comment]
Works now without mawk installed on nightly x86_64.
