### ISSUE TITLE
netsurf 3.10-2: build fails on hrev55204 x86_64

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#6030]
This build compiled successfully on Haiku R1B2 x86_64. 
May fail on Haiku R1B3.

`COMPILE: frontends/beos/cookies.cpp
frontends/beos/cookies.cpp:41:10: fatal error: NetworkCookieJar.h: No such file or directory
 #include <NetworkCookieJar.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:864: recipe for target 'build/beos-beos/frontends_beos_cookies.o' failed
make: *** [build/beos-beos/frontends_beos_cookies.o] Error 1
make: *** Waiting for unfinished jobs....
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 2.
Error: Build has failed - stopping.`

~/haikuports/www-client/netsurf> uname -a
Haiku shredder 1 hrev55204 Jul  1 2021 06:03:31 x86_64 x86_64 Haiku

~/haikuports/www-client/netsurf> find /system/develop/headers -name NetworkCookieJar.h
/system/develop/headers/private/netservices/NetworkCookieJar.h

**Comment by pulkomandy** [comment]
This include is not needed in NetSurf and can be removed. It is there because this file was copied from the version in WebPositive.
