### ISSUE TITLE
Add jpeg-xl

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#6041]
jpeg-xl is one of the new improved image file formats looking to replace jpeg.
https://gitlab.com/wg1/jpeg-xl

Bonus if a Haiku translator can be added as well

**Comment by Begasus** [comment]
So far only Fedora mentioned at Repology, should be possible (at least for a base package - translator is out of my leage :) )

**Comment by Begasus** [comment]
Gerntoo reports this package as libjxl, others as jpegxl and others jpeg-xl, think we're going for libjxl ...

**Comment by wattoc** [comment]
I can have a look at this, time permitting.  Will give me an excuse to play about with the translator stuff.

**Comment by Begasus** [comment]
Already have a working recipe here, just didn't push :)

**Comment by Begasus** [comment]
Just not as a translator, no idea there

**Comment by wattoc** [comment]
If you push the recipe I can start working on a translator for it :)

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/6096
Just remembered why I didn't push, checksums seems to change on the other SOURCE_URI's :(

**Comment by wattoc** [comment]
No problem, it's much better than my recipe so far - it's a starting point for working on a translator

**Comment by wattoc** [comment]
Progress so far:

![wip jpegxl translator](https://user-images.githubusercontent.com/45884543/127021871-28bd365d-8f55-45f8-9c16-b33458298b19.png)

Conversion from JPEG XL to Haiku bitmaps is working, need to handle the reverse scenario and add some configuration to the Translator.

**Comment by Begasus** [comment]
Done in https://github.com/haikuports/haikuports/pull/6096 @wattoc maybe you can look into creating the translator for it now? :)

**Comment by wattoc** [comment]
Translator is done: https://github.com/wattoc/JXLTranslator, just need to get around to creating the recipe
