### ISSUE TITLE
qemu_x86_m68k package: error trying to install

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#6082]
When trying to install the qemu_x86_m68k package, I got the following error:

Fatal error occurred while installing package qemu_x86_m68k: Failed to find a match for "qemu_x86_m68k" ()

The same error I get when trying to install other qemu packages like the ppc one. The only one that managed to install correctly is the qemu_x86_x86 one.

I'm using Haiku nightly, 32 bit (hrev55240)

**Comment by korli** [comment]
should be fixed in 68ea128837e9b9384b61b89dc683b53068f6da08

**Comment by unspacyar** [comment]
I confirm that the issue was fixed.  Thank you @korli  !!!
