### ISSUE TITLE
MEDO, wrong german translations Haiku 64 and 32 bit beta 3

### ISSUE THREAD

**Issue by Brunobasta** [haikuports/haikuports#6092]
The translations in Medo are wrong. Lelldoring should review his translations!
Nahmen/ablagen is very strange and wrong in german language!

Aufnehmen/Ablegen
would be better for drag'n drop...

See:
http://0x0.st/-Wrm.png
http://0x0.st/-WrB.png

**Comment by humdingerb** [comment]
Please file a ticket at the project's bug tracker.
