### ISSUE TITLE
SDL2: upstream final patch...

### ISSUE THREAD

**Issue by icculus** [haikuports/haikuports#6095]
The SDL2 patchset sitting here...

https://github.com/haikuports/haikuports/blob/462947dd4f285a885d8011cade7cd0f7151cfe74/media-libs/libsdl2/patches/libsdl2-2.0.14.patchset

...is almost all upstreamed and will be part of the SDL 2.0.16 release, which is great, except for _one patch_ which has been bouncing around for a long time now across several attempts to merge into SDL's revision control:

```diff
diff --git a/Makefile.in b/Makefile.in
index 3a7e5571..20ba5702 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -152,13 +152,13 @@ update-revision:
 .PHONY: all update-revision install install-bin install-hdrs install-lib install-data uninstall uninstall-bin uninstall-hdrs uninstall-lib uninstall-data clean distclean dist $(OBJECTS:.lo=.d)
 
 $(objects)/$(TARGET): $(GEN_HEADERS) $(GEN_OBJECTS) $(OBJECTS) $(VERSION_OBJECTS)
-       $(RUN_CMD_LTLINK)$(LIBTOOL) --tag=CC --mode=link $(CC) -o $@ $(OBJECTS) $(GEN_OBJECTS) $(VERSION_OBJECTS) $(LDFLAGS) $(EXTRA_LDFLAGS) $(LT_LDFLAGS)
+       $(RUN_CMD_LTLINK)$(LIBTOOL) --tag=CXX --mode=link $(CXX) -o $@ $(OBJECTS) $(GEN_OBJECTS) $(VERSION_OBJECTS) $(LDFLAGS) $(EXTRA_LDFLAGS) $(LT_LDFLAGS)
 
 $(objects)/$(SDLMAIN_TARGET): $(SDLMAIN_OBJECTS)
-       $(RUN_CMD_LTLINK)$(LIBTOOL) --tag=CC --mode=link $(CC) -static -o $@ $(SDLMAIN_OBJECTS) -rpath $(libdir)
+       $(RUN_CMD_LTLINK)$(LIBTOOL) --tag=CXX --mode=link $(CXX) -static -o $@ $(SDLMAIN_OBJECTS) -rpath $(libdir)
 
 $(objects)/$(SDLTEST_TARGET): $(SDLTEST_OBJECTS)
-       $(RUN_CMD_LTLINK)$(LIBTOOL) --tag=CC --mode=link $(CC) -static -o $@ $(SDLTEST_OBJECTS) -rpath $(libdir)
+       $(RUN_CMD_LTLINK)$(LIBTOOL) --tag=CXX --mode=link $(CXX) -static -o $@ $(SDLTEST_OBJECTS) -rpath $(libdir)
 
 install: all install-bin install-hdrs install-lib install-data
 install-bin:
```

We can't universally flip the build from C to C++ in Makefile.in, even if it makes sense to do so on Haiku.

If someone changes this to only use `--tag=CXX --mode=link $(CXX)` on Haiku (or at least as some generic option that Haiku builds flip on by default), then we will merge it right away, resolving the last outstanding piece of the patchset.

I am not an expert at autotools, but if there are any questions I can answer, I'm happy to help.

**Comment by jessicah** [comment]
You can do something like:

Firstly, in `configure.ac`:
```
dnl libtool: use CXX tag on Haiku
case "$host" in
  *-*-haiku)
    LIBTOOL_TAG=CXX
    ;;
  *)
    LIBTOOL_TAG=CC
    ;;
esac
```

And near the end, with all the `AC_SUBST`, add `AC_SUBST(LIBTOOL_TAG)`

Then in `Makefile.in`
```
LIBTOOL_TAG = @LIBTOOL_TAG@
```
and replace `--tag=CC` with `--tag=$(LIBTOOL_TAG)

Should do the trick

**Comment by jessicah** [comment]
See https://github.com/jessicah/haikuports/commit/01dc0c2a7d8f92aa26bb832165d2036dfe595014
