### ISSUE TITLE
QuickRes doesn't appears under the "Open with" context menu: this can be achieved by changing the supported mime types in the executable.

### ISSUE THREAD

**Issue by Giova84** [haikuports/haikuports#610]
I attempted to open some executable files using QuickRes, but it doesn't appears under the "Open with" context menu.

I unpacked the hpkg, and by using "File Types" I removed all the supported mime types and I just added "Generic file" as only supported mime type (also "Diskprobe " is set to support generic file): Now QuickRes appears under the "Open with" context menu.

**Comment by Giova84** [comment]
Sorry for the noise.
I just upgraded Haiku using "pkgman update" (keeping my modifed version of Quickres) and Quickres disappeared again from the "Open with" menu. In the meantime I downloaded the original version from here http://www.angryredplanet.com/~hackbod/beos/quickres.html and works flawlessly out of the box when unzipped.

**Comment by humdingerb** [comment]
I also dowloaded the original app from angryredplanet. It appears under "Open with...". I changed the quickres.rdef in the additional-files of our recipe to emulate exactly what I see in the supported file types of the original:

resource file_types message {
	"types" = "application/x-be-executable",
	"types" = "application/x-vnd.be-elfexecutable",
	"types" = "application/x-be-resource",
	"types" = "application/octet-stream",
	"types" = "text/x-vnd.be.resourcedef"
};

Built a new package. No difference: still not in the "Open with..." menu.

Then I changed it to simply the "Generic file":

resource file_types message {
	"types" = "application/octet-stream"
};

Still, not in "Open with...". What's going on?

**Comment by fbrosson** [comment]
@humdingerb, If you did not refresh your haikuporter since https://github.com/haikuports/haikuporter/pull/89 got merged then I think it doing so will help.

**Comment by humdingerb** [comment]
@fbrosson, that might just have been it, thanks! Though it only began to work after a reboot. That kinda sucks, totally "un-Haiku"... :\

I have committed that change to the rdef and updated the package in the repo.

**Comment by fbrosson** [comment]
Yep, that's strange. Anyway, the good news is that it's fixed now ;-)

**Comment by Giova84** [comment]
> it only began to work after a reboot. That kinda sucks, totally "un-Haiku"... :\

I noticed the same with many other apps on Haiku, although the fact that the original QuickRes (which lives under the non packaged directory) is immediately present under the "Open with" menu, when unzipped.

Maybe would be a good idea open a ticket on the Haiku's bugtracker?

Sorry for the noise.

**Comment by humdingerb** [comment]
Imagine my surprise, when I looked through the bug tracker and found [#11766](https://dev.haiku-os.org/ticket/11766) that I have filed myself a mere 1.5 years ago. :)
