### ISSUE TITLE
Compile zip extension in PHP

### ISSUE THREAD

**Issue by Coldfirex** [haikuports/haikuports#6129]
I would like to request that the php-zip extension is compiled in our PHP version.
https://www.php.net/manual/en/zip.installation.php

**Comment by Begasus** [comment]
Looking at our recipe (and the description on that link) it seems to be done already?

https://github.com/haikuports/haikuports/blob/master/dev-lang/php/php-7.4.16.recipe#L107
```
--with-zlib-dir=`finddir B_SYSTEM_DIRECTORY` --with-zlib=shared 
```

**Comment by Coldfirex** [comment]
Per that link do we need to change to --with-zip then?
My use case was attempting to run the Phoronix Test Suite and its output is just that the ZIP PHP extension is required before it can run and that zlib is only optional.

**Comment by Begasus** [comment]
My bad, mistaken zlib with zip :)

**Comment by korli** [comment]
Please check with php-7.4.16-3

**Comment by Coldfirex** [comment]
Running into a problem now.  I updated but SoftwareUpdater says:
nothing provides lib:libffi<=6.0.4 needed by python3-3.7.10-4.
I chose to uninstall Python-3 to continue.  I then went into HaikuDepot to reinstal python3 but I am getting the same error.
The solutions provided are to either ignore or do not install python3.

**Comment by korli** [comment]
it was caused by 46a864c9eeabead7495daafc6ca0fd5e9a1833b0

**Comment by Coldfirex** [comment]
Thanks Korli.
For some reason running the Phoronix Test Suite I still get the same error output after the update.

"The following PHP extensions are REQUIRED:
ZIP    ZIP support is required for file compressions."

Any ideas?

**Comment by korli** [comment]
No idea, maybe PHP doesn't see extensions correctly?
