### ISSUE TITLE
MPD (Music Player Daemon) fails to install (lib:libiso9660_x86 related issue)

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#6131]
When trying to install MPD package, HaikuDepot throws the following error:

package mpd_x68-0.21.20-5 requires lib:libiso9660_x86>=10.0.0

The version available at /boot/systemlib/x86/ is the following one:  
libiso9660.so.11.0.0

Tested on Haiku nightly (32 bit): hrev55295

**Comment by korli** [comment]
Thanks for the report. Should be fixed with mpd_x86-0.21.20-6
