### ISSUE TITLE
libffi: update to get riscv support

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#6132]
version: libffi-3.2.1

Current libffi version have no RISC-V support and can't be compiled for it. Updating is needed.

**Comment by X547** [comment]
RISC-V support was introduced in libffi v3.3.

https://github.com/libffi/libffi/releases/tag/v3.3

**Comment by diversys** [comment]
Updated in 46a864c9eeabead7495daafc6ca0fd5e9a1833b0.
