### ISSUE TITLE
nmap failed to build

### ISSUE THREAD

**Issue by Coldfirex** [haikuports/haikuports#6144]
We have nmap in haikuports, but it wasnt showing up under HaikuDepot.
I found that the day of the it's most recent commit (12-26-2020) the build failed.

https://github.com/haikuports/haikuports/commit/ed9b52b7ca3321e120491516c115a0acf0718a17
https://build.haiku-os.org/buildmaster/master/x86_64/?buildrunDir=5107&viewMode=expanded

If I can do anything to help please let me know.

**Comment by diversys** [comment]
The build worked for me when building locally, however buildmaster build failed.
We need to figure out why this happens:

```
Compiling libnbase
rm -f libnbase.a
Compiling libnbase
rm -f libnbase.a
ar cr libnbase.a snprintf.o nbase_str.o nbase_misc.o nbase_memalloc.o nbase_rnd.o
ar cr libnbase.a snprintf.o nbase_str.o nbase_misc.o nbase_memalloc.o nbase_rnd.o
ar: libnbase.a: file format not recognized
ar: libnbase.a: No such file or directory
```

**Comment by extrowerk** [comment]
```ar: libnbase.a: file format not recognized```
Maybe the command ```ar cr libname.a objects.o``` doesn't works on Haiku?

**Comment by pulkomandy** [comment]
Why wouldn't it work? It's a standard binutils tool and it just creates an archive (a bit like tar).

But it looks like the command is run twice at the same time? So it's overwriting itself?

**Comment by Coldfirex** [comment]
Can we force buildmaster to try again?  Maybe it will behave different since these were upgraded to Beta 3?

**Comment by kenmays** [comment]
@diver - Add '--without-nmapfe' to recipe.
