### ISSUE TITLE
vmware_addons-1.2.1 causes a kernel panic at boot

### ISSUE THREAD

**Issue by augiedoggie** [haikuports/haikuports#6161]
Haiku x86_64 nightly using UEFI
VMWare Workstation 15.5.7

![Haiku-2021-08-28-20-54-35](https://user-images.githubusercontent.com/51547/131236917-36066973-a380-4ca9-925a-d9e2d0cb13ae.png)

**Comment by diversys** [comment]
Did the previous version work?

**Comment by augiedoggie** [comment]
yes

**Comment by augiedoggie** [comment]
> Did the previous version work?

yes, i have gone back to the older version for now

**Comment by diversys** [comment]
I think we should revert for now. @s40in any idea what's going on?

**Comment by Coldfirex** [comment]
Looks like the driver needs to be made SMAP aware.  
Potentially device.c needs to be updated to not use B_READ_AREA and use B_KERNEL_READ_AREA instead.

**Comment by Coldfirex** [comment]
You could also disable SMAP on bootup to confirm it gets past this error.

**Comment by Coldfirex** [comment]
I attempted to recreate this, while updating the source, but I only have access to ESXi.  No mouse control via console or with VMRC.  :(

**Comment by s40in** [comment]
> 
> 
> I think we should revert for now. @s40in any idea what's going on?

Sorry. I don't have any VMware VM now. Video driver good work in VirtualBox VMSVGA video mode.

**Comment by Coldfirex** [comment]
I figured out my ESXi issues.  I can confirm that booting with SMAP disabled from the boot menu gets around this.  The driver will need to be updated.

**Comment by diversys** [comment]
I wonder why device.c wasn't added to Makefile before the latest commit: https://github.com/HaikuArchives/VMwareAddons/commit/14bafb885686da4bc63c4a5b4f0c87187a83bb8e

**Comment by Coldfirex** [comment]
Not sure how it compiled before, but a visible error is under InitAccelerant.c.  It references B_KERENL_READ_AREA instead of B_KERNEL_READ_AREA.
Its possible this is the actual source of the problem, but device.c should be review either way as well.

**Comment by rjzak** [comment]
Same issue with VMware Fusion 12.1.2 on Mac OS, hrev55399. Works fine with hrev55240.

**Comment by chaoticbob** [comment]
Just ran into this issue with VMWare Workstation Pro 16 using Beta3 and hrev55448.

**Comment by korli** [comment]
@diver try to use user_memcpy() for instance:
https://github.com/HaikuArchives/VMwareAddons/blob/master/vmware_video/kernel/device.c#L285
https://github.com/HaikuArchives/VMwareAddons/blob/master/vmware_video/kernel/device.c#L289
https://github.com/HaikuArchives/VMwareAddons/blob/master/vmware_video/kernel/device.c#L309
https://github.com/HaikuArchives/VMwareAddons/blob/master/vmware_video/kernel/device.c#L326
https://github.com/HaikuArchives/VMwareAddons/blob/master/vmware_video/kernel/device.c#L341
https://github.com/HaikuArchives/VMwareAddons/blob/master/vmware_video/kernel/device.c#L350
VMWARE_GET_DEVICE_NAME is already correct.

**Comment by fabianmu** [comment]
Is there a way to downgrade or at least download an older version of the package?

**Comment by diversys** [comment]
You can rever the latest commit and rebuild the package using haikuporter. If you don't know how to do that I will try to do that myself later today (hopefully) and upload the package somewhere.

**Comment by diversys** [comment]
Try this version http://haikuware.ru/repo/lote/packages/vmware_addons-1.2.1-2-x86_64.hpkg (with korli's patch)
