### ISSUE TITLE
VLC not available in HaikuDepot for Haiku nightly_x84 (hrev: 55370)

### ISSUE THREAD

**Issue by Brunobasta** [haikuports/haikuports#6171]
VLC is not in HaikuDepot.
so I tried to install it with pkgman install vlc_x86 and get an error:
http://0x0.st/-vGi.png

Would be better to have it in HaikuDepot or working with Terminal.

**Comment by waddlesplash** [comment]
This is not a HaikuPorts problem. It appears Diver has helped you out on IRC anyway.
