### ISSUE TITLE
VLC for Haiku x86 hrev 55378 nightly not available in HaikuDepot

### ISSUE THREAD

**Issue by Brunobasta** [haikuports/haikuports#6172]
VLC for Haiku x86 hrev 55378 nightly not available in HaikuDepot

**Comment by waddlesplash** [comment]
Yes it is: https://depot.haiku-os.org/#!/pkg/vlc_x86/haikuports/3/0/16/-/1/x86_gcc2?bcguid=bc230-DFWK

You must have some other issue.

**Comment by Brunobasta** [comment]
Ok had some problems... Close it

**Comment by diversys** [comment]
Did you figure out what was the problem?

**Comment by Brunobasta** [comment]
I think there was some misconfiguration in the Repositories.
I deactivated an activated the Beta3 Repositories and after that and some hint from you it was in Pkgman and after! install it showed up in HaikuDepot.
