### ISSUE TITLE
BePDF, DocumentViewer, Vision: Unable to launch>Missing symbol

### ISSUE THREAD

**Issue by roired** [haikuports/haikuports#6179]
Good day,

Trying to launch Vision lately and end up always with the same dialog window saying:

"Could not open 'Vision' [Missing symbol: _ZTI6BField]"

This is happening on Haiku nightly, hrev55403 64bit.

Regards,
RR

**Comment by pulkomandy** [comment]
@waddlesplash I suspect this is a consequence of making static libs symbols private?

**Comment by waddlesplash** [comment]
Yes, indeed. `-lcolumnlistview` probably needs to go before `-lbe`. I will look into this and BePDF later, unless someone else beats me to it.

**Comment by waddlesplash** [comment]
BePDF done in https://github.com/haikuports/haikuports/commit/16f4231841ff355cfc7f430ae73afd59bc05b4ef

**Comment by waddlesplash** [comment]
I pushed fixes to HaikuArchives for Vision (https://github.com/HaikuArchives/Vision/commit/959a5bb9f18975d8246411ff9082cd98325d0b44) and DocumentViewer (https://github.com/HaikuArchives/DocumentViewer/commit/314dee24ec8361720cb6ec7420e272c98054895a), these recipes also need to be updated.

**Comment by diversys** [comment]
FTPPositive is also broken.

**Comment by diversys** [comment]
Also Kottan.

**Comment by pulkomandy** [comment]
Let's make a tasklist:

- [ ] Update Vision recipe
- [ ] Update documentViewer recipe
- [ ] Fix FTPPositive and update recipe
- [ ] Fix Kottan and update recipe

**Comment by korli** [comment]
Also check  [Puri](https://github.com/HaikuArchives/Puri/blob/21e317d9821cb856338166e115eb160894a7a77c/src/Makefile#L94 ) and [ArmyKnife](https://github.com/HaikuArchives/ArmyKnife/blob/4e92b18705930e32fd162273a58647fc7fc55537/Makefile#L85)

**Comment by Begasus** [comment]
> Also check [Puri](https://github.com/HaikuArchives/Puri/blob/21e317d9821cb856338166e115eb160894a7a77c/src/Makefile#L94) and [ArmyKnife](https://github.com/HaikuArchives/ArmyKnife/blob/4e92b18705930e32fd162273a58647fc7fc55537/Makefile#L85)

Puri needs some looking into, ArmyKnife seems to be OK (on the latest commit checkout)

**Comment by Brunobasta** [comment]
army knive 5.1.0.1 Haiku32bit nightly (55436) works!
Haiku 64bit nightly 55436 does not start! Missing symbol

**Comment by Brunobasta** [comment]
Still same here with 64bit haiku nightly hrev.: 55476
Still missing symbol:
http://0x0.st/-gNt.png
ZN_15 B_Colum List

**Comment by Brunobasta** [comment]
Vision and BePDF works fine now Haiku 64bit nightly.. 55482

**Comment by pulkomandy** [comment]
Anything left TODO here?

**Comment by Begasus** [comment]
I'm OK with closing, if things rise up again seperate issues should be created? :)
