### ISSUE TITLE
ResidualVM 0.4.0 does not start game (Haiku 32bit hrev. 55393)

### ISSUE THREAD

**Issue by Brunobasta** [haikuports/haikuports#6180]
ResidualVM starts but crash on loading the game "Escape from Monkey Island"

![image](https://user-images.githubusercontent.com/1316513/132892790-352392c1-8770-4575-8e3b-3c7bb323f646.png)

**Comment by diversys** [comment]
For the future you can just copy paste from terminal instead of linking to a picture of the terminal :)

**Comment by threedeyes** [comment]
Other opengl games works?

**Comment by Brunobasta** [comment]
not tested yes, I will try TLJ.
Maybe it is a problem with the former Residual 0.3.0 settings/config files?
Ok I will try first.
Diver, thx! I had problems before with copy/paste and drag'n drop with Git here...

**Comment by Brunobasta** [comment]
I tried with TLJ and some adjustments in Residual.ini file but does not work.

[residualvm]
filtering=true
mute=false
speech_volume=192
gui_use_game_language=true
kbdmouse_speed=3
talkspeed=60
gfx_mode=opengl
subtitles=false
fullscreen=false
gui_browser_show_hidden=false
gui_renderer=antialias
browser_lastpath=/boot/home/Games/TLJ
sfx_volume=192
music_volume=192
speech_mute=false
lastselectedgame=monkey4-win-de
vsync=true
aspect_ratio=true
versioninfo=0.4.0git
autosave_period=300
renderer=software

[monkey4-win-de]
movie_subtitles=true
movie_quality=false
description=Escape From Monkey Island (Windows/German)
mute=false
speech_volume=256
check_gamedata=false
datausr_load=false
talkspeed=179
path=/boot/home/Games/SCUMM Games/Escape from Monkey Island
music_quality=false
engineid=grim
subtitles=true
gameid=monkey4
audio_effects=true
language=de
misc_video_effects=2
gui_saveload_last_pos=3
sfx_volume=211
music_volume=30
show_fps=true
platform=windows
speech_mute=false
shadow_effects=true
gsl=unstable
guioptions=sndNoMIDI gameOption1 gameOption2 lang_German

[tlj-win-de]
enable_assets_mod=true
description=The Longest Journey (DVD/Windows/German)
extra=DVD
filtering=true
use_linear_filtering=true
path=/boot/home/Games/TLJ
engineid=stark
enable_font_antialiasing=true
fullscreen=false
gameid=tlj
language=de
platform=windows
vsync=false
aspect_ratio=true
guioptions=sndNoMIDI gameOption1 gameOption2 gameOption3 lang_German

**Comment by Brunobasta** [comment]
Still the same issues.
GUI loads but crash by loading a game:
GalliumContext: CreateScreen: Using llvmpipe (LLVM 7.0, 128 bits) driver.
User picked target 'tlj-win-de' (engine ID 'stark', game ID 'tlj')...
   Looking for a plugin supporting this target... Stark
no renderer found! 
WARNING: OpenGLGraphicsManager::endGFXTransaction: Could not load any graphics mode!!
Unlocking BLocker with sem 4032 from wrong thread 720, current holder -1 (see issue #6400).
Unlocking BLocker with sem 4024 from wrong thread 718, current holder 720 (see issue #6400).
/boot/system/apps/ResidualVM>

**Comment by Begasus** [comment]
Still an issue? ResidualVM has been imported in ScummVM for a while now.

**Comment by Brunobasta** [comment]
There are new versions of SCUMMVM to be tested now
