### ISSUE TITLE
Python: build with --enable-optimizations

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#6181]
This was [enabled](https://github.com/SerenityOS/serenity/commit/6595db9) recently in Serenity so I though we could do the same? I checked with python 3.9.7 and it builds just fine. Haven't done any tests beyond that though.

https://stackoverflow.com/questions/41405728/what-does-enable-optimizations-do-while-compiling-python

**Comment by diversys** [comment]
Apparently, it can be done: https://github.com/haikuports/haikuports/blob/dafd512fb6f6d4166b8fe3e94fb9bde83d596b80/dev-vcs/git/git-2.37.3.recipe#L297-L302

**Comment by korli** [comment]
Sure
