### ISSUE TITLE
IceBreaker, bump to 2.2.0

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#6199]
There has been a new release that is running fine when building from Terminal, would be nice to see an updated recipe for this

HOMEPAGE: https://mattdm.org/icebreaker/
SOURCE_URI: https://mattdm.org/icebreaker/2.2.x/icebreaker-2.2.0.tar.xz

**Comment by davidkaroly** [comment]
the recipe for icebreaker-2.2.1 was merged so perhaps this issue can be closed?

**Comment by korli** [comment]
sure
