### ISSUE TITLE
BeShare does not work/start with hblock enabled Haiku 55445 64bit

### ISSUE THREAD

**Issue by Brunobasta** [haikuports/haikuports#6204]
BeShare will not start anymore if you use hBlock.
I you use StevensBlock list it wont work either.

Something needs to be enabled or disabled in system/settings/network hosts-file to make  BeShare work again with hosts enabled.
Using only StevensBlackList 
or using only the hosts file generated by hBlock in Terminal 
will not work.

**Comment by Brunobasta** [comment]
Debug information for team /boot/system/apps/BeShare (1389):
CPU(s): 4x Intel Core™ i5-2500K
Memory: 19.97 GiB total, 1.02 GiB used
Haiku revision: hrev55445 Sep 23 2021 07:04:51 (x86_64)

Active Threads:
	thread 1389: BeShare (main)
	thread 1393: MUSCLE Thread 
	thread 1395: w>BeShare - Benutzer #18  - Ver 
	thread 1396: team 1389 debug task 
	thread 1400: MUSCLE Thread 
	thread 1394: MUSCLE Thread 
		state: Call (_numAvailable <= _numBlocks)

		Frame		IP			Function Name
		-----------------------------------------------
		00000000	0xd9e5ec17cf	_kern_debugger + 0x7 
			Disassembly:
				_kern_debugger:
				0x000000d9e5ec17c8:   48c7c0e4000000  mov $0xe4, %rax
				0x000000d9e5ec17cf:             0f05  syscall  <--

		0x7ff3d9e1f7a0	0xd9e5ec81d0	__assert_fail + 0x60 
		0x7ff3d9e1f7e0	0xd9e5f4d1c9	BPrivate::processHeap::free(void*) + 0x1a9 
		0x7ff3d9e1f800	0xd9e5f4e1ed	free + 0x3d 
		0x7ff3d9e1f820	0xd9e5ef6a34	_IO_new_fclose + 0x74 
		0x7ff3d9e1f830	0x183d319b3b4	_endhtent + 0x24 
		0x7ff3d9e1f890	0x183d319b89e	_gethtbyname2 + 0xbe 
		0x7ff3d9e1f8b0	0x183d319bb6c	_gethtbyname + 0x4c 
		0x7ff3d9e1fad0	0x183d319fc90	nsdispatch + 0x3c0 
		0x7ff3d9e1fb30	0x183d319ae5d	gethostbyname_internal.isra.2 + 0x23d 
		0x7ff3d9e1fb60	0x183d319afe5	gethostbyname + 0x35 
		0x7ff3d9e1fb80	0x1a09e0a1da5	muscle::GetHostByName(char const*) + 0x35 
		0x7ff3d9e1fc30	0x1a09e0611c1	muscle::ThreadSupervisorSession::MessageReceivedFromOwner(muscle::Ref<muscle::Message> const&, unsigned int) + 0x881 
		0x7ff3d9e1fc60	0x1a09e05ce32	muscle::ThreadSupervisorSession::MessageReceivedFromGateway(muscle::Ref<muscle::Message> const&, void*) + 0x32 
		0x7ff3d9e1fd90	0x1a09e06151d	muscle::SignalMessageIOGateway::DoInputImplementation(muscle::AbstractGatewayMessageReceiver&, unsigned int) + 0x9d 
		0x7ff3d9e1fdc0	0x1a09e0b0b11	muscle::AbstractReflectSession::DoInput(muscle::AbstractGatewayMessageReceiver&, unsigned int) + 0x21 
		0x7ff3d9e20030	0x1a09e0aa246	muscle::ReflectServer::ServerProcessLoop() + 0x536 
		0x7ff3d9e20060	0x1a09e05cd3d	muscle::MessageTransceiverThread::InternalThreadEntry() + 0x1d 
		0x7ff3d9e20070	0x1a09e063ff4	muscle::Thread::InternalThreadEntryFunc(void*) + 0x4 
		0x7ff3d9e20090	0xd9e5ec0547	thread_entry + 0x17 
		00000000	0x7f6230e18260	commpage_thread_exit + 0 

		Registers:
			  rip:	0x000000d9e5ec17d1
			  rsp:	0x00007ff3d9e1f758
			  rbp:	0x00007ff3d9e1f790
			  rax:	0x00000000000000e4
			  rbx:	0x000000d9e5f7ad94
			  rcx:	0x000000d9e5ec17d1
			  rdx:	0x00007ff3d9e1f26c
			  rsi:	0x0000000000000001
			  rdi:	0x000000d9e5f7ad94
			   r8:	0x0000000000000001
			   r9:	0x00000000ffffffe5
			  r10:	0x000000d9e5f7ad94
			  r11:	0x0000000000000206
			  r12:	0x000010d2ad236000
			  r13:	0x0000000000000000
			  r14:	0x0000000000000000
			  r15:	0x00000183d33c4e68
			   cs:	0x002b
			   ds:	0x0000
			   es:	0x0000
			   fs:	0x0000
			   gs:	0x0000
			   ss:	0x0023
			  st0:	0
			  st1:	0
			  st2:	0
			  st3:	0
			  st4:	0
			  st5:	0
			  st6:	0
			  st7:	0
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0, 0, 0, 0}
			  mm2:	{0, 0, 0, 0}
			  mm3:	{0, 0, 0, 0}
			  mm4:	{0, 0, 0, 0}
			  mm5:	{0, 0, 0, 0}
			  mm6:	{0, 0, 0, 0}
			  mm7:	{0, 0, 0, 0}
			 ymm0:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			 ymm1:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			 ymm2:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			 ymm3:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			 ymm4:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			 ymm5:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			 ymm6:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			 ymm7:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			 ymm8:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			 ymm9:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			ymm10:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			ymm11:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			ymm12:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			ymm13:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			ymm14:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
			ymm15:	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	4940	0x35eca37000	0x35eca4c000	0x35ecc4b000	0x35ecc4d000	lib    	/boot/system/lib/libtranslation.so
	4951	0x9e0cdad000	0x9e0cea7000	0x9e0d0a7000	0x9e0d0aa000	lib    	/boot/system/lib/libtextencoding.so
	4939	0xd9e5e83000	0xd9e5f90000	0xd9e6190000	0xd9e61e2000	lib    	/boot/system/lib/libroot.so
	4953	0xe9b0e4b000	0xe9b0e52000	0xe9b1052000	0xe9b1053000	add-on 	/boot/system/add-ons/locale/catalogs/plaintext
	4945	0xea08937000	0xea08943000	0xea08b42000	0xea08b44000	lib    	/boot/system/lib/libicuio.so.66.1
	4942	0xf94b5dc000	0xf94b5f1000	0xf94b7f1000	0xf94b7f2000	lib    	/boot/system/lib/libgcc_s.so.1
	4943	0x10a80c83000	0x10a80c84000	0x10a80e83000	0x10a80e84000	lib    	/boot/system/lib/libicudata.so.66.1
	4937	0x10b1f1d3000	0x10b1f4ea000	0x10b1f6e9000	0x10b1f717000	lib    	/boot/system/lib/libbe.so
	4950	0x11dc405e000	0x11dc4065000	0x11dc4265000	0x11dc4266000	lib    	/boot/system/lib/libbsd.so
	4954	0x12ac732f000	0x12ac7340000	0x12ac7540000	0x12ac7541000	lib    	/boot/system/lib/libroot-addon-icu.so
	4947	0x12c3d6d3000	0x12c3d89c000	0x12c3da9c000	0x12c3dab2000	lib    	/boot/system/lib/libicuuc.so.66.1
	4946	0x14209468000	0x14209498000	0x14209697000	0x142096cb000	lib    	/boot/system/lib/libicutu.so.66.1
	4944	0x157df34b000	0x157df633000	0x157df832000	0x157df84a000	lib    	/boot/system/lib/libicui18n.so.66.1
	4949	0x16cdf7ae000	0x16cdf87a000	0x16cdfa79000	0x16cdfa7a000	lib    	/boot/system/lib/libzstd.so.1.4.5
	4938	0x183d3183000	0x183d31c3000	0x183d33c2000	0x183d33cb000	lib    	/boot/system/lib/libnetwork.so
	4948	0x197c3a8e000	0x197c3aaa000	0x197c3ca9000	0x197c3caa000	lib    	/boot/system/lib/libz.so.1.2.11
	4941	0x1984c03f000	0x1984c1a1000	0x1984c3a0000	0x1984c3b4000	lib    	/boot/system/lib/libstdc++.so.6.0.25
	4936	0x1a09df62000	0x1a09e125000	0x1a09e324000	0x1a09e340000	app    	/boot/system/apps/BeShare
	4935	0x2159cb3d000	0x2159cb5c000	0x2159cd5b000	0x2159cd5d000	lib    	/boot/system/runtime_loader
	4934	0x7f6230e18000	0x7f6230e20000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	21327	0x60000000	0x60001000	         4	rw-cS      	none          	server_memory
	21329	0x68000000	0x68020000	       128	rw-cS      	none          	server_memory
	21271	0x1debb09000	0x1debb19000	        64	rw-        	none          	rld heap
	21284	0x35eca37000	0x35eca4c000	        84	r-x        	none          	libtranslation.so_seg0ro
	21285	0x35ecc4b000	0x35ecc4d000	         8	rw-        	none          	libtranslation.so_seg1rw
	21272	0x614b6f7000	0x614b6f8000	         4	rw-cS      	none          	_rld_debug_
	21312	0x98f6b1c000	0x98f6b24000	        32	rw-        	none          	rld heap
	21313	0x9d96515000	0x9d96525000	        64	rw-        	none          	rld heap
	21314	0x9e0c2c1000	0x9e0c2d1000	        64	rw-        	none          	rld heap
	21315	0x9e0c7e9000	0x9e0c801000	        96	rw-        	none          	rld heap
	21316	0x9e0c95c000	0x9e0c974000	        96	rw-        	none          	rld heap
	21310	0x9e0cdad000	0x9e0cea7000	      1000	r-x        	none          	libtextencoding.so_seg0ro
	21311	0x9e0d0a7000	0x9e0d0aa000	        12	rw-        	none          	libtextencoding.so_seg1rw
	21318	0xbb3a1a2000	0xbb3bc5f000	     27380	r--S       	none          	libicuuc.so.66 mmap area
	21281	0xd9e5e83000	0xd9e5f90000	      1076	r-x        	none          	libroot.so_seg0ro
	21282	0xd9e6190000	0xd9e619e000	        56	rw-        	none          	libroot.so_seg1rw
	21283	0xd9e619e000	0xd9e61e2000	       272	rw-        	none          	libroot.so_seg2rw
	21321	0xe9b0e4b000	0xe9b0e52000	        28	r-x        	none          	plaintext_seg0ro
	21322	0xe9b1052000	0xe9b1053000	         4	rw-        	none          	plaintext_seg1rw
	21296	0xea08937000	0xea08943000	        48	r-x        	none          	libicuio.so.66.1_seg0ro
	21297	0xea08b42000	0xea08b44000	         8	rw-        	none          	libicuio.so.66.1_seg1rw
	21289	0xf94b5dc000	0xf94b5f1000	        84	r-x        	none          	libgcc_s.so.1_seg0ro
	21290	0xf94b7f1000	0xf94b7f2000	         4	rw-        	none          	libgcc_s.so.1_seg1rw
	21291	0x10a80c83000	0x10a80c84000	         4	r-x        	none          	libicudata.so.66.1_seg0ro
	21292	0x10a80e83000	0x10a80e84000	         4	rw-        	none          	libicudata.so.66.1_seg1rw
	21276	0x10b1f1d3000	0x10b1f4ea000	      3164	r-x        	none          	libbe.so_seg0ro
	21277	0x10b1f6e9000	0x10b1f717000	       184	rw-        	none          	libbe.so_seg1rw
	21308	0x11dc405e000	0x11dc4065000	        28	r-x        	none          	libbsd.so_seg0ro
	21309	0x11dc4265000	0x11dc4266000	         4	rw-        	none          	libbsd.so_seg1rw
	21338	0x12ac732f000	0x12ac7340000	        68	r-x        	none          	libroot-addon-icu.so_seg0ro
	21339	0x12ac7540000	0x12ac7541000	         4	rw-        	none          	libroot-addon-icu.so_seg1rw
	21301	0x12c3d6d3000	0x12c3d89c000	      1828	r-x        	none          	libicuuc.so.66.1_seg0ro
	21302	0x12c3da9c000	0x12c3dab1000	        84	rw-        	none          	libicuuc.so.66.1_seg1rw
	21303	0x12c3dab1000	0x12c3dab2000	         4	rw-        	none          	libicuuc.so.66.1_seg2rw
	21298	0x14209468000	0x14209498000	       192	r-x        	none          	libicutu.so.66.1_seg0ro
	21299	0x14209697000	0x1420969a000	        12	rw-        	none          	libicutu.so.66.1_seg1rw
	21300	0x1420969a000	0x142096cb000	       196	rw-        	none          	libicutu.so.66.1_seg2rw
	21293	0x157df34b000	0x157df633000	      2976	r-x        	none          	libicui18n.so.66.1_seg0ro
	21294	0x157df832000	0x157df849000	        92	rw-        	none          	libicui18n.so.66.1_seg1rw
	21295	0x157df849000	0x157df84a000	         4	rw-        	none          	libicui18n.so.66.1_seg2rw
	21306	0x16cdf7ae000	0x16cdf87a000	       816	r-x        	none          	libzstd.so.1.4.5_seg0ro
	21307	0x16cdfa79000	0x16cdfa7a000	         4	rw-        	none          	libzstd.so.1.4.5_seg1rw
	21278	0x183d3183000	0x183d31c3000	       256	r-x        	none          	libnetwork.so_seg0ro
	21279	0x183d33c2000	0x183d33c5000	        12	rw-        	none          	libnetwork.so_seg1rw
	21280	0x183d33c5000	0x183d33cb000	        24	rw-        	none          	libnetwork.so_seg2rw
	21304	0x197c3a8e000	0x197c3aaa000	       112	r-x        	none          	libz.so.1.2.11_seg0ro
	21305	0x197c3ca9000	0x197c3caa000	         4	rw-        	none          	libz.so.1.2.11_seg1rw
	21286	0x1984c03f000	0x1984c1a1000	      1416	r-x        	none          	libstdc++.so.6.0.25_seg0ro
	21287	0x1984c3a0000	0x1984c3ac000	        48	rw-        	none          	libstdc++.so.6.0.25_seg1rw
	21288	0x1984c3ac000	0x1984c3b4000	        32	rw-        	none          	libstdc++.so.6.0.25_seg2rw
	21273	0x1a09df62000	0x1a09e125000	      1804	r-x        	none          	BeShare_seg0ro
	21274	0x1a09e324000	0x1a09e33f000	       108	rw-        	none          	BeShare_seg1rw
	21275	0x1a09e33f000	0x1a09e340000	         4	rw-        	none          	BeShare_seg2rw
	21269	0x2159cb3d000	0x2159cb5c000	       124	r-x        	none          	runtime_loader_seg0ro
	21270	0x2159cd5b000	0x2159cd5d000	         8	rw-        	none          	runtime_loader_seg1rw
	21317	0x10d2ad236000	0x10d2ad3c6000	      1600	rw-c       	none          	heap
	21369	0x7f3eedc42000	0x7f3eedc87000	       276	rw-s       	none          	MUSCLE Thread_1400_stack
	21337	0x7f4fd033f000	0x7f4fd0384000	       276	rw-s       	none          	w>BeShare_1395_stack
	21333	0x7f511efaa000	0x7f511efef000	       276	rw-s       	none          	MUSCLE Thread_1393_stack
	21268	0x7f6230e18000	0x7f6230e20000	        32	r-xSk      	full          	commpage
	21335	0x7ff3d9ddd000	0x7ff3d9e22000	       276	rw-s       	none          	MUSCLE Thread_1394_stack
	21267	0x7ff5956d7000	0x7ff5966d8000	     16388	rw-s       	none          	BeShare_1389_stack
	21265	0x7ffa518e7000	0x7ffa518eb000	        16	rw-k       	full          	user area

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	13877	    0	          0	some BBlockCache lock
	13878	    0	          0	token space
	13879	    0	          0	BLooperList lock
	13880	    0	          0	AppServerLink_sLock
	13881	    0	          0	some BLocker
	13882	    0	          0	some BLocker
	13883	    0	          0	Catalog
	13884	    0	          0	LocaleRosterData
	13885	    0	          0	some BLocker
	13886	    0	          0	Catalog
	13887	    0	          0	some BLocker
	13888	    0	          0	some BLocker
	13889	    0	          0	some BLocker
	13890	    0	          0	some BLocker
	13891	    0	          0	some BLocker
	13892	    0	          0	some BLocker
	13893	    0	          0	some BLocker
	13894	    0	          0	some BLocker
	13895	    0	          0	some BLocker
	13896	    0	          0	some BLocker
	13897	    0	          0	some BLocker
	13898	    0	          0	some BLocker
	13899	    0	          0	some BLocker
	13900	    0	          0	some BLocker
	13901	    0	          0	some BLocker
	13902	    0	          0	some BLocker
	13903	    0	          0	some BLocker
	13904	    0	          0	some BLocker
	13905	    0	          0	some BLocker
	13906	    0	          0	some BLocker
	13907	    0	          0	BMessageQueue Lock
	13908	    0	          0	AppLooperPort
	13920	    0	          0	screen list
	13921	    0	          0	clipboard
	13922	    0	          0	width buffer
	13923	    0	          0	BMessageQueue Lock
	13924	   -1	          0	BeShare
	13930	    0	          0	some BLocker
	13931	    0	          0	some BLocker
	13932	    0	          0	some BLocker
	13933	    0	          0	some BLocker
	13934	    0	          0	some BLocker
	13935	    0	          0	some BLocker
	13942	    0	          0	some BLocker
	13964	    0	          0	some BLocker
	13965	    0	          0	some BLocker
	13966	    0	          0	some BLocker
	14180	    0	          0	tool tip manager

**Comment by diversys** [comment]
This is most likely a bug in Haiku https://dev.haiku-os.org/ticket/17269.
