### ISSUE TITLE
Netsurf 3.10-3 doesn't work

### ISSUE THREAD

**Issue by iam-git** [haikuports/haikuports#6205]
hrev55448 Haiku x86_64 writes:
runtime_loader: /boot/system/apps/NetSurf: Could not resolve symbol '_ZNK4BRow8HasLatchEv'
resolve symbol "_ZNK4BRow8HasLatchEv" returned: -2147478780
runtime_loader: /boot/system/apps/NetSurf: Troubles relocating: Symbol not found

**Comment by korli** [comment]
Makefile to patch https://source.netsurf-browser.org/netsurf.git/tree/frontends/beos/Makefile#n15

`LDFLAGS += -lbe -ltranslation -lcolumnlistview -ltracker -lnetwork`

**Comment by kenmays** [comment]
NetSurf 3.10-3 currently works with Haiku R1B3 x86_64. I'll reconfirm on nightly.

**Comment by korli** [comment]
d43090c9ade0abc2f7c790ae5217eba624a7fa38 should fix
