### ISSUE TITLE
Port of Cudatext?

### ISSUE THREAD

**Issue by Alexey-T** [haikuports/haikuports#623]
I welcome if someone can port Cudatext [see my GHub]. it is Lazarus based. I don't yet use Haiku. Cannot port myself. I can help anyone who can do. 

It is text editor with the same power as SublimeText. Python3 embedded is also used. Cross platform.
(App can run w/out Python too)

**Comment by roired** [comment]
Working on it https://github.com/Alexey-T/CudaText/issues/3374

**Comment by sikmir** [comment]
> Working on it [Alexey-T/CudaText#3374](https://github.com/Alexey-T/CudaText/issues/3374)

Good news, I've tried to port some time ago, but with no success.

**Comment by Begasus** [comment]
@roired not sure where I got the working recipe from (can't find it at your github account), I have a working recipe for version 1.152.0.9 at: https://github.com/Begasus/haikuports/commit/14c6655c3f50467260be438da4ad83345cec0294
Thought it was based on the recipe you had earlier?

**Comment by korli** [comment]
@Begasus is this still current?

**Comment by Begasus** [comment]
@korli I released my work at haikuports a while ago, not the latest version but works fine on 32bit, the 64bit hasn't hit haikuports but could be retreived with the link mentioned in the post earlier.
