### ISSUE TITLE
Speed Dreams crashes at exit with Mesa 21.2.3

### ISSUE THREAD

**Issue by BeagleJoe** [haikuports/haikuports#6257]
Crashes in BGLView::UnlockGL()

Do duplicate:
Install speed_dreams from HaikuDepot
Run the game. Start a race. Hit the Escape key. Choose Quit.

Works ok with Mesa 17
Also works on nightly with Mesa 21 from LOTE repo

![newmesa](https://user-images.githubusercontent.com/5296685/136679666-5ebf1c04-9f8d-4616-8776-a0886cd3999b.png)
.

**Comment by BeagleJoe** [comment]
@waddlesplash I'm not sure what you are asking for.

**Comment by pulkomandy** [comment]
It's here: https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/hgl/GLView.cpp#L83

Apparently Mesa wants locks and unlocks to happen in the same thread and it wasn't the case here. Is it really needed? Does Mesa use thread-local storage? If not, it seems like it could let applications do whatever they want with a locked GL context, including sending it to another thread?

**Comment by BeagleJoe** [comment]
Acidentally closed

**Comment by kenmays** [comment]
@BeagleJoe - Need to use the newer SDL2 1.0.14-7 package. This package fixes the issue on both x64 Stable/Nightly.

**Comment by kenmays** [comment]
@BeagleJoe - See: https://github.com/haikuports/haikuports/pull/6295
