### ISSUE TITLE
coreutils ln: hardlink creation fails with exit code 0, potentially breaking scripts

### ISSUE THREAD

**Issue by barctor** [haikuports/haikuports#6327]
# System Information
Haiku R1/beta3 (Revision hrev55181+62) x86_64

# Expected behaviour

Using `ln` to create a hardlink should fail and the binary should exit with a non-zero status code (this behaviour confirmed on Linux).  

# Actual behaviour

No hardlink is created, but no errors are printed to stderr and the program exits with status code 0.  

# Reproducing

* Create a file
* Attempt to create a hardlink to this file using ln
* Observe the exit status

In bash this may be achieved with `touch empty; ln empty empty2; echo $?`  
This should print 0 to the terminal.  

# Why might this be a problem

Any script that tries to create a hardlink and uses the exit code to decide if this worked can fail in potentially unpredictable ways.  
To observe this in practice, [download](http://zbar.sourceforge.net/download.html) version 0.10 of the zbar library and attempt to build it.  
To build zbar extract the archive, and run `./configure --disable-video --without-gtk --without-python --without-qt --prefix /boot/home/Software/libzbar/ --build x86_64-unknown-haiku` then `make`.  

The build fails because `libtool` attempts to hardlink a couple of object files using `ln`, which causes a later build step to fail:
```
copying selected object files to avoid basename conflicts...
libtool: link: ln zbar/processor/zbar_libzbar_la-null.o zbar/.libs/libzbar.lax/lt1-zbar_libzbar_la-null.o || cp zbar/processor/zbar_libzbar_la-null.o zbar/.libs/libzbar.lax/lt1-zbar_libzbar_la-null.o
libtool: link: ln zbar/window/zbar_libzbar_la-null.o zbar/.libs/libzbar.lax/lt2-zbar_libzbar_la-null.o || cp zbar/window/zbar_libzbar_la-null.o zbar/.libs/libzbar.lax/lt2-zbar_libzbar_la-null.o
libtool: link: ar cru zbar/.libs/libzbar.a zbar/zbar_libzbar_la-config.o zbar/zbar_libzbar_la-error.o zbar/zbar_libzbar_la-symbol.o zbar/zbar_libzbar_la-image.o zbar/zbar_libzbar_la-convert.o zbar/zbar_libzbar_la-processor.o zbar/processor/zbar_libzbar_la-lock.o zbar/zbar_libzbar_la-refcnt.o zbar/zbar_libzbar_la-window.o zbar/zbar_libzbar_la-video.o zbar/zbar_libzbar_la-img_scanner.o zbar/zbar_libzbar_la-scanner.o zbar/zbar_libzbar_la-decoder.o zbar/decoder/zbar_libzbar_la-ean.o zbar/decoder/zbar_libzbar_la-code128.o zbar/decoder/zbar_libzbar_la-code39.o zbar/decoder/zbar_libzbar_la-i25.o zbar/decoder/zbar_libzbar_la-qr_finder.o zbar/qrcode/zbar_libzbar_la-qrdec.o zbar/qrcode/zbar_libzbar_la-qrdectxt.o zbar/qrcode/zbar_libzbar_la-rs.o zbar/qrcode/zbar_libzbar_la-isaac.o zbar/qrcode/zbar_libzbar_la-bch15_5.o zbar/qrcode/zbar_libzbar_la-binarize.o zbar/qrcode/zbar_libzbar_la-util.o zbar/processor/zbar_libzbar_la-posix.o zbar/video/zbar_libzbar_la-null.o zbar/zbar_libzbar_la-jpeg.o zbar/.libs/libzbar.lax/lt1-zbar_libzbar_la-null.o zbar/.libs/libzbar.lax/lt2-zbar_libzbar_la-null.o
ar: zbar/.libs/libzbar.lax/lt1-zbar_libzbar_la-null.o: No such file or directory
Makefile:1141: recipe for target 'zbar/libzbar.la' failed
```

The reason this occurs is line 8457 in `libtool` (the one created by ./configure, not the system version):
```
func_show_eval "ln $obj $gentop/$newobj || cp $obj $gentop/$newobj"
```

If `ln` failed correctly, `cp` would be tried and the build woud succeed.  
This can be observed by replacing the line with this:
```
func_show_eval "false $obj $gentop/$newobj || cp $obj $gentop/$newobj"
```

Run `make` after this change and the build continues successfully, building the library and binary (./zbarimg/zbarimg).  

# Further information

## Why does ln fail

Before going any further I must mention that I am not an experienced C or C++ developer. I am new to C++, Haiku, and the C/C++ build tooling (autotools etc.)  
Everything from this point onward in the post is based on my understanding of C/C++ and may be wrong. I tried my best, but please correct me here.

I believe `ln` fails because Haiku's error macros (in this case `B_UNSUPPORTED`) are negative when stored in a regular signed `int`.  
At line 335 in `ln.c` the variable `link_errno` is set to the return value of calling function `force_linkat`. This `force_linkat` function is defined in `force-link.c` on line 95.
According to the comment:
```c
/* Hard-link directory SRCDIR's file SRCNAME to directory DSTDIR's
   file DSTNAME, using linkat-style FLAGS to control the linking.
   If FORCE and DSTNAME already exists, replace it atomically.
   If LINKAT_ERRNO is 0, the hard link is already done; if positive,
   the hard link was tried and failed with errno == LINKAT_ERRNO.  Return
   -1 if successful and DSTNAME already existed,
   0 if successful and DSTNAME did not already exist, and
   a positive errno value on failure.  */
```
So if hardlink creation fails, a positive value should be returned.
But line 103 shows that the error is directly returned from what the `linkat` function sets `errno` to be.
Inserting some print statements into the function showed that `linkat_errno` was set to **-2147459058**.
The function then returns this value back to `ln.c`.
Having just set `link_errno` to a negative value between lines 335 to 341, directly below we see the following comment:
```c
/* Until now, link_errno < 0 meant the link has not been tried.
   From here on, link_errno < 0 means the link worked but
   required removing the destination first.  */
```
So according to `force_linkat` has returned a negative number as an error, and `ln` now assumes the link was successfully created.

## Why does linkat set a negative error

Running `strace ln exists exists2`:
```
create_link(0xffffffff, "exists2", 0xffffffff, "exists", true) = 0x8000600e Operation not supported (11 us)
```
This value ** 0x8000600e** is what the int **-2147459058** prints to with `printf("%x", linkat_errno);`.
This is also the value given when printin `printf("%x", B_UNSUPPORTED);`

# Comments

The simplest solution would probably be to maintain a Haiku-specific patch for `ln` that detects this specific error value and sets `link_errno` to a negative value.
An alternative would be to reach out to somebody more familiar with coreutils and work out whether this should be fixed upstream.

There also might be consequences to fixing this. A script that tries to create a hardlink but doesn't use the hardlink later will currently work. Fixing the bug could cause the script to fail.
I'm not sure whether there are more scripts that would be fixed or broken by a patch here.

**Comment by waddlesplash** [comment]
This is breaking the build of GCC on Haiku: https://dev.haiku-os.org/attachment/ticket/17366/BuildTools.txt

We should revert the coreutils upgrade until this should be fixed.

**Comment by korli** [comment]
Handled in 7d8d90c81469190affe4474d8c3b7f85012b8ff2
