### ISSUE TITLE
Create a recipe for youtube downloader yt-dlp

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#6338]
Since youtube-dl has been in stasis for long time, it'd be nice to have an actively developed alternative. 

From https://github.com/yt-dlp/yt-dlp :

> yt-dlp is a youtube-dl fork based on the now inactive youtube-dlc. The main focus of this project is adding new features and patches while also keeping up to date with the original project.

**Comment by korli** [comment]
added in 8569b59bfed05d75a9eb19a040f6d2cee738d3fa
