### ISSUE TITLE
DESCRIPTION extend the lines to 100 characters as is done in Haiku's source now

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#6353]
There has been a discusssion to extend the lines in the Haiku source files from 80 to 100 characters.
Maybe a good idea to set this also for the recipes?
https://github.com/haikuports/haikuports/wiki/HaikuPorter-Guidelines#description

**Comment by waddlesplash** [comment]
Yes.

**Comment by humdingerb** [comment]
Done.

**Comment by humdingerb** [comment]
Thanks, I should've in-page searching for "80"... :)
