### ISSUE TITLE
Haiku-style icon for Sonic Robo Blast 2 (SRB2)

### ISSUE THREAD

**Issue by win8linux** [haikuports/haikuports#6363]
*Sonic Robo Blast 2* recipe needs a Haiku-style icon to be created.

Original icon for reference:
![image](https://user-images.githubusercontent.com/11584387/140324840-9fff120d-6c56-4f1e-91bf-bf9495b01eb5.png)

This issue is basically about rendering Sonic the Hedgehog in the Haiku icon artstyle.

**Comment by threedeyes** [comment]
![screenshot27](https://user-images.githubusercontent.com/2559260/140468858-eec871b2-734b-4e18-a8ef-7c90b6532936.png)

[sonic.iom.zip](https://github.com/haikuports/haikuports/files/7481083/sonic.iom.zip)

**Comment by win8linux** [comment]
Closing since the icon was merged.
