### ISSUE TITLE
DWARF4 patch lost from GCC 11

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#6367]
Found here: https://github.com/haikuports/haikuports/blob/f47813e0f499406382f2a34102bdcad356ac78ca/sys-devel/gcc/patches/gcc-8.3.0_2019_05_24.patchset#L3290

This needs to be in place or else our Debugger will be unable to read generated debug information.

CC: @korli, @extrowerk.

**Comment by waddlesplash** [comment]
The LINK_SSP_SPEC patch is also missing from the GCC 11 patchset.

**Comment by waddlesplash** [comment]
Also, we probably should upgrade to GCC 11.2 ... 11.1 is already out of date :)

**Comment by pulkomandy** [comment]
Wouldn't it be better to update Debugger to handle dwarf5?

**Comment by extrowerk** [comment]
FYI: i am working on it.

**Comment by extrowerk** [comment]
On the recipe, not on the dwarf support in Debugger, to make it clear. I just can't edit the previous comment.

**Comment by extrowerk** [comment]
Seems to be solved with GCC11.2
