### ISSUE TITLE
Telegram doesn't run on a Haiku amd64 Beta 3 system

### ISSUE THREAD

**Issue by lpvm** [haikuports/haikuports#6380]
On a clean Haiku x86_64 Beta 3 system, running on an AMD Ryzen system, I've installed Telegram from HaikuDepot.

When trying to run it, it complains about a `Missing Symbol`, but doesn't specify any.
Please see the attached image.
![2021-11-08_15-24](https://user-images.githubusercontent.com/7320067/140771314-b2e90dea-11af-4af1-bd60-123c31dca70d.png)

**Comment by lpvm** [comment]
When run from the terminal,
```
> ./Telegram 
runtime_loader: /boot/system/lib/libstdc++.so.6.0.25: version "GLIBCXX_3.4.29" not found (required by Telegram)
```

**Comment by korli** [comment]
Packages are now built with a newer compiler, but the version dependency on libstdc++ isn't exposed by the hpkg. Please try to manually update the package gcc_syslibs.

**Comment by diversys** [comment]
I winder why the missing symbol is... missing in the alert window? :) Probably a bug in Tracker? So please open another ticket for this issue at https://dev.haiku-os.org/

**Comment by korli** [comment]
> I wonder why the missing symbol is... missing in the alert window? :) Probably a bug in Tracker? So please open another ticket for this issue at https://dev.haiku-os.org/

it's not a symbol?
