### ISSUE TITLE
GCC11.2: -fstack-protector doesn't works on x86

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#6382]
Build fails:
https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2066/builds/77002.log

**Comment by korli** [comment]
yeah sorry this was scattered among a few commits. This one might help.
https://github.com/haikuports/haikuports/commit/558523994f3ab645b82e257a0f40f5b3f9940469

**Comment by extrowerk** [comment]
@korli i don't really see what should we do now. The referred commit removes patches, but doesn1t add new ones.
Originally 11.1 didint had this patch, i added it in 11.2, but it is still broken. Could you explain what kind of change is needed? I can provide the required patches.

**Comment by korli** [comment]
@extrowerk please look at the commit (the recipe)

**Comment by pulkomandy** [comment]
This seems to be the part that needs to be added into the nez recipe:

	# merge libssp_nonshared.a in libgcc.a on x86
	if [ "$targetArchitecture" = "x86_gcc2" ]; then
		(mkdir temp_libgcc; cd temp_libgcc; ar x ../$gccLibDir/libssp_nonshared.a;
			ar x ../$gccLibDir/libgcc.a; cd ..)
		ar -qc $developLibDir/libgcc.a temp_libgcc/*.o
		cp $developLibDir/libgcc.a $gccLibDir/libgcc.a
		rm -rf temp_libgcc
	fi

**Comment by korli** [comment]
Thanks, fixed in e2db3969ce3b2ab09476db6552423532e9f18b6c
