### ISSUE TITLE
Bug in our gcc11 port?

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#6391]
Building opencolorio (1.1.1 - needed for blender) the build fails with: error: 'this' pointer is null [-Werror=nonnull]

https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/6359/builds/76317.log

Could be related to: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96003

Local fix is to not use `-Werror` on the build atm.

**Comment by korli** [comment]
gcc11 finds more warnings as gcc8, this is expected. usually these are fixed upstream, or disabled in ports (-Wno-error=nonnull)

**Comment by korli** [comment]
see https://github.com/AcademySoftwareFoundation/OpenColorIO/commit/9b7885176d7a2ddde5e5089bb634343ddc783e8c

why is 1.1.1 needed for blender? I would disable blender instead and remove this old version, it is not maintained upstream.

**Comment by Begasus** [comment]
Didn't check (yet) if our current blender still runs, but atm it still depends on the old version (this also includes previous yaml-cpp)

**Comment by Begasus** [comment]
This can be closed I guess, when someone stumbles into this it can be found here still.
(giving up on blender, can install but then complains about openimageio) :)
