### ISSUE TITLE
bump recipe for ccache

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#6398]
Current version in haikuports is 3.7.6
Bump to version 4.4.2

**Comment by Begasus** [comment]
Looking into this, the build changed to cmake and a new optional dependency has been added to it "hiredis"

**Comment by Begasus** [comment]
PR created at https://github.com/haikuports/haikuports/pull/6401 could you check @Vidrep ?

**Comment by Vidrep** [comment]
Version 4.4.2 returns this error when building HaikuWebKit. ccache 3.7.6 working OK. It looks like a problem with links.

ccache: error: failed to link /boot/home/.ccache/tmp/tmp.cpp_stdout.fsgyCX to /boot/home/.ccache/tmp/tmp.cpp_stdout.fsgyCX.ii: Operation not allowed

**Comment by Vidrep** [comment]
I copied the recipe and patchset for ccache 4.5.1 (latest version). It builds OK, but returns the same linking error as 4.4.2 when building HaikuWebKit.

**Comment by Vidrep** [comment]
When building HaikuWebKit,
ccache 3.7.6 links to /boot/home/.cache (working)
ccache 4.4.2 links to /boot/home/config/cache/ccache
This may be the cause of the error message below:
ccache: error: failed to link /boot/home/.ccache/tmp/tmp.cpp_stdout.fsgyCX to boot/home/.ccache/tmp/tmp.cpp_stdout.fsgyCX.ii: Operation not allowed

**Comment by Begasus** [comment]
I need to find something (smaller then HaikuWebKit :) ) to check this, will try to see if I can find anything there (if no one beats me to it), @pulkomandy you build that thing also, are you experiencing something similar there?

**Comment by pulkomandy** [comment]
I don't use ccache.

**Comment by Begasus** [comment]
Latest 4.6 version shows the same error (checked with cavepacker), maybe we should disable the 4.* version?

**Comment by Begasus** [comment]
Updated in the meantime to 4.10.
