### ISSUE TITLE
Add PlayLister to HaikuArchives

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#640]
@waddlesplash ummm this one has an interesting licence....

[Playlister-1.2-x86_src-incl.zip](https://github.com/haikuports/haikuports/files/321708/Playlister-1.2-x86_src-incl.zip)

**Comment by waddlesplash** [comment]
![nope](https://cloud.githubusercontent.com/assets/2175324/16179240/beee30ea-362d-11e6-9627-802478aa432f.jpg)
