### ISSUE TITLE
vulkan: build failed on x86

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#6403]
Ref: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2088/builds/77044.log

**Comment by diversys** [comment]
cc @X547

**Comment by X547** [comment]
Seems some secondary architecture paths problem.

**Comment by kenmays** [comment]
Fixed.

**Comment by diversys** [comment]
When was it fixed? Please stop randomly close tickets.

**Comment by kenmays** [comment]
@diver - It is fixed. Check the PR.

**Comment by korli** [comment]
fixed in 967de252e42c1a32f532f68e166aae615ace0f86
