### ISSUE TITLE
uptime broken?

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#6405]
Trying to run it in Terminal fails now:
```
~> uptime
uptime: /etc/utmp: No such file or directory
```
```
~> strace -o logggg uptime output
uptime: output: No such file or directory
strace: Failed to run thread 1547: Bad port ID
```

Maybe introduced with the new coreutils?

**Comment by extrowerk** [comment]
Uptime is not the only cli executable emmitting the same error, i planned open an issue with a list of the affected programs, but i am awk now.
