### ISSUE TITLE
Drop ICU 57 on x86_64 (and everywhere else but gcc2)

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#6409]
As in title. It appears ICU 57 is still built by default. We should drop it in favor of ICU 66 completely, and rebuild whatever packages depend on it.

**Comment by X547** [comment]
Note that migration from ICU 57 is not yet completed for RISC-V and maybe other architectures. Haiku riscv64 do not boot with ICU 66+ (probably inconsistent packages from haikuports.cross).

cc @kallisti5
