### ISSUE TITLE
Switch to using _bin package for QtWebEngine

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#6415]
We already use a `_bin` package for Rust (and the real recipe is marked untested) due to how long Rust takes to build and how much RAM it needs. We should do the same for QtWebEngine, as it looks like it is going to take around 24 hours to complete a build on the buildmaster: https://build.haiku-os.org/buildmaster/master/x86_64/?buildrunDir=6391&viewMode=expanded

**Comment by waddlesplash** [comment]
Over 25 hours, and now at [18513/21219]. All the more reason to have a _bin package.

**Comment by threedeyes** [comment]
How much RAM does the buildmaster have? Maybe they have started to swap?
I managed to rebuild qtwebengine package 6 times from scratch during this time. ))
On my Rizen7 it takes about an hour and a half to build.

**Comment by waddlesplash** [comment]
I would have to check, but I think it's a few GB at most.

>  I managed to rebuild qtwebengine package 6 times from scratch during this time. ))

Does that mean we can expect some new features before long? :)

**Comment by waddlesplash** [comment]
It's currently at `[19979/21219]`.

**Comment by waddlesplash** [comment]
Ah, I see you made an audio backend. @threedeyes, if you can upload a `_bin` recipe, I can kill the existing build.
