### ISSUE TITLE
make: build failed

### ISSUE THREAD

**Issue by davidkaroly** [haikuports/haikuports#6417]
I tried rebuilding make on recent Haiku nightly and I got the following error:

```
compiling dir.c...
./dir.c: In function 'read_dirstream':
./dir.c:1145:50: error: invalid application of 'sizeof' to incomplete type 'char[]'
 1145 |           unsigned int sz = sizeof (*d) - sizeof (d->d_name) + len;
      |                                                  ^
Warning: Command '['bash', '-c', '. /wrapper-script']' returned non-zero exit status 1.
Error: Build has failed - stopping.

```

The same issue occurs also when doing bootstrap build with cross compile. (I tried bootstrap for arm but it could be relevant for other arch as well)

Can it be related to the recent change in dirent.h?

**Comment by waddlesplash** [comment]
Yes, it is.

The portable way of doing this would be to use `(offsetof(d, d_name) - sizeof(struct dirent))`, I think. Not sure if we should submit such a patch upstream however.

**Comment by waddlesplash** [comment]
Ultimately the problem here is that GCC does not treat char[0] and char[] equivalently, or else I would have used the former, which returns sizeof()=0. (GCC throws errors when you try to access any data in a char[0], it doesn't on char[]).

**Comment by davidkaroly** [comment]
We can use a simple workaround like this to get a successful build:

```
           struct dirent *d;
           size_t len = df->length + 1;
-          size_t sz = sizeof (*d) - sizeof (d->d_name) + len;
+          size_t sz = sizeof (*d) + len;

```

Clearly this is not a portable solution and definitely not suitable for upstreaming.

Test results - with "haikuporter -test"
- make-4.1: n/a, the recipe does not perform any testing
- make-4.2.1: test suite crashes with ulimit related error message - probably not related to the dirent refactor
- make-4.3: 5 tests failed - not sure if any of them might be related

**Comment by davidkaroly** [comment]
A short test:

```
        printf("sizeof(struct dirent) = %d\n", sizeof(struct dirent));
        printf("offsetof(struct dirent, d_name) = %d\n", offsetof(struct dirent, d_name));
```

output:
```
sizeof(struct dirent) = 32
offsetof(struct dirent, d_name) = 26
```

So the workaround in my previous comment might be wasting a few bytes.

Perhaps the following could work - haven't tried it yet:

```
          size_t sz = offsetof (struct dirent, d_name) + len;
```

**Comment by waddlesplash** [comment]
Yes, your last example is the way to go here. (Probably we should use something similar in Haiku itself.)

**Comment by davidkaroly** [comment]
I created draft PR #6436

build OK on x86_64
as a simple test I tried rebuilding libpcap with 4 parallel jobs, seems to work.

**Comment by davidkaroly** [comment]
the related pr has been merged so I think we can close this issue
