### ISSUE TITLE
Enable Emacs GUI in next release

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#6425]
It appears someone has written a full GUI frontend for Haiku for Emacs and upstreamed it: https://github.com/emacs-mirror/emacs/commit/85a078e7853d708e599f97a3de06aed3a1c090ea

We should make sure the next version of the recipe includes this.

**Comment by e3bc54b2** [comment]
Indeed, and it builds and works very well (so far, for me). I created another ticket to add libgccjit #6440.

With Emacs, Haiku is more or less complete for me,

**Comment by augiedoggie** [comment]
Forgot to mention this issue in the pull request.  Emacs recipe has been updated to 29.0.50~git in be896abe with Haiku GUI support.

**Comment by waddlesplash** [comment]
Very good!
