### ISSUE TITLE
stress-ng: stress-icache does not work on x86

### ISSUE THREAD

**Issue by davidkaroly** [haikuports/haikuports#6428]
If I build stress-ng for x86 secondary architecture, I get a defunct executable:

```
~/haikuports/app-benchmarks/stress-ng/work-x86-0.13.05/sources/stress-ng-0.13.05> stress-ng
runtime_loader: /boot/home/haikuports/app-benchmarks/stress-ng/work-x86-0.13.05/sources/stress-ng-0.13.05/stress-ng: Could not map image: Bad data
~/haikuports/app-benchmarks/stress-ng/work-x86-0.13.05/sources/stress-ng-0.13.05>

```

The issue is caused by stress-icache as it's linked in its own section stress_icache_cal aligned on 64K boundary.
This results in a gap greater than 8K between two sections in the executable file, therefore runtime_loader gives as B_BAD_DATA.
see: https://github.com/haiku/haiku/blob/master/src/system/runtime_loader/images.cpp#L335

```
	// Check whether the segments have an unreasonable amount of unused space
	// inbetween.
	if (reservedSize > length + MAX_PAGE_SIZE * 2)
		return B_BAD_DATA;

```

No such error on x86_64 as MAX_PAGE_SIZE is defined as 2M there.

**Comment by korli** [comment]
x86 uses an older binutils, might also be related

**Comment by davidkaroly** [comment]
attaching "bad" and "good" section list generated with "readelf -S"

the original binary contains section stress_icache_cal aligned on 64K

if I remove the 64K alignment (but leave in the next alignment in the sources which is 16K) i get a binary where stress_icache_cal is aligned on 16K and now it's possible to load it on 32-bit Haiku

[stress_ng_bad.txt](https://github.com/haikuports/haikuports/files/7609791/stress_ng_bad.txt)
[stress_ng_good.txt](https://github.com/haikuports/haikuports/files/7609794/stress_ng_good.txt)

**Comment by davidkaroly** [comment]
...and this seems to be a good solution, as the 64K-aligned section is only used if the page size is 64K which is not the case on x86.

**Comment by davidkaroly** [comment]
#6435

**Comment by Begasus** [comment]
![DSC_0387](https://user-images.githubusercontent.com/16057090/144702289-9c7f59c6-0d10-43f1-965b-aa2d96cd3e48.JPG)

KDL when trying to run one of the examples there ... (32bit R1B3)

**Comment by diversys** [comment]
This should be reported in Haiku's Trac.

**Comment by Begasus** [comment]
> This should be reported in Haiku's Trac.

Done in https://dev.haiku-os.org/ticket/17448

**Comment by davidkaroly** [comment]
stress-ng related PRs have been merged and trac ticket exists for any instabilities found. Therefore I believe this ticket can be closed.

**Comment by Begasus** [comment]
Didn't check this recently, has something changed in the meantime?
