### ISSUE TITLE
Add Attr2id3 to HaikuArchives

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#644]
[attr2id3_src-incl.zip](https://github.com/haikuports/haikuports/files/321720/attr2id3_src-incl.zip)

Other similar cml apps:
[id3attr-1.3.0_src-incl.zip](https://github.com/haikuports/haikuports/files/321722/id3attr-1.3.0_src-incl.zip)
[ID3tag-R4-x86-0.9b_src-incl.zip](https://github.com/haikuports/haikuports/files/321723/ID3tag-R4-x86-0.9b_src-incl.zip)

**Comment by waddlesplash** [comment]
It's ID3v1, ArmyKnife already does this, and it's kinda hacky.
