### ISSUE TITLE
Add libgccjit

### ISSUE THREAD

**Issue by bhankas** [haikuports/haikuports#6440]
libgccjit is a way to package GCC as a lib for using as JIT compiler.

documentation: 
https://gcc.gnu.org/wiki/JIT
https://gcc.gnu.org/onlinedocs/jit/

Recently GNU Emacs got a support for building on Haiku as one of the target platform. I can confirm (in my limited usage) it builds and works just fine. I'll be making more use (and hence testing) of it over coming weeks. 

Emacs also recently got support for native compilation via libgccjit. Without libgccjit, we are limited to using slower interpreter and bytecode compiler. It will be nice to have full spectrum of Emacs capabilities available on Haiku, but libgccjit is not present in haikudepot.

**Comment by Begasus** [comment]
@nielx any possibility to add this to our gcc package, builds ok out of the box but not sure if it needs any patching. :)

**Comment by nielx** [comment]
Note to self: libgccjit packaging notes: https://gcc.gnu.org/onlinedocs/jit/internals/index.html#packaging-notes
