### ISSUE TITLE
Bug with language selection in Lagrange

### ISSUE THREAD

**Issue by HSDChannel** [haikuports/haikuports#6444]
<img src="https://i.imgur.com/iWUxDzG.png"></a>
If you expand the window to full screen, everything is in its place:
 <img src="https://i.imgur.com/xOQI58R.png"></a>

**Comment by sikmir** [comment]
Confirm, I have the same issue.

**Comment by skyjake** [comment]
Large popup menus, including the language selection dropdown, are SDL-managed separate windows. Perhaps there's a problem with setting up or drawing with a second SDL renderer in the same app?

I suggest using the `ENABLE_POPUP_MENUS=NO` build option to disable the use of windows for menus.

**Comment by sikmir** [comment]
It works for me with `ENABLE_POPUP_MENUS=NO`. Thanks!
