### ISSUE TITLE
ghostscript does not run anymore on Haiku

### ISSUE THREAD

**Issue by lelldorin** [haikuports/haikuports#6456]
gs -dNODISPLAY  -dNOPAUSE -dBATCH /boot/home/Desktop/DiscoverHaiku.pdf |grep Page|wc -l

**runtime_loader: /boot/system/lib/x86/libstdc++.so.6.0.25: version "GLIBCXX_3.4.29" not found (required by gs)
0**

I get this output any time, on top is an example script

**Comment by korli** [comment]
Please upgrade ghostscript and try again.

**Comment by lelldorin** [comment]
I already installed the one, available over HaikuDepot. I think this should be the current one. Is there a development release too?

**Comment by korli** [comment]
it should upgrade to 9.55.0-2
