### ISSUE TITLE
Lagrange crashes when trying to update the feed list

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#6468]
Hi.  When I try to update the feed list (click "refresh feed" button), the application crash:

I'm using Haiku 32 bit version, with the last Lagrange package (1.9.2-1)

<details>

`
Debug information for team /boot/system/apps/Lagrange/lagrange (817):
CPU(s): 4x Intel Core i3
Memory: 1.86 GiB total, 426.50 MiB used
Haiku revision: hrev55706 Dec  8 2021 08:00:20 (BePC)

Active Threads:
	thread 817: lagrange (main)
	thread 818: SDLTimer 
	thread 819: SDLApplication 
	thread 823: direct daemon 
	thread 824: drawing_thread 
	thread 825: w>cmccabe 
	thread 826: llvmpipe-0 
	thread 827: llvmpipe-1 
	thread 828: llvmpipe-2 
	thread 829: llvmpipe-3 
	thread 830: pthread func 
	thread 831: pthread func 
	thread 832: pthread func 
	thread 833: pthread func 
	thread 834: lagrang:disk$0 
	thread 837: pthread func 
	thread 841: pthread func 
	thread 852: team 817 debug task 
	thread 840: pthread func 
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x70f15470	0x11b15db	strlen + 0x2b 
			Disassembly:
				strlen:
				0x011b15b0:               55  push %ebp
				0x011b15b1:             89e5  mov %esp, %ebp
				0x011b15b3:               53  push %ebx
				0x011b15b4:           8b4d08  mov 0x8(%ebp), %ecx
				0x011b15b7:           f6c103  test $0x3, %cl
				0x011b15ba:             744c  jz 0x11b1608
				0x011b15bc:             31c0  xor %eax, %eax
				0x011b15be:             eb09  jmp 0x11b15c9
				0x011b15c0:               40  inc %eax
				0x011b15c1:           8d1401  lea (%ecx,%eax), %edx
				0x011b15c4:           f6c203  test $0x3, %dl
				0x011b15c7:             7412  jz 0x11b15db
				0x011b15c9:         803c0100  cmp $0x0, (%ecx,%eax)
				0x011b15cd:             75f1  jnz 0x11b15c0
				0x011b15cf:               5b  pop %ebx
				0x011b15d0:               5d  pop %ebp
				0x011b15d1:               c3  ret 
				0x011b15d2:     8db600000000  lea (%esi), %esi
				0x011b15d8:           83c204  add $0x4, %edx
				0x011b15db:             8b02  mov (%edx), %eax <--

			Frame memory:
				[0x70f15464]  H....}.p....   48 85 1f 01 f8 7d f1 70 be d5 18 01
		0x70f17df8	0x118d5b9	_IO_vfprintf + 0x45a9 
		0x70f17f28	0x1171661	vsnprintf + 0x81 
		0x70f17f58	0x15ae533	vprintf_Block + 0x23 
		0x70f17f78	0x15b9dae	format_String + 0x1e 
		0x70f18078	0x14e1ecb	fetch_Feeds_ + 0xd1b 
		0x70f18098	0x15bdee4	run_Threads_ + 0x34 
		0x70f180c0	0x1149c6f	pthread_thread_entry(void*, void*) + 0x1f 
		00000000	0x60bbd250	commpage_thread_exit + 0 

		Registers:
			  eip:	0x011b15db
			  esp:	0x70f15464
			  ebp:	0x70f15468
			  eax:	0x70f17fa0
			  ebx:	0x011f8548
			  ecx:	0x232c1eb0
			  edx:	0x232c1eb0
			  esi:	0x011f8548
			  edi:	0xffffffff
			   cs:	0x001b
			   ds:	0x0023
			   es:	0x0023
			   fs:	0x0063
			   gs:	0x0023
			   ss:	0x0023
			  st0:	nan
			  st1:	nan
			  st2:	0
			  st3:	0
			  st4:	8.59e+07
			  st5:	341
			  st6:	17
			  st7:	1.56e+07
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0xff, 0, 0, 0}
			  mm2:	{0, 0, 0, 0}
			  mm3:	{0, 0, 0, 0}
			  mm4:	{0, 0, 0x9e20, 0xa3ed}
			  mm5:	{0, 0, 0, 0xaa80}
			  mm6:	{0xa61a, 0xd4b6, 0x5e41, 0x880f}
			  mm7:	{0, 0, 0, 0xed4e}
			 xmm0:	{0, 0, 0, 0x3fe0, 0, 0, 0, 0}
			 xmm1:	{0x9298, 0x7561, 0, 0, 0x8086, 0x3b0b, 0x1028, 0x471}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0x6aea, 0x1bf0, 0x5bec, 0x4a8d, 0x7695, 0x9b74, 0x5609, 0x302d}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	3598	0x003b5000	0x003fb000	0x003fb000	0x003fc000	lib    	/boot/system/lib/x86/libpcre.so.1.2.13
	3602	0x0041e000	0x0044a000	0x0044a000	0x0044c000	lib    	/boot/system/lib/x86/libGL.so.1.0.0
	3600	0x004cb000	0x0068e000	0x0068e000	0x006aa000	lib    	/boot/system/lib/x86/libcrypto.so.1.1
	3599	0x00870000	0x008dc000	0x008dc000	0x008e5000	lib    	/boot/system/lib/x86/libssl.so.1.1
	3617	0x00a38000	0x00bf4000	0x00bf4000	0x00c02000	lib    	/boot/system/lib/x86/libicuuc.so.66.1
	3614	0x00cfd000	0x00cfe000	0x00cfe000	0x00cff000	lib    	/boot/system/lib/x86/libicudata.so.66.1
	3592	0x00dbd000	0x00df5000	0x00df5000	0x00dfc000	lib    	/boot/system/lib/x86/libnetwork.so
	3618	0x00e66000	0x00f2f000	0x00f2f000	0x00f31000	lib    	/boot/system/lib/x86/libzstd.so.1.5.0
	3609	0x00f37000	0x00f50000	0x00f50000	0x00f51000	lib    	/boot/system/lib/x86/libgcc_s.so.1
	3589	0x00fd9000	0x010d0000	0x010d0000	0x010d8000	lib    	/boot/system/lib/x86/libSDL2-2.0.so.0.14.0
	3601	0x0110a000	0x011f5000	0x011f5000	0x01235000	lib    	/boot/system/lib/x86/libroot.so
	3591	0x012a0000	0x012bb000	0x012bb000	0x012bc000	lib    	/boot/system/lib/x86/libfribidi.so.0.4.0
	3619	0x01342000	0x01352000	0x01352000	0x01354000	lib    	/boot/system/lib/x86/libbz2.so.1.0.8
	3593	0x0147e000	0x01484000	0x01484000	0x01485000	lib    	/boot/system/lib/x86/libbsd.so
	3588	0x014a8000	0x015d8000	0x015d8000	0x015de000	app    	/boot/system/apps/Lagrange/lagrange
	3607	0x015ee000	0x016e5000	0x016e5000	0x016e7000	lib    	/boot/system/lib/x86/libtextencoding.so
	3595	0x0170b000	0x01771000	0x01771000	0x01774000	lib    	/boot/system/lib/x86/libwebp.so.7.1.2
	3620	0x01789000	0x017b4000	0x017b4000	0x017b5000	lib    	/boot/system/lib/x86/libpng16.so.16.37.0
	3611	0x017b8000	0x017de000	0x017de000	0x017e0000	lib    	/boot/system/lib/x86/libgraphite2.so.3.2.1
	3596	0x017e1000	0x01952000	0x01952000	0x01955000	lib    	/boot/system/lib/x86/libunistring.so.2.1.0
	3587	0x019c8000	0x019e5000	0x019e5000	0x019e7000	lib    	/boot/system/runtime_loader
	3608	0x01a60000	0x01c30000	0x01c30000	0x01c3f000	lib    	/boot/system/lib/x86/libstdc++.so.6.0.29
	3610	0x01c40000	0x01cf6000	0x01cf6000	0x01cfb000	lib    	/boot/system/lib/x86/libfreetype.so.6.18.0
	3605	0x01cfe000	0x01d1b000	0x01d1b000	0x01d1d000	lib    	/boot/system/lib/x86/libgame.so
	3612	0x01d1d000	0x01dfb000	0x01dfb000	0x01dfc000	lib    	/boot/system/lib/x86/libiconv.so.2.6.1
	3594	0x01e01000	0x01e5c000	0x01e5c000	0x01e5e000	lib    	/boot/system/lib/x86/libmpg123.so.0.46.2
	3597	0x01e63000	0x01e7b000	0x01e7b000	0x01e7c000	lib    	/boot/system/lib/x86/libz.so.1.2.11
	3621	0x01e7e000	0x01e8f000	0x01e8f000	0x01e90000	lib    	/boot/system/lib/x86/libroot-addon-icu.so
	3616	0x01e91000	0x01e9c000	0x01e9c000	0x01e9d000	lib    	/boot/system/lib/x86/libicuio.so.66.1
	3590	0x01eba000	0x01fc0000	0x01fc0000	0x01fc2000	lib    	/boot/system/lib/x86/libharfbuzz.so.0.20801.0
	3613	0x02164000	0x0219e000	0x0219e000	0x021a3000	lib    	/boot/system/lib/x86/libglapi.so.0.0.0
	3606	0x021c7000	0x021d5000	0x021d5000	0x021d6000	lib    	/boot/system/lib/x86/libdevice.so
	3604	0x02352000	0x023fd000	0x023fd000	0x02404000	lib    	/boot/system/lib/x86/libmedia.so
	3603	0x0268d000	0x0298b000	0x0298b000	0x029a5000	lib    	/boot/system/lib/x86/libbe.so
	3615	0x02aaa000	0x02d94000	0x02d94000	0x02da1000	lib    	/boot/system/lib/x86/libicui18n.so.66.1
	3623	0x05341000	0x05d14000	0x05d14000	0x05f86000	add-on 	/boot/system/add-ons/x86/opengl/Software Pipe
	3624	0x0607c000	0x0a0bf000	0x0a0bf000	0x0a466000	lib    	/boot/system/lib/x86/libLLVM-9.so
	3586	0x60bbd000	0x60bc5000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	9983	0x00270000	0x00280000	        64	rw-        	none          	rld heap
	10009	0x003b5000	0x003fb000	       280	r-x        	none          	libpcre.so.1.2.13_seg0ro
	10010	0x003fb000	0x003fc000	         4	rw-        	none          	libpcre.so.1.2.13_seg1rw
	10019	0x0041e000	0x0044a000	       176	r-x        	none          	libGL.so.1.0.0_seg0ro
	10020	0x0044a000	0x0044c000	         8	rw-        	none          	libGL.so.1.0.0_seg1rw
	9984	0x00464000	0x00465000	         4	rw-cS      	none          	_rld_debug_
	10060	0x004bc000	0x004c4000	        32	rw-        	none          	rld heap
	10013	0x004cb000	0x0068e000	      1804	r-x        	none          	libcrypto.so.1.1_seg0ro
	10014	0x0068e000	0x006a7000	       100	rw-        	none          	libcrypto.so.1.1_seg1rw
	10015	0x006a7000	0x006aa000	        12	rw-        	none          	libcrypto.so.1.1_seg2rw
	10061	0x006d3000	0x006db000	        32	rw-        	none          	rld heap
	10062	0x007b2000	0x007c2000	        64	rw-        	none          	rld heap
	10063	0x00811000	0x00821000	        64	rw-        	none          	rld heap
	10011	0x00870000	0x008dc000	       432	r-x        	none          	libssl.so.1.1_seg0ro
	10012	0x008dc000	0x008e5000	        36	rw-        	none          	libssl.so.1.1_seg1rw
	10051	0x00a38000	0x00bf4000	      1776	r-x        	none          	libicuuc.so.66.1_seg0ro
	10052	0x00bf4000	0x00c01000	        52	rw-        	none          	libicuuc.so.66.1_seg1rw
	10053	0x00c01000	0x00c02000	         4	rw-        	none          	libicuuc.so.66.1_seg2rw
	10045	0x00cfd000	0x00cfe000	         4	r-x        	none          	libicudata.so.66.1_seg0ro
	10046	0x00cfe000	0x00cff000	         4	rw-        	none          	libicudata.so.66.1_seg1rw
	9995	0x00dbd000	0x00df5000	       224	r-x        	none          	libnetwork.so_seg0ro
	9996	0x00df5000	0x00df7000	         8	rw-        	none          	libnetwork.so_seg1rw
	9997	0x00df7000	0x00dfc000	        20	rw-        	none          	libnetwork.so_seg2rw
	10077	0x00e43000	0x00e55000	        72	rw-rw-     	none          	BeControlLook_seg0ro
	10078	0x00e55000	0x00e57000	         8	rw-        	none          	BeControlLook_seg1rw
	10054	0x00e66000	0x00f2f000	       804	r-x        	none          	libzstd.so.1.5.0_seg0ro
	10055	0x00f2f000	0x00f31000	         8	rw-        	none          	libzstd.so.1.5.0_seg1rw
	10035	0x00f37000	0x00f50000	       100	r-x        	none          	libgcc_s.so.1_seg0ro
	10036	0x00f50000	0x00f51000	         4	rw-        	none          	libgcc_s.so.1_seg1rw
	9988	0x00fd9000	0x010d0000	       988	r-x        	none          	libSDL2-2.0.so.0.14.0_seg0ro
	9989	0x010d0000	0x010d6000	        24	rw-        	none          	libSDL2-2.0.so.0.14.0_seg1rw
	9990	0x010d6000	0x010d8000	         8	rw-        	none          	libSDL2-2.0.so.0.14.0_seg2rw
	10016	0x0110a000	0x011f5000	       940	r-x        	none          	libroot.so_seg0ro
	10017	0x011f5000	0x011ff000	        40	rw-        	none          	libroot.so_seg1rw
	10018	0x011ff000	0x01235000	       216	rw-        	none          	libroot.so_seg2rw
	9993	0x012a0000	0x012bb000	       108	r-x        	none          	libfribidi.so.0.4.0_seg0ro
	9994	0x012bb000	0x012bc000	         4	rw-        	none          	libfribidi.so.0.4.0_seg1rw
	10056	0x01342000	0x01352000	        64	r-x        	none          	libbz2.so.1.0.8_seg0ro
	10057	0x01352000	0x01354000	         8	rw-        	none          	libbz2.so.1.0.8_seg1rw
	9998	0x0147e000	0x01484000	        24	r-x        	none          	libbsd.so_seg0ro
	9999	0x01484000	0x01485000	         4	rw-        	none          	libbsd.so_seg1rw
	9985	0x014a8000	0x015d8000	      1216	r-x        	none          	lagrange_seg0ro
	9986	0x015d8000	0x015dd000	        20	rw-        	none          	lagrange_seg1rw
	9987	0x015dd000	0x015de000	         4	rw-        	none          	lagrange_seg2rw
	10030	0x015ee000	0x016e5000	       988	r-x        	none          	libtextencoding.so_seg0ro
	10031	0x016e5000	0x016e7000	         8	rw-        	none          	libtextencoding.so_seg1rw
	10002	0x0170b000	0x01771000	       408	r-x        	none          	libwebp.so.7.1.2_seg0ro
	10003	0x01771000	0x01772000	         4	rw-        	none          	libwebp.so.7.1.2_seg1rw
	10004	0x01772000	0x01774000	         8	rw-        	none          	libwebp.so.7.1.2_seg2rw
	10058	0x01789000	0x017b4000	       172	r-x        	none          	libpng16.so.16.37.0_seg0ro
	10059	0x017b4000	0x017b5000	         4	rw-        	none          	libpng16.so.16.37.0_seg1rw
	10039	0x017b8000	0x017de000	       152	r-x        	none          	libgraphite2.so.3.2.1_seg0ro
	10040	0x017de000	0x017e0000	         8	rw-        	none          	libgraphite2.so.3.2.1_seg1rw
	10005	0x017e1000	0x01952000	      1476	r-x        	none          	libunistring.so.2.1.0_seg0ro
	10006	0x01952000	0x01955000	        12	rw-        	none          	libunistring.so.2.1.0_seg1rw
	9981	0x019c8000	0x019e5000	       116	r-x        	none          	runtime_loader_seg0ro
	9982	0x019e5000	0x019e7000	         8	rw-        	none          	runtime_loader_seg1rw
	10032	0x01a60000	0x01c30000	      1856	r-x        	none          	libstdc++.so.6.0.29_seg0ro
	10033	0x01c30000	0x01c38000	        32	rw-        	none          	libstdc++.so.6.0.29_seg1rw
	10034	0x01c38000	0x01c3f000	        28	rw-        	none          	libstdc++.so.6.0.29_seg2rw
	10037	0x01c40000	0x01cf6000	       728	r-x        	none          	libfreetype.so.6.18.0_seg0ro
	10038	0x01cf6000	0x01cfb000	        20	rw-        	none          	libfreetype.so.6.18.0_seg1rw
	10026	0x01cfe000	0x01d1b000	       116	r-x        	none          	libgame.so_seg0ro
	10027	0x01d1b000	0x01d1d000	         8	rw-        	none          	libgame.so_seg1rw
	10041	0x01d1d000	0x01dfb000	       888	r-x        	none          	libiconv.so.2.6.1_seg0ro
	10042	0x01dfb000	0x01dfc000	         4	rw-        	none          	libiconv.so.2.6.1_seg1rw
	10000	0x01e01000	0x01e5c000	       364	r-x        	none          	libmpg123.so.0.46.2_seg0ro
	10001	0x01e5c000	0x01e5e000	         8	rw-        	none          	libmpg123.so.0.46.2_seg1rw
	10007	0x01e63000	0x01e7b000	        96	r-x        	none          	libz.so.1.2.11_seg0ro
	10008	0x01e7b000	0x01e7c000	         4	rw-        	none          	libz.so.1.2.11_seg1rw
	10066	0x01e7e000	0x01e8f000	        68	r-x        	none          	libroot-addon-icu.so_seg0ro
	10067	0x01e8f000	0x01e90000	         4	rw-        	none          	libroot-addon-icu.so_seg1rw
	10049	0x01e91000	0x01e9c000	        44	r-x        	none          	libicuio.so.66.1_seg0ro
	10050	0x01e9c000	0x01e9d000	         4	rw-        	none          	libicuio.so.66.1_seg1rw
	9991	0x01eba000	0x01fc0000	      1048	r-x        	none          	libharfbuzz.so.0.20801.0_seg0ro
	9992	0x01fc0000	0x01fc2000	         8	rw-        	none          	libharfbuzz.so.0.20801.0_seg1rw
	10043	0x02164000	0x0219e000	       232	r-x        	none          	libglapi.so.0.0.0_seg0ro
	10044	0x0219e000	0x021a3000	        20	rw-        	none          	libglapi.so.0.0.0_seg1rw
	10028	0x021c7000	0x021d5000	        56	r-x        	none          	libdevice.so_seg0ro
	10029	0x021d5000	0x021d6000	         4	rw-        	none          	libdevice.so_seg1rw
	10023	0x02352000	0x023fd000	       684	r-x        	none          	libmedia.so_seg0ro
	10024	0x023fd000	0x02403000	        24	rw-        	none          	libmedia.so_seg1rw
	10025	0x02403000	0x02404000	         4	rw-        	none          	libmedia.so_seg2rw
	10021	0x0268d000	0x0298b000	      3064	r-x        	none          	libbe.so_seg0ro
	10022	0x0298b000	0x029a5000	       104	rw-        	none          	libbe.so_seg1rw
	10047	0x02aaa000	0x02d94000	      2984	r-x        	none          	libicui18n.so.66.1_seg0ro
	10048	0x02d94000	0x02da1000	        52	rw-        	none          	libicui18n.so.66.1_seg1rw
	10065	0x0324a000	0x04d07000	     27380	r--S       	none          	libicuuc.so.66 mmap area
	10084	0x04d07000	0x04d08000	         4	r--S       	none          	cloned direct area
	10097	0x04fd4000	0x05004000	       192	rw-        	none          	rld heap
	10098	0x05071000	0x050a1000	       192	rw-        	none          	rld heap
	10115	0x05199000	0x052da000	      1284	rw-S       	none          	libswpipe.so mmap area
	10128	0x052f9000	0x052fa000	         4	rw-        	none          	libLLVM-9.so mmap area
	10129	0x0531d000	0x0531e000	         4	rw-        	none          	libLLVM-9.so mmap area
	10130	0x05334000	0x05335000	         4	rw-        	none          	libLLVM-9.so mmap area
	10131	0x05337000	0x05338000	         4	rw-        	none          	libLLVM-9.so mmap area
	10132	0x0533c000	0x0533d000	         4	rw-        	none          	libLLVM-9.so mmap area
	10091	0x05341000	0x05d14000	     10060	r-x        	none          	Software Pipe_seg0ro
	10092	0x05d14000	0x05eef000	      1900	rw-        	none          	Software Pipe_seg1rw
	10093	0x05eef000	0x05f86000	       604	rw-        	none          	Software Pipe_seg2rw
	10094	0x0607c000	0x0a0bf000	     65804	r-x        	none          	libLLVM-9.so_seg0ro
	10095	0x0a0bf000	0x0a430000	      3524	rw-        	none          	libLLVM-9.so_seg1rw
	10096	0x0a430000	0x0a466000	       216	rw-        	none          	libLLVM-9.so_seg2rw
	10133	0x12b95000	0x13595000	     10240	rwx        	none          	libswpipe.so mmap area
	10134	0x13820000	0x13821000	         4	rw-        	none          	libLLVM-9.so mmap area
	10135	0x13bb5000	0x13bb6000	         4	rw-        	none          	libLLVM-9.so mmap area
	10136	0x13d52000	0x13d53000	         4	rw-        	none          	libLLVM-9.so mmap area
	10137	0x14530000	0x14531000	         4	rw-        	none          	libLLVM-9.so mmap area
	10138	0x14bff000	0x14c00000	         4	rw-        	none          	libLLVM-9.so mmap area
	10139	0x14fb4000	0x14fb5000	         4	rw-        	none          	libLLVM-9.so mmap area
	10140	0x15766000	0x15767000	         4	rw-        	none          	libLLVM-9.so mmap area
	10141	0x15bbc000	0x15bbd000	         4	rw-        	none          	libLLVM-9.so mmap area
	10142	0x15fc7000	0x15fc8000	         4	rw-        	none          	libLLVM-9.so mmap area
	10143	0x16399000	0x1639a000	         4	rw-        	none          	libLLVM-9.so mmap area
	10144	0x1651d000	0x1651e000	         4	rw-        	none          	libLLVM-9.so mmap area
	10145	0x1685c000	0x1685d000	         4	rw-        	none          	libLLVM-9.so mmap area
	10146	0x16a66000	0x16a67000	         4	rw-        	none          	libLLVM-9.so mmap area
	10147	0x170e2000	0x170e3000	         4	rw-        	none          	libLLVM-9.so mmap area
	10148	0x17739000	0x1773a000	         4	rw-        	none          	libLLVM-9.so mmap area
	10149	0x17c3b000	0x17c3c000	         4	rw-        	none          	libLLVM-9.so mmap area
	10150	0x18434000	0x18435000	         4	rw-        	none          	libLLVM-9.so mmap area
	10151	0x18452000	0x18453000	         4	rw-        	none          	libLLVM-9.so mmap area
	10152	0x18453000	0x18454000	         4	rw-        	none          	libLLVM-9.so mmap area
	10064	0x18454000	0x1b164000	     46144	rw-        	none          	heap
	10162	0x60670000	0x60a90000	      4224	rw-cS      	none          	server_memory
	10153	0x60b93000	0x60b94000	         4	rw-        	none          	libLLVM-9.so mmap area
	10154	0x60bac000	0x60bad000	         4	rw-        	none          	libLLVM-9.so mmap area
	10155	0x60bb5000	0x60bb6000	         4	rw-        	none          	libLLVM-9.so mmap area
	10156	0x60bb9000	0x60bba000	         4	rw-        	none          	libLLVM-9.so mmap area
	10157	0x60bba000	0x60bbb000	         4	rw-        	none          	libLLVM-9.so mmap area
	10158	0x60bbb000	0x60bbc000	         4	rw-        	none          	libLLVM-9.so mmap area
	10159	0x60bbc000	0x60bbd000	         4	rw-        	none          	libLLVM-9.so mmap area
	9980	0x60bbd000	0x60bc5000	        32	r-xSk      	full          	commpage
	10166	0x60bc5000	0x60fe5000	      4224	rw-cS      	none          	server_memory
	10160	0x6131c000	0x6131d000	         4	rw-        	none          	libLLVM-9.so mmap area
	10169	0x61a82000	0x61a83000	         4	rw-        	none          	libLLVM-9.so mmap area
	10170	0x61c67000	0x61c68000	         4	rw-        	none          	libLLVM-9.so mmap area
	10171	0x61c81000	0x61c82000	         4	rw-        	none          	libLLVM-9.so mmap area
	9977	0x61d0d000	0x61d11000	        16	rw-k       	full          	user area
	10076	0x61d8d000	0x61d8e000	         4	rw-cS      	none          	server_memory
	10069	0x700de000	0x70123000	       276	rw-s       	none          	pthread func_818_stack
	10104	0x70377000	0x703bc000	       276	rw-s       	none          	pthread func_828_stack
	10088	0x70802000	0x70847000	       276	rw-s       	none          	drawing_thread_824_stack
	10173	0x70ed5000	0x70f1a000	       276	rw-s       	none          	pthread func_840_stack
	10110	0x711c8000	0x7120d000	       276	rw-s       	none          	pthread func_831_stack
	10108	0x71225000	0x7126a000	       276	rw-s       	none          	pthread func_830_stack
	10100	0x7126f000	0x712b4000	       276	rw-s       	none          	pthread func_826_stack
	10127	0x71430000	0x71475000	       276	rw-s       	none          	pthread func_837_stack
	9979	0x714c7000	0x724c8000	     16388	rw-s       	none          	lagrange_817_stack
	10112	0x724ef000	0x72534000	       276	rw-s       	none          	pthread func_832_stack
	10106	0x7253b000	0x72580000	       276	rw-s       	none          	pthread func_829_stack
	10114	0x725b2000	0x725f7000	       276	rw-s       	none          	pthread func_833_stack
	10102	0x72609000	0x7264e000	       276	rw-s       	none          	pthread func_827_stack
	10175	0x7265b000	0x726a0000	       276	rw-s       	none          	pthread func_841_stack
	10117	0x726be000	0x72703000	       276	rw-s       	none          	pthread func_834_stack
	10090	0x72708000	0x7274d000	       276	rw-s       	none          	w>Untitled_825_stack
	10071	0x727bf000	0x72804000	       276	rw-s       	none          	pthread func_819_stack
	10080	0x72804000	0x72824000	       128	rw-cS      	none          	server_memory

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	45097	    0	          0	some BBlockCache lock
	45098	    0	        825	token space
	45099	    0	        819	BLooperList lock
	45100	    0	        819	AppServerLink_sLock
	45101	    0	          0	some BLocker
	45102	    0	          0	some BLocker
	45103	    0	          0	Catalog
	45104	    0	          0	LocaleRosterData
	45105	    0	          0	some BLocker
	45106	    0	          0	some BLocker
	45107	    0	          0	BMediaRoster::Roster locker
	45108	    0	          0	port pool
	45109	    0	          0	media theme lock
	45110	    0	          0	add-on manager
	45111	    0	          0	shared buffer list
	45112	    0	          0	media plugin manager
	45113	    0	          0	GameSound device lock
	45114	    0	          0	Catalog
	45122	    0	          0	BMessageQueue Lock
	45123	    0	          0	AppLooperPort
	45135	    0	          0	screen list
	45136	    0	          0	clipboard
	45137	    0	          0	width buffer
	45148	    0	          0	BMessageQueue Lock
	45149	    0	        825	Untitled
	45160	    0	          0	some BLocker
	45167	    0	          0	BGLView draw lock
	45168	    0	          0	BGLView display lock
	45221	    0	          0	info locker
	45344	    0	          0	BMessageQueue Lock
	45345	    0	          0	offscreen bitmap
	45352	    0	          0	BMessageQueue Lock
	45353	    0	          0	offscreen bitmap
	45948	    0	          0	tool tip manager

`

</details>

**Comment by sikmir** [comment]
Could you try with latest lagrange 1.10.1? There is no crash when I'm trying to update feed list.

**Comment by unspacyar** [comment]
Well, there is some improvement:  with 1.10.1 the application don't crash anymore.  However, don't load the feed list.  After hit the "Refresh Feeds" button,  there is the following error in the output (when run Lagrange from Terminal):

440634752:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:

**Comment by unspacyar** [comment]
update: the previous error in the output apparently is related to some certificate error with one of the sites in my feed list. I removed that site from the feeds, and now the error dissapeared.  However, the main issue still persist: the feed list never populate.

**Comment by sikmir** [comment]
Looks promising (FYI @skyjake):
```
                state: Exception (Segment violation)

                Frame           IP                      Function Name
                -----------------------------------------------
                0x7a1c8450      0xbce5db        strlen + 0x2b 
                        Disassembly:
                                strlen:
                                0x00bce5b0:               55  push %ebp
                                0x00bce5b1:             89e5  mov %esp, %ebp
                                0x00bce5b3:               53  push %ebx
                                0x00bce5b4:           8b4d08  mov 0x8(%ebp), %ecx
                                0x00bce5b7:           f6c103  test $0x3, %cl
                                0x00bce5ba:             744c  jz 0xbce608
                                0x00bce5bc:             31c0  xor %eax, %eax
                                0x00bce5be:             eb09  jmp 0xbce5c9
                                0x00bce5c0:               40  inc %eax
                                0x00bce5c1:           8d1401  lea (%ecx,%eax), %edx
                                0x00bce5c4:           f6c203  test $0x3, %dl
                                0x00bce5c7:             7412  jz 0xbce5db
                                0x00bce5c9:         803c0100  cmp $0x0, (%ecx,%eax)
                                0x00bce5cd:             75f1  jnz 0xbce5c0
                                0x00bce5cf:               5b  pop %ebx
                                0x00bce5d0:               5d  pop %ebp
                                0x00bce5d1:               c3  ret 
                                0x00bce5d2:     8db600000000  lea (%esi), %esi
                                0x00bce5d8:           83c204  add $0x4, %edx
                                0x00bce5db:             8b02  mov (%edx), %eax <--

                        Frame memory:
                                [0x7a1c8444]  HU.....z....   48 55 c1 00 d8 ad 1c 7a be a5 ba 00
                0x7a1cadd8      0xbaa5b9        _IO_vfprintf + 0x45a9 
                0x7a1caf08      0xb8e661        vsnprintf + 0x81 
                0x7a1caf38      0x25ebc73       vprintf_Block + 0x23 
                0x7a1caf58      0x25f752e       format_String + 0x1e 
                0x7a1cb058      0x25176bb       fetch_Feeds_ + 0xd1b 
                0x7a1cb078      0x25fb664       run_Threads_ + 0x34 
                0x7a1cb0a0      0xb66c6f        pthread_thread_entry(void*, void*) + 0x1f 
                00000000        0x60cb6250      commpage_thread_exit + 0
```

**Comment by skyjake** [comment]
https://git.skyjake.fi/gemini/lagrange/commit/fa3a2c297b89abe91a25dafed98c3c635613b2dd may help with this.

**Comment by sikmir** [comment]
I still can't reproduce the crash, but I run x86_64 Haiku. @unspacyar could you check with 1.10.3 (#6582)? It includes the fix mentioned above.

**Comment by unspacyar** [comment]
@sikmir I can confirm that after upgrading to version 1.10.3, the feeds list works properly (on 32 bits).

Thank you for your help!
