### ISSUE TITLE
Add Q to HaikuArchives

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#647]
[Q-1.1-src.zip](https://github.com/haikuports/haikuports/files/321732/Q-1.1-src.zip)

Not exactly searchable name, so I don't know if it already hidden away somewhere.

**Comment by waddlesplash** [comment]
No documentation in that archive. Is there any?

**Comment by waddlesplash** [comment]
https://github.com/HaikuArchives/Q
