### ISSUE TITLE
Printing support in Qt applications

### ISSUE THREAD

**Issue by bitigchi** [haikuports/haikuports#6483]
Opening this issue in lieu of ticket [#17488](https://dev.haiku-os.org/ticket/17488#comment:11). Author mentions that printing is not working in LibreOffice and other applications.

**Comment by korli** [comment]
See https://github.com/haikuports/haikuports/issues/3558

**Comment by danboid** [comment]
I'm a strong believer that getting LO working well ie with working printing, would be a major boost for the platform. Its an app that most users want to run on a desktop OS. Its majorly crippled without local printing support.

**Comment by diversys** [comment]
Closing as a dupe of #3558.
