### ISSUE TITLE
Linking against libXaw results in unrunnable applications

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#6489]
e.g. compiling xclock via
```
gcc Clock.c xclock.c -o xclock -I ../BeXlib/include/ -lXt -lX11 -L ../build-BeXlib-Desktop-Debug/lib/ -lXmu -lXaw
```
results in:
```
runtime_loader: Cannot open file libXaw.so.7 (needed by xclock): No such file or directory
```
The installed symlinks to libXaw in `/system/develop/lib` are as follows:
```
lr-xr-xr-x 1 user root 10 Jun  9  2021 /system/develop/lib/libXaw.so -> libXaw7.so
lr-xr-xr-x 1 user root 12 Jun  9  2021 /system/develop/lib/libXaw.so.6 -> libXaw6.so.6
lr-xr-xr-x 1 user root 12 Jun  9  2021 /system/develop/lib/libXaw.so.7 -> libXaw7.so.7
lr-xr-xr-x 1 user root 16 Jun  9  2021 /system/develop/lib/libXaw6.so -> libXaw6.so.6.0.1
lr-xr-xr-x 1 user root 16 Jun  9  2021 /system/develop/lib/libXaw6.so.6 -> libXaw6.so.6.0.1
lr-xr-xr-x 1 user root 26 Jun  9  2021 /system/develop/lib/libXaw6.so.6.0.1 -> ../../lib/libXaw6.so.6.0.1
lr-xr-xr-x 1 user root 16 Jun  9  2021 /system/develop/lib/libXaw7.so -> libXaw7.so.7.0.0
lr-xr-xr-x 1 user root 16 Jun  9  2021 /system/develop/lib/libXaw7.so.7 -> libXaw7.so.7.0.0
lr-xr-xr-x 1 user root 26 Jun  9  2021 /system/develop/lib/libXaw7.so.7.0.0 -> ../../lib/libXaw7.so.7.0.0
```
While in `/system/lib` there is only:
```
lr-xr-xr-x 1 user root     16 Jun  9  2021 /system/lib/libXaw6.so.6 -> libXaw6.so.6.0.1
-r-xr-xr-x 1 user root 369840 Jun  9  2021 /system/lib/libXaw6.so.6.0.1
lr-xr-xr-x 1 user root     16 Jun  9  2021 /system/lib/libXaw7.so.7 -> libXaw7.so.7.0.0
-r-xr-xr-x 1 user root 512400 Jun  9  2021 /system/lib/libXaw7.so.7.0.0
```

This may be a problem with `prepareInstalledDevelLibs` in HaikuPorter.

**Comment by waddlesplash** [comment]
CC @pulkomandy, we were recently having a discussion about this on IRC. What should happen here? I think there should be more symlinks in `/system/lib`, no?

**Comment by waddlesplash** [comment]
Specifically we should still have a `libXaw.so.7` symlink at the very least.

**Comment by waddlesplash** [comment]
Actually, linking against `-lXaw7` instead of `-lXaw` does not seem to make a difference, I get the same exact error...

**Comment by waddlesplash** [comment]
Neither does specifying `/boot/system/lib/libXaw7.so.7`. Maybe there is a broken SONAME, or perhaps runtime_loader is mistaken about `xclock` being the thing that needs `libXaw.so.7`?

**Comment by waddlesplash** [comment]
Ah, no:
```
$ objdump -p /boot/system/lib/libXaw7.so.7 | grep SONAME
  SONAME               libXaw.so.7
```
So, the original set of symlinks is correct, and I'd guess `prepareInstalledDevelLibs` messed things up here.

**Comment by pulkomandy** [comment]
prepareInstalledDevelLibs does not care what links were installed by the previous install steps. What it does is take the list of libraries passed as a parameter, find them in the lib directory, read their soname (the soname is a field inside the elf header), and:

- in system lib dir, rename the library so it matches the soname (this is what the runtime loader will use to find the library at runtime)
- in develop lib dir, create a symlink with the original, non-versioned name (this is what the linker will look for when you use, say -lXaw in your command line)

If your library needs something more complicated than a single filename to use with the linker -l option, and a single soname, prepareInstalledDevelLibs will not be able to figure it out for you. You will need to create your own links (fully replacing it, or in addition to the one it creates)

Note that the way it works in Linux is completely different. The most obvious difference is that the two directories (system and develop) are merged together. The second difference is that linux runtime_loader equivalent does not need the filename to match the soname. Instead, a separate tool (ldconfig) is used to scan all libraries in the directory, and build a database mapping sonames to library names. Their runtime_loader then uses that database. As a result, they don't even need a file with a name matching the soname (they still usually provide one in case you really want to load a file by name: from the linker, or from dlopen for example)

So, I don't think prepareInstalledDevelLibs will "mess things up". It's just that your libraries rely too heavily on how things work in Linux, and something more similar to the Linux way is needed, which means adding more symlinks, and possibly you will need to change sonames in some libraries

**Comment by waddlesplash** [comment]
> What it does is take the list of libraries passed as a parameter, find them in the lib directory, read their soname (the soname is a field inside the elf header), and:

Well, that's strange then, because as you can see, actual SONAME for this library is nowhere to be found in `/system/lib`!
