### ISSUE TITLE
Add EggsControl to HaikuArchives

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#650]
[EggsControl-1.3-src.zip](https://github.com/haikuports/haikuports/files/321748/EggsControl-1.3-src.zip)

The name seems to be a pun on XControl, although I thought only New Zealanders mangle vowels that badly. 

It is duffy-cult to ame-jen that iggs-ecktly. 😁

**Comment by waddlesplash** [comment]
https://github.com/HaikuArchives/EggsControl
