### ISSUE TITLE
gcc  gcc_syslibs_devel doesn't require gcc_syslibs?

### ISSUE THREAD

**Issue by kallisti5** [haikuports/haikuports#6505]
I noticed this working on the bootstrap...

https://github.com/haikuports/haikuports/blob/master/sys-devel/gcc/gcc-11.2.0_2021_07_28.recipe#L125
https://github.com/haikuports/haikuports/blob/master/sys-devel/gcc/gcc-7.3.0_2018_05_01.recipe#L119

vs

https://github.com/haikuports/haikuports.cross/blob/master/sys-devel/gcc_bootstrap/gcc_bootstrap-8.3.0_2021_02_27.recipe#L73

The bootstrap recipies have gcc_syslibs_devel depend on gcc_syslibs... while the normal non-bootstrap versions don't.

The gcc_syslibs_devel package includes symlinks to shared libraries in gcc_syslibs... so i'm pretty sure there should be a dependency here?

**Comment by waddlesplash** [comment]
Yes.

**Comment by Begasus** [comment]
Should be fixed by now?

**Comment by Begasus** [comment]
Pings @nielx
