### ISSUE TITLE
Please upgrade uriparser to 0.9.6 with security fixes 

### ISSUE THREAD

**Issue by hartwork** [haikuports/haikuports#6516]
Hi!

I found a vulnerable copy of uriparser 0.9.5 in here at [`dev-libs/uriparser/uriparser-0.9.5.recipe`](https://github.com/haikuports/haikuports/blob/master/dev-libs/uriparser/uriparser-0.9.5.recipe). uriparser 0.9.6 with security fixes has been released, the [change log](https://github.com/uriparser/uriparser/blob/uriparser-0.9.6/ChangeLog) has more details. Would be awesome if you could update to 0.9.6.  Thank you! :pray:

Best, Sebastian

**Comment by Begasus** [comment]
Thanks for dropping a note here, looking into it :)

**Comment by Begasus** [comment]
Updated in https://github.com/haikuports/haikuports/pull/6517

**Comment by hartwork** [comment]
@Begasus thank you!
