### ISSUE TITLE
mozc does not work with the current protobuf

### ISSUE THREAD

**Issue by Dry-Leaf** [haikuports/haikuports#6538]
mozc does not work on the last 64 bit Haiku release, because of some kind of issue with protobuf.
<img width="516" alt="log" src="https://user-images.githubusercontent.com/96496785/149596280-a4943dad-c4d8-4ce4-9ee0-e03a3e98bc01.png">

**Comment by Begasus** [comment]
One thing you can try for now: **pkgman install protobuf24**
Checking a rebuild with the latest protobuf atm

**Comment by extrowerk** [comment]
Protobuf recipes were revbumped. It should fix the problem, otherwise we will have to revbump mozc too.

**Comment by Begasus** [comment]
@hanya could you look into this, I saw upstream has made updates and your fork is behind there, I don't know how far your "releases" have involved your changes for Haiku but maybe you could rebase there?

**Comment by hanya** [comment]
Needs sometime to rebase haiku port to upstream, I think.

**Comment by Begasus** [comment]
Seems it required the new gcc compiler
**KERN: runtime_loader: /boot/system/lib/libstdc++.so.6.0.25: version "GLIBCXX_3.4.29" not found (required by libprotobuf.so.24)**
Issue seems to be solved with a (system) update according to the forum thread.

**Comment by Begasus** [comment]
> Needs sometime to rebase haiku port to upstream, I think.

I guess, looking at the changes you made, thanks for that hard work! :+1:

**Comment by Begasus** [comment]
For now it seems to work: https://discuss.haiku-os.org/t/solved-unending-pending-after-trying-to-reinstall-mozc/11812
