### ISSUE TITLE
7kaa: duplicate data folder

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#6541]
There seems to be a duplicate of the data folder packaged in 7kaa:

![duplicated_data_dir](https://user-images.githubusercontent.com/6107158/149655844-ca7b7a9a-688b-45e8-9f41-8bfdb53532e8.png)

Maybe @TheZeldakatze  can have another look?

**Comment by Begasus** [comment]
Nice catch! Looking into it also, atleast the problem with curl can be fixed with adding "cmd:pkg_config$secondaryArchSuffix" in BUILD_PREREQUIRES, it also checks for libiconv and libintl (gettext) so might as well add them where needed ...

**Comment by Begasus** [comment]
Even nicer with music :)

**Comment by TheZeldakatze** [comment]
> cmd:pkg_config$secondaryArchSuffix

I somehow managed to copy the data folder twice, because I excpected make to not put it into the correct path and not checking it afterwards. I also found a way to make the game run in window mode, you have to create a config file for that. I'll try to create it automatically with a post install script.

**Comment by Begasus** [comment]
Nice, I'll add a recipe for the music files then ;)

**Comment by Begasus** [comment]
PR created at: https://github.com/haikuports/haikuports/pull/6542
If you want to check it just add **7kaa_music** to REQUIRES (after a local build if it's not merged yet) :)

**Comment by TheZeldakatze** [comment]
> PR created at: #6542
> If you want to check it just add **7kaa_music** to REQUIRES (after a local build if it's not merged yet) :)

I finally figured out how to run the post install scripts. (I constantly installed the wrong package until I noticed that I had changed the revision). Sorry for taking so much time because of that. The PR is #6544 . The game now also runs in windowed mode by default
and requires the music

**Comment by Begasus** [comment]
Fixed in the meantime.
