### ISSUE TITLE
[GTK3] Compiled-in resources broken

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#6546]
There is a hack in the patchset to not assert-exit due to failing to load the image-missing.png icon, which is supposed to be included by default as part of the resources but for some reason is not. Similarly images fail to load in the "Pixbuf" example in `gtk3-demo`. This seems pretty serious.

The old Broadway-based GTK3 "port" had resources working, based on the screenshots: https://discuss.haiku-os.org/t/ported-gtk3-live/7687

**Comment by waddlesplash** [comment]
Here's what happens, specifically:

```
(gtk3-demo:4857): Gtk-WARNING **: 21:52:45.504: Could not find the icon 'window-minimize-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

(gtk3-demo:4857): Gtk-WARNING **: 21:52:45.505: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
```

**Comment by waddlesplash** [comment]
Potentially relevant to all this, from GIMP configure script:
```
  Vector icons:              no (librsvg GdkPixbuf loader missing)
```

**Comment by threedeyes** [comment]
The reason is empty cache file for gdk_pixbuff loaders - I hope it fixed in this commit https://github.com/haikuports/haikuports/commit/ec631eb8bf516540b5216befd619ec0e4f5681cc. Everything works for me
![2022-01-19_22-51](https://user-images.githubusercontent.com/2559260/150134008-1d19f620-b197-4a80-b2bf-8425dd91a5f5.png)
.

**Comment by threedeyes** [comment]
And yes, in order for the icons to work, we needpackaged the Adwaita iconpack

**Comment by waddlesplash** [comment]
Why not enable SVG icons in GDK-Pixbuf and then use the Haiku SVG Icon pack?

**Comment by threedeyes** [comment]
I don't really understand what you mean. GDK-Pixbuf is an equivalent of TranslatorKit.

**Comment by waddlesplash** [comment]
Yes, I mean we should compile GDK-Pixbuf with librsvg, so it has support for loading SVGs, and then patch GTK3 to use the Haiku SVG icon theme.

**Comment by threedeyes** [comment]
The gdk-pixbuff doesn't support svg at all.

**Comment by threedeyes** [comment]
https://github.com/haikuports/haikuports/blob/master/gnome-base/librsvg/librsvg-2.50.3.recipe#L111

**Comment by threedeyes** [comment]
Haiku SVG icon theme works

![2022-01-20_12-24](https://user-images.githubusercontent.com/2559260/150260889-90bb2563-c623-4c27-bb5d-ac6037c3fa94.png)

![2022-01-20_12-23](https://user-images.githubusercontent.com/2559260/150260883-0afe4a36-ac5e-40c7-94ba-83882d9b030b.png)
