### ISSUE TITLE
GIMP

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#6547]
We need a number of dependencies first:

 * [x] babl
 * [x] gegl
 * etc...

**Comment by waddlesplash** [comment]
Perhaps @extrowerk or @Begasus can work on this one, now that there is a functioning GTK3 recipe? I added a template GIMP recipe in 10ad62ea9af76ab6527edf02fd452eed00613c4a.

**Comment by extrowerk** [comment]
I can definetely spend some hours with this at the upcoming weekend, maybe earlier.

**Comment by threedeyes** [comment]
I already have working recipes for these libraries

**Comment by extrowerk** [comment]
> I already have working recipes for these libraries

I am always late of the show. Thanks!

**Comment by threedeyes** [comment]
I made them a long time ago, I just did not publish them for lack of use

**Comment by threedeyes** [comment]
babl, gegl, gexiv2 - done
i have appstream_glib recipe also, but it requered some broken libs (xinerama for example) for build

**Comment by waddlesplash** [comment]
There really is no way to build appstream_glib without Xinerama? I can patch it, if so. Submit the recipe anyway even if it's disabled and I can take a look.

**Comment by waddlesplash** [comment]
Anyone working on GIMP itself, then? If nobody else does, I can next week.

**Comment by extrowerk** [comment]
> Anyone working on GIMP itself, then? If nobody else does, I can next week.

I can look into it. But each and every gtk sample program/ hello world crashes here on my side. Have to recheck.

**Comment by waddlesplash** [comment]
Not even the ones included with the package? That may be due to some misconfiguration. Make sure you upgrade gdk_pixbuf to the latest version in case it isn't. Upload a crash report and I'll take a look. (Make sure you don't have libX11 installed but `xlibe` instead.)

**Comment by waddlesplash** [comment]
The crashes may be fixed by https://github.com/haikuports/haikuports/commit/f366bf6118862812c481cd11227c95e1c15ffb52.

**Comment by Begasus** [comment]
gegl needs to be fixed (as mentioned) but json_glib also (for secondary architecture on 32bit)

**Comment by Begasus** [comment]
PR for appstream_glib and gtk3 have been filed, build for GIMP succeeds on 32bit but fails to launch:

```
~> GIMP 
libX11: unhandled Property: _NET_WM_PID<XA_CARDINAL>
libX11: unhandled Property: WM_CLIENT_LEADER<XA_WINDOW>
libX11: unhandled Property: _NET_WM_PID<XA_CARDINAL>
Cannot spawn a message bus when setuid
This is a development version of GIMP.  Debug messages may appear here.

Application icon missing: /packages/gimp_x86-2.99.8-1/.self/data/icons/hicolor/16x16/apps/gimp.png (Openen van bestand ‘/packages/gimp_x86-2.99.8-1/.self/data/icons/hicolor/16x16/apps/gimp.png’ mislukt: No such file or directory)
Application icon missing: /packages/gimp_x86-2.99.8-1/.self/data/icons/hicolor/32x32/apps/gimp.png (Openen van bestand ‘/packages/gimp_x86-2.99.8-1/.self/data/icons/hicolor/32x32/apps/gimp.png’ mislukt: No such file or directory)
Application icon missing: /packages/gimp_x86-2.99.8-1/.self/data/icons/hicolor/48x48/apps/gimp.png (Openen van bestand ‘/packages/gimp_x86-2.99.8-1/.self/data/icons/hicolor/48x48/apps/gimp.png’ mislukt: No such file or directory)
Application icon missing: /packages/gimp_x86-2.99.8-1/.self/data/icons/hicolor/64x64/apps/gimp.png (Openen van bestand ‘/packages/gimp_x86-2.99.8-1/.self/data/icons/hicolor/64x64/apps/gimp.png’ mislukt: No such file or directory)
Application icon missing: /packages/gimp_x86-2.99.8-1/.self/data/icons/hicolor/scalable/apps/gimp.svg (Openen van bestand ‘/packages/gimp_x86-2.99.8-1/.self/data/icons/hicolor/scalable/apps/gimp.svg’ mislukt: No such file or directory)
Application icon missing: /packages/gimp_x86-2.99.8-1/.self/data/icons/hicolor/256x256/apps/gimp.png
libX11: client requested non-existent Atom '_NET_WORKAREA'
GIMP: fatal error: Segmentation violation
GIMP: terminated: Interrupt
```

From syslog:
```
KERN: vm_page_fault: vm_soft_fault returned error 'Bad address' on fault at 0x4e013704, ip 0x2003436, write 1, user 1, thread 0x7b20e
KERN: vm_soft_fault: va 0x4e013000 not covered by area in address space
KERN: vm_page_fault: vm_soft_fault returned error 'Bad address' on fault at 0x4e013704, ip 0x2003436, write 1, user 1, thread 0x7b20e
KERN: vm_soft_fault: va 0x4e013000 not covered by area in address space
KERN: vm_page_fault: vm_soft_fault returned error 'Bad address' on fault at 0x4e013704, ip 0x2003436, write 1, user 1, thread 0x7b20e
KERN: vm_soft_fault: va 0x4e013000 not covered by area in address space
KERN: vm_page_fault: vm_soft_fault returned error 'Bad address' on fault at 0x4e013704, ip 0x2003436, write 1, user 1, thread 0x7b20e
KERN: vm_soft_fault: va 0x4e013000 not covered by area in address space
KERN: vm_page_fault: vm_soft_fault returned error 'Bad address' on fault at 0x4e013704, ip 0x2003436, write 1, user 1, thread 0x7b20e
KERN: vm_soft_fault: va 0x4e013000 not covered by area in address space
KERN: vm_page_fault: vm_soft_fault returned error 'Bad address' on fault at 0x4e013704, ip 0x2003436, write 1, user 1, thread 0x7b20e
```

**Comment by kenmays** [comment]
GIMP x86 launch: uuid_unparse - Missing symbol

**Comment by Begasus** [comment]
Seems to be a R1B3 vs nightly issue, checked on a "clean" 64bit installs for both, on the R1B3 it fails to launch (same messages as above), on the nightly it launches OK. (Haven't checked a 32bit build on nightly (yet))

**Comment by extrowerk** [comment]
> GIMP 2.99.8-2 x86 launch: uuid_unparse - Missing symbol
> 
> * x86/uuid/uuid.h - uuid_unparse defined.

Uuid lib is available in2 different package, maybe it needs the other one?

**Comment by Begasus** [comment]
Just fired up a build for GIMP here and I saw it's using libuuid (not util_linux) so that version should be ok, will report back later (on 32bit)

**Comment by Begasus** [comment]
Looks related to appstream_glib?
```
~> GIMP 
runtime_loader: /boot/system/lib/x86/libuuid.so.1.3.0: No version information available (required by /boot/system/lib/x86/libappstream-glib.so.8.0.10)
runtime_loader: /boot/system/lib/x86/libappstream-glib.so.8.0.10: Could not resolve symbol 'uuid_unparse'
resolve symbol "uuid_unparse" returned: -2147478780
runtime_loader: /boot/system/lib/x86/libappstream-glib.so.8.0.10: Troubles relocating: Symbol not found
```

**Comment by Begasus** [comment]
I think this one can be closed?
