### ISSUE TITLE
simutrans crashes on start

### ISSUE THREAD

**Issue by TheZeldakatze** [haikuports/haikuports#6556]
Simutrans crashes after loading. There is a segment Violation in money_to_string (utils/simstring.cc). But I don't understand what exactly is wrong there. Modifying the funtction makes simutrans load up and show  the menu/game, but it crashes when opening the finance screen

**Comment by korli** [comment]
Please attach the crash report.

**Comment by kenmays** [comment]
Seems to still work after loading on Haiku hrev55795 x64. Rebuild works too. Finances screen (years/month) working from menu.
Any specific steps?

**Comment by TheZeldakatze** [comment]
[simutrans-758-debug-01-09-2009-00-20-31.report.txt](https://github.com/haikuports/haikuports/files/7936478/simutrans-758-debug-01-09-2009-00-20-31.report.txt)
> Please attach the crash report.

(Added an .txt suffix to upload it to github)
I'm using a development build (hrev55792), the language is set to german

**Comment by TheZeldakatze** [comment]
Still crases on 123.0

**Comment by kenmays** [comment]
1. pkgman full-sync

Is the installed within a virtual machine or physical hardware?

**Comment by TheZeldakatze** [comment]
> Is it installed within a virtual machine or on physical hardware?
> Seems to lstartup and work OK on my end.

The report comes from a physical machine (Dell Optiplex 780), but it crashed in the same way in a virtual machine. I could compress the virtual machine's disk image and send it if that would help

**Comment by korli** [comment]
Looks like a crash in memcpy in money_to_string at https://github.com/aburch/simutrans/blob/d77d7bf8ecad83ee24660c75a18e2c2ba21f6d2c/gui/simwin.cc#L1960
The buffer is on the stack. Can you check in the syslog? the same stack trace should tell if the segment violation is a read or a write.

**Comment by TheZeldakatze** [comment]
looks like a write segment violation 
[syslog.txt](https://github.com/haikuports/haikuports/files/7942814/syslog.txt)
[simutrans-1444-debug-26-01-2022-15-07-32.report.txt](https://github.com/haikuports/haikuports/files/7942817/simutrans-1444-debug-26-01-2022-15-07-32.report.txt)

**Comment by TheZeldakatze** [comment]
> Recompile/Retest with the newer patchset. What Simutrans graphics pack are you loading?
> 
> .

Still crashes. I've both tried pak64 (123.0) and pak128 (2.8.1)
Under pak64, the game once froze on the loading screen, but ususally crashes

**Comment by TheZeldakatze** [comment]
It's the language. With english set as the main language and german formatting the game runs. Setting german to be the only language in the settings and leaving the locale as english also crashes the game.

**Comment by kenmays** [comment]
Thanks! I'll let the devs know to fix upstream.

**Comment by kenmays** [comment]
All patched up. You can close this ticket.
