### ISSUE TITLE
cdrecord: may cause GPE/KDL when cloning or reading CD/DVD/BD media

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#6561]
Haiku hrev55795 x64 w/cdrecord 3.02a9 and w/BurnItNow 1.2.1-1 using internal DVD writer unit.

1. BurnItNow - clone to a file gave GPE/KD when cloning a professionally-created DVD (non-copyprotected).
- readcd -clone (from SCSI unit to /dev/null, this passes in CLI, (tested with CD-R)
- readcd -c2scan (seems OK, but gave GPE/KDL with certain optical media (possible disc erors)

![cdrecord_readcd_kdl](https://user-images.githubusercontent.com/5168719/150842791-46a6f29b-dc9c-4464-b032-99aead9827d1.gif)

**Comment by waddlesplash** [comment]
KDLs should always be reported to the main Haiku bug tracker.
