### ISSUE TITLE
libpoppler_x86 conflict version

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#6602]
When trying to do a system upgrade (pkgman full-sync), we got this error message:

`
problem 1: package libreoffice_x86-6.4.7.2-6 requires lib:libpoppler_x86>=104.0.0, but none of the providers can be installed
  solution 1:
    - keep poppler_x86-20.11.0-3 from excluded repository
    - keep poppler_x86_devel-20.11.0-3 from excluded repository
    - keep poppler_x86_qt5-20.11.0-3 from excluded repository
    - keep booksorg_x86-0.3-4 from excluded repository
    - keep qpdfview_x86-0.4.18-5 from excluded repository
    - keep poppler_x86_glib-20.11.0-3 from excluded repository
  solution 2:
    - allow deinstallation of libreoffice_x86-6.4.7.2-6
`

I'm using Haiku 32 bit version (hrev 55840 - nightly)

**Comment by bbjimmy** [comment]
I have a similar problem on x86_64 but in this case /boot/system/packages/poppler-22.01.0-1-x86_64.hpkg is installed and libreoffice is looking for poppler-20.11.0-3-x86_64.hpkg I installed libreoffice and the popler package in ~/config/packages and it works even with the other popler package in /boot/system/packages.

**Comment by Begasus** [comment]
My bad, failing revbump is mentioned in: https://github.com/haikuports/haikuports/pull/6512
For 32bit it seems to be some gcc11 thing, for 64bit it seems related to bison, don't have the time to look into it atm, but it's reported on the merge for poppler, thanks for pointing this with a new issue, if someone has the time and means it would be nice if they could check out the mentioned solutions.

**Comment by kenmays** [comment]
Workaround:

Updated to Haiku R1B3+63 (current):
1. 'pkgman full-sync' from R1B3 clean install
2. Keep 'poppler_x86*' packages (don't update them yet). 

Note: Otherwise, revert to old snapshot to regain previous statel.

This will keep LO 6.4.7.2-6 and Scribus 1.5.7-3 functional on x86 for now.

**Comment by halian** [comment]
@kenmays This does not seem to work in my fresh R1B3 x64 installation, with OP's issue occurring right off the hop.

**Comment by augiedoggie** [comment]
> Update: You can update to the newer poppler packages on x86.

The gegl package needs to be fixed and rebuilt.  It might prevent an update if someone has the old version installed for GIMP.  The recipe needs some "requires" adjustments due to the changes in cairo.
