### ISSUE TITLE
libreoffice: 6.4.7.2-7 build fails on x86

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#6607]
Tested on Haiku R1B3 (+63) x86:
[libreoffice_bug-2.txt](https://github.com/haikuports/haikuports/files/8034798/libreoffice_bug-2.txt)

**Comment by Begasus** [comment]
As mentioned in the PR for poppler, this could be related to gcc11, maybe a small fix but haven't been able to check it out: https://github.com/haikuports/haikuports/pull/6512 (the fix for 64bit has already been applied)

**Comment by augiedoggie** [comment]
I see similar reports to this problem.  Looks like the "patch" could be really simple.  Perhaps one of these is helpful ...

https://cgit.freedesktop.org/libreoffice/core/commit/?id=1f3dddd6f21d91c429190ae314dadeec409f35f4

or possibly the suse fix

https://bugzilla.suse.com/show_bug.cgi?id=1186110#c5

**Comment by kenmays** [comment]
Bug resolved. Seems good for now.

**Comment by Begasus** [comment]
Rebuilding atm with the "fix" mentioned in the poppler PR for 32bit, it will take some time but if successful I'll file a PR for that

**Comment by kenmays** [comment]
Build completed.
