### ISSUE TITLE
Add a recipe for MP3Gain

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#661]
http://mp3gain.sourceforge.net

Old BeOS port: 
[MP3GainBeOS-1.3.1_src-incl.zip](https://github.com/haikuports/haikuports/files/322286/MP3GainBeOS-1.3.1_src-incl.zip)

Interesting to see who the original porters were for this one. 😉

**Comment by mmuman** [comment]
I have no idea who that can be 😄

**Comment by richienyhus** [comment]
Fixed in #2123
