### ISSUE TITLE
icebreaker: Sound not working

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#662]
There's no sound, only a crack of the speaker on launch.

**Comment by Begasus** [comment]
Could you check? I checked here and I got sound, revbumped the recipe with some small changes just now

**Comment by davidkaroly** [comment]
I checked on icebreaker-2.2.1 in VirtualBox, getting sound as expected.

**Comment by Begasus** [comment]
Thanks for checking also, closing as solved :)
