### ISSUE TITLE
Port Kalendar

### ISSUE THREAD

**Issue by extrowerk** [haikuports/haikuports#6624]
Kalendar is a calendar application that allows you to manage your tasks and events. Kalendar supports both local calendars as well as a multitude of online calendars: Nextcloud, Google® Calendar, Outlook®, Caldav, and many more.

https://apps.kde.org/kalendar/

**Comment by Begasus** [comment]
Could be done, but events or tasks aren't created/saved (no patches involved so far).

![Kalendar](https://github.com/haikuports/haikuports/assets/16057090/446cac50-2980-4e67-9f39-06f83c5d91a7)

**Comment by Begasus** [comment]
Kalendar has now been integrated into Merkuro afaict, thus making this obsolete.
Porting Merkuro isn't feasable. :)

![Merkuro](https://github.com/haikuports/haikuports/assets/16057090/7c78d21d-1498-4c3a-9c3d-4923e2b45390)
