### ISSUE TITLE
Please update vulnerable Expat to 2.4.5

### ISSUE THREAD

**Issue by hartwork** [haikuports/haikuports#6640]
Hi!

[libexpat 2.4.5](https://github.com/libexpat/libexpat/releases/tag/R_2_4_5) with **security fixes** has been released, the upstream [change log](https://github.com/libexpat/libexpat/blob/R_2_4_5/expat/Changes) has more details.

Thanks for updating! :pray: 

Best, Sebastian

**Comment by korli** [comment]
Done in 5212f28802a32b595c38e05c6aef07b98bfba744
