### ISSUE TITLE
port htop

### ISSUE THREAD

**Issue by 1o1o1** [haikuports/haikuports#6641]
don't work  :(

![Снимок экрана 2022-02-19 в 21 26 28](https://user-images.githubusercontent.com/46845416/154816080-a2b2f4be-d008-47c5-b46d-4faf954d978e.png)

**Comment by extrowerk** [comment]
For reference: https://github.com/haikuports/haikuports/tree/master/sys-process/htop

**Comment by 1o1o1** [comment]
can you build for update in pkgman ??

**Comment by extrowerk** [comment]
> can you build for update in pkgman ??

It is marked as untested.

**Comment by extrowerk** [comment]
Duplicate of https://github.com/haikuports/haikuports/issues/1655
