### ISSUE TITLE
Please update Expat to 2.4.6 with a regression fix

### ISSUE THREAD

**Issue by hartwork** [haikuports/haikuports#6645]
Hi!

[libexpat 2.4.6](https://github.com/libexpat/libexpat/releases/tag/R_2_4_6) with a regression fix has been released, the upstream [change log](https://github.com/libexpat/libexpat/blob/R_2_4_6/expat/Changes) has more details.

Thanks for updating! :pray: 

Best, Sebastian

**Comment by korli** [comment]
cf2d695bb4ee9c5cf15a4821a64e5bd0edb95b4e
