### ISSUE TITLE
Build failures on buildmaster

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#6686]
Maybe list them here also so they are more visible to others?

**Comment by Begasus** [comment]
32bit:

- [ ] musicpc: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2413/builds/77507.log
- [ ] npm: Missing packages 1 nodejs14_x86-14.18.1
- [ ] qmplay2: resolving build dependencies failed: build-requires "devel:libavcodec_x86 >= 59" of package "qmplay2_x86-21.12.24" could not be resolved
- [ ] php8: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2429/builds/77535.log
- [ ] libtasn1: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2431/builds/77546.log
- [ ] scribus: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2441/builds/77582.log
- [ ] ceres_solver: resolving build dependencies failed: requires "lib:libamd" of package "ceres_solver-2.0.1~git" could not be resolved
- [ ] sshfs_fuse: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2460/builds/77610.log
- [ ] kdoctools: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2466/builds/77627.log
- [ ] dragengine: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/2471/builds/77632.log

**Comment by Begasus** [comment]
64bit:

- [ ] pdftranslator: https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/6704/builds/76775.log
- [ ] musicpc: https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/6726/builds/76802.log
- [ ] chafa: https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/6764/builds/76878.log
- [ ] bghostview: https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/6772/builds/76889.log
- [ ] dragengine: https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/6784/builds/76910.log

**Comment by Begasus** [comment]
@korli nodejs16 isn't enabled for secondary architecture, any specific reason for that?

**Comment by korli** [comment]
> @korli nodejs16 isn't enabled for secondary architecture, any specific reason for that? **EDIT** build failed locally with: invalid conversion (v8 related)

nodejs probably needs some porting on x86.

**Comment by waddlesplash** [comment]
Should we keep this open, or don't bother?

**Comment by Begasus** [comment]
Closing (forgot about it), people should follow up on a merge, and we can still check and report if needed.
