### ISSUE TITLE
Qmplay2 - video freeze on full screen mode (FFMpeg issue?)

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#6706]
Hello. I think this issue is related to the last update from Qmplay2 that happened recently.  If I open a video from my hard disk, or play a youtube link and switch to full screen mode, the video stops (and the music keeps playing).  If I get out of full screen mode, the video play resumes normally.   

I'm using Haiku 32 bit (hrev55929).

Qmplay2 version: 21-12-24-3
FFMpeg: 4.2.2-9
FFMpeg5: 5.0-1

**Comment by kenmays** [comment]
Tested QMPlay2 22.03.19 on hrev56350 x64 w/full screen mode. Video/audio seems fine with various Youtube videos while switching to/from full screen mode.

**Comment by unspacyar** [comment]
Hi. I confirm that the issue with the full screen mode is fixed after updating to the last version of QMPlay2 (22.08.21).  Thank you!
