### ISSUE TITLE
VVVVVV: No longer starting on nightlies

### ISSUE THREAD

**Issue by win8linux** [haikuports/haikuports#6738]
While attempting to update the *VVVVVV* package to 2.3.6 from 2.3.1, the game doesn't display a window when run anymore. Nothing appears in the terminal nor in Debugger, though I am not experienced with using the latter. Initially suspecting a breakage between 2.2.1 and 2.2.6, I tested every stable version in between with the same results. Then i tried running the game from the version in HaikuDepot, to no avail. It means that the issue could be elsewhere, possibly in the deps or in Haiku itself.

Should be noted that this was on `x86_64`. `x86` uses 2.0 instead, the last known version of *VVVVVV* to work on that architecture.

**Comment by waddlesplash** [comment]
Does it use SDL? Likely the SDL upgrades somehow broke it, I suppose.

**Comment by win8linux** [comment]
It does indeed use SDL.

**Comment by augiedoggie** [comment]
VVVVVV was updated to 2.3.6 in #7379. The game ran fine for me on both x86_64 and x86.  Can you check and see if the problems are fixed for you?

**Comment by win8linux** [comment]
No sorry, there is still no window displayed.

**Comment by win8linux** [comment]
Did another round of tests on `x86` and `x86_64` inside VMs and bare metal machines with nightlies and the Beta 4 Test Candidate 0 images, without success.  Would rather not have this broken game showing up for anyone checking out beta 4, so it will be disabled in HaikuPorts.

For now, this issue will remain open in the event that a solution is found soon enough. I may close it sometime post-B4, however.

**Comment by Begasus** [comment]
@augiedoggie if this still works for you (I haven't checked) please re-enable the recipe for the architecture you are running it on?

**Comment by win8linux** [comment]
After beta 4 is out, I will attempt to update *VVVVVV* to the current upstream version. If it starts working again after undergoing a similar round of tests by then, I will push updated recipes. If not, then this issue will be updated accordingly and discussions can proceed from there.

**Comment by kquote03** [comment]
I think the package should be re-enabled, because it works fine for me 🤷‍♂️ 

Tested on a T480 (the huawei died) on latest hrev, only modification for recipes was enabling x86_64 and changing the hash for vvvvvv_data. 

Maybe we need to contact the maintainer before immediately disabling ??? (spitballing here)

![vvvvvv works](https://user-images.githubusercontent.com/37013292/205433478-6b2fc152-f947-47b2-8449-c0d8606bb867.png)

**Comment by win8linux** [comment]
I'll enable the package about a week after beta 4 releases at the earliest, when most of the coverage is out. Will still sync it with upstream and see if the startup issues are sorted out here.

**Comment by kquote03** [comment]
I mean, it would be certianly cool if it's possible to make VVVVVV work at the time beta4 is out since it is a really great game and it would bring at least a bit of positive press but I'm not that familiar with the haikuports pipeline or the crashing issue, so I am way out of my depth and it really isnt my call :P

**Comment by win8linux** [comment]
I ***really*** like the game too, but it has been consistently failing to show a window on my machines and VMs for months now on the nightlies. There are also conflicting reports of it working and not working on others' computers. The package was disabled, since the beta is coming and it would not be a good look to have any potentially problematic featured packages in HaikuDepot.

> Maybe we need to contact the maintainer before immediately disabling ??? (spitballing here)

Considering that the game data [license exemption](https://github.com/TerryCavanagh/VVVVVV/blob/master/License%20exceptions.md) that allows it to be freely redistributed on HaikuPorts is in my name, guess I'm that maintainer.

**Comment by kquote03** [comment]
ah that explains alot, thank you

**Comment by waddlesplash** [comment]
It's a beta release, there will be things that don't work. We should re-enable the recipe anyway.

So far the only thing anyone has said is "it doesn't open", which is not descriptive at all of what the problem might be. Did you determine when it stopped working? Did you try running it from Terminal to see what error messages it might show?

**Comment by kquote03** [comment]
@win8linux Can you document your tests (or link to the place where you documented them if you already did so)?, like hardware have you tried, VM software, etc? 

I realize that disabling the package from haiku depot is not even that big of a deal as trying to actually make it work again.

I tried it today on a KVM (er) VM, and it worked just fine. I applied the same steps as the t480 (basically nothing, just stuff to make haikuporter not scream at me)

![image](https://user-images.githubusercontent.com/37013292/205723592-084a6973-a738-41d7-b54c-3def9ef5e9dc.png)

Here's also the virsh XML (to see the specs I have in the VM, it's the standard one that virt-manaer uses for Haiku)
https://pastebin.ubuntu.com/p/sS8CP6FZv2/

**Comment by win8linux** [comment]
> @win8linux Can you document your tests (or link to the place where you documented them if you already did so)?, like hardware have you tried, VM software, etc? 
> 
> I realize that disabling the package from haiku depot is not even that big of a deal as trying to actually make it work again.
> 
> I tried it today on a KVM (er) VM, and it worked just fine. I applied the same steps as the t480 (basically nothing, just stuff to make haikuporter not scream at me)
> 
> ![image](https://user-images.githubusercontent.com/37013292/205723592-084a6973-a738-41d7-b54c-3def9ef5e9dc.png)
> 
> Here's also the virsh XML (to see the specs I have in the VM, it's the standard one that virt-manaer uses for Haiku)
> https://pastebin.ubuntu.com/p/sS8CP6FZv2/ 
> 
> Edit# I have tried Virtio (both with 3d accel and not), VGA and QXL, all seem to work. 

The testing was done in VirtualBox VMs and bare metal hardware.

VBox VM specifications

* 3 CPU cores
* 128 MB video memory (max)
* 4 GB RAM
* 1080p resolution

Bare metal hardware

Netbook:
* AMD Athlon Neo II Dual-Core
* ATI Radeon HD 4200
* 2 GB RAM
* 1366 × 720 resolution

Desktop:
* AMD Ryzen 5 2600 (6C/12T)
* AMD Radeon RX 5700 XT
* 32 GB RAM
* 1080p resolution

**Comment by kquote03** [comment]
I just tried Virtualbox with stock settings and it works as well 
![image](https://user-images.githubusercontent.com/37013292/205731494-c2e4ed3c-2476-4229-926f-a2bf3643a6fc.png)

I will test it also on an old sony vaio (it has an amd gpu as well)

**Comment by win8linux** [comment]
Have you tried with also using the other graphics adapters in VBox? I can't get to my VBox VMs right now, but some of them do use the others besides the default one.

**Comment by kquote03** [comment]
@win8linux 

Previous test was done on VMSVGA
<details>
<summary>VBoxVGA no 3D (Works) </summary>

![image](https://user-images.githubusercontent.com/37013292/205733775-54536941-bb4c-4c13-9ac3-aecff1b4ef7f.png)

</details>

<details>
<summary>VBoxSVGA no 3D (Works)</summary>

![image](https://user-images.githubusercontent.com/37013292/205734080-1802067c-19a7-4b56-b1e2-45970a9d43bb.png)

</details>

When enabling 3D it just reverts to VMSVGA automatically

**Comment by kquote03** [comment]
> Not really sure if the GPU actually matters for bare metal without GPU drivers but just in case it's relevant, does your netbook use a GPU from the same generation as mine (TeraScale 1)?

Sadly it's an Evergreen PALM (HD 6310)... the thing isn't even properly supported on Windows :P

**Comment by waddlesplash** [comment]
It built and ran just fine here so I re-enabled it in https://github.com/haikuports/haikuports/commit/06a81c636e17c0e4e2e5c49e1e6e3c641edcd7c6. We can investigate it not working on whatever systems it doesn't.

**Comment by win8linux** [comment]
Still cannot get a window going on `hrev56350` in a VM (VBox), will try again after updating:`
![Screenshot_20221207_162719](https://user-images.githubusercontent.com/11584387/206127246-be40e9aa-3779-4c13-b294-4feabb241051.png)

**Comment by korli** [comment]
Try with the kernel debugger. It will show which mutex the SDLApplication thread wait on. Then you can check the current owner of the mutex. Looks like the runtime loader [lock](https://github.com/haiku/haiku/blob/8f16317a5b6db5c672f331814273e5857555020f/src/system/runtime_loader/elf.cpp#L617)

**Comment by win8linux** [comment]
Ok, then. Haven't used KDL for actual debugging yet, but this seems like a good time to learn.

> EDIT: it seems the interface kit tries to load a control look addon.

Huh, it gets a bit further when using the default ControlLook (instead of Flat) but still no window.

**Comment by korli** [comment]
If you can reproduce the issue by installing the flat ControlLook again, then please report the issue at the Haiku bug tracker. 
You can generate a report:
Debugger --team xxx --save-report

**Comment by augiedoggie** [comment]
Issue is with Haiku decorator code and not the game.

**Comment by korli** [comment]
Is there a bug report at the Haiku bug tracker then?

**Comment by augiedoggie** [comment]
> Is there a bug report at the Haiku bug tracker then?

Not that I've seen.  I don't have the flat decorator installed to see if it's still broken.
