### ISSUE TITLE
Native file dialogs in Qt accept folders when only files should be accepted

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#6749]
e.g. in Qt Creator "Open File": Pressing "enter" on directories opens them (only for Qt Creator to give an error) instead of navigating into the folder.

**Comment by threedeyes** [comment]
Does double-clicking open folders?

**Comment by threedeyes** [comment]
I specified an extra node_flavor (B_DIRECTORY_NODE) for the default open dialog - https://github.com/threedeyes/qthaikuplugins/blob/master/platforms/qhaikuplatform/haiku/qhaikuplatformdialoghelpers.h#L166
I will publish a new release with this fix in the next few days.

**Comment by threedeyes** [comment]
Fixed in https://github.com/haikuports/haikuports/commit/97d4dbe8a1ac4d81f05ede5793ab3c1ca6da7b90
