### ISSUE TITLE
Port Borg Backup

### ISSUE THREAD

**Issue by mmuman** [haikuports/haikuports#6777]
Some hints [there](https://github.com/borgbackup/borg/issues/4117).

**Comment by Begasus** [comment]
Not sure how it's used (or even if it's usable), but it can be done :) (just need some time to write the recipe) :)

![borg](https://user-images.githubusercontent.com/16057090/160294265-8e013613-69e2-4d87-9740-f2a726eda268.png)

**Comment by Begasus** [comment]
At least for this pip needs to be fixed: https://github.com/haikuports/haikuports/pull/6714#discussion_r835930770

**Comment by Begasus** [comment]
Most of the dependencies have been updated/added in the last day, for both branches all is there to do a build in Terminal and install, master branch has an extra dependency which I can't seem to resolve: argon2-cffi, wip work has been uploaded to: https://github.com/Begasus/haikuports/commit/f963f30e5ecdb79b7edead397ead156b3478327b

**Comment by Begasus** [comment]
Closing this one, PR created (checked build on 32bit and 64bit) here: https://github.com/haikuports/haikuports/pull/6921
A first basic instruction seems to working fine. @mmuman could you have a look?
