### ISSUE TITLE
clang always uses old gcc 2.9.5 linker, wrong default includes

### ISSUE THREAD

**Issue by Alexco500** [haikuports/haikuports#678]
It seems to me that clang always uses the old linker. Regardless of architecture setting it refers always to the old linker:
`
~> setarch x86

Switching to architecture x86

~> clang -Xlinker -v
collect2 version 2.95.3-haiku-2014_07_26 (i386 Haiku/ELF)
/packages/gcc-2.95.3_2014_10_14-3/.self/develop/tools/i586-pc-haiku/bin/ld -m elf_i386_haiku 
-shared -Bsymbolic --no-undefined -o a.out /boot/system/develop/lib/crti.o 
/packages/gcc-2.95.3_2014_10_14-3/.self/develop/tools/lib/gcc-lib/i586-pc-haiku/2.95.3-haiku-2014_07_26/crtbeginS.o
 /boot/system/develop/lib/start_dyn.o /boot/system/develop/lib/init_term_dyn.o 
 -L/packages/gcc-2.95.3_2014_10_14-3/.self/develop/tools/lib/gcc-lib/i586-pc-haiku/2.95.3-haiku-2014_07_26 
 -L/packages/gcc-2.95.3_2014_10_14-3/.self/develop/tools/i586-pc-haiku/lib 
 -L/packages/gcc-2.95.3_2014_10_14-3/.self/develop/tools/lib -L/boot/system/develop/lib 
 -v -lroot /packages/gcc-2.95.3_2014_10_14-3/.self/develop/tools/lib/gcc-lib/i586-pc-haiku/2.95.3-haiku-2014_07_26/crtendS.o 
 /boot/system/develop/lib/crtn.o
/boot/system/develop/lib/start_dyn.o: In function `_start':
start_dyn.c:(.text+0x57): undefined reference to `main'
GNU ld version 2.17-haiku-2013_04_21
collect2: ld returned 1 exit status
clang-3.8: error: linker (via gcc) command failed with exit code 1 (use -v to see invocation) 
`
Also the default include path of clang is completely different than those of gcc 5.4. So at the moment clang can't be used as direct replacement for gcc.

Clang default includes:
`
~/Desktop> clang++ -E -xc++ - -v </dev/null  >clang.txt
clang version 3.8.0 (tags/RELEASE_380/final)
Target: i586-pc-haiku
Thread model: posix
InstalledDir: /bin
 "/boot/system/bin/clang-3.8" -cc1 -triple i586-pc-haiku -E -disable-free -disable-llvm-verifier -main-file-name - -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -target-cpu i586 -v -dwarf-column-info -debugger-tuning=gdb -resource-dir /boot/system/bin/../lib/clang/3.8.0 -internal-isystem /system/develop/headers/c++ -internal-isystem /system/develop/headers/c++/backward -internal-isystem /system/develop/headers/c++/i586-pc-haiku -fdeprecated-macro -fdebug-compilation-dir /boot/home/Desktop -ferror-limit 19 -fmessage-length 80 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o - -x c++ -
clang -cc1 version 3.8.0 based upon LLVM 3.8.0 default target i586-pc-haiku
ignoring nonexistent directory "/system/develop/headers/c++/backward"
ignoring nonexistent directory "/system/develop/headers/c++/i586-pc-haiku"
ignoring nonexistent directory "/usr/local/include"
ignoring nonexistent directory "/boot/system/bin/../lib/clang/3.8.0/include"
ignoring nonexistent directory "/boot/system/non-packaged/develop/headers"
ignoring nonexistent directory "/boot/system/develop/headers/3rdparty"
ignoring nonexistent directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /system/develop/headers/c++
 /boot/system/develop/headers/os
 /boot/system/develop/headers/os/app
 /boot/system/develop/headers/os/arch
 /boot/system/develop/headers/os/device
 /boot/system/develop/headers/os/drivers
 /boot/system/develop/headers/os/game
 /boot/system/develop/headers/os/interface
 /boot/system/develop/headers/os/kernel
 /boot/system/develop/headers/os/locale
 /boot/system/develop/headers/os/mail
 /boot/system/develop/headers/os/media
 /boot/system/develop/headers/os/midi
 /boot/system/develop/headers/os/midi2
 /boot/system/develop/headers/os/net
 /boot/system/develop/headers/os/opengl
 /boot/system/develop/headers/os/storage
 /boot/system/develop/headers/os/support
 /boot/system/develop/headers/os/translation
 /boot/system/develop/headers/os/add-ons/graphics
 /boot/system/develop/headers/os/add-ons/input_server
 /boot/system/develop/headers/os/add-ons/mail_daemon
 /boot/system/develop/headers/os/add-ons/registrar
 /boot/system/develop/headers/os/add-ons/screen_saver
 /boot/system/develop/headers/os/add-ons/tracker
 /boot/system/develop/headers/os/be_apps/Deskbar
 /boot/system/develop/headers/os/be_apps/NetPositive
 /boot/system/develop/headers/os/be_apps/Tracker
 /boot/system/develop/headers/bsd
 /boot/system/develop/headers/glibc
 /boot/system/develop/headers/posix
 /boot/system/develop/headers

End of search list.
`

**Comment by korli** [comment]
Please check with hrev50425 or newer. Thanks.
