### ISSUE TITLE
[Midnight Commander] Suggestion: switch from ncurses to slang-2.3.2

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#6849]
Now that Haiku's Terminal [supports 24 bit colors](https://git.haiku-os.org/haiku/log/?qt=range&q=hrev56010..hrev56011), maybe Midnight Commander could switch from being built with `--with-screen=ncurses` to `--with-screen=slang` in order to be able to use [true-color themes](https://midnight-commander.org/ticket/3724).

[This issue](https://dev.haiku-os.org/ticket/17719) might get in the way, but seems fairly minor.

BTW... any idea about why box-drawing characters are not used/enabled/working on the current `mc` Haiku port?

**Comment by augiedoggie** [comment]
I'm having trouble getting this to link properly with slang.  I might push an update to fix a few problems with the `mc` recipe but there are still issues with it.

> BTW... any idea about why box-drawing characters are not used/enabled/working on the current `mc` Haiku port?

Have you tried a different font?  `mc` looks identical between Haiku and Linux with both using a `Source Code Pro` font

**Comment by augiedoggie** [comment]
![screenshot1](https://user-images.githubusercontent.com/51547/168713652-2aa7ca8e-99c1-48d5-8a4c-f993f63e4c1f.png)
I did get it to build with slang.  I submitted a pull request and I'll give it a day to see if anyone has comments.
