### ISSUE TITLE
LeoCAD don't start on Haiku 32 bits (Error creating OpenGL context)

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#6852]
When trying to run LeoCAD (from Terminal), the following error appears:
Error creating OpenGL context.

Maybe there is a missing dependence ?

**Comment by threedeyes** [comment]
1. haiku b3 or nighly ? revision?
2. mesa_x86 and mesa_x86_swpipe updated to actual version (21.3.7) ?

**Comment by unspacyar** [comment]
Sorry, I missed that:  I'm using Haiku nightly (hrev56040).

Mesa packages:
mesa_x86 version: 21.3.7-1
mesa_x86_swpipe version:  21.3.7-1

qthaikuplugins_x86 version: 5.15.2.21-1

Let me try updating the qthaikuplugins package.

**Comment by unspacyar** [comment]
After upgrading the qthaikuplugins_x86 package, LeoCAD works fine.
Thanks for your help!
