### ISSUE TITLE
[pdflib] Suggestion: Don't include binaries for the included sample code

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#6893]
I was about to comment that `pdflib` should really get a `-devel` package instead of including everything in the main .hpkg, but... a comment on it's [recipe](media-libs/pdflib/pdflib-5.0.3.recipe) reads:

`# no devel package, due to licensing`

In that case... maybe the binaries for the **sample code** could not be included?

I guess that at least should trim several megabytes of the final size (depending on how well/bad it compresses), and some bandwidth as well.

**Comment by Begasus** [comment]
This was done here: https://github.com/haikuports/haikuports/commit/81cd27e422e68d9105065eb1e96574c5c9d86c1f
