### ISSUE TITLE
lftp 4.8.4-4 liblftp-network.so missing

### ISSUE THREAD

**Issue by Mad-Mason** [haikuports/haikuports#6908]
I've just installed `lftp` and it fails with `Missing library`.

I've run strace against it and the fault appear to be a missing link from `/boot/system/lib/lftp/4.8.4/liblftp-network.so` to `/boot/system/lib/liblftp-network.so`

Strace output shows
```
[  3605] read_stat(0xffffffff, "/boot/system/bin/lib/liblftp-network.so", false, 0x7faf7f3c0ce0, 0x80) = 0x80006003 No such file or directory (17 us)
[  3605] read_stat(0xffffffff, "/boot/home/config/non-packaged/lib/liblftp-network.so", false, 0x7faf7f3c0ce0, 0x80) = 0x80006003 No such file or directory (14 us)
[  3605] read_stat(0xffffffff, "/boot/home/config/lib/liblftp-network.so", false, 0x7faf7f3c0ce0, 0x80) = 0x80006003 No such file or directory (8 us)
[  3605] read_stat(0xffffffff, "/boot/system/non-packaged/lib/liblftp-network.so", false, 0x7faf7f3c0ce0, 0x80) = 0x80006003 No such file or directory (12 us)
[  3605] read_stat(0xffffffff, "/boot/system/lib/liblftp-network.so", false, 0x7faf7f3c0ce0, 0x80) = 0x80006003 No such file or directory (12 us)
[  3605] debug_output("runtime_loader: Cannot open file liblftp-network.so: No such file or directory
```

Regards
Iain

**Comment by augiedoggie** [comment]
Apparently this isn't the first time we've had to disable the shared modules. I just noticed #1248, maybe I should have left a note in the recipe file :stuck_out_tongue:

**Comment by korli** [comment]
Maybe fixing the root issue would be better.

**Comment by augiedoggie** [comment]
> Maybe fixing the root issue would be better.

Of course, but I don't see a lot of benefit in spending time on it *right now*.  Arch Linux disables the modules, the upstream project is abandoned, and it seems as though using the module system is more trouble than it's worth.
