### ISSUE TITLE
[Python] Enhancement: enable building with support for Tk/Tkinter

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#6914]
Considering that there are packages for both TCL and Tk, it would be nice if the packaged Python was built with support for Tk/Tkinter.

Currently (on Haiku beta3, Python 3.7.12), attempting to `import tkinter` fails with: `ModuleNotFoundError: No module named '_tkinter'`, and the offending line read:

`import _tkinter # If this fails your Python may not be configured for Tk`

Having a working tkinter module would allow running (or at least porting) multitude of new tools/programs/libs.

Edit: I just now noticed the WIP #6912, and its comments regarding the Tk ports (SDL vs X11 versions). I'm not really aware as to how functional the Tk ports really are (and that may well be why its support it's not enabled on Python).

I'll leave this issue up just in case (I guess devs can close it when the time comes).

As usual, thanks a lot guys, for your porting efforts!

**Comment by Begasus** [comment]
Well, it can be done, not sure how others feel about it (the PR I created was in the first place to have a working tcl/tk on 32bit)

![tkinter](https://user-images.githubusercontent.com/16057090/169028121-5692826b-ea8e-4f04-b264-9bea4c6153b6.png)

**Comment by pulkomandy** [comment]
We should enable it. Can it be made into a separate package? If yes, that's ideal, but if not I guess it's ok to have python depend on Tk (and Xlibe)

**Comment by korli** [comment]
maybe make it easily optional, so that bootstrapping is still possible.

**Comment by Begasus** [comment]
> We should enable it. Can it be made into a separate package? If yes, that's ideal, but if not I guess it's ok to have python depend on Tk (and Xlibe)

It's part of python (did this check with python310) so I don't think we can create a separate package for it, also as mentioned, tk is enabled for SDL2 not for Xlibe in the PR.

**Comment by Begasus** [comment]
Added some "sed" magic to the tk recipe, so far only python3.10 seems to pick this up, so not sure why the other (prior) versions don't ....

**Comment by Begasus** [comment]
> maybe make it easily optional, so that bootstrapping is still possible.

Added a PR that enables a build for tkinter and python3.10 at: https://github.com/haikuports/haikuports/pull/6932
It's optional atm (tcl/tk) so far that it is only needed when building, this also fixes the last commit from @OscarL , import only works when tk is installed (no dependency on installing python3.10)

**Comment by Begasus** [comment]
@OscarL 
```
Sometimes Linux distributions separate out their Tkinter support into a separate package.
That saves installing the Tcl/Tk libraries for people who are using Python but not Tkinter.
If so, you'll need to find and install this package, which will also ensure that appropriate
versions of the Tcl/Tk libraries are installed on your system.
```
I checked at repology on how others do this, it could be possible to have a separate _tkinter package created by moving the "right" stuff into a separate sub-package, would be the next step.
I also see that some move the tests into a separate package, that could save some bytes in the core package for python also, not sure how much they are needed to "run" python?

**Comment by Begasus** [comment]
Python3.9 also working (patch not added to the PR yet)

**Comment by Begasus** [comment]
Fixed in: https://github.com/haikuports/haikuports/pull/6932

**Comment by Begasus** [comment]
Glad to help out, 32bit should be OK in a short while on buildmaster, for 64bit tk needs a revbump and pythong 3.* also after that (my main focus is 32bit so forgot that the 64bit version for tk didn't got a rebuild) :)
