### ISSUE TITLE
Submit dev-cpp/abseil-cpp patches upstream

### ISSUE THREAD

**Issue by Tevo45** [haikuports/haikuports#6928]
Hello; the latest release of abseil doesn't seem to build on Haiku. Haikuports has a [patch](https://github.com/haikuports/haikuports/blob/master/dev-cpp/abseil-cpp/patches/abseil_cpp-20211102.0.patchset) for that, which looks trivial; is there any reason this wasn't submitted upstream? I ask because my [Bazel port](https://github.com/bazelbuild/bazel/issues/12522#issuecomment-1121321856) depends on it, and Bazel fetches and builds it's own version of the library, rather than relying on the system's.

@threedeyes

**Comment by pulkomandy** [comment]
Probably no one had time to submit it upstream yet.

It would be preferred for haikuports that Bazel uses system libraries instead of duplicating them (but in your own port, you do what you want...)

**Comment by korli** [comment]
Done

**Comment by pulkomandy** [comment]
For reference: https://github.com/abseil/abseil-cpp/pull/1181
