### ISSUE TITLE
xpmtranslator: doesn't find "unknown" license

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#6962]
> Error: No match found for license unknown

Removing "unknown" under LICENSE let's me build the package. Is the "unknown" intentional?

**Comment by Begasus** [comment]
@humdingerb this is known, trying to contact the original author for now failed so we can't add it to haikuports: https://github.com/haikuports/haikuports/pull/3744#issuecomment-553339555

**Comment by Begasus** [comment]
Closing as this is mentioned upstream.
