### ISSUE TITLE
BGhostview: Needs xpmtranslator in REQUIRED

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#6963]
XPMTranslator is required to show icons in the toolbar.

XPMTranslator currently fails to build, see #6962 .

**Comment by augiedoggie** [comment]
I have only briefly looked at the code but it should be pretty easy to just convert the icons to png or some other format and get rid of the xpmtranslator dependency.

**Comment by humdingerb** [comment]
That would be best, considering the open license question. The elusive "Ernest S. Tomlinson" has left no trace on the interwebs. Or it's been trotten out by the famous English composer of the same name...
