### ISSUE TITLE
verilator cant run examples

### ISSUE THREAD

**Issue by genki0000** [haikuports/haikuports#6971]
-- Verilator hello-world simple example
-- VERILATE ----------------
verilator -cc --exe top.v sim_main.cpp
-- COMPILE -----------------
make -j 4 -C obj_dir -f Vtop.mk
make[1]: Entering directory '/boot/home/Desktop/dram_control/hello_world_c/obj_dir'
Vtop.mk:53: /packages/verilator-3.924-1/.self/data/verilator/include/verilated.mk: No such file or directory
make[1]: *** No rule to make target '/packages/verilator-3.924-1/.self/data/verilator/include/verilated.mk'.  Stop.
make[1]: Leaving directory '/boot/home/Desktop/dram_control/hello_world_c/obj_dir'
Makefile:37: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by Begasus** [comment]
My bad probably (again), pushed to the latest release, had some success with building some of the examples provided in the source. Please check again once the buildmaster(s) finish their build.

**Comment by Begasus** [comment]
@genki0000 could you re-check?

**Comment by genki0000** [comment]
yep seems to work. thanks.
