### ISSUE TITLE
ghostwriter: crash on launch in QHaikuWindow::setParent()

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#6972]
Crashing on launch:

[Ghostwriter-1329-debug-03-06-2022-14-40-02.report.txt](https://github.com/haikuports/haikuports/files/8833119/Ghostwriter-1329-debug-03-06-2022-14-40-02.report.txt)

**Comment by Begasus** [comment]
Resolved: https://github.com/haikuports/haikuports/issues/7410
