### ISSUE TITLE
A example recipes for my games?

### ISSUE THREAD

**Issue by fstltna** [haikuports/haikuports#6973]
Just now getting into packaging my games for haiku, and I need some examples of recipes for them and what the tree structure should be. Would love any suggestions!

**Comment by Begasus** [comment]
Hi @fstltna first start would be checking out the wiki here: https://github.com/haikuports/haikuports/wiki
There are multiple pages that could help you getting started.
There are also some generic recipes (a bit out of date but still useful) if you cloned haikuporter: https://github.com/haikuports/haikuporter/tree/master/generic
Aside from that you could search here on github (haikuports) for games to get an idea on how others have done it: https://github.com/haikuports/haikuports/search?q=games

Don't hesitate to ask if you need help :)

**Comment by scottmc** [comment]
@fstltna any luck so far?

**Comment by waddlesplash** [comment]
This is not an "issue" and should be discussed elsewhere, I think.
