### ISSUE TITLE
(Haiku 32 bits) - package ktexteditor_x86-5.93.0-1 requires lib:libgit2_x86>=0.27.0, but none of the providers can be installed

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#6983]
Hi. Since a couple of days, I'm getting this error when trying to upgrade Haiku:

package ktexteditor_x86-5.93.0-1 requires lib:libgit2_x86>=0.27.0, but none of the providers can be installed

I already have the **libgit2_x86** package installed, and the version is 0.27.0-3, so don't understand why HaikuDepot throws this message.

**Comment by Begasus** [comment]
My bad probably, normally the buildmaster report mentions this, I've updated our libgit2 a few days ago, I'll try to see to revbump ktexteditor today so that should be fixed.

**Comment by Begasus** [comment]
@unspacyar could you check? revbumped ktexteditor and buildmaster finished the packages, should be OK now.

**Comment by unspacyar** [comment]
Hi @Begasus   I tried today and now is working perfectly.   Thank you so much for your help!
