### ISSUE TITLE
Port Furnace Tracker

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#7014]
https://github.com/tildearrow/furnace

This is a tracker for composing chiptune music with various soundchips. Seems to be SDL2 based so it should not be too difficult

**Comment by Begasus** [comment]
Got a look at it, need to ifndef __HAIKU__ at: https://github.com/tildearrow/furnace/blob/bdbebc99f1b5c9154b23f26484b939df1638b639/extern/igfd/ImGuiFileDialog.cpp#L1552

After build/install I'm facing: https://github.com/tildearrow/furnace/issues/464

Disabling the GUI can be done, but then you'll just end up with a binary for playback I guess ...

**Comment by pulkomandy** [comment]
There is now a pull request upstream for getting it to run under Haiku. Can you share your recipe (even if disabled for now) for testing?

**Comment by Begasus** [comment]
Saw it, grabbing the source first (clone) and do a check in Terminal, haven't started with a recipe, but if the build is OK then a recipe shouldn't be to hard to create.

**Comment by Begasus** [comment]
@pulkomandy PR created, think I covered most there, disabled for now.
