### ISSUE TITLE
Update gertty

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#7015]
Gertty is a python+ncurses interface to gerrit. There is an older version available in haikuports.
I wrote a recipe for a newer version but dependencies are missing or outdated, for example:

- a newer gitpython is needed
- this in turn depends on typing-extensions
- typing-extensions is not setuptools based, it needs flit (another python packaging system) hackaged first, and some changes to the typical python packaging recipe
Possibly there are more, yet undiscovered, packaging problems

**Comment by Begasus** [comment]
Should be done in: https://github.com/haikuports/haikuports/pull/7027
