### ISSUE TITLE
libusb bumb to 1.0.26

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#7017]
Latest revision is 1.0.26. Haikuports is currently at 1.0.24

CHECKSUM_SHA256="a09bff99c74e03e582aa30759cada218ea8fa03580517e52d463c59c0b25e240"

build error (x86_64)

./configure: line 17510: syntax error near unexpected token `UMOCKDEV,'
./configure: line 17510: `              PKG_CHECK_MODULES(UMOCKDEV, umockdev-1.0 >= 0.16.0, ac_have_umockdev=yes, ac_have_umockdev=no)'

**Comment by Begasus** [comment]
Missing cmd:pkg_config$secondaryArchSuffix in the recipe (BUILD_PREREQUIRES), see: https://github.com/libusb/libusb/issues/1096
Other errors when building atm:
```
/boot/system/develop/tools/x86/lib/gcc/i586-pc-haiku/11.2.0/include/stdatomic.h:218:9: error: '_Atomic' does not name a type
   218 | typedef _Atomic struct
```

**Comment by Begasus** [comment]
@Vidrep created a PR, could you have a look? I think you got more USB connected devices to check ;)
