### ISSUE TITLE
Add BeOhms to HaikuArchives

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#702]
Github does not allow you to upload .tar files, so I had to rename the file to .tar.zip to uplod it. 
[BeOhms-x86_src-incl.tar.zip](https://github.com/haikuports/haikuports/files/367170/BeOhms-x86_src-incl.tar.zip)

**Comment by waddlesplash** [comment]
https://github.com/HaikuArchives/BeOhms
