### ISSUE TITLE
FreeType rebuild required itself

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#7040]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=2943&viewMode=expanded

Note the required packages includes the previous version of FreeType and its devel package; this pulled in brotli despite it being removed.

**Comment by waddlesplash** [comment]
Next rebuild did the same, though of course this time there wasn't brotli in the dependencies: https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=2949&viewMode=expanded

**Comment by korli** [comment]
harfbuzz is the one pulling freetype. Tip: the last built package providing a dependency is the one included. Bumping the revision of freetype_bootstrap first will have the freetype build use it instead of itself.
