### ISSUE TITLE
Python 3.7.12 crashes when running gertty

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#7056]
- Install gertty: pkgman install cmd:gertty
- Create a configuration file in config/settings/gertty.yaml (I set one to point to review.haiku-os.org)
- Try to start gertty

The Python interpreter crashes (on x86_64).

**Comment by waddlesplash** [comment]
Report?

**Comment by pulkomandy** [comment]
[python3.7m-22439-debug-15-07-2022-18-05-06.report.txt](https://github.com/haikuports/haikuports/files/9123069/python3.7m-22439-debug-15-07-2022-18-05-06.report.txt)

**Comment by Begasus** [comment]
Just installed gertty (1.6.0-2) with pkgman, created a (minimal) gerty.yaml in ~/config/settings and launched gertty, seems to be OK on 32bit:

![gertty2](https://user-images.githubusercontent.com/16057090/179344781-2cf24ea8-fa00-41ca-94d0-ea8427b61e38.png)

**Comment by pulkomandy** [comment]
The crash is fixed with python 3.9.
