### ISSUE TITLE
gtk initialization crash

### ISSUE THREAD

**Issue by EmanueleDavalli** [haikuports/haikuports#7070]
I'm trying to port to haiku the editor Geany.
It compiles fine, but then crashes immediately while initializing gtk.

[lt-geany-30290-debug-22-07-2022-08-43-33.txt](https://github.com/haikuports/haikuports/files/9166462/lt-geany-30290-debug-22-07-2022-08-43-33.txt)

**Comment by EmanueleDavalli** [comment]
I did a bit of debugging myself:
it seems that gdk_pixbuf_get_formats() is calling g_build_filename() with arguments
"/system/settings",
"gdk-pixbuf-2.0",
"loaders.cache",
"",
invalid pointer 0x5f,
invalid pointer 0x44.

The last pointer is the one crashing the program because the variadic arguments should be terminated by a NULL.
Sadly i cannot debug any further because gdk-pixbuf debug symbols don't have source file information.

**Comment by Begasus** [comment]
Did a quick check/build in Terminal, doesn't crash for me, but doesn't seem to load the icons (missing icon theme?)
Maybe @threedeyes has a clue there?

![Geany](https://user-images.githubusercontent.com/16057090/180634167-6f65ba9e-af2c-4ee8-ad66-8ff8b0890221.png)

**Comment by EmanueleDavalli** [comment]
That's promising!
How did you compile?

**Comment by Begasus** [comment]
> That's promising! How did you compile?

Just did:
```
./autogen.sh
./configure --prefix=/boot/home/destdir --disable-html-docs
make
make install
```
Didn't have docutils installed to build the docs so first run with autogen.sh failed there, then restarted configure with the docs disabled.

**Comment by EmanueleDavalli** [comment]
Tried a clean build with those commands, same results.
Then i tried to reinstall gdk-pixbuf and during installation i get a similar crash in gdk-pixbuf-query-loaders
[gdk-pixbuf-query-loaders-853-debug-25-07-2022-08-03-16.txt](https://github.com/haikuports/haikuports/files/9179281/gdk-pixbuf-query-loaders-853-debug-25-07-2022-08-03-16.txt)

**Comment by Begasus** [comment]
Not sure if it's related, but wxgtk has just been updated, are you running the latest 3.2.0 version there?

**Comment by Begasus** [comment]
Should be resolved, if this keeps to be a problem, please re-open.
