### ISSUE TITLE
haikuwebkit: port to Webkit2

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#7071]
Enhancement (GSoC):
Update Haiku integration code.for Webkit2 backend.
For WebKit 614.1.20.1 and higher:
> Fix Haiku’s RemoteNetworkingContextHaiku code.
> Fix Haiku’s NetworkDataTaskHaiku code.
> Fix Haiku’s SharedMemoryHaiku code.
> Fix Haiku’s IPCSemaphoreUnix code.

**Comment by waddlesplash** [comment]
I don't think this is the appropriate place for this issue; we have a "Kits/Web Kit" component on the tracker instead?

**Comment by pulkomandy** [comment]
Agreed, webkit work is tracked in haiku bugtracker.
