### ISSUE TITLE
RtMidi pkg-config wrong includedir

### ISSUE THREAD

**Issue by OPNA2608** [haikuports/haikuports#7084]
The `includedir` entry of RtMidi's `rtmidi.pc` points to the wrong directory.

It should looks like this:
![Bildschirmfoto von 2022-08-01 15-11-52](https://user-images.githubusercontent.com/23431373/182155907-a6d0b6e5-125e-4c5c-ba31-01f56e0f7dee.png)
Note the `/rtmidi` in the `includedir`, and the presence of the headers in that directory.

With the `rtmidi_devel` package I installed via `pkgman`, this is what I'm getting:
![IMG_20220801_150650](https://user-images.githubusercontent.com/23431373/182156804-9a1879a2-8f62-40b2-8b00-ddb1353f0045.jpg)
Note the absence of the `/rtmidi` in the `includedir`, and the specified directory lacking the actual headers.

This causes configuration/build processes that use the pkg-config file for making use of a system-installed RtMidi to fail<sup>1</sup>, because the include is suddenly `"rtmidi/RtMidi.h"` instead of the usual `"RtMidi.h"`. If you want a real-world example to verify, I'm running into this with the master branch of [ptcollab](https://github.com/yuxshao/ptcollab) (this needs Qt5 and actually running it might currently be broken, but compilation is what matters here):
```
# Doesn't work without explicitly giving a full path to the haiku-g++ spec?
qmake -spec /boot/system/data/Qt5/mkspecs/haiku-g++
vim Makefile
# Edit out the broken path in the QMAKE variable so it's just "QMAKE = qmake", save & exit
make qmake_all
```
You should see
```
Checking for rtmidi_pkgconfig... no
Checking for rtmidi_lib... no
```
despite having `pkg-config` and `rtmidi_devel` installed. `src/config.log` will reveal the following:
```
executing config test rtmidi_pkgconfig
[...]
> g++ -c -pipe -O2 -pthread -Wall -Wextra -fPIC -DRTMIDI -D__HAIKU_BMIDI2__ -I. -I/packages/rtmidi-5.0.0-2/.self/develop/headers -I/boot/system/data/Qt5/mkspecs/haiku-g++ -o test.o ../../test.cpp
> ../../test.cpp:2:10: fatal error: RtMidi.h: No such file or directory
>     2 | #include "RtMidi.h"
>       |          ^~~~~~~~~~
> compilation terminated
```

[<sup>1</sup>] As for why the furnace package isn't affected by this misconfiguration, it looks like it actually [hardcodes its vendored RtMidi headers instead of resolving it via include paths…](https://github.com/tildearrow/furnace/blob/f689409f02ea98ad4620377bc34cc9415efc3273/src/audio/rtmidi.h#L20) Uff. :slightly_frowning_face:

**Comment by Begasus** [comment]
As for furnace indeed it seemed OK (so I didn't check further), if this remains a problem one of the solutions would be to alter the path after fixPkgconfig, see for an example: https://github.com/Begasus/haikuports/wiki/Useful-variables-for-recipes#fixpkgconfig

**Comment by korli** [comment]
Something like https://github.com/haikuports/haikuports/commit/730e9393dfd3a4dd9108936cb57dd92fab9e6ec7 might help

**Comment by Begasus** [comment]
> Something like [730e939](https://github.com/haikuports/haikuports/commit/730e9393dfd3a4dd9108936cb57dd92fab9e6ec7) might help

Added that one to the wiki, thanks @korli 

Fix coming up for rtmidi :)

**Comment by Begasus** [comment]
Checked with a build from ptcollab (which builds OK, but crashes some times with quick checks)
