### ISSUE TITLE
MAME debugger doesn't work

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#7085]
Start mame with the debugger:

     mame -debug

Error message:

    Ignoring MAME exception: Error: ImGui debugger requires the BGFX renderer.
    Fatal error: Error: ImGui debugger requires the BGFX renderer.

Then it crashes.

Options:

- Enable "BGFX" (what's this?)
- Use some non-ImGui debugger?

**Comment by pulkomandy** [comment]
BGFX also doesn't work:

     mame -video bgfx -debug

    Ignoring MAME exception: BGFX: Unable to load required shaders. Please check and reinstall the bgfx folder
    Fatal error: BGFX: Unable to load required shaders. Please check and reinstall the bgfx folder

**Comment by pulkomandy** [comment]
It looks like Qt could be used as a replacement for ImGui but I don't know how to enble it

**Comment by pulkomandy** [comment]
It looks like I can do:

     cd /system/lib/mame/
     mame -video bgfx -debug

But then it only renders a white screen

I am also a bit confused because the package comes with a MAME script (in addition to the mame executable). Am I supposed to use that? What does it do? It look like I cannot pass arguments to it...

**Comment by waddlesplash** [comment]
Looks like you can build with Qt by passing `USE_QTDEBUG=1` to the make, maybe?
