### ISSUE TITLE
Error trying to install geany_x86 on Haiku 32 bits

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#7086]
When trying to install it from HaikuDepot, I get the following error:

package geany_x86-1.38.0-1 requires lib:libgdk_3_x86>=3.2400.10 but none of the providers can be installed.

I'm using Haiku 32 bit - nightly (hrev56320).

**Comment by Begasus** [comment]
This is related to xlibe/cairo ... try to see if you can install `gtk3_x86` in `Terminal` with `pkgman`?

**Comment by unspacyar** [comment]
Hi!  I get the following error:

problem 1: package gtk3_x86-3.24.30-6 requires xcairo_x86>=1.16.0, but none of the providers can be installed
  solution 1:
    - allow deinstallation of cairo_x86-1.16.0-5
    - allow deinstallation of libx11_x86-1.6.9-3
    - allow deinstallation of cairo_x86_devel-1.16.0-5
    - allow deinstallation of libx11_x86_devel-1.6.9-3
  solution 2:
    - do not install "providing gtk3_x86"

**Comment by Begasus** [comment]
Right, as I thought, saw this when trying to build geany on another laptop, solution 1 is the way to go :)

**Comment by unspacyar** [comment]
Sorry for the 'noob' question:  I understant that both **cairo** and **xcairo** cannot live toghether in the same system.  That is the reason because I need to unninstall **cairo**?

**Comment by Begasus** [comment]
> Sorry for the 'noob' question: I understant that both **"cairo"** and **"xcairo"** cannot live toghether in the same system. That is the reason because I need to unninstall **cairo**?

Right (sorry for the late reply)
