### ISSUE TITLE
Add Hoipolloi to HaikuArchives

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#713]
Before uploading it to HaikuArchives, we might want to ask Michel Clasquin-Johnson if he would rather host it since he is the author. 

 [hoipolloi-04_src-incl.zip](https://github.com/haikuports/haikuports/files/367246/hoipolloi-04_src-incl.zip)

**Comment by waddlesplash** [comment]
Can you email him then?

**Comment by richienyhus** [comment]
He said he would be happy for it to be on Github.

**Comment by richienyhus** [comment]
https://github.com/HaikuArchives/HoiPolloi
