### ISSUE TITLE
[python] ensurepip still available despite recipes building Python with configure option "--without-ensurepip"

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#7184]
Having Python 3.7.12 and 3.10.6 installed, both of them have an `ensurepip` package installed on the respective  /system/lib/python3.xx/ folder.

I think the problem is that the recipes uses this: [--without-ensurepip](https://github.com/haikuports/haikuports/blob/380d0fc44435a52579c68e081e67285687436c5f/dev-lang/python/python3-3.7.12.recipe#L105)

 when the correct version seems to be: [--with-ensurepip=no](https://github.com/python/cpython/blob/88a7f661ca02c0eb76b8f19234b8293b70f171e2/configure#L1883)

Edit: To clarify...

My assumption is that the idea was to disable the inclusion of `ensurepip`, as the `pip` command has its own separate .hpkg.

**Comment by korli** [comment]
aren't --without options evaluated as --with...=no
https://github.com/python/cpython/blob/88a7f661ca02c0eb76b8f19234b8293b70f171e2/configure#L1515
