### ISSUE TITLE
libtar error: /boot/system/lib/libtar.so.0.0.0: Could not resolve symbol 'minor'

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#7185]
When trying to run an application that needs the libtar_x86 package, I got the following error:

runtime_loader: /boot/system/lib/x86/libtar.so.0.0.0: Could not resolve symbol 'minor'
resolve symbol "minor" returned: -2147478780
runtime_loader: /boot/system/lib/x86/libtar.so.0.0.0: Troubles relocating: Symbol not found

It is weird that the .so files are numbered as 0.0.0, instead of the package version (that is 1.2.20-4 in HaikuDepot).  I am using Haiku 32 bit, on a nightly version (hrev56408).

**Comment by unspacyar** [comment]
Also, I got the same error if I try to run the 'libtar' command, included in the package:

~> libtar
runtime_loader: /boot/system/lib/libtar.so.0.0.0: Could not resolve symbol 'minor'
resolve symbol "minor" returned: -2147478780
runtime_loader: /boot/system/lib/libtar.so.0.0.0: Troubles relocating: Symbol not found
~> libtar-x86 
runtime_loader: /boot/system/lib/x86/libtar.so.0.0.0: Could not resolve symbol 'minor'
resolve symbol "minor" returned: -2147478780
runtime_loader: /boot/system/lib/x86/libtar.so.0.0.0: Troubles relocating: Symbol not found
~>

**Comment by extrowerk** [comment]
> It is weird that the .so files are numbered as 0.0.0, instead of the package version (that is 1.2.20-4 in HaikuDepot).

No, thats not the version, but the SOName. This reflect the ABI compatibility.

**Comment by Begasus** [comment]
Confirmed, tried rebuilding with patches from Gentoo, but output is the same here.

**Comment by korli** [comment]
fixed in libtar-1.2.20-5
