### ISSUE TITLE
Add RefLine to HaikuArchives

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#719]
[RefLine_src-incl.pkg.zip](https://github.com/haikuports/haikuports/files/367302/RefLine_src-incl.pkg.zip)

**Comment by waddlesplash** [comment]
Can't install the .pkg. Can you report a Haiku bug, please?

**Comment by waddlesplash** [comment]
https://github.com/HaikuArchives/RefLine

**Comment by waddlesplash** [comment]
Also fixed the bug in LegacyPackageInstaller.
