### ISSUE TITLE
Update minisign 0.9 -> 0.10

### ISSUE THREAD

**Issue by applecuckoo** [haikuports/haikuports#7248]
Mainly realised this since minisign is used by the Haiku project itself to verify Haiku images. Not an expert at this so maybe @waddlesplash could help? Here's the changelog:

> - Minisign can be compiled with Zig instead of cmake+make+a C toolchain
> - Minimal `VERIFY_ONLY` versions can be built again
> - Prehashing is now enabled by default, regardless of the input size. Support for non-prehashed signatures will eventually be removed
> - Legacy signatures can be rejected with the addition of the `-H` flag
> - Precompiled binaries for Win64, Linux and WebAssembly are now available.

**Comment by waddlesplash** [comment]
I don't really know much about our use of minisign, @kallisti5 set that up.

**Comment by Begasus** [comment]
0.11 still builds fine, broken on 32bit secondary architecture (installs in $prefix/bin), so do we really want to have both architectures for 32bit as primary builds fine (there is only 1 binary in the package)?

**Comment by Begasus** [comment]
Fixed in: https://github.com/haikuports/haikuports/pull/9042
