### ISSUE TITLE
[Python] Create/Update recipe for the upcomming 3.11.0 release

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#7252]
Python 3.11.0 has an expected released date of [2022-10-24](https://peps.python.org/pep-0664/).

I have working (as in: it builds, installs, and is able to run the REPL) recipe+patchset for the current 3.11.0rc2 version (based on the 3.10.7 recipe+patchset... thanks @korli et al!).

~~https://github.com/OscarL/haikuports/commit/d937592e839fb1a748194278e273a88bd5671476~~ 
Edit: watch this branch: https://github.com/OscarL/haikuports/tree/python311, until I open at least a draft PR.

It is a first draft, but I figure it might come in handy (or at least serve as a point of discussion). It certainly was/is a learning experience!

This is my first attempt at working with patchsets of this size/scope, so any tip/suggestions/fixes are more than welcome!

Some notes:

From that 3.10.7 patchset, only 6 diffs from the first patch (@korli's "initial Haiku patch") were not applying cleanly anymore. Some of those even appear to not be necessary any longer.

What I did was split the patchset, filter out those diffs from the first patch, and apply them in order (the rest applied cleanly).

Then I manually coerced the remaining diffs to play ball with the current Python code. I'm sure I messed up something somewhere, and I'm specially not sure if the changes I've made to `Lib/siteconfig.py` are correct.

I guess we'll find out.

PS: I've attempted to build with "--enable-optimizations", but it seemed to hung up (one core pegged to 100%, but memory usage was flat-lining, with zero I/O), so I killed it after half an hour of no changes.  At the time of the hang, there were some "libgcov error" messages on the Terminal window.

Edit: Tried building again with "--enable-optimizations", and the build was successful. The PYSTONE benchmark runs around a 25% faster than on 3.10.7 (latest version on HaikuDepot, without optimizations).

Not sure what can causes the builds to fail occasionally.

**Comment by Begasus** [comment]
Did you clean the build before running a new build? (saw this also a few times for packages that build fine, cleaning and doing a new build solved that)

**Comment by Begasus** [comment]
Well Python 3.11 is still in development stage (iirc), maybe you could get in contact with the developers there about open issues atm?

**Comment by korli** [comment]
Well 3.12 might be even more work and regressions.

**Comment by Begasus** [comment]
Merged in the meantime.
