### ISSUE TITLE
gimp fatal error at launch

### ISSUE THREAD

**Issue by haroldsoixante** [haikuports/haikuports#7258]
gimp stops launching immediately on fatal error
message appears only when launched from terminal :

~> /boot/system/apps/GIMP 
runtime_loader: /boot/system/lib/libuuid.so.1.3.0: No version information available (required by /boot/system/lib/libappstream-glib.so.8.0.10)
runtime_loader: /boot/system/lib/libappstream-glib.so.8.0.10: Could not resolve symbol 'uuid_unparse'
resolve symbol "uuid_unparse" returned: -2147478780
runtime_loader: /boot/system/lib/libappstream-glib.so.8.0.10: Troubles relocating: Symbol not found

see attached..

![screenshot2](https://user-images.githubusercontent.com/102438052/194670650-cb4f55f4-2927-49d7-904e-3be9fc0eaeba.png)
![screenshot3](https://user-images.githubusercontent.com/102438052/194670694-c485003f-9fcd-4f1c-b07e-00530d153feb.png)

**Comment by haroldsoixante** [comment]
just add the nightly screen
![screenshot4](https://user-images.githubusercontent.com/102438052/194670802-25ec9ecc-f1a5-4b9c-ac70-ca52eceb2518.png)

**Comment by Begasus** [comment]
appstream-glib has been updated not too long ago, maybe a revision bump is needed here?

**Comment by haroldsoixante** [comment]
awaiting to get the ability to launch gimp on haiku :o

**Comment by diversys** [comment]
You can get it from LOTE repo for now https://haikuware.ru/package_list.php?repo=lote

**Comment by waddlesplash** [comment]
Probably appstream_glib should be built with `-Wl,--no-undefined` placed in LDFLAGS.

**Comment by Begasus** [comment]
Still crashing on latest version bump on 32bit (same error).

**Comment by waddlesplash** [comment]
And https://github.com/haikuports/haikuports/commit/b40e44eee1f63cb7ed9880adc04c5033fc374ead?

**Comment by Begasus** [comment]
Launches fine after that commit. Can be closed if no one else has issues with it. :)

**Comment by humdingerb** [comment]
No problems installing from HaikuDepot and launching on Haiku hrev56578+22, 64bit.
