### ISSUE TITLE
SMB client hrev56521 64 bit not work

### ISSUE THREAD

**Issue by kim1963** [haikuports/haikuports#7272]
Debug report

https://dev.haiku-os.org/attachment/ticket/17981/userlandfs_server-27415-debug-10-10-2022-02-02-36.report

https://dev.haiku-os.org/attachment/ticket/17981/syslog56521.txt

**Comment by pulkomandy** [comment]
Yes, the latest version with my fixes is on haikuarchives. Jua made his version private so I based my work off Diver's backup copy.
