### ISSUE TITLE
Add recipe for LLVM 15

### ISSUE THREAD

**Issue by X547** [haikuports/haikuports#7276]

**Comment by kenmays** [comment]
I have a recipe for LLVM 15.0.5. If you want to update your patch for it. I can test it.

**Comment by davidkaroly** [comment]
Is it still valid now that llvm16 is available in HaikuDepot?

**Comment by kenmays** [comment]
No, historical. Superseded by https://github.com/haikuports/haikuports/pull/9141.

**Comment by Begasus** [comment]
Closing as superseded by LLVM16
