### ISSUE TITLE
Add a recipe for mdate

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#728]
https://github.com/ewe2/mdate

Old BeOS port:  [mdate-1.5.1-BeOS_src-incl.zip](https://github.com/haikuports/haikuports/files/368897/mdate-1.5.1-BeOS_src-incl.zip)

**Comment by localanu** [comment]
where I must put the recipe?

**Comment by scottmc** [comment]
Put it in app-misc

**Comment by richienyhus** [comment]
#1876 should close this once merged

**Comment by fbrosson** [comment]
#1876 just merged :-)
