### ISSUE TITLE
Add VanDelay to HaikuArchives

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#729]
[Vandelay-1.0-src.zip](https://github.com/haikuports/haikuports/files/368904/Vandelay-1.0-src.zip)

**Comment by waddlesplash** [comment]
https://github.com/HaikuArchives/Vandelay

**Comment by scottmc** [comment]
Where did you get this source code and what is the license that it was agreed to for releasing it?  Did you discuss with original author?  What's the copyright date(s)?  Try to get this info documented when adding source code please.

**Comment by richienyhus** [comment]
The app and its source code was on [BeBits](http://www.bebits.com/app/3063) and Haikuware. I can't seem to access my Haikuware archive right now to get further info, but I will try again later.
