### ISSUE TITLE
Frescobaldi is missing on x86

### ISSUE THREAD

**Issue by jmairboeck** [haikuports/haikuports#7317]
The package frescobaldi (see #6924) is not available on x86. It is an "any" arch package, and according to the buildmaster log, it built successfully:

https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/3211/builds/78727.log

**Comment by Begasus** [comment]
Confirmed, `pkgman search frescobaldi` didn't produce any hits on 32bit here

**Comment by jmairboeck** [comment]
thanks, I have it installed now.

I checked which portmidi it needs. As expected, it is `portmidi_x86` (because python3 uses secondaryArch), so I guess we must keep it that way and can't add a dependency ...
