### ISSUE TITLE
Add gerbv gerber file viewer

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#7320]
Uses Cairo or GTK+
http://gerbv.geda-project.org/

**Comment by pengphei** [comment]
As for gerbv, it depends:

gtk+-2: needs porting
xrender, not compitable with xlibe, will need reimpliment.

much work todo ;)

**Comment by Begasus** [comment]
Could this be closed? The ones reported on repology still mention using GTK+2 (which I guess will never happen on Haiku), latest source dates from 8 to 15 years ago.

https://github.com/spe-ciellt/gerbv
http://git.geda-project.org/gerbv/

**Comment by pulkomandy** [comment]
Yes, we could use the Gerber viewer provided with Kicad instead, when that gets ported.
