### ISSUE TITLE
BeCJK icons break

### ISSUE THREAD

**Issue by pengphei** [haikuports/haikuports#7323]
With the latest BeCJK， its icons are broken.
![becjk-icon-break](https://user-images.githubusercontent.com/895650/197933619-0024acb0-939b-43ee-a4c8-bb05cd3eac29.png)

**Comment by mmuman** [comment]
I just noticed this here too, with 1.0.1-5.

**Comment by mmuman** [comment]
I suspect either some 64bit issue in the custom XPM reader, or maybe some change in BBitmap, it seems the data is there but the stride is incorrect, the about box does some something that resemble the intended picture.

**Comment by mmuman** [comment]
Why do I have the impression it's due to hrev55351…

**Comment by mmuman** [comment]
Yep; fixed upstream.

**Comment by mmuman** [comment]
Just bumped the recipe.
