### ISSUE TITLE
Add Shirley to HaikuArchives

### ISSUE THREAD

**Issue by richienyhus** [haikuports/haikuports#733]
[shirley_beta_7.zip](https://github.com/haikuports/haikuports/files/369087/shirley_beta_7.zip)

**Comment by waddlesplash** [comment]
That's not actually the full source code; it's just the source code for the plugins. The library itself is closed-source, and the author is long gone...

**Comment by richienyhus** [comment]
I am going to contact the author. I am a bit busy at the moment, but I will add the links here for safe keeping.

https://github.com/dparnell
https://bitbucket.org/dparnell/
http://blog.danielparnell.com
