### ISSUE TITLE
haikuporter: No module named 'HaikuPorter'

### ISSUE THREAD

**Issue by danboid** [haikuports/haikuports#7357]
If I install haikuporter via HaikuDepot it fails to run with the error:

```
ModuleNotFoudError: No module named 'HaikuPorter'
```

Haikuporter runs fine if I clone its repo from github but it would be nice if the haikudepot package worked.

**Comment by korli** [comment]
yes, the package installs as python 3.7 module, but the package doesn't declare this dependency (python3 >= 3.7). It's broken since f4e7f37f8b3099e2e116aba18241f8b35b986ee6

**Comment by Begasus** [comment]
Maybe it's time to release a new version for haikuporter? git repo contains version 1.2.7 already while the one here still is version 1.2.5 (1.2.6 is released also but hasn't been updated here).
