### ISSUE TITLE
zziplib: invoking cmake without CMAKE_BUILD_TYPE specified

### ISSUE THREAD

**Issue by danboid** [haikuports/haikuports#7358]
I want to try building milkytracker but it seems I need to build zziplib first yet I cannot because I get the error:

```
error: invoking cmake without CMAKE_BUILD_TYPE specified!
note: you probably want -DCMAKE_BUILD_TYPE=Release ...
```

When I try to build zziplib with haikuporter.

**Comment by danboid** [comment]
This is fixed by https://github.com/haikuports/haikuports/pull/7359

**Comment by korli** [comment]
Why not install devel:libzzip?
