### ISSUE TITLE
Add a recipe for FLTK

### ISSUE THREAD

**Issue by mmuman** [haikuports/haikuports#737]
My current FLTK port is available here:
https://github.com/mmuman/fltk-test-only/tree/haiku-port-rebasing
It's not yet usable but someday it will need a recipe.

**Comment by Begasus** [comment]
Page not found @mmuman ? :)

**Comment by waddlesplash** [comment]
Appears to now live at https://github.com/mmuman/fltk-test-only/tree/haiku-1.4-rebasing

**Comment by mmuman** [comment]
Actually the working branch is the 1.3 one.
I've rebased it against the new and official repository and added a recipe in 92db0c6.
