### ISSUE TITLE
haiku-apps/vision: Update default IRC server from freenode to OFTC?

### ISSUE THREAD

**Issue by xoblite** [haikuports/haikuports#7388]
...last time I looked at a nightly it was still having **freenode** as its one and only default server.
Apologize if this has changed more recently, but I figured it'd be a good thing to address for beta 4 so reporting just in case...

BR//Karl aka qwilk/@xoblite

**Comment by humdingerb** [comment]
That was changed quite a while back already, see https://github.com/HaikuArchives/Vision/commit/10352663daab4dc41fbc28fd34de74904266dee7

Maybe some lingering Vision settings file on your end?
