### ISSUE TITLE
Adjust path to .wget-hsts in wget

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#739]
Currently wget creates ~/.wget-hsts file. It should probably be moved to ~/config/cache

**Comment by korli** [comment]
Sounds like #460, which should already fixed after the update of packages on 21th July. Please check again.

**Comment by Giova84** [comment]
I am on Haiku hrev50480 and now the "wget-hsts" file (now without the dot) is present under ~/config/settings

**Comment by pulkomandy** [comment]
Duplicate of #460.
