### ISSUE TITLE
FtpPositive missing symbol

### ISSUE THREAD

**Issue by bbjimmy** [haikuports/haikuports#7390]
/boot/system/apps/FtpPositive/FtpPositive
runtime_loader: /boot/system/apps/FtpPositive/FtpPositive: Could not resolve symbol '_ZTI4BRow'
resolve symbol "_ZTI4BRow" returned: -2147478780
runtime_loader: /boot/system/apps/FtpPositive/FtpPositive: Troubles relocating: Symbol not found

**Comment by humdingerb** [comment]
Fixed with 311ad58
