### ISSUE TITLE
Speedometer crashes QtWebEngine

### ISSUE THREAD

**Issue by Agandalf** [haikuports/haikuports#7399]
Running Speedometer benchmark in Falkon browser crashes QtWebEngine. Speedometer website below:
https://browserbench.org/Speedometer2.1/

[QtWebEngineProcess-89250-debug-12-11-2022-05-51-05.txt](https://github.com/haikuports/haikuports/files/9994250/QtWebEngineProcess-89250-debug-12-11-2022-05-51-05.txt)

**Comment by kenmays** [comment]
Tested. Resolved using qtwebengine-5.15.2-2.
