### ISSUE TITLE
vlc 0.86 resolve symbol "img_convert" returned: -2147478780

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#740]
vlc 0.86 uses deprecated function img_convert.

rm -rf ~/config/settings/VideoLAN Client/cache/plugins*.dat
vlc
resolve symbol "img_convert" returned: -2147478780

img_convert() needs to be repalced with sws_scale()

```
grep -rIn img_convert modules
modules/codec/ffmpeg/chroma.c:164:        img_convert( &p_vout->chroma.p_sys->tmp_pic,
modules/codec/ffmpeg/chroma.c:173:        img_convert( &dest_pic, p_vout->chroma.p_sys->i_dst_ffmpeg_chroma,
modules/codec/ffmpeg/video.c:842:            img_convert( &dest_pic, PIX_FMT_YUV420P,
modules/codec/ffmpeg/video_filter.c:524:        img_convert( p_dst, p_sys->i_dst_ffmpeg_chroma,
```

**Comment by pulkomandy** [comment]
Maybe it is time to focus on the 2.x versions of VLC?
Otherwise we can try to make it use an old version of ffmpeg again. It makes little sense to try to use VLC 0.8 with current ffmpeg.

**Comment by diversys** [comment]
Do you think it's not feasible to make VLC use current ffmpeg version?

**Comment by pulkomandy** [comment]
It's possible, but I think it is a waste of time. It would be easier to write a native GUI for a current version of VLC.

**Comment by miqlas** [comment]
+1

**Comment by waddlesplash** [comment]
We have new VLC, can we close this?

**Comment by extrowerk** [comment]
i think it is safe to close.
