### ISSUE TITLE
Jetstream crashes QtWebEngine

### ISSUE THREAD

**Issue by Agandalf** [haikuports/haikuports#7400]
Running Jetstream benchmark in Falkon browser crashes QtWebEngine. Jetstream 2 website below:
https://browserbench.org/JetStream/

[QtWebEngineProcess-91655-debug-12-11-2022-05-57-46.txt](https://github.com/haikuports/haikuports/files/9994268/QtWebEngineProcess-91655-debug-12-11-2022-05-57-46.txt)

**Comment by kenmays** [comment]
Tested. Resolved using qtwebengine-5.15.2-2.
