### ISSUE TITLE
Ghostwriter crashes

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#7410]
ghostwriter-1.7.4-3 crashes upon launch (Haiku hrev56588, 64bit): 
[Ghostwriter-17686-debug-14-11-2022-08-38-38.report.txt](https://github.com/haikuports/haikuports/files/10001204/Ghostwriter-17686-debug-14-11-2022-08-38-38.report.txt)

**Comment by Begasus** [comment]
Crashes on 32bit too

**Comment by threedeyes** [comment]
![photo_2022-11-20_20-48-06](https://user-images.githubusercontent.com/2559260/202898063-db04bb2f-f902-4ae7-8b3b-16919eb2b05c.jpg)

**Comment by humdingerb** [comment]
New version? My crashy one is v1.7.4

**Comment by threedeyes** [comment]
1.7.4 fixed in https://github.com/haikuports/haikuports/commit/3a3e1f7884b927132c58e2f8b133f1094837fd1d

**Comment by threedeyes** [comment]
![photo_2022-11-20_21-42-35](https://user-images.githubusercontent.com/2559260/202900059-47e19245-68c9-4c35-8280-c2067c55dc81.jpg)
