### ISSUE TITLE
Gimp cannot be installed

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#7411]
Trying to install Gimp on hrev56588, 64bit:

```
problem 1: package gimp-2.99.8-3 requires lib:libgegl_0.4>=0.433.1, but none of the providers can be installed
  solution 1:
    - allow deinstallation of cairo-1.16.0-5
  solution 2:
    - do not install "providing gimp"

```

**Comment by humdingerb** [comment]
Hmm... I was reluctant to deinstall cairo. But deinstalling it apparently had no sideeffects, no app was uninstalled.
After that I could install Gimp (and Inkscape btw).
So, close ticket?

**Comment by Begasus** [comment]
Had a build checked on 64bit also here a while ago, same error on launch

**Comment by korli** [comment]
reported here: https://github.com/haikuports/haikuports/issues/7258

**Comment by humdingerb** [comment]
I never liked Gimp anyway... :P
Thanks!

**Comment by jmairboeck** [comment]
Gimp probably needs xcairo (the version based on xlibe) which [conflicts with the normal cairo](https://github.com/haikuports/haikuports/blob/f366bf6118862812c481cd11227c95e1c15ffb52/x11-libs/cairo/xcairo-1.16.0.recipe#L55).

**Comment by waddlesplash** [comment]
Yes, indeed that's correct, you have to uninstall cairo and install xcairo instead when installing GIMP.

**Comment by humdingerb** [comment]
Shouldn't the gimp recipe have "xcairo" in its REQUIRES instead of "lib:libcairo"?

**Comment by waddlesplash** [comment]
No, it doesn't need to, because GIMP itself just uses plain old Cairo. It's GTK that needs xcairo, and depends on it appropriately. So GIMP's Cairo require will be supplied by xcairo while GTK is installed.
