### ISSUE TITLE
subtitlecomposer: 0.7.0-3 build fails on hrev56595 x64

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#7443]
1. src/streamprocessor/streamprocessor.cpp:204:52 - Invalid conversion 'const AVCodec' to 'AVCodec*'

**Comment by Begasus** [comment]
These patches could work?
https://invent.kde.org/multimedia/subtitlecomposer/-/commit/4f4f560e40ba0b760cf688eb024be3cc734ca347.patch
https://invent.kde.org/multimedia/subtitlecomposer/-/commit/d8f9797d9c0d45fa9f4402f79c539544b74d2cc7.patch

**Comment by kenmays** [comment]
Re-tested. Resolved. Build works with Haiku hrev56621 x86_gcc2.
