### ISSUE TITLE
johntheripper:1.9.0-1 build fails on hrev56595 x64

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#7460]
In file included from argon2_core_plug.c:
1. blake2.h:112:5: error: size of array element is not the multiple of its alignment: blake2b_state S[4][1];

**Comment by Begasus** [comment]
https://github.com/openwall/john/issues/4604

**Comment by kenmays** [comment]
Resolved: https://github.com/haikuports/haikuports/pull/7489
