### ISSUE TITLE
Webkit_GTK needs macro "LITTLE_ENDIAN" defined

### ISSUE THREAD

**Issue by SamuraiCrow** [haikuports/haikuports#7462]
This morning when I built Webkit_GTK with HaikuPorter, a warning popped up during the build stating that a macro called "LITTLE_ENDIAN" was undefined and equated to 0.  This was on an x86_64 architecture so this was clearly wrong.  It should be set to the same endianness as the equivalent Haiku SDK macro.

**Comment by SamuraiCrow** [comment]
## Update

```
/sources/webkitgtk-2.38.2/Source/ThirdParty/xdgmime/src/xdgmimemagic.c: In function '_xdg_mime_magic_parse_magic_line':
/sources/webkitgtk-2.38.2/Source/ThirdParty/xdgmime/src/xdgmimemagic.c:489:5: warning: "LITTLE_ENDIAN" is not defined, evaluates to 0 [-Wundef]
  489 | #if LITTLE_ENDIAN
      |     ^~~~~~~~~~~~~
```

**Comment by SamuraiCrow** [comment]
Referenced in https://github.com/haikuports/haikuports/pull/7469

**Comment by Begasus** [comment]
This can be closed as completed?

**Comment by SamuraiCrow** [comment]
Yes.
