### ISSUE TITLE
pinentry: 1.1.0-2 build fails on hrev56595 x64

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#7463]
1. pinentry-emacs.c:178: unknown reference to 'socket' (function: set_socket)

**Comment by Begasus** [comment]
libnetwork ... I think some/most of the issues you reported can be easily fixed when you know where to search?

**Comment by kenmays** [comment]
Resolved: https://github.com/haikuports/haikuports/pull/7486
