### ISSUE TITLE
Bump Celestia version to 1.6.2.2

### ISSUE THREAD

**Issue by TheLostProbe** [haikuports/haikuports#7467]
https://github.com/CelestiaProject/Celestia/releases/tag/1.6.2.2

**Comment by Begasus** [comment]
Done, thanks for the heads up!

**Comment by TheLostProbe** [comment]
no problem haha, i'll alert you once again when 1.7.0 finally releases too :)

**Comment by Begasus** [comment]
Don't know if you looked at our patchset (isn't mine :) ), maybe some of it could be upstreamed?

**Comment by TheLostProbe** [comment]
i'm not one of celestia's developers so i wouldnt really know, you would have to ask them (email team@celestia.space, or create an issue on [the repo](https://github.com/CelestiaProject/Celestia)). or we could just ask scottmc and/or threedeyes

**Comment by Begasus** [comment]
OK, will leave it for now then :)
