### ISSUE TITLE
Migration to python 3.9

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#7475]
1. Review package migration issues on python <3.9.

- [x] calibre
- [x] dev-python
- [x] freshcobaldi
- [x] fs-uae-launcher
- [x] haikuporter
- [x] jdreplace
- [x] jdtextedit
- [x] openshot
- [x] picard
- [x] pyqt5_python
- [x] qutebrowser
- [x] qscintilla
- [x] retext
- [x] youtube_dl
- [x] yt_dlp

**Comment by jmairboeck** [comment]
The haikuporter package is also broken since the switch to python 3.9.

**Comment by n0toose** [comment]
Hi, a fresh system with `pkgman install python` (which currently installs Python 3.7.14) cannot execute Python files with a shebang.

- `touch test.py`
- `chmod +x test.py`
- Append the following:
```python
#!/usr/bin/env python

print("hello world!")
```
- Run the file:
```
~> ./test.py
-bash: ./test.py: Permission denied
```

**Comment by pulkomandy** [comment]
python3.9 comes preinstalled in the release. Just don't "pkgman install python" and you should be fine.

**Comment by n0toose** [comment]
> python3.9 comes preinstalled in the release. Just don't "pkgman install python" and you should be fine.

Weird, I didn't seem to have it installed when I updated from a pre-beta4 nightly to a past-beta4 nightly. I am not sure if I did anything cursed on accident.

> Also you have to use `#!/usr/bin/env python3` at the top of your file.

Missed that, I'll send in the PR for Haikuporter because that's the program I had this happen with and got sidetracked by the fact that this worked with `python3.9` without using the package directly.

**Comment by pulkomandy** [comment]
The upgrade path was not very well tested I think. So maybe in that case it doesn't get added. Generally it still seems a bit random which Python versions you end up with... The goal was 3.9 for beta4 but there is some 3.7 still around and some 3.10 already starting to appear...

**Comment by n0toose** [comment]
> The upgrade path was not very well tested I think.

Thankfully, using the package manager makes things OK-ish again on the Nightly, relatively speaking.

**Comment by korli** [comment]
x86_64 should now be fine. Waiting for the builder on x86.

**Comment by kenmays** [comment]
- [x] x86-64: Buildrun [8400](https://build.haiku-os.org/buildmaster/master/x86_64/?buildrunDir=8180&viewMode=expanded)
- [ ] x86: Buildrun [3841](https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=3841&viewMode=expanded)

Thanks for the update. Seems the x86 buildbot is acting up since Monday... but everything else looks good for now.
Closing ticket.
