### ISSUE TITLE
GTK apps crash gtk_icon_helper assertion (both GIMP and Epiphany) on a particular box.

### ISSUE THREAD

**Issue by smallstepforman** [haikuports/haikuports#7477]
I have 2 Haiku machines (hrev56595) with Epiphany / GIMP. On the desktop, they both work fine.  On the laptop, on start it always asserts (crash) in the following stack trace:

abort + 0x4a
g_get_current_dir(void) + 0x37
g_assertion_message_error()
ensure_surface_for_gicon + 0x35a
gtk_icon_helper_load_surface + 0x224
_gtl_icon_helper_get_size + 0x11a

This started after an update this morning, it was working fine a couple of days ago when I last tried it.  I repeat, on the desktop PC with the exact same version, it works fine.  This impacts both GIMP and Epiphany, so the underlying GTK library has an issue on this laptop (configuration file?  cache?  settings?)

**Comment by threedeyes** [comment]
Remove this folders:

rm -rf /boot/system/non-packaged/data/mime
rm -rf /boot/home/config/non-packaged/data/mime

And try again.

**Comment by smallstepforman** [comment]
Hi 3deyes.  Both directories do not exist.  When I run the browser from the command line, this is the error I get.

/boot/system/apps/GNOME Web> ./Web

(Web:10852): GLib-GIO-WARNING **: 09:32:07.711: Failed to create file monitor for /boot/home/config/settings/glib-2.0/settings/keyfile: Unable to find default local file monitor type

(epiphany:10852): GLib-GIO-WARNING **: 09:32:07.716: Failed to create file monitor for /boot/home/config/non-packaged/data/epiphany/permissions.ini: Unable to find default local file monitor type
wl_ips_client_connected
display: 0x11a124b3e6a0
client: 0x11a124b75040

(epiphany:10852): Gtk-WARNING **: 09:32:07.854: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /boot/system/data/icons/haiku/status/16/image-missing.svg: Unable to load image-loading module: /packages/gdk_pixbuf-2.42.2-8/.self/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: No such file or directory (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /boot/system/data/icons/haiku/status/16/image-missing.svg: Unable to load image-loading module: /packages/gdk_pixbuf-2.42.2-8/.self/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: No such file or directory (gdk-pixbuf-error-quark, 5)
Abort
Kill Thread

**Comment by threedeyes** [comment]
All packages is updated? Librsvg installed?

**Comment by smallstepforman** [comment]
GIMP gives the same error:

/system/apps> GIMP
wl_ips_client_connected
display: 0x109e73b3df30
client: 0x109e73a91260

(GIMP:14873): GLib-GIO-WARNING **: 10:11:18.251: Failed to create file monitor for /boot/home/config/settings/glib-2.0/settings/keyfile: Unable to find default local file monitor type
Cannot spawn a message bus when AT_SECURE is set
Skipping extension '/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/extensions/org.gimp.extension.goat-exercises': /packages/gimp-2.99.14-1/.self/lib/gimp/2.99/extensions/org.gimp.extension.goat-exercises/org.gimp.extension.goat-exercises.metainfo.xml could not be read: Failed to open file “/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/extensions/org.gimp.extension.goat-exercises/org.gimp.extension.goat-exercises.metainfo.xml”: No such file or directory
This is a development version of GIMP.  Debug messages may appear here.


(GIMP:14873): GLib-CRITICAL **: 10:11:18.303: g_path_get_dirname: assertion 'file_name != NULL' failed
Application icon missing: /packages/gimp-2.99.14-1/.self/data/icons/hicolor/scalable/apps/gimp.svg (Unable to load image-loading module: /packages/gdk_pixbuf-2.42.2-8/.self/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: No such file or directory)
gui_dbus_name_lost: connection to the bus cannot be established.
set device 'Wayland Pointer' to mode: disabled
Traceback (most recent call last):
  File "/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/plug-ins/colorxhtml/colorxhtml.py", line 24, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
GIMP-WARNING: GIMP: gimp_wire_read(): error

Traceback (most recent call last):
  File "/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/plug-ins/file-openraster/file-openraster.py", line 16, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
GIMP-WARNING: GIMP: gimp_wire_read(): error

Traceback (most recent call last):
  File "/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/plug-ins/foggify/foggify.py", line 17, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
GIMP-WARNING: GIMP: gimp_wire_read(): error

Traceback (most recent call last):
  File "/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/plug-ins/gradients-save-as-css/gradients-save-as-css.py", line 25, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
GIMP-WARNING: GIMP: gimp_wire_read(): error

Traceback (most recent call last):
  File "/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/plug-ins/histogram-export/histogram-export.py", line 42, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
GIMP-WARNING: GIMP: gimp_wire_read(): error

Traceback (most recent call last):
  File "/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/plug-ins/palette-offset/palette-offset.py", line 16, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
GIMP-WARNING: GIMP: gimp_wire_read(): error

Traceback (most recent call last):
  File "/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/plug-ins/palette-sort/palette-sort.py", line 26, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
GIMP-WARNING: GIMP: gimp_wire_read(): error

Traceback (most recent call last):
  File "/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/plug-ins/palette-to-gradient/palette-to-gradient.py", line 16, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
GIMP-WARNING: GIMP: gimp_wire_read(): error

Traceback (most recent call last):
  File "/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/plug-ins/python-console/python-console.py", line 19, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
GIMP-WARNING: GIMP: gimp_wire_read(): error

Traceback (most recent call last):
  File "/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/plug-ins/python-eval/python-eval.py", line 19, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
GIMP-WARNING: GIMP: gimp_wire_read(): error

Traceback (most recent call last):
  File "/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/plug-ins/spyro-plus/spyro-plus.py", line 18, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
GIMP-WARNING: GIMP: gimp_wire_read(): error

GIMP-Error: Unable to run plug-in "test-sphere-v3.scm"
(/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/plug-ins/test-sphere-v3/test-sphere-v3.scm)

Failed to fork (No such file or directory)

GIMP-Error: Unable to run plug-in "ts-helloworld.scm"
(/packages/gimp-2.99.14-1/.self/lib/gimp/2.99/plug-ins/ts-helloworld/ts-helloworld.scm)

Failed to fork (No such file or directory)

gimp_plug_in_extension_process: Invalid Argument

(GIMP:14873): Gtk-WARNING **: 10:11:28.458: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /boot/system/data/icons/Adwaita/scalable/status/image-missing-symbolic.svg: Unable to load image-loading module: /packages/gdk_pixbuf-2.42.2-8/.self/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: No such file or directory (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /boot/system/data/icons/Adwaita/scalable/status/image-missing-symbolic.svg: Unable to load image-loading module: /packages/gdk_pixbuf-2.42.2-8/.self/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: No such file or directory (gdk-pixbuf-error-quark, 5)
Abort
Kill Thread

**Comment by smallstepforman** [comment]
The files /boot/system/data/icons/haiku/status/16/image-missing.svg (requested by Epiphany) and /boot/system/data/icons/Adwaita/scalable/status/image-missing-symbolic.svg (requested by GIMP) both exist.

**Comment by threedeyes** [comment]
gdk-pixbuf-query-loaders > /boot/system/settings/gdk-pixbuf-2.0/loaders.cache

**Comment by threedeyes** [comment]
sometimes the postinstall script is not executed. I don't know why.

**Comment by ilfelice** [comment]
Howdy,

I have a similar situation, but only with GIMP not starting (Epiphany starts just fine).

I ran the script as described byt @smallstepforman, but it made no difference.

If there is any additional info that you need to look into this, please let me know, and I will provide it.

**Comment by threedeyes** [comment]
Fixed in:
https://github.com/haikuports/haikuports/commit/c19bdbb6d253ef6f0f84ea3c49bd721f20ed9172
and
https://github.com/haikuports/haikuports/commit/2f172ea9521ce6b5bb9d334bd55afe823241e3a7
