### ISSUE TITLE
Add a recipe for swars

### ISSUE THREAD

**Issue by ed-dismantle** [haikuports/haikuports#748]
recipe and patch for swars, an open source, reverse engineered Syndicate Wars engine.

This one isn't in gentoo portage, I've had it in games-action/swars but not sure if that is the most appropriate place.
[swars_x86-0.3.patchset.txt](https://github.com/haikuports/haikuports/files/393614/swars_x86-0.3.patchset.txt)
[swars-0.3.recipe.txt](https://github.com/haikuports/haikuports/files/393615/swars-0.3.recipe.txt)

**Comment by Begasus** [comment]
Is libogg and libvorbis required? atleast I don't see any check for it when configure is running, ps, working on a recipe based on your files

**Comment by ed-dismantle** [comment]
> Is libogg and libvorbis required?
You're right! I think they were listed on the project homepage as dependencies so I added them.

> ps, working on a recipe based on your files
Hmm, what's wrong with this recipe? I think possibly the only things that can be added are a deskbar shortcut and an icon... and possibly audio ripping

**Comment by Begasus** [comment]
Most of the parts are fine, you can look at what I've been doing here:
https://github.com/Begasus/haikuports/tree/swars
I moved some of the description into a readme file that went into the $docDir and changed the description a bit according to the wiki page
As the port is a cmd there wouldn't be a need to add it to the Deskbar or create an icon for it (imho) :)

**Comment by ed-dismantle** [comment]
Ah ok, I misunderstood. Well I think it would be nice to have a shortcut eventually, as it is a game it would be easier to launch it from the deskbar.

**Comment by Begasus** [comment]
Once you have the data in place yes, if not you'd still have to launch if in Terminal :)

**Comment by Begasus** [comment]
recipe has been approved and merged into haikuporter, this can be closed?

**Comment by korli** [comment]
Closed by #754
