### ISSUE TITLE
webkit_gtk: 2.38.2-5 - crash termination issue with https://github.com

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#7490]
Using Epiphany 43.0 - getting intermittent termination (crashes) issue or "unable to display this website". Says: "page seems to be unavailable". Got it to load eventually using personal or project pages like: https://github.com/haiku - not always reliable or may get rendering issues.

* Works with Web+ and Otter Browser.

**Comment by diversys** [comment]
Should be fixed after https://github.com/haikuports/haikuports/commit/0144377a0d831c49d331237aa715995a3d82e246

**Comment by threedeyes** [comment]
> Should be fixed after [0144377](https://github.com/haikuports/haikuports/commit/0144377a0d831c49d331237aa715995a3d82e246)

No. It won't fix the problem. It is only part of the solution. I will update the webkit-gtk recipe shortly, which will fix this bug.

**Comment by kenmays** [comment]
Proposed fix: https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/7753/builds/78252.log

**Comment by kenmays** [comment]
x86 - Tested webkit_gtk-2.38.2-6 - same issue.

**Comment by kenmays** [comment]
Note: Cleared web cache. Was able to display the github pages for awhile - but when I signed in, the issues reoccurred. 
- Epiphany 43.0-2

**Comment by kenmays** [comment]
> Preferences->Privacy->Clear Website Cache -> Select All Options ->Submit

This seems to work better (as long as I didn't sign in) for Github. This was similar to an issue with Twitter (and other sites)
with a stored cache issue. Good enough for now.  Focusing on any web sign-in issues.

**Comment by kenmays** [comment]
Resolved. Github login works as well as all basic github activities when signed in.
