### ISSUE TITLE
Add nanosvg

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#750]
maybe put under media-libs/ ?
This looks like the current repo: https://github.com/memononen/nanosvg
It will be an optional lib for newer versions of some tux4kids apps.

**Comment by threedeyes** [comment]
2016-08-04 3:46 GMT+10:00 Scott McCreary <notifications@github.com>:

> maybe put under media-libs/ ?
> This looks like the current repo: https://github.com/memononen/nanosvg
> It will be an optional lib for newer versions of some tux4kids apps.
>
It will be very cool. My NanoSVG Translator
<https://github.com/threedeyes/NanoSVGTranslator> used nanosvg headers also.

**Comment by scottmc** [comment]
Nice.  We should get a recipe added for the translator as well.

**Comment by threedeyes** [comment]
2016-08-04 8:16 GMT+10:00 Scott McCreary <notifications@github.com>:

> Nice. We should get a recipe added for the translator as well.
>
To late ;)  -
https://depot.haiku-os.org/#/pkg/nanosvgtranslator/haikuports/1/0/1/-/1/x86_gcc2?bcguid=bc176-NBHA

**Comment by waddlesplash** [comment]
NanoSVG is a header file library, we can't make a recipe for it. And there already is one for NanoSVGTranslator.

**Comment by mmuman** [comment]
Well we can make a _dev package without requiring a lib one...
