### ISSUE TITLE
Blender3 doesn't pull in ffmpeg_avdevice automatically (trivial)

### ISSUE THREAD

**Issue by kquote03** [haikuports/haikuports#7509]
It seems that the blender3 package doesn't have ffmpeg_avdevice as one of its dependencies. Launching it after immediately installing results in 

```
runtime_loader: Cannot open file libavdevice.so.58 (needed by /boot/system/apps/Blender3/Blender): No such file or directory
```

However after installing ffmpeg_avdevice it works

**Comment by korli** [comment]
should be fixed in cf84eed4ae4546d8f82455af9fe8f32697afe251
