### ISSUE TITLE
Epiphany ( Web) does not launch on x86_64

### ISSUE THREAD

**Issue by bbjimmy** [haikuports/haikuports#7518]
hrev56627 epiphany-43.0-2-x86_64.hpkg error from Terminal:  
![screenshot1](https://user-images.githubusercontent.com/6108954/205504290-4b4fceb1-05a4-4468-9511-293bd2bac7b3.png)

post-install script output from Terminal:

![screenshot2](https://user-images.githubusercontent.com/6108954/205504335-6df1c64b-56f8-418f-b492-6db8f1445417.png)

**Comment by diversys** [comment]
Try this:
```
rm -rf /boot/system/non-packaged/data/mime
rm -rf /boot/home/config/non-packaged/data/mime
gdk-pixbuf-query-loaders >/boot/system/settings/gdk-pixbuf-2.0/loaders.cache
```

**Comment by bbjimmy** [comment]
That allows it to launch.
Whatever went wrong with the install needs to be fixed.
