### ISSUE TITLE
Missing dependency for libxext_devel

### ISSUE THREAD

**Issue by kwyxz** [haikuports/haikuports#7557]
It looks like the libxext_devel package is broken due to a missing dependency:

```
~> pkgman install libxext_devel
100% repochecksum-1 [65 bytes]
Validating checksum for Haiku...done.
100% repochecksum-1 [64 bytes]
Validating checksum for HaikuPorts...done.
Encountered problems:
problem 1: nothing provides devel:libx11_xcb>=1.0.0 needed by libxext_devel-1.3.4-2
  solution 1:
    - do not install "providing libxext_devel"
Please select a solution, skip the problem for now or quit.
select [1/s/q]: 
```

Not sure how to solve this myself, so if someone feels up to the challenge... thanks!

**Comment by waddlesplash** [comment]
`libXext` needs a real X11 server and client libraries. We currently do not provide those on purpose, instead `xlibe` is provided (which has a stub version of `Xext` included.)

**Comment by waddlesplash** [comment]
(If for some reason you need or wish to experiment with a "real" X11 server instead of the Xlibe compatibility layer you can make  the necessary modifications to the `libx11` recipe, and then `libXext` will work.)

**Comment by kwyxz** [comment]
I am looking into porting Snes9X to maybe package it for #6349 and it requires X11 to build, even though SDL could be used for video. It is just a little experiment for now and I stumbled upon this dependency thing. As you mentioned, `xlibe` did the trick. Thanks!
