### ISSUE TITLE
Epiphany: < key does not work

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#7593]
The extra key on european keyboards (<> usually, placed next to left shift) is not usable in Epiphany. It does not type anything.

**Comment by threedeyes** [comment]
I think it's here - https://github.com/X547/wayland-server/issues

**Comment by pulkomandy** [comment]
AltGr key also does not work (it is needed to type some characters on my keyboard layout)

**Comment by khallebal** [comment]
The numerical keypad either doesn't work, although it does work when holding down the Shift key while typing which is obviously wrong.
