### ISSUE TITLE
libuuid conflicts again

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#7600]
We still have two conflicting providers for libuuid.

I get this problem when trying to build zsh:

problem 1: package libuuid-1.3.1-4 conflicts with util_linux provided by util_linux-2.34-1
  solution 1:
    - allow deinstallation of libuuid-1.3.1-4
    - allow deinstallation of appstream_glib-0.8.1-3
    - allow deinstallation of librsvg-2.50.7-3
    - allow deinstallation of epiphany-43.0-5
    - allow deinstallation of gtk3-3.24.34-6
    - allow deinstallation of libdazzle-3.44.0-3
    - allow deinstallation of gcr-3.41.1-3
    - allow deinstallation of libportal-0.6-2
    - allow deinstallation of webkit_gtk-2.39.3-2
    - allow deinstallation of libhandy-1.6.3-4
  solution 2:
    - do not install "providing cmd:col"

**Comment by korli** [comment]
It's not a problem per se, because the builder obviously found a solution. Please try to build util_linux locally, it will land in the packages directory, will probably be available for haikuporter.

**Comment by pulkomandy** [comment]
The builder didn't need the libuuid package.
Right now util-linux and libuuid packages can't be installed at the same time, and pkgman does not want to uninstall libuuid to install util_linux.

So, yes, the builder has a solution, but as soon as you have libuuid installed, you can't have util-linux.

**Comment by korli** [comment]
as I said you can install util_linux in the haikuports packages directory, and it will be picked up by haikuporter. No need to install every package locally.

**Comment by pulkomandy** [comment]
When I build packages, it's because I need them and I want to install them locally. Currently cmd:col (and rename, nologin, hexdump, …) is not installable side by side with anything that depends on libuuid.

I will fix it in my own way and fix libuuid package so I can at least install these commands…

**Comment by korli** [comment]
BTW building zsh shouldn't require cmd:col anyway. Might be an idea to check.
