### ISSUE TITLE
sshd AuthorizedKeysCommand doesn't like our virtual root

### ISSUE THREAD

**Issue by kallisti5** [haikuports/haikuports#7619]
Working on getting sshd working on Google Cloud Platform.

sshd's "AuthorizedKeysCommand" doesn't like our virtual root for security reasons...

```
AUTH 'sshd'[423]: error: Unsafe AuthorizedKeysCommand "/bin/google_authorized_keys": bad ownership or modes for directory /
Last message repeated 1 time
```

We likely need to detect Haiku and relax those restrictions a little.  For full context...

```
~> ls -la /
drwxrwxrwx 1 user root    0 Dec 23 20:08 .
lrwxrwxrwx 1 user root   16 Dec 23 20:08 bin -> /boot/system/bin
.
.
dr-xr-xr-x 1 user root       0 Dec 17 07:18 bin
.
.
-r-xr-xr-x 1 user root 2148096 Dec 16 01:53 google_authorized_keys
```

**Comment by kallisti5** [comment]
Looks like NixOS had a similar issue:   https://github.com/NixOS/nixpkgs/issues/94653

**Comment by kallisti5** [comment]
The issue is around here:
```
https://github.com/openssh/openssh-portable/blob/master/misc.c#L2633
```

It looks like any safety checks for sshd subprocesses is going to fail with our virtual ```/``` filesystem.  This likely includes things like sftp.

**Comment by kallisti5** [comment]
haha.. https://github.com/openssh/openssh-portable/blob/master/misc.c#L2168

>  XXX Should any specific check be done for sym links ?

... yes.

**Comment by kallisti5** [comment]
Haiku:
```
/> stat /
  File: /
  Size: 0         	Blocks: 0          IO Block: 65536  directory
Device: 0,1	Inode: 1           Links: 1
Access: (0777/drwxrwxrwx)  Uid: (    0/    user)   Gid: (    0/    root)
Access: 2022-12-23 20:37:06.000000000 +0000
Modify: 2022-12-23 20:08:36.212680000 +0000
Change: 2022-12-23 20:08:36.212680000 +0000
 Birth: 2022-12-23 20:08:35.089135000 +0000
```


Linux:
```
stat /
  File: /
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 259,3	Inode: 2           Links: 22
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-12-23 13:21:28.954251750 -0600
Modify: 2022-10-25 20:29:18.867904687 -0500
Change: 2022-10-25 20:29:18.867904687 -0500
 Birth: 2020-09-25 09:54:10.000000000 -0500
```

**Comment by kallisti5** [comment]
@waddlesplash pointed out our / is 777.  maybe we want 755 instead?
https://xref.landonf.org/source/xref/haiku/src/system/kernel/fs/rootfs.cpp#404

**Comment by pulkomandy** [comment]
I think this is fixed in Haiku side with https://cgit.haiku-os.org/haiku/commit/?id=1f846c9cc5f5f7e8c9f759a9e587f109e198dc43 ?

**Comment by korli** [comment]
correct
