### ISSUE TITLE
freeciv 2.5.5 build fails, unhandled argument in libjpeg

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#763]
CCLD     libfcgui-sdl.la
copying selected object files to avoid basename conflicts...
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt1-lapi.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lapi.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt2-lauxlib.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lauxlib.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt3-lbaselib.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lbaselib.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt4-lbitlib.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lbitlib.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt5-lcode.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lcode.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt6-lcorolib.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lcorolib.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt7-lctype.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lctype.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt8-ldblib.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/ldblib.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt9-ldebug.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/ldebug.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt10-ldo.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/ldo.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt11-ldump.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/ldump.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt12-lfunc.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lfunc.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt13-lgc.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lgc.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt14-linit.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/linit.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt15-liolib.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/liolib.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt16-llex.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/llex.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt17-lmathlib.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lmathlib.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt18-lmem.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lmem.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt19-loadlib.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/loadlib.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt20-lobject.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lobject.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt21-lopcodes.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lopcodes.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt22-loslib.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/loslib.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt23-lparser.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lparser.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt24-lstate.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lstate.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt25-lstring.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lstring.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt26-lstrlib.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lstrlib.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt27-ltable.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/ltable.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt28-ltablib.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/ltablib.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt29-ltm.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/ltm.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt30-lundump.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lundump.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt31-lvm.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lvm.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt32-lzio.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/lzio.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt33-tolua_event.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/tolua_event.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt34-tolua_is.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/tolua_is.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt35-tolua_map.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/tolua_map.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt36-tolua_push.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/tolua_push.o': Operation not supported
ln: failed to create hard link '.libs/libfcgui-sdl.lax/lt37-tolua_to.o' => '.libs/libfcgui-sdl.lax/libscripting_client.a/tolua_to.o': Operation not supported
  CC       dummy.o
  CCLD     freeciv-sdl
libtool: link: cannot find the library `/packages/jpeg_x86-9-3/.self/develop/lib/x86/libjpeg.la' or unhandled argument `/packages/jpeg_x86-9-3/.self/develop/lib/x86/libjpeg.la'
Makefile:1313: recipe for target 'freeciv-sdl' failed
make[3]: *** [freeciv-sdl] Error 1

**Comment by korli** [comment]
Please grep "libjpeg.la" in /system/develop/lib/x86/*.la. When nothing, please check your Haikuports local packages folder.

**Comment by Begasus** [comment]
Thanks for the help earlier on IRC, it worked (after rebuilding some of the SDL libs, now running into "nothing provides" for sdl_gfx" ... wip

**Comment by Begasus** [comment]
Don't know if it really is something with sdl_gfx but when I changed the compat to ">=2" it worked (after rebuilding sdl_gfx)
	lib:libSDL_gfx$secondaryArchSuffix = 15.9.1 compat >= 2

**Comment by Begasus** [comment]
This one can be closed, just needed to rebuild the sdl libs ... freeciv is working fine :) (thanks to Jerome for the pointers on IRC)!
