### ISSUE TITLE
fontforge requires libreadline.so.7 but doesn't declare it

### ISSUE THREAD

**Issue by jmairboeck** [haikuports/haikuports#7676]
I am currently in the process of updating the Lilypond recipe to 2.24.0, which requires cmd:fontforge to build.

However, the current version of fontforge doesn't run without requiring lib:libreadline = 7 explicitly. The activated packages in Haikuporter now contain both `readline` (version 8) and `readline7`.

It seems that fontforge needs a rebuild against libreadline 8 (or libedit?) or declare that it needs libreadline 7 specifically.

**Comment by pulkomandy** [comment]
Switching to libedit would be best if possible. The API is mostly compatible, but often some buildsystem patching is needed.

**Comment by jmairboeck** [comment]
This was fixed with the fontforge updates (#8239).
