### ISSUE TITLE
youtube_dl requires rebuild 

### ISSUE THREAD

**Issue by Vidrep** [haikuports/haikuports#7677]
![screenshot1](https://user-images.githubusercontent.com/13264393/209717025-75c2b7d2-4396-4bd4-b5ca-a6290efc7afd.png)
![screenshot2](https://user-images.githubusercontent.com/13264393/209717048-87621293-803f-4c43-8841-e717624a820e.png)
 Building package locally works OK. Python 3.9?

**Comment by Begasus** [comment]
This is working for me, did you update your system packages, I've got python3.7 version 3.7.14 installed?

**Comment by Begasus** [comment]
Could you re-check, should be fixed in https://github.com/haikuports/haikuports/pull/7682

**Comment by Vidrep** [comment]
Working again
