### ISSUE TITLE
QMPlay2 unusably huge

### ISSUE THREAD

**Issue by nephele-gh** [haikuports/haikuports#7727]
I am not sure when this happened, qmplay2 now has a huge window, too big for my laptop screen.
All controls are scaled up way too big, as is the text. 
My text is only marginally bigger than the default, the Haiku standard apps all have usable control sizes.

![screenshot12](https://user-images.githubusercontent.com/105942296/210679605-1f8f26e0-5b34-4d3b-842a-763ad742bfca.png)

**Comment by threedeyes** [comment]
Update packages and try again.
