### ISSUE TITLE
vmware-addons fails because 'vmware' dependency is missing.

### ISSUE THREAD

**Issue by memecode** [haikuports/haikuports#7738]
> ./haikuporter --get-dependencies -j3 vmware-addons
....
Error: vmware not found in repository

I don't see any reference to 'vmware' in the recipe file. Can someone point me in the right direction?

**Comment by augiedoggie** [comment]
The package name is vmware_addons.

From the [wiki](https://github.com/haikuports/haikuports/wiki/HaikuPorter-Guidelines#general-tips): 'Recipes name must be lower-case and the package name must not contain dashes (-), but use underscores (_) instead'

**Comment by memecode** [comment]
Thanks. I wonder if really haikuporter could print a better error message in this case?

**Comment by augiedoggie** [comment]
The dash is used to specify a version to build(like haikuporter vmware_addons-X.Y.Z).  It would probably get tricky trying to figure out when to replace the dash or not if the project has some strange non-numeric versioning scheme.  I don't recall why it was originally done this way.
