### ISSUE TITLE
split r header to r_devel maybe is not a good idea

### ISSUE THREAD

**Issue by armgong** [haikuports/haikuports#7750]
split r header to r_devel Maybe is not good idea. Most r user will install r packages when using R, if  package contains c or fortran code, the installation will failed if r_devel not installed.  Could we include r header and lib to r pacakge?

**Comment by Begasus** [comment]
It isn't that hard, had a talk about this with someone on IRC and he told me the headers are not really needed at runtime. Could you give an example for this?

**Comment by armgong** [comment]
just exmaple, after installed R(r_devel not installed ) in R console  run 
~~~r
install.packages("curl")
~~~
this will failed , because curl package (https://github.com/jeroen/curl) contains c source code , which need R headers and libs to compile.
btw, lots of R packages contain c/fortran codes, if no R header files ,these packages can't build and installed. Futhermore most R user will install quite a few  packages when he/she use R, no R header and lib will make install packages not so handy.

**Comment by armgong** [comment]
on debian linux , it indeed split R to base and base-dev, but debian also build lots of  cran r package for user to installed.
~~~bash
apt-cache search "^r-.*" | sort
~~~ 
so on debian when user install an R package , he/she can choose install pre-build package use APT , instead of R install.packages() command. 
but on haiku-os or haikuports, maybe we should not pre-build a lot of R package then use pkgman install r-*** , let user himself to build package use install.packages().

**Comment by armgong** [comment]
yeah , IMO when use R ,installing packages that need compiling usually  unavoidable for R users.
for the curl package demo, it is just an example, just an example. 
many frequently used packages , need header and libs to compile and install

**Comment by Begasus** [comment]
OK, I'm still not against it, one point I'd like to make, you can rund SDL games on Haiku with all the work that has been done here (runtime dependencies), if you like to create something that relies on SDL you would need the headers that are stored in the devel package (as it has been for many years and still valid), it doesn't make much change to put all this in in "one" package only, but the idea is to have a runtime dependency and a build dependency ?

**Comment by armgong** [comment]
IMHO,  SDL itself is a library(runtime and dev dependency ) ,people write application base on it . but   R is data analysis tool for most user , install an R packages is extend R function like python package(haikuports have lots python-* packages,but none R packages), so it better no split. so haikuport will not need prebuild lots of r package like python?

**Comment by Begasus** [comment]
Doing a local build atm with all included in one package, will give you a heads up when things are fine and ready to be merged, thanks on the feedback.

**Comment by Begasus** [comment]
Should be fixed in https://github.com/haikuports/haikuports/pull/7755

Could you give a notice if that one is working for you? (build on 64bit buildmaster finished, 32bit about to finish, so you can update in a short while).

**Comment by armgong** [comment]
uninstall and re-install R , install.packages work smoothly , thank you very much.
