### ISSUE TITLE
cannot install boost163 without icu57

### ISSUE THREAD

**Issue by iam-git** [haikuports/haikuports#7753]
It appears that some packages (for example, vcmi) cannot be installed on a clean system. It looks like boost163 just need to rebuild.

**Comment by Begasus** [comment]
Or vcmi rebuild against a newer version of boost? Think it's time (where possible) to drop the older boost versions.

**Comment by iam-git** [comment]
In this case I just provided feedback of another user while I am not personally interested in vcmi. Just letting you know that repository is in an inconsistent state.

**Comment by Begasus** [comment]
Thanks, if I get around to it (or someone else), we'll look into the issue.

**Comment by pulkomandy** [comment]
I have updated vcmi.

How can we check if anything else uses the older boost versions?

**Comment by pulkomandy** [comment]
We need to delete the old boost versions. I wanted to do the rebuilds first and then remove them when they are not needed anymore.

I'm confused about vcmi because I rebuilt it and confirmed locally that it needs only boost 1.69, so that should be already solved.

**Comment by robxnano** [comment]
So #7899 fixed the build problem. For future reference, the cause was that there were multiple separate devel:libboost_* entries, but only one of them had the minimum version specified. Once all of them had the same minimum version, the build was successful.

**Comment by Begasus** [comment]
First 3 of the older boost versions have been removed, if something is still using them they will show up sooner or later.

**Comment by korli** [comment]
can this be closed?
