### ISSUE TITLE
Falkon 3.2.0-4 fails to start

### ISSUE THREAD

**Issue by Glog78** [haikuports/haikuports#7766]
Falkon doesn't start with error message -> Missing libraries libevent-2.1.so.6

**Comment by Begasus** [comment]
It's related to the update on libevent, I'll try to  build a revbump for the webengine this weeks to see if this solves the issue.

**Comment by Begasus** [comment]
yes (imho) but I'm not the expert, doing a rebuild for qtwebengine here (should probably take a while as mentioned in the recipe

**Comment by korli** [comment]
IMO we should keep compatibility libs available, instead of breaking things like this.

**Comment by Begasus** [comment]
> IMO we should keep compatibility libs available, instead of breaking things like this.

Granted, did a quick check with creating the symlink, this indeed works, but maybe enable the previous recipe for a compatible package?

**Comment by Begasus** [comment]
Added the libevent21 back without the develop package, checked on 64bit and Falkon and Dooble launch fine with this change.

**Comment by Begasus** [comment]
Could you update and check @Glog78 ? Should be fixed with recent changes (checked here and things are fine on my side).

**Comment by Glog78** [comment]
fixed after i did the update. Thanks alot 

![image](https://user-images.githubusercontent.com/7598856/212468330-d33ed33a-f1ef-450f-97fa-770a8b68490f.png)

**Comment by Begasus** [comment]
Thanks for reporting! 👍
