### ISSUE TITLE
vcmi 1.1.0 doesn't find boost-datetime in boost 1.70

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#7769]
It works with boost 1.69 but not 1.70. What changed in between?

**Comment by Begasus** [comment]
Changing boost version constraints to` >= 1.70.0` (for the devel:boost* lines) and adding `-DBUILD_SHARED_LIBS=ON` to cmake cmd finds the boost requirements (checked on a 64bit install). Maybe somehow related to the removal of the static libraries, but then it would also complain for boost169?

**Comment by korli** [comment]
FWIW Arch Linux builds Boost with static and shared libs.

**Comment by pulkomandy** [comment]
Building it with shared libs finds boost, but it fails later at the end of the build with an undefined reference error (to boost::detail::set_tss_data). So it fixes only half the issue.

I guess boost 1.70 is too new for VCMI and newer VCMI releases might fix the problem.

**Comment by korli** [comment]
should be fixed in 46df7a950603cb360f2f32a9f1ffa170abb22a53
