### ISSUE TITLE
libiconv is built/shipped without cp437

### ISSUE THREAD

**Issue by mywave82** [haikuports/haikuports#7781]
iconv cp437 being available is essential for opencubicplayer to operate, since it is used to translate text from DOS-era files into modern UTF-8.

I'm certain it was available before.

**Comment by korli** [comment]
When was it working? you can check the history: https://github.com/haikuports/haikuports/commits/master/dev-libs/libiconv
You can eventually build older recipes and try the built libiconv by using the LIBRARY_PATH variable when launching openucubicplayer.

**Comment by mywave82** [comment]
If it worked, it was back in 2020

**Comment by mywave82** [comment]
(random guess is that configure might need the --enable-extra-encodings  option, not at system at the moment)
