### ISSUE TITLE
It seems BUILD() script is not called in my new recipe for libQt4Pas. 

### ISSUE THREAD

**Issue by oco27** [haikuports/haikuports#781]
Once again, i am trying to make packages for Lazarus. I am starting to build de Freepascal binding around Qt first, which should be easy as it compiled out of the box on x86 arch when Qt is installed (http://users.telenet.be/Jan.Van.hijfte/qtforfpc/fpcqt4.html).

But i am unable to generate a correct package. It seems the build section is not called and the generated package is empty. I have tried many options without success. Maybe the SOURCE_DIR variable required to extract sources from the original package is a problem but i can't figure why.

Maybe someone with more package experience can help me point out the problem...

I have attached my current recipe.

[libQt4Pas-2.5.0.recipe.txt](https://github.com/haikuports/haikuports/files/439684/libQt4Pas-2.5.0.recipe.txt)

**Comment by diversys** [comment]
SOURCE_DIR is not a problem. The problem is that generated Makefile has wrong install paths:

```
Collecting files to be packaged ...
cp -f "libQt4Pas.so.5.2.5" "/packages/libqt4_x86-4.8.7-5/.self/lib/x86/libQt4Pas.so.5.2.5"
cp: cannot create regular file '/packages/libqt4_x86-4.8.7-5/.self/lib/x86/libQt4Pas.so.5.2.5': Read-only file system
Makefile:1695: recipe for target 'install_target' failed
```

**Comment by oco27** [comment]
Finally got it working at BeGeistert 030 with hints from PulkoMandy : it was a matter of uppercase letters in the recipe name. Everything should be in lowercase.
Corresponding proposed pull request is here : https://github.com/haikuports/haikuports/pull/871
