### ISSUE TITLE
lilypond build failed because of fontconfig

### ISSUE THREAD

**Issue by jmairboeck** [haikuports/haikuports#7815]
The x86_64 build of lilypond [failed](https://build.haiku-os.org/buildmaster/master/x86_64/?buildrunDir=8046&viewMode=expanded) because of missing fontconfig config files.

Either haikuporter is older than this commit: https://github.com/haikuports/haikuporter/commit/4acf4899fe1442f04bc94ad4c430d1e2090e8592, or fontconfig needs to be installed on the host for that change to actually work, and it isn't.

**Edit:** this will probably also affect the x86 (32 bit) build, once #7811 is merged and the texinfo problem is fixed.

**Comment by korli** [comment]
@mmlr do we have means to check the builder haikuporter version and the local list of packages?

**Comment by jmairboeck** [comment]
The x86_64 build of lilypond worked now, so this is fixed apparently. Thanks @waddlesplash!

(the x86 build is still broken but that should hopefully be fixed by #7888)
