### ISSUE TITLE
gettext_devel: missing libs / broken links

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#7817]
(this is on beta4, 64 bits)

Just noticed that after `pkgman -i devel:libgettextlib` (which installs `gettext_devel`), two broken links appear under `/boot/system/develop/lib`:

- `libgettextlib.so` (points to a non-existent `libgettextlib-0.21.1.so`)
- `libgettextsrc.so` (points to a non-existent `libgettextsrc-0.21.1.so`)

Looking around, I've noticed that fab78934996e2e75e9a7440a78931706977fa496 changed how those two particular libs are handled by `prepareInstalledDevelLib`:

before:
```sh
	prepareInstalledDevelLib libgettextlib '*.so' '*'
	prepareInstalledDevelLib libgettextsrc '*.so' '*
```

after:
```sh
	prepareInstalledDevelLibs \
		[...]
		libgettextlib \
		libgettextsrc \
		[...]
```

Could that be the cause of the missing-libs / broken-links?

Maybe they required to be "special-cased" due to their name pattern (`lib<name>-<version>.so`)?

Paging @waddlesplash, hope that's OK.

Edit: seems that creating links for those libraries, from `system/lib/` to `{/system,~/config}/non-packaged/develop/libs`, do not work as an override :-(

**Comment by waddlesplash** [comment]
It's possible I missed some libraries in that list, yes. That should be fixed.
