### ISSUE TITLE
Buildmaster issues

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#7887]
The last merges haven't been properly build on buildmaster, buildmaster seems to be reconnecting the whole time, packages build(?) don't end up in the depot, it's no use at this moment to merge anything new?

**Comment by waddlesplash** [comment]
Don't worry about merging new things, eventually once buildmaster is fixed it will just catch up.

**Comment by waddlesplash** [comment]
I have made a proper fix in https://github.com/haikuports/haikuporter/commit/99d801b595ab01acc7dbdb6658b120ba3f9f2c18 but this needs to be applied on the server-side by @kallisti5 updating the docker containers. In the meantime I applied a hot-patch to the builders themselves, and it seems to be working. I triggered a new build.

Let's leave this open until the real fix is applied and the hot-fix can be removed.

**Comment by korli** [comment]
ATM the x86 builder is lost
