### ISSUE TITLE
Create recipe for `sock`

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#7889]
http://www.icir.org/christian/sock.html

It's currently in the Haiku tree, check there if it needs patching: https://xref.landonf.org/source/xref/haiku/src/tests/system/network/sock

**Comment by waddlesplash** [comment]
cc @Begasus

**Comment by Begasus** [comment]
Upstream builds without patching, no idea how to test though (no test case provided).
Haven't build Haiku (or internal parts of it yet) for a long time, so no idea how to test there or create a recipe from the source in the Haiku tree, the upsteam should be fine to create a recipe though.

**Comment by Begasus** [comment]
PR created at: https://github.com/haikuports/haikuports/pull/7938
You should be able to build on any architecture and test it. :)
