### ISSUE TITLE
Epiphany - copy and paste CJK characters from application to clipboard/text editor issue

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#7890]
Test: Copy CJK text from Epiphany web browser to Pe text editor in Haiku.
Result: FAILED - Displays Unicode character hex encodings in Pe (versus actual characters).

Note: 
1. Test passed successfully when using Web+ and Pe. 
2. Copying CJK text from clipboard/Pe text editor and pasting within Epiphany - test passed.

Tested on hrev56792 x86 with Epiphany 43.0-6 and Pe 2.4.5-10.

**Comment by humdingerb** [comment]
Reported here: https://github.com/X547/wayland-server/issues/5
