### ISSUE TITLE
Port Request: ddnet

### ISSUE THREAD

**Issue by n0toose** [haikuports/haikuports#7914]
A while back, some effort was made to support https://ddnet.org (multiplayer game based on Teeworlds) using the Teeworlds patches and a lot of work by myself and maintainers:

I linked all PRs containing the word "Haiku" below:

- https://github.com/ddnet/ddnet/pull/2986
- https://github.com/ddnet/ddnet/pull/3779
- https://github.com/ddnet/ddnet/pull/3782
- https://github.com/ddnet/ddnet/pull/3783
- https://github.com/ddnet/ddnet/pull/3913
- https://github.com/ddnet/ddnet/pull/6295

Unfortunately, as a result of time constraints, I never really got around to making the recipe and ultimately making ddnet available through HaikuDepot and also forgot to make this issue.

I think I temporarily dropped some of the work because I was waiting for the then-most recent port of Mesa to reach end users' systems (https://github.com/haikuports/haikuports/issues/5838) at the time. There's a chance that the port is not 100% compatible or complete anymore, as some time has definitely passed ever since I worked on this.

It would be great if someone else got around to pushing this to the finish line, as I've already dealt with most of the work already. The maintainer of ddnet is also absolutely delightful to work with and would probably be open to further PRs, so I'd advise not maintaining a downstream port and pushing the changes to master.

**Comment by n0toose** [comment]
Since ddnet is a fork of Teeworlds, one can probably use the recipe we have for Teeworlds as a base.

**Comment by n0toose** [comment]
After this is merged, we'll really just need a recipe: https://github.com/ddnet/ddnet/pull/6395

**Comment by korli** [comment]
@n0toose is the issue with https://github.com/haikuports/haikuports/issues/5838) now fixed for Teeworlds?

**Comment by n0toose** [comment]
They use essentially the same base, I haven't tested it myself but I'd definitely assume that this issue is now fixed. Some additional stability issues regarding how the game draws into the BRect should probably be investigated -- I sometimes got a fully white screen in ddnet, but it's now gone for some reason.
