### ISSUE TITLE
gertty-1.6.0-6: x86 (GCC2) build failure

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#7953]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=3832
resolving build dependencies failed: requires "sqlalchemy_python310" of package "gertty_python310-1.6.0" could not be resolved

**Comment by kenmays** [comment]
Resolved.

**Comment by Begasus** [comment]
sqlalchemy should be solved in https://github.com/haikuports/haikuports/pull/7955 (and thus this issue too).

**Comment by Begasus** [comment]
Fixed in: https://github.com/haikuports/haikuports/pull/7959

**Comment by kenmays** [comment]
https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=3874&viewMode=expanded
