### ISSUE TITLE
jansson 2.12 missing .pc file for pkgconfig

### ISSUE THREAD

**Issue by eblanca** [haikuports/haikuports#8056]
Title explains the issue, usual installation of jansson provides a .pc file for pkgconfig (on linux it does), but I see this is missing into hpkg for 2.12
I find many of them into /boot/system/develop/lib/pkgconfig but nothing jansson related.
This happens on haiku 64 bit, instead on haiku 32 bit the .pc file appears as expected.

**Comment by augiedoggie** [comment]
Do you have `jansson_devel` installed?  That's the package the contains the pkg-config file.

**Comment by eblanca** [comment]
Oh! This is fair!
You're right, sorry for the noise.
