### ISSUE TITLE
python packages: improve secondaryArch provides

### ISSUE THREAD

**Issue by jmairboeck** [haikuports/haikuports#8106]
There are a few architecture specific python packages, which contain an additional `PROVIDES` on x86_gcc2 without the x86 suffix, e.g.

https://github.com/haikuports/haikuports/blob/92975803ce6caaf709acc2615aa36d1c5950738d/dev-python/dulwich/dulwich-0.20.32.recipe#L42-L46

The condition there could be generalized as `if [ -n "$secondaryArchSuffix" ]` so that this also works if we have more than one secondaryArch in the future.

(As long as there is only `x86` on `x86_gcc2` it doesn't really matter.)

**Comment by korli** [comment]
gcc2 is the exception here, any other primary arch should be able to build arch specific python packages.

**Comment by jmairboeck** [comment]
You are right, there is (probably) no need to provide the aliases for e.g. a 32 bit build of a package on x86_64 because the package can be built natively instead.
