### ISSUE TITLE
Sigil: crash on close

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#8111]
App starts, seems to be fine, but on close produces the following crash report (beta4, 32 bits):
[Sigil-23424-debug-24-03-2023-06-49-25.report.txt](https://github.com/haikuports/haikuports/files/11070565/Sigil-23424-debug-24-03-2023-06-49-25.report.txt)

**Comment by Begasus** [comment]
Thanks! Confirmed here.
