### ISSUE TITLE
Qt6: pkg-config files in wrong folder

### ISSUE THREAD

**Issue by robxnano** [haikuports/haikuports#8197]
All the qt6 .pc files are installed in /boot/system/lib/pkgconfig instead of /boot/system/develop/lib/pkgconfig. The recipes are all missing `fixPkgconfig`, probably because the initial release of qt6 didn't include the .pc files.

Affected packages:

- [x] qt6_3d
- [x] qt6_5compat
- [x] qt6_base
- [x] qt6_charts
- [x] qt6_connectivity
- [x] qt6_datavis3d
- [x] qt6_declarative
- [x] qt6_multimedia
- [x] qt6_networkauth
- [x] qt6_positioning
- [x] qt6_quick3d
- [x] qt6_quicktimeline
- [x] qt6_scxml
- [x] qt6_sensors
- [x] qt6_serialport
- [x] qt6_shadertools
- [x] qt6_svg
- [x] qt6_tools
- [x] qt6_webchannel
- [x] qt6_websockets

**Comment by threedeyes** [comment]
Please don't do anything about this problem yet. I am preparing an update of Qt6 to version 6.5.0 and will fix this problem at the same time.

**Comment by Begasus** [comment]
@threedeyes while you are at it, I see lots of Qt(5 and 6) and K* config files in $libDir instead of moved to $developLibDir. ;)

**Comment by waddlesplash** [comment]
@threedeyes could https://github.com/threedeyes/qt6-haikuplugins/issues/1 be done at the same time?

**Comment by threedeyes** [comment]
> @threedeyes could [threedeyes/qt6-haikuplugins#1](https://github.com/threedeyes/qt6-haikuplugins/issues/1) be done at the same time?

I tried this patch and got a lot of problems with font size in different applications. The font size has a non-linear relationship with the system settings.

**Comment by waddlesplash** [comment]
That seems strange ... the scaling factor should just be applied based on system settings consistently. Perhaps the individual applications were choosing to behave differently? It's worth noting that Qt applications don't often handle "fractional" scaling well even on Windows 10.

**Comment by threedeyes** [comment]
After merging the changes with qthaikuplugins for Qt5, there were many applications with windows that did not fit in the screen, had disproportionate font sizes. An example of this bug is https://github.com/haikuports/haikuports/issues/7727

**Comment by waddlesplash** [comment]
It looks like scaling is being applied twice: first from the "scale factor", I guess, and then the system font sizes of 18 are being scaled too.

**Comment by waddlesplash** [comment]
So I guess the question is how Qt6 decides on font sizes, maybe there is some difference there where my code to adjust them does not work properly.

**Comment by threedeyes** [comment]
Regardless of Qt5 or Qt6, the behavior of your code is the same. It feels like there is double scaling, through the scaling factor and through the font size at the same time.

**Comment by waddlesplash** [comment]
Hmm, I didn't see this with Qt5. I will have to check with QMPlay, I guess. Know any other applications with this problem?

**Comment by threedeyes** [comment]
> Hmm, I didn't see this with Qt5. I will have to check with QMPlay, I guess. Know any other applications with this problem?

At the moment the double scaling in Qt5 is not observed because I basically disabled your patch by setting an environment variable - setenv("QT_AUTO_SCREEN_SCALE_FACTOR", "0", 0); 
https://github.com/threedeyes/qthaikuplugins/commit/1f1af1b23a0a01632974a16190cc7a09f98257f6

I don't remember which applications it was in since I tested it in January, but I'll try to find it.
