### ISSUE TITLE
SDL2: cannot work with CMake

### ISSUE THREAD

**Issue by carlo-bramini** [haikuports/haikuports#8275]
I updated my packages with HaikuDepot application.
The process updated SDL2 from 2.0.20 to 2.26.4-2 and I discovered that the development package doesn't work anymore with CMake.
Running a simple script prints this message on the console:

```
CMake Error at /boot/system/lib/cmake/SDL2/SDL2mainTargets.cmake:80 (message):
  The imported target "SDL2::SDL2main" references the file

     "/boot/system/lib/libSDL2main.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/boot/system/lib/cmake/SDL2/SDL2mainTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /boot/system/lib/cmake/SDL2/SDL2Config.cmake:49 (include)
  CMakeLists.txt:18 (find_package)
```

Actually, CMake is right because I have found that static library installed here:

```
/boot/system/develop/lib/libSDL2main.a
```

Manually fixing the issue by making a link to `/boot/system/lib/libSDL2main.a` didn't work because it prints that the filesystem is read-only, but I think that there is something else to do.

**Comment by korli** [comment]
Can you point at an impacted haiku ports package?
