### ISSUE TITLE
cmake config files in the wrong package

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#8300]
I still see a lot of packages leaving their cmake configuration files behind in $libDir, as they are intended to be used in development stage they should be moved to the devel package ~~($developLibDir)~~ $libDir/cmake, like:

```
packageEntries devel \
	$developDir \
	$libDir/cmake
```

**Comment by Begasus** [comment]
Related to the pkgconfig files in the wrong place: https://github.com/haikuports/haikuports/issues/8197

**Comment by jmairboeck** [comment]
There is a `fixCMake` scriptlet to probably fix that in most cases: https://github.com/haikuports/haikuporter/blob/adc25c2375d3ad59b4f1f6874abd0cd56d8a6538/HaikuPorter/ShellScriptlets.py#L494

**Comment by Begasus** [comment]
> There is a `fixCMake` scriptlet to probably fix that in most cases: https://github.com/haikuports/haikuporter/blob/adc25c2375d3ad59b4f1f6874abd0cd56d8a6538/HaikuPorter/ShellScriptlets.py#L494

This doesn't always work as expected, just tried this for: https://github.com/haikuports/haikuports/pull/8301
All I get there now is an empty $developLibDir/cmake ?

Also, some packages install their configuration files in $dataDir/cmake (those should be fine I think).

**Comment by pulkomandy** [comment]
haikuporter could have a policy check for cmake files in $libDir

> Also, some packages install their configuration files in $dataDir/cmake (those should be fine I think).

This is a problem because the same files will be used by both the gcc2 and gcc11 versions. For cmakefiles in $developLibDir, "setarch" will do the right thing, but for those in $dataDir, it won't. Only a problem if the package can be used with both gcc2 and gcc11, I think, so maybe we can ignore the issue.

**Comment by Begasus** [comment]
A good thing I think that not that many (multi arch depending) packages use the $dataDir path (if so I will keep an eye on the ones I run into now and see if they can be moved to $libDir).

**Comment by threedeyes** [comment]
There is no problem transferring pkgconfig files, but moving cmake files to developLibDir causes a lot of problems. This will require a huge number of fixes to the cmake files themselves as well as to the recipe. I don't think this is the best thing to do at this point.

**Comment by Begasus** [comment]
> There is no problem moving pkgconfig files, but moving cmake files to developLibDir causes a lot of problems

I think I need to correct myself here, the configuration files are not transfered to $developLibDir, but $libDir/cmake should be in the devel package. Will correct above statement.

**Comment by Begasus** [comment]
One I found is opencascade which stores the cmake config files in $developLibDir.

https://github.com/haikuports/haikuports/blob/49cbe61c662794ed2e42e0e41cf0c004f3e27499/sci-libs/opencascade/opencascade-7.7.1.recipe#L337

**Comment by jmairboeck** [comment]
> One I found is opencascade which stores the cmake config files in $developLibDir.
> 
> https://github.com/haikuports/haikuports/blob/49cbe61c662794ed2e42e0e41cf0c004f3e27499/sci-libs/opencascade/opencascade-7.7.1.recipe#L337

We could change that if it is desired, but I thought that `$developLibDir` is more correct, and it was rather easy in this case. Their cmake files needed patching anyway for secondaryArch support:

https://github.com/haikuports/haikuports/blob/49cbe61c662794ed2e42e0e41cf0c004f3e27499/sci-libs/opencascade/patches/opencascade-7.7.1.patchset#L30-L57

**Comment by Begasus** [comment]
> > **EDIT** or maybe something like: `$INSTALL_DIR/lib${LIB_SUFFIX}/cmake/opencascade-<version>`
> 
> `${LIB_SUFFIX}` is `64` on 64 bit Linux (which uses `lib64` as libDir). I'm not sure if it could be used as `$secondaryArchSubdir`.

I've used it a few times in the last days, `-DLIB_SUFFIX=$secondaryArchSubDir`, works fine as it will remain empty on 64bit.

**Comment by jmairboeck** [comment]
For the opencascade case this wouldn't be sufficient. What the patch does is an extra call to `get_filename_component (OpenCASCADE_INSTALL_PREFIX "${OpenCASCADE_INSTALL_PREFIX}" PATH)`, which does effectively what `..` in the shell would do, i.e. traverse up the subdirectory hierarchy. That is needed if we use `$libDir` for the cmake files. The second part of the patch (the `if` with `develop$`) could be removed in that case.

**Comment by Begasus** [comment]
Closing this one, so far only 3 (zstd, tinyxml2 and opencascade) add them in $developLibDir/cmake as intended by the recipe creators.
