### ISSUE TITLE
gitk does not find git repository

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#8322]
Starting gitk results in an error message "Cannot find a git repository here.".

**Comment by waddlesplash** [comment]
git-gui is also now basically unusable anyway since the window can't be resized without causing crashes. Previously (#6469) it would only crash "some" of the time.

**Comment by waddlesplash** [comment]
If someone who can figure out Tk internals could look into https://github.com/waddlesplash/xlibe/issues/2#issuecomment-1000941137 and figure out what is going wrong, we could get rid of the "windowed" Tk and use an Xlibe-based one instead...

**Comment by pulkomandy** [comment]
Yes, this is a recent regression, it was working a few days ago (besides the already reported problem that it needs the locale to be set to C, otherwise it crashes due to number formatting/parsing issues)

**Comment by pulkomandy** [comment]
I looked at strace and I can see a setcwd to /boot/system/bin.

Tracing this in Debugger, it comes from SDL_InitBeApp in StartBeLooper. This looks intentional in our SDL port, there is a commit saying "Change working directory to that of executable". But this is not correct. In Linux this happens only when things are run from the GUI, when they are run from Terminal, they run in the current directory, and that's what should happen for gitk.

So I'm bringing this to SDL bugtracker for further discussion https://github.com/libsdl-org/SDL/issues/7596

**Comment by korli** [comment]
> Not sure why it worked before, however, there are not a lot of very recent changes to this code?

I think StartBeLooper was added in d96a8717a6b5e3ec8cf9a130ea9ee79a110cf7cd

**Comment by korli** [comment]
Does gitk create another BApplication before SDLApplication? It could make sense to only change the working directory when creating the SDLApplication.

**Comment by pulkomandy** [comment]
SDL devs have replied that we should detect if ran from Terminal, and they do similar things on OSX.

We can do that by detecting if the TERM variable is set, for example, but are there better ways? Ryan sugested (see linked bugreport above) to look for the parent PID, I think that should work in our case as well?

**Comment by korli** [comment]
the TERM variable is the standard way. isatty doesn't work when redirecting input/output.
