### ISSUE TITLE
gitk: resizing the window immediately crashes (SDL2, Mesa)

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#8370]
- Start gitk
- Resize the BWindow using the resize handle
- Crash in BGLView::UnlockGL, call to debugger() with the message: `[!]`

**Comment by pulkomandy** [comment]
workaround:

    wish /bin/gitk -sdlfullscreen

or other options described here: https://www.androwish.org/index.html/wiki?name=Beyond+AndroWish&p . However -sdlnogl has no effect.

**Comment by waddlesplash** [comment]
Probably related to #6469.

**Comment by Begasus** [comment]
gitk still crashes here, even with "wish /bin/gitk -sdlfullscreen"

**Comment by pulkomandy** [comment]
That's the other problem tracked in #7392. You can try the workaround listed there, that is to set locale to english.

**Comment by Begasus** [comment]
Confirmed, thanks on the link, windowed started up but indeed crashes when resizing.

**Comment by infrastation** [comment]
Bug fix confirmed, thank you!
