### ISSUE TITLE
Wrong dependency libVersion for libsndfile

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#8408]

**Comment by Begasus** [comment]
- [x] twolame https://github.com/haikuports/haikuports/pull/8409

**Comment by Begasus** [comment]
The issue only rises with packages build after previous version bump for libsndfile, checked some of the others that are still OK with the latest (corrected) libVersion.

**Comment by korli** [comment]
+blender3

**Comment by Begasus** [comment]
> +blender3

Covered in https://github.com/haikuports/haikuports/pull/8456

Thought I had things covered (but using 32bit I guess this slipped through) :)

**Comment by Begasus** [comment]
Nothing popped up anymore, closing.
