### ISSUE TITLE
manpages installed in the wrong directory

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#8514]
Upon checking package bind_utils I saw that it installed the manpages in $docDir (cp -v doc/man/{dig.1,host.1,nslookup.1} $docDir)
After that looking in $manDir I see faulty directories there too (needs cleanup).

**Comment by augiedoggie** [comment]
Is this still an issue that needs to be tracked?  I haven't noticed any packages with misplaced man pages.

**Comment by Begasus** [comment]
Will do another checkup on my installed system, I guess most issues are resolved atm, if not they could still be linked here if need be, thnx for the reminder.

**Comment by Begasus** [comment]
- [ ] freerdp has manpages installed in $dataDir/man

**Comment by Begasus** [comment]
Closing, if something pops up just link it here.
