### ISSUE TITLE
Update neon to  0.30.2

### ISSUE THREAD

**Issue by scottmc** [haikuports/haikuports#853]
From the  0.30.2 neon release email:
Download: http://www.webdav.org/neon/neon-0.30.2.tar.gz
 MD5:   e28d77bf14032d7f5046b3930704ef41  neon-0.30.2.tar.gz
SHA256: db0bd8cdec329b48f53a6f00199c92d5ba40b0f015b153718d1b15d3d967fbca  neon-0.30.2.tar.gz

Changes in release 0.30.2:
* Add support for OpenSSL 1.1.x (Kurt Roeckx).
* Fix PKCS#11 support under GnuTLS 3.x.
 - PKCS#11 API no longer supported with GnuTLS 2.x

**Comment by miqlas** [comment]
Here: https://github.com/haikuports/haikuports/pull/854
