### ISSUE TITLE
Tiny-First

### ISSUE THREAD

**Issue by pentalive** [haikuports/haikuports#8588]
I have prepared the first release of tiny-first on Gitlab: https://gitlab.com/waspentalive/tiny/-/releases/First

Tiny is an RPN based language that roughly fills the same nitch as tiny basic.

It is an integer only (for now0, line numbered like BASIC, small interpreter. 
Details of the language can be found at: https://esolangs.org/wiki/Tiny

If Tiny is found worthy please create a recipe for it and add it to HaikuDepot?

**Comment by Begasus** [comment]
What version do you plan to use? (can't seem to find one on your gitlab)
