### ISSUE TITLE
LibreOffice crashing when re-opening previously saved document

### ISSUE THREAD

**Issue by ArDrakho** [haikuports/haikuports#8596]
LibreOffice crashing when you try re-open a previously saved document (i.e. odt, ods, docx, xlsx, sxw,…). However, the older file types are unaffected, such doc, xls, and rtf.

1) Creating a new document is not an issue for any file type. 
2) Creating, saving, and re-opening the same .ods / .odt document is an issue. 
3) Creating, saving, and re-opening the same .doc / .xls document is not an issue. 

This issue seems to be associated with the newer file type documents.

Version LibreOffice 7.3.3.2
OS Version: R1B4 (hrev 56578+81)

Details highlighted in discourse at https://discuss.haiku-os.org/t/libreoffice-crashes/13424/2.

**Comment by korli** [comment]
this same issue was already tracked in https://github.com/haikuports/haikuports/issues/8587 and closed after the libxmlsec rebuild. Please update the libxmlsec package.
If, after updating,  you can still reproduce the issue, please reopen and provide a syslog.
