### ISSUE TITLE
mgba (the stand alone one) disapeared from the depot for 32 bit.

### ISSUE THREAD

**Issue by AlienSoldier2** [haikuports/haikuports#8622]
The libretro (beurk) one is still there but the plain mGBA one is no longer in the list.  So software updater don't update it either.  The 64 bit one is there (0.10.2-1).  So i am stuck with my 0.9.2 one in 32bit.

**Comment by korli** [comment]
should be fixed but the qt gui crash in the file dialog. Can be run from the cmd line.
