### ISSUE TITLE
7KAA Seven Kingdoms error on startup

### ISSUE THREAD

**Issue by andimachovec** [haikuports/haikuports#8625]
Reported by forum user Polli, I'm opening the issue for him because he's not very comfortable with English. 
7kaa fails to start with the error message [File::file_open] error opening file RESOURCE/PAL_STD.RES No such file or directory. 
Happens under both 32 and 64 bit versions of Haiku, hrev is 56976.

**Comment by Briseur** [comment]
After testing on both stable and nightly 64 bits, the error occurs when the game is started from apps menu.
The file in question is present and the game starts normally when called from terminal.
