### ISSUE TITLE
Spurious Error 'ascii' codec can't decode byte in position ordinal not in range

### ISSUE THREAD

**Issue by agmsmith** [haikuports/haikuports#864]
While trying to make a new recipe for BeShare, I keep on running into a hard to debug problem where any run has the mostly useless error message of:

    Checking if any package-infos need to be updated ...
    'ascii' codec can't decode byte 0xc2 in position 50: ordinal not in range(128)

It's triggered by a particular spelling of the copyright line in a recipe:
COPYRIGHT="2000-2007 Copyright Level Control Systems"

Even if you retype it manually (rather than cut and paste) to avoid UTF-8 characters, it still happens.  Just put it in any recipe (the canonical sys-apps/which/which*.recipe for example) and HaikuPorter breaks.

Very mysterious, and annoying!

\- Alex

**Comment by humdingerb** [comment]
On 11 November 2016 at 05:33, Alexander G. M. Smith
<notifications@github.com> wrote:
> It's triggered by a particular spelling of the copyright line in a recipe:
> COPYRIGHT="2000-2007 Copyright Level Control Systems"

The error message doesn't give a hint what's wrong... :)
Remove the "Copyright" and it works.

Regards,
Humdinger

--
Did you know:
  If half the Haiku supporters at http://www.goodsearch.com
  made 10 searches a day, we could have a fulltime developer.

**Comment by humdingerb** [comment]
> It's triggered by a particular spelling of the copyright line in a recipe:
> COPYRIGHT="2000-2007 Copyright Level Control Systems"

The error message doesn't give a hint what's wrong... :)
Remove the "Copyright" and it works.

**Comment by fbrosson** [comment]
@agmsmith: In case you would like to "convert" this issue into a PR, here's what you can do:
```
curl --user agmsmith --request POST \
     --data '{"pull":"864", "head":"agmsmith:BeShare3", "base":"master", "title":"muscle3: create recipe (with version 3.20)"}' \
     https://api.github.com/repos/haikuports/haikuports/pulls
```
Of course, you can change the title to whatever suits you best.

**Comment by korli** [comment]
There is already a recipe for muscle 6.0, why the need to build muscle 3.20?

**Comment by fbrosson** [comment]
Oops, you are right. How did I miss that?!!!

**Comment by agmsmith** [comment]
That's right, muscle v6 exists but not for gcc2, and I need muscle version 3 for other compatibility reasons with BeOS.

But this seems to be a bug in HaikuPorter (that a particular wording blows it away), should I refile it as an issue in the bug tracker for HaikuPorter?

**Comment by fbrosson** [comment]
> That's right, muscle v6 exists but not for gcc2, and I need muscle version 3 for other compatibility reasons with BeOS.

Hmm, that's interesting. So I guess that if your recipe for muscle 3.20 (in net-misc/muscle3) does not conflict with that of muscle 6.0 (in net-misc/muscle) then maybe it would be nice to have it in the tree ;-)

> But this seems to be a bug in HaikuPorter (that a particular wording blows it away), should I refile it as an issue in the bug tracker for HaikuPorter?

Well, I wouldn't bother creating a ticket for HaikuPorter, but please feel free to do so if you wish.
That said, I doubt that anyone would fix the issue because with "correct" recipes the misleading error never happens ;-)

**Comment by bbjimmy** [comment]
I say file the ticket. the error should lead you in a direction to discover what is incorrect with your recipe.

**Comment by pulkomandy** [comment]
Yes, there should be a proper error message in this case, but the code to display it seems broken. Definitely file a bug at HaikuPorter side.

**Comment by fbrosson** [comment]
Maybe we should close this issue, now that @agmsmith has created haikuports/haikuporter/issues/101.

**Comment by agmsmith** [comment]
Good point, this bug should be in the HaikuPorter area.
