### ISSUE TITLE
Build failures on 32bit with libxml2

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#8650]
When checking out the latest version for Bluefish (2.2.13) I ran into the problem that it can't seem to find the headers `libxml/xmlmemory.h` and `libxml/parser.h`.

Looking at the build process I see (which is correct):
```
-I/packages/libxml2_x86-2.10.4-2/.self/develop/headers/x86/libxml2
```

Source files include (also correct)
```
#include <libxml/xmlmemory>
#include <libxml/parser>
...
```

Checked current recipe for Bluefish (2.2.12) and current geany_plugins recipe which both end up with:
```
fatal error: libxml/parser.h: No such file or directory (same for libxml/xmlmemory)
```

Checking Bluefish 2.2.12 on 64bit works fine.

**Comment by korli** [comment]
Shouldn't be -I/packages/libxml2_x86_devel-2.10.4-2/.self/develop/headers/x86/libxml2 ?

**Comment by Begasus** [comment]
> Maybe check the chroot packages libxml2_x86*

How do I check that (never been checking inside chroot)?

**Comment by korli** [comment]
'haikuporter -E bluefish' drops you in the chroot. the package list should already say whether the libxml2 packages are consistent.

**Comment by korli** [comment]
from the irclog:

/boot/system/packages/libxml2_x86-2.10.4-3-x86_gcc2.hpkg
/boot/system/packages/libxml2_x86_devel-2.10.4-2-x86_gcc2.hpkg

This is incorrect, the revisions don't match.

**Comment by Begasus** [comment]
The install seems wrong on the revision for the devel package?
```
The following changes will be made:
  in system:
    install package libxml2_x86_devel-2.10.4-2 from repository HaikuPorts
```

**Comment by korli** [comment]
libxml2_x86-2.10.4-3-x86_gcc2.hpkg shouldn't even exist given that the recipe is at revision 2.

**Comment by Begasus** [comment]
> EDIT you can query locally libxml2_x86-2.10.4-2-x86_gcc2.hpkg, and install it with pkgman

No hits ...

**Comment by korli** [comment]
Then download:
https://eu.hpkg.haiku-os.org/haikuports/master/x86_gcc2/current/packages/libxml2_x86-2.10.4-2-x86_gcc2.hpkg

**Comment by Begasus** [comment]
Local rebuild did the trick I think, will do a fresh build for new bluefish release and close if things are fine, sorry for the noise :)

**Comment by Begasus** [comment]
All good now, sorry for all the trouble :)
