### ISSUE TITLE
Handbrake crashes...

### ISSUE THREAD

**Issue by ArDrakho** [haikuports/haikuports#8698]
After I open Handbrake, I select and click on the 'Open Source' button; it prsents the termination  of application error window.

![Handbrake_Open_Source_Crashes](https://github.com/haikuports/haikuports/assets/48101100/ef7b02e8-e7ed-476b-b8fd-82be8996fcaa)

[HandBrake-88215-debug-19-05-2023-23-57-26.report.txt](https://github.com/haikuports/haikuports/files/11522876/HandBrake-88215-debug-19-05-2023-23-57-26.report.txt)

I also saved the crash report (see attached file). Handbrake performs the same error condition in Haiku laptop and my PC environments.

**Comment by augiedoggie** [comment]
From a quick glance at the crash report, this seems similar to #7477 and #7821.  Perhaps you could try removing the files listed in those issues or running the command to update the loaders.cache file.

**Comment by ArDrakho** [comment]
Here is the report from the laptop:

[HandBrake-1522-debug-20-05-2023-01-45-38.report.txt](https://github.com/haikuports/haikuports/files/11523117/HandBrake-1522-debug-20-05-2023-01-45-38.report.txt)

Hmmm...what is command and its syntax that you by "running the command that updates the loaders.cache file"?

**Comment by augiedoggie** [comment]
> Hmmm...what is command and its syntax that you by "running the command that updates the loaders.cache file"?

The command to update it is:
```
gdk-pixbuf-query-loaders > /boot/system/settings/gdk-pixbuf-2.0/loaders.cache
```

and the command to remove the old mime files
```
rm -rf /boot/system/non-packaged/data/mime
rm -rf /boot/home/config/non-packaged/data/mime
```

**Comment by ArDrakho** [comment]
From the Terminal, I get a message:

bash: /boot/system/settings/gdk-pixbuf-2.0/loaders.cache: Permission denied

**Comment by augiedoggie** [comment]
You need to run the `gdk-pixbuf-query-loaders` command including the redirect `>` as I wrote above...

```
gdk-pixbuf-query-loaders > /boot/system/settings/gdk-pixbuf-2.0/loaders.cache
```

**Comment by ArDrakho** [comment]
I do not understand what we just did...but that worked in my laptop.

i will perform the same three commands in my PC later today.

If that clears the issue I will close the ticket.

**Comment by augiedoggie** [comment]
> I do not understand what we just did...but that worked in my laptop.
> 
> i will perform the same three commands in my PC later today.

It is discussed in the other issues I linked to earlier.  The `gdk-pixbuf-query-loaders` command does not always run when the package is installed.  You can probably just run that command and skip the `rm -rf` commands unless the app is still crashing.

**Comment by ArDrakho** [comment]
It takes all three commands to resolve the issue:

gdk-pixbuf-query-loaders > /boot/system/settings/gdk-pixbuf-2.0/loaders.cache

rm -rf /boot/system/non-packaged/data/mime

rm -rf /boot/home/config/non-packaged/data/mime

Thank you!
