### ISSUE TITLE
OpenBLAS : missing provides

### ISSUE THREAD

**Issue by miqlas** [haikuports/haikuports#875]
> POLICY ERROR: no matching provides "lib:libopenblasp_r0.2.19_x86" for "lib/libopenblasp-r0.2.19.so"

It PROVIDES:
> lib:libopenblas_r${portVersion}_$secondaryArchSuffix = $portVersion compat >= 0

but it should be:

> lib:libopenblasp_r${portVersion}_$secondaryArchSuffix = $portVersion compat >= 0

So mmu_man you just forgot a p. The PROVIDES_devel is correct.

Info:
hrev50700 gcc2h
updated ports tree (76e1616)
up to date haikuporter

**Comment by mmuman** [comment]
Thanks, I noticed it but only fixed the devel one.
Should be fixed by b383cf1.

**Comment by miqlas** [comment]
Thanks, but it doesn't build yet:

It PROVIDES and PROVIDES_devel:

`libopenblas_r${portVersion}_$secondaryArchSuffix`

but the generated lib actually:

`libopenblas-r${portVersion}_$secondaryArchSuffix`

As you can see here:
POLICY ERROR: no matching provides "lib:libopenblasp_r0.2.19_x86" for "lib/**libopenblasp-r0.2.19.so**"

So minus instead of underscore. But one cannot use minus in the recipes. So what's now?

**Comment by pulkomandy** [comment]
I think the best thing to do would be to patch the project to use a properly formatted name: libopenblasp.so.0.2.19

**Comment by korli** [comment]
Should be fixed with 613a3e9c1da20e8b4e2b4b9d7d961d458c9207b5

**Comment by mmuman** [comment]
Thanks!
