### ISSUE TITLE
mozc: broken builds

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#8767]
Current recipe for mozc is broken, due to cmd:python3 pointing to 3.9, and the recipe also requiring six_python3 (which got removed on commit https://github.com/haikuports/haikuports/commit/df145a169a3a6063c7107ff4ae0e529f2f639507.

Trying to switch to six_python39, I get:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 49: invalid continuation byte`

early on. I'm attaching .txt file for that output, as I can't paste multilines properly with WebPositive (eats away all newlines).
[mozc-build-failure-py39.txt](https://github.com/haikuports/haikuports/files/11614712/mozc-build-failure-py39.txt)

Then, trying to figure out when things broke, I've tried re-enabling the `six_python3` package (and modifing mozc recipe to reference Python 3.7 where needed). Build progressed MUCH further (no more `UnicodeDecodeError`), but I now reliably get crashes near the end of the build. Either `Exception (Segment violation)`, or a `Call (abort() called)` after a `terminate called after throwing an instance of 'std::bad_alloc'`.

Also attaching Debugger reports.txt those, just in case.
[gen_system_dictionary_data_main-1296-debug-31-05-2023-13-07-07.report.txt](https://github.com/haikuports/haikuports/files/11614786/gen_system_dictionary_data_main-1296-debug-31-05-2023-13-07-07.report.txt)
[gen_system_dictionary_data_main-1900-debug-31-05-2023-13-14-17.report.txt](https://github.com/haikuports/haikuports/files/11614787/gen_system_dictionary_data_main-1900-debug-31-05-2023-13-14-17.report.txt)

This was all on beta4, hrev56578+86, 32 bits.

**Comment by Begasus** [comment]
Should be fixed in: https://github.com/haikuports/haikuports/pull/8845
