### ISSUE TITLE
LibreOffice crashes

### ISSUE THREAD

**Issue by ArDrakho** [haikuports/haikuports#8801]
I can create a new document and save it; then quit LibreOffice.
However, if I return later and try to re-open it, it immediately crashes and displays a “crash” window. The behavious is as in previous posting: https://discuss.haiku-os.org/t/libreoffice-crashes/13424

It started after these updates were applied: /boot/system/packages/administrative/state_2023-05-28_13:43:15

boehm_gc-8.2.2-1-x86_64.hpkg
wildmidi-0.4.4-2-x86_64.hpkg
xmlsec_nss-1.2.37-1-x86_64.hpkg
xmlsec-1.2.37-1-x86_64.hpkg

LibreOffice works as normal if I boot/load a previous state prior to these updates.
If I boot normally. LibreOffice will crash when trying to re-open a .ods or .odt file.

**Comment by Begasus** [comment]
Odd, probably related to the update on xmlsec, LO doesn't crash on 32bit but indeed on 64bit it fails (will investigate):

```
resolve symbol "xmlSecBase64Decode" returned: -2147478780
warn:sal.osl:2258:1:sal/osl/unx/module.cxx:152: dlopen(/boot/system/apps/LibreOffice/program/../program/libxmlsecurity.so, 2): Symbol not found
warn:sfx.doc:2258:1:sfx2/source/doc/objserv.cxx:1748: Failed to get document signature information com.sun.star.uno.DeploymentException message: component context fails to supply service com.sun.star.security.DocumentDigitalSignatures of type com.sun.star.security.XDocumentDigitalSignatures: loading component library <file:///boot/system/apps/LibreOffice/program/../program/libxmlsecurity.so> failed /sources/core-libreoffice-7.3.7.2/cppuhelper/source/shlib.cxx:311 /sources/core-libreoffice-7.3.7.2/workdir/UnoApiHeadersTarget/offapi/normal/com/sun/star/security/DocumentDigitalSignatures.hpp:77
warn:sal.osl.pipe:2258:1:sal/osl/unx/pipe.cxx:353: shutdown() failed: ENOTCONN
warn:sal.osl.pipe:2258:3:sal/osl/unx/pipe.cxx:389: accept() failed: -2147479552 (Bad semaphore ID)
```

**Comment by korli** [comment]
https://bugs.gentoo.org/904387
https://github.com/LibreOffice/core/commit/19e998aa98d966cffca98bed9408d5758d91d9be

=> we should stay on 1.2.37 until LibreOffice is updated to a version not using xmlSecBase64Decode

**Comment by korli** [comment]
Please sync xmlsec with the version 1.2.37-2 or 1.2.37-1. Sorry for the trouble.
