### ISSUE TITLE
samba-3.6.25.recipe specifies wrong log directory

### ISSUE THREAD

**Issue by axeld** [haikuports/haikuports#882]
See:
https://github.com/haikuports/haikuports/blob/master/net-fs/samba/samba-3.6.25.recipe#L115

There is probably just a '$' missing, but I'm not sure as I've never written a recipe yet.

**Comment by mmuman** [comment]
Indeed, it's missing the $.
The available variables are documented on the wiki:
https://github.com/haikuports/haikuports/wiki/HaikuPorter-BuildRecipes

**Comment by mmuman** [comment]
Should be fixed now.

**Comment by axeld** [comment]
Thanks a lot, and also thanks for the wiki link!  :+1:
