### ISSUE TITLE
Update squirrel recipe to version 3.1

### ISSUE THREAD

**Issue by korli** [haikuports/haikuports#886]
dev-lang/squirrel/squirrel-3.0.4.recipe

https://sourceforge.net/projects/squirrel/files/squirrel3/squirrel%203.1%20stable/squirrel_3_1_stable.tar.gz

**Comment by Begasus** [comment]
https://github.com/haikuports/haikuports/pull/1559

**Comment by korli** [comment]
ad6ded8c9032247a871495f35e5a4f439b353ecb
