### ISSUE TITLE
lua54 update and use lua54 as default lua with addition of lua53

### ISSUE THREAD

**Issue by FractalU** [haikuports/haikuports#8872]
Lua version 5.4.6 has been released. The current lua54 version is 5.4.4.

The default lua version is still lua 5.3.6 yet lua54 exists. There is no lua53. So this is probably by design. Is there a reason why this is the case? The lua packaging looks very outdated.

**Comment by Begasus** [comment]
No one has stepped up to update lua54? :)
lua54 hasn't been tested that much so that's why lua53 is still default.

**Comment by FractalU** [comment]
Makes sense. It's probably good to keep the issue. Hopefully it gets resolved one day.

**Comment by FractalU** [comment]
Thanks, the updated lua works well for me. I had trouble installing though. Haiku depot froze a lot when I tried to update this package. I had to try many times. Eventually it worked. This is probably due to additional packages haiku installs.

For more detail, Here is the gui prompt before installing lua in text.
```
Package changes

The following additional package changes have to be made:

in system:

    install package haiku-r1~beta4_hrev56578_87-1-x86_64.hpkg from repository Haiku

    install package haiku_devel-r1~beta4_hrev56578_87-1-x86_64.hpkg from repository Haiku

    install package haiku-r1~beta4_hrev56578_59-1

    install package haiku_devel-r1~beta4_hrev56578_59-1
```

To me it looks like haiku depot sometimes works, sometimes doesn't. It's not reliable.
