### ISSUE TITLE
luajit from the download page is outdated, the git v2.0 and v2.1 branches should be used instead

### ISSUE THREAD

**Issue by FractalU** [haikuports/haikuports#8873]
I checked the recipes `luajit-2.0.4.recipe` and `luajit-2.1.0~beta3.recipe` in `dev-lang/luajit` and see that it used luajit from the download page. The version `2.0.4` is about 8 years and the version `2.1.0-beta3` is about 6 years old and outdated. The project is currently being maintained in the v2.0 and v2.1 branches of the luajit git repository https://luajit.org/git/luajit.git. In the download page it's written that distros should do a snapshot of a branch.

In luajit download page:

> **Releases of Actively Developed Branches**
> 
> Releases are only made occasionally. You're strongly encouraged to follow the git branches.
> 
> Distros that require releases should do regular snapshots of a branch. Do not attempt to cherry-pick or backport individual changes, no matter how self-standing individual changes look (because they often are not). 

Even Mike Pall (the creator of luajit) admitted in a git issue that he won't do releases anymore. The comment can be found under the link https://github.com/LuaJIT/LuaJIT/issues/665.

Mike Pall comment in 'Project status':

> Look at the git v2.1 history and judge yourself. Releases are an antiquated concept. Most everyone is using v2.1, anyway.

It's really unfortunate that he doesn't put releases anymore. All the later improvements and bug fixes are now in the v2.0 and v2.1 branches.

Also the version `2.0.4` is being used instead of `2.1.0-beta3`. When using the git repo, the v2.1 branch should be preferred over the v2.0 one even if the version is `2.1.0-beta3` and therefore being marked as beta. The git branches are actively maintained and fully production ready. It's just that Mike Pall doesn't put releases anymore and as a consequence production ready software is being marked as beta. The versioning could be done similar to the arch or debian linux distros. They already use the git branches.

**Comment by FractalU** [comment]
Recently, luajit switched to rolling releases. The new version is just `2.1` as opposed to `2.1.0-beta3`. For the `v2.0` git branch of luajit, the new version is just `2.0` as opposed to `2.0.5`. For more detail, see https://luajit.org/status.html#release.

**Comment by Begasus** [comment]
This is getting confusing for an old man :) So we should switch to  v2.0.ROLLING and v2.1.ROLLING?

**Comment by FractalU** [comment]
Luajit switched to a release model where the version number is automatically being determined from the git commit. Mike Pall, the creator of Luajit, wanted a release model where the version number monotonically increases over the commit history. Basically, newer commits have a higher version number than the previous ones. To achieve that, he chose the unix timestamp as the last part of a version number. The version number would look like `2.1.1693350652`. The number `1693350652` is a unix timestamp of a commit. The timestamp can be derived from the git command `git show -s --format=%ct` in the Luajit git repository. That means that Mike Pall won't do stable releases and expects everyone to use the latest git commit of the `v2.1` or `v2.0` branch. From time to time, git snapshots of Luajit have to be done. There is a way of getting a tarball from the Luajit git repo with the command `git archive --format=tar -o <Luajit archive name>.tar HEAD`. `git archive` automatically derives the timestamp and therefore the version number from the current commit. The timestamp is then being stored in the `.relver` file. The version number isn't being stored directly. It has to be derived from the timestamp in `.relver`. You can look at `.gitattributes` and `.relver` files for more details.

**Comment by Begasus** [comment]
Luajit updated today: https://github.com/haikuports/haikuports/pull/10577
Closing this one, if need be give a jell or open a new issue for it. Thanks!
