### ISSUE TITLE
 libdvdread: fix GCC2 build

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#8879]
See: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/4711/builds/81177.log

**Comment by Begasus** [comment]
If it's only parse errors, they shouldn't be too hard to fix.

**Comment by kenmays** [comment]
@Begasus - Checked all current dependencies for libdvdread GCC2 usage. No GCC2 work is needed.

**Comment by kenmays** [comment]
@begasus - Per #8356. Verified all dependencies were migrated to Haiku x86 and/or x64.

**Comment by Begasus** [comment]
> @Begasus - Per #8356. Verified all dependencies were migrated to Haiku x86 and/or x64.

It's not because that one can't be fixed for gcc2 (iirc there were too many parse errors) this one can't be fixed, did you atleast investigate?

**Comment by kenmays** [comment]
@Begasus - Yes. Outdated for GCC2, as all major Haiku CD/DVD/Blu-ray-related apps and libs were migrated to GCC >2.95.3. BeBytes and BeOS software archive didn't have any port of these libraries (hence, BeOS 5.x non-requirement).
