### ISSUE TITLE
DVDBackup goes to KDL when copying DVD

### ISSUE THREAD

**Issue by ArDrakho** [haikuports/haikuports#8884]
I attempted to "backup"/"rip" a movie DVD and sometime in the rip process--it crashed.

Refer to pictures for details:

![20230523_141917](https://github.com/haikuports/haikuports/assets/48101100/59be288b-caee-4383-9bbc-03cf44f6aa55)
![20230523_141929](https://github.com/haikuports/haikuports/assets/48101100/400d2080-07d9-41d6-9d56-b521f002654a)
![20230523_141931](https://github.com/haikuports/haikuports/assets/48101100/26e7e21a-9190-449f-9c10-29be28131288)

**Comment by jmairboeck** [comment]
KDL issues should be reported at https://dev.haiku-os.org/ because this is a driver issue.

**Comment by diversys** [comment]
Indeed.

**Comment by korli** [comment]
Please test on a nightly build. This code changed since beta4
