### ISSUE TITLE
Web (Epiphany) goes into KDL during site refresh

### ISSUE THREAD

**Issue by ArDrakho** [haikuports/haikuports#8885]
Web crashed when page was re-loading.

Refer to pictures for details:

![20230622_160223](https://github.com/haikuports/haikuports/assets/48101100/071adbdf-77e1-43ab-976e-4583bac7b740)
![20230622_160225](https://github.com/haikuports/haikuports/assets/48101100/df351f3b-e56f-4a98-989d-1327e82c6565)
![20230622_160227](https://github.com/haikuports/haikuports/assets/48101100/76baba09-e923-42f0-81d8-5644fd9b5894)

**Comment by waddlesplash** [comment]
Yes, please open a ticket at the bugtracker.
