### ISSUE TITLE
Is it possible to port Mozilla Firefox?

### ISSUE THREAD

**Issue by chrisonlinux** [haikuports/haikuports#8890]
The port of Epiphany made the internet much more accessible from Haiku. I wonder if it's possible to port a fully featured web browser to Haiku, such as Mozilla Firefox or Google Chrome.

**Comment by Begasus** [comment]
You can check or lend a hand(?) :) at the topic on the forum: https://discuss.haiku-os.org/t/progress-on-porting-firefox/13493

**Comment by chrisonlinux** [comment]
Firefox is too demanding to run on Haiku. (At least for now) I am personally unable to help port software to Haiku, as I don't know much about programming. I really hope we manage to port it one day, though!

**Comment by korli** [comment]
Can this be closed?

**Comment by waddlesplash** [comment]
I think so.
