### ISSUE TITLE
FooBillard++ not launcching from Tracker/Deskbar

### ISSUE THREAD

**Issue by psw1747** [haikuports/haikuports#8891]
foobillardplus 3.42.0-2 haikuports-x86_64 is trying to launch but milliseconds after I see window borders, it crashes. I have installed some packages perhaps necessary to run it, SDL and libpng. Haiku OS current stable R4_Beta on Dell Latitude e7250 RAM 16GB

**Comment by humdingerb** [comment]
When the app crashes, a window pops up letting you save a debug report that should be attached to this ticket.

**Comment by psw1747** [comment]
No, the app is trying to open. Soon after the window border emerges; it shuts down (total 0.1 sec). No debug window or any sorts of helpers pops up. I tried to open a debug app for it. It freezes too.

**Comment by Begasus** [comment]
> I have installed some packages perhaps necessary to run it, SDL and libpng

When installing the package those packages (if not installed) should be installed by the package manager, no need to install them manually?

Aside from that, try to launch it in the Terminal and see if you could get some information there, before doing that open a second tab and run the command `tail -f /var/log/syslog` to see if anything shows there with the crash.

**Comment by psw1747** [comment]
I installed the package from Terminal not from GUI. Yes, you're right. I could run it by executing from Terminal. It plays music thus better than Ubuntu/Debian won't play it. 
But It doesn't launch from  the GUI App Launcher. Here's detail of syslog.
`tail /var/log/syslog`
```

KERN: usb_midi: init_driver() version:Jun 21 2023 06:16:26
KERN: usb_midi: init_driver() OK
KERN: usb_midi: publish_devices()
KERN: usb_midi: uninit_driver()
KERN: usb_midi: uninit complete
KERN: loaded driver /boot/system/add-ons/kernel/drivers/dev/midi/usb_midi
KERN: loaded driver /boot/system/add-ons/kernel/drivers/dev/midi/ice1712
KERN: loaded driver /boot/system/add-ons/kernel/drivers/dev/midi/emuxki
KERN: devfs: reload driver "ice1712" (4, 35953)
KERN: devfs: reload driver "emuxki" (4, 35956)
KERN: emuxki: init_hardware()
KERN: Illegal sampler view creation without bind flag
Last message repeated 1 time
KERN: Last message repeated 2 times.
Last message repeated 2 times
KERN: slab memory manager: created area 0xffffffffa4001000 (32186)
```
From Terminal

`/boot/system/apps/FooBillard++/FoBillard++ 2>stderr.log`
```
-- cut help documents --

/boot/home/config/settings/FooBillardPlus/foobillardrc
extension_cubemap_ARB=1
extension_multitexture_ARB=1
extension_combine_ARB: 1
extension_dot3_ARB: 1
extension_vp_ARB: 1
extension_ts_NV=0
extension_rc_NV=0
extension_vp_NV=0
options_multisample: 1
Anisotropic Filter 1.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Now playing 07 E.M.I.T.R - Neptunes Realm.ogg.
Mesa: User error: GL_INVALID_VALUE in glMaterial(invalid shininess: 1000.000000 out range [0, 128.000000])
Mesa: 9 similar GL_INVALID_VALUE errors
Mesa: User error: GL_STACK_OVERFLOW in glPushMatrix(mode=GL_TEXTURE, unit=0)
Mesa: User error: GL_INVALID_VALUE in glMaterial(invalid shininess: 1000.000000 out range [0, 128.000000])
Mesa: User error: GL_INVALID_VALUE in glTexParameter(param)

--cut these last two errors x hundreds times --
```

**Comment by Begasus** [comment]
OK, those messages seem harmless, looks like this is an issue not launching correctly from Tracker/Deskbar ... could use someone to look into this :)

**Comment by augiedoggie** [comment]
The problem appears to be when SDL is initialized it changes the working directory to the application executable, but the game expects it to be set to the data directory. Calling the `enter_data_directory()` function a second time seems to fix it for me.

**Comment by kenmays** [comment]
The x86/x86_64 foobillardplus recipe needs freetype2 patching.

**Comment by kenmays** [comment]
New recipe/patchset builds on hrev57134 x86. But, OpenGL renderer "not found" issue.

**Comment by kenmays** [comment]
New recipe/patchset builds on hrev57134 x86. Works so far.
