### ISSUE TITLE
[Wishlist] Drawterm

### ISSUE THREAD

**Issue by maylay** [haikuports/haikuports#8899]
Drawterm is a program that users of non-Plan 9 systems can use to establish graphical cpu connections with Plan 9 CPU servers. Drawterm serves its local name space as well as some devices (the keyboard, mouse, and screen) to a remote CPU server. 

9front fork (Supports TLS, DP9IK): http://git.9front.org/plan9front/drawterm/HEAD/info.html
Vanilla fork: https://github.com/9fans/drawterm

> Plan 9 is a distributed computing environment assembled from separate machines acting as terminals, CPU servers, and file servers. A user works at a terminal, running a window system on a raster display. Some windows are connected to CPU servers; the intent is that heavy computing should be done in those windows but it is also possible to compute on the terminal. A separate file server provides file storage for terminals and CPU servers alike.

**Comment by Begasus** [comment]
Done in: https://github.com/haikuports/haikuports/pull/9252
