### ISSUE TITLE
Iaito: add icon

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#8903]
In the source there is already a svg icon, however this fails to be converted to rdef, so could use someone with skills on IOM/Wonderbrush.

**Comment by pulkomandy** [comment]
Please report that icon on Haiku bugrtracker, since we have a student working on Icon-O-Matic this summer, it might be an opportunity to improve the SVG import :)

**Comment by Begasus** [comment]
Had been thinking about it, but thought about not bothering him for it, will do :)
