### ISSUE TITLE
 diff program with --strip-trailing-cr option stack traces

### ISSUE THREAD

**Issue by hoanga** [haikuports/haikuports#8917]
the _--strip-trailing-cr_ option for the _diff_ command produces a stack trace (last observed on hrev57122).  opening issue here as it does not appear to be directly related to os-level code.

for more details see [this ticket](https://dev.haiku-os.org/ticket/18487)

steps to reproduce
```
> touch a.txt b.txt

> diff --strip-trailing-cr a.txt b.txt
```

**Comment by augiedoggie** [comment]
It is something to do with the gcc2 patches for the port. When I build `diffutils` (on x86_64 nightly) without the patchset then the command behaves normally.  From a quick look at the stack trace it appears to be something near [this part](https://github.com/haikuports/haikuports/blob/master/sys-apps/diffutils/patches/diffutils-3.8.patchset#L272) of the patch.

**Comment by pulkomandy** [comment]
Yes, before the patch we have this:

```
*srclim = '\r';
dst = rawmemchr (p, '\r');
```

After the change, these two are reversed and there's a risk the rawmemchr never reaches a \r and goes out of memory bounds.

The code should probably be:

```
char *srclim = p + buffered;
char *dst;
char const *src;

*srclim = '\r';
dst = rawmemchr (p, '\r');
```

But, do we need to keep this buildable with gcc2?
