### ISSUE TITLE
EUAE_x86 probably needs to be rebuild.

### ISSUE THREAD

**Issue by unspacyar** [haikuports/haikuports#9006]
When trying to update Haiku, I get the following message:

package euae_x86-0.8.29~wip4-4 requires lib:libsdl_sound_x86>=1.0.2, but none of the providers can be installed.

I am using Haiku 32 bit.

**Comment by unspacyar** [comment]
nevermind... I guess this is being addressed here:
https://github.com/haikuports/haikuports/commit/827b282bdb214064e84797c63f3ea942612d7ebd

**Comment by Begasus** [comment]
It's in the pipeline, atm mame is still building there. :)

**Comment by unspacyar** [comment]
Thank you for the information, @Begasus !  I was able to update successfully.

**Comment by Begasus** [comment]
Thanks for following up @unspacyar!
