### ISSUE TITLE
qtkeychain: add qt6_keychain

### ISSUE THREAD

**Issue by nephele-gh** [haikuports/haikuports#9012]

**Comment by mmuman** [comment]
How should we name it, do we have a convention already?

**Comment by Begasus** [comment]
dev-libs/qtkeychain (gentoo): https://packages.gentoo.org/packages/dev-libs/qtkeychain

**Comment by mmuman** [comment]
Yes but the qt6 version specifically, we can't have both names the same, and we already have the qt5 version.

**Comment by Begasus** [comment]
qtkeychain-qt6 is more used in some places, I guess that should be ok?

https://repology.org/project/qtkeychain-qt6/versions

**Comment by Begasus** [comment]
Done in: https://github.com/haikuports/haikuports/pull/9019
