### ISSUE TITLE
Update vim recipe

### ISSUE THREAD

**Issue by miqlas** [haikuports/haikuports#902]
https://github.com/vim/vim
https://github.com/haikuports/haikuports/pull/917

Try to enable the optional features, like multibyte editing support and scripting languages.

**Comment by korli** [comment]
Hmm vim is still on the list of recipes which didn't pass the build on x86_64, when I tried a mass rebuild. I didn't investigate more. IMO fixing recipes should come before updating them.

**Comment by ohnx** [comment]
@korli do you happen to have a list of these recipes that didn't build?

**Comment by korli** [comment]
I couldn't validate the failures yet, but a few recipes: minimizeall, besol, bespider, ale, interface_elements, libbdplus, libquicktime, vorbis_tools

**Comment by korli** [comment]
aria2 and dovecot fail to build/validate too.

**Comment by jessicah** [comment]
Can we split gvim into a separate sub-package? Otherwise it requires installing ruby just to install command line vim, which doesn't actually need ruby.

**Comment by miqlas** [comment]
Jesicah, i explicitly enabled ruby in the recipe, since i thought if it is already compiled with --with-features=big, then we shouls try to enable as much functionality, as we can. So i tried all the configure switches, and enablen all of them, then removed every, what made problems.

Technically i can split gvim into an own package, and if you want, i can do a vim minimal cli package too (with conflicting against the big version)

I thought ruby comes preinstalled with Haiku.

**Comment by miqlas** [comment]
It is already recent enough and i already enabled all the features, was working correctly on Haiku.
Closing for now.
