### ISSUE TITLE
Slim down MuPDF package

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuports#9061]
1. Move documentation to devel package
2. Create debuginfo package (libmupdf is very large)

**Comment by Begasus** [comment]
There is already a debuginfopackage for it?
https://github.com/haikuports/haikuports/blob/b6cd133669f9fe2038f163aa37fd5b588c5c631e/app-text/mupdf/mupdf-1.20.3.recipe#L93

**Comment by Begasus** [comment]
Documentation moved in: https://github.com/haikuports/haikuports/pull/9065
