### ISSUE TITLE
openjdk11 sources not fetchable

### ISSUE THREAD

**Issue by kohlschuetter** [haikuports/haikuports#9118]
I can't connect to https://ports-mirror.haiku-os.org

Commands like "haikuporter openjdk11" fail with "Connection refused"

**Comment by waddlesplash** [comment]
Yes, it's been down since an infrastructure migration a while back. The problem is tracked here: https://github.com/haiku/infrastructure/issues/82

openjdk11 sources not existing anymore should be treated as a separate problem. CC @korli.

**Comment by korli** [comment]
Use `pkgman install openjdk11` to install on x86_64.
