### ISSUE TITLE
Monsterz stopped working

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#9196]
Seems to be related to the recent python work:

```
 ❯ /boot/system/apps/Monsterz/Monsterz
Traceback (most recent call last):
  File "/boot/system/apps/Monsterz/Monsterz", line 15, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'
```

A simple rebuild of the Monsterz package doesn't solve it.

**Comment by Begasus** [comment]
Pygame needs a revbump, thought I had that covered, checked and monsterz did work for me. Will check into it. :)

**Comment by Begasus** [comment]
Should be fixed in: https://github.com/haikuports/haikuports/pull/9197
Could you check again?

**Comment by humdingerb** [comment]
Thanks for the very quick fix!
Highly addictive game. I had to turn off the earworm music or I'd keep humming it until I fall asleep at night... :)
