### ISSUE TITLE
Monsterz: washed out monster colours

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#9199]
After the recent fix by updating "pygame" the monsters on the score panel appear washed out until they score > 0:

![washedout1](https://github.com/haikuports/haikuports/assets/6107158/1f51ccea-4c9a-4ba2-949a-6647da74f19b)

Blue and red monsters still with no points, therefore still dull coloured:

![washedout2](https://github.com/haikuports/haikuports/assets/6107158/cbaf750c-0d24-465b-a546-60591e610285)

**Comment by augiedoggie** [comment]
I think that's intentional.  I see screenshots where the ones with points are more brightly colored.

https://i0.wp.com/www.linuxlinks.com/wp-content/uploads/2017/12/Screenshot-Monsterz.jpg
http://sam.zoy.org/monsterz/monsterz-1.png

**Comment by humdingerb** [comment]
I'm very sure though that before our Python updates those colours weren't dimmed...
Anyway, never mind, seems to be intentional. 😃

**Comment by Begasus** [comment]
Aside from the python version nothing really changed for pygame.
Maybe it behaves as it should now ;)
