### ISSUE TITLE
Unreferenced patchset in PATCHES

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuports#9340]
List of `Unreferenced patchset in PATCHES` errors found by running `hp --lint`.

- [x] cronie-1.5.2.patchset #9343
- [x] dos2unix-7.4.3.patchset https://github.com/haikuports/haikuports/pull/9346
- [x] flam3-3.1.1.patchset https://github.com/haikuports/haikuports/pull/9347
- [x] giddy3-1.5.patchset https://github.com/haikuports/haikuports/pull/9348
- [x] iup-3.8.patchset #10682
- [x] kraptor-4.4.14.patchset #10247
- [x] libcdio_paranoia-10.2_2.0.0.patchset https://github.com/haikuports/haikuports/pull/9350
- [x] libexif-0.6.22.patchset https://github.com/haikuports/haikuports/pull/9351
- [x] libmatroska-1.4.5.patchset https://github.com/haikuports/haikuports/pull/9352
- [x] libyaml-0.2.5.patchset https://github.com/haikuports/haikuports/pull/9353
- [x] milkytracker-0.90.86.patchset (referenced only if $effectiveTargetArchitecture != "x86_gcc2")
- [x] openexr-2.2.1.patchset (referenced only if $effectiveTargetArchitecture = "x86_gcc2")

**Comment by pulkomandy** [comment]
We already have a ticket for the "unknown licenses" ones tracing our attempts to reach the original developers

**Comment by Begasus** [comment]
For the license lint errors I wouldn't bother to much, for cronie it's a false positive as the patchset is only applied on 32bit hence not used on 64bit (maybe others too?)

**Comment by Begasus** [comment]
For dos2unix we could just drop support for gcc2 and go for x86 on 32bit, having it for both architectures is pointless too I think?
