### ISSUE TITLE
32bit buildmaster has been down/stalled for more then a day

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#9342]
Maybe someone with access could reboot/revive it, seems stuck (no progress) on building numpy: https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=&viewMode=expanded

Pokes @mmlr @kallisti5 @nielx (not sure who has access also there).

**Comment by nielx** [comment]
Restarted haikuporter, please close if it was helpful.

**Comment by Begasus** [comment]
Thanks! Up and running again :)

**Comment by Begasus** [comment]
Stuck again for a few days now on numpy (note to self, leave that one out for 32bit).

**Comment by Begasus** [comment]
Up and running again, thanks again @nielx ! 👍
