### ISSUE TITLE
[RFC] secondaryArch perl packages

### ISSUE THREAD

**Issue by jmairboeck** [haikuports/haikuports#9394]
Perl is now available as a secondaryArch package on x86_gcc2 (since #9202). Does it make sense to provide perl module packages (in `dev-perl`) twice for x86_gcc2?

For packages that use compiled parts (i.e. use `ARCHITECTURES="all"`), that would just mean adding the usual `SECONDARY_ARCHITECTURES="x86"` and `$secondaryArchSuffix`.

For `any` arch packages (which is the majority, I presume), we could still add `SECONDARY_ARCHITECTURES="x86"` and thus create a second package with a `_x86` suffix on x86_gcc2.

Is this a good idea or am I on the wrong track here? We might need some secondaryArch perl packages if we encounter some that use compiled parts which don't build with gcc2. Also, should `perl_x86` be treated as  a "first-class citicen" on x86_gcc2? Right now, it seems that it isn't really (but `perl_x86` is also still rather new).

----

Alternatively, we could maybe also drop the gcc2 version of perl and still provide only one perl version (i.e. `perl_x86`, and make it provide `cmd:perl` etc.) also on x86_gcc2, if this doesn't cause problems elsewhere, like with gawk.

----

## Summary

We have multiple different solutions here:

1. keep both versions as is, using `$secondaryArchSuffix` on everything and have `perl_x86` install its stuff in `$prefix/lib/x86/perl`.
   - this requires using `SECONDARY_ARCHITECTURES="x86"` and `$secondaryArchSuffix` also for perl module packages:
     - #9403
     - #9436
     - #9438
   - and some fixes for perl itself: #9437
2. drop gcc2 perl and make `perl_x86` the only perl and using `$prefix/lib/perl5`.
   - this requires fixing the Haiku build to not require old texinfo versions for x86_gcc2 (and other architectures), i.e. [Haiku ticket #18587](https://dev.haiku-os.org/ticket/18587) (or remove the perl dependency on those) and the appropriate changes to the perl recipe: #9439
3. drop `perl_x86` again and make perl only available on the primary architecture.
   - this requires removing the dependency on perl for texinfo_x86-7 (see #9461)
   - it also blocks having packages on x86 with binary perl extensions which require a modern compiler on x86 (like sdl_perl and frozen-bubble).
4. the middle-ground solution of keeping both but conflicting each other would probably not work because `cmd:perl` wouldn't be unique any more.

**Comment by pulkomandy** [comment]
I don't see any problems here, let's remove perl for gcc2 and build it only as secondary arch.

**Comment by jmairboeck** [comment]
At least texinfo uses compiled perl extensions that require perl to be built with the same compiler as itself. That was the very reason why `perl_x86` was introduced. Wouldn't that be problematic for the old version of texinfo?

**Comment by Begasus** [comment]
Fine with me, if the perl_x86 package would supply "cmd:perl" instead of "cmd:perl$secondaryArchSuffix" this wouldn't really change for the "current" perl modules I suppose  (that use "all")?
For "texinfo" we would need to see that it doesn't break there.

**Comment by jmairboeck** [comment]
Using `_x86` subpackages in the same recipe probably isn't a good idea either because they wouldn't be real portable `any` packages any more (see https://github.com/haikuports/haikuporter/issues/234 for the motivation why this would be sensible). So it seems we need separate `foo_secondary` recipes instead (which aren't `any` arch then).

**Comment by jmairboeck** [comment]
Perl packages with `ARCHITECTURE="any"` do contain only perl code which is interpreted by perl, but we'll need two different versions for these packages on 32 bit, e.g. `foo` and `foo_x86`. The easiest way to achieve that is adding `SECONDARY_ARCHITECTURES="x86"`. See #9403 for example.

I'm not sure if this is a good solution, but it is a solution that works.

**Comment by Begasus** [comment]
yeah, classic $prefix/lib vs $libDir in the search paths for the modules, perl gcc2 can't be dropped atm because it's needed for the older textinfo, which in it's state is needed for Haiku.

**Comment by jmairboeck** [comment]
Just for reference: I doubt that dropping gcc2 perl would help for running frozen-bubble on 32 bit. It seems the problem there is related to using secondaryArch SDL (in `/boot/system/lib/x86` instead of `/boot/system/lib`) which sdl_perl can't load apparently.

But dropping gcc2 perl would simplify all perl module packages quite a bit of course, as they wouldn't need to use a secondaryArch hack. `perl_x86` could use `$prefix/lib/perl5` as it's base directory instead of `$prefix/lib/x86/perl5`.

**Comment by Begasus** [comment]
Some packages still rely on gcc2 version of Perl, so those should probably need a revbump (if it would come to this). @jmairboeck maybe you can setup a draft for  Perl to do this on 32bit (PR's/branch) to check it out? For frozen-bubble maybe there is an option to --libdir=$prefix/lib?
@OscarL I ran some checks on the sources for the buildtools of 32bit (did this on 64bit so it's using the installed "newer versions" of texinfo, gcc.texi and iostream.texi can't be build with the newer ones, but ... I got the html page build using texi2html, I'm not sure how hard it would be to switch from texinfo to texi2html internaly for Haiku.

**Comment by Begasus** [comment]
@OscarL already looked at those 2 tickes, nothing I could find there to solve this.
This is the outcome when I try to run this (64bit) on binutils (from buildtools):
```
/Opslag/wip/buildtools-9866b1a47a32306b1660ebff0efbec067545cf7f/html> makeinfo --html ../binutils/binutils/doc/binutils.texi 
binutils.texi:8: @include: could not find bfdver.texi
binutils.texi:55: warning: undefined flag: VERSION
binutils.texi:57: warning: undefined flag: UPDATED
binutils.texi:82: warning: undefined flag: VERSION
binutils.texi:5157: @include: could not find at-file.texi
```

**Comment by korli** [comment]
it seems the use of compiled perl extensions can be disabled with `--disable-perl-xs`. Have you tried it?

**Comment by waddlesplash** [comment]
> At least texinfo uses compiled perl extensions that require perl to be built with the same compiler as itself. 

Isn't Perl entirely C ABI? So then you can mix GCC 2 / GCC 13 binaries without a problem, so long as you link them properly (same as the FFmpeg hack.)

> it seems the use of compiled perl extensions can be disabled with --disable-perl-xs. Have you tried it?

This might be preferred.

**Comment by jmairboeck** [comment]
Perl was moved to secondaryArch only on x86. This is essentially solution 2 above.
