### ISSUE TITLE
vcmi: game does not start

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuports#9404]
Install VCMI and load your Heroes of Might and Magic III files.

The game will run fine until you try playing a campaign. Instead of starting the campaign, VCMI GUI will remain stuck on a "chose a scenario" screen after connecting to the vcmiserver. It looks like there is a communication problem between the client and server in vcmi (it uses a local network connection).

**Comment by korli** [comment]
You mean you bumped the version to 1.3.1, then submit an issue that the game doesn't start?

**Comment by pulkomandy** [comment]
I am on hrev57257 64 bits.

The old v1.2.0 version of VCMI did not fully support campaigns, that's why I made the update in the first place. But I will check 1.2.0 as well to see if it is a regression in VCMI. I thought testing that the game menus running was enough testing, and didn't notice the problem before pushing the new recipe.

It could be also a difference of game data files? I'm using the French version of the game freshly bought from GOG.com. The same datafiles works, more or less, on Windows 7 (but that's not a supported platform for VCMI and the game will crash a little further, it tries to use functions introduced in Windows 8).

I will also check if I can install the version from the repository instead of the one I built myself, maybe it uses different versions of some dependencies.

**Comment by korli** [comment]
For me everything works with 1.3.1 on beta4.

**Comment by pulkomandy** [comment]
VCMI 1.2.0 behaves the same for me. So it's either the nightlies, or something on my system. I'll see if I can try it on another machine.

**Comment by pulkomandy** [comment]
I tried it on another machine, hrev56721, 32bit. I reimported the data from the GOG installer. The result is the same, the menu works but the game does not start.

So it looks like a regression in Haiku? I guess the next step is capturing the network traffic between the client and server?

**Comment by korli** [comment]
This would seem to be like https://dev.haiku-os.org/ticket/18337   Maybe a regression somehow.
strace would already give a picture of what goes on.

**Comment by korli** [comment]
hrev56911 also fails after clicking after "Begin". Bisecting might also be possible.

**Comment by korli** [comment]
tested again on hrev57581 with vcmi-1.3.1-2-x86_64.hpkg . the game does start.
Could you check please?

**Comment by pulkomandy** [comment]
Yes, seems to be working fine now!

**Comment by Begasus** [comment]
I know it's closed, did a rebuild on 64bit R1B4 with: https://github.com/haikuports/haikuports/pull/10631

I don't have the data to check, primary launch is OK, but would be nice if someone could check if TBB could be updated for this. :)
