### ISSUE TITLE
frozen_bubble: app doesn't launch (x64)

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#9419]
frozen_bubble 2.212-2 doesn't launch on Haiku x64 (hrev57257). Fails with 'Compilation failure' errors in CLI.
Doesn't launch in GUI or CLI.

**Comment by Begasus** [comment]
Launches fine here on nightly and R1B4

![Frozn-Bubble](https://github.com/haikuports/haikuports/assets/16057090/d98aa76e-68b3-4bcc-9098-1a24e2f9c4e7)


![Frozen-Bubble2](https://github.com/haikuports/haikuports/assets/16057090/328c2baf-183a-4f1b-95c6-dc309b6d59d9)

**Comment by Begasus** [comment]
Launches fine from Terminal also.

**Comment by augiedoggie** [comment]
There is a missing dependency on the `class_inspector` package.  The game crashed until I installed it.

**Comment by kenmays** [comment]
@augiedoggie - Verified. That worked for me.
@Begasus - Can we add 'class_inspector' as a "REQUIRES" to the applicable package - like 'frozen_bubble' or 'sdl_perl-2' ??
