### ISSUE TITLE
"exec" issue (Another World recipe)

### ISSUE THREAD

**Issue by Luca1991** [haikuports/haikuports#9472]
First of all, I want to apologize because I was sure I double checked everything, but this one was sneaky.
Basically the "exec" command proposed in the PR makes the game unbootable when launched from Tracker.
If you remove the "exec" command from the launch script, the game will start just fine when launched from Tracker.

So, is the "exec" command really needed anyway? Is it ok to just remove it from the script? 

Tagging the relevant colleagues: @Begasus @humdingerb @korli 

Thanks a lot,
Luca

**Comment by korli** [comment]
the SDL startup code seems locked in a loop. Must be a bug in Haiku or our SDL port.
Anyway I switched to launching in the background in 573142d5aaf135452cd59729b209b8c6d49f53d6.

**Comment by Luca1991** [comment]
Ok, thank you @korli 

We can now close this issue 😉
