### ISSUE TITLE
Create a hpkg for Cceleste (platform game)

### ISSUE THREAD

**Issue by johna23-lab** [haikuports/haikuports#9601]
"Celeste Classic C source port for 3DS and PC."

https://github.com/lemon32767/ccleste

Here is the .recipe
==========
SUMMARY="Celeste Classic C source port for 3DS and PC"
DESCRIPTION="Celeste Classic C source port for 3DS and PC, platform game"
 
HOMEPAGE="https://github.com/lemon32767/ccleste"
COPYRIGHT="lemon32767"
LICENSE="GNU GPL v2"
REVISION="1"
SOURCE_URI="https://github.com/lemon32767/ccleste/archive/refs/tags/v$portVersion.tar.gz"
CHECKSUM_SHA256="32dfd797f3c863201e0c19aa97974c56a8ed589a34c0522503f25f6e1399edd6"
SOURCE_DIR="ccleste-1.4.0"
 
 
ARCHITECTURES="x86_gcc2 x86 x86_64"
 
PROVIDES="
	ccleste$secondaryArchSuffix = $portVersion
	app:ccleste$secondaryArchSuffix = $portVersion
	cmd:ccleste
		"
REQUIRES="
	haiku$secondaryArchSuffix
	lib:libsdl2_2.0$secondaryArchSuffix
	lib:libsdl2_mixer_2.0$secondaryArchSuffix
		"
 
BUILD_REQUIRES="
	haiku${secondaryArchSuffix}_devel
	devel:libsdl2_2.0$secondaryArchSuffix
	devel:libsdl2_mixer_2.0$secondaryArchSuffix
		"
 
BUILD_PREREQUIRES="
	cmd:gcc$secondaryArchSuffix
	cmd:ld$secondaryArchSuffix
	cmd:make
	cmd:pkg_config$secondaryArchSuffix
	"
 
BUILD()
{
 
	make $jobArgs
}
 
INSTALL()
{
 
    mkdir -p $appsDir/ccleste
	cp ccleste $appsDir/ccleste
	cp *.txt $appsDir/ccleste
	cp -r data $appsDir/ccleste
	chmod +x "$appsDir/ccleste/ccleste"
	addAppDeskbarSymlink "$appsDir/ccleste/ccleste" "ccleste"
}

**Comment by Begasus** [comment]
Could you turn this into a PR (pull-request), it would be handy to comment on it and you would get the credits as the author for this recipe :)
Also not fully sure here, is this a game engine or an actual game? (didn't check a build yet), if it's an engine I think it should go to the subdir game-engines, if not we need to see where to put it.

**Comment by humdingerb** [comment]
And please work a bit on the SUMMARY and DESCRIPTION. The info that's in there now isn't relevant for the gaming user... :) Better describe the game play, goal of the game, controls etc.

**Comment by Begasus** [comment]
PR created. Thanks!
