### ISSUE TITLE
pango fails to build (checked on 64bit?

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#9604]
Upon checking updates for glib2, gobject-intrspection, harfbuzz ... I noticed pango not building anymore when checking.
Check has been done with the prior new packages and the packages currently in the depot, I also checked previous and latest release for pango, all fail with the same error `cannot find -lharfbuzz-gobject: No such file or directory`:

```
cc  -o tests/testboundaries tests/testboundaries.p/testboundaries.c.o -Wl,--as-needed -Wl,--no-undefined '-Wl,-rpath,$ORIGIN/../pango:/packages/glib2-2.77.0-1/.self/develop/lib:/packages/fribidi-1.0.13-1/.self/develop/lib:/packages/harfbuzz-7.3.0-1/.self/develop/lib:/packages/fontconfig-2.13.96-2/.self/develop/lib:/packages/freetype_bootstrap-2.12.1-1/.self/develop/lib:/packages/cairo-1.16.0-6/.self/develop/lib' -Wl,-rpath-link,/sources/pango-1.50.3/build/pango -Wl,-rpath-link,/packages/glib2-2.77.0-1/.self/develop/lib -Wl,-rpath-link,/packages/fribidi-1.0.13-1/.self/develop/lib -Wl,-rpath-link,/packages/harfbuzz-7.3.0-1/.self/develop/lib -Wl,-rpath-link,/packages/fontconfig-2.13.96-2/.self/develop/lib -Wl,-rpath-link,/packages/freetype_bootstrap-2.12.1-1/.self/develop/lib -Wl,-rpath-link,/packages/cairo-1.16.0-6/.self/develop/lib -Wl,--start-group pango/libpango-1.0.so.0.5000.3 -lm /packages/glib2-2.77.0-1/.self/develop/lib/libglib-2.0.so /packages/glib2-2.77.0-1/.self/develop/lib/libintl.so /packages/glib2-2.77.0-1/.self/develop/lib/libgobject-2.0.so /packages/glib2-2.77.0-1/.self/develop/lib/libgio-2.0.so /packages/fribidi-1.0.13-1/.self/develop/lib/libfribidi.so /packages/harfbuzz-7.3.0-1/.self/develop/lib/libharfbuzz.so /packages/fontconfig-2.13.96-2/.self/develop/lib/libfontconfig.so /packages/fontconfig-2.13.96-2/.self/develop/lib/libfreetype.so /packages/freetype_bootstrap-2.12.1-1/.self/develop/lib/libfreetype.so /packages/cairo-1.16.0-6/.self/develop/lib/libcairo.so /packages/harfbuzz-7.3.0-1/.self/develop/lib/libgobject-2.0.so /packages/harfbuzz-7.3.0-1/.self/develop/lib/libglib-2.0.so /packages/harfbuzz-7.3.0-1/.self/develop/lib/libintl.so -L/packages/harfbuzz-7.3.0-1/.self/develop/lib -L/packages/glib2-2.77.0-1/.self/develop/lib -lharfbuzz-gobject -Wl,--end-group
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/13.2.0/../../../../x86_64-unknown-haiku/bin/ld: cannot find -lharfbuzz-gobject: No such file or directory
collect2: error: ld returned 1 exit status
[80/145] Generating pango/Pango-1.0.gir with a custom command (wrapped by meson to set env)
FAILED: pango/Pango-1.0.gir 
```

**Comment by Begasus** [comment]
Checked on another laptop where I can switch 32bit and 64bit, those don't contain the new packages I'm trying out on this one.
Neither arch there is able to build pango and end up with the same error.

**Comment by Begasus** [comment]
Ok, fix mentioned by @diversys works on both arch's, @threedeyes maybe it would be good to move devel:libharfbuzz_gobject$secondaryArchSuffix also into the _glib package?

**Comment by Begasus** [comment]
Round * :) 
Making the _devel package for harfbuzz also depend on the _glib package solves it also, so no changes would be needed for pango then.

**Comment by Begasus** [comment]
OK so far (working up on checking a build for gtk4) I got this far:
* Needed to enable glib in harfbuzz
* Adjust requirement in pango for it

Without these changes the first error (not enbling glib in harfbuzz) is, hb-glib.h is not included in the package, gtk4 relies on this
Not rebuilding pango against the newer (enabled glib) harfbuzz results in a missing symbol: undefined reference to `hb_glib_script_to_script'

Having those in place made it possible to get a build for gtk4 (hence not working yet), but at least progress (seems to be missing libgdk4 in the package?).

So maybe we could create a seperate harfbuzz_glib package (simular to what is done for cairo/xcairo)?

**Comment by korli** [comment]
> harfbuzz_glib

Can't remember sorry. @threedeyes did the split and disabled glib in harfbuzz.

**Comment by Begasus** [comment]
Well ... strike gtk4, anyway, harfbuzz or pango need a fix for this, the missing symbol hasn't shown up before gtk4 so I think it should be ok to drop above idea to enable glib for harfbuzz.

**Comment by threedeyes** [comment]
Not really. I didn't split the harfbuzz package. It used to be built without glib support. I included glib support and put it in a separate subpackage so as not to add extra dependencies to packages that don't use glib. For example Haiku itself
Переведено с помощью DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by Begasus** [comment]
glib was enabled the first time the support was added, when moving things into a subpackage it was disabled, I guess it should be OK to enable that again as it will only be needed for the subpackge.
Change: https://github.com/haikuports/haikuports/commit/72df83c8309b7014d943f69ada4cb36475018dab#diff-b95b48515689f270af602e3392b084e2189e3cb0bda2a64b8f5e17b08cf35d01R129

**Comment by korli** [comment]
indeed that's a problem. Maybe a conflicting harfbuzz_glib could be added, avoiding the split. But the _devel packages are really difficult then. How to choose one or the other.

**Comment by Begasus** [comment]
PR created: https://github.com/haikuports/haikuports/pull/9611
Bumped version, left the icu version for default harfbuzz to icu66, for the harfbuzz_glib I switched to the newer icu73.
Got a pango update ready when this is ok to merge so that it will pick up the harfbuzz_glib package.

**Comment by Begasus** [comment]
Build OK on buildmaster, descent fix should still be found for harfbuzz/glib, mentioned in issue https://github.com/haikuports/haikuports/issues/9622
