### ISSUE TITLE
wesnoth: Boost.Asio - Haiku networking linkage issue

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#9616]
Ref: Boost.Asio is a cross-platform C++ library for network and low-level I/O programming that provides developers with a consistent asynchronous model using a modern C++ approach.

Test package: Wesnoth 1.16.10 w/boost 1.70->1.83.0 (Haiku hrev57322 x86)
Result: PASSED configuration.
Build ERROR: During wesnoth 1.16.0 build, error in finding definitions:
boost/asio/error.hpp - BOOST_ASIO_NETDB_ERROR (...)
boost/asio/detail/resolver_service.hpp - NI_MAXHOST, NI_MAXSERV, host_name, service_name (see: libnetwork)

Ref: http://devdocs.wesnoth.org/network__asio_8cpp_source.html
Ref: https://www.boost.org/doc/libs/1_83_0/doc/html/boost_asio/using.html

**Comment by lonemadmax** [comment]
See discussion in https://discuss.haiku-os.org/t/porting-issues-r1b4-vs-nightly/13968/10.

**Comment by kenmays** [comment]
@begasus - Submitted PR for build review.

**Comment by kenmays** [comment]
Tested on R1B4 x64 and x86. No issues.
