### ISSUE TITLE
SDL2-ttf configuration files (cmake) are broken?

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#9637]
Latest ppsspp fails to detect latest SDL2-ttf with the included configuration files (those were not present in previous version so it did a fallback with pkgconfig).
Removing them from the package make latest ppsspp build with it, adding some of the devel packages in the REQUIRES_devel also solves the need to add harfbuzz into the recipe for ppsspp.

**Comment by augiedoggie** [comment]
I looked at fixing the cmake files the other night but that didn't seem to help with building freegemas.  There must be another problem with it.

**Comment by Begasus** [comment]
Thanks! 👍
