### ISSUE TITLE
libtool: do not generate .la files

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#970]

**Comment by korli** [comment]
What is the gain for Haiku? Linux distributions keep removing libtool files too, and don't patch libtool for this at least.

**Comment by diversys** [comment]
This idea was extracted from one of the PulkoMandy's comments and I thought it made sense to have it as an issue here. If there is no gain for us we would close it, sure.

**Comment by waddlesplash** [comment]
Seems like we should just stick with what Linux does here. At least it hasn't posed more of a problem in the intervening 5 years...
