### ISSUE TITLE
NetSurf 3.6 recipe missing dependancy and broken link

### ISSUE THREAD

**Issue by Perelandra0x309** [haikuports/haikuports#971]
NetSurf 3.6 needs libwapcaplet to run, is missing in depedancies.  Installing the library from HaikuDepot resolves error:
"Could not open "NetSurf" (Missing libraries: libwapcaplet.so.0)

Also the Be Application menu link to NetSurf is broken.  I believe the correct INSTALL command should be:

addAppDeskbarSymlink $appsDir/netsurf/NetSurf NetSurf

**Comment by diversys** [comment]
Fixed in 08190e92b57f66fbcf9fb4bcde73c0325998ed8d.
