### ISSUE TITLE
Update Noto fonts

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuports#9727]
Apparently there's a new version out for the Noto font.
In the course of Trac ticket [#12986: Use half-stars in Tracker's "rating" attribute column](https://dev.haiku-os.org/ticket/12986) PulkoMandy tracked down a new version at https://github.com/notofonts/symbols/releases/tag/NotoSansSymbols2-v2.008

Unfortunately, I'm totally confused about how the Noto fonts are organized. There doesn't seem to be a complete archive as is used in our current recipe (SOURCE_URI="https://github.com/googlefonts/noto-fonts/archive/v20201206-phase3.tar.gz") ?

**Comment by pulkomandy** [comment]
Yes, there isn't a big combined release anymore. This was not manageable for them to have so many fonts synchronized into a single release. So now each font has its own release cycle.

We can either do a separate recipe for each, or do a single recipe with several SOURCE_URI and several output packages.

so we need to package at least these:

https://github.com/notofonts/latin-greek-cyrillic/releases (Noto Sans, Noto Serif and Noto Sans Mono)
https://github.com/notofonts/noto-cjk/releases (Noto Sans CJK, Noto Serif CJK)
https://github.com/notofonts/symbols/releases (Noto Sans Symbols 2)
https://github.com/notofonts/thai (Noto Thai)
https://fonts.google.com/noto/specimen/Noto+Emoji/glyphs (Noto Emoji, not available on Github)

Possibly other things: noto-music, noto-maths, and other languages/scripts as needed.

**Comment by Begasus** [comment]
I'm guessing for those you need the Noto*.zip files (not the source archives)? I haven't looked further atm

**Comment by Begasus** [comment]
For the basic recipe (currently noto-20200106-1-any.hpkg) I'm still missing, `NotoSansDisplay` and `NotoSansSymbol`

**Comment by pulkomandy** [comment]
I think there is a single "Noto Symbols" font now (which I linked above), replacing "Noto Sans Symbols"

**Comment by Begasus** [comment]
> I think there is a single "Noto Symbols" font now (which I linked above), replacing "Noto Sans Symbols".

OK, got that. Leaves NotoSansDisplay (got NotoSerifDisplay).

**Comment by korli** [comment]
> Once the Noto package is updated, I will adjust the font fallback system in Haiku to the new font names.

I hope these names are still compatible with beta4.

**Comment by Begasus** [comment]
> > Once the Noto package is updated, I will adjust the font fallback system in Haiku to the new font names.
> 
> I hope these names are still compatible with beta4.

So far the names are the same when comparing the package list with.
Only diff atm:
```
diff noto-20200106-1-any.txt noto-2.013-1-any.txt 
22,39d21
< data/fonts/ttfonts/NotoSansDisplay-Black.ttf
< data/fonts/ttfonts/NotoSansDisplay-BlackItalic.ttf
< data/fonts/ttfonts/NotoSansDisplay-Bold.ttf
< data/fonts/ttfonts/NotoSansDisplay-BoldItalic.ttf
< data/fonts/ttfonts/NotoSansDisplay-ExtraBold.ttf
< data/fonts/ttfonts/NotoSansDisplay-ExtraBoldItalic.ttf
< data/fonts/ttfonts/NotoSansDisplay-ExtraLight.ttf
< data/fonts/ttfonts/NotoSansDisplay-ExtraLightItalic.ttf
< data/fonts/ttfonts/NotoSansDisplay-Italic.ttf
< data/fonts/ttfonts/NotoSansDisplay-Light.ttf
< data/fonts/ttfonts/NotoSansDisplay-LightItalic.ttf
< data/fonts/ttfonts/NotoSansDisplay-Medium.ttf
< data/fonts/ttfonts/NotoSansDisplay-MediumItalic.ttf
< data/fonts/ttfonts/NotoSansDisplay-Regular.ttf
< data/fonts/ttfonts/NotoSansDisplay-SemiBold.ttf
< data/fonts/ttfonts/NotoSansDisplay-SemiBoldItalic.ttf
< data/fonts/ttfonts/NotoSansDisplay-Thin.ttf
< data/fonts/ttfonts/NotoSansDisplay-ThinItalic.ttf
49,57d30
< data/fonts/ttfonts/NotoSansSymbols-Black.ttf
< data/fonts/ttfonts/NotoSansSymbols-Bold.ttf
< data/fonts/ttfonts/NotoSansSymbols-ExtraBold.ttf
< data/fonts/ttfonts/NotoSansSymbols-ExtraLight.ttf
< data/fonts/ttfonts/NotoSansSymbols-Light.ttf
< data/fonts/ttfonts/NotoSansSymbols-Medium.ttf
< data/fonts/ttfonts/NotoSansSymbols-Regular.ttf
< data/fonts/ttfonts/NotoSansSymbols-SemiBold.ttf
< data/fonts/ttfonts/NotoSansSymbols-Thin.ttf
```
The NotoSansSymbols2 ones are combined now as @pulkomandy mentioned and is included.

**Comment by Begasus** [comment]
Think I got most covered for the default noto package, still no NotoSansDisplay found.
For the 3 fonts used in the chroscore package I can't find any release (archived or no release on their pages):
https://github.com/notofonts/Arimo
https://github.com/notofonts/Cousine
https://github.com/notofonts/Tinos

**Comment by Begasus** [comment]
A (big) WIP from what I have so far: https://github.com/Begasus/haikuports/tree/noto

**Comment by Begasus** [comment]
OK, noto package is done, installing it works also but requires a hard reboot here (power button).
On the 2 installs I have here both had Noto Sans Display set in Appearance, as mentioned I haven't been able to find one for that (and the other three mentioned above).
When installed the system tries to find a fall-back for the used font and in my case it took the Noto Sans Thai one.
After reboot everything is fine and I've set the font to Noto Sans (Regular) now.
Screenshot when package is installed, menu etc are not accasible at that time.

![screenshot2](https://github.com/haikuports/haikuports/assets/16057090/961ebdbb-b88a-4452-833d-f70690c2a275)

**Comment by Begasus** [comment]
OK, so far things are working fine after the installation. Also finished the CJK recipes.
Default noto branch: https://github.com/Begasus/haikuports/tree/noto (download to create the packages about 1GiB)
CJK branch (sans + serif): https://github.com/Begasus/haikuports/tree/noto_cjk (combined download for both recipes a bit over 1GiB)

**Comment by Begasus** [comment]
> I would prefer more smaller noto packages if possible, maybe splitting the serif/non-serif versions as apropriate.

That would be possible, just a bit of work to be done :)

**Comment by Begasus** [comment]
I can to either way, nothing done beside the basic work. :)
Another thing is the versioning, for noto I used version 2.013, while some of the archives in the recipe use a different version), same thing for the noto_cjk fonts.
Maybe using a year version would be better here? (not like we update these packages every year)

**Comment by Begasus** [comment]
For noto_cjk it's easy, not that much, for noto, that would be about 178 seperate recipes?
Even for git repositories there can be version differences between Sans and Serif archives.

**Comment by pulkomandy** [comment]
We don't really need all of them to be packaged. We did this previously because the release from Google came in one big package. So we can pick just the ones we need (Latin-Greek-Cyrillic, Thai, CJK, symbols) and add more as needed?

**Comment by Begasus** [comment]
Fair enough, back to the drawing board. ;)

**Comment by Begasus** [comment]
Another round for an example on splitting further up: https://github.com/Begasus/haikuports/commit/135b07b795e92287789a81d9f9ca4cac10ee3a31

First one contains the noto_sans, noto_serif and noto_sansmono for latin/greek/cyrilic
Second one could be an example on splitting the first one further, in this case the noto_sans package(s).

**Comment by Begasus** [comment]
I just now used the noto_lgc-2.013.recipe as a base for noto_sans_symbols2 and noto_thai, that works, having a generic one shouldn't really matter as these are not that frequently updated.

**Comment by Begasus** [comment]
Another round:
1st (was done already), containing all fonts (even the reginol ones)
https://github.com/haikuports/haikuports/commit/859ba6ae685755ae354f20263731ffb173eef8e2

2nd, containing the basic ones, being: latin/greek/cyrillic and symbol2 (with the condensed package)
https://github.com/Begasus/haikuports/blob/db7898a05b8af53f714ec9cc38c44f3828c17338/media-fonts/noto/noto-2.013.recipe

**Comment by korli** [comment]
noto_emoji_color can be updated to https://github.com/googlefonts/noto-emoji/releases/tag/v2.042

**Comment by Begasus** [comment]
Related: https://github.com/haikuports/haikuports/pull/10097

**Comment by korli** [comment]
updated in 491c9a65793a2af8e0ec73697ff57db798ce5dca
