### ISSUE TITLE
Git package includes mksh incompatible shell includes in the default profile

### ISSUE THREAD

**Issue by ghost** [haikuports/haikuports#9741]
When starting a new shell with mksh with git installed this happens:
`Welcome to the Haiku shell.

/bin/mksh: /etc/profile.d/git-completion.sh[251]: syntax error: unexpected '(('
/bin/mksh: /etc/profile.d/git-prompt.sh[166]: syntax error: unexpected '(('
~ `

I don't know when this happened. those files clearly mention beeing for bash/zsh only so should not be added to the deafult profile.d which is for posix compatible shells.

**Comment by Begasus** [comment]
On a sidenote, git bash completion is working fine. :)

**Comment by pulkomandy** [comment]
> this would be overwritten on the next update presumeably?

No, the only implemented policy for global-writable-files conflict resolution is "keep-old", which keeps the old version and never replaces it with a package update. As documented here: https://www.haiku-os.org/docs/develop/packages/BuildingPackages.html

This allows users to modify or replace these scripts. If they were in the git package, it would be impossible to disable them without uninstalling said package, and impossible to customize them as well.

**Comment by Begasus** [comment]
@OscarL I updated git local here to version 2.42.1 without the files in profile.d, are there any benifits from having them in there? Arch moves them to bash-completions? https://gitlab.archlinux.org/archlinux/packaging/packages/git/-/blob/main/PKGBUILD?ref_type=heads#L95

**Comment by augiedoggie** [comment]
> Feel free to move them to the `bash-completions` package as you see it fit (either by downloading them as part of the `bash-completions`, adding them as `additional-files`, or in a patchset, even? :-)
> 
> I planned to just remove these offending files from the next git recipe update (at least to address the breakage I caused), but I'll be glad if you beat me to it :-)

I don't think they need to move to a different package, just a different folder so they don't get sourced by every shell at startup.  There are `bash-completion` dirs where the files should be put instead of the `profile.d` directory.  Like `/system/data/bash-completion/completions`

**Comment by Begasus** [comment]
Gentoo even does it diffferent:
```
	newbashcomp contrib/completion/git-completion.bash ${PN}
	bashcomp_alias git gitk
	# Not really a bash-completion file (bug #477920)
	# but still needed uncompressed (bug #507480)
	insinto /usr/share/${PN}
	doins contrib/completion/git-prompt.sh
```
So far even without both files I haven't seen any downside.

**Comment by Begasus** [comment]
For those wanting to check, just created a PR for latest version, removed bashism from the completion file, completion works (didn't work without the files installed).

**Comment by korli** [comment]
Please check with version 2.42.1

**Comment by Begasus** [comment]
Thanks for checking!
