### ISSUE TITLE
endless sky does not start.

### ISSUE THREAD

**Issue by bbjimmy** [haikuports/haikuports#9783]
on hrev57394 endless sky error: 

Welcome to the Haiku shell.

~/games> /boot/home/games/endless-sky
runtime_loader: /boot/system/lib/libuuid.so.1.3.0: No version information available (required by /boot/system/apps/EndlessSky/endless-sky)
runtime_loader: /boot/system/apps/EndlessSky/endless-sky: Could not resolve symbol 'uuid_copy'
resolve symbol "uuid_copy" returned: -2147478780
runtime_loader: /boot/system/apps/EndlessSky/endless-sky: Troubles relocating: Symbol not found
~/games>

**Comment by Begasus** [comment]
Sounds like you got util-linux uuid installed (libuuidVersion="1.3.0"), pkgman install libuuid(_x86) should fix this.

**Comment by bbjimmy** [comment]
libuuid is installed, util_linux_libuuid cannot be installed.

**Comment by Begasus** [comment]
Could you update, bumped revision earlier, so it should pick up libbuid's version now.

**Comment by bbjimmy** [comment]
now it starts after updating to endless_sky-0.10.4-2-x86_64.hpkg

**Comment by Begasus** [comment]
Thanks for checking! :)
