### ISSUE TITLE
qtwebengine-5.15.2: build issue on Haiku R1B4 x86-64

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#9789]
[qtwebengine_5.15.2-2_buildlog.txt](https://github.com/haikuports/haikuports/files/13462327/qtwebengine_5.15.2-2_buildlog.txt)

**Comment by korli** [comment]
Please try with 8820cefd8b3c98d4bb868a98e787112af993c2a7

**Comment by kenmays** [comment]
[qtwebengine_5.15.2-2_buildlog-2.txt](https://github.com/haikuports/haikuports/files/13462859/qtwebengine_5.15.2-2_buildlog-2.txt)

**Comment by korli** [comment]
Should be fixed with d37983580e2be567c1c007688b438fba80db10a3  Now tested a rebuild, sorry for the noise.

**Comment by korli** [comment]
This is to be built with ffmpeg 4.4.

**Comment by kenmays** [comment]
Build completed successfully using FFmpeg 4.2.9.
