### ISSUE TITLE
Latest haikuwebkit crashes Web+

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#9831]
Mentioned here: https://discuss.haiku-os.org/t/webkit-1-99-upgrade-causes-webpositive-to-crash/14307/5

Crash report from here on R1B4 64bit:

[WebPositive-133929-debug-05-12-2023-19-48-53.report.txt](https://github.com/haikuports/haikuports/files/13572285/WebPositive-133929-debug-05-12-2023-19-48-53.report.txt)

**Comment by pulkomandy** [comment]
5 décembre 2023 à 21:35 "nephele" ***@***.***> a écrit:



> 
> Haikuwebkit is an internal project, the bug report does not belong here.
> 
> Please open this on https://dev.haiku-os.org https://dev.haiku-os.org/ 
> So that pulkomandy or me can take a look.

I'll push a fix soon (it's compiling right now).

It's fine, no need for extra paperwork here since it's easily fixed (just a missing NULL pointer check).

**Comment by Begasus** [comment]
> Haikuwebkit is an internal project, the bug report does not belong here.

Will do the next time. :)

**Comment by Begasus** [comment]
I grabbed the "patch" and can apply it to the current recipe, building it however is pretty hard on the system (consumes 99% RAM (15GiB)). So gave I killed the process at about the 900'th target :)

**Comment by korli** [comment]
Still an issue?

**Comment by Begasus** [comment]
Will check later, thanks for the reminder.

**Comment by Begasus** [comment]
Closing as fixed :)
