### ISSUE TITLE
Ark does not recognize compressed file or crashes when to create one

### ISSUE THREAD

**Issue by ArDrakho** [haikuports/haikuports#9843]
When I attempt to open a compressed file (i.e. zip, rar, 7z, etc.), Ark presents an error message:

Loading the archive ‘/boot/home/Bible Web/Database/bible_databases_deuterocanonical-master.zip’ failed with the following error:
No suitable plugin found. Ark does not seem to support this file type.

If I attempt to create a new compressed file, it crashes.
[Ark-1337-debug-07-12-2023-04-36-17.report.txt](https://github.com/haikuports/haikuports/files/13595511/Ark-1337-debug-07-12-2023-04-36-17.report.txt)
[Ark-23040-debug-06-12-2023-22-50-23.report.txt](https://github.com/haikuports/haikuports/files/13595512/Ark-23040-debug-06-12-2023-22-50-23.report.txt)

The crash reports are from my Haiku R1B4 laptop and PC. Both the laptop and PC are synced software-wise.

This error occur after qt5-5.15.9-1-x86_64.hpkg, knewstuff-5.93.0-1-x86_64.hpkg, kcalc-22.04.0-1-x86_64.hpkg, qtwebengine_bin-5.15.2-6-x86_64.hpkg, pyqt5-5.15.9-1-x86_64.hpkg, pyqt5_python39-5.15.9-1-x86_64.hpkg, pyqtwebengine5_python39-5.15.6-1-x86_64.hpkg,  calibre-5.32.0-6-x86_64.hpkg, openshot-3.1.0-1-any.hpkg, pyqt5_sip_python39-12.12.2-1-x86_64.hpkg, & picard-2.10-1-x86_64.hpkg.

**Comment by Begasus** [comment]
From syslog:
With Cantor installed, crashes, uninstalling it launches again
```
KERN: runtime_loader: Cannot open file libdbus-1.so.3 (needed by /boot/system/lib/libQt5Core.so.5.15.11): No such file or directory
KERN: runtime_loader: Cannot open file libdbus-1 (needed by /boot/system/lib/libQt5Core.so.5.15.11): No such file or directory
KERN: runtime_loader: Cannot open file libdbus-1.so.2 (needed by /boot/system/lib/libQt5Core.so.5.15.11): No such file or directory
KERN: runtime_loader: Cannot open file libdbus-1 (needed by /boot/system/lib/libQt5Core.so.5.15.11): No such file or directory
KERN: runtime_loader: Cannot open file libdbus-1.so (needed by /boot/system/lib/libQt5Core.so.5.15.11): No such file or directory
KERN: runtime_loader: Cannot open file libdbus-1 (needed by /boot/system/lib/libQt5Core.so.5.15.11): No such file or directory
KERN: package_daemon: [137107015:  1718] CommitTransactionHandler::_ChangePackageActivation(): activating 0, deactivating 1 packages
KERN: unknown: [137108376:  1718] Volume::_ChangeActivation(): 0 new packages, 1 old packages
KERN: unknown: [137111998:  1718] package "cantor-23.08.4-1-x86_64.hpkg" deactivated
KERN: package_daemon: [137608538:  1718] Volume::_PackagesEntryRemoved("cantor-23.08.4-1-x86_64.hpkg")
KERN: runtime_loader: Cannot open file libdbus-1.so.3 (needed by /boot/system/lib/libQt5Core.so.5.15.11): No such file or directory
KERN: runtime_loader: Cannot open file libdbus-1 (needed by /boot/system/lib/libQt5Core.so.5.15.11): No such file or directory
KERN: runtime_loader: Cannot open file libdbus-1.so.2 (needed by /boot/system/lib/libQt5Core.so.5.15.11): No such file or directory
KERN: runtime_loader: Cannot open file libdbus-1 (needed by /boot/system/lib/libQt5Core.so.5.15.11): No such file or directory
KERN: runtime_loader: Cannot open file libdbus-1.so (needed by /boot/system/lib/libQt5Core.so.5.15.11): No such file or directory
KERN: runtime_loader: Cannot open file libdbus-1 (needed by /boot/system/lib/libQt5Core.so.5.15.11): No such file or directory
KERN: package_daemon: [331061332:  1718] CommitTransactionHandler::_ChangePackageActivation(): activating 1, deactivating 0 packages
KERN: unknown: [331062257:  1718] Volume::_ChangeActivation(): 1 new packages, 0 old packages
KERN: unknown: [331069138:  1718] package "dbus-1.12.20-6-x86_64.hpkg" activated
KERN: package_daemon: [331485889:  1718] Volume::_PackagesEntryCreated("dbus-1.12.20-6-x86_64.hpkg")
KERN: register_domain(9, unix)
```
Installed dbus because of the mentioned warning (didn't make any change, so probably not relavent).

**Comment by threedeyes** [comment]
> With Cantor installed, crashes, uninstalling it launches again

This is a known problem of file shading. Files from the cantor package shade files in the /data/mime folder. To fix this problem in the cantor recipe, do the same thing as in the calligra recipe:

https://github.com/haikuports/haikuports/blob/master/app-office/calligra/calligra-3.2.1.recipe#L283

**Comment by Begasus** [comment]
Thanks @threedeyes ! Seemed like akonadi/akonadi_mime and kmymoney were putting those files in there too, fix comming up.

**Comment by Begasus** [comment]
@ArDrakho The issue with Cantor and KMyMoney and Ark should be fixed (checked on a few installs), can this be closed or do you still have an error there?

**Comment by Begasus** [comment]
Fixed, kudos to @threedeyes !
