### ISSUE TITLE
Web crashes after recent updates

### ISSUE THREAD

**Issue by ArDrakho** [haikuports/haikuports#9844]
When I attempt to start Web, it crashes in both laptop and PC environments.

See attached crash reports:
[Web-1087-debug-07-12-2023-04-31-47.report.txt](https://github.com/haikuports/haikuports/files/13595649/Web-1087-debug-07-12-2023-04-31-47.report.txt)
[Web-1241-debug-05-12-2023-21-38-23.report.txt](https://github.com/haikuports/haikuports/files/13595651/Web-1241-debug-05-12-2023-21-38-23.report.txt)

This occurred after recent updates.

**Comment by Begasus** [comment]
Fixed, thanks for reporting!
