### ISSUE TITLE
RawTherapee crashes on startup...

### ISSUE THREAD

**Issue by ArDrakho** [haikuports/haikuports#9845]
When I attempt to start RawTherapee, it crashes sometime after and presents a crashed window.

I attached two crash reports from each impacted emvironment: laptop and PC>

[RawTherapee-1162-debug-07-12-2023-04-32-50.report.txt](https://github.com/haikuports/haikuports/files/13595686/RawTherapee-1162-debug-07-12-2023-04-32-50.report.txt)
[RawTherapee-2715-debug-05-12-2023-21-16-20.report.txt](https://github.com/haikuports/haikuports/files/13595687/RawTherapee-2715-debug-05-12-2023-21-16-20.report.txt)

**Comment by ArDrakho** [comment]
Here's another crash report: 
[RawTherapee-37572-debug-07-12-2023-15-04-16.report.txt](https://github.com/haikuports/haikuports/files/13601807/RawTherapee-37572-debug-07-12-2023-15-04-16.report.txt)

Hopefully it contains a clue to what is going on.

**Comment by Begasus** [comment]
Seems others (GTK) are broken also, following the advise from the forum:
```
In Terminal:
rm -rf /boot/system/non-packaged/data/mime
rm -rf /boot/home/config/non-packaged/data/mime
pkgman ins librsvg
/boot/system/boot/post-install/update_loaders_cache.sh
```
Checked with Web, Geany, Bluefish and RawTherapee, adding crash reports for these.
[Web-116633-debug-16-01-2024-11-50-31.report.txt](https://github.com/haikuports/haikuports/files/13949533/Web-116633-debug-16-01-2024-11-50-31.report.txt)
[RawTherapee-117541-debug-16-01-2024-11-57-41.report.txt](https://github.com/haikuports/haikuports/files/13949534/RawTherapee-117541-debug-16-01-2024-11-57-41.report.txt)
[Geany-117495-debug-16-01-2024-11-57-11.report.txt](https://github.com/haikuports/haikuports/files/13949535/Geany-117495-debug-16-01-2024-11-57-11.report.txt)
[BlueFish-116583-debug-16-01-2024-11-50-05.report.txt](https://github.com/haikuports/haikuports/files/13949541/BlueFish-116583-debug-16-01-2024-11-50-05.report.txt)

**Comment by Begasus** [comment]
RawTherapee issue resolved.
