### ISSUE TITLE
Okular cannot open a previously saved PDF

### ISSUE THREAD

**Issue by ArDrakho** [haikuports/haikuports#9854]
Okular no longer is able to open PDFs that it saved previously. 
They open with no issues on BePDF.

From the Terminal:

~> Okular ~/oil_color_chart.pdf
kf.windowsystem: Could not find any platform plugin
Kill Thread

![Okular error on opening a previouos saved pdf-20231206](https://github.com/haikuports/haikuports/assets/48101100/2de89a31-e6e8-473a-b30d-180603a6c65e)

**Comment by Begasus** [comment]
Fixed.
