### ISSUE TITLE
qt5webengine: Web Payments API support

### ISSUE THREAD

**Issue by kenmays** [haikuports/haikuports#9864]
[Web Payments](https://web.dev/articles/empowering-payment-apps-with-web-payments#what_is_web_payments) brings to the web a browser's built-in interface that allows users to enter required payment information easier than ever before.

" Caution: Payment Handler API is only supported in Chrome as of January 2023. However, since Chromium based browsers already have the implementation, some of them may expose the API in the future." - [Web-based payment apps overview | Articles | web.dev](https://web.dev/articles/web-based-payment-apps-overview)

Web Payments
[Payment Request API 1.1 (w3c.github.io)](https://w3c.github.io/payment-request/)
Ref: [How Payment Request API works | Articles | web.dev](https://web.dev/articles/how-payment-request-api-works)

Chrome >= 78, 119 (Android)
Safari >= 12.2 (IOS)

**Comment by korli** [comment]
How is this related to HaikuPorts?

**Comment by kenmays** [comment]
This feature didn't seem working - possibly an oversight in the build. Closing for now.
