### ISSUE TITLE
qemu: TCG accelerator on Haiku host is much slower than on FreeBSD, Linux

### ISSUE THREAD

**Issue by olegkapitonov** [haikuports/haikuports#9868]
I ran the same QEMU VM in TCG mode on Haiku, Linux, and FreeBSD hosts. QEMU is at least 3-4 times slower on the Haiku host! 

I disabled hardware acceleration (KVM) when running QEMU on Linux and compared the TCG accelerator in all cases.
Of course, in Linux with KVM enabled, QEMU is much faster than in Haiku with TCG. But the problem is that the TCG mode (!) in Haiku is much slower than the TCG mode in Linux or FreeBSD. 

By the way, Dosbox works very well on the same machines as the Haiku host. It's much faster than QEMU + FreeDOS on Haiku host - which is very strange, definitely not normal.

What could be the reason for this?

**Comment by waddlesplash** [comment]
Are you comparing exactly identical QEMU versions, command lines, VMs?

**Comment by olegkapitonov** [comment]
Yes, I am comparing the same version of QEMU 8.1.3 on Haiku and on Linux.
I did some more research and found that the problem is most likely that when QEMU is running, the processor clock speed does not rise above 50% of the maximum. On Linux, when the same virtual machine is running, it is 100% of the maximum.

It seems that the problem is with the Haiku's processor frequency control.

**Comment by waddlesplash** [comment]
You can try disabling the CPU idle kernel modules and see if that makes a difference.

**Comment by olegkapitonov** [comment]
I disabled intel_pstate and intel_cstate modules, without them QEMU works normal.

**Comment by waddlesplash** [comment]
Well, then this might be a bug in one of them, or in Haiku's setting of CPU idle states.

**Comment by olegkapitonov** [comment]
This is obviously not a QEMU port bug, so I'm closing this issue
