### ISSUE TITLE
Audacity and Tenacity crash when trying to open the Open dialog

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuports#9889]
With the fix to the portmidi recipe both packages can't be installed: 

`requires "lib:libportmidi_x86 >= 2.0.4" of package "tenacity_x86-1.3.2-1" could not be resolved`

On checking a rebuild I saw that both crash when trying to open the Open dialog window. Running from Terminal doesn't show any output, not even with LD_PRELOAD.

```
~> LD_PRELOAD=libroot_debug.so Tenacity 
Kill Thread
```

**Comment by Begasus** [comment]
Also checked the package currently in the depot and a reverted package for portmidi, same behaviour.

**Comment by davidkaroly** [comment]
awww that looks bad... i'll try to take a look at it

**Comment by davidkaroly** [comment]
audacity seems to work for me after rebuilding it
quick test with some basic operations: startup, open mp3 file, cut&paste, apply fade in / fade out effect - seems to work fine.

**Comment by Begasus** [comment]
Thanks for checking! I'll revbump both then to clear the reports :)
