### ISSUE TITLE
Create a recipe for SystemManager

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuports#9925]
https://github.com/X547/HaikuUtils/tree/master/SystemManager

**Comment by Begasus** [comment]
What version should this have? @X547 in the rdef file it's still listed as 0.0.0, maybe 0.0.1?

**Comment by Begasus** [comment]
PR created, build checked on 32bit and 64bit: https://github.com/haikuports/haikuports/pull/9926

**Comment by X547** [comment]
I expect version will be `echo "r$(git rev-list --count master)"`.

**Comment by Begasus** [comment]
Fix merged upstream, merged here in: https://github.com/haikuports/haikuports/pull/9926
